### ISSUE TITLE
Unknown host 'android.oa.com'. 

### ISSUE THREAD

**Issue by Rogero0o** [Tencent/tinker#1]
Is that for public ? Or need some proxy settings ? Anything will help , Thx.

**Comment by StudyLifeTime** [comment]
Yes,It`s Public! You can use it,if you find problems,welcome to ask for us.

**Comment by AlanCheen** [comment]
怎么解决？ 我也遇到了~

**Comment by Rogero0o** [comment]
Sorry , actually i mean that i got error "Gradle sync failed: Unknown host 'android.oa.com'." when i try to import the project . How to solve this ?

**Comment by SHAU-LOK** [comment]
```
gradle/wrapper/gradle-wrapper.properties下：
```
distributionUrl=http://android.oa.com/gradle/gradle-2.11-all.zip
改成distributionUrl=https\://services.gradle.org/distributions/gradle-2.11-all.zip

>可以解决

**Comment by tomystang** [comment]
@Rogero0o 
That URL is our internal AOSP mirror site. The fixed version of gradle-wrapper.properties is pushed, you can pull master branch to fix this issue. Really sorry about this.

**Comment by AlanCheen** [comment]
发现了  ~
