### ISSUE TITLE
TinkerUncaughtHandler类中ueh.uncaughtException(thread, ex);这段代码是不是bug

### ISSUE THREAD

**Issue by bwcxjason** [Tencent/tinker#1000]
public void uncaughtException(Thread thread, Throwable ex) {
        Log.e(TAG, "TinkerUncaughtHandler catch exception:" + Log.getStackTraceString(ex));
        ueh.uncaughtException(thread, ex); // 这段代码重复调用自己，是何用意，是Bug吧？？？？

        if (crashFile != null) {
            Thread.UncaughtExceptionHandler handler = Thread.getDefaultUncaughtExceptionHandler();

            //only catch real uncaught Exception
            if (handler instanceof TinkerUncaughtHandler) {
                File parentFile = crashFile.getParentFile();
                if (!parentFile.exists() && !parentFile.mkdirs()) {
                    Log.e(TAG, "print crash file error: create directory fail!");
                    return;
                }
                PrintWriter pw = null;
                try {
                    pw = new PrintWriter(new FileWriter(crashFile, false));
                    pw.println("process:" + ShareTinkerInternals.getProcessName(this.context));
                    pw.println(ShareTinkerInternals.getExceptionCauseString(ex));
                } catch (IOException e) {
                    //ignore
                    Log.e(TAG, "print crash file error:" + Log.getStackTraceString(e));
                } finally {
                    SharePatchFileUtil.closeQuietly(pw);
                }
                android.os.Process.killProcess(android.os.Process.myPid());
            }
        }
    }

**Comment by tomystang** [comment]
ueh是系统默认的exception handler，不是自己。
不过这里确实改坏了，下面的打crash文件的逻辑跑不到，下个版本统一修一下才行。
