### ISSUE TITLE
对resources.arsc做patch时，可以新建一个resources.arsc，只供R文件中为0x71开头的资源进行读取吗

### ISSUE THREAD

**Issue by FnAndroid** [Tencent/tinker#1009]
这样做的目的，是想只对apk的部分values进行更新，而不更新全部values。

如：
```
    <string name="app_name">tinker-sample-android</string>
    <string name="test_resource">game</string>
```
计算差异包时，检查出app_name和test_resource"都有修改，但是只想让test_resource的修改生效，而忽略app_name的修改。

因为一些业务场景，需要实现上述功能。大佬们能帮忙给一些实现思路吗？

群已满，只能借助issure请教，望谅解。

**Comment by FnAndroid** [comment]
我现在实现的办法是，给assetmanager多次addAssetPath，能在android 6.0和8.0上自测OK，但是由于mResDir只能设置一个resdir，不能同时设置两个assetpath，不知道会不会有什么坑？

**Comment by tomystang** [comment]
其实这个思路是ok的，参考[阿里的patch方案](https://yq.aliyun.com/articles/102404)。你要patch上去的新资源和没变化的资源使用不同的id前缀就可以了。
