### ISSUE TITLE
打补丁后，文件没有被删除

### ISSUE THREAD

**Issue by wonghoman** [Tencent/tinker#101]
我用这上面的demo打补丁的时候，调用TinkerInstaller.onReceiveUpgradePatch打补丁，补丁成功后会自动删除目录的补丁文件，但我接入到我的项目后，补丁成功后并没有自动删除目录的补丁文件，这是为什么呢？

**Comment by shwenzhang** [comment]
要看你的TinkerResultService的实现，这个自己看代码把

**Comment by wonghoman** [comment]
@shwenzhang 我的TinkerResultService直接是用demo的那个SampleResultService类的，没有修改过，按道理应该会删除才对的啊？
