### ISSUE TITLE
大神请教下调试技巧之“dump了栈顶附近几个方法的机器码”是如何操作的？

### ISSUE THREAD

**Issue by jtaizlx** [Tencent/tinker#1011]
大神请教下调试技巧

1.如何调试，比如：“dump了栈顶附近几个方法的机器码”
2.release的apk如何进行调试和定位问题？

**Comment by tomystang** [comment]
1. dump机器码是用oatdump做的，可以在adb shell里直接输`oatdump --help`看下帮助。dump release apk需要root过的机器，我一般是直接用工程机或者编个eng版的ROM刷进Nexus或者Pixel系列机器里搞定的。

2. 调试release的apk……一般如果不涉及classloader或者更底层的vm逻辑的问题，我比较习惯用xposed或者magisk hook住感兴趣的方法打log，比用开了ro.debuggable的机器断进去调要方便。另外其实framework和虚拟机都是可以调试的，编个工程ROM，得到相关so和可执行文件的调试符号就可以了。遇到更底层的问题xposed和magisk会破坏环境，就只能这么查了。
