### ISSUE TITLE
如何在我的设备上禁用Tinker？

### ISSUE THREAD

**Issue by kcschan** [Tencent/tinker#1019]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：非异常

手机型号：与设备无关

手机系统版本：与具体系统无关

tinker版本：1.9.11

gradle版本：无关

是否使用热更新SDK： 无关

系统：无关

堆栈/日志：
不涉及

具体描述：
当我安装了一个使用了Tinker组件的应用时，作为用户，如何确保它像Google play渠道的应用那样停止工作？

是否反注册com.tencent.tinker.lib.service包下的全部Serivice就足以达到这个目的？

**Comment by tuzhao** [comment]
apk打包的时候针对GooglePlay的渠道单独处理,将tinker相关的依赖不打包进入apk即可。

**Comment by xingda920813** [comment]
@tomystang 

当我安装了一个使用了Tinker组件的应用时，作为用户，如何确保它像Google play渠道的应用那样停止工作？

是否反注册com.tencent.tinker.lib.service包下的全部Serivice就足以达到这个目的？

@tuzhao 

没有回答问题.

**Comment by tuzhao** [comment]
楼主可以去看下gradle如何分渠道控制依赖，同时还可以看下如何分chann代码。
