### ISSUE TITLE
Tinker.with(getApplicationContext()).cleanPatch();

### ISSUE THREAD

**Issue by wonghoman** [Tencent/tinker#102]
请问大神，cleanPatch()这个方法应该在什么时候调用的？是在同一个版本的每次打补丁前调用，还是在更新版本后调用？还是其它的情况？

**Comment by shwenzhang** [comment]
一般情况下，上面几种情况都不需要显示调用。一般只在出现异常才会去调用

**Comment by wonghoman** [comment]
@shwenzhang 那我的代码只需要每次下载补丁文件后直接调用TinkerInstaller.onReceiveUpgradePatch就行了？如果发布新版本呢？tinker会删除补丁吗？还是我要自己处理？

**Comment by wonghoman** [comment]
@shwenzhang hi,上面的问题，大神有答案吗？

**Comment by shwenzhang** [comment]
会自动处理的

**Comment by wonghoman** [comment]
@shwenzhang 那我的代码只需要每次下载补丁文件后直接调用TinkerInstaller.onReceiveUpgradePatch就行了？

**Comment by wonghoman** [comment]
@shwenzhang hi，那我的代码只需要每次下载补丁文件后直接调用TinkerInstaller.onReceiveUpgradePatch就行了？

**Comment by wonghoman** [comment]
@shwenzhang hi大神，那我的代码只需要每次下载补丁文件后直接调用TinkerInstaller.onReceiveUpgradePatch就行了？
