### ISSUE TITLE
执行java -jar tinker-patch-lib-1.9.11.jar提示Error: Could not find or load main class com.tencent.tinker.patch.CliMain

### ISSUE THREAD

**Issue by XHelloCode** [Tencent/tinker#1026]
我下载的是1.9.11版本最新的代码，用BuildTinkerSDK编译出来打补丁包的工具，然后使用命令方式生成补丁包，提示错误 Error: Could not find or load main class com.tencent.tinker.patch.CliMain，后面查了tinker-patch-cli-1.9.11.jar包发现只有5.04k，是不是需要配置些什么？？
merge_mapping.py
proguard_warning.py
release.keystore
tinker-patch-cli-1.9.11.jar
tinker_config.xml
tinker_multidexkeep.pro
tinker_proguard.pro

**Comment by tomystang** [comment]
已fix，可以用1.9.12尝试一下，Android运行时部分和1.9.11是一样的。

**Comment by XHelloCode** [comment]
好的
