### ISSUE TITLE
补丁包有多余东西

### ISSUE THREAD

**Issue by ifinver** [Tencent/tinker#103]
只修改了一个Activity的一行代码:
```
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.live_activity_debug);
        ButterKnife.bind(this);

//        tvShow.setText("without patch");
        tvShow.setText("patch applied!");

        btnLoadPatch.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(), Environment.getExternalStorageDirectory().getAbsolutePath() + "/patch_signed_7zip.apk");
            }
        });
    }
```
选择raw方式，tinkerPatchDebug编出来的patch_signed.apk大小为1.25M
解压发现里面有个res文件夹占了1.20M
![image](https://cloud.githubusercontent.com/assets/12935415/19212186/0b2fd8ca-8d7f-11e6-86c6-5a0bbbcbd8bf.png)
![image](https://cloud.githubusercontent.com/assets/12935415/19212187/1340dafa-8d7f-11e6-9451-f794327ef911.png)
![image](https://cloud.githubusercontent.com/assets/12935415/19212193/32983236-8d7f-11e6-9a33-936643d38369.png)
这些图标均与被修改的Activity无关联。
出现的图标大部分是v4和v7包里的，少量的是我们项目自己的和v11包里，需要做什么配置吗？
多谢~

**Comment by shwenzhang** [comment]
两个apk看看为什么这些资源改变了

**Comment by icespring** [comment]
遇到同样的问题，在试用demo的时候，也填写了ResouceMapping文件，但是却多出来了这么多

**Comment by dodola** [comment]
@icespring 这个问题不是tinker造成的，如果直接使用Android Studio Run出来的apk 和assembleDebug&assembleRelease 的包做对比是会出现这些资源的，请使用Gradle 的assemble***的命令生成出来的包作为原始apk就可以了

**Comment by ifinver** [comment]
@dodola 原来是这样，多谢~
刚刚同样的改动，用assemnle**测试，raw模式的丁包只有3.75K

**Comment by icespring** [comment]
@dodola 非常感谢

**Comment by HunanDj** [comment]
@dodola 你好，我也遇到了这个问题，然后按照你的说法:用命令行assembleDebug生成
原始apk，的确OK了。
但是随后我clean了一下project(原始apk依旧保留）
这时候再生成补丁包，发现又出现了上述问题
请问有遇到吗？如果有，可以解决吗？
