### ISSUE TITLE
Tinker1.7.7编译异常

### ISSUE THREAD

**Issue by August1993** [Tencent/tinker#1049]
异常类型：编译异常
tinker版本：1.7.7
gradle版本：2.3.1
是否使用热更新SDK： TinkerPatch SDK
系统：win7
问题描述: 今天在使用TInker打包项目时,打开项目直接编译异常,并报异常"Error:Failed to resolve: com.tencent.tinker:tinker-android-anno:1.7.7"
Error:Failed to resolve: com.tencent.tinker:tinker-android-lib:1.7.7
 测试其他Tinker项目均存在这种问题. 是不是TInker关闭了该版本的服务呢

**Comment by eterrao** [comment]
我刚才也遇到了, 估计是 jcenter 的锅, 又给下架了吧?
相关问题 
#1048 Tinker Could not resolve com.tencent.tinker:tinker-android-anno:1.9.x
#556 tinker获取不到了
