### ISSUE TITLE
Could not resolve com.tencent.tinker:tinker-android-lib:1.9.8

### ISSUE THREAD

**Issue by lxy228** [Tencent/tinker#1050]
Could not resolve com.tencent.tinker:tinker-android-lib:1.9.8.
    > Could not get resource 'https://jcenter.bintray.com/com/tencent/tinker/tinker-android-lib/1.9.8/tinker-android-lib-1.9.8.pom'.
          > Could not HEAD 'https://jcenter.bintray.com/com/tencent/tinker/tinker-android-lib/1.9.8/tinker-android-lib-1.9.8.pom'. Received status code 502 from server: Bad Gateway
[上午好好的，下午就编译不过了

**Comment by awdvhil9** [comment]
同样的问题
