### ISSUE TITLE
tinker所有类都在classes2.dex中

### ISSUE THREAD

**Issue by ibabyting** [Tencent/tinker#1058]
异常类型：app编译异常

minSdkVersion : 22

tinker-patch-gradle-plugin版本：1.9.9

tinker版本：1.9.9

gradle版本：如:2.3.0

是否使用热更新SDK： 无

系统：Windows

在实验多次后发现，当minSdkVersion>=21，minifyEnabled=true时，编译后的apk中，tinker.loader包下的类都在classes2.dex中，因而tinkerpatch无法生成，若将minifyEnabled设为false则正常在mian dex中，麻烦tinker们能看一下，万分感谢

**Comment by xLyong** [comment]
+1

**Comment by ibabyting** [comment]
我将ignoreWarning设为true了，编的补丁包能正常使用，我猜测当sdkVersion>=21时，由于aot机制会将所有dex文件合并成ota文件，loader类在classes2.dex中也没关系，不知道是不是这样

**Comment by xLyong** [comment]
@ibabyting 找到解决办法了么？

**Comment by ibabyting** [comment]
我把ignoreWarning设为true了

**Comment by Qiang11** [comment]
看官方说ignoreWarning为true会导致编译的patch包有风险    老哥你这么做测试过没

**Comment by ibabyting** [comment]
> 看官方说ignoreWarning为true会导致编译的patch包有风险 老哥你这么做测试过没

我测试过android 5.0 5.1 6.0 7.0 8.0 9.0的系统，公司测试组也做过补丁发布及应用测试，已经上线了，应该没啥问题，兄弟你要是碰到问题了记得提醒下
