### ISSUE TITLE
请问下打补丁的逻辑是怎样的？

### ISSUE THREAD

**Issue by wonghoman** [Tencent/tinker#106]
是不是只需要下载补丁文件后直接调用TinkerInstaller.onReceiveUpgradePatch就行了？每次都是这个逻辑对吧？

**Comment by sisel** [comment]
这个我也有疑问，文档里面讲的不是很清楚：
1.onReceiveUpgradePatch和onReceiveRepairPatch的处理有什么区别呢？
2.多次对同一底包（同一tinkerID）打补丁，会产生怎样的行为？覆盖？叠加？如果补丁之间产生冲突会怎样？

**Comment by shwenzhang** [comment]
试一下就知道了，onReceiveRepairPatch这个接口其实大家不会主动去调用的

**Comment by shishuo365** [comment]
#464 issue464 提供了一份流程图，可以作为参考。
