### ISSUE TITLE
tryLoadPatchFiles:patch dir not exist

### ISSUE THREAD

**Issue by Drizzlezhang** [Tencent/tinker#109]
>W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.sample/tinker
I/Tinker.SamplePatchListener: application maxMemory:256
W/Tinker.Tinker: tinker patch directory: /data/user/0/com.sample/tinker
I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/com.sample/tinker, code:-2, cost:2
W/Tinker.Tinker: tinker load fail!
W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:5393
I/Tinker.SamplePatchListener: get platform:all
I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-10, isUpgrade:true

加载补丁的时候报了这个错。之前有个issue提过这个问题，但是他在更新1.6.2后解决掉了。我这边一直没有解决。加载时用Tinker过滤的log是这些。生成patch的log.txt看起来也没有问题。

**Comment by Drizzlezhang** [comment]
生成patch的log
> -----------------------Tinker patch begin-----------------------
configuration: 
oldApk:/Users/drizzle/develop/JavaScript/sample/application/build/bakApk/application-debug-1010-12-10-25.apk
newApk:/Users/drizzle/develop/JavaScript/sample/application/build/outputs/apk/application-dev-debug.apk
outputFolder:/Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug
isIgnoreWarning:false
7-ZipPath:/Users/drizzle/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:platform, filed value:all
dex configs: 
dexMode: jar
dexPattern:assets/secondary-dex-.\.jar
dexPattern:classes.*\.dex
dex loader:com.sample.utils.BaseApplication
dex loader:com.tencent.tinker.loader.*
lib configs: 
libPattern:lib/armeabi/.*\.so
resource configs: 
resPattern:resources\.arsc
resPattern:assets/.*
resPattern:res/.*
resPattern:AndroidManifest\.xml
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: application-debug-1010-12-10-25.apk, size=8458016, md5=82ff7034c7da7be0d10ccc6e12acd38c
new apk: application-dev-debug.apk, size=8457992, md5=4bb8a84ee53e331a83120532cf6f03bb
UnZipping apk to /Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/application-debug-1010-12-10-25
UnZipping apk to /Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/application-dev-debug
Check for loader classes in dex: ../application-debug-1010-12-10-25/classes.dex
Check for loader classes in dex: ../application-debug-1010-12-10-25/classes2.dex

Gen classes.dex patch file:/Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/tinker_result/classes.dex, size:2078, md5:6f12a2cb56bc66092e7e80812f1e72b5
Verifying if patched new dex is logically the same as original new dex: application-dev-debug/classes.dex ...

Gen classes.dex for dalvik full dex file:/Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/tempPatchedDexes/full/classes.dex, size:9475584, md5:dcaef35083660d0cd2a7022fa434fddf
Start generating small patch info file...

Gen classes.dex for art small dex file:/Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/tempPatchedDexes/small/classes.dex, size:21356, md5:4e3a06d1644b55a1f7ce658df700eee7
DexDecoder:write meta file data: classes.dex,,dcaef35083660d0cd2a7022fa434fddf,4e3a06d1644b55a1f7ce658df700eee7,6f12a2cb56bc66092e7e80812f1e72b5,1754979038,jar

Add test install result dex: /Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:/Users/drizzle/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
Result: final signed patch result: /Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/patch_signed.apk, size=5039
Result: final signed with 7zip patch result: /Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug/patch_signed_7zip.apk, size=5393
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 354 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 10.235000s
Tinker patch done, you can go to file to find the output /Users/drizzle/develop/JavaScript/sample/application/build/outputs/tinkerPatch/dev/debug
-----------------------Tinker patch end-------------------------

**Comment by shwenzhang** [comment]
code -10不是写的很清楚
