### ISSUE TITLE
关于Unity的问题

### ISSUE THREAD

**Issue by YangZixuanKim** [Tencent/tinker#1090]
```
异常类型：app运行时异常/编译异常

手机型号：如:VivoX23(如是编译异常，则可以不填)

手机系统版本：如:Android 8.0 (如是编译异常，则可以不填)

tinker版本：如:1.9.13

gradle版本：如:2.3.3

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：如:Mac

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。

```
请问Tinker可以在Unity或Cocos项目中使用,用来更新assets下的资源或者so库吗？

**Comment by tomystang** [comment]
原理上是可行的，但目前我还没实际使用Unity或者Cocos大规模测试过。

**Comment by YangZixuanKim** [comment]
在Cocos上我试了下是可以的，但是在unity项目上，资源热更新上有点问题，看日志补丁是合成成功的，但是就是没生效

**Comment by YangZixuanKim** [comment]
请问对可更新的资源类别有要求吗？

**Comment by YangZixuanKim** [comment]
> 原理上是可行的，但目前我还没实际使用Unity或者Cocos大规模测试过。
请问对可更新的资源类别有要求吗？在Cocos上我试了下是可以的，但是在unity项目上，资源热更新上有点问题，看日志补丁是合成成功的，但是运行时看日志没发生变化

**Comment by tomystang** [comment]
其实就是看引入的sdk有没有自己的资源解压、创建AssetManager的行为，tinker本身也是靠创建一个新assetmanager来让资源patch生效的，如果其他sdk也有类似的行为，tinker的这个assetmanager就会被覆盖掉。

**Comment by YangZixuanKim** [comment]
> 其实就是看引入的sdk有没有自己的资源解压、创建AssetManager的行为，tinker本身也是靠创建一个新assetmanager来让资源patch生效的，如果其他sdk也有类似的行为，tinker的这个assetmanager就会被覆盖掉。
噢噢，好，我再好好看看，谢谢

**Comment by YangZixuanKim** [comment]
> 其实就是看引入的sdk有没有自己的资源解压、创建AssetManager的行为，tinker本身也是靠创建一个新assetmanager来让资源patch生效的，如果其他sdk也有类似的行为，tinker的这个assetmanager就会被覆盖掉。

那是不是说，如果真的是这个原因的话，我只要想办法将tinker的assetManager覆盖掉其他的就好了

**Comment by YangZixuanKim** [comment]
> > 其实就是看引入的sdk有没有自己的资源解压、创建AssetManager的行为，tinker本身也是靠创建一个新assetmanager来让资源patch生效的，如果其他sdk也有类似的行为，tinker的这个assetmanager就会被覆盖掉。
> 
> 那是不是说，如果真的是这个原因的话，我只要想办法将tinker的assetManager覆盖掉其他的就好了

**Comment by YangZixuanKim** [comment]
> 其实就是看引入的sdk有没有自己的资源解压、创建AssetManager的行为，tinker本身也是靠创建一个新assetmanager来让资源patch生效的，如果其他sdk也有类似的行为，tinker的这个assetmanager就会被覆盖掉。
 如果真的是这种情况有没有可能通过自定义的TinkerLoader来解决呢？
