### ISSUE TITLE
bsdiff 导致 java OOM

### ISSUE THREAD

**Issue by 9527se** [Tencent/tinker#1097]
异常类型：bsdiff 导致 java OOM

手机型号：360 n7

手机系统版本：Android 8.0

tinker版本：如:1.9.9

gradle版本：如:4.6

是否使用热更新SDK： Bugly SDK

系统：window

日志：
合成失败。日志显示bsdiff stream 操作申请内存 OOM， 原so过大导致无法合并。原so 260mb，只有一代码修改，但是因为OOM 导致无法so 更新，是否能提供一个开关，不使用bsdiff 增量更新so，直接下载so后使用新so。

**Comment by tomystang** [comment]
额，260M的so放进补丁里直接下载……感觉有点吓人哇，还不如直接发全量包了。
后面我改一下bsdiff的参数让它不要使用读取整个旧文件到内存中的模式吧。

**Comment by 9527se** [comment]
好的，调整了麻烦通知下我。希望有参数可以控制所有更新都能不使用增量更新， 直接使用新的就好了。合并过程在一些低端机器上卡顿非常厉害。

**Comment by 9527se** [comment]
哪个版本会升级这个功能？

> 额，260M的so放进补丁里直接下载……感觉有点吓人哇，还不如直接发全量包了。
> 后面我改一下bsdiff的参数让它不要使用读取整个旧文件到内存中的模式吧。

哪个版本会升级这个功能。

**Comment by tomystang** [comment]
1.9.14会改的

**Comment by 9527se** [comment]
> ~1.9.14会改的~
> 
> 刚才我发现一个问题，bspatch算法要求能在旧文件数据中随机访问，因此只能一次读完旧文件，或者提供一个打开了旧文件的RandomAccessFile。后者要求先把旧文件从base包中解压出来，在旧文件比较大的时候代价可能有点高，下个版本暂时还是先不改哈。

那至少能提供一个开关关闭so合并操作。直接使用下载的so。因为我们so被7z压缩很小 50mb。

**Comment by 9527se** [comment]
> ~1.9.14会改的~
> 
> 刚才我发现一个问题，bspatch算法要求能在旧文件数据中随机访问，因此只能一次读完旧文件，或者提供一个打开了旧文件的RandomAccessFile。后者要求先把旧文件从base包中解压出来，在旧文件比较大的时候代价可能有点高，下个版本暂时还是先不改哈。

打开了旧文件的RandomAccessFile这种方式，能不能提供一下代码修改例子。具体在哪里文件哪个位置加比较好。
