### ISSUE TITLE
请教 导入Sample Error:(19, 0) CreateProcess error=2, 系统找不到指定的文件。

### ISSUE THREAD

**Issue by LuoboDcom** [Tencent/tinker#11]
我是单独IDE窗口导入Simple ,报如下错误。如图：
![image](https://cloud.githubusercontent.com/assets/7316013/18815110/2c7b00e8-8359-11e6-9280-9fccbad4405c.png)

**Comment by llmsparkbbbboy** [comment]
修改classpath -->  classpath 'com.android.tools.build:gradle:2.1.0'

**Comment by LuoboDcom** [comment]
@llmsparkbbbboy  我的gradle已经是2.1.0了

**Comment by shwenzhang** [comment]
没有安装git，你可以换成其他的tinkerid生成方法。

**Comment by LuoboDcom** [comment]
有git,是我配置错了吗？
![image](https://cloud.githubusercontent.com/assets/7316013/18815284/f7c20342-835d-11e6-8c03-ee3ac83238b6.png)
![image](https://cloud.githubusercontent.com/assets/7316013/18815285/058de2c0-835e-11e6-8cd5-bd91e9725698.png)

**Comment by shwenzhang** [comment]
要添加到系统变量

**Comment by dodola** [comment]
@LuoboDcom 重新装个 https://git-scm.com/download/win 这个试试

**Comment by LuoboDcom** [comment]
@shwenzhang  @dodola 是的，我没配置到系统变量去。谢谢大神的帮助！

**Comment by memorycj** [comment]
你好，我在导入tinker-sample-android的时候，构建总会出现
![image](https://cloud.githubusercontent.com/assets/16283516/18821287/74053c7a-83d7-11e6-927a-3d73f573b2ef.png),注释掉app.gradle中的
![image](https://cloud.githubusercontent.com/assets/16283516/18821311/a47c1e6e-83d7-11e6-914d-8421f128d36b.png)这段代码后就不会出现这样的错误，但是后面在run的时候又会出现这个，
![image](https://cloud.githubusercontent.com/assets/16283516/18821343/c91f7af4-83d7-11e6-97b9-3ca156ff0934.png)

**Comment by dodola** [comment]
@memorycj  第一个出现assembleDebug的情况你拿一下最新的代码试一下，看看还有没有这个问题

**Comment by memorycj** [comment]
@dodola 用了最新的代码，已经不会出现第一个问题了，但是第二个问题依旧，git 配置到环境变量里面了..

**Comment by dodola** [comment]
@memorycj 你是不是把配置里的tinkerid项给注释掉了。。

**Comment by memorycj** [comment]
@dodola 哈哈，没呢，这边的代码我下载都没动过的，
![image](https://cloud.githubusercontent.com/assets/16283516/18821972/684c9d32-83dd-11e6-871c-13b09faa4c57.png)，
![image](https://cloud.githubusercontent.com/assets/16283516/18821981/79700b3a-83dd-11e6-9663-66833c11ab58.png)

**Comment by memorycj** [comment]
@dodola gradle版本不会影响这个吧？因为我这边的gradle版本是2.14.1，这个demo的gradle版本是2.10，我在gradle-wrapper.properties文件里，将gradle版本改为了2.14.1

**Comment by memorycj** [comment]
@shwenzhang 请教，导入demo的时候出现，![image](https://cloud.githubusercontent.com/assets/16283516/18822956/7ed623f2-83e7-11e6-93eb-e23b4752c607.png)，gradle的配置没有改动，打印tinkerId没有值，

**Comment by shwenzhang** [comment]
这个是我们主动抛出的错误，因为TinkerID返回获取不到任何数值，请主动打印一下函数返回值

**Comment by memorycj** [comment]
@shwenzhang tinkerID没有任何数值，什么情况下会导致获取不到呢？

**Comment by shwenzhang** [comment]
gitSha函数的返回值，如果没有使用git管理，可以使用其他的函数例如svn rev

**Comment by memorycj** [comment]
使用的是git进行管理，并且已经配置到环境变量，studio中也进行了相关配置 @shwenzhang

**Comment by 15189611** [comment]
同求·，我也遇到上面的问题了·配置git 系统变量

**Comment by memorycj** [comment]
@15189611 https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by 15189611** [comment]
你是换成其他的字符串的 ？还是调用getSha()这个函数的？

**Comment by memorycj** [comment]
@15189611 我是调用的gitSha()函数，你可以先检查git环境变量是否设置成功，然后还不行的话你可以尝试本地commit一次然后就可以了..

**Comment by 15189611** [comment]
好我试试·

**Comment by 15189611** [comment]
谢谢 我也是commit一次 成功了·

**Comment by ngochuu90** [comment]
I added git environment variable
![capture](https://cloud.githubusercontent.com/assets/9895294/18858987/692182b4-849a-11e6-90e6-38ebcf30265c.PNG)

But still get "TinkerID is not set!!!
Help me.

**Comment by memorycj** [comment]
@ngochuu90 My solution is to use local git to submit a code, you can try the next ...

**Comment by ngochuu90** [comment]
@memorycj:
I have just used Git. Please guide to me use local git. Thanks

**Comment by xialei92** [comment]
@ngochuu90 use git clone rather than download the zip

**Comment by jp1017** [comment]
直接设置值了，哈哈 :smile: 

```
String gitRev = 'v1.7.5'
```

**Comment by luyingchn** [comment]
请教，glide开源项目，导入as，报错Error:CreateProcess error=2, 系统找不到指定的文件。 请问怎么解决

**Comment by jp1017** [comment]
@luyingchn 多半是环境没配置好,如果其他项目没问题,就是gradle配置问题咯

**Comment by Developmc** [comment]
commit一次之后就可以跑起来了

**Comment by chenjiayulove** [comment]
是怎么解决  tinkerId is not set!!!  看不太懂你们上面说的啊 @dodola @memorycj @shwenzhang
