### ISSUE TITLE
同一套代码，打多个渠道包，用一个补丁来解决热更的问题

### ISSUE THREAD

**Issue by victorfan336** [Tencent/tinker#1107]
tinker版本：如:1.9.11

gradle版本：4.10.1

是否使用热更新SDK： 无

系统：win10

您好，我想请问下，如何在一套代码下，打出的多个渠道包能够使用同一个补丁呢？我看了issues里面有提这个的，但是好像并没有给出解决方法。也有提多个渠道不同代码打补丁包的，但是我这个是要求同一套代码，打多个渠道包，用一个补丁来解决热更的问题。
我的代码都是同一套，除了渠道号不一样，其他的都是一致的，但是想通过一个补丁来实现一个版本的所有渠道包热更，请问下有什么解决方法吗？渠道号都是在AndroidManifest.xml中占坑，然后在app的build.gradle中配置的。不然10个渠道，3个版本需要热更的话，就会生成30个补丁包了，不方便管理。
按照官方文档说：**运行tinkerPatchAllFlavorDebug或者tinkerPatchAllFlavorRelease即可得到所有flavor的补丁包。**
但是，不知道为什么我的项目里面并没有wiki文档上说的tinkerPatchAllFlavorDebug或者tinkerPatchAllFlavorRelease命令。
@simpleton @gryamy @junyuecao @dodola @hzlzh 
老版本：
[https://github.com/Tencent/tinker/issues/5](url)
[https://github.com/Tencent/tinker/issues/184](url) 文档看了也还是没找到解决办法啊，大佬。

**Comment by wstczlt** [comment]
渠道包只要dex、资源、so这几个没有差异，那么用一个补丁就行了；关于渠道包怎么打，在tinker的wiki上就有这块的建议，可以翻看一下，https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by victorfan336** [comment]
@wstczlt 感谢回答，看过很多遍了，但是在执行上不太清楚具体哪个地方出现了问题，补丁包能够打出来，但是不同渠道的包无法在其他渠道上的包进行热更。

**Comment by victorfan336** [comment]
解决办法，[https://github.com/Tencent/tinker/issues/12](url)，我是通过这个解决的。里面有解决方法，居然没人赞，我赞了一个，以后就知道了

**Comment by nijian141893** [comment]
> 解决办法，[https://github.com/Tencent/tinker/issues/12](url)，我是通过这个解决的。里面有解决方法，居然没人赞，我赞了一个，以后就知道了

你好这个连接失效了，麻烦再帮发个连接吧。
