### ISSUE TITLE
patch fail，please check reason

### ISSUE THREAD

**Issue by fishsoft** [Tencent/tinker#1115]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：App热更新失败

手机型号：华为荣耀8C

手机系统版本：8.1

tinker版本：1.9.1

gradle版本：3.4.1

是否使用热更新SDK： TinkerPatch SDK

系统：windows

提示patch fail，please check reason
Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.morse.demo/tinker
Tinker.SamplePatchListener: application maxMemory:192
Tinker.Tinker: tinker patch directory: /data/user/0/com.morse.demo/tinker
Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.morse.demo/tinker, code: -2, cost: 3ms
Tinker.Tinker: tinker load fail!
Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

**Comment by tomystang** [comment]
这句log是正常的，因为补丁没有apply完成，所以就会报找不到patch file。可以再多等一段时间看下，如果超过1min还没看到patch成功的消息再把patch进程的log发到这里吧。
