### ISSUE TITLE
热更成功后通知栏布局文件修改不生效

### ISSUE THREAD

**Issue by victorfan336** [Tencent/tinker#1117]
异常类型：app运行时异常
Tinker.SampleUncaughtExHandler: uncaughtException:Bad notification posted from package  Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.xxx.shuo user=UserHandle{0} id=1000 tag=null score=0 key=0|com.xxi.shuo|1000|null|10737: Notification(pri=0 contentView=com.xx.shuo/0x7f0c00bc vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE))
06-03 16:44:35.665 1375-1375/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:android.app.RemoteServiceException: Bad notification posted from package com.xxx.shuo: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.xx.shuo user=UserHandle{0} id=1000 tag=null score=0 key=0|com.xx.shuo|1000|null|10737: Notification(pri=0 contentView=com.xx.shuo/0x7f0c00bc vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE))
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5560)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:965)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
手机型号：如:Nexus 5(如是编译异常，则可以不填)

手机系统版本：都不行

tinker版本：1.9.11

gradle版本：3.3.2

是否使用热更新SDK： 无

系统：如:windows

 合成日志：

SampleResultService receive result: %s
    PatchResult: 
    isSuccess:true
    rawPatchFilePath:/storage/emulated/0/Android/data/comxx.oshuo/cache/patch_signed_7zip.apk
    costTime:1188
    patchVersion:c507d32191571aeb70b7809dc0f85a50
06-03 16:43:39.185 880-1316/? E/DuoYue@tinker: PatchResult: 
    isSuccess:true
    rawPatchFilePath:/storage/emulated/0/Android/data/com.xx.shuo/cache/patch_signed_7zip.apk
    costTime:1188
    patchVersion:c507d32191571aeb70b7809dc0f85a50
tinker: 合并成功, current version : null, result version : c507d32191571aeb70b7809dc0f85a50
06-03 16:43:39.185 880-1316/? E/DuoYue@tinker: 补丁包路径 : /storage/emulated/0/Android/data/com.xx.shuo/cache/patch_signed_7zip.apk

补丁是热更生效了的，因为之前发布的apk报了上面这个错误，是由于通知栏的布局用了自定义View导致。我去掉了通知栏布局里的自定义View后，直接运行是不会报错的，但是热更后，而且热更成功了，还是会报这个错误，是不是热更没有办法修改通知栏布局呀？如果不可以，那有什么办法可以解决修改通知栏布局吗？我这个是用来做版本升级更新的，现在版本都没法升级了。
谢谢了。
@simpleton @gryamy @junyuecao @dodola @hzlzh

**Comment by tomystang** [comment]
是的，通知栏布局属于RemoteView，是无法通过tinker更新的。

**Comment by victorfan336** [comment]
> 是的，通知栏布局属于RemoteView，是无法通过tinker更新的。

好的，感谢回答，已经想了其他解决方案了。
