### ISSUE TITLE
有人遇到用multiDexKeepProguard把loader加入maindex后主dex class数目超过限制的问题么

### ISSUE THREAD

**Issue by shizhy1986** [Tencent/tinker#112]
未添加loader时主dex只有1000多个类，但添加multiDexKeepProguard file把loader放进去后，居然主dex list中的类超过限制，gradle报Too many classes in --main-dex-list, main dex capacity exceeded的错误，loader里也没有多少个类啊，怎么会导致main dex list超过限制呢，gradle有bug？

**Comment by yjf2011** [comment]
不是class的数量太多，而是方法数超过了65535（或者--set-max-idx-number的值），你得看下原来main dex里有多少个方法，用build-tool里的dexdump工具可以查看。
tinker会增加2000+的方法，加上原来的方法可能超了数量限制了

**Comment by shwenzhang** [comment]
see above

**Comment by oncealong** [comment]
同样接入tinker报错，
```
try update tinker multidex keep proguard file with /Users/along/k12/build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
D8: Cannot fit requested classes in the main-dex file (# methods: 73483 > 65536)
```
 没接入tinker之前，查了 maindex方法数65383，然后+tinker的2000，确实爆掉了。请问如何设置才能让main-dex里不要有那么多方法，可以正常接入tinker
```
/Users/along/Library/Android/sdk/build-tools/29.0.2/dexdump -f classes.dex | grep method_ids_size
method_ids_size     : 65383
```
