### ISSUE TITLE
tinker不能集成到module中

### ISSUE THREAD

**Issue by fishsoft** [Tencent/tinker#1123]
如何将tinker集成到module中

**Comment by tomystang** [comment]
额，你是想用Tinker单独更新某个module？
Tinker跟插件化有点不同，接入Tinker的App在Tinker看来就是Dex、So和其他资源的集合，已经失去module这种编译时的划分了，所以Tinker并不能像你希望的那样单独来热更新某个module。Tinker也不支持接入到module里。

**Comment by fishsoft** [comment]
是的。

**Comment by YaoHhuiling** [comment]
可以把合并补丁的操作放在某个module中，生成补丁的放在主模块中吗？
