### ISSUE TITLE
1.9.13.1 依赖失败

### ISSUE THREAD

**Issue by yanweimin7** [Tencent/tinker#1125]
看起来像是 1.9.13.1版本发布过程中异常了, jar包没有真正传上来。
jar包下载不下来
https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-lib/1.9.13.1/tinker-patch-lib-1.9.13.1.jar

![image](https://user-images.githubusercontent.com/1791581/59329120-b5cb9a00-8d20-11e9-9dc7-78be9e0b550a.png)

**Comment by tomystang** [comment]
再试试看？估计是jcenter审核延迟了一下。

**Comment by yanweimin7** [comment]
还是不行，其他三个文件都能下载

![image](https://user-images.githubusercontent.com/1791581/59329555-b9135580-8d21-11e9-9ec6-18c7be8e3e3a.png)

**Comment by tomystang** [comment]
额，我又publish了一次，我这边已经可以用你发的链接下载了

**Comment by yanweimin7** [comment]
额，貌似是墙的问题，就墙了这一个文件。。。
