### ISSUE TITLE
Tinker为什么 dexdiff算法？可以使用bsdiff算法计算差分吗？

### ISSUE THREAD

**Issue by mivanzhang** [Tencent/tinker#1126]
因为发现补丁的合成时间比较长，bsdiff算法运算速度比较快，可能会降低合成的时间，从而提升成功率

**Comment by tomystang** [comment]
有两个原因：
1. dexdiff可以把loader pattern里指定的类从patch dex里移除，避免出现ClassCastException的问题。比方说Application类，因为补丁加载之前肯定已经用默认ClassLoader加载过一次了，如果补丁里不移除这个类的话，app其他逻辑一旦引用了Application，就会报这个异常。不过要规避的话可以在AndroidNClassLoader里做判断，目前这个逻辑已经有了，但如果你的项目还需要指定其他的存在这种问题的类，就只能改Tinker代码了。**另外如果你还打算支持Dalvik机器的话，这个AndroidNClassLoader的hack逻辑还需要改到对所有版本的系统都生效，不然Dalvik机器现在不会替换默认ClassLoader，换用bsdiff肯定会导致pre-verified error问题**，成因和上面的描述是类似的。

2. dexdiff产物普遍要比bsdiff小，平均能小1/5。当然现在流量已经很便宜了，不担心下发补丁的时候瞬时流量导致的cdn费用问题的话其实换成bsdiff也可以。

总之其实可以换，就是处理ClassCastException和pre-verified error问题会比较麻烦而已。

**Comment by mivanzhang** [comment]
3q
