### ISSUE TITLE
无法运行：You have not accepted the license agreements of the following SDK components

### ISSUE THREAD

**Issue by oops-liang** [Tencent/tinker#113]
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
[Android SDK Platform 23, Android SDK Build-Tools 23.0.2].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

不知道如何解决.....

**Comment by shwenzhang** [comment]
重新下载sdk,这个问题请自行google
