### ISSUE TITLE
手动打包，热修复提示TinkerLoadResult: parseTinkerResult loadCode:-2

### ISSUE THREAD

**Issue by fishsoft** [Tencent/tinker#1136]
```
手动打包生成的文件没有patch_signed_7zip.apk，用patch_signed.apk修复时，产生一下日志
异常类型：app运行时异常/编译异常

手机型号：华为P30

手机系统版本：如:Android 9.+

tinker版本：如:1.9.9

gradle版本：如:3.4.1

是否使用热更新SDK： tinker

系统：windows

2019-06-25 11:23:44.331 32430-32430/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.morse.yindexfix/tinker
2019-06-25 11:23:44.332 32430-32430/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.morse.yindexfix/tinker
2019-06-25 11:23:44.332 32430-32430/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
2019-06-25 11:23:44.332 32430-32430/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.morse.yindexfix, main process:true, systemOTA:false, fingerPrint:HUAWEI/ELE-AL00/HWELE:9/HUAWEIELE-AL00/162C00:user/release-keys, oatDir:null, useInterpretMode:false
2019-06-25 11:23:44.332 32430-32430/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-06-25 11:23:44.332 32430-32430/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.morse.yindexfix/tinker, code: -2, cost: 1ms
2019-06-25 11:23:44.332 32430-32430/? W/Tinker.Tinker: tinker load fail!
2019-06-25 11:23:44.332 32430-32430/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.

**Comment by fishsoft** [comment]
手动产生的包，在修复的时候会提示tinkerId is not equal, base is D28B6717D8F0015F84B874F9D6688EF7, but patch is 1.0，在AndroidManifest中配置的TINKER_ID是D28B6717D8F0015F84B874F9D6688EF7，patch文件中的TINKER_ID还是1.0

**Comment by fishsoft** [comment]
#base package config field
#Tue Jun 25 11:30:09 CST 2019
patchMessage=classes.dex
TINKER_ID=1.0
NEW_TINKER_ID=D28B6717D8F0015F84B874F9D6688EF7
is_protected_app=0
platform=all

**Comment by tomystang** [comment]
是用命令行工具打的patch包吗？

**Comment by fishsoft** [comment]
> ```
> 手动打包生成的文件没有patch_signed_7zip.apk，用patch_signed.apk修复时，产生一下日志
> 异常类型：app运行时异常/编译异常
> 
> 手机型号：华为P30
> 
> 手机系统版本：如:Android 9.+
> 
> tinker版本：如:1.9.9
> 
> gradle版本：如:3.4.1
> 
> 是否使用热更新SDK： tinker
> 
> 系统：windows
> 
> 2019-06-25 11:23:44.331 32430-32430/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.morse.yindexfix/tinker
> 2019-06-25 11:23:44.332 32430-32430/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.morse.yindexfix/tinker
> 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
> 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.morse.yindexfix, main process:true, systemOTA:false, fingerPrint:HUAWEI/ELE-AL00/HWELE:9/HUAWEIELE-AL00/162C00:user/release-keys, oatDir:null, useInterpretMode:false
> 2019-06-25 11:23:44.332 32430-32430/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
> 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.morse.yindexfix/tinker, code: -2, cost: 1ms
> 2019-06-25 11:23:44.332 32430-32430/? W/Tinker.Tinker: tinker load fail!
> 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
> ```

缺少读取权限

**Comment by fishsoft** [comment]
> 手动产生的包，在修复的时候会提示tinkerId is not equal, base is D28B6717D8F0015F84B874F9D6688EF7, but patch is 1.0，在AndroidManifest中配置的TINKER_ID是D28B6717D8F0015F84B874F9D6688EF7，patch文件中的TINKER_ID还是1.0

在AndroidManifest配置的TINKER_ID和tinker_config.xml配置的不一样

**Comment by liuyiyuan** [comment]
> > ```
> > 手动打包生成的文件没有patch_signed_7zip.apk，用patch_signed.apk修复时，产生一下日志
> > 异常类型：app运行时异常/编译异常
> > 
> > 手机型号：华为P30
> > 
> > 手机系统版本：如:Android 9.+
> > 
> > tinker版本：如:1.9.9
> > 
> > gradle版本：如:3.4.1
> > 
> > 是否使用热更新SDK： tinker
> > 
> > 系统：windows
> > 
> > 2019-06-25 11:23:44.331 32430-32430/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.morse.yindexfix/tinker
> > 2019-06-25 11:23:44.332 32430-32430/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.morse.yindexfix/tinker
> > 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
> > 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.morse.yindexfix, main process:true, systemOTA:false, fingerPrint:HUAWEI/ELE-AL00/HWELE:9/HUAWEIELE-AL00/162C00:user/release-keys, oatDir:null, useInterpretMode:false
> > 2019-06-25 11:23:44.332 32430-32430/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
> > 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.morse.yindexfix/tinker, code: -2, cost: 1ms
> > 2019-06-25 11:23:44.332 32430-32430/? W/Tinker.Tinker: tinker load fail!
> > 2019-06-25 11:23:44.332 32430-32430/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
> > ```
> 
> 缺少读取权限

检查一下代码,是否值配置了文件写入权限,而没提供文件读的权限
