### ISSUE TITLE
在assembleDebug时候出现FileNotFoundException

### ISSUE THREAD

**Issue by SmallBenClock** [Tencent/tinker#114]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageProdArmeabiDebug'.
> java.io.FileNotFoundException: F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\build\intermediates\transforms\mergeJavaRes\prod\debug\folders\2\1f\main\META-INF (拒绝访问。)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 10.227 secs
F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\build\intermediates\transforms\mergeJavaRes\prod\debug\folders\2\1f\main\META-INF (拒绝访问。)

**Comment by shwenzhang** [comment]
请查看gradle相关配置
