### ISSUE TITLE
资源文件中的命名中有“.” (如：android:textColor="?attr/album.element.color") 补丁中会当成修改内容，导致崩溃

### ISSUE THREAD

**Issue by yinzj1993** [Tencent/tinker#1150]
异常类型：app运行时异常

tinker版本：如:1.9.9

gradle版本：如:4.1

是否使用热更新SDK：  Bugly SDK

系统：如:Windows

资源文件中的命名中有.(如：android:textColor="?attr/album.element.color") 补丁中会当成修改内容将文件打进补丁，app打上此补丁会崩溃

**Comment by dotcink** [comment]
@tomystang 请问这个 bug 有进展吗？
