### ISSUE TITLE
Tinker配合AndRes生成补丁包导致无法运行的问题

### ISSUE THREAD

**Issue by w4lle** [Tencent/tinker#117]
情况1：
oldApk：Res混淆
newApk：新增drawable资源，修改java代码，未做andRes混淆
tinker结果：打patch正常，tinkerlog显示资源文件都是add，运行正常

情况2：
oldAPk：Res混淆
newApk：新增drawable资源，修改java代码，Res混淆
tinker结果：打patch正常，运行崩溃
android.content.res.Resources$NotFoundException: File r/a2/y.xml from xml type layout resource ID #0x7f050018
查看resouce_out.zip/resource.arsc中没有新增的资源文件。

**Comment by w4lle** [comment]
解决：
在tinker的res.pattern中增加 "r/*"
因为AndRes混淆后变成短链，都在在"r"目录，加上pattern才能打包进去

**Comment by dodola** [comment]
@w4lle 1. 你如果基础包使用了res混淆，那么后面的apk最好也要用andres混淆处理一下
2. 你如果使用res混淆的化，你需要在 配置里增加
```gradle
            pattern = ["res/*", "r/*","assets/*", "resources.arsc", "AndroidManifest.xml"]
```

**Comment by dodola** [comment]
@w4lle 我还没写完就close了:joy:

**Comment by 15189611** [comment]
请问下 我用redAnd混淆后生成的resource_mapping-release-1025-19-24-55.txt 文件 该用到那。谢谢
