### ISSUE TITLE
TinkerApplication 无法获取

### ISSUE THREAD

**Issue by liangchaojie** [Tencent/tinker#1176]
api 'com.tencent.tinker:tinker-android-lib:1.9.9'
升级到
 api 'com.tencent.tinker:tinker-android-lib:1.9.13'

这个时候发现代码爆红，无法饮用TinkerApplication了

**Comment by Licardo** [comment]
怎么解决的 找不到TinkerApplication呢？

**Comment by JaydenHoFly** [comment]
我们也遇到这个问题了，请问怎么解决的呢

**Comment by JaydenHoFly** [comment]
更新到v1.9.13.2吧，https://github.com/Tencent/tinker/issues/1074
