### ISSUE TITLE
希望支持 Gradle TinkerPatch 同时生成debug&release 的7z.apk 方案

### ISSUE THREAD

**Issue by letyouthgoon** [Tencent/tinker#119]
现在是7z.apk唯一，持续集成环境下需要维护两套代码来生成apk

**Comment by kongnanlive** [comment]
+1

**Comment by shwenzhang** [comment]
为什么需要维持两套代码？

**Comment by letyouthgoon** [comment]
@shwenzhang 因为没有TinkerPatch
 做debug／release 都是生成同名的7z.apk

**Comment by kongnanlive** [comment]
@shwenzhang 我的理解是tinkerOldApkPath每次只能设置一个，release跟debug两个apk不一样。

**Comment by shwenzhang** [comment]
这个通过改sample的脚本就可以实现

**Comment by letyouthgoon** [comment]
用tinkerpatch －p 可以搞定
