### ISSUE TITLE
TinkerApplication 里为何不直接通过 ApplicationLike 接口调用 delegate 的相关方法，而是通过反射调用？

### ISSUE THREAD

**Issue by wsxyeah** [Tencent/tinker#1193]
个人的一点疑问，希望可以解答下。

**Comment by tomystang** [comment]
直接调用的话ApplicationLike的接口方法的代码以及它引用的代码都会被内联到Application类里。因为Application类加载的时候Tinker的hack还没开始做，而ApplicationLike的代码又是在Tinker做了替换classloader的hack之后才开始跑的，这样在Android P开始就会出现“被内联的代码和内联到的类的classloader不一致”的校验错误，同时包括P以下，>=N的系统又会出现ClassCastException。

**Comment by wsxyeah** [comment]
感谢回复。可否理解为 `ApplicationLike` 自身的 classloader 与实现类的 classloader 不一致，从而导致无法完成向上转型呢？

**Comment by tomystang** [comment]
对的，就是这样。
不过出于性能考虑，1.9.14版本我换成try-catch+特殊命名避免内联了。
