### ISSUE TITLE
Tinker 官方对 DexFile 有替换的计划么？

### ISSUE THREAD

**Issue by tdounnyy** [Tencent/tinker#1197]
官方在 API 26 给 [DexFile](https://kapeli.com/dash_share?docset_file=Android&docset_name=Android&path=developer.android.com/reference/dalvik/system/DexFile.html&platform=android&repo=Main&source=https://developer.android.com/reference/dalvik/system/DexFile&version=9.0.0) 标记了 @Deprecated

Tinker 也曾经移除过相关调用，后来又 [revert](https://github.com/Tencent/tinker/commit/45c1c1983170150a969a8db665b2b6694ee97f6d) 回来了。

问题：可以说明一下 revert 的原因么？Tinker 官方对 DexFile 有替换的计划么？

**Comment by tomystang** [comment]
有的。

revert的原因是有些厂商帮我们跳过了DexFile触发的dex2oat，导致调完之后没有oat文件落地影响加载阶段的dex合成成功检测。

不过最近有厂商反馈DexFile会阻止运行时jit优化补丁dex，所以1.9.14版本在>=Android P的情况下就改用运行时注入的那个ClassLoader来触发dex2oat了。
