### ISSUE TITLE
使用assemble打包的时候出现没有打包成功

### ISSUE THREAD

**Issue by SmallBenClock** [Tencent/tinker#120]
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

:app:processDevArmeabiDebugResources
:app:processDevUniversalDebugManifest
F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\src\main\AndroidManifest.xml:61:5-66 Warning:
	Element uses-permission#android.permission.VIBRATE at AndroidManifest.xml:61:5-66 duplicated with element declared at AndroidManifest.xml:23:5-66
F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\src\main\AndroidManifest.xml:62:5-73 Warning:
	Element uses-permission#android.permission.WRITE_SETTINGS at AndroidManifest.xml:62:5-73 duplicated with element declared at AndroidManifest.xml:46:5-73
F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\src\main\AndroidManifest.xml:70:5-66 Warning:
	Element uses-permission#android.permission.VIBRATE at AndroidManifest.xml:70:5-66 duplicated with element declared at AndroidManifest.xml:61:5-66
tinker add cbc0b12 to your AndroidManifest.xml F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\build\intermediates\manifests\full\dev\debug\AndroidManifest.xml
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml
:app:tinkerProcessDevDebugManifest
apply resource mapping file F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\build\bakApk/app-debug-1012-15-57-46-R.txt is illegal, just ignore
tinker gen resource public.xml in build/intermediates/tinker_intermediates/public.xml
tinker gen resource idx.xml in build/intermediates/tinker_intermediates/idx.xml
:app:tinkerProcessDevDebugResourceId
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

**Comment by shwenzhang** [comment]
最后异常的日志？
