### ISSUE TITLE
Duplicate zip entry [tinker-ziputils-1.9.2.jar:com/tencent/tinker/ziputils/ziputil/Arrays.class])

### ISSUE THREAD

**Issue by awpss** [Tencent/tinker#1200]
异常类型：编译补丁包异常

tinker版本：1.9.2

gradle版本：3.1.4

TINKERPATCH_VERSION：1.2.2

是否使用热更新SDK： Bugly SDK

系统：Windows10

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForRongXinDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/tencent/tinker/ziputils/ziputil/Arrays.class

**Comment by OS9527** [comment]
异常类型：编译补丁包异常
as版本 ： 3.5
tinker版本：1.9.9

gradle版本：3.1.4

TINKERPATCH_VERSION：1.2.2

是否使用热更新SDK： Bugly SDK

系统：Windows10

* What went wrong:
Execution failed for task ':android_lab:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: kotlinx/android/extensions/ContainerOptions.class
