### ISSUE TITLE
有一个问题

### ISSUE THREAD

**Issue by flyer1b** [Tencent/tinker#1201]
比如基础包a ，用b包基于a做补丁得到c
然后a应用c补丁得到d
再用e包基于a做补丁f
这个时候d包会应用补丁f吗

**Comment by tomystang** [comment]
不做判断的话是会的，应用补丁的时候只检查base包的tinkerid。但是你下发patch的时候可以加个版本号，接收的时候比对一下自身可以被patch升级的版本号，比方说当你发现d包已经加载了，收到的补丁版本为f，你就可以决定是否要调onPatchReceived函数来控制是否要应用补丁了。
