### ISSUE TITLE
使用newApk方式打patch报 but resources.arsc is changed, you should use applyResourceMapping mode to build the new apk

### ISSUE THREAD

**Issue by yanweimin7** [Tencent/tinker#1203]
使用 tinkerPatch task方式打patch包，在添加了newApk参数的情况下。
```
./gradlew tinkerPatchGjjRelease -POLD_APK=old.pak -PNEW_APK=new.apk
```

报错

```
ignoreWarning is false, but resources.arsc is changed, you should use applyResourceMapping mode to build the new apk, otherwise, it may be crash at some times
```

看原因是因为 

https://github.com/Tencent/tinker/blob/89f0ff53074c049f8105eb468de32cfa9e2741c5/tinker-build/tinker-patch-lib/src/main/java/com/tencent/tinker/build/decoder/ResDiffDecoder.java#L310

mUseApplyResource 值为false，只能在buildConfig里面手动开启。

```
tinkerPatch {
        buildConfig {
           useApplyResource = true
           ....
        }
}

```

### 问题
* 在使用newApk的场景下，是否不需要检测useApplyResource?

**Comment by tomystang** [comment]
这个检测必须得开着，不然编出来的包资源id对不上，会导致运行时资源错乱的。

**Comment by tomystang** [comment]
另外其实这种用法挺奇怪的，你触发tinkerPatchTask的时候会先触发assembleTask，编出来的包默认就是新包了，只用指定oldApk就好。如果你分别指定old和new，相当于tinkerPatchTask这次触发白编译了一次哇。

**Comment by yanweimin7** [comment]
@tomystang  wiki文档上说 

![image](https://user-images.githubusercontent.com/1791581/64072920-8c8c2b80-ccc9-11e9-8118-2a4bbdefa0cc.png)

不会触发编译的，直接会对两个apk做diff。
