### ISSUE TITLE
1.9.14在4.x系统上安装启动即闪退的问题，回退到1.9.13.2后问题消失

### ISSUE THREAD

**Issue by kiitos** [Tencent/tinker#1229]
异常类型：app运行时异常

手机型号：三星note2 联想A590 等

手机系统版本：4.1.1

tinker版本：1.9.14

gradle版本：Gradle版本5.1.1， AGP版本3.4.2

是否使用热更新SDK： Bugly SDK

系统：Mac， Linux

其它：通过bugly方式集成，enableProxyApplication = true的方式初始化sdk，未开启加固，tinker-support版本1.2.0，回退到1.9.13.2版后问题消失，只在1.9.14上出现

堆栈/日志：

09-18 10:28:46.293 E/AndroidRuntime( 2937): FATAL EXCEPTION: main
09-18 10:28:46.293 E/AndroidRuntime( 2937): java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:501)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4291)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.ActivityThread.access$1300(ActivityThread.java:149)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.os.Looper.loop(Looper.java:153)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.ActivityThread.main(ActivityThread.java:4994)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at java.lang.reflect.Method.invoke(Method.java:511)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at dalvik.system.NativeStart.main(Native Method)
09-18 10:28:46.293 E/AndroidRuntime( 2937): Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(SourceFile:118)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:127)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:146)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(SourceFile:57)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.Application.attach(Application.java:146)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.Instrumentation.newApplication(Instrumentation.java:983)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.Instrumentation.newApplication(Instrumentation.java:967)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	... 11 more
09-18 10:28:46.293 E/AndroidRuntime( 2937): Caused by: java.lang.ClassNotFoundException: com.tencent.tinker.entry.TinkerApplicationInlineFence
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at java.lang.Class.classForName(Native Method)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at java.lang.Class.forName(Class.java:217)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(SourceFile:108)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	... 18 more
09-18 10:28:46.293 E/AndroidRuntime( 2937): Caused by: java.lang.NoClassDefFoundError: com/tencent/tinker/entry/TinkerApplicationInlineFence
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	... 21 more
09-18 10:28:46.293 E/AndroidRuntime( 2937): Caused by: java.lang.ClassNotFoundException: com.tencent.tinker.entry.TinkerApplicationInlineFence
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
09-18 10:28:46.293 E/AndroidRuntime( 2937): 	... 21 more

**Comment by tomystang** [comment]
已知问题，在项目的maindex list中添加com.tencent.tinker.entry.TinkerApplicationInlineFence这个类即可，这周会发小版本修复。

**Comment by achenglike** [comment]
大佬,麻烦问下大概啥时候发这个修复版本,我们看看是升级最新还是先暂时用1.9.13.2

**Comment by sunbird89629** [comment]
> 大佬,麻烦问下大概啥时候发这个修复版本,我们看看是升级最新还是先暂时用1.9.13.2

这个问题你怎么处理的啊？是回退版本了还是按照上面说的把TinkerApplicationInlineFence这个类加到了maindex list中了？

**Comment by achenglike** [comment]
> > 大佬,麻烦问下大概啥时候发这个修复版本,我们看看是升级最新还是先暂时用1.9.13.2
> 
> 这个问题你怎么处理的啊？是回退版本了还是按照上面说的把TinkerApplicationInlineFence这个类加到了maindex list中了？

我回退到1.9.13.2了

**Comment by sunbird89629** [comment]
> > > 大佬,麻烦问下大概啥时候发这个修复版本,我们看看是升级最新还是先暂时用1.9.13.2
> > 
> > 
> > 这个问题你怎么处理的啊？是回退版本了还是按照上面说的把TinkerApplicationInlineFence这个类加到了maindex list中了？
> 
> 我回退到1.9.13.2了

ok!

**Comment by LG27** [comment]
> 已知问题，在项目的maindex list中添加com.tencent.tinker.entry.TinkerApplicationInlineFence这个类即可，这周会发小版本修复。

1.9.14.3跟新上说修改这个问题，但是我在4.4的手机上还是找不到TinkerApplicationInlineFence这个class
