### ISSUE TITLE
命令行接入问题

### ISSUE THREAD

**Issue by ysq1993** [Tencent/tinker#123]
命令行如何接入 之前的步骤都按照文档走了
![issue](https://cloud.githubusercontent.com/assets/17694025/19340180/2a5608b2-915a-11e6-8f92-fa43eec52da2.png)

**Comment by gaoxuxu** [comment]
命令行接入你的自己处理混淆和资源ID

**Comment by ysq1993** [comment]
@gaoxuxu 
![image](https://cloud.githubusercontent.com/assets/17694025/19342554/d81b6302-9164-11e6-8b58-0b1317691953.png) wiki说不是命令行工具tinker-patch-cli.jar提供了基准包与新安装包做差异，生成补丁包的功能

**Comment by JoeyChen52** [comment]
同问命令具体行如何接入？

**Comment by gaoxuxu** [comment]
@ysq1993 @JoeyChen52 

cli的源码在```tinker-build/tinker-patch-cli```，可以自己编译jar包，编译出jar包后，使用方法可以

```
java -jar tinker-patch-cli-1.6.2.jar -h

Usage: java -jar tinker.jar -old old.apk -new new.apk -config tinker_config.xml -out output_path
others please contact us
```

**Comment by ysq1993** [comment]
@gaoxuxu 
![image](https://cloud.githubusercontent.com/assets/17694025/19381687/5e3b1a0c-922f-11e6-9d9c-bde2c3279972.png)这个项目AS打包后 adb命令执行即可？

**Comment by tomystang** [comment]
@ysq1993 
在项目根目录里有个buildSdk文件夹，里面有个配置文件，叫tinker_config.xml，参数大致上跟build.gradle里的配置是一样的，配置好之后，按wiki里的描述通过命令行执行那个tinker-patch-cli-1.x.x.jar就好。

**Comment by ysq1993** [comment]
@tomystang 
![image](https://cloud.githubusercontent.com/assets/17694025/19382120/5842d818-9231-11e6-81e9-0e7c4851b2c9.png) demo没有呀

**Comment by tomystang** [comment]
不是demo的根目录，是整个tinker项目的根目录，如果还找不到的话就触发一次:tinker-build:tinker-patch-cli, others里的buildSdk task吧
