### ISSUE TITLE
TinkerTestDexLoad.isPatch是在什么地方被修改为true的，源码里没看到

### ISSUE THREAD

**Issue by TracyZhangLei** [Tencent/tinker#1254]
用jar包做出的补丁，加载不成功，报code -14；
用gradle task做出补丁包却可以成功；
查到了TinkerTestDexLoad.isPatch，还望大神指点迷津。

**Comment by TracyZhangLei** [comment]
找到了。

**Comment by CoderNo89757** [comment]
我遇到类似的问题，在多了一些引用后，加载补丁包会抛出异常，问题关键就在TinkerTestDexLoad.isPatch = false，导致加载补丁失败code -14，但是我反编译了补丁包的test.dex中的这个类，发现TinkerTestDexLoad.isPatch = true，请问下TinkerTestDexLoad.isPatch是在什么地方被修改为true的？
