### ISSUE TITLE
工业平板运行demo报code-5

### ISSUE THREAD

**Issue by hzl1378252** [Tencent/tinker#1256]
工业平板处理器
 型号：ESM/EPC-700 
处理器：QuadCore-A64 
Android版本：6.0.1
tinker版本：1.9.14.3
点击load patch提示
10-16 17:20:31.648 18473-18473/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: sdcard/patch_signed_7zip.apk, file size:148928
10-16 17:20:31.652 18473-18473/tinker.sample.android I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /sdcard/patch_signed_7zip.apk, code: -5

**Comment by tomystang** [comment]
应该是你的设备同时满足了下面的条件：
1. 存在 `dalvik.vm.usejit` 和 `dalvik.vm.usejitprofiles` 两个 system properties
2. Android SDK Version < 7

在这种情况下为了避免 jit 引入兼容性问题，目前 Tinker 会直接忽略这类设备上的请求。
