### ISSUE TITLE
Error parsing XML: not well-formed (invalid token)

### ISSUE THREAD

**Issue by xybCoder** [Tencent/tinker#126]
AndroidManifest.xml  file 注释如下
 /-----------------------------社会化分享，登陆--------------------------/
 Error parsing XML: not well-formed (invalid token)，

**Comment by shwenzhang** [comment]
我这边似乎没有问题，你使用的是windows?

**Comment by xybCoder** [comment]
嗯

**Comment by shwenzhang** [comment]
@xybCoder  使用1.7.1再尝试一下
