### ISSUE TITLE
patch_unsigned.apk无法自动签名 

### ISSUE THREAD

**Issue by a8stefan** [Tencent/tinker#1275]
Gen classes2.dex patch file:/Users/jerrychang/svn_emc/full/3.0.7/app/build/outputs/apk/tinkerPatch/release/tinker_result/classes2.dex, size:3011, md5:7f740e3771121d365a35485ab3ab6698
Verifying if patched new dex is logically the same as original new dex: emc_new_v3.0.8_2019-11-07/classes2.dex ...

Gen classes2.dex for dalvik full dex file:/Users/jerrychang/svn_emc/full/3.0.7/app/build/outputs/apk/tinkerPatch/release/tempPatchedDexes/classes2.dex, size:10503180, md5:de108003d7d0f3ee34d73890c2339ab1

Gen classes.dex patch file:/Users/jerrychang/svn_emc/full/3.0.7/app/build/outputs/apk/tinkerPatch/release/tinker_result/classes.dex, size:1374, md5:0facadc35ebb4b5c1f8c6002ff3b6ac2
Verifying if patched new dex is logically the same as original new dex: emc_new_v3.0.8_2019-11-07/classes.dex ...

Gen classes.dex for dalvik full dex file:/Users/jerrychang/svn_emc/full/3.0.7/app/build/outputs/apk/tinkerPatch/release/tempPatchedDexes/classes.dex, size:5594164, md5:a245d188dd4e55b0ecc78d8132d44642
DexDecoder:write meta file data: classes3.dex,,0,341beacdd15a5a041c38fbe1599e2749,0,1320236254,1320236254,jar
DexDecoder:write meta file data: classes2.dex,,de108003d7d0f3ee34d73890c2339ab1,de108003d7d0f3ee34d73890c2339ab1,7f740e3771121d365a35485ab3ab6698,128403603,3250677019,jar
DexDecoder:write meta file data: classes.dex,,a245d188dd4e55b0ecc78d8132d44642,a245d188dd4e55b0ecc78d8132d44642,0facadc35ebb4b5c1f8c6002ff3b6ac2,2709763730,2785508993,jar

Add test install result dex: /Users/jerrychang/svn_emc/full/3.0.7/app/build/outputs/apk/tinkerPatch/release/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,0,jar
Add Test resource file: assets/only_use_to_test_tinker_resource.txt
Final normal zip resource: resources_out.zip, size=21345170, md5=f7350b0c45b2e406e13f1a940ec2c97e
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
12:25:48: Task execution finished 'tinkerPatchRelease'.
只编译一个patch_unsigned.apk 其他编译失败

**Comment by 1136346879** [comment]
楼主解决了吗？
我这边现在也报这个异常

**Comment by a8stefan** [comment]
搞定了
