### ISSUE TITLE
删除下载的临时文件后，重启app，崩溃

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#128]
见UpgradePatchRetry.onPatchServiceStart()方法
line152:
String patchMd5 = SharePatchFileUtil.getMD5(patchFile);
此时由于sd卡中的临时文件被删除，patchMd5会是null，后面使用它，就崩溃了

**Comment by shwenzhang** [comment]
这个问题1.7.0已经修复了吧？

**Comment by shwenzhang** [comment]
请使用1.7.0再次尝试

**Comment by balizhuang2012** [comment]
大神辛苦了
