### ISSUE TITLE
修改xml的布局样子，生成patch出现问题

### ISSUE THREAD

**Issue by Anayuta** [Tencent/tinker#129]
Analyze old and new apk files:
old apk: app-debug-1017-18-34-43.apk, size=26066500, md5=2c79a0f58028c54272f17543e012cf51
new apk: app-debug.apk, size=26098868, md5=3232f627e004881768a522febcb87bb0
UnZipping apk to D:\kpie\2.0.3.0\trunk\source\kpie\app\build\outputs\tinkerPatch\debug\app-debug-1017-18-34-43
UnZipping apk to D:\kpie\2.0.3.0\trunk\source\kpie\app\build\outputs\tinkerPatch\debug\app-debug
Check for loader classes in dex: ../app-debug-1017-18-34-43/classes.dex
Check for loader classes in dex: ../app-debug-1017-18-34-43/classes2.dex
Warning:ignoreWarning is true, but we found loader classes are found in old secondary dex. Found classes: {Ltinker/sample/android/app/BaseBuildInfo;}
Found modify resource: res/layout/activity_index.xml
No dexes were changed, nothing needs to be done next.

**Comment by shwenzhang** [comment]
Warning:ignoreWarning is true, but we found loader classes are found in old secondary dex. Found classes: {Ltinker/sample/android/app/BaseBuildInfo;}， 请看文档！
