### ISSUE TITLE
1.7.0生成补丁失败（loader classes are found in old secondary dex）

### ISSUE THREAD

**Issue by tandywang** [Tencent/tinker#130]
java.lang.RuntimeException: com.tencent.tinker.build.util.TinkerPatchException: loader classes are found in old secondary dex. Found classes: {Lcom/tencent/tinker/loader/R$string;,Lcom/tencent/tinker/loader/R;}

1.6.2生成补丁正常，但1.7.0报这个错误，multiDexKeepProguard file('keep_in_main_dex.txt')已配置，麻烦看下什么问题

-keep class com.tencent.tinker.loader.** {
    *;
}

**Comment by shwenzhang** [comment]
这里可能是transform的坑，1.7.1会去掉transform

**Comment by shwenzhang** [comment]
@tandywang ， 使用1.7.1再尝试一下
