### ISSUE TITLE
DefaultApplicationLike的onCreate()被多个线程调用；

### ISSUE THREAD

**Issue by wonghoman** [Tencent/tinker#131]
在DefaultApplicationLike的继承类中，定义一个i，
在它的onCreate()中执行i++，然后打印Log.e("tag", "my:::::::"+i);

结果输出：
10-18 11:41:37.082 31577-31577/xxx.xxx E/error: my::::::1
10-18 11:41:40.642 31716-31716/xxx.xxx:process1 E/error: my::::::1
10-18 11:41:40.672 31727-31727/xxx.xxx:process2 E/error: my::::::1
10-18 11:41:42.582 31836-31836/xxx.xxx:bdservice_v1 E/error: my::::::1
10-18 11:41:47.902 31997-31997/xxx.xxx:remote E/error: my::::::1
10-18 11:41:49.002 32042-32042/xxx.xxx:patch E/error: my::::::1

可以看到，onCreate()被多个线程调用，这是为什么呢？我哪里错了吗？请大神指教！

**Comment by shwenzhang** [comment]
是多个进程，不是多个线程

**Comment by wonghoman** [comment]
@shwenzhang 嗯，是进程，我打错字而已，请问这样正常吗？

**Comment by wonghoman** [comment]
@shwenzhang 嗯，是进程，我打错字而已，请问这样正常吗？
