### ISSUE TITLE
开放出来的是腾讯团队用的么？

### ISSUE THREAD

**Issue by TracyZhangLei** [Tencent/tinker#133]
有什么坑么？怎么这么多人反馈问题

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/19478183/1da6aaa4-9574-11e6-88fd-ce0ef8fce2ca.png)

这里可以看到微信正在使用的版本，大部分的issue都已经解决。除了1.7.0由于增加transform引入的几个问题

**Comment by dodola** [comment]
@TracyZhangLei 其中大部分issues是因为配置不当造成的

**Comment by TracyZhangLei** [comment]
@shwenzhang  @dodola 好的　谢谢．
