### ISSUE TITLE
> No such property: variant for class: com.tencent.tinker.build.gradle.TinkerPatchPlugin

### ISSUE THREAD

**Issue by vfishv** [Tencent/tinker#1345]
AS 3.6  Mac OS
升级到AS 3.6 编译不通过

classpath 'com.android.tools.build:gradle:3.6.0'
Gradle 5.6.4

**Comment by hqzxzwb** [comment]
针对这个情况写了一个dirty hack，分享一下。
放在`apply plugin: 'com.tencent.tinker.patch'`之前。

```
// Hack Tinker to be compatible with AGP 3.6.0
plugins.whenPluginAdded { plugin ->
    if (plugin.getClass().getName() == "com.tencent.tinker.build.gradle.TinkerPatchPlugin") {
        plugin.metaClass.getObfuscateTask = { String variantName ->
            String r8TaskName = "minify${variantName}WithR8"
            def r8 = mProject.tasks.findByName(r8TaskName)
            if (r8 != null) {
                return r8
            }
            throw new RuntimeException("Cannot find r8 task.")
        }
        plugin.metaClass.getR8Task = { String variantName ->
            String r8TaskName = "minify${variantName}WithR8"
            def r8Task = mProject.tasks.findByName(r8TaskName)
            if (r8Task != null) {
                def multidexConfigTask = mProject.tasks.findByName("tinkerProcess${variantName}MultidexKeep")
                multidexConfigTask.multiDexKeepProguard = project.file("build/intermediates/legacy_multidex_aapt_derived_proguard_rules/${variantName.uncapitalize()}/manifest_keep.txt")
                r8Task.dependsOn multidexConfigTask
            }
            return null
        }
    }
}
```

**Comment by Jay-Droid** [comment]
> 针对这个情况写了一个dirty hack，分享一下。
> 放在`apply plugin: 'com.tencent.tinker.patch'`之前。
> 
> ```
> // Hack Tinker to be compatible with AGP 3.6.0
> plugins.whenPluginAdded { plugin ->
>     if (plugin.getClass().getName() == "com.tencent.tinker.build.gradle.TinkerPatchPlugin") {
>         plugin.metaClass.getObfuscateTask = { String variantName ->
>             String r8TaskName = "minify${variantName}WithR8"
>             def r8 = mProject.tasks.findByName(r8TaskName)
>             if (r8 != null) {
>                 return r8
>             }
>             throw new RuntimeException("Cannot find r8 task.")
>         }
>         plugin.metaClass.getR8Task = { String variantName ->
>             String r8TaskName = "minify${variantName}WithR8"
>             def r8Task = mProject.tasks.findByName(r8TaskName)
>             if (r8Task != null) {
>                 def multidexConfigTask = mProject.tasks.findByName("tinkerProcess${variantName}MultidexKeep")
>                 multidexConfigTask.multiDexKeepProguard = project.file("build/intermediates/legacy_multidex_aapt_derived_proguard_rules/${variantName.uncapitalize()}/manifest_keep.txt")
>                 r8Task.dependsOn multidexConfigTask
>             }
>             return null
>         }
>     }
> }
> ```

Cannot find r8 task.

**Comment by vfishv** [comment]
> 针对这个情况写了一个dirty hack，分享一下。
> 放在`apply plugin: 'com.tencent.tinker.patch'`之前。
> 
> ```
> // Hack Tinker to be compatible with AGP 3.6.0
> plugins.whenPluginAdded { plugin ->
>     if (plugin.getClass().getName() == "com.tencent.tinker.build.gradle.TinkerPatchPlugin") {
>         plugin.metaClass.getObfuscateTask = { String variantName ->
>             String r8TaskName = "minify${variantName}WithR8"
>             def r8 = mProject.tasks.findByName(r8TaskName)
>             if (r8 != null) {
>                 return r8
>             }
>             throw new RuntimeException("Cannot find r8 task.")
>         }
>         plugin.metaClass.getR8Task = { String variantName ->
>             String r8TaskName = "minify${variantName}WithR8"
>             def r8Task = mProject.tasks.findByName(r8TaskName)
>             if (r8Task != null) {
>                 def multidexConfigTask = mProject.tasks.findByName("tinkerProcess${variantName}MultidexKeep")
>                 multidexConfigTask.multiDexKeepProguard = project.file("build/intermediates/legacy_multidex_aapt_derived_proguard_rules/${variantName.uncapitalize()}/manifest_keep.txt")
>                 r8Task.dependsOn multidexConfigTask
>             }
>             return null
>         }
>     }
> }
> ```

not work

**Comment by vfishv** [comment]
version 1.9.14.6  is OK
