### ISSUE TITLE
能使用在含有运行时依赖注解的项目中吗？

### ISSUE THREAD

**Issue by xiang23** [Tencent/tinker#135]
比如DataBinding

**Comment by shwenzhang** [comment]
可以的，tinker只针对最后的dex产物

**Comment by amyliu1062** [comment]
@shwenzhang  使用Databinding后，提示SampleApplication与build/generated/...../SampleApplication重复
![image](https://cloud.githubusercontent.com/assets/6679526/24130838/d48ebb1a-0e25-11e7-9a2b-5f63250796e8.png)
