### ISSUE TITLE
Demo 1.7.0 在4.2.1 手机上补丁包安装失败

### ISSUE THREAD

**Issue by S-MILE-S** [Tencent/tinker#136]
1.7.0在 其他系统版本手机安装正常，1.6.2 全部正常。
测试过多个品牌的4.2.1 系统的手机，均无法安装补丁包。
日志：
`
10-18 16:32:59.649 17217-17217/tinker.sample.android I/SurfaceTextureClient: [STC::queueBuffer] (this:0x5cdf5ed0) fps:0.03, dur:57710.06, max:57520.15, min:189.91
10-18 16:32:59.649 17217-17217/tinker.sample.android I/SurfaceTextureClient: [STC::queueBuffer] this:0x5cdf5ed0, api:1, last queue time elapsed:57520.15
10-18 16:32:59.794 17217-17217/tinker.sample.android V/Provider/Settings:  from settings cache , name = sound_effects_enabled , value = 1
10-18 16:32:59.794 17217-17217/tinker.sample.android V/Provider/Settings:  from settings cache , name = sound_effects_enabled , value = 1
10-18 16:32:59.795 17217-17217/tinker.sample.android I/OppoExVibrator: OppoExVibrator setSecureController code=10002
10-18 16:32:59.798 17217-17217/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/sdcard0/patch_signed_7zip.apk, isUpgrade:true, file size:4234
10-18 16:32:59.798 17217-17217/tinker.sample.android D/dalvikvm: create interp thread : stack size=32KB
10-18 16:32:59.798 17217-17217/tinker.sample.android D/dalvikvm: create new thread
10-18 16:32:59.798 17217-17217/tinker.sample.android D/dalvikvm: new thread created
10-18 16:32:59.798 17217-17217/tinker.sample.android D/dalvikvm: update thread list
10-18 16:32:59.798 17217-18134/tinker.sample.android D/dalvikvm: threadid=13: interp stack at 0x5f0ac000
10-18 16:32:59.799 17217-18134/tinker.sample.android D/dalvikvm: threadid=13: created from interp
10-18 16:32:59.799 17217-17217/tinker.sample.android D/dalvikvm: start new thread
10-18 16:32:59.799 17217-18134/tinker.sample.android D/dalvikvm: threadid=13: notify debugger
10-18 16:32:59.799 17217-18134/tinker.sample.android D/dalvikvm: threadid=13 (SharedPreferencesImpl-load): calling run()
10-18 16:32:59.801 17217-18134/tinker.sample.android D/dalvikvm: threadid=13: exiting
10-18 16:32:59.801 17217-18134/tinker.sample.android D/dalvikvm: threadid=13: bye!
10-18 16:32:59.810 17217-17217/tinker.sample.android D/dalvikvm: create interp thread : stack size=32KB
10-18 16:32:59.811 17217-17217/tinker.sample.android D/dalvikvm: create new thread
10-18 16:32:59.811 17217-17217/tinker.sample.android D/dalvikvm: new thread created
10-18 16:32:59.811 17217-17217/tinker.sample.android D/dalvikvm: update thread list
10-18 16:32:59.813 17217-18137/tinker.sample.android D/dalvikvm: threadid=13: interp stack at 0x5f0ac000
10-18 16:32:59.813 17217-18137/tinker.sample.android D/dalvikvm: threadid=13: created from interp
10-18 16:32:59.813 17217-17217/tinker.sample.android D/dalvikvm: start new thread
10-18 16:32:59.813 17217-18137/tinker.sample.android D/dalvikvm: threadid=13: notify debugger
10-18 16:32:59.813 17217-18137/tinker.sample.android D/dalvikvm: threadid=13 (SharedPreferencesImpl-load): calling run()
10-18 16:32:59.823 17217-18137/tinker.sample.android D/dalvikvm: threadid=13: exiting
10-18 16:32:59.823 17217-18137/tinker.sample.android D/dalvikvm: threadid=13: bye!
10-18 16:32:59.833 17217-17219/tinker.sample.android D/dalvikvm: GC_CONCURRENT freed 272K, 11% free 3321K/3732K, paused 3ms+2ms, total 26ms
10-18 16:32:59.833 17217-17219/tinker.sample.android D/jdwp: sendBufferedRequest : len=0x34
10-18 16:32:59.835 17217-17217/tinker.sample.android D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 19ms
10-18 16:32:59.838 17217-17217/tinker.sample.android I/Tinker.SamplePatchListener: get platform:all
10-18 16:32:59.990 17217-17217/tinker.sample.android D/dalvikvm: create interp thread : stack size=32KB
10-18 16:32:59.990 17217-17217/tinker.sample.android D/dalvikvm: create new thread
10-18 16:32:59.991 17217-17217/tinker.sample.android D/dalvikvm: new thread created
10-18 16:32:59.991 17217-17217/tinker.sample.android D/dalvikvm: update thread list
10-18 16:32:59.991 17217-18156/tinker.sample.android D/dalvikvm: threadid=13: interp stack at 0x5f0ac000
10-18 16:32:59.992 17217-18156/tinker.sample.android D/dalvikvm: threadid=13: created from interp
10-18 16:32:59.992 17217-17217/tinker.sample.android D/dalvikvm: start new thread
10-18 16:32:59.992 17217-18156/tinker.sample.android D/dalvikvm: threadid=13: notify debugger
10-18 16:32:59.992 17217-18156/tinker.sample.android D/dalvikvm: threadid=13 (IntentService[AbstractResultService]): calling run()
10-18 16:33:00.000 17217-18156/tinker.sample.android I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                                   PatchResult: 
                                                                                   isUpgradePatch:true
                                                                                   isSuccess:false
                                                                                   rawPatchFilePath:/storage/sdcard0/patch_signed_7zip.apk
                                                                                   costTime:37
10-18 16:33:00.005 17217-18156/tinker.sample.android I/Process: Sending signal. PID: 18140 SIG: 9
10-18 16:33:00.007 17217-17217/tinker.sample.android D/skia: Flag is not 10
10-18 16:33:00.012 17217-18156/tinker.sample.android D/dalvikvm: threadid=13: exiting
10-18 16:33:00.012 17217-18156/tinker.sample.android D/dalvikvm: threadid=13: bye!

`

**Comment by shwenzhang** [comment]
这个是1.7.0为了解决jsk签名引入的一个bug。。其实也是4.2.1在验签时的bug。现在在dev分支已经修复，可使用licalmaven验证

**Comment by S-MILE-S** [comment]
刚刚试了，的确已经修复
