### ISSUE TITLE
Tinker 1.8.0版本规划

### ISSUE THREAD

**Issue by shwenzhang** [Tencent/tinker#137]
1. Tinker后台 service部分, 已完成 [TinkerPatch平台](http://www.tinkerpatch.com);
2. Tinker四大组件代理支持

**Comment by kongnanlive** [comment]
四大组件的代理都有了，有没有类似于[阿里Atlas](http://mp.weixin.qq.com/s?__biz=MjM5MDE0Mjc4MA==&mid=2650994465&idx=2&sn=d28e52cd5e6aeacf4db11538feca6e40)插件化啊？

**Comment by shwenzhang** [comment]
@kongnanlive 插件化跟热补丁还是不太一样，暂时不计划直接支持插件化

**Comment by long-fei** [comment]
真棒

**Comment by yanyuquan** [comment]
辛苦了

**Comment by weinierfei** [comment]
有木有1.8.0版本的大体时间表?

**Comment by shwenzhang** [comment]
这里大约需要两周吧，计划11月中旬可以完成

**Comment by weinierfei** [comment]
后台 service部分目前规划了哪些功能呢

**Comment by TracyZhangLei** [comment]
@shwenzhang 大神，android n上tinker成功率好像不是很高，貌似还比较耗时．了解这个情况么？

**Comment by shwenzhang** [comment]
@TracyZhangLei ,这个是怎么得出的结论？

**Comment by TracyZhangLei** [comment]
@shwenzhang 在其他手机上应用上补丁，杀进程(启动后很短时间就可以)，重启就能起效；在android n上试了几次都不起效，等待较长时间后杀进程也不行，偶尔可以起效．不知道是哪里的原因．

**Comment by shwenzhang** [comment]
@TracyZhangLei , 应该不会，这样说没有意义。请更新到1.7.1，然后给出合成以及加载的日志吧

**Comment by TracyZhangLei** [comment]
@shwenzhang 请问＂ Keep dex apply插件:即保证编译补丁包时使用与基础包一样的分包方案，减少由于dex移动导致的变化＂这个todolist是什么进展了？如果patchApk和baseApk相比出现dex偏移，tinker怎么处理补丁包？

**Comment by haozhnn** [comment]
@shwenzhang 大神，我想问下怎么连续更新呢，假设原apk是1，修改一点后变成2，再修改一点变成3。1和2之间的补丁是a，2和3之间的补丁是b。现在是1可以通过补丁a变成2，但是无法再根据补丁b变成3。

**Comment by shwenzhang** [comment]
@TracyZhangLei  dev已经合入keep dex apply功能

**Comment by shwenzhang** [comment]
@haozhnn 看文档

**Comment by GoombaCN** [comment]
@shwenzhang 大神 请问一下是否所有的加固都不支持 包括应用宝的

**Comment by shwenzhang** [comment]
@GoombaCN 应用宝的后期会支持

**Comment by keke195** [comment]
接入了TinkerPatch后台，使用时为什么已安装的应用没有下载补丁包，而新安装的应用能够下载补丁包？

**Comment by wisekingokok** [comment]
@shwenzhang 大神，1.8.0什么时候出来啊？需要四大组件代理支持啊

**Comment by shwenzhang** [comment]
#452
