### ISSUE TITLE
热更新检测补丁失败

### ISSUE THREAD

**Issue by jun201607** [Tencent/tinker#1373]
异常类型：检测热更新补丁异常
PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.net.ConnectException: Failed to connect to q.tinkerpatch.com/127.0.0.1:80
热更新版本：1.9.14.5
使用的是基础班套餐（没花钱的），邮件咨询套餐购买，没人回

**Comment by zhengzhuoxing** [comment]
@jun201607 你好，你的这个问题解决了么，我遇到了和你一样的问题
