### ISSUE TITLE
打1.7.1补丁包时，IOException: Can't write 

### ISSUE THREAD

**Issue by Lsdjack** [Tencent/tinker#138]
1.7.1
* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [F:\android\my_work\demos2\tinker-dev\tinker-sample-android\app\build\intermediates\transforms\proguard\release\jars\3\1f\main.jar] (Can't read [F:\android\my_work\demos2\tinker-dev\tinker-sample-android\app\build\intermediate
s\transforms\AuxiliaryInject\release\jars\1\1f\aosp-dexutils-1.7.1_9cc07307ace0cf0140f4bf3df8fae896.jar(;;;;;;**.class)] (Duplicate zip entry [com/tencent/tinker/a/a/a.class == aosp-dexutils-1.7.1_9cc07307ace0cf0140f4bf3df8fae896.jar:com/tencent/tinker/android/
dex/Annotation.class]))

**Comment by shwenzhang** [comment]
fix with dev branch

**Comment by Lsdjack** [comment]
请问：这个是要下1.8.0才完成修复吗？如果是1.8.0大概在什么时候出呀？

**Comment by shwenzhang** [comment]
你用dev分支编译，已经解决了
