### ISSUE TITLE
1.9.14.7版本似乎漏传tinker-android-anno-support到仓库

### ISSUE THREAD

**Issue by youthyJJ** [Tencent/tinker#1393]
异常类型：编译异常

tinker版本: 1.9.14.7

gradle版本：gradle-5.6.4-all | android-tools-3.6.3

是否使用热更新SDK： 否

系统：Mac

问题描述:
今天发现tinker添加了 1.9.14.7 Tag, 开心地更新了版本, 然后执行编译命令
```
./gradlew clean build
```
提示无法在maven中找到以下内容:
```
http://~/tencent/tinker/tinker-android-anno-support/1.9.14.7/tinker-android-anno-support-1.9.14.7.pom
http://~/tencent/tinker/tinker-android-anno-support/1.9.14.7/tinker-android-anno-support-1.9.14.7.jar
```
在 https://bintray.com/bintray/jcenter 中查找只能够找到 tinker-android-anno, 暂未找到 tinker-android-anno-support , 查看代码发现此库为3月27日新增, 烦请确认是否遗漏.

**Comment by hisgod** [comment]
一样，下载不来依赖，咋办

**Comment by youthyJJ** [comment]
> 一样，下载不来依赖，咋办

先用1.9.14.6咯, 等大佬确认一下~
如果急用可以直接源码编译一下, 传到本地maven先用着, 哪个库只有三个类哈哈

**Comment by Code6666** [comment]
一样，下载不来依赖，赶紧补传

**Comment by YuYongzhi** [comment]
什么时候可以上传好？

**Comment by simpleton** [comment]
可以暂时添加，一个额外的源来作为workaround。
```
https://dl.bintray.com/tinker/maven
```

jcenter同步可能需要1天左右的时间, cc @tomystang

**Comment by youthyJJ** [comment]
项目中引入已经能够找到对应的库了，此issus关闭。

**Comment by yuanshenbin** [comment]
@youthyJJ 你咋处理， https://dl.bintray.com/tinker/maven这个里面也没有啊，是重新编译的么
