### ISSUE TITLE
kotlin会支持吗？

### ISSUE THREAD

**Issue by congtaowang** [Tencent/tinker#14]
项目是用kotlin开发的，tinker支持吗？或者说会把对kotlin的支持规划进tinker的分支里？

**Comment by sendya** [comment]
`kotlin` 好像是可以直接兼容的吧

**Comment by shwenzhang** [comment]
应该是支持的，我们只针对最后的Dex来做Diff

**Comment by congtaowang** [comment]
多谢，我试试 @shwenzhang
