### ISSUE TITLE
error: Resource entry id/android:list is already defined in package crm.hecom.cn

### ISSUE THREAD

**Issue by laotian** [Tencent/tinker#141]
开启tinker后，执行任务 tinkerPatchDebug ,提示出错

:app-hqcrm:tinkerProcessDebugManifest
tinker add testTinkerId to your AndroidManifest.xml /Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/manifests/full/debug/AndroidManifest.xml
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml

:app-hqcrm:tinkerProcessDebugResourceId
we build app-hqcrm apk with apply resource mapping file /Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/bakApk/app-hqcrm-debug-1025-17-26-05-R.txt
tinker gen resource public.xml in build/intermediates/tinker_intermediates/public.xml
tinker gen resource idx.xml in build/intermediates/tinker_intermediates/idx.xml

:app-hqcrm:processDebugResources
AGPBI: {"kind":"error","text":"Resource entry id/android:list is already defined in package crm.hecom.cn.","sources":[{"file":"/Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/res/merged/debug/values/ids.xml","position":{"startLine":672}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Error declaring public resource id/android:list for included package crm.hecom.cn","sources":[{"file":"/Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/res/merged/debug/values/public.xml","position":{"startLine":1872}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"Public symbol style/goal_item_label_reach declared here is not defined.","sources":[{"file":"/Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/res/merged/debug/values/public.xml","position":{"startLine":9437}}],"original":"","tool":"AAPT"}
/Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/res/merged/debug/values/ids.xml:673: error: Resource entry id/android:list is already defined in package crm.hecom.cn.
/Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/res/merged/debug/values/public.xml:1873: error: Error declaring public resource id/android:list for included package crm.hecom.cn

/Users/tianlupan/IdeaProjects/mgm/app-hqcrm/build/intermediates/res/merged/debug/values/public.xml:9438: error: Public symbol style/goal_item_label_reach declared here is not defined.

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app-hqcrm:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
build.config设置

[build.gradle.zip](https://github.com/Tencent/tinker/files/550235/build.gradle.zip)

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
[tinker_intermediates.zip](https://github.com/Tencent/tinker/files/550222/tinker_intermediates.zip)

**Comment by shwenzhang** [comment]
android:list是属于一个非法定义，正常aapt也会去忽略它，这里为了校验，tinker就不做修改了
