### ISSUE TITLE
补丁提交失败，显示请选择文件

### ISSUE THREAD

**Issue by MrLiGitHub** [Tencent/tinker#1429]
操作流程:  选择上传补丁 >>  填写描述 >>  选择全量下发 >> 提交 >> 提示请选择文件
如下图：
![untitled1](https://user-images.githubusercontent.com/20282811/87870539-9c912480-c9db-11ea-8cc0-59cda06da563.png)
![untitled2](https://user-images.githubusercontent.com/20282811/87870542-9dc25180-c9db-11ea-84eb-1968dcba58f3.png)

Chrome浏览器、QQ浏览器、Microsoft Edge效果一致均无法上传

**Comment by youxiachai** [comment]
你反馈错项目了。。。。
