### ISSUE TITLE
最新版本在哪些手机或者系统会崩溃？

### ISSUE THREAD

**Issue by h3r3x3** [Tencent/tinker#145]
有测试到崩溃的同学能不能列下机型和系统
对于无法fix的，考虑服务器不对这些机型下发patch

**Comment by shwenzhang** [comment]
1. tinker是有crash自动回退机制的  2. 新版本特别是资源方面，在微信的确是没有full test，这块准备下周灰度

**Comment by h3r3x3** [comment]
是有自动回退机制，但是如果能提前预知的话，服务端下发策略体验会更好点
希望微信端灰度以后，能把出问题的机型系统列出来 @shwenzhang

**Comment by shwenzhang** [comment]
其实无论资源还是代码都有做提前检测，我们是希望有问题的机型是可以直接通过框架筛选出来，而不希望是通过配置的方式。对于资源的case，可能要修改检测的机制。

我的观点还是，不应该通过白名单的方式，这个是低效而且无法维护的。我还是看看如果通过框架能准确的识别这台机器是否是可以patch的。

**Comment by kongnanlive** [comment]
“tinker是有crash自动回退机制的 ”SampleUncaughtExceptionHandler有相关代码可以看下，崩溃3次后cleanPatch。

**Comment by shwenzhang** [comment]
@kongnanlive 除了那个还有safemode，安全模式
