### ISSUE TITLE
上传失败！补丁文件缺失必需字段：Created-Time、Created-By、YaPatchType、VersionName、VersionCode、From、To，请检查补丁文件后重试！

### ISSUE THREAD

**Issue by wuyubo0522** [Tencent/tinker#1475]
使用Tinker 1.9.14.7，打补丁包完成。在bugly管理平台发布补丁出现

上传失败！补丁文件缺失必需字段：Created-Time、Created-By、YaPatchType、VersionName、VersionCode、From、To，请检查补丁文件后重试！

查看相关的配置没有问题。

**Comment by youxiachai** [comment]
我也是用1.9.14.7 在bugly上传补丁,没你这个情况...

**Comment by tqlmorepassion** [comment]
你要在patch目录下的补丁包才行，包里面会有yapatch.mf文件才对。
不是在tinkerPatch目录下那个包。

**Comment by YaowenGuo** [comment]
> 你要在patch目录下的补丁包才行，包里面会有yapatch.mf文件才对。
> 不是在tinkerPatch目录下那个包。

我的项目并没有生成 patch 目录，请问怎么回事呀？

**Comment by SaiHor** [comment]
同样是这个问题，解决了么

**Comment by woaimi520** [comment]
我也是1.9.14.5 也是 上传没有这些必须字段

**Comment by isong0623** [comment]
last version 同样的问题，解决：不要用tinker的buildTinkerPatchRelease用thinker-support
