### ISSUE TITLE
不支持 高于 3.4.2 的  gradle 插件版本

### ISSUE THREAD

**Issue by zhangdepeng125** [Tencent/tinker#1509]
异常类型：编译异常

tinker版本：1.9.14.5

gradle版本：4.1.1 

使用的tinker sdk 有： tinker-android-lib、tinker-android-loader、tinker-android-anno

系统：windows 10 

堆栈/日志：

![image](https://user-images.githubusercontent.com/31883653/103724054-75242780-500e-11eb-9616-1e8bad27347d.png)

gradle 构建失败日志：
A problem occurred configuring project ':app'.
> No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData

gradle 版本 修改为 3.4.2 就没有问题了

**Comment by yanjunhui2014** [comment]
我也遇到了，什么时候支持3.6.0以上的gradle啊

**Comment by smashinggit** [comment]
同问

**Comment by gaowen** [comment]
同问

**Comment by tigerose** [comment]
同问，目前 classpath 'com.android.tools.build:gradle:3.5.3'， 迟早无法使用新版本的AndroidStudio

**Comment by youxiachai** [comment]
已经更新啦...可以支持了

**Comment by tigerose** [comment]
刚试了，目前是这样
classpath 'com.android.tools.build:gradle:4.0.1'
classpath "com.tencent.bugly:tinker-support:1.2.1"
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
    buglyCrashReportUpgrade = "1.5.0"
    buglyTinker = "1.9.14.10"
    buglyNativeCrashReport = "3.7.1"

最终提示：
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData
   > can't find tinkerProcessPreDebugManifest, you must init tinker plugin first!

**Comment by mjnhmd** [comment]
我用 1.9.14.11可以了， gradle 6.5  buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了

**Comment by zhangdepeng125** [comment]
新版本已经支持

**Comment by tigerose** [comment]
> 我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了

直接使用tinker？我是通过bugly使用，bugly1.5.0（内含 tinker 1.9.14.10,）。它的tinker plugin还不能适应高版本gradle

**Comment by zhangdepeng125** [comment]
你好，请问我的项目中 自定义Application 多层继承，而且里面的代码复杂，没法使用 ApplicationLike 代理。你遇到过这个问题吗。 你的 Application 是通过 ApplicationLike&nbsp; 代理的吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tinker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 下午5:01
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Tencent/tinker] 不支持 高于 3.4.2 的  gradle 插件版本 (#1509)





  
我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了
  
直接使用tinker？我是通过bugly使用，bugly1.5.0（内含 tinker 1.9.14.10,）。它的tinker plugin还不能适应高版本gradle

**Comment by tigerose** [comment]
> 你好，请问我的项目中 自定义Application 多层继承，而且里面的代码复杂，没法使用 ApplicationLike 代理。你遇到过这个问题吗。 你的 Application 是通过 ApplicationLike&nbsp; 代理的吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/tinker" ***@***.***&gt;; 发送时间:&nbsp;2021年3月21日(星期天) 下午5:01 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [Tencent/tinker] 不支持 高于 3.4.2 的 gradle 插件版本 (#1509) 我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了 直接使用tinker？我是通过bugly使用，bugly1.5.0（内含 tinker 1.9.14.10,）。它的tinker plugin还不能适应高版本gradle — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

我是继承TinkerApplication，类A； 继承DefaultApplicationLike， 类B， 类A的构造函数中传入类B的class。。。和bugly官方要求一样

**Comment by zhangdepeng125** [comment]
可以加您的微信或者QQ 向您请教一下吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月24日(星期三) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Tencent/tinker] 不支持 高于 3.4.2 的  gradle 插件版本 (#1509)





  
你好，请问我的项目中 自定义Application 多层继承，而且里面的代码复杂，没法使用 ApplicationLike 代理。你遇到过这个问题吗。 你的 Application 是通过 ApplicationLike&nbsp; 代理的吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/tinker" @.&gt;; 发送时间:&nbsp;2021年3月21日(星期天) 下午5:01 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [Tencent/tinker] 不支持 高于 3.4.2 的 gradle 插件版本 (#1509) 我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了 直接使用tinker？我是通过bugly使用，bugly1.5.0（内含 tinker 1.9.14.10,）。它的tinker plugin还不能适应高版本gradle — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我是继承TinkerApplication，类A； 继承DefaultApplicationLike， 类B， 类A的构造函数中传入类B的class。。。和bugly官方要求一样

**Comment by tigerose** [comment]
> 可以加您的微信或者QQ 向您请教一下吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月24日(星期三) 下午4:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [Tencent/tinker] 不支持 高于 3.4.2 的 gradle 插件版本 (#1509) 你好，请问我的项目中 自定义Application 多层继承，而且里面的代码复杂，没法使用 ApplicationLike 代理。你遇到过这个问题吗。 你的 Application 是通过 ApplicationLike&nbsp; 代理的吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/tinker" @.&gt;; 发送时间:&nbsp;2021年3月21日(星期天) 下午5:01 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [Tencent/tinker] 不支持 高于 3.4.2 的 gradle 插件版本 (#1509) 我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了 直接使用tinker？我是通过bugly使用，bugly1.5.0（内含 tinker 1.9.14.10,）。它的tinker plugin还不能适应高版本gradle — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 我是继承TinkerApplication，类A； 继承DefaultApplicationLike， 类B， 类A的构造函数中传入类B的class。。。和bugly官方要求一样 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

把联系方式发给我

**Comment by zhangdepeng125** [comment]
qq: 1252861234
wx: 15688429875
ph: 15688429875




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月24日(星期三) 下午5:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Tencent/tinker] 不支持 高于 3.4.2 的  gradle 插件版本 (#1509)





  
可以加您的微信或者QQ 向您请教一下吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月24日(星期三) 下午4:42 收件人: @.&gt;; 抄送: @.&gt;; "State @.&gt;; 主题: Re: [Tencent/tinker] 不支持 高于 3.4.2 的 gradle 插件版本 (#1509) 你好，请问我的项目中 自定义Application 多层继承，而且里面的代码复杂，没法使用 ApplicationLike 代理。你遇到过这个问题吗。 你的 Application 是通过 ApplicationLike&nbsp; 代理的吗 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/tinker" @.&gt;; 发送时间:&nbsp;2021年3月21日(星期天) 下午5:01 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [Tencent/tinker] 不支持 高于 3.4.2 的 gradle 插件版本 (#1509) 我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了 直接使用tinker？我是通过bugly使用，bugly1.5.0（内含 tinker 1.9.14.10,）。它的tinker plugin还不能适应高版本gradle — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 我是继承TinkerApplication，类A； 继承DefaultApplicationLike， 类B， 类A的构造函数中传入类B的class。。。和bugly官方要求一样 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
把联系方式发给我

**Comment by scsfwgy** [comment]
> 我用 1.9.14.11可以了， gradle 6.5 buildtool 4.1.1. 我看提交记录最新版已经到1.9.14.13了，他们现在更新已经连readme都懒得更新了

distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip

classpath 'com.android.tools.build:gradle:4.1.1'
classpath 'com.tencent.bugly:tinker-support:1.2.3'

//https://github.com/Tencent/tinker
    api 'com.tencent.tinker:tinker-android-lib:1.9.14.15'
    //https://mvnrepository.com/artifact/com.tencent.bugly/crashreport_upgrade?repo=jcenter
    api 'com.tencent.bugly:crashreport_upgrade:1.5.1'

----------       
 classpath 'com.android.tools.build:gradle:4.1.1' 这个升级导致的，3.4.1就ok

打包、安装什么都没问题，但是打补丁包报以下错误：

`
Execution failed for task ':app:tinkerPatchRelease'.
> com.tencent.tinker.build.util.TinkerPatchException: can't find TINKER_ID from the old apk manifest file, it must be set!
`

**Comment by AtenzaZoom** [comment]
官网上只看到这个：支持到最新tinker lib 1.9.14.10,tinker-support版本1.2.1。楼上说的1.9.14.11版本对应的support应该是多少啊？试了下用1.9.14.11对应support的1.2.3，编译正常打完基准包运行直接闪退啊。对了采用的是enableProxyApplication = true 的方式

**Comment by mjnhmd** [comment]
> 官网上只看到这个：支持到最新tinker lib 1.9.14.10,tinker-support版本1.2.1。楼上说的1.9.14.11版本对应的support应该是多少啊？试了下用1.9.14.11对应support的1.2.3，编译正常打完基准包运行直接闪退啊。对了采用的是enableProxyApplication = true 的方式

我用的是原生的 没有使用bugly的版本，没有tinker-support

**Comment by MrZWC** [comment]
classpath "com.tencent.bugly:tinker-support:1.2.3"

implementation 'com.tencent.bugly:nativecrashreport:3.9.0'
implementation 'com.tencent.tinker:tinker-android-lib:1.9.14.17'
implementation 'com.tencent.bugly:crashreport_upgrade:1.5.23'
现在最新的支持版本
bugly文档没有更新可以在https://mvnrepository.com/ 上搜索最新版本  已经支持gradle-6.5
