### ISSUE TITLE
Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by taoweiji** [Tencent/tinker#151]
使用Tinker修复一个继承Service的类，导致出现了Class ref in pre-verified class resolved to unexpected implementation异常。
Tinker版本：1.7.3

http://bugly.qq.com/share/Bh46Zb

**Comment by zyn4399** [comment]
如果出现Class ref in pre-verified class resolved to unexpected implementation异常, 请确认以下几点：Application中传入ApplicationLike的参数时是否采用字符串而不是Class.getName方式；新的Application是否已经加入到dex loader pattern中; 额外添加到dex loader pattern中类的引用类也需要加载到loader pattern中。

**Comment by taoweiji** [comment]
只有部分机型出错，大多数的机型都没有问题。

**Comment by shwenzhang** [comment]
部分机型指的是dalvik虚拟机的机器？这个问题请自己先排查一次

**Comment by taoweiji** [comment]
的确是只有部分的dalvik手机出现问题
`public class MyApplication extends TinkerApplication {

    public MyApplication() {
        super(7, "co.runner.app.SampleApplicationLike", "com.tencent.tinker.loader.TinkerLoader", false);
    }

}`
这是自动生成的，我没有做修改
multiDexKeepProguard对应的文件
`-keep class com.tencent.tinker.loader.** {
    *;
}
-keep class co.runner.app.MyApplication {
    *;
}
-keep public class * implements com.tencent.tinker.loader.app.ApplicationLifeCycle {
    *;
}
-keep public class * extends com.tencent.tinker.loader.TinkerLoader {
    *;
}
-keep public class * extends com.tencent.tinker.loader.app.TinkerApplication {
    *;
}`
出现的类属于Account Service类，用于系统账号同步，不知道是否有影响？

**Comment by shwenzhang** [comment]
dex loader pattern
