### ISSUE TITLE
关于对apkPath开放的咨询

### ISSUE THREAD

**Issue by chowjee** [Tencent/tinker#152]
Tinker合成的逻辑默认是通过Context获取applicationInfo.sourceDir作为待合成的源文件：
String apkPath = applicationInfo.sourceDir;
apk = new ZipFile(apkPath);

这对于插件化项目中的插件apk想使用Tinker来说有一定的局限 （Context问题），请问能否将apkPath获取开放出来呢？

**Comment by shwenzhang** [comment]
对于插件其实可以自己很简单的封一套的，类似bsdiff那样

**Comment by chowjee** [comment]
自己封装或者修改代码是可以实现，但是考虑到Tinker一直在迭代，这样有后期可能存在代码merge冲突带来的维护问题，如果Tinker能够支持这样的扩展那是最好不过了。

封装类似bsdiff可以合成插件dex，但是TinkerService中对dex做的安全校验相关的轮子岂不是要重新造了(拷贝)，这样又回到前面所说的问题了。

**Comment by zhaoxuyang** [comment]
Hi,我在阅读dev分之的最新代码发现个和以前不一致的地方，在使用UsePreGeneratedPatchDex模式的时候，以前只把refer to refer affected changed classes打入到了patch，新的代码还包含refer to changed classes，请教下为什么这么写？

**Comment by shwenzhang** [comment]
@chowjee 这边暂时不做修改，我后期单独封一个aardiff的工具出来把
