### ISSUE TITLE
每次执行transformClassesAndResourcesWithProguardForRelease的时候都会出错

### ISSUE THREAD

**Issue by mabeijianxi** [Tencent/tinker#153]
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Can't write [C:\studio_work_space\soon_2.4_10_26\app\build\intermed
iates\transforms\proguard\release\jars\3\1f\main.jar] (Can't read [C:\studio_work_space\so
on_2.4_10_26\app\build\intermediates\transforms\AuxiliaryInject\release\jars\1\1f\gson-2.2
.4_388aac006cf2bc8f414bb5b58fed415b.jar(;;;;;;**.class)] (Duplicate zip entry [gson-2.2.4_
388aac006cf2bc8f414bb5b58fed415b.jar:com/google/gson/Gson$5.class]))

使用版本1.7.3

**Comment by mabeijianxi** [comment]
clean一些数据后正常

**Comment by Warpath** [comment]
@mabeijianxi 我也遇到这个问题，tinker 1.7.7你是 clean 哪些数据正常呢
