### ISSUE TITLE
安装补丁成功，加载失败，log onPatchRetryLoad retry info not exist, just return

### ISSUE THREAD

**Issue by liangyuteng0927** [Tencent/tinker#155]
基本上一些类是从simple拷来的，安装log：
11-05 15:56:58.005 29662-29695/kh.android.funnyiconpack:patch W/Tinker.ResDiffPatchInternal: success recover large modify file:/data/user/0/kh.android.funnyiconpack/tinker/patch-c0e76a35/res/resources.arsc , file size:264100, use time:132
11-05 15:56:58.005 29662-29695/kh.android.funnyiconpack:patch W/Tinker.ResDiffPatchInternal: success recover all large modify use time:142
11-05 15:56:58.124 29662-29695/kh.android.funnyiconpack:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/kh.android.funnyiconpack/tinker/patch-c0e76a35/res/resources.arsc
11-05 15:56:58.131 29662-29695/kh.android.funnyiconpack:patch I/Tinker.ResDiffPatchInternal: final new resource file:/data/user/0/kh.android.funnyiconpack/tinker/patch-c0e76a35/res/resources.apk, entry count:523, size:4817573
11-05 15:56:58.131 29662-29695/kh.android.funnyiconpack:patch I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:275, isNewPatch:true
11-05 15:56:58.133 29662-29695/kh.android.funnyiconpack:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
11-05 15:56:58.133 29662-29695/kh.android.funnyiconpack:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch.apk, success:true, cost:376, isUpgrade:true
11-05 15:56:58.133 29662-29695/kh.android.funnyiconpack:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/kh.android.funnyiconpack/tinker/patch.retry
11-05 15:56:58.133 29662-29695/kh.android.funnyiconpack:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/kh.android.funnyiconpack/tinker/temp.apk
11-05 15:56:58.165 29465-29704/kh.android.funnyiconpack I/Tinker.ResultService: SampleResultService receive result: 
                                                                                PatchResult: 
                                                                                isUpgradePatch:true
                                                                                isSuccess:true
                                                                                rawPatchFilePath:/storage/emulated/0/patch.apk
                                                                                costTime:376
                                                                                patchVersion:c0e76a359ca6dc182d05e36adbee9c30
                                                                                patchTinkerID:tinkerId
                                                                                baseTinkerID:tinkerId
11-05 15:56:58.169 29465-29704/kh.android.funnyiconpack I/Tinker.ResultService: save delete raw patch file
11-05 15:56:58.169 29465-29704/kh.android.funnyiconpack I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/patch.apk
11-05 15:56:58.169 29465-29704/kh.android.funnyiconpack I/Tinker.ResultService: tinker wait screen to restart process
toast提示成功，重启应用时：
 11-05 15:59:13.252 31913-31913/kh.android.funnyiconpack W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
11-05 15:59:13.257 31913-31913/kh.android.funnyiconpack W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_kh.android.funnyiconpack count:0
11-05 15:59:13.260 31913-31913/kh.android.funnyiconpack W/Tinker.TinkerLoader: after tinker safe mode count:1
11-05 15:59:13.260 31913-31913/kh.android.funnyiconpack W/Tinker.TinkerDexLoader: there is no dex to load
11-05 15:59:13.263 31913-31913/kh.android.funnyiconpack E/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
11-05 15:59:13.263 31913-31913/kh.android.funnyiconpack I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/user/0/kh.android.funnyiconpack/tinker/patch-c0e76a35/res/resources.apk, use time: 3
11-05 15:59:13.263 31913-31913/kh.android.funnyiconpack I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
11-05 15:59:13.265 31913-31913/kh.android.funnyiconpack D/Tinker.DefaultAppLike: onBaseContextAttached:
11-05 15:59:13.268 31913-31913/kh.android.funnyiconpack I/Tinker.SamplePatchListener: application maxMemory:288
11-05 15:59:13.269 31913-31913/kh.android.funnyiconpack W/Tinker.Tinker: tinker patch directory: /data/user/0/kh.android.funnyiconpack/tinker
11-05 15:59:13.270 31913-31913/kh.android.funnyiconpack I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
11-05 15:59:13.270 31913-31913/kh.android.funnyiconpack I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:c0e76a359ca6dc182d05e36adbee9c30, current:c0e76a359ca6dc182d05e36adbee9c30
11-05 15:59:13.271 31913-31913/kh.android.funnyiconpack I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
11-05 15:59:13.271 31913-31913/kh.android.funnyiconpack I/Tinker.DefaultLoadReporter: patch version change from  to c0e76a359ca6dc182d05e36adbee9c30
11-05 15:59:13.271 31913-31913/kh.android.funnyiconpack I/Tinker.DefaultLoadReporter: try kill all other process
11-05 15:59:13.272 31913-31913/kh.android.funnyiconpack I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/kh.android.funnyiconpack/tinker, code:0, cost:48
11-05 15:59:13.753 31913-31913/kh.android.funnyiconpack W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return

patch没有生效。何解

**Comment by shwenzhang** [comment]
没生效指的是什么，你上面没有改任何的dex。只改了资源

**Comment by liangyuteng0927** [comment]
改dex也这样

**Comment by liangyuteng0927** [comment]
成功了，是忘了配置
dex {
        pattern = ["classes*.dex"]
    }
谢大神。
