### ISSUE TITLE
debug补丁生成没问题，release就失败了

### ISSUE THREAD

**Issue by liangyuteng0927** [Tencent/tinker#156]
这是错误：
Error:Execution failed for task ':app:tinkerPatchRelease'.
> Could not get unknown property 'taskName' for task ':app:tinkerPatchRelease' of type com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.

求大神解答~

**Comment by shwenzhang** [comment]
这种问题是直接关闭的
