### ISSUE TITLE
1.7.3patch生成gradle插件有问题？

### ISSUE THREAD

**Issue by shizhy1986** [Tencent/tinker#158]
1.7.1的补丁生成正常，只改了classes2, 但1.7.3插件生成的patch中，dex_meta里面包含了classes3的信息

**Comment by shizhy1986** [comment]
未新增方法，新增变量，看dex log似乎在查找被修改类的引用类了

**Comment by shwenzhang** [comment]
对，因为可能存在内联的问题，所以就算没有新增也需要在最终的art dex合成
