### ISSUE TITLE
task:tinkerPatchVariantName 嘛意思

### ISSUE THREAD

**Issue by llmsparkbbbboy** [Tencent/tinker#16]
直接使用task:tinkerPatchVariantName(例如tinkerPatchDebug、tinkerPatchRelease)即可自动根据Variant选择相应的编译类型  
这句话是什么意思呢? 可以具体的展开吗? 有相关实例代码吗?

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/18824723/ce3ba34a-83f6-11e6-8ce3-bb88a0738ae5.png)
请参考gradle task相关知识
