### ISSUE TITLE
报new patch recover, try patch dex failed

### ISSUE THREAD

**Issue by zyn4399** [Tencent/tinker#160]
11-08 11:20:39.596 23372-23372/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:7382
11-08 11:20:39.612 23372-23372/? I/Tinker.SamplePatchListener: get platform:all
11-08 11:20:39.623 1937-4065/? D/Interception: isInterceptByRule realCallingPid: 23372 isInterceptAsUsual: false isMatch: false, runType===retrieve_service|||callerPkg===cc.kaipao.dongjia|||calleePkg===cc.kaipao.dongjia|||calleeClass===com.tencent.tinker.lib.service.TinkerPatchService|||processName===cc.kaipao.dongjia:patch|||action===*|||data===*|||extras===Bundle[mParcelledData.dataSize=180]|||interception===false
11-08 11:20:39.735 1937-4065/? I/ActivityManager: Start proc 24622:cc.kaipao.dongjia:patch/u0a604 for service cc.kaipao.dongjia/com.tencent.tinker.lib.service.TinkerPatchService
11-08 11:20:40.098 24622-24622/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/data/cc.kaipao.dongjia/tinker/patch.info
11-08 11:20:40.103 24622-24622/? D/Tinker.DefaultAppLike: onBaseContextAttached:
11-08 11:20:40.127 24622-24622/? I/Tinker.SamplePatchListener: application maxMemory:256
11-08 11:20:40.139 24622-24622/? W/Tinker.Tinker: tinker patch directory: /data/data/cc.kaipao.dongjia/tinker
11-08 11:20:40.140 24622-24622/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3
11-08 11:20:40.202 24622-24622/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-08 11:20:40.202 24622-24622/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cc.kaipao.dongjia/tinker, code:-3, cost:7
11-08 11:20:40.213 24622-24622/? W/Tinker.Tinker: tinker load fail!
11-08 11:20:40.232 24622-24622/? D/Tinker.DefaultAppLike: onCreate
11-08 11:20:40.478 24622-24622/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@19f6b846 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=cc.kaipao.dongjia intent=null}
11-08 11:20:40.479 24622-24622/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@19f6b846 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=cc.kaipao.dongjia intent=null}
11-08 11:20:40.479 24622-24622/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService@655fa07, flags=0, startId=1
11-08 11:20:40.479 24622-24622/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@19f6b846 startId=1 args=Intent { cmp=cc.kaipao.dongjia/com.tencent.tinker.lib.service.TinkerPatchService (has extras) }}
11-08 11:20:40.480 24622-24647/? I/Tinker.DefaultPatchReporter: patchReporter: patch service start
11-08 11:20:40.480 24622-24622/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-08 11:20:40.482 24622-24647/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch_signed_7zip.apk to /data/data/cc.kaipao.dongjia/tinker/temp.apk
11-08 11:20:40.496 24622-24647/? I/Tinker.TinkerPatchService: try to increase patch process priority
11-08 11:20:40.504 1937-4065/? D/Interception: isInterceptByRule realCallingPid: 24622 isInterceptAsUsual: false isMatch: false, runType===retrieve_service|||callerPkg===cc.kaipao.dongjia|||calleePkg===cc.kaipao.dongjia|||calleeClass===com.tencent.tinker.lib.service.TinkerPatchService$InnerService|||processName===cc.kaipao.dongjia:patch|||action===*|||data===*|||extras===*|||interception===false
11-08 11:20:40.506 24622-24622/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@d33c734 className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=cc.kaipao.dongjia intent=null}
11-08 11:20:40.507 24622-24622/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@d33c734 className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=cc.kaipao.dongjia intent=null}
11-08 11:20:40.507 24622-24622/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@2bf5d95d, flags=0, startId=1
11-08 11:20:40.507 24622-24622/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@d33c734 startId=1 args=Intent { cmp=cc.kaipao.dongjia/com.tencent.tinker.lib.service.TinkerPatchService$InnerService }}
11-08 11:20:40.507 24622-24622/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@2bf5d95d
11-08 11:20:40.566 24622-24647/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:dexDiffMd5:8b09f57e9fec7f331bbd1686a833f84b
11-08 11:20:40.566 24622-24647/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e
11-08 11:20:40.568 24622-24647/? W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/patch_signed_7zip.apk size:7382, /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/patch-8b09f57e.apk size:7382
11-08 11:20:44.172 24622-24647/? W/Tinker.DexDiffPatchInternal: Failed to recover dex file /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/dex/classes.dex.jar
11-08 11:20:44.172 24622-24647/? I/Tinker.DefaultPatchReporter: patchReporter: file extract fail type:dex_art, path:/data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/patch-8b09f57e.apk, extractTo:/data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/dex/classes.dex.jar, filename:classes.dex, isUpgrade:true
11-08 11:20:44.173 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/patch-8b09f57e.apk
11-08 11:20:44.173 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/dex/classes.dex.jar
11-08 11:20:44.173 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/dex
11-08 11:20:44.174 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e
11-08 11:20:44.174 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch-8b09f57e/dex/classes.dex.jar
11-08 11:20:44.174 24622-24647/? W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
11-08 11:20:44.174 24622-24647/? I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:3605, isUpgradePatch:true
11-08 11:20:44.182 24622-24647/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
11-08 11:20:44.182 24622-24647/? I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:false, cost:3685, isUpgrade:true
11-08 11:20:44.182 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch.retry
11-08 11:20:44.183 24622-24647/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/temp.apk
11-08 11:20:44.226 24622-24622/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService@655fa07
11-08 11:20:44.230 23372-24650/? I/Tinker.SampleResultService: SampleResultService receive result: 
                                                               PatchResult: 
                                                               isUpgradePatch:true
                                                               isSuccess:false
                                                               rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                               costTime:3685
                                                               patchVersion:8b09f57e9fec7f331bbd1686a833f84b
                                                               patchTinkerID:191dbe1
                                                               baseTinkerID:191dbe1

**Comment by zyn4399** [comment]
请问这个是什么问题啊？我比较急！！在线等

**Comment by shwenzhang** [comment]
localmaven已经解决了，你可以自己编译看看

**Comment by zyn4399** [comment]
怎么弄啊，不会。。。

**Comment by shizhy1986** [comment]
这个是不是阿里云的系统,看日志像是阿里云os的, 最新的应该已经对云os直接patch失败了吧?

**Comment by shwenzhang** [comment]
try with 1.7.5
