### ISSUE TITLE
patch meta entry not found

### ISSUE THREAD

**Issue by chenqingfeid** [Tencent/tinker#161]
6-19186/? E/Tinker.TinkerInternals: patch meta entry not found
11-08 12:16:32.459 19186-19186/? I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-10, isUpgrade:true
11-08 12

**Comment by chenqingfeid** [comment]
How to solve this problem?

**Comment by shwenzhang** [comment]
see wiki detail

**Comment by chenqingfeid** [comment]
thanks!

在 2016年11月8日，下午12:28，shwenzhang <notifications@github.com<mailto:notifications@github.com>> 写道：


see wiki detail

**Comment by naqvijafar91** [comment]
Please can i get this answer in English, in the wiki as well. It will be great if we can get the wiki in English

**Comment by shwenzhang** [comment]
@naqvijafar91 because due to Google Play Developer Distribution Agreement, we can't dynamic update our apk. 
It is not easy to use tinker through GP, so far, we don't have any English wiki, sorry

**Comment by nb312** [comment]
@shwenzhang  can you give the detail URL?I cannot find it
