### ISSUE TITLE
the tinker just diabled, but still have a "tinkerId is not set" exception when build project.

### ISSUE THREAD

**Issue by Yunme** [Tencent/tinker#163]
I just set the tinkerEnabled false in the build.gradle, but still have the exception with "tinkerId is not set". otherwise, when set it true, everything is just fine. hope reply. Thanks.

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/20125509/f210ac04-a668-11e6-9d9c-9263e5d3003a.png)

read the ** sources build.gradle

**Comment by kakinIA** [comment]
@shwenzhang 没用，和tinker-android-sample一模一样都不可以，把id写死了也不可以

**Comment by shwenzhang** [comment]
像sample的用法一样，如果debug模式不引入tinker相关的plugin
