### ISSUE TITLE
Android12系统，如果修复的内容没有dex变化，如只有(So、资源变化)时，在Android12系统以下可以生效，但Android 12.0上无效。

### ISSUE THREAD

**Issue by lijinshanmx** [Tencent/tinker#1631]
异常类型：修复资源和So未生效

手机型号：RedmiK40Pro

手机系统版本：Android 12.0 （S）

tinker版本：1.9.14.19

gradle版本：4.1

是否使用热更新SDK：  TinkerPatch SDK

**Comment by lijinshanmx** [comment]
前几天更新了Android12系统，之前Flutter端的热更新都可以正常工作，但是升级了安卓S系统后，So资源和Assets资源无法生效(注：无dex变动)，【注:(对比测试)同样的apk和patcher补丁，装到IQOO Android 11系统上同时测试没有问题】。

但是如果dex文件发生变化（随便修改一处java文件，让补丁中有dex变化），此时修复So和Assets资源是OK的。

而且Tinker Log中 native lib插入也是正确的，位于So列表的第一个，所以目前来看应该是 Android12系统上有些逻辑发生了改变，导致 虽然So和资源文件修复成功，但是在dex无变动的时候无法起作用。


总结：

Android12系统上：

  补丁中有 dex变动，则So文件以及资源文件都能修复成功且能正确生效。

  补丁中没有dex变动，那么So文件以及资源文件都能修复成功但是 不能生效。

Android11及以下：

  按照预期正确工作。

**Comment by lijinshanmx** [comment]
暂时先自行解决，仅限于Flutter项目。在Android12上 用Tinker生成的修复文件，然后手动插桩补丁目录中的libapp_so库和替换Flutter Engine的需要的AssetsManager（使用修复后补丁目录中的Resources.apk中的资源）。

期待官方的打补丁方式，能对Android12及以上版本兼容~。

**Comment by yaqian** [comment]
请问你的问题是如何解决的呢？我遇到的问题是在Android12系统的手机上图片热更无效，代码热更成功，这个如何解决呢？
