### ISSUE TITLE
对自定义的buildType执行tinkerPatch任务时不能生成补丁包

### ISSUE THREAD

**Issue by zyn4399** [Tencent/tinker#164]
执行debug和release可以生成补丁包，执行其他自定义的就不行

release {
            manifestPlaceholders = [DONGJIA_RN_DEBUG_VALUE: "false",
                                    DONGJIA_DEBUG_VALUE   : "false",
                                    EASEMOB_APPKEY        : "dongjia#dongjia",
                                    CHAT_RECEIVER         : "easemob.newmsg.dongjia.dongjiacc.kaipao.dongjia"]
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

        }
        debug {
            manifestPlaceholders = [DONGJIA_RN_DEBUG_VALUE: "true",
                                    DONGJIA_DEBUG_VALUE   : "true",
                                    EASEMOB_APPKEY        : "dj-teste#dongjia",
                                    CHAT_RECEIVER         : "easemob.newmsg.dj.teste.dongjiacc.kaipao.dongjia"]

            signingConfig signingConfigs.testDebug
        }

        debugRn {
            manifestPlaceholders = [DONGJIA_RN_DEBUG_VALUE: "false",
                                    DONGJIA_DEBUG_VALUE   : "true",
                                    EASEMOB_APPKEY        : "dj-teste#dongjia",
                                    CHAT_RECEIVER         : "easemob.newmsg.dj.teste.dongjiacc.kaipao.dongjia"]

            signingConfig signingConfigs.testDebug
        }
是设计如此吗？

**Comment by shwenzhang** [comment]
其他自定义的需要自己适配保留结果的task
