### ISSUE TITLE
显示修复成功，全退出后，却没有效果

### ISSUE THREAD

**Issue by Lsdjack** [Tencent/tinker#169]
![1111](https://cloud.githubusercontent.com/assets/16152409/20204032/2057f14a-a807-11e6-8a2a-05a30e726608.png)
![2222](https://cloud.githubusercontent.com/assets/16152409/20204035/25246b72-a807-11e6-9084-c675888d7ecb.png)
如图片所示

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/20205346/fd4c889e-a812-11e6-85ff-ea8f7f4d8a92.png)

你根本没有改任何dex啊

**Comment by xiaobaoKing1** [comment]
你的问题解决没？ log和你差不多。 按照流程来的，做了去修改TextView的内容。 提示success但是重启没有效果。 @Lsdjack
