### ISSUE TITLE
tinker-sample-android项目找不到SampleApplication类

### ISSUE THREAD

**Issue by mwping** [Tencent/tinker#17]
[AndroidManifest.xml](https://github.com/Tencent/tinker/blob/dev/tinker-sample-android/app/src/main/AndroidManifest.xml)

项目里并没有SampleApplication这个类，麻烦确认一下，thx

**Comment by shwenzhang** [comment]
SampleApplication是运行时自动生成的，请认真查看文档

**Comment by CSnowStack** [comment]
请问,原本已经有application的话, ApplicationLike要怎么写,原本application里的代码写在哪

**Comment by shwenzhang** [comment]
把application的代码都移动到ApplicationLike中，参考Sample的做法即可

**Comment by CSnowStack** [comment]
好的,谢谢

**Comment by mwping** [comment]
@shwenzhang 看到了，多谢
