### ISSUE TITLE
如果补丁出问题了，支持回滚成打补丁前的dex吗

### ISSUE THREAD

**Issue by listen2code** [Tencent/tinker#170]
1.线上版本A，打了补丁a，这时候如过还有问题，线上版本Aa是否可以恢复成A；如果重新制作补丁b，是基于A制作，还是Aa制作；
2.dex合成是一次操作后，就永久生效么？

**Comment by shwenzhang** [comment]
可以回退，他不影响原本的dex文件。只要cleanpatch即可

**Comment by icespring** [comment]
如果下发了补丁A之后下发补丁B，结果补丁B出问题了，支持回退到补丁A么

**Comment by shwenzhang** [comment]
默认不行，可以重新发布A
