### ISSUE TITLE
新增资源未被识别出差异

### ISSUE THREAD

**Issue by NiuGuohui** [Tencent/tinker#1701]
异常类型：差量编译异常

tinker版本：1.9.14.25.1

gradle版本：4.2.2

是否使用热更新SDK： 是

系统：Mac OS

描述：
新增的layout文件在编译时未被识别出差异，编译出的补丁包内也没有新增的布局文件

这是新增资源后的构建产物：
<img width="337" alt="image" src="https://user-images.githubusercontent.com/37471959/215686366-f8102066-c81e-4ca4-a192-7c8027fd0ab1.png">
其中有名为`GZ.xml`的新增文件
<img width="393" alt="image" src="https://user-images.githubusercontent.com/37471959/215686470-3f948f91-efbc-4602-806f-63d0602984f9.png">

在旧的基准包内确定没有此文件（但是有个区分大小写的名为`gZ.xml`的文件）：
<img width="348" alt="image" src="https://user-images.githubusercontent.com/37471959/215687092-4f1ec4e7-30b1-4331-a19c-95cd80fafe30.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/37471959/215686989-96fbd0d3-9fff-48de-b04c-1033633c475f.png">

构建的日志中也没有检测出新增的`GZ.xml`文件：
[res_log.txt](https://github.com/Tencent/tinker/files/10543566/res_log.txt)
<img width="725" alt="image" src="https://user-images.githubusercontent.com/37471959/215687494-03bc7a4b-f9a0-4ef9-9c48-aeb9a6f87c15.png">

但是在`resources.arsc`中却有指向`GZ.xml`的资源地址：
<img width="912" alt="image" src="https://user-images.githubusercontent.com/37471959/215687874-23852672-e46b-4c9e-8958-e4ca137741d3.png">

造成的问题是，更新后，应用访问此资源时会Crash，找不到这个layout

**Comment by NiuGuohui** [comment]
@tys282000

**Comment by tonyzzp** [comment]
你在windows打的patch吧?
他要先解压apk的，解压后GZ.xml  和gz.xml就一样了。

**Comment by NiuGuohui** [comment]
> 

Mac.....
这个问题基本上确认是Bug了。

**Comment by NiuGuohui** [comment]
> 你在windows打的patch吧? 他要先解压apk的，解压后GZ.xml 和gz.xml就一样了。

Mac.....
这个问题基本上确认是Bug了。

**Comment by NiuGuohui** [comment]
Have a fix PR: #1710

**Comment by NiuGuohui** [comment]
此问题已被解决，另外可以在PR合并前可通过修改构建环境，支持大小写的文件系统即可修复此Bug
