### ISSUE TITLE
java.security.SignatureException: error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length

### ISSUE THREAD

**Issue by zyn4399** [Tencent/tinker#171]
11-13 21:23:02.164 27977-27977/cc.kaipao.dongjia D/Tinker.DefaultAppLike: onTrimMemory level:20
11-13 21:23:03.832 27977-28778/cc.kaipao.dongjia I/Tinker.SamplePatchListener: receive a patch file: /data/data/cc.kaipao.dongjia/tinker/temp.apk, isUpgrade:true, file size:12860
11-13 21:23:03.835 27977-28778/cc.kaipao.dongjia I/Tinker.SamplePatchListener: get platform:all
11-13 21:23:03.836 793-1730/? D/Interception: isInterceptByRule realCallingPid: 27977 isInterceptAsUsual: false isMatch: false, runType===retrieve_service|||callerPkg===cc.kaipao.dongjia|||calleePkg===cc.kaipao.dongjia|||calleeClass===com.tencent.tinker.lib.service.TinkerPatchService|||processName===cc.kaipao.dongjia:patch|||action===*|||data===*|||extras===Bundle[mParcelledData.dataSize=188]|||interception===false
11-13 21:23:03.871 793-1730/? I/ActivityManager: Start proc 28781:cc.kaipao.dongjia:patch/u0a622 for service cc.kaipao.dongjia/com.tencent.tinker.lib.service.TinkerPatchService
11-13 21:23:03.910 28781-28781/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/data/cc.kaipao.dongjia/tinker/patch.info
11-13 21:23:03.913 28781-28781/? D/Tinker.DefaultAppLike: onBaseContextAttached:
11-13 21:23:03.919 28781-28781/? I/Tinker.SamplePatchListener: application maxMemory:256
11-13 21:23:03.921 28781-28781/? W/Tinker.Tinker: tinker patch directory: /data/data/cc.kaipao.dongjia/tinker
11-13 21:23:03.922 28781-28781/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3
11-13 21:23:03.923 28781-28781/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-13 21:23:03.923 28781-28781/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/cc.kaipao.dongjia/tinker, code:-3, cost:3
11-13 21:23:03.923 28781-28781/? W/Tinker.Tinker: tinker load fail!
11-13 21:23:03.925 28781-28781/? D/Tinker.DefaultAppLike: onCreate
11-13 21:23:03.994 28781-28781/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@34378fb4 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=cc.kaipao.dongjia intent=null}
11-13 21:23:03.995 28781-28781/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@34378fb4 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=cc.kaipao.dongjia intent=null}
11-13 21:23:03.995 28781-28781/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService@2a937dd, flags=0, startId=1
11-13 21:23:03.995 28781-28781/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@34378fb4 startId=1 args=Intent { cmp=cc.kaipao.dongjia/com.tencent.tinker.lib.service.TinkerPatchService (has extras) }}
11-13 21:23:03.995 28781-28808/? I/Tinker.DefaultPatchReporter: patchReporter: patch service start
11-13 21:23:03.995 28781-28781/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-13 21:23:03.998 28781-28808/? I/Tinker.TinkerPatchService: try to increase patch process priority
11-13 21:23:04.001 793-1437/? D/Interception: isInterceptByRule realCallingPid: 28781 isInterceptAsUsual: false isMatch: false, runType===retrieve_service|||callerPkg===cc.kaipao.dongjia|||calleePkg===cc.kaipao.dongjia|||calleeClass===com.tencent.tinker.lib.service.TinkerPatchService$InnerService|||processName===cc.kaipao.dongjia:patch|||action===*|||data===*|||extras===*|||interception===false
11-13 21:23:04.002 28781-28781/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@3004f52 className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=cc.kaipao.dongjia intent=null}
11-13 21:23:04.003 28781-28781/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@3004f52 className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=cc.kaipao.dongjia intent=null}
11-13 21:23:04.004 28781-28781/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@ab8f223, flags=0, startId=1
11-13 21:23:04.004 28781-28781/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@3004f52 startId=1 args=Intent { cmp=cc.kaipao.dongjia/com.tencent.tinker.lib.service.TinkerPatchService$InnerService }}
11-13 21:23:04.004 28781-28781/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@ab8f223
11-13 21:23:04.016 28781-28808/? E/ShareSecurityCheck: /data/data/cc.kaipao.dongjia/tinker/temp.apk
                                                       java.security.SignatureException: error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
                                                           at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
                                                           at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:349)
                                                           at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:384)
                                                           at org.apache.harmony.security.utils.WrappedX509Certificate.verify(WrappedX509Certificate.java:156)
                                                           at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.check(ShareSecurityCheck.java:184)
                                                           at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:159)
                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:84)
                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:69)
                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:59)
                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:122)
                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                           at android.os.Looper.loop(Looper.java:194)
                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
11-13 21:23:04.016 28781-28808/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:onPatchPackageCheckFail
11-13 21:23:04.016 28781-28808/? I/Tinker.DefaultPatchReporter: patchReporter: package check failed. path:/data/data/cc.kaipao.dongjia/tinker/temp.apk, isUpgrade:true, code:-1
11-13 21:23:04.016 28781-28808/? I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/data/data/cc.kaipao.dongjia/tinker/temp.apk, success:false, cost:18, isUpgrade:true
11-13 21:23:04.016 28781-28808/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/patch.retry
11-13 21:23:04.016 28781-28808/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cc.kaipao.dongjia/tinker/temp.apk
11-13 21:23:04.024 28781-28781/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService@2a937dd
11-13 21:23:04.027 27977-28810/cc.kaipao.dongjia I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                               PatchResult: 
                                                                               isUpgradePatch:true
                                                                               isSuccess:false
                                                                               rawPatchFilePath:/data/data/cc.kaipao.dongjia/tinker/temp.apk
                                                                               costTime:18
11-13 21:23:04.027 27977-27977/cc.kaipao.dongjia E/Tinker.SampleResultService: patch fail, please check reason

**Comment by zyn4399** [comment]
找到原因了，是因为我多渠道打包导致的，打包用一个渠道就好了

**Comment by elton-wang-ch** [comment]
多渠道打包试试什么意思？小弟不才，也遇到相同错误信息，正在寻求解决方法，望前辈指教

**Comment by jiezigg** [comment]
build.gradle里可以配置productFlavors来多渠道打包啊

**Comment by jiezigg** [comment]
build.gradle里可以配置productFlavors来多渠道打包啊
