### ISSUE TITLE
cannot apply resource id when resource name contains dot and its type is id.

### ISSUE THREAD

**Issue by coofee** [Tencent/tinker#172]
当id中包含点号时，patch中的id值和base apk中的同名id的值不一样，详见如下：

activity_main.xml:

![image](https://cloud.githubusercontent.com/assets/2087865/20263459/c246a806-aaa1-11e6-9ed4-31c4b2d0e8ad.png)

applyResources base apk R.txt
<img width="451" alt="370b2c37-8846-404d-8d79-2a9dea4bb661" src="https://cloud.githubusercontent.com/assets/2087865/20263674/c8632aa6-aaa2-11e6-8255-348b7bed9da1.png">

tinkerPatch生成的public.xml
<img width="804" alt="c8f214db-d18c-4556-ad0f-8e50b6bacb26" src="https://cloud.githubusercontent.com/assets/2087865/20263627/88f0667c-aaa2-11e6-98d9-f5855ffcfd8c.png">

日志: 
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/bakApk/app-debug-1114-18-41-02.apk
newApk:~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/apk/app-debug.apk
outputFolder:~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug
isIgnoreWarning:false
isInsertStubMode:false
7-ZipPath:~/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:tinker is sample to use
filed name:platform, filed value:all
filed name:patchVersion, filed value:1.0
dex configs: 
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.tencent.tinker.loader.*
dex loader:tinker.sample.android.app.BaseBuildInfo
dex loader:tinker.sample.android.app.SampleApplication
lib configs: 
libPattern:lib/armeabi/.*\.so
resource configs: 
resPattern:AndroidManifest\.xml
resPattern:resources\.arsc
resPattern:res/.*
resPattern:assets/.*
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: app-debug-1114-18-41-02.apk, size=1384161, md5=f78c6f18c1e5e8f1ba463cfa13731886
new apk: app-debug.apk, size=1384174, md5=e16b585c70b18b6e409b8a5d4ffb7c24

UnZipping apk to ~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/app-debug-1114-18-41-02
UnZipping apk to ~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/app-debug
Check for loader classes in dex: ../app-debug-1114-18-41-02/classes.dex
Found modify resource: res/layout/activity_main.xml
Found modify resource: res/layout-v17/activity_main.xml
ApkParser: resources.arsc is not equal, reason: file size is changed
Found large modify resource: resources.arsc size:190888

Gen classes.dex patch file:~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tinker_result/classes.dex, size:758, md5:6d467fa82445c1b1af611fc69d75ea41
Verifying if patched new dex is logically the same as original new dex: app-debug/classes.dex ...

Gen classes.dex for dalvik full dex file:~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tempPatchedDexes/dalvik/classes.dex, size:2075916, md5:02c390005c3318decc4b9e4172856cc7
Start generating small patch info file...

Gen classes.dex for art small dex file:~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tempPatchedDexes/art/classes.dex, size:4016, md5:59c601ac8d6f86bb337ce7026d8569d5
DexDecoder:write meta file data: classes.dex,,02c390005c3318decc4b9e4172856cc7,59c601ac8d6f86bb337ce7026d8569d5,6d467fa82445c1b1af611fc69d75ea41,1122245297,jar

Add test install result dex: ~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
Add Test resource file: assets/only_use_to_test_tinker_resource.txt
Final normal zip resource: resources_out.zip, size=434025, md5=0de1847dc7a43a95175ca41224a16877
Final 7zip resource: resources_out_7z.zip, size=433995, md5=f5aea550aedcfa6cbc0138e039a5199d
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:~/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
Result: final signed patch result: ~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/patch_signed.apk, size=6220
Result: final signed with 7zip patch result: ~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug/patch_signed_7zip.apk, size=7118
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 898 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 30.413000s
Tinker patch done, you can go to file to find the output ~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/outputs/tinkerPatch/debug
-----------------------Tinker patch end-------------------------

BUILD SUCCESSFUL

修改PatchUtil.generatePublicResourceXml()函数如下，将id中的点转换成下划线时，编译时会出现两个id，名字都是test_dot_name_2m这个，然后编译失败。 

日志: 
:tinker-sample-android:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
~/program/git_proj/plugin/tinker/tinker-sample-android/app/build/generated/source/r/debug/tinker/sample/android/R.java:1687: 错误: 已在类 id中定义了变量 test_dot_name_2m
        public static final int test_dot_name_2m=0x7f0c0067;
                                ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
1 个错误

patch的R.txt
<img width="423" alt="e669eb3b-bc00-41c3-8421-64ee55b15706" src="https://cloud.githubusercontent.com/assets/2087865/20264038/8069cdac-aaa4-11e6-9f32-82a01818b0de.png">

修改代码如下:

```java
            while (iterator.hasNext()) {
                Entry<RType, Set<RDotTxtEntry>> entry = iterator.next();
                RType rType = entry.getKey();
                if (!rType.equals(RType.STYLEABLE)) {
                    Set<RDotTxtEntry> set = entry.getValue();
                    Set<String> ignoreIdSet = aaptResourceCollector.getIgnoreIdSet();

                    for (RDotTxtEntry rDotTxtEntry : set) {
//                        if (rType.equals(RType.STYLE)) {
                            String rawName = aaptResourceCollector.getRawName(rType, rDotTxtEntry.name);
                            if (StringUtil.isBlank(rawName)) {
//                                System.err.println("Blank?" + rDotTxtEntry.name);
                                rawName = rDotTxtEntry.name;
                            }

                            if (!rType.equals(RType.STYLE) && rawName.indexOf(Constant.Symbol.DOT) > 0) {
                                if (rType.equals(RType.ID) && ignoreIdSet.contains(rDotTxtEntry.name)) {
                                    // if entry is ignored id, do nothing;
                                } else {
                                    // replace dot with underscores
                                    String newRawName = rawName.replaceAll("\\.", "\\_");
                                    System.err.println("public.xml; rawName=" + rawName + " has dot, so replace dot with underscores, rawName=" + newRawName);
                                    rawName = newRawName;
                                }
                            }

                            publicWriter.println("<public type=\"" + rType + "\" name=\"" + rawName + "\" id=\"" + rDotTxtEntry.idValue + "\" />");
//                        } else {
//                            publicWriter.println("<public type=\"" + rType + "\" name=\"" + rDotTxtEntry.name + "\" id=\"" + rDotTxtEntry.idValue + "\" />");
//                        }
                    }

                    for (RDotTxtEntry rDotTxtEntry : set) {
                        String rawName = rDotTxtEntry.name;

                        if (rawName.indexOf(Constant.Symbol.DOT) > 0) {
                            String newRawName = rawName.replaceAll("\\.", "\\_");
                            System.err.println("ID.xml; rawName=" + rawName + " has dot, so replace dot with underscores, rawName=" + newRawName);
                            rawName = newRawName;
                        }

                        if (rType.equals(RType.ID) && !ignoreIdSet.contains(rDotTxtEntry.name)) {
                            idsWriter.println("<item type=\"" + rType + "\" name=\"" + rawName + "\"/>");
                        } else if (rType.equals(RType.STYLE)) {

                            if (rDotTxtEntry.name.indexOf(Constant.Symbol.UNDERLINE) > 0) {
//idsWriter.println("<item type=\""+rType+"\" name=\""+(rDotTxtEntry.name.replace(Constant.Symbol.UNDERLINE, Constant.Symbol.DOT))+"\"/>");
                            }
                        }
                    }
                }
                idsWriter.flush();
                publicWriter.flush();
            }

```

**Comment by shwenzhang** [comment]
问题是什么？使用tinker代码，有这个变量可以编译成功
