### ISSUE TITLE
tinkerPatch命令执行成功，但是没有生成补丁apk文件

### ISSUE THREAD

**Issue by coderloveryan** [Tencent/tinker#1737]
异常类型：编译异常

tinker版本：1.9.26

gradle版本: 6.7.1

AGP: 4.2.1

是否使用热更新SDK：否

系统：Mac

日志
[log.txt](https://github.com/Tencent/tinker/files/13682936/log.txt)

执行tinkerPatchshengchanRelease成功了 日志里也有patch_signed相关打印，但是tinker_result目录下没有找到apk
![hBH5gtnF29](https://github.com/Tencent/tinker/assets/10841769/f0d15290-f5ce-48b7-bcfe-dccefeb3d7f6)

**Comment by coderloveryan** [comment]
看了一下1.9.14.26下的build代码Runner和PatchBuilder下没看到会删除的代码，有遇到相同问题的兄弟们么？

**Comment by coderloveryan** [comment]
编译时实时查看文件夹内容确认了一下patchxx相关apk是有的，但是被删除了

**Comment by coderloveryan** [comment]
解决了，找错目录了，虽然日志打印是这个，但是tmp是临时目录最终在build/outputs/apk/flavor下的tinkerPatch

**Comment by coderloveryan** [comment]
解决了，找错目录了，虽然日志打印是这个，但是tmp是临时目录最终在build/outputs/apk/flavor下的tinkerPatch

**Comment by isanwenyu** [comment]
请教一下 你kotlin版本是多少？ @coderloveryan
