### ISSUE TITLE
加载补丁失败Failed to recover dex file /data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes2.dex.jar

### ISSUE THREAD

**Issue by jiyuxuan** [Tencent/tinker#175]
tinker 1.7.3
我的app 设置了 multidexmode 从log 里面看是在替换dex2失败了 
不知道是什么原因
我的gradle 配置和demo里面一样

11-15 14:55:17.643 15247-15247/com.tencent.example D/Tinker: ------------patchInfo=[patch is not loaded] 
                                                                 [buildConfig CLIENTVERSION] e656c9a 
                                                                 [buildConfig MESSSAGE] I am the base apk 
                                                                 [TINKER_ID] e656c9a 
                                                                 [BaseBuildInfo Message] I won't change with tinker patch! 
11-15 14:55:17.646 15247-15247/com.tencent.example D/Tinker: ------------onReceiveUpgradePatch
11-15 14:55:17.647 15247-15247/com.tencent.example I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:7268
11-15 14:55:17.660 15247-15247/com.tencent.example I/Tinker.SamplePatchListener: get platform:all
                                                                                     
                                                                                     --------- beginning of system
11-15 14:55:17.812 18828-18828/com.tencent.example:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.tencent.example/tinker
11-15 14:55:17.816 18828-18828/com.tencent.example:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
11-15 14:55:17.824 18828-18828/com.tencent.example:patch I/Tinker.SamplePatchListener: application maxMemory:128
11-15 14:55:17.829 18828-18828/com.tencent.example:patch W/Tinker.Tinker: tinker patch directory: /data/data/com.tencent.example/tinker
11-15 14:55:17.831 18828-18828/com.tencent.example:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
11-15 14:55:17.831 18828-18828/com.tencent.example:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-15 14:55:17.831 18828-18828/com.tencent.example:patch I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/com.tencent.example/tinker, code:-2, cost:4
11-15 14:55:17.832 18828-18828/com.tencent.example:patch W/Tinker.Tinker: tinker load fail!
11-15 14:55:17.832 18828-18828/com.tencent.example:patch D/Tinker.DefaultAppLike: onCreate
11-15 14:55:18.321 18828-18905/com.tencent.example:patch I/Tinker.DefaultPatchReporter: patchReporter: patch service start
11-15 14:55:18.330 18828-18905/com.tencent.example:patch W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch_signed_7zip.apk to /data/data/com.tencent.example/tinker/temp.apk
11-15 14:55:18.354 18828-18905/com.tencent.example:patch I/Tinker.TinkerPatchService: try to increase patch process priority
11-15 14:55:18.419 18828-18905/com.tencent.example:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:dexDiffMd5:34d0cc3193c947ff7588c47dab5a0da6
11-15 14:55:18.419 18828-18905/com.tencent.example:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.tencent.example/tinker/patch-34d0cc31
11-15 14:55:18.421 18828-18828/com.tencent.example:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-15 14:55:18.422 18828-18905/com.tencent.example:patch W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/patch_signed_7zip.apk size:7268, /data/data/com.tencent.example/tinker/patch-34d0cc31/patch-34d0cc31.apk size:7268
11-15 14:55:23.357 18828-18905/com.tencent.example:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes.dex.jar, use time: 4899
11-15 14:55:26.268 18828-18905/com.tencent.example:patch W/Tinker.DexDiffPatchInternal: Failed to recover dex file /data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes2.dex.jar
11-15 14:55:26.269 18828-18905/com.tencent.example:patch I/Tinker.DefaultPatchReporter: patchReporter: file extract fail type:dex_art, path:/data/data/com.tencent.example/tinker/patch-34d0cc31/patch-34d0cc31.apk, extractTo:/data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes2.dex.jar, filename:classes2.dex, isUpgrade:true
11-15 14:55:26.270 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch-34d0cc31/patch-34d0cc31.apk
11-15 14:55:26.271 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes.dex.jar
11-15 14:55:26.271 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes2.dex.jar
11-15 14:55:26.271 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch-34d0cc31/dex
11-15 14:55:26.271 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch-34d0cc31
11-15 14:55:26.271 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch-34d0cc31/dex/classes2.dex.jar
11-15 14:55:26.272 18828-18905/com.tencent.example:patch W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
11-15 14:55:26.272 18828-18905/com.tencent.example:patch I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:7849, isUpgradePatch:true
11-15 14:55:26.272 18828-18905/com.tencent.example:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
11-15 14:55:26.272 18828-18905/com.tencent.example:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:false, cost:7919, isUpgrade:true
11-15 14:55:26.272 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/patch.retry
11-15 14:55:26.272 18828-18905/com.tencent.example:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.example/tinker/temp.apk
11-15 14:55:26.295 15247-19093/com.tencent.example I/Tinker.TinkerResultService: TinkerResultService receive result: 
                                                                                     PatchResult: 
                                                                                     isUpgradePatch:true
                                                                                     isSuccess:false
                                                                                     rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                                     costTime:7919
                                                                                     patchVersion:34d0cc3193c947ff7588c47dab5a0da6
                                                                                     patchTinkerID:e656c9a
                                                                                     baseTinkerID:e656c9a
11-15 14:56:55.520 15247-15247/com.tencent.example D/Tinker.DefaultAppLike: onTrimMemory level:20
11-15 14:56:59.846 21311-21311/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/data/com.tencent.example/tinker/patch.info
11-15 14:56:59.853 21311-21311/? D/Tinker.DefaultAppLike: onBaseContextAttached:
11-15 14:56:59.865 21311-21311/? I/Tinker.SamplePatchListener: application maxMemory:128
11-15 14:56:59.870 21311-21311/? W/Tinker.Tinker: tinker patch directory: /data/data/com.tencent.example/tinker
11-15 14:56:59.872 21311-21311/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3
11-15 14:56:59.873 21311-21311/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-15 14:56:59.873 21311-21311/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/com.tencent.example/tinker, code:-3, cost:4
11-15 14:56:59.873 21311-21311/? W/Tinker.Tinker: tinker load fail!
11-15 14:56:59.873 21311-21311/? D/Tinker.DefaultAppLike: onCreate
11-15 14:57:00.596 21391-21391/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/data/com.tencent.example/tinker/patch.info
11-15 14:57:00.601 21391-21391/? D/Tinker.DefaultAppLike: onBaseContextAttached:
11-15 14:57:00.604 21391-21391/? D/Tinker.DefaultAppLike: onCreate
11-15 14:57:01.059 21311-21311/com.tencent.example W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
11-15 14:57:05.166 21311-21311/com.tencent.example D/Tinker: ------------I am from old apk

**Comment by tomystang** [comment]
已知问题，下个版本修复。

**Comment by jiyuxuan** [comment]
请问下个版本大概什么时间发布

**Comment by tomystang** [comment]
这周五会发

**Comment by shwenzhang** [comment]
try with 1.7.5
