### ISSUE TITLE
小米手机兼容问题

### ISSUE THREAD

**Issue by quanquan521** [Tencent/tinker#1757]
异常类型：app运行时异常

手机型号：XiaoMi/MIUI 

手机系统版本：Android 14,level 34

tinker版本：1.9.14.26.3

gradle版本：7.0.4

是否使用热更新SDK：TinkerPatch 

系统：window

堆栈/日志：

No direct method <init>(Lcom/yzq/order/FirmOrderActivity;)V in class Lcom/yzq/order/v0; or its super classes (declaration of 'com.yzq.order.v0' appears in /data/user/0/com.yzq/tinker/patch-a508fa76/dex/tinker_classN.apk!classes3.dex)

只有XiaoMi/MIUI 出现问题，其他手机正常。

**Comment by canlan818** [comment]
这是来自QQ邮箱的自动回复邮件。您好，来信已收到，谢谢您，我会及时回复您的！O(∩_∩)O~
