### ISSUE TITLE
Error:(34, 0) Cause: can't get git rev, you should add git to system path or just input test value, such as 'testTinkerId' <a href="openFile:D:\workspace\tinker-sample-android\app\build.gradle">Open File</a>

### ISSUE THREAD

**Issue by FrameJack** [Tencent/tinker#178]
这个问题好像没有人提问吧，能给个回复嘛，大神
Error:(34, 0) Cause: can't get git rev, you should add git to system path or just input test value, such as 'testTinkerId'

**Comment by shwenzhang** [comment]
Error:(34, 0) Cause: can't get git rev, you should add git to system path or just input test value, such as 'testTinkerId'
错误不是已经说的很清楚。

![image](https://cloud.githubusercontent.com/assets/8335303/20336761/a8b4eca6-ac07-11e6-9a48-91b72671132f.png)
