### ISSUE TITLE
patch后加载so报多条Total arena pages for JIT，然后crash

### ISSUE THREAD

**Issue by theYY** [Tencent/tinker#179]
机型：HM NOTE 1S CU
Android版本：4.4.4

base版本和new版本直接运行时没有问题，base版本和new版本存在代码修改，资源替换和资源新增。
base版本通过下发patch成功，资源替换，代码替换确认成功。
但是在进入需要加载so的模块时会连续报多条下面信息，然后crash。so大小400K左右，base和new间未修改。
11-18 10:44:47.961 12442-12449/ I/dalvikvm:Total arena pages for JIT: 13
11-18 10:44:47.961 12442-12449/ I/dalvikvm:Total arena pages for JIT: 14
11-18 10:44:47.961 12442-12449/ I/dalvikvm:Total arena pages for JIT: 15
11-18 10:44:47.961 12442-12449/ I/dalvikvm:Total arena pages for JIT: 16
11-1810:44:47.961 12442-12449/ I/dalvikvm: Total arena pages for JIT: 17
11-1810:44:47.961 12442-12449/ I/dalvikvm: Total arena pages for JIT: 18
11-1810:44:47.961 12442-12449/ I/dalvikvm: Total arena pages for JIT: 19
11-18 10:44:47.961 12442-12449/ I/dalvikvm:Total arena pages for JIT: 20
...
11-18 10:44:48.031 12442-12449/ I/dalvikvm:Total arena pages for JIT: 212

**Comment by theYY** [comment]
使用tinker版本：1.7.3

**Comment by shwenzhang** [comment]
将详细的crash跟加载日志贴上来把，上面那个只是warning

**Comment by theYY** [comment]
可以忽略上面的warning，crash原因是某处空指针异常，但是正常安装不会有该异常，不知道tinker是否会有这样的影响。

**Comment by shwenzhang** [comment]
试一下1.7.5

**Comment by theYY** [comment]
1.7.5还是会发生同样的空指针异常问题，发生问题时我的app会启动另外两个进程，存在进程间通信，不知道跟这个有没有关系，具体细节后面再添加。

**Comment by shwenzhang** [comment]
还是把详细的日志发出来，描述现象根本没有意义
