### ISSUE TITLE
为什么生成release包就会出错

### ISSUE THREAD

**Issue by nielev** [Tencent/tinker#182]
基本都是粘贴sample的配置，不知道哪里出了问题，debug就是可以的，release就是不行，希望能知道为什么，谢谢

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:tinkerPatchBaiduRelease'.
> Could not get unknown property 'taskName' for task ':app:tinkerPatchBaiduRelease' of type com.tencent.tinker.build.gradle.task.TinkerPatchSc
hemaTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by 1242128273wangpeng** [comment]
我也出现过这情况，一直不知道怎么解决就没去弄了

**Comment by nielev** [comment]
这个问题找到原因了，需要在build里面配置这个，我之前配置了，但是没有跟signingConfig关联，就是这句话signingConfig signingConfigs.release。希望下一个遇到这个问题的人别像我一样找了快一天才找到这个坑
signingConfigs {
        release {
           storeFile file("./keystore/release.keystore")
                storePassword "testres"
                keyAlias "testres"
                keyPassword "testres"
        }
    }
buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
