### ISSUE TITLE
如果针对不同渠道包，只用一个补丁文件，会有什么影响吗

### ISSUE THREAD

**Issue by nielev** [Tencent/tinker#184]
问一下，如果针对不同flavor渠道包，只用一个补丁文件，会出现无法合成补丁的问题吗，我试了一下联想渠道的补丁打给华为渠道包，好像没什么问题。一定要一个补丁对应一个渠道包吗

**Comment by nielev** [comment]
还是用androidmanifest的方式吧

**Comment by shwenzhang** [comment]
看文档！
