### ISSUE TITLE
请教下,集成在我的项目中运行Task:assembleDebug,总在这splashActivity:compileDebugJavaWithJavac运行Task出错,在没把simple demo的代码拷贝过来之前,光配置gradle是没有问题的.

### ISSUE THREAD

**Issue by wyh497823256** [Tencent/tinker#186]

**Comment by shwenzhang** [comment]
这种issue的提问方式是不符合规范的，需要将详细的错误日志贴出来

**Comment by wyh497823256** [comment]
![image](https://cloud.githubusercontent.com/assets/8830870/20511485/cd865c26-b0b3-11e6-8f5e-628a2364090c.png)

**Comment by shwenzhang** [comment]
@wyh497823256 是错误日志，点一下左上角的a/b

**Comment by wyh497823256** [comment]
@shwenzhang

**Comment by wyh497823256** [comment]
感谢 大神,一直没发现这个功能,看了日志解决了问题.因为在SampleUncaughtExceptionHandler包引用出问题了.
