### ISSUE TITLE
请教一下：patch fail, please check reason，tinker-sample-android  code = -3 

### ISSUE THREAD

**Issue by superLY91** [Tencent/tinker#187]
![image](https://cloud.githubusercontent.com/assets/5880785/20512552/f9f009cc-b0ba-11e6-858e-c818cd466395.png)

**Comment by shwenzhang** [comment]
此类问题一律应该先看文档

**Comment by superLY91** [comment]
文档已经看过了，是这个code吧，ShareConstants.ERROR_LOAD_PATCH_INFO_NOT_EXIST = -3
之前1.7.2sample是正常跑通的，更新到最新1.7.5 发现一直失败。

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/20513355/4c3b1398-b0c0-11e6-86ab-a723d93ebd29.png)
日志已经非常明显了，基准包不一致

**Comment by superLY91** [comment]
感谢！是基准包的问题，我使用的是运行完tinkerPatchDebug之后build/outputs/app-debug.apk
