### ISSUE TITLE
tinker 1.62版本出现 java.lang.NoClassDefFoundError: qalsdk.ah

### ISSUE THREAD

**Issue by lichangqiang** [Tencent/tinker#190]
11-22 14:52:26.415 357-357/? E/tinker: logfile:TIME=1440963584000
                                       FINGERPRINT=Huawei/PE-TL20/hwPE:4.4.2/HuaweiPE-TL20/CHNC00B200:user/ota-rel-keys,release-keys
                                       replacements=[Ljava.lang.String;@41600ff8
                                       HARDWARE=hi3630
                                       matchers=[Ljava.lang.String;@41600e78
                                       UNKNOWN=unknown
                                       RADIO=unknown
                                       BOARD=PE-TL20
                                       PRODUCT=PE-TL20
                                       DISPLAY=PE-TL20V100R001CHNC00B200
                                       USER=jenkins
                                       HOST=android14
                                       DEVICE=hwPE
                                       HIDE_PRODUCT_INFO=false
                                       TAGS=ota-rel-keys,release-keys
                                       MODEL=PE-TL20
                                       BOOTLOADER=unknown
                                       CPU_ABI=armeabi-v7a
                                       CPU_ABI2=armeabi
                                       IS_DEBUGGABLE=false
                                       ID=HuaweiPE-TL20
                                       SERIAL=F8UDU16308010204
                                       MANUFACTURER=HUAWEI
                                       BRAND=Huawei
                                       TYPE=user
                                       java.lang.NoClassDefFoundError: qalsdk.ah
                                           at qalsdk.aj.a(SourceFile:385)
                                           at qalsdk.aj.a(SourceFile:98)
                                           at com.tencent.qalsdk.core.j.a(SourceFile:204)
                                           at com.tencent.qalsdk.service.QalService.serviceInit(SourceFile:272)
                                           at com.tencent.qalsdk.service.QalService.onCreate(SourceFile:221)
                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:2702)
                                           at android.app.ActivityThread.access$2100(ActivityThread.java:139)
                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1348)
                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                           at android.os.Looper.loop(Looper.java:136)
                                           at android.app.ActivityThread.main(ActivityThread.java:5315)
                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                           at dalvik.system.NativeStart.main(Native Method)
                                       
                                       {"3975":"{\"APPLY_PATCH\":{\"onFastCrashProtect\":\"code=7\"}}"}

机型：Huawei PE-TL20
补丁打成功后重新启动造成上述问题。其他机型暂无发现

**Comment by lichangqiang** [comment]
Tinker Log记录

11-22 14:51:24.140 31730-31809/? I/Tinker.DefaultPatchReporter: patchReporter: patch service start
11-22 14:51:24.140 31730-31730/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-22 14:51:24.380 31730-31809/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/Download/jumeiyoupin_3974-3.zip to /data/data/com.jm.android.jumei/tinker/temp.apk
11-22 14:51:24.520 31730-31809/? I/Tinker.TinkerPatchService: try to increase patch process priority
11-22 14:51:25.090 31730-31809/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:dexDiffMd5:a786b7e0a0ca17865daa1dceaba6600d
11-22 14:51:25.090 31730-31809/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.jm.android.jumei/tinker/patch-a786b7e0
11-22 14:51:25.135 31730-31809/? W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/Download/jumeiyoupin_3974-3.zip size:6422042, /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/patch-a786b7e0.apk size:6422042
11-22 14:51:34.510 31730-31809/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/dex/classes.dex.jar, use time: 9177
11-22 14:51:42.830 31730-31809/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/dex/classes2.dex.jar, use time: 8316
11-22 14:51:42.830 31730-31809/? I/Tinker.DexDiffPatchInternal: try Extracting /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/dex/test.dex.jar
11-22 14:51:42.830 31730-31809/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
11-22 14:51:44.940 31730-31809/? I/Tinker.DexDiffPatchInternal: success dex optimize file, path: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/dex/classes.dex.jar, use time: 2107
11-22 14:51:46.560 31730-31809/? I/Tinker.DexDiffPatchInternal: success dex optimize file, path: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/dex/classes2.dex.jar, use time: 1618
11-22 14:51:46.635 31730-31809/? I/Tinker.DexDiffPatchInternal: success dex optimize file, path: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/dex/test.dex.jar, use time: 76
11-22 14:51:46.635 31730-31809/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:21493, isUpgradePatch:true
11-22 14:51:46.640 31730-31809/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
11-22 14:51:46.690 31730-31809/? I/Tinker.ResDiffPatchInternal: res dir: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/res/, meta: resArscMd5:be54ef981b502ab299f008a3a5994676
                                                                arscBaseCrc:3597417099
                                                                pattern:res/.*
                                                                pattern:assets/.*
                                                                pattern:r/.*
                                                                pattern:resources\.arsc
                                                                modifiedSet:res/drawable-ldrtl-hdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
                                                                modifiedSet:res/drawable-ldrtl-hdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
                                                                modifiedSet:res/drawable-ldrtl-hdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
                                                                modifiedSet:res/drawable/confirm_red.png
                                                                modifiedSet:res/drawable/commit_error.png
                                                                modifiedSet:res/drawable/redenvelope_bottom_red.png
                                                                modifiedSet:res/drawable/userimage.png
                                                                modifiedSet:res/drawable/confirm_bg_red.png
                                                                modifiedSet:res/drawable/info.png
                                                                modifiedSet:res/drawable/dash_line_hori.png
                                                                modifiedSet:res/drawable/video_to_full_screen.png
                                                                modifiedSet:res/drawable/icon_short_cut.png
                                                                modifiedSet:res/drawable/img_home_small_clickload_d.png
                                                                modifiedSet:res/drawable/video_to_normal_screen.png
                                                                modifiedSet:res/drawable/img_home_small_clickload_s.png
                                                                modifiedSet:res/drawable/little_heart_3.png
                                                                modifiedSet:res/drawable/commit_complate.png
                                                                modifiedSet:res/drawable/redenvelope_bottom_gray.png
                                                                modifiedSet:res/drawable-ldrtl-xxhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
                                                                modifiedSet:res/drawable-ldrtl-xxhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
                                                                modifiedSet:res/drawable-ldrtl-xxhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/img_host_setting_volume.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/recharge_new.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/record_sound_time_too_short.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/special_comment.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/im_send_failed_pressed.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/img_share_we_chat.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/icon_personal_letter_gray.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/im_emoji_delete.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/cou_tuan_go_bg.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/ic_close.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/jm_new_title_back_white_icon.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_detail_new_more_btn.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/msg_tab_heart_normal.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/img_share_sina_weibo.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/share_atention_1.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/cs_photo.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/cs_red.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_detail_more_praise_count.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/search_edit_delete.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/cs_voice_express_right.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_publish_bg_new.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/user_center_modify_user_info_toast.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/accept_redpacket.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/im_chat_text_burn.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/img_guanzhu_grey.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/address_item_not_select.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_img_nofriends.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/icon_video_play.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_like_icon.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/search_more_icon.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_share_bg_new.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/exit_btn_gray.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/share_sms.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_index_small_live_bg.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/share_qzone.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/msg_tab_heart_selected.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/blog_forward_comment_no.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/share_atention_5.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/switch_bg_grey.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/point_highlight.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_product_currency.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/reward_back_new.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/social_detail_btn_guanzhu_ed.png
                                                                modifiedSet:res/drawable-xxhdpi-v4/abc_scrubber_control_off_mtrl_alpha.png
                                                                modifiedSet:res/dr
11-22 14:51:47.180 31730-31809/? W/Tinker.ResDiffPatchInternal: success recover large modify file:/data/data/com.jm.android.jumei/tinker/patch-a786b7e0/res/resources.arsc , file size:1316128, use time:359
11-22 14:51:47.180 31730-31809/? W/Tinker.ResDiffPatchInternal: success recover all large modify use time:492
11-22 14:51:50.315 31730-31809/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.jm.android.jumei/tinker/patch-a786b7e0/res/resources.arsc
11-22 14:51:50.500 31730-31809/? I/Tinker.ResDiffPatchInternal: final new resource file:/data/data/com.jm.android.jumei/tinker/patch-a786b7e0/res/resources.apk, entry count:3611, size:8983225
11-22 14:51:50.500 31730-31809/? I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:3849, isNewPatch:true
11-22 14:51:50.500 31730-31809/? I/PatchInfo: rewritePatchInfoFile file path:/data/data/com.jm.android.jumei/tinker/patch.info , oldVer:, newVer:a786b7e0a0ca17865daa1dceaba6600d
11-22 14:51:50.505 31730-31809/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
11-22 14:51:50.505 31730-31809/? I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/Download/jumeiyoupin_3974-3.zip, success:true, cost:25984, isUpgrade:true
11-22 14:51:50.505 31730-31809/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.jm.android.jumei/tinker/patch.retry
11-22 14:51:50.505 31730-31809/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.jm.android.jumei/tinker/temp.apk
11-22 14:51:50.545 31231-31870/? I/Tinker.SampleResultService: SampleResultService receive result: 
                                                               PatchResult: 
                                                               isUpgradePatch:true
                                                               isSuccess:true
                                                               rawPatchFilePath:/storage/emulated/0/Download/jumeiyoupin_3974-3.zip
                                                               costTime:25984
                                                               patchVersion:a786b7e0a0ca17865daa1dceaba6600d
                                                               patchTinkerID:3970
                                                               baseTinkerID:3970

**Comment by shwenzhang** [comment]
这个应该是一个已知问题，后面换到1.7.5吧，等周五微信灰度结果出来之后
