### ISSUE TITLE
app成功合并加载完补丁(已经看到了修改之后的效果),然后无论怎么修改代码 ,通过as runAPP的方式运行, 看不到任何修改之后的效果

### ISSUE THREAD

**Issue by llmsparkbbbboy** [Tencent/tinker#192]
以下是我的操作流程
1. 生成基准apk 
2. 成功生成补丁包
3. 成功加载安装了补丁包
4. 问题就出现在这里  --->在as上修改了部分代码之后(简单添加了一个log), 执行pm 操作,  但是app 重启之后没有做出相应的变化.

**Comment by shwenzhang** [comment]
不要这样提问issue，请先看文档与sample代码！

**Comment by llmsparkbbbboy** [comment]
pm install  命令 对打过补丁包的 APP 没有任何效果
