### ISSUE TITLE
关于客户端是否拉取到补丁的判断

### ISSUE THREAD

**Issue by vihuela** [Tencent/tinker#193]
怎么确定客户端是否拉取到补丁了？
TinkerServerManager.installTinkerServer(getApplication(), Tinker.with(getApplication()), 3);
之后，在SamplePatchRequestCallback中，一直走onPatchSyncFail 回调：

> java.io.FileNotFoundException: http://q.tinkerpatch.com/330d94fe4e200800/1.0.0?d=fd119223-38a5-45e5-ade4-ff7912f7f5ae&v=1479803868170

已配置appKey这些，然后本地补丁可成功应用，php管理页已上传补丁
①怎么确定与后台的连接配置无误，已设置key这些
②在php管理页上传补丁有个版本，怎么累加的？
③怎么查看获取补丁成功与否？

**Comment by shwenzhang** [comment]
这部分问题请到 https://github.com/simpleton/tinker_server_client/issues 这边提问
