### ISSUE TITLE
小米5 手机  补丁合成成功，加载失败

### ISSUE THREAD

**Issue by Mongolian** [Tencent/tinker#197]
11-23 10:21:36.199 18698-18698/com.demo.test W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
11-23 10:21:36.207 18698-18698/com.demo.test D/Tinker.TinkerInternals: same fingerprint:Xiaomi/gemini/gemini:6.0.1/MXB48T/V8.1.1.0.MAACNDI:user/release-keys
11-23 10:21:36.224 18698-18698/com.demo.test W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.demo.test count:0
11-23 10:21:36.229 18698-18698/com.demo.test W/Tinker.TinkerLoader: after tinker safe mode count:1
11-23 10:21:36.229 18698-18698/com.demo.test I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.demo.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.test-1/lib/arm, /data/app/com.demo.test-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
11-23 10:21:36.257 18698-18698/com.demo.test W/Tinker.ClassLoaderAdder: checkDexInstall result:false
11-23 10:21:36.258 18698-18698/com.demo.test E/Tinker.TinkerDexLoader: install dexes failed
11-23 10:21:36.259 18698-18698/com.demo.test W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
11-23 10:21:36.262 18698-18698/com.demo.test D/Tinker.DefaultAppLike: onBaseContextAttached:
11-23 10:21:36.266 18698-18698/com.demo.test I/Tinker.SamplePatchListener: application maxMemory:256
11-23 10:21:36.268 18698-18698/com.demo.test W/Tinker.Tinker: tinker patch directory: /data/user/0/com.demo.test/tinker
11-23 10:21:36.269 18698-18698/com.demo.test I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14
11-23 10:21:36.269 18698-18698/com.demo.test I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:b2cecd31feddc51f76e0389d378d2308, current:b2cecd31feddc51f76e0389d378d2308
11-23 10:21:36.269 18698-18698/com.demo.test I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
11-23 10:21:36.271 18698-18698/com.demo.test E/Tinker.DefaultLoadReporter: tinker dex check fail:Tinker Exception:checkDexInstall failed
11-23 10:21:36.275 18698-18698/com.demo.test I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
11-23 10:21:36.275 18698-18698/com.demo.test E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
11-23 10:21:36.276 18698-18698/com.demo.test E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                                  at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:79)
                                                                                  at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:137)
                                                                                  at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:222)
                                                                                  at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:169)
                                                                                  at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134)
                                                                                  at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
                                                                                  at android.app.Application.attach(Application.java:191)
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4716)
                                                                                  at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
11-23 10:21:36.277 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/patch-b2cecd31.apk
11-23 10:21:36.278 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex/classes.dex.jar
11-23 10:21:36.279 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex/classes2.dex.jar
11-23 10:21:36.281 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex/classes3.dex.jar
11-23 10:21:36.284 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex/classes4.dex.jar
11-23 10:21:36.285 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex/classes5.dex.jar
11-23 10:21:36.285 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex/test.dex.jar
11-23 10:21:36.285 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex/classes.dex.dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex/classes2.dex.dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex/classes3.dex.dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex/classes5.dex.dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex/classes4.dex.dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex/test.dex.dex
11-23 10:21:36.286 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/odex
11-23 10:21:36.287 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/res/resources.apk
11-23 10:21:36.312 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31/res
11-23 10:21:36.312 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-b2cecd31
11-23 10:21:36.312 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/info.lock
11-23 10:21:36.312 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch.info
11-23 10:21:36.313 18698-18698/com.demo.test I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker

**Comment by shwenzhang** [comment]
小米5是不会出现这个问题，把你编译的日志也给一下

**Comment by Mongolian** [comment]
下面是我的加载补丁的日志
I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:421336
11-24 15:56:33.445 19238-19238/com.demo.test I/Tinker.SamplePatchListener: get platform:all
11-24 15:56:33.462 1335-1992/? I/ActivityManager: Start proc 20164:com.demo.test:patch/u0a180 for service com.demo.test/com.tencent.tinker.lib.service.TinkerPatchService
11-24 15:56:33.561 20164-20164/com.demo.test:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.demo.test/tinker
11-24 15:56:33.568 20164-20164/com.demo.test:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
11-24 15:56:33.578 20164-20164/com.demo.test:patch I/Tinker.SamplePatchListener: application maxMemory:256
11-24 15:56:33.583 20164-20164/com.demo.test:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.demo.test/tinker
11-24 15:56:33.584 20164-20164/com.demo.test:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
11-24 15:56:33.584 20164-20164/com.demo.test:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-24 15:56:33.585 20164-20164/com.demo.test:patch I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/com.demo.test/tinker, code:-2, cost:3
11-24 15:56:33.585 20164-20164/com.demo.test:patch W/Tinker.Tinker: tinker load fail!
11-24 15:56:33.932 20164-20164/com.demo.test:patch D/Tinker.DefaultAppLike: onCreate
11-24 15:56:33.936 20164-20197/com.demo.test:patch I/Tinker.DefaultPatchReporter: patchReporter: patch service start
11-24 15:56:33.955 20164-20197/com.demo.test:patch W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch_signed_7zip.apk to /data/user/0/com.demo.test/tinker/temp.apk
11-24 15:56:33.958 20164-20164/com.demo.test:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-24 15:56:33.964 20164-20197/com.demo.test:patch I/Tinker.TinkerPatchService: try to increase patch process priority
11-24 15:56:33.967 1335-1383/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.demo.test/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
11-24 15:56:33.978 1335-1383/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.demo.test/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
11-24 15:56:34.059 20164-20197/com.demo.test:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:876757df71e39627c9c6eda04775cc32
11-24 15:56:34.059 20164-20197/com.demo.test:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.demo.test/tinker/patch-876757df
11-24 15:56:34.065 20164-20197/com.demo.test:patch W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/patch_signed_7zip.apk size:421336, /data/user/0/com.demo.test/tinker/patch-876757df/patch-876757df.apk size:421336
11-24 15:56:34.105 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.demo.test/tinker/patch-876757df/dex/classes.dex.jar
11-24 15:56:34.521 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
11-24 15:56:43.725 20164-20197/com.demo.test:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.demo.test/tinker/patch-876757df/dex/classes2.dex.jar, use time: 9174
11-24 15:56:43.726 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.demo.test/tinker/patch-876757df/dex/classes3.dex.jar
11-24 15:56:45.004 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
11-24 15:56:45.102 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.demo.test/tinker/patch-876757df/dex/classes4.dex.jar
11-24 15:56:45.463 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
11-24 15:56:45.491 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.demo.test/tinker/patch-876757df/dex/classes5.dex.jar
11-24 15:56:45.517 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
11-24 15:56:45.521 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.demo.test/tinker/patch-876757df/dex/test.dex.jar
11-24 15:56:45.523 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
11-24 15:56:58.463 20164-20197/com.demo.test:patch I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:24397, isUpgradePatch:true
11-24 15:56:58.465 20164-20197/com.demo.test:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
11-24 15:56:58.474 20164-20197/com.demo.test:patch I/Tinker.ResDiffPatchInternal: res dir: /data/user/0/com.demo.test/tinker/patch-876757df/res/, meta: resArscMd5:ac715b290af052556063ede707e4e561
                                                                                     arscBaseCrc:3249781952
                                                                                     pattern:res/.*
                                                                                     pattern:assets/.*
                                                                                     pattern:resources\.arsc
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_000.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_015.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_000.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_015.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_clear_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_menu_share_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_search_api_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_star_black_16dp.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_star_black_36dp.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_star_half_black_16dp.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_star_half_black_36dp.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_focused_holo.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_scrubber_control_off_mtrl_alpha.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_scrubber_control_to_pressed_mtrl_000.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_scrubber_control_to_pressed_mtrl_005.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_scrubber_track_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/actionbar_shadow.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/banner_operate_.png
                                                                                     addedSet:res/drawable-hdpi-v4/bar_atoz.png
                                                                                     addedSet:res/drawable-hdpi-v4/bar_atoz_trans.png
                                                                                     addedSet:res/drawable-hdpi-v4/btn_white_nor.png
                                                                                     addedSet:res/drawable-hdpi-v4/btn_white_press.png
                                                                                     addedSet:res/drawable-hdpi-v4/camera_crop_height.png
                                                                                     addedSet:res/drawable-hdpi-v4/camera_crop_width.png
                                                                                     addedSet:res/drawable-hdpi-v4/chat_send_time_bg.9.png
                                                                                     addedSet:res/drawable-hdpi-v4/common_full_open_on_phone.png
                                                                                     addedSet:res/drawable-hdpi-v4/default_ptr_flip.png
                                                                                     addedSet:res/drawable-hdpi-v4/definition_normal.png
                                                                                     addedSet:res/drawable-hdpi-v4/definition_selected.png
                                                                                     addedSet:res/drawable-hdpi-v4/face_del_ico_dafeult.png
                                                                                     addedSet:res/
11-24 15:56:58.990 20164-20197/com.demo.test:patch W/Tinker.ResDiffPatchInternal: success recover large modify file:/data/user/0/com.demo.test/tinker/patch-876757df/res/resources.arsc , file size:1504272, use time:463
11-24 15:56:58.990 20164-20197/com.demo.test:patch W/Tinker.ResDiffPatchInternal: success recover all large modify use time:515
11-24 15:57:01.925 20164-20197/com.demo.test:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch-876757df/res/resources.arsc
11-24 15:57:01.971 20164-20197/com.demo.test:patch I/Tinker.ResDiffPatchInternal: final new resource file:/data/user/0/com.demo.test/tinker/patch-876757df/res/resources.apk, entry count:7595, size:37760380
11-24 15:57:01.971 20164-20197/com.demo.test:patch I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:3506, isNewPatch:true
11-24 15:57:01.974 20164-20197/com.demo.test:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
11-24 15:57:01.974 20164-20197/com.demo.test:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:true, cost:28010, isUpgrade:true
11-24 15:57:01.975 20164-20197/com.demo.test:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/patch.retry
11-24 15:57:01.975 20164-20197/com.demo.test:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.demo.test/tinker/temp.apk

**Comment by shwenzhang** [comment]
麻烦再给一下编译时的日志

**Comment by shwenzhang** [comment]
问题的原因在于只修改了其他dex，而没有修改主dex。直接提取旧的classes.dex时，没有去remove loader 类

**Comment by shwenzhang** [comment]
在dev分支已经fix该问题

**Comment by motcwang** [comment]
三星S7，也有类似问题，Patch成功，Install失败，请问具体什么时候发布下一版。日志如下：
```
12-05 15:29:07.700 17220-17220/com.xxx.android W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-05 15:29:07.710 17220-17220/com.xxx.android D/Tinker.TinkerInternals: same fingerprint:samsung/hero2qltezc/hero2qltechn:6.0.1/MMB29M/G9350ZCU2APJ3:user/release-keys
12-05 15:29:07.710 17220-17220/com.xxx.android W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.xxx.android count:0
12-05 15:29:07.720 17220-17220/com.xxx.android W/Tinker.TinkerLoader: after tinker safe mode count:1
12-05 15:29:07.720 17220-17220/com.xxx.android I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.android-2/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.android-2/lib/arm, /data/app/com.xxx.android-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
12-05 15:29:07.730 17220-17220/com.xxx.android W/Tinker.ClassLoaderAdder: checkDexInstall result:false
12-05 15:29:07.730 17220-17220/com.xxx.android E/Tinker.TinkerDexLoader: install dexes failed
12-05 15:29:07.730 17220-17220/com.xxx.android W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
12-05 15:29:07.730 17220-17220/com.xxx.android D/Tinker.DefaultAppLike: onBaseContextAttached:
12-05 15:29:07.730 17220-17220/com.xxx.android I/Tinker.SamplePatchListener: application maxMemory:256
12-05 15:29:07.740 17220-17220/com.xxx.android W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.android/tinker
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:7f15759942e431e2f8b1d9f24cf98166, current:7f15759942e431e2f8b1d9f24cf98166
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
12-05 15:29:07.740 17220-17220/com.xxx.android E/Tinker.DefaultLoadReporter: tinker dex check fail:Tinker Exception:checkDexInstall failed
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
12-05 15:29:07.740 17220-17220/com.xxx.android E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
12-05 15:29:07.740 17220-17220/com.xxx.android E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                                    at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:79)
                                                                                    at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:137)
                                                                                    at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:222)
                                                                                    at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:169)
                                                                                    at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134)
                                                                                    at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
                                                                                    at android.app.Application.attach(Application.java:211)
                                                                                    at android.app.Instrumentation.newApplication(Instrumentation.java:1020)
                                                                                    at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                                    at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6298)
                                                                                    at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7233)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/patch-7f157599.apk
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/dex/classes.dex.jar
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/dex/classes2.dex.jar
12-05 15:29:07.740 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/dex/test.dex.jar
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/dex
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/odex/classes.dex.dex
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/odex/classes2.dex.dex
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/odex/test.dex.dex
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599/odex
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch-7f157599
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/info.lock
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker/patch.info
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.android/tinker
12-05 15:29:07.750 17220-17220/com.xxx.android I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/com.xxx.android/tinker, code:-14, cost:55
12-05 15:29:07.750 17220-17220/com.xxx.android W/Tinker.Tinker: tinker load fail!
12-05 15:29:07.760 17220-17220/com.xxx.android D/Tinker.DefaultAppLike: onCreate
                                                                           
                                                                           [ 12-05 15:29:07.770 17220:17220 W/         ]
                                                                           Unable to open '/system/framework/dpmapi.jar': No such file or directory
12-05 15:29:08.490 17220-17220/com.xxx.android W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
```
