### ISSUE TITLE
自定义补丁包文件名

### ISSUE THREAD

**Issue by jp1017** [Tencent/tinker#200]
如何自定义 `tinkerPatchDebug` 打补丁的包名，默认是 `patch_signed_7zip.apk` 等

**Comment by shwenzhang** [comment]
你自己可以重命名成任何你想要的名字

**Comment by jp1017** [comment]
打补丁后是可以的，我意思是执行 `tinkerPatchDebug` 脚本的时候自动生成，不用再自己手动修改

**Comment by shwenzhang** [comment]
你可以自己反射定义输出目录，这种问题自己去看。
