### ISSUE TITLE
 在 CDATA 节中找到无效的 XML 字符 (Unicode: 0x10)

### ISSUE THREAD

**Issue by hellosad** [Tencent/tinker#202]
Error:Execution failed for task ':app:tinkerProcessDebugResourceId'.
> com.tencent.tinker.build.aapt.JavaXmlUtil$JavaXmlUtilException: org.xml.sax.SAXParseException; systemId: file:/Users/Kay/Work/Live_Android/app/build/intermediates/res/merged/debug/raw/aliwx_itemmatch.xml; lineNumber: 204; columnNumber: 34; 在 CDATA 节中找到无效的 XML 字符 (Unicode: 0x10)。
----------------------------------------------------------------------------------------------------

<regular><![CDATA[(((^http(s)?://)|^)item\.taobao\.com/auction/item_detail\.(htm|jhtml)\?.*itemId=\w+)]]></regular>

正常编译的时候没有问题，问题提示定位处时引入了阿里的包，但问题出现时因为修改了自己工程的部分代码，跟定位处并没有交互，请问问题出在哪里

**Comment by shwenzhang** [comment]
tinker版本？这个xml对应的错误内容是什么

**Comment by hellosad** [comment]
tinker1.7.3
对应内容<regular><![CDATA[(((^http(s)?://)|^)item\.taobao\.com/auction/item_detail\.(htm|jhtml)\?.*itemId=\w+)]]></regular>
该xml文件中有多处该内容，报错的不是第一项也不是最后一项，而且之前是没有问题的，在我修改了一些与此处无关的代码后出现的问题，但我无法确定到底是修改了哪出会导致这个问题出现

**Comment by hellosad** [comment]
`<regular><![CDATA[(((^http(s)?://)|^)item\.taobao\.com/auction/item_detail\.(htm|jhtml)\?.*itemId=\w+)]]></regular>`

**Comment by shwenzhang** [comment]
把完整的xml发我邮箱？我试一下？

**Comment by shwenzhang** [comment]
@hellosad 使用dev 分支，利用localmaven尝试一下是否fix

**Comment by hellosad** [comment]
@shwenzhang dev可行

**Comment by letyouthgoon** [comment]
解决方案是什么？1.7.5没有fix？ @shwenzhang
