### ISSUE TITLE
Questions about this library

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Tencent/tinker#203]
I'm not sure exactly what it does.
Can it be used for patching code?
Can it be used for launching a mini app within (using an APK), without the need to install it?

**Comment by shwenzhang** [comment]
Tinker can use to patch code, library and resources.  For example, if there is a version A app, I can use Tinker change to Version B without installing Version B. Instead, it just need to send a small patch.

Tinker can't launching a mini app, it just use for upgrade your app with installing a new version.

**Comment by AndroidDeveloperLB** [comment]
So it can't be used for plugins, themes, mini apps, etc...

But maybe the same mechanism you used can do it?
Could be cool to know how it's done.

**Comment by iamironz** [comment]
Can you please show me Google Play Agreement about restrictions policy for dynamic app updates?

**Comment by AndroidDeveloperLB** [comment]
@iamironz  I don't understand.

**Comment by iamironz** [comment]
`
Known Issues

There are some issues which Tinker can't dynamic update.

Due to Google Play Developer Distribution Agreement, we can't dynamic update our apk.
Support.
`

Can you show me where you found this agreement part?

**Comment by shwenzhang** [comment]
@AndroidDeveloperLB yes, with a little change, Tinker can use for plugins, themes, mini apps, etc...

@iamironz @AndroidDeveloperLB here is the agreement part
![image](https://cloud.githubusercontent.com/assets/8335303/20695991/1b24e11a-b62b-11e6-9170-55844876886d.png)

**Comment by AndroidDeveloperLB** [comment]
@shwenzhang Can you please create a new library that shows how to use it for plugins, themes, and mini apps (that use APK files) ?

**Comment by shwenzhang** [comment]
such as https://github.com/DroidPluginTeam/DroidPlugin or https://github.com/asLody/VirtualApp can do this

**Comment by AndroidDeveloperLB** [comment]
Do they really work?
Do you know of any app that uses them?

**Comment by shwenzhang** [comment]
@AndroidDeveloperLB 
 they must work on most of phones, but every one.
 I don't know the extral users of them,

**Comment by AndroidDeveloperLB** [comment]
ok thanks.
