### ISSUE TITLE
屏幕锁屏 app crash

### ISSUE THREAD

**Issue by FrameJack** [Tencent/tinker#204]
//初始化TinkerPatch 服务器 SDK
        TinkerServerManager.installTinkerServer(getApplication(), Tinker.with(getApplication()), 3);
        //每隔访问三小时服务器是否有更新
        TinkerServerManager.checkTinkerUpdate(false);

加了上面两句代码，求解答

version 1.75

**Comment by shwenzhang** [comment]
TinkerPatch相关issue，到https://github.com/simpleton/tinker_server_client/issues
