### ISSUE TITLE
360加固后，usePreGeneratedPatchDex为true时，activity的内的修改没有效果~

### ISSUE THREAD

**Issue by zhoulikai** [Tencent/tinker#207]
HI~
      您好，根据文档，加固时使用usePreGeneratedPatchDex模式后，patch内的layout xml修改起效果，但是activity java内的代码没有起作用，有否解决方式啊~

**Comment by shwenzhang** [comment]
是否为launcher Activity？

**Comment by zhoulikai** [comment]
不，加固前都没问题，加固后所有的activity java内的均木起效果，layout xml的修改有作用。。

**Comment by shwenzhang** [comment]
加固这里问题比较多，未来tinker应该不考虑支持加固了。主要是因为Android N之后当前模式无法支持了
