### ISSUE TITLE
补丁修复包资源文件找不到，怀疑与tinker资源修复有关

### ISSUE THREAD

**Issue by ruanlei** [Tencent/tinker#208]
TINKER_VERSION=1.7.5
补丁未更改此文件。
只在修复成功的版本出现。
用户基数：56026（修复成功用户数）
影响用户数：629
机型：HUAWEI、VIVO、OPPO等常见机型
Android版本：4、5、6 都有分布

Fatal Exception: android.content.res.Resources$NotFoundException: File res/raw/ms_voice_played.ogg from drawable resource ID #0x7f080012
       at android.content.res.Resources.openRawResourceFd(Resources.java:1087)
       at android.media.SoundPool$SoundPoolImpl.load(SoundPool.java:491)
       at android.media.SoundPool.load(SoundPool.java:159)

**Comment by shwenzhang** [comment]
在合成成功的resources_out.zip里面是否有这个文件？

**Comment by ruanlei** [comment]
首先，如果resources_out.zip没有这个文件，这个问题会全量出现，而不是1.12%的概率。
并且我查了合成成功的resources_out.zip里面有这个文件。

**Comment by ruanlei** [comment]
首先，如果resources_out.zip没有这个文件，这个问题会全量出现，而不是1.12%的概率。
并且我查了合成成功的resources_out.zip里面有这个文件。

**Comment by shwenzhang** [comment]
对应的id正确吗？调用的路径是什么？有更加详细的日志吗？

**Comment by ruanlei** [comment]
查了这个id
打补丁生成的/build/bakApk/app-release-R.txt中
int raw ms_voice_played 0x7f080012
是对应的；

调用 soundPool.load(context, R.raw.ms_voice_played, 1)
load方法中context.getResources().openRawResourceFd(resId) 抛出的NotFoundException

**Comment by shwenzhang** [comment]
1. 是否确定只有补丁的用户会发生这个crash？
2. 是否是必现的，能否自己复现或者联系用户？

**Comment by ruanlei** [comment]
非补丁用户有2个crash，概率极低。补丁用户发生这个crash的概率较大。目前我自己无法复现，正在尝试联系用户。

**Comment by ruanlei** [comment]
补充一下，确实是有修改资源文件，因为每次打包都有脚本自动修改一些文件，但是res/raw/ms_voice_played.ogg 文件没有修改。

**Comment by shwenzhang** [comment]
原因是因为删除了补丁，但是没有去重启进程，是应用自己处理的问题
