### ISSUE TITLE
需求：tinker 可以用SDK更新么？

### ISSUE THREAD

**Issue by jack0825** [Tencent/tinker#209]
我们团队开发了一款游戏的SDK，供各个游戏工作室接入， 现在我们sdk 准备做热更功能，想了解下这种业务场景，tingker能满足么？  (因为我们是对外提供的sdk，我们无法拿到各个游戏的最新apk包和老版本apk包，这样就无法直接生成补丁包，我们只有最新版本的sdk包，和老版本的sdk包，所以我想如果我用新版sdk包 和老版本skd包 生成sdk的补丁包，这样sdk的补丁包下发到游戏上，能否实现热更新？)

**Comment by shwenzhang** [comment]
Tinker统一的SDK后面会考虑的
