### ISSUE TITLE
patch fail, please check reason

### ISSUE THREAD

**Issue by adhere534** [Tencent/tinker#21]
Load　Patch 提示
patch fail, please check reason
 SampleResultService receive result: 
                                                                                 PatchResult: 
                                                                                 isUpgradePatch:true
                                                                                 isSuccess:false
                                                                                 rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                                 costTime:146
                                                                                 patchVersion:null
                                                                                 patchTinkerID:null
                                                                                 baseTinkerID:null
                                                                                 Throwable: null

**Comment by shwenzhang** [comment]
请补充完整的加载日志，使用"Tinker."过滤。请提交符合规范的issue

**Comment by adhere534** [comment]
receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:1999
get platform:all
 SampleResultService receive result: 
 PatchResult: 
 isUpgradePatch:true
 isSuccess:false
 rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
 costTime:126
 patchVersion:null
 patchTinkerID:null
 baseTinkerID:null
 Throwable: null

**Comment by shwenzhang** [comment]
这里是合成失败，需要把合成过程的日志也补上

**Comment by adhere534** [comment]
/tinker.sample.android W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/tinker.sample.android/tinker
/tinker.sample.android D/Tinker.DefaultAppLike: onBaseContextAttached:
/tinker.sample.android I/Tinker.SamplePatchListener: application maxMemory:256
/tinker.sample.android W/Tinker.Tinker: tinker patch directory: /data/data/tinker.sample.android/tinker
/tinker.sample.android I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
/tinker.sample.android W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
/tinker.sample.android I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/tinker.sample.android/tinker, code:-2, cost:3
/tinker.sample.android W/Tinker.Tinker: tinker load fail!
/tinker.sample.android D/Tinker.DefaultAppLike: onCreate
/tinker.sample.android D/Tinker.DefaultAppLike: onTrimMemory level:15
/tinker.sample.android E/Tinker.MainActivity: i am on onCreate classloader:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk
/tinker.sample.android E/Tinker.MainActivity: i am on onCreate string:I am in the base apk
/tinker.sample.android E/Tinker.MainActivity: i am on onResume
/tinker.sample.android W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:1999
/tinker.sample.android I/Tinker.SamplePatchListener: get platform:all

**Comment by adhere534** [comment]
17:09:31: Executing external task 'tinkerPatchDebug'...
Incremental java compilation is an incubating feature.
----------------------tinker build warning ------------------------------------
tinker will change your build configs:
we will add TINDER_ID=1.0 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and you should copy it to your own multiDex keep proguard file yourself.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportMultidex101Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComTencentTinkerTinkerAndroidLib160Library UP-TO-DATE
:app:prepareComTencentTinkerTinkerAndroidLoader160Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest
tinker add 1.0 to your AndroidManifest.xml D:\app\tinker-dev\tinker-sample-android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml
:app:tinkerProcessDebugManifest
apply resource mapping file D:\app\tinker-dev\tinker-sample-android\app\build\bakApk/ is illegal, just ignore
tinker gen resource public.xml in build/intermediates/tinker_intermediates/public.xml
tinker gen resource idx.xml in build/intermediates/tinker_intermediates/idx.xml
:app:tinkerProcessDebugResourceId
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
try update tinker multidex keep proguard file with D:\app\tinker-dev\tinker-sample-android\app\build\intermediates\tinker_intermediates\tinker_multidexkeep.pro
:app:tinkerProcessDebugMultidexKeep
:app:transformClassesWithJarMergingForDebug UP-TO-DATE
:app:collectDebugMultiDexComponents UP-TO-DATE
:app:transformClassesWithMultidexlistForDebug UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug
:app:tinkerPatchDebug
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:D:\app\tinker-dev\tinker-sample-android\app\build\bakApk/app-debug-0926-16-53-55.apk
newApk:D:\app\tinker-dev\tinker-sample-android\app\build\outputs\apk\app-debug.apk
outputFolder:D:\app\tinker-dev\tinker-sample-android\app\build\outputs/tinkerPatch/debug
isIgnoreWarning:false
7-ZipPath:C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:tinker is sample to use
filed name:platform, filed value:all
dex configs: 
dexMode: jar
dexPattern:assets/secondary-dex-.\.jar
dexPattern:classes.*\.dex
dex loader:com.tencent.tinker.loader.*
dex loader:tinker.sample.android.SampleApplication
dex loader:tinker.sample.android.app.BaseBuildInfo
lib configs: 
libPattern:lib/armeabi/.*\.so
resource configs: 
resPattern:res/.*
resPattern:assets/.*
resPattern:resources\.arsc
resPattern:AndroidManifest\.xml
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: app-debug-0926-16-53-55.apk, size=1475228, md5=c1719cfe6fa4aede3a26fa12a33961be
new apk: app-debug.apk, size=1475287, md5=89d5aa758922e2a8fe5def60d628c4f9

UnZipping apk to D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\app-debug-0926-16-53-55
UnZipping apk to D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\app-debug
Check for loader classes in dex: ../app-debug-0926-16-53-55/classes.dex
Verifying if patched new dex is logically the same as original new dex: app-debug/classes.dex ...
Start generating small patch info file...
DexDecoder:write meta file data: classes.dex,,b22411a9afd27d2493b111164b593ccd,090e96bdf5f1897d7efa27f2408e7bae,917d13d2580cdc87b1b57a514252a6fe,1820237341,jar
Add test install result dex: D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\tinker_result\test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
General unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
Tinker patch done, total time cost: 3.435000s
Tinker patch done, you can go to file to find the output D:\app\tinker-dev\tinker-sample-android\app\build\outputs/tinkerPatch/debug
-----------------------Tinker patch end-------------------------
Gen classes.dex for dalvik full dex file:D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\tempPatchedDexes\full\classes.dex, size:2076500, md5:b22411a9afd27d2493b111164b593ccd
Gen classes.dex for art small dex file:D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\tempPatchedDexes\small\classes.dex, size:5500, md5:090e96bdf5f1897d7efa27f2408e7bae
Result: final signed patch result: D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\patch_signed.apk, size=3817
Result: final signed with 7zip patch result: D:\app\tinker-dev\tinker-sample-android\app\build\outputs\tinkerPatch\debug\patch_signed_7zip.apk, size=4221
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 404 byte, you should choose patch_signed.apk at these time!

BUILD SUCCESSFUL

Total time: 5.265 secs
17:09:36: External task execution finished 'tinkerPatchDebug'.

**Comment by adhere534** [comment]
receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:4221
get platform:all
SampleResultService receive result: 
PatchResult: 
isUpgradePatch:true
isSuccess:false
rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
costTime:38
patchVersion:null
patchTinkerID:null
baseTinkerID:null
Throwable: null

**Comment by adhere534** [comment]
patch.info没有生成
tryLoadPatchFiles:patch info not exist:/data/data/tinker.sample.android/tinker/patch.info

 patchVersion:null
 patchTinkerID:null
 baseTinkerID:null
 Throwable: null
这几个空的 是什么情况？

**Comment by shwenzhang** [comment]
是在合成的时候错误了，你要看合成过程的日志
'''java
isSuccess:false
'''

**Comment by adhere534** [comment]
没看见sample:patch进程起来 
![image](https://cloud.githubusercontent.com/assets/9199894/18857035/242e9450-8493-11e6-84f7-8b3eea9d948e.png)

**Comment by shwenzhang** [comment]
把Tinker.跟右边only show都去掉看看

**Comment by adhere534** [comment]
![image](https://cloud.githubusercontent.com/assets/9199894/18857273/3267ed3a-8495-11e6-9fb2-b9618b78c6c1.png)

**Comment by shwenzhang** [comment]
错误码出来了，-7，TINKER_ID不一致。你的tinkerId是不是类似1.0这样短的字符串？现在会有问题，你把他改成长一点的。用到的apk-parser库有问题

**Comment by adhere534** [comment]
现在Success了
但是
![image](https://cloud.githubusercontent.com/assets/9199894/18857486/eefacce6-8496-11e6-9263-22951cef140a.png)

怎么还是一个啊

**Comment by 7heaven** [comment]
:patch 进程并不会在打完补丁后再次启动  只有在接收到补丁文件的时候(TinkerInstaller.onReceiveUpgradePatch或者TinkerInstaller.onReceiveRepairPatch)才会启动:patch进程对补丁进行处理
