### ISSUE TITLE
热修复失败 

### ISSUE THREAD

**Issue by jclick** [Tencent/tinker#214]
`11-30 14:17:50.658 5872-5872/? I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
11-30 14:17:50.658 5872-5872/? D/ResourcesManager: For user 0 new overlays fetched Null
11-30 14:17:50.658 5872-5872/? I/InjectionManager: Inside getClassLibPath caller 
11-30 14:17:50.668 5872-5872/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.xxx/tinker/patch.info
11-30 14:17:50.668 5872-5872/? D/Tinker.DefaultAppLike: onBaseContextAttached:
11-30 14:17:50.668 5872-5872/? I/MultiDex: VM with version 2.1.0 has multidex support
11-30 14:17:50.668 5872-5872/? I/MultiDex: install
11-30 14:17:50.668 5872-5872/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
11-30 14:17:50.678 5872-5872/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.Apricotforest_epocket/tinker
11-30 14:17:50.678 5872-5872/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
11-30 14:17:50.678 5872-5872/? W/Tinker.Tinker: tinker load fail!`

用的bugly上面的热修复。。1.7.5版本。。在实际项目中运用出现这个问题

**Comment by shwenzhang** [comment]
上面的日志完全没有问题，自己再看看文档吧

**Comment by jclick** [comment]
测试了六七个设备。。三星华为各种都没有问题，三星S7一直就hotfix无法成功。。看文档能解决么

**Comment by shwenzhang** [comment]
你上面的日志根本没有任何作用，你先看看提交issue的规范把
