### ISSUE TITLE
资源patch删除资源 打进resources_out.zip的小bug

### ISSUE THREAD

**Issue by hellokugo** [Tencent/tinker#215]
在学习资源patch过程中发现，新apk删除资源后打patch，最后还是会copy到resources_out.zip，看源码应该是想过滤掉删除资源不做copy，测试发现应该是DeletedResVisitor在deletedFiles.add时没有对路径进行转义。

**Comment by shwenzhang** [comment]
欢迎提pr

**Comment by shwenzhang** [comment]
dev fixed
