### ISSUE TITLE
关于注解生成Application生成有个顺序的问题，

### ISSUE THREAD

**Issue by jiuwu0905** [Tencent/tinker#216]
如果在AndroidManifest 先添加好了name属性。Application类怎么都没办法生成，而且全程不会有错误抛出。
建议加一个注意点，或者看看有没有办法解决这个问题 。

**Comment by shwenzhang** [comment]
这个还是找出为什么无法生成的原因把，编译过程会有日志的

**Comment by jiuwu0905** [comment]
刚用Demo做了多次尝试，并对比日志，发现的确和顺序无关，Rebuild 的话都会出来的。
以为和Android annotaion一样，build一下就可以，惯性思维很可怕。
