### ISSUE TITLE
基版和修复版本期间修改的代码后能git commit吗？

### ISSUE THREAD

**Issue by graychens** [Tencent/tinker#223]
我之前生成一个基版，commit之后又修改了代码生成不了patch。查了下是BaseBuildInfo.TINKER_ID 基版和修改后的版本不一致导致的。
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Warning:ignoreWarning is false, but we found some loader class has been changed in new dex. Such these changes will not take effect!! related classes: {Ltinker/app/BaseBuildInfo;}
Error:com.tencent.tinker.build.util.TinkerPatchException: some loader class has been changed in new dex. Such these changes will not take effect!! related classes: {Ltinker/app/BaseBuildInfo;}
Information:1,050 errors
Information:6 warnings
Information:See complete output in console

**Comment by shwenzhang** [comment]
请认真看文档 这个是因为BaseBuildInfo在loader dex pattern，然后他的值改变了。在这种情况，1. 把ignore warning改为true  2. 删掉BaseBuildInfo类
