### ISSUE TITLE
Tinker 启用后，导致Instant Run无法使用，编译太慢了。

### ISSUE THREAD

**Issue by gybin02** [Tencent/tinker#224]

**Comment by shwenzhang** [comment]
1. 请看文档， debug期间可以把tinkerEanble关掉，即可

**Comment by typ0520** [comment]
tinkerEanble的值可以从local.properties中取，默认关掉，如果想开启的时候在自己的local.properties中打开也不会影响到别人

def buildWithTinker() {
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    def TINKER_ENABLE = properties.getProperty('TINKER_ENABLE', "true")
    return "false".equals(TINKER_ENABLE) ? Boolean.valueOf(TINKER_ENABLE) : Boolean.valueOf(ext.tinkerEnabled)
}

**Comment by playscforever** [comment]
@shwenzhang tinkerEanble关掉后还是不行

**Comment by guangmomo** [comment]
同问，tinkerEanble关掉后还是不行，https://www.jianshu.com/p/6ee2c1f581eb 这个也不行，1.9.6 版本
