### ISSUE TITLE
checkTinkerUpdate相关问题

### ISSUE THREAD

**Issue by zktufo** [Tencent/tinker#225]
下面是checkTinkerUpdate内部的方法：

     if (tinker.isMainProcess()) {
            Looper.getMainLooper().myQueue().addIdleHandler(new MessageQueue.IdleHandler() {
                @Override public boolean queueIdle() {
                    sTinkerServerClient.checkTinkerUpdate(immediately);
                    return false;
                }
            });
        }

在我的项目中回调并没有执行，是不是在主线程空闲时才会执行，还有为何限定必须在主线程运行

**Comment by shwenzhang** [comment]
这个是有时间间隔控制，tinkerpatch的issue不要在这边提
