### ISSUE TITLE
Task with name 'tinkerPath_360Debug' not found in project ':app'.

### ISSUE THREAD

**Issue by 24suixinsuoyu** [Tencent/tinker#228]
在 build.gradle 文件的这一行：
def tinkerTask = tasks.getByName("tinkerPath${flavor.capitalize()}Debug")
报题目中的错误。。How to fix it ?

**Comment by linjonh** [comment]
肯定是flavor名字定义有误

**Comment by shwenzhang** [comment]
这个其实只是sample中的脚本，只是一个事例，大家可以参加自己的情况修改

**Comment by 24suixinsuoyu** [comment]
仔细检查了下，应该是 tinkerPatch, 我打成了 tinkerPath.....My fault.
