### ISSUE TITLE
Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:you must install tinker before get tinker sInstance

### ISSUE THREAD

**Issue by Aniderr** [Tencent/tinker#229]
我都配置好了 
             

1.  classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
compile("com.tencent.tinker:tinker-android-lib:${TINKER_VERSION}") { changing = true }
provided("com.tencent.tinker:tinker-android-anno:${TINKER_VERSION}") { changing = true }     

但是还是提示我标题的内容 叫我安装，请问应该如何做？

**Comment by shwenzhang** [comment]
.......这里是指在获取tinker实例之前，需要先初始化Tinker

**Comment by Aniderr** [comment]
不是说在获取实例前要安装吗？tinker的初始化是通过SampleApplicationLike这个类来实现的吗？

**Comment by shwenzhang** [comment]
自己看看sample的代码把

**Comment by Aniderr** [comment]
现在没有问题了 主要是如果想搭建完成就得将所有的service util crash这些包文件全部拷贝进去吗？
