### ISSUE TITLE
Error:(331, 0) Task with name 'assembleDebug' not found in project ':app'.

### ISSUE THREAD

**Issue by 411370845** [Tencent/tinker#23]
gradle syc 的时候报错。怎么解决这问题
![image](https://cloud.githubusercontent.com/assets/11730848/18826167/94fd16d8-83fe-11e6-8e42-eea5249f3ab3.png)

**Comment by shwenzhang** [comment]
#11

**Comment by 411370845** [comment]
弄好了，谢谢.
