### ISSUE TITLE
无法loadpatch 也没有任何提示

### ISSUE THREAD

**Issue by Aniderr** [Tencent/tinker#231]
请问 我使用demo中的如下代码load patch 但是load不了 路径这些配置和demo一样 只是module的名字换了  这是什么原因？

TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(), Environment.getExternalStorageDirectory().getAbsolutePath() + "/patch_signed_7zip.apk");

**Comment by linjonh** [comment]
读写SD卡权限是否grant？

**Comment by Aniderr** [comment]
额 好了 谢谢哈  另外那个load成功的提示我看demo没有写 如何取判断是否load成功呢 在不重启查看效果的情况下？

**Comment by shwenzhang** [comment]
看文档，给日志！
