### ISSUE TITLE
编译失败：auxiliaryInject/debug/jars/1/1f目录下出现重复jar包

### ISSUE THREAD

**Issue by lightai** [Tencent/tinker#233]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

**Comment by shwenzhang** [comment]
下个版本将统一处理这个问题

**Comment by lightai** [comment]
btw：把auxiliaryInject目录删掉可以编译通过

**Comment by shwenzhang** [comment]
使用 dev localmaven
