### ISSUE TITLE
usePreGeneratedPatchDex=true ,执行assembleRelease或assembleDebug报错

### ISSUE THREAD

**Issue by xns1001** [Tencent/tinker#234]
:app:mergeReleaseAssets
:app:transformClassesWithAuxiliaryInjectForRelease
[AuxiliaryInject] Processing ADDED file android/support/design/R$anim.class
[AuxiliaryInject] Processing ADDED file android/support/design/R$attr.class
...
...

* What went wrong:
Execution failed for task ':app:transformClassesWithAuxiliaryInjectForDebug'.
> java.lang.ArrayIndexOutOfBoundsException (no error message)

**Comment by shwenzhang** [comment]
Tinker将取消加固的支持
