### ISSUE TITLE
tinker 加渠道就不能打差分包了

### ISSUE THREAD

**Issue by AriaLyy** [Tencent/tinker#237]
渠道配置
productFlavors {
    //河北电信
    HBDX_HWYH_HBIPTV {
      manifestPlaceholders = [CHANNEL_VALUE: name]
    }
}

这是我配置的路径
tinkerOldApkPath = "${bakPath}/app-1207-18-23-35/HBDX_HWYH_HBIPTV/app-HBDX_HWYH_HBIPTV-debug.apk"

已运行打差分的任务就出现了以下错误，莫名其妙就少了‘app-1207-18-23-35’路径..
Execution failed for task ':app:tinkerPatchHBDX_HWYH_HBIPTVDebug'.
> old apk E:\workspace\WanBa2\app\build\bakApk//hBDX_HWYH_HBIPTV/app-hBDX_HWYH_HBIPTV-debug.apk is not exist, you must set the correct old apk value!

**Comment by shwenzhang** [comment]
wiki
