### ISSUE TITLE
Instant Run Runtime started. Android package is com.xx.app.iqc, real application class is null

### ISSUE THREAD

**Issue by wyh497823256** [Tencent/tinker#238]
环境：

- Android studio 2.2.3  

-  Android  6.0-7.0

- Gradle :tinkerEnabled = false
描述：Android studio 2.2.3  打开 Instant Run 功能后，在android  6.0 和android 7.0 环境下，无法加载继承DefaultApplicationLike 的自定义类。但是在android 4.3环境下app可以正常运行。实验关闭Android studio 2.2.3  Instant Run  功能在 android 4.3、android  6.0 和android 7.0 环境下 app都可以正常 运行。反复开关，证实以下报错日志跟Instant Run 功能  有关；

Log: Instant Run Runtime started. Android package is com.xx.app.iqc, real application class is null

**Comment by shwenzhang** [comment]
本地测试没有复现，tinker后面增了一个开关

**Comment by jianwue** [comment]
I meet the same problem with you yesterday, did you solve the problem? if did, could you please give me your solve method? thanks.

**Comment by wyh497823256** [comment]
tinkerEnabled = true
disenable Instant Run 
This method works only in 1.7.5, I don't know why, but it is feasible
@jianwue

**Comment by jianwue** [comment]
@wyh497823256 
Thanks for your reply, but it can't help me because i have update my AS and gradle to the latest version.

**Comment by wyh497823256** [comment]
@jianwue 
You can try to replace the equipment，I did this

**Comment by jianwue** [comment]
Are you a Chinese?

**Comment by wyh497823256** [comment]
@jianwue 
Yes!I am working hard on my English!

**Comment by jianwue** [comment]
Haha,
我也是，你加我微信吧，手机号：18701791107
