### ISSUE TITLE
tinker build warning

### ISSUE THREAD

**Issue by zhoujunqz** [Tencent/tinker#239]
----------------------tinker build warning ------------------------------------
tinker will change your build configs:
we will add TINKER_ID=173cb3f in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and you should copy it to your own multiDex keep proguard file yourself.

if applyResourceMapping file is exist
we will build quFenQiAndroidApp apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!

这串警告需要关注吗？

**Comment by shwenzhang** [comment]
无需，只是告诉你tinker plugin会做什么
