### ISSUE TITLE
应用中自定义的XXXXapplication

### ISSUE THREAD

**Issue by l114624915** [Tencent/tinker#24]
自己应用中的XXXXApplicaiton怎么处理 要写一个 xxxxLike extends DefaultApplicationLike的类吗？

**Comment by shwenzhang** [comment]
#17 ， 在提问之前请先查找已经存在的issue以及文档信息

**Comment by dodola** [comment]
@l114624915  可以看看这个是不是你想要的 [Tinker 自定义扩展](https://github.com/Tencent/tinker/wiki/Tinker-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95)

**Comment by Drizzlezhang** [comment]
@shwenzhang 如果我的APP的application不会在补丁中进行修改，那么我不用DefaultApplicationLike可以么

**Comment by shwenzhang** [comment]
不行，不仅仅是application不修改就可以的。Application的引用类也不能修改，如果不做隔离，很容易出问题

**Comment by Drizzlezhang** [comment]
@shwenzhang 请问下Application的引用类的意思是Application中用到的类还是用到Application的类？我们的项目现在觉得这种方式侵入性略强，所以还是想保留之前的Application

**Comment by shwenzhang** [comment]
Application用到的类，改造其实还好把，应该在一个小时可以完成。如果不使用代理方式，只能通过替换Application方式，但是那种方式兼容性是有问题的

**Comment by l114624915** [comment]
@shwenzhang 
tinker-sample在我6.0手机上debug和release打补丁验证过了，现打算移入项目，关于自定义的application，以前所有继承自application类要处理成xxxxxxxLike extends DefaultApplicationLike，把以前自定义中的代码逻辑移入xxxxxxxLike？

**Comment by shwenzhang** [comment]
直接把application的所有代码拷过去，然后改一下就行，参考sample

**Comment by l114624915** [comment]
原先application直接拷贝进  
 public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);
        //you must install multiDex whatever tinker is installed!
        MultiDex.install(base);
        YLBBaseApplicationContext.application = getApplication();
        YLBBaseApplicationContext.context = getApplication();
        TinkerManager.setTinkerApplicationLike(this);
        TinkerManager.initFastCrashProtect();
        //should set before tinker is installed
        TinkerManager.setUpgradeRetryEnable(true);
        //optional set logIml, or you can use default debug log
        TinkerInstaller.setLogIml(new MyLogImp());
        //installTinker after load multiDex
        //or you can put com.tencent.tinker.** to main dex
        TinkerManager.installTinker(this);

----------------原来自定义Application 代码 ？
    }

**Comment by shwenzhang** [comment]
参考sample与文档即可

**Comment by l114624915** [comment]
以前在自定义Applicaiton中的方法，现在挪到XXXBaseApplicationLike后，其他类需要调用原先自定义Applicaiton中的方法怎么处理
其他类中调用
XXXBaseApplicationContext.application.dosomething() 编译不过的，谢谢

**Comment by shwenzhang** [comment]
参考sample，Applicationlike.getapplication就可以得到application。可以用静态变量存起来

**Comment by l114624915** [comment]
我说的方法调用不是变量，项目中有些方法写在在定义application中，挪到XXXBaseApplicationLike后，怎么调用这个方法？

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/18899545/49b49236-856c-11e6-90fa-947b76edc959.png)

Sample跟wik都有啊？

**Comment by SolveBugs** [comment]
你好，你找到怎么调用原来Application中的方法的 办法了吗？

**Comment by dodola** [comment]
@SolveBugs #66 看一下这个issue
