### ISSUE TITLE
xg_service_v2 E/dalvikvm: Could not find class 'tInKEr.pReVEnT.PrEVErIfIEd.STuBCLaSS', referenced from method com.tencent.android.tpush.XGPushReceiver.<init>

### ISSUE THREAD

**Issue by wsgang** [Tencent/tinker#242]
xg_service_v2 E/dalvikvm: Could not find class 'tInKEr.pReVEnT.PrEVErIfIEd.STuBCLaSS', referenced from method com.tencent.android.tpush.XGPushReceiver.<init>

**Comment by shwenzhang** [comment]
使用插桩模式的确会出现这样的提示的
