### ISSUE TITLE
app:tinkerPatchRelease时报错debug模式正常这是什么情况

### ISSUE THREAD

**Issue by 18337129968** [Tencent/tinker#243]
Error:Execution failed for task ':app:tinkerPatchRelease'.
> Could not get unknown property 'taskName' for task ':app:tinkerPatchRelease' of type com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.

**Comment by shwenzhang** [comment]
fixed by dev

**Comment by 18337129968** [comment]
def taskName = variant.name
具体怎么正确修改，才能实现release补丁
def taskName = "release"这样修改看不行

**Comment by Aniderr** [comment]
@18337129968 请问问题解决了吗？我也遇到了

**Comment by 18337129968** [comment]
首先需要打开混淆
然后
def taskName = "release"

**Comment by Aniderr** [comment]
@18337129968  我这样做了 第一次完整打包 第二次修改点内容 release打包就提示了这个问题

**Comment by Aniderr** [comment]
@18337129968 3Q 可以了 我之前删除了打包时的签名配置

**Comment by Aniderr** [comment]
@18337129968 您好在打扰一下 我有个问题 现在的签名文件及密码这些都配置进了build文件中，这样安全吗？还是说可以不这样配置进去？

**Comment by 18337129968** [comment]
谷歌推荐将签名文件及密码写入gradle.properties

**Comment by Aniderr** [comment]
也就是build.gradle文件中是不可取的是不？

**Comment by 18337129968** [comment]
这个东西其实没有什么绝对安全的，也有很多人放到gradle，其实放到properties也不是绝对安全只是相对安全一下，不过一样是透明的，网上有帖子说把密码存储，其实没有什么绝对安全的，放到properties是谷歌默许的相对比较正规一些而已

**Comment by Aniderr** [comment]
那这样岂不是很容易就被拿走了 二次打包什么的更加轻松了

**Comment by 18337129968** [comment]
所以才有那么多的加固啊

**Comment by Aniderr** [comment]
@18337129968 您好 又来打扰了 我demo没有问题 但是在主项目中增加进去 第一没有生成后缀有mapping的文件 以及在loadpatch的时候一直提示路径加载失败 但是那个路径下 确实有文件的 ， 请问如何解决这两个问题啊？Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/sdcard/sdcard/patch_signed_7zip.apk

**Comment by shwenzhang** [comment]
详细的日志

**Comment by 18337129968** [comment]
@Aniderr 需要看一下你的控制台详细日志

**Comment by Aniderr** [comment]
额 谢谢各位 我之前应用的demo这些没有问题 可能是我配置没配置好还是怎么的，三星手机不行 我的小米能够读取，只是项目都没有生成mapping文件，而主项目又运用了360加固，所以这边项目应该不会使用了，其他项目中接入，如果从一开始进入应该没有问题，在此万分感谢各位的热心解答。

**Comment by 18337129968** [comment]
建议你在接入到项目之前仔细看一下他们的详细说明，https://github.com/Tencent/tinker/wiki，还有如果项目需要使用Tinker，建议不要使用加固，“5、由于各个厂商的加固实现并不一致，在1.7.6以及之后的版本，tinker不再支持加固的动态更新；” 他们已经声明不再支持加固更新

**Comment by Android-Star** [comment]
我想问一下def taskName = "release"这个东西需要加在哪里啊？

**Comment by yatou252303** [comment]
bulid.gradle



279642707@qq.com
 
发件人： Android-Star
发送时间： 2017-01-06 13:10
收件人： Tencent/tinker
抄送： Subscribed
主题： Re: [Tencent/tinker] app:tinkerPatchRelease时报错debug模式正常这是什么情况 (#243)
我想问一下def taskName = "release"这个东西需要加在哪里啊？

**Comment by 18337129968** [comment]
仔细看一下你的build文件就能找到了

**Comment by Android-Star** [comment]
找到了，通过不断修改终于可以实现简单功能的修复了，非常感谢，再继续学习。。。
