### ISSUE TITLE
执行过加载补丁的方法后过会闪退了，再次打开已经成功修复了。

### ISSUE THREAD

**Issue by answersonya** [Tencent/tinker#246]
12-12 16:55:01.043 1008-3735/? I/ActivityManager: bindServiceLocked, r: ServiceRecord{7f83ba7 u0 euid: 0 com.tky.tinker/com.tencent.tinker.lib.service.TinkerPatchService}, euid: 0
12-12 16:55:01.044 1008-3735/? I/ActivityManager: mAm.startProcessLocked for service: ServiceRecord{7f83ba7 u0 euid: 0 com.tky.tinker/com.tencent.tinker.lib.service.TinkerPatchService}, appinfo euid: 0
12-12 16:55:01.063 1008-3735/? I/ActivityManager: Start proc 7817:com.tky.tinker:patch/u0a424 for service com.tky.tinker/com.tencent.tinker.lib.service.TinkerPatchService
12-12 16:55:01.138 7817-7817/com.tky.tinker:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.tky.tinker/tinker
12-12 16:55:01.140 7817-7817/com.tky.tinker:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
12-12 16:55:01.145 7817-7817/com.tky.tinker:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.tky.tinker/tinker
12-12 16:55:01.148 7817-7817/com.tky.tinker:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
12-12 16:55:01.148 7817-7817/com.tky.tinker:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
12-12 16:55:01.148 7817-7817/com.tky.tinker:patch I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/com.tky.tinker/tinker, code:-2, cost:3
12-12 16:55:01.148 7817-7817/com.tky.tinker:patch W/Tinker.Tinker: tinker load fail!
12-12 16:55:01.152 7817-7817/com.tky.tinker:patch D/Tinker.DefaultAppLike: onCreate
12-12 16:55:01.155 7817-7833/com.tky.tinker:patch I/Tinker.DefaultPatchReporter: patchReporter: patch service start
12-12 16:55:01.155 7817-7817/com.tky.tinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:80
12-12 16:55:01.155 7817-7833/com.tky.tinker:patch I/Tinker.TinkerPatchService: try to increase patch process priority
12-12 16:55:01.156 1008-1022/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.tky.tinker/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
12-12 16:55:01.158 1008-3733/? I/ActivityManager: bindServiceLocked, r: ServiceRecord{870b23e u0 euid: 0 com.tky.tinker/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}, euid: 0
12-12 16:55:01.163 1008-1022/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.tky.tinker/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
12-12 16:55:01.186 7817-7833/com.tky.tinker:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:c4afa1cf965df4ca711f78343dad2c2e
12-12 16:55:01.186 7817-7833/com.tky.tinker:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.tky.tinker/tinker/patch-c4afa1cf
12-12 16:55:01.187 7817-7833/com.tky.tinker:patch W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/patch_signed_7zip.apk size:3507, /data/user/0/com.tky.tinker/tinker/patch-c4afa1cf/patch-c4afa1cf.apk size:3507
12-12 16:55:01.466 7817-7833/com.tky.tinker:patch I/art: Explicit concurrent mark sweep GC freed 160327(6MB) AllocSpace objects, 7(2MB) LOS objects, 19% free, 16MB/20MB, paused 110us total 16.132ms at IntentService[TinkerPatchService] thread CareAboutPauseTimes 1
12-12 16:55:01.507 7817-7833/com.tky.tinker:patch I/art: Explicit concurrent mark sweep GC freed 50713(1382KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 16MB/20MB, paused 72us total 9.364ms at IntentService[TinkerPatchService] thread CareAboutPauseTimes 1
12-12 16:55:01.954 7817-7833/com.tky.tinker:patch I/art: Explicit concurrent mark sweep GC freed 435712(26MB) AllocSpace objects, 13(496KB) LOS objects, 18% free, 17MB/21MB, paused 93us total 26.966ms at IntentService[TinkerPatchService] thread CareAboutPauseTimes 1
12-12 16:55:02.004 7817-7833/com.tky.tinker:patch I/art: Explicit concurrent mark sweep GC freed 61246(1777KB) AllocSpace objects, 1(244KB) LOS objects, 18% free, 17MB/21MB, paused 93us total 10.130ms at IntentService[TinkerPatchService] thread CareAboutPauseTimes 1
12-12 16:55:02.238 7817-7833/com.tky.tinker:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.tky.tinker/tinker/patch-c4afa1cf/dex/classes.dex.jar, use time: 1049
12-12 16:55:02.239 7817-7833/com.tky.tinker:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.tky.tinker/tinker/patch-c4afa1cf/dex/test.dex.jar
12-12 16:55:02.239 7817-7833/com.tky.tinker:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
12-12 16:55:02.994 7817-7833/com.tky.tinker:patch I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:1807, isUpgradePatch:true
12-12 16:55:02.994 7817-7833/com.tky.tinker:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
12-12 16:55:02.994 7817-7833/com.tky.tinker:patch W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
12-12 16:55:02.997 7817-7833/com.tky.tinker:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
12-12 16:55:02.998 7817-7833/com.tky.tinker:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:true, cost:1843, isUpgrade:true
12-12 16:55:03.004 1008-1019/? I/ActivityManager: bindServiceLocked, r: ServiceRecord{fc1b44a u0 euid: 0 com.tky.tinker/com.tencent.tinker.lib.service.DefaultTinkerResultService}, euid: 0
12-12 16:55:03.010 4112-7883/com.tky.tinker I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                 PatchResult: 
                                                                                 isUpgradePatch:true
                                                                                 isSuccess:true
                                                                                 rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                                 costTime:1843
                                                                                 patchVersion:c4afa1cf965df4ca711f78343dad2c2e
                                                                                  
12-12 16:55:03.010 4112-7883/com.tky.tinker I/Tinker.DefaultTinkerResultService: save delete raw patch file
12-12 16:55:03.010 4112-7883/com.tky.tinker I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/patch_signed_7zip.apk
12-12 16:55:03.306 1008-1020/? W/ActivityManager: Scheduling restart of crashed service com.tky.tinker/com.tencent.tinker.lib.service.DefaultTinkerResultService in 1000ms

- 

1.

**Comment by shwenzhang** [comment]
wiki
