### ISSUE TITLE
偶尔会出现空指针sTinkerServerClient.getCurrentPatchMd5()

### ISSUE THREAD

**Issue by 18337129968** [Tencent/tinker#247]
if (!patchMd5.equals(sTinkerServerClient.getCurrentPatchMd5())) {
                TinkerLog.e(TAG, "reportTinkerPatchFail, md5 not equal, " +
                        "patchMd5:%s, currentPatchMd5:%s", patchMd5, sTinkerServerClient.getCurrentPatchMd5());
                return;
            }

**Comment by shwenzhang** [comment]
新的SDK会统一fix
