### ISSUE TITLE
java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定的文件。

### ISSUE THREAD

**Issue by 411370845** [Tencent/tinker#25]
当我执行java -jar tinker.jar -old old.apk -new new.apk -config tinker_config.xml -out output_path的时候，报错，need help

java -jar E:\work\app\10\test\tinker-patch-cli.jar -old E:\work\app\10\test\old.apk -new E:\work\app\10\test\new.apk -config E:\work\app\10\test\tinker_config.xml -out E:\work\app\10\test\aaa
special configFile file path:E:\work\app\10\test\tinker_config.xml
special output directory path: E:\work\app\10\test\aaa
reading config file, E:\work\app\10\test\tinker_config.xml
-----------------------Tinker patch begin-----------------------
configuration:
oldApk:E:\work\app\10\test\old.apk
newApk:E:\work\app\10\test\new.apk
outputFolder:E:\work\app\10\test\aaa
isIgnoreWarning:false
7-ZipPath:7za
useSignAPk:true
package meta fields:
filed name:patchMessage, filed value:classes.dex
dex configs:
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.tencent.tinker.loader.*
dex loader:tinker.sample.android.SampleApplication
lib configs:
libPattern:lib/armeabi/.*\.so
resource configs:
resPattern:res/.*
resPattern:resources\.arsc
resPattern:AndroidManifest\.xml
resPattern:assets/.*
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: old.apk, size=1325037, md5=3381f286679f2103071568f8c0efb527
new apk: new.apk, size=1325017, md5=49c48574a25bf0116adc7eef7d94f4fb

UnZipping apk to E:\work\app\10\test\aaa\old
UnZipping apk to E:\work\app\10\test\aaa\new
Check for loader classes in dex: ../old/classes.dex
Verifying if patched new dex is logically the same as original new dex: new/classes.dex ...
Gen classes.dex for dalvik full dex file:E:\work\app\10\test\aaa\tempPatchedDexes\full\classes.dex, size:2076496, md5:8c088c810aa6ca7809a302e61db9cca6
Start generating small patch info file...
Gen classes.dex for art small dex file:E:\work\app\10\test\aaa\tempPatchedDexes\small\classes.dex, size:648, md5:b2f4377d6a5bb39affb3a756113cef50
DexDecoder:write meta file data: classes.dex,,8c088c810aa6ca7809a302e61db9cca6,b2f4377d6a5bb39affb3a756113cef50,0a5c8e14727751b8a51672f5d96d7357,1784658777,jar
Add test install result dex: E:\work\app\10\test\aaa\tinker_result\test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
General unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
java.io.IOException: Cannot run program "jarsigner": CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at com.tencent.tinker.build.builder.PatchBuilder.signApk(PatchBuilder.java:101)
        at com.tencent.tinker.build.builder.PatchBuilder.buildPatch(PatchBuilder.java:58)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:74)
        at com.tencent.tinker.patch.CliMain.run(CliMain.java:103)
        at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more

Usage: java -jar tinker.jar -old old.apk -new new.apk -config tinker_config.xml -out output_path

**Comment by shwenzhang** [comment]
将jarsigner添加到环境变量
