### ISSUE TITLE
1.7.3补丁生成失败

### ISSUE THREAD

**Issue by OoadaioO** [Tencent/tinker#252]
java.lang.RuntimeException: com.tencent.tinker.build.util.TinkerPatchException: some loader class has been changed in new dex. Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/R;}

**Comment by shwenzhang** [comment]
see wiki

**Comment by OoadaioO** [comment]
生成补丁的时候同样配置生成的release包  2台电脑可以补丁可以成功生成 另两台不可以
自己的proguard和multiDexKeepProguard 的配置文件都加入了

-keep class com.tencent.tinker.loader.** {
    *;
}

**Comment by shwenzhang** [comment]
1. Lcom/tencent/tinker/loader/R; 这个文件变在哪里
2. 使用最新版本尝试

**Comment by OoadaioO** [comment]
老版的release包打补丁失败，1.7.5打的的release包不会出现该问题了，老版打包会生成动态生成一个com.tencent.tinker.loader.R文件，新版打包不会生成所以就没问题了
