### ISSUE TITLE
Illegal class access: 'com.jm.android.jumei.r.b.h' attempting to access 

### ISSUE THREAD

**Issue by lichangqiang** [Tencent/tinker#253]
12-14 11:19:37.356 31614-31614/? E/CrashReport: # EXCEPTION MSG: Illegal class access: 'com.jm.android.jumei.r.b.h' attempting to access 'com.jm.android.jumei.presenter.usercenter.MinePresenter$14' (declaration of 'com.jm.android.jumei.r.b.h' appears in /data/app/com.jm.android.jumei-1/base.apk:classes2.dex)
12-14 11:19:37.356 31614-31614/? E/CrashReport: # EXCEPTION STACK:
                                                 com.jm.android.jumei.r.b.h.a(SourceFile:806)
                                                com.jm.android.jumei.r.b.h.access$1100(SourceFile:64)
                                                com.jm.android.jumei.r.b.n.onResponse(SourceFile:797)
                                                com.jm.android.jumei.r.b.n.onResponse(SourceFile:771)
                                                com.jm.android.jumei.usercenter.handler.CommonRspHandler.onSuccess(SourceFile:90)
                                                com.jm.android.jumei.home.b.e.b(SourceFile:277)
                                                com.jm.android.jumei.home.b.e.a(SourceFile:39)
                                                com.jm.android.jumei.home.b.f.handleMessage(SourceFile:79)
                                                android.os.Handler.dispatchMessage(Handler.java:111)
                                                android.os.Looper.loop(Looper.java:207)
                                                android.app.ActivityThread.main(ActivityThread.java:5905)
                                                java.lang.reflect.Method.invoke(Native Method)
                                                com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

这是每次都必现一个crash且是在不安装补丁的情况下。
crash的出现规律如下：开启混淆，打开tinkerEnabled ，crash不出现
                                      关闭混淆，打开tinkerEnabled ，crash出现
                                      开启混淆，关闭tinkerEnabled，crash不出现
通过反编译apk发现：MinePresenter的内部类都被混淆，唯独MinePresenter$14不被混淆，MinePresenter$14是最后一个内部类。Tinker版本1.75，混淆版本ProGuard, version 5.3.2

**Comment by shwenzhang** [comment]
关闭混淆？为什么crash还会出现，这样根本不会混淆啊

**Comment by lichangqiang** [comment]
不好意思，描述有问题
关闭混淆，都不出现crash
打开混淆，关闭tinkerEnable，不出现crash
打开混淆,打开tinkerEnable,不出现crash

**Comment by lichangqiang** [comment]
不好意思，描述有问题
关闭混淆，都不出现crash
打开混淆，关闭tinkerEnable，不出现crash
打开混淆,打开tinkerEnable,出现crash

**Comment by shwenzhang** [comment]
apply mapping过程出现warning? 这个是要解决的，这种情况需要修改原来的mapping文件
