### ISSUE TITLE
apply plugin: 'com.tencent.tinker.patch' 和 protobuf冲突问题

### ISSUE THREAD

**Issue by 09xuanjian** [Tencent/tinker#255]
在项目中，引入bugly中的  tinker ,  在Gradle 中引入  apply plugin: 'com.tencent.tinker.patch' 插件的时候，
出现以下错误：  Error:(203, 0) Plugin with id 'osdetector' not found.

发现和项目中使用的 protobuf的插件有冲突，屏蔽其中一个就可以正常使用。但是我项目中又必须要引入protobuf,  这个可以怎么解决冲突问题。

app里面的gradle：
apply plugin: 'com.google.protobuf'
apply plugin: 'com.tencent.tinker.patch'
apply plugin: 'com.tencent.bugly.tinker-support'

根目录的gradle:
protobuf:
classpath "com.google.protobuf:protobuf-gradle-plugin:0.8.0" 

Tinker:
        // tinker gradle插件
classpath ('com.tencent.tinker:tinker-patch-gradle-plugin:1.7.5')
        // tinkersupport插件
classpath ("com.tencent.bugly:tinker-support:latest.release")

**Comment by shwenzhang** [comment]
先尝试只import tinker的plugin是否存在问题，是否是bugly引起的问题

**Comment by 09xuanjian** [comment]
只import tinker  也会出现一样的问题。
