### ISSUE TITLE
com.google.gradle:osdetector-gradle-plugin 更新

### ISSUE THREAD

**Issue by xuguobiao** [Tencent/tinker#258]
现在osdetector-gradle-plugin的最新版本是1.4.0，但是当前tinker使用的osdetector版本是1.2.1，这两者之间存在一个差别就是plugin的名字改变了（1.2.1(osdetector)->1.4.0(com.google.osdetector)）。导致多个classpath覆盖使用了1.4.0的版本后，tinker编译报错'Plugin with id 'osdetector' not found'

**Comment by shwenzhang** [comment]
will fixed by 1.7.6

**Comment by shwenzhang** [comment]
fixed by dev
