### ISSUE TITLE
Patch包有大量v4v7包无用图片

### ISSUE THREAD

**Issue by liveei** [Tencent/tinker#260]
基准包以及patch包都为release
   配置：
   cruncherEnabled false
   shrinkResources true
   zipAlignEnabled true

     // 编译相关配置项  方法均指向真实路径或有效值
        buildConfig {
            applyMapping = getApplyMappingPath() 
            applyResourceMapping = getApplyResourceMappingPath() 
            tinkerId = getTinkerIdValue()
        }

多渠道为comment方式

打补丁前后只有代码发生2行改变，资源文件未变动
patch包里打进了很多以abc开头的  v4 v7包图片，app本身的图片也有，但较少

以下为日志文件，新旧包的大小有明显差别的，初步怀疑是否通过tinkerPatch 生成的新包没有将support包里的无用资源去除，可能是受资源applyResourceMapping的影响？

log.txt:

-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\bakApk/app-1215-17-58-47/dailybuild/tiqianle_c105_v2.0.1.test_dailybuild_release.apk
newApk:F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\apk\tiqianle_c105_v2.0.1.test_official_release.apk
outputFolder:F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs/tinkerPatch/official/release
isIgnoreWarning:false
isInsertStubMode:false
7-ZipPath:C:/Program Files/7-Zip/7z
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:patch for V2.0.1.test C105
filed name:platform, filed value:all
filed name:patchVersion, filed value:1.0
dex configs: 
dexMode: jar
dexPattern:assets/secondary-dex-.\.jar
dexPattern:classes.*\.dex
dex loader:com.fenqile.bluecollarloan.base.TiqianleApp
dex loader:com.tencent.tinker.loader.*
lib configs: 
libPattern:lib/armeabi/.*\.so
resource configs: 
resPattern:res/.*
resPattern:AndroidManifest\.xml
resPattern:resources\.arsc
resPattern:assets/.*
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: tiqianle_c105_v2.0.1.test_dailybuild_release.apk, size=13313587, md5=c5275d720d23dd78c8a35616c6982f1c
new apk: tiqianle_c105_v2.0.1.test_official_release.apk, size=13508514, md5=f49edad82fd99eecbcbfeaf89d147133
UnZipping apk to F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\tiqianle_c105_v2.0.1.test_dailybuild_release
UnZipping apk to F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\tiqianle_c105_v2.0.1.test_official_release
found modify resource: AndroidManifest.xml, but it is AndroidManifest.xml, just ignore!
Check for loader classes in dex: classes.dex
Found add resource: res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_000.png
Found add resource: res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_015.png
Found add resource: res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_000.png
Found add resource: res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_015.png
Found add resource: res/drawable-hdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
Found add resource: res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
Found add resource: res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_clear_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_menu_share_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_search_api_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
Found add resource: res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_list_focused_holo.9.png
Found add resource: res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png
Found add resource: res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png
Found add resource: res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png
Found add resource: res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png
Found add resource: res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png
Found add resource: res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
Found add resource: res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png
Found add resource: res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/abc_text_cursor_mtrl_alpha.9.png
Found add resource: res/drawable-hdpi-v4/ico_return.png
Found add resource: res/drawable-hdpi-v4/ic_launcher.png
Found add resource: res/drawable-hdpi-v4/jpush_statusbar_notification_icon.png
Found add resource: res/drawable-hdpi-v4/tiqianle_launcher.png
Found add resource: res/drawable-ldrtl-hdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-hdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-hdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
Found add resource: res/drawable-ldrtl-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png
Found add resource: res/drawable-ldrtl-mdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-mdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-mdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
Found add resource: res/drawable-ldrtl-mdpi-v4/abc_spinner_mtrl_am_alpha.9.png
Found add resource: res/drawable-ldrtl-xhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-xhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-xhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
Found add resource: res/drawable-ldrtl-xhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
Found add resource: res/drawable-ldrtl-xxxhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-xxxhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
Found add resource: res/drawable-ldrtl-xxxhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
Found add resource: res/drawable-ldrtl-xxxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
Found add resource: res/drawable-mdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png
Found add resource: res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_000.png
Found add resource: res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_015.png
Found add resource: res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_000.png
Found add resource: res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_015.png
Found add resource: res/drawable-mdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png
Found add resource: res/drawable-mdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png
Found add resource: res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
Found add resource: res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
Found add resource: res/drawable-mdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
Found add resource: res/drawable-mdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
Found add resource: res/drawable-mdpi-v4/abc_ic_clear_mtrl_alpha.png
Found add resource: res/drawable-mdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
......省略若干资源项......

Found large modify resource: resources.arsc size:458324

Gen classes.dex patch file:F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\tinker_result\classes.dex, size:760, md5:d0b8a5fa82e3d7c47d68815833b8852e
Verifying if patched new dex is logically the same as original new dex: tiqianle_c105_v2.0.1.test_official_release/classes.dex ...

Gen classes.dex for dalvik full dex file:F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\tempPatchedDexes\dalvik\classes.dex, size:7320088, md5:121149c8ebe6910f454afb42b69e29ec
DexDecoder:write meta file data: classes.dex,,121149c8ebe6910f454afb42b69e29ec,121149c8ebe6910f454afb42b69e29ec,d0b8a5fa82e3d7c47d68815833b8852e,2851303840,jar

Add test install result dex: F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\tinker_result\test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
Add Test resource file: assets/only_use_to_test_tinker_resource.txt
Final normal zip resource: resources_out.zip, size=7452916, md5=0260b15353ec0c151f3ac970f05628dc
Final 7zip resource: resources_out_7z.zip, size=7450689, md5=1ed04304225cebaffb99d81fe2790a98
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:C:/Program Files/7-Zip/7z
Result: final signed patch result: F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\patch_signed.apk, size=189140
Result: final signed with 7zip patch result: F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs\tinkerPatch\official\release\patch_signed_7zip.apk, size=193351
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 4211 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 9.264000s
Tinker patch done, you can go to file to find the output F:\WorkSpace\tiqianle_2.0\tiqianle\BlueCollarLoan\app\build\outputs/tinkerPatch/official/release
-----------------------Tinker patch end-------------------------

res_log.txt:

add resource: res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png, oldSize=0, newSize=287
add resource: res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_000.png, oldSize=0, newSize=227
add resource: res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_015.png, oldSize=0, newSize=404
add resource: res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_000.png, oldSize=0, newSize=464
add resource: res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_015.png, oldSize=0, newSize=563
add resource: res/drawable-hdpi-v4/abc_btn_rating_star_off_mtrl_alpha.png, oldSize=0, newSize=954
add resource: res/drawable-hdpi-v4/abc_btn_rating_star_on_mtrl_alpha.png, oldSize=0, newSize=632
add resource: res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png, oldSize=0, newSize=1548
add resource: res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png, oldSize=0, newSize=1748
add resource: res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png, oldSize=0, newSize=229
add resource: res/drawable-hdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png, oldSize=0, newSize=279
add resource: res/drawable-hdpi-v4/abc_ic_clear_mtrl_alpha.png, oldSize=0, newSize=324
add resource: res/drawable-hdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png, oldSize=0, newSize=171
add resource: res/drawable-hdpi-v4/abc_ic_go_search_api_mtrl_alpha.png, oldSize=0, newSize=118
add resource: res/drawable-hdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png, oldSize=0, newSize=203
add resource: res/drawable-hdpi-v4/abc_ic_menu_cut_mtrl_alpha.png, oldSize=0, newSize=404
add resource: res/drawable-hdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png, oldSize=0, newSize=134
add resource: res/drawable-hdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png, oldSize=0, newSize=226
......省略若干资源项......

dex_log.txt：

Start diff between [tiqianle_c105_v2.0.1.test_dailybuild_release/classes.dex] as old and [tiqianle_c105_v2.0.1.test_official_release/classes.dex] as new:
classes.dex, oldSize=7297140, newSize=7297168, diffSize=760

R.txt: (部分)

int dimen tab_max_width 0x7f080076
int dimen tab_min_width 0x7f080015
int dimen time_text_size 0x7f080077
int dimen title_height 0x7f080078
int drawable abc_ab_share_pack_mtrl_alpha 0x7f020000
int drawable abc_btn_borderless_material 0x7f020001
int drawable abc_btn_check_material 0x7f020002
int drawable abc_btn_check_to_on_mtrl_000 0x7f020003
int drawable abc_btn_check_to_on_mtrl_015 0x7f020004
int drawable abc_btn_default_mtrl_shape 0x7f020005
int drawable abc_btn_radio_material 0x7f020006
int drawable abc_btn_radio_to_on_mtrl_000 0x7f020007
int drawable abc_btn_radio_to_on_mtrl_015 0x7f020008
int drawable abc_btn_rating_star_off_mtrl_alpha 0x7f020009
int drawable abc_btn_rating_star_on_mtrl_alpha 0x7f02000a
int drawable abc_btn_switch_to_on_mtrl_00001 0x7f02000b
int drawable abc_btn_switch_to_on_mtrl_00012 0x7f02000c
int drawable abc_cab_background_internal_bg 0x7f02000d
int drawable abc_cab_background_top_material 0x7f02000e
int drawable abc_cab_background_top_mtrl_alpha 0x7f02000f
int drawable abc_dialog_material_background_dark 0x7f020010
int drawable abc_dialog_material_background_light 0x7f020011
int drawable abc_edit_text_material 0x7f020012
int drawable abc_ic_ab_back_mtrl_am_alpha 0x7f020013
int drawable abc_ic_clear_mtrl_alpha 0x7f020014
int drawable abc_ic_commit_search_api_mtrl_alpha 0x7f020015
int drawable abc_ic_go_search_api_mtrl_alpha 0x7f020016
int drawable abc_ic_menu_copy_mtrl_am_alpha 0x7f020017
int drawable abc_ic_menu_cut_mtrl_alpha 0x7f020018
int drawable abc_ic_menu_moreoverflow_mtrl_alpha 0x7f020019
int drawable abc_ic_menu_paste_mtrl_am_alpha 0x7f02001a
int drawable abc_ic_menu_selectall_mtrl_alpha 0x7f02001b
int drawable abc_ic_menu_share_mtrl_alpha 0x7f02001c
int drawable abc_ic_search_api_mtrl_alpha 0x7f02001d
int drawable abc_ic_voice_search_api_mtrl_alpha 0x7f02001e
int drawable abc_item_background_holo_dark 0x7f02001f
int drawable abc_item_background_holo_light 0x7f020020
int drawable abc_list_divider_mtrl_alpha 0x7f020021
int drawable abc_list_focused_holo 0x7f020022
int drawable abc_list_longpressed_holo 0x7f020023
int drawable abc_list_pressed_holo_dark 0x7f020024
int drawable abc_list_pressed_holo_light 0x7f020025
int drawable abc_list_selector_background_transition_holo_dark 0x7f020026
int drawable abc_list_selector_background_transition_holo_light 0x7f020027
int drawable abc_list_selector_disabled_holo_dark 0x7f020028
int drawable abc_list_selector_disabled_holo_light 0x7f020029
int drawable abc_list_selector_holo_dark 0x7f02002a
int drawable abc_list_selector_holo_light 0x7f02002b
int drawable abc_menu_hardkey_panel_mtrl_mult 0x7f02002c
int drawable abc_popup_background_mtrl_mult 0x7f02002d
int drawable abc_ratingbar_full_material 0x7f02002e
int drawable abc_spinner_mtrl_am_alpha 0x7f02002f
int drawable abc_spinner_textfield_background_material 0x7f020030
int drawable abc_switch_thumb_material 0x7f020031
int drawable abc_switch_track_mtrl_alpha 0x7f020032
int drawable abc_tab_indicator_material 0x7f020033
int drawable abc_tab_indicator_mtrl_alpha 0x7f020034
int drawable abc_text_cursor_mtrl_alpha 0x7f020035
int drawable abc_textfield_activated_mtrl_alpha 0x7f020036
int drawable abc_textfield_default_mtrl_alpha 0x7f020037
int drawable abc_textfield_search_activated_mtrl_alpha 0x7f020038
int drawable abc_textfield_search_default_mtrl_alpha 0x7f020039
int drawable abc_textfield_search_material 0x7f02003a
int drawable action_btn 0x7f02003b
int drawable asv 0x7f02003c
int drawable asy 0x7f02003d
int drawable back_to_top 0x7f02003e
int drawable base_action_bar_back_normal 0x7f02003f
int drawable bg_nothing 0x7f020040
int drawable browser_32 0x7f020041

**Comment by shwenzhang** [comment]
可以将applyResourceMapping关闭尝试一下

**Comment by liveei** [comment]
@shwenzhang   Warning:ignoreWarning is false, but resources.arsc is changed, you should use applyResourceMapping mode to build the new apk, otherwise, it may be crash at some times  
清理了工程重新走一遍，报上面的错误 ，因为第二个包打入了一些v4v7包的无用图片，资源确实发生了改变，所以会有上面的提示，其实通过ignore *.png 是可以解决上面问题， 但无法避免当真要替换资源的时候，100多K无用资源带来的损耗

**Comment by liveei** [comment]
@shwenzhang   应该是执行tinkerPatchOfficalRelease 生成新包的时候  shrinkResources true  未生效

**Comment by liveei** [comment]
@shwenzhang   
又看了下日志，assembleOfficalRelease  和 tinkerPatchOfficalRelease 两者shrinkResources 都生效了，
但tinkerPatchOfficalRelease 不知道什么原因把本来只需要在一个drawable文件夹存在的图片，
在其他drawable文件夹也都存了一份，不知道是否是tinker插件内部的一些操作引起的？

以下是tinkerPatchOfficalRelease   gradle 构建 的日志:
路径  app/build/outputs/mapping/official/release/resources.txt

android.content.res.Resources#getIdentifier present: true
Web content present: true

......省略若干项......
  
Skipped unused resource res/anim/coupons_account.xml: 660 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/out_left_right.xml: 468 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/out_right_left.xml: 468 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/pulldown_rotate_down.xml: 500 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/pulldown_rotate_up.xml: 500 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/rehome_in.xml: 428 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/rehome_out.xml: 428 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/translationy_in.xml: 640 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/translationy_out.xml: 640 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_fb_slide_in_from_left.xml: 440 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_fb_slide_in_from_right.xml: 440 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_fb_slide_out_from_left.xml: 440 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_fb_slide_out_from_right.xml: 440 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_share_popup_enter.xml: 796 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_share_popup_exit.xml: 796 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_socialize_fade_in.xml: 464 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_socialize_fade_out.xml: 464 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_socialize_shareboard_animation_in.xml: 768 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_socialize_shareboard_animation_out.xml: 424 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_socialize_slide_in_from_bottom.xml: 440 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/anim/umeng_socialize_slide_out_from_bottom.xml: 440 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable-hdpi-v4/ic_action_about_96.png: 1215 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-hdpi-v4/ic_launcher.png: 592 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-hdpi-v4/ic_recent_qr.png: 2076 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-hdpi-v4/ico_indicator_bottom_silver.png: 180 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-hdpi-v4/ico_pic_placeholder.9.png: 3207 bytes (replaced with small dummy file of size 77 bytes)
Skipped unused resource res/drawable-mdpi-v4/ic_launcher.png: 499 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/btn_back.png: 603 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/crop__divider.9.png: 168 bytes (replaced with small dummy file of size 77 bytes)
Skipped unused resource res/drawable-xhdpi-v4/crop__ic_cancel.png: 1358 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/crop__ic_done.png: 1320 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/crop__tile.png: 142 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/ic_launcher.png: 655 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/ic_menu_back.png: 1319 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/liveness_faceppinside.png: 10377 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/liveness_head_left.png: 17191 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/liveness_head_right.png: 17180 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/liveness_layout_bottom_tips.png: 7582 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xhdpi-v4/liveness_surfacemask.9.png: 3082 bytes (replaced with small dummy file of size 77 bytes)
Skipped unused resource res/drawable-xxhdpi-v4/asv.png: 2759 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable-xxhdpi-v4/ic_launcher.png: 1221 bytes (replaced with small dummy file of size 67 bytes)
Skipped unused resource res/drawable/crop__selectable_background.xml: 1060 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/crop__texture.xml: 380 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_base_scrollbar.xml: 776 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_base_title_bg.xml: 520 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_capture_toast_bg.xml: 540 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_compat_status_bar_bg.xml: 572 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_search_tab_bg.xml: 540 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_toast_bg.xml: 680 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_wallet_divider.xml: 572 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/shape_webview_progress_end.xml: 740 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/tb_munion_icon.xml: 832 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/drawable/tb_munion_item_selector.xml: 620 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/layout/crop__activity_crop.xml: 744 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/layout/crop_layout_done_cancel.xml: 1592 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/layout/cube_ptr_simple_loading.xml: 452 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/layout/tb_munion_aditem.xml: 668 bytes (replaced with small dummy file of size 104 bytes)
Skipped unused resource res/raw/keep.xml: 265 bytes
Skipped unused resource res/raw/meglive_failed.mp3: 76948 bytes (replaced with small dummy file of size 0 bytes)
Skipped unused resource res/raw/meglive_success.mp3: 50617 bytes (replaced with small dummy file of size 0 bytes)

**Comment by shwenzhang** [comment]
这边无法复现，你本地尝试localmaven定位一下把

**Comment by iluhcm** [comment]
这个会不会是你打release包时点run编译打出来的，然后打补丁包时用tinkerXXXPatch打出来的？之前遇到过一次， 必须用assembleXXXRelease打包，然后用tinkerXXXPatch打补丁包才没有这些资源文件。
