### ISSUE TITLE
Demo不能运行

### ISSUE THREAD

**Issue by yinguanping** [Tencent/tinker#261]
下载了tinker-sample-android的demo。并不能运行。没有按照接入文档中所述生成相应的文件夹，并且。调用tinkerpatchdebug  是在哪里。能把接入文档写的再详细些吗

**Comment by yinguanping** [comment]
如何生成patch包。不解，求指教

**Comment by yatou252303** [comment]
建议学习一下gradle脚本部分。右边框上有gradle 脚本面板



279642707@qq.com
 
发件人： yinguanping
发送时间： 2016-12-16 11:07
收件人： Tencent/tinker
抄送： Subscribed
主题： [Tencent/tinker] Demo不能运行 (#261)
下载了tinker-sample-android的demo。并不能运行。没有按照接入文档中所述生成相应的文件夹，并且。调用tinkerpatchdebug 是在哪里。能把接入文档写的再详细些吗

**Comment by shwenzhang** [comment]
请认真学习文档后再提问
