### ISSUE TITLE
about application

### ISSUE THREAD

**Issue by stewForAni** [Tencent/tinker#265]
注解的方式 没有成功生成自己的Application 是什么原因？

官方demo下载下来SampleApplication也是没有的，但编译之后就有了，

 但在自己项目里没有成功，编译之后还是报红

**Comment by stewForAni** [comment]
自己的application 在其他位置生成了  需要添加apt依赖

**Comment by Android-Star** [comment]
我的也没有生成application 但是我是有apt依赖的  你知道怎么回事么？
