### ISSUE TITLE
tinkerPatchDebug编辑失败

### ISSUE THREAD

**Issue by yinguanping** [Tencent/tinker#266]
前面的步骤编译全部OK。但在最后tinkerPatchDebug步骤时卡住不动。并且最上面Run build处出现红色叹号，但是并没有失败log。我运行git上面的demo是没有问题。这个原理是哪里配置出错了。求解，我都已经又重新配置过一次了，还是不行。

**Comment by shwenzhang** [comment]
see wiki

**Comment by bacy** [comment]
你好，我也碰到了，请问你最后怎么解决的？
