### ISSUE TITLE
Tinker和ReactApplication冲突

### ISSUE THREAD

**Issue by superLY91** [Tencent/tinker#267]
Tinker生成的代理MyTinkerApplication，没有implements ReactApplication。
![image](https://cloud.githubusercontent.com/assets/5880785/21304267/ddc7d5be-c5fe-11e6-93a1-18e9f4667983.png)
导致强转ReactApplication时报 java.lang.ClassCastException
![image](https://cloud.githubusercontent.com/assets/5880785/21304282/02309c7e-c5ff-11e6-8c81-6b66200bf3da.png)

可以使用#180 方法解决。是更换RN接入方式。
请问tinker是否可以兼容这个问题。比如生成代理Application的模版中增加供实现接口的注解标识。

**Comment by shwenzhang** [comment]
不行，只要增加了，就会导致提前导入这些类。后面会增加反射Application的方式满足这个需求
