### ISSUE TITLE
Demo app can't start with sdk version 24 and java version 1.8

### ISSUE THREAD

**Issue by kindyrain** [Tencent/tinker#269]
we build tinker_sample_android App with Android Studio 2.2.1.  The apk will crash when start, since tinker build plugin doesn't create the SampleApplication.java file, so the class SampleApplication class can't find.
build.gradle config as below:
def javaVersion = JavaVersion.VERSION_1_8

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"

    compileOptions {
        sourceCompatibility javaVersion
        targetCompatibility javaVersion
    }
    defaultConfig {
        applicationId "tinker.sample.android"
        minSdkVersion 10
        targetSdkVersion 24
        versionCode 1
        versionName "1.0.0"
        jackOptions {
            enabled true
        }
......
}

**Comment by shwenzhang** [comment]
SampleApplication will be created during building the apk

**Comment by shwenzhang** [comment]
jack mode does not support android processor, you can create a Application yourself

**Comment by kindyrain** [comment]
Thanks
