### ISSUE TITLE
Error:Execution failed for task ':app:tinkerProcessDebugManifest'. > tinkerId is not set!!!

### ISSUE THREAD

**Issue by lsprite** [Tencent/tinker#27]
Error:Execution failed for task ':app:tinkerProcessDebugManifest'.
> tinkerId is not set!!!  这是什么意思？

**Comment by anzyhui** [comment]
哈哈，我也是一样的错，貌似是里面的gitSha()方法返回字符串为空，因为我studio 并没有配置git,拿不到所以报空，把他返回值写死就可以成功运行。

**Comment by shwenzhang** [comment]
#11, 再次说明一点，在提issue之前需要先查找一下相关issue。以后这样的问题一律不再回答

**Comment by lsprite** [comment]
你在open里的把原先提的这个问题给close了

**Comment by lsprite** [comment]
@anzyhui 怎么能生成补丁包，我已经手动改了tinkerOldApkPath这个的地址了，但是build/outputs并没有tinkerPatch这个目录生成

**Comment by anzyhui** [comment]
@lsprite 右侧gradle选择tinkerPatchXXX，就会在相应目录生成补丁相关文件了啊

**Comment by lsprite** [comment]
@anzyhui 谢谢啦
