### ISSUE TITLE
Warning:ignoreWarning is false, but we found loader classes are found in old secondary dex

### ISSUE THREAD

**Issue by yinguanping** [Tencent/tinker#270]
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:/Users/yinguanping/b2c/mtime_app/mTimeMovie/build/bakApk/mTimeMovie-debug-1220-09-57-49.apk
newApk:/Users/yinguanping/b2c/mtime_app/mTimeMovie/build/outputs/apk/mTimeMovie-debug.apk
outputFolder:/Users/yinguanping/b2c/mtime_app/mTimeMovie/build/outputs/tinkerPatch/debug
isIgnoreWarning:false
isInsertStubMode:false
7-ZipPath:/Users/yinguanping/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:tinker is sample to use
filed name:platform, filed value:all
filed name:patchVersion, filed value:1.0
dex configs: 
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.frame.activity.MtimeApplication
dex loader:com.tencent.tinker.loader.*
dex loader:tinker.sample.android.app.BaseBuildInfo
lib configs: 
libPattern:lib/armeabi/.*\.so
resource configs: 
resPattern:AndroidManifest\.xml
resPattern:res/.*
resPattern:resources\.arsc
resPattern:assets/.*
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: mTimeMovie-debug-1220-09-57-49.apk, size=22615114, md5=bdd5a7f409adf3ee0aa88e2a138dd0f8
new apk: mTimeMovie-debug.apk, size=22615386, md5=2bf5b13f41815251afc4626da0fedbe6
UnZipping apk to /Users/yinguanping/b2c/mtime_app/mTimeMovie/build/outputs/tinkerPatch/debug/mTimeMovie-debug-1220-09-57-49
UnZipping apk to /Users/yinguanping/b2c/mtime_app/mTimeMovie/build/outputs/tinkerPatch/debug/mTimeMovie-debug
Check for loader classes in dex: classes.dex
Check for loader classes in dex: classes2.dex
Warning:ignoreWarning is false, but we found loader classes are found in old secondary dex. Found classes: {Lcom/tencent/tinker/loader/shareutil/ShareResPatchInfo;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V23;,Lcom/tencent/tinker/loader/shareutil/ShareBsDiffPatchInfo;,Lcom/tencent/tinker/loader/BuildConfig;,Lcom/tencent/tinker/loader/shareutil/ShareFileLockHelper;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V14;,Lcom/tencent/tinker/loader/TinkerParallelDexOptimizer$ResultCallback;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V4;,Lcom/tencent/tinker/loader/TinkerParallelDexOptimizer;,Lcom/tencent/tinker/loader/TinkerDexLoader$1;,Lcom/tencent/tinker/loader/TinkerTestDexLoad;,Lcom/tencent/tinker/loader/TinkerSoLoader;,Lcom/tencent/tinker/loader/TinkerDexLoader;,Lcom/tencent/tinker/loader/TinkerResourcePatcher;,Lcom/tencent/tinker/loader/AndroidNClassLoader;,Lcom/tencent/tinker/loader/TinkerResourceLoader;,Lcom/tencent/tinker/loader/shareutil/SharePatchInfo;,Lcom/tencent/tinker/loader/shareutil/ShareDexDiffPatchInfo;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V19;,Lcom/tencent/tinker/loader/TinkerParallelDexOptimizer$OptimizeWorker;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder;,Lcom/tencent/tinker/loader/shareutil/ShareResPatchInfo$LargeModeInfo;}

tinkerPatchDebu卡在最后一步不能执行。Log如上。

**Comment by shwenzhang** [comment]
see wiki, loader class一定要在主dex
