### ISSUE TITLE
cleanPatch可以主动调用吗？

### ISSUE THREAD

**Issue by superLY91** [Tencent/tinker#272]
![image](https://cloud.githubusercontent.com/assets/5880785/21338970/eea7150e-c6b5-11e6-803a-9ca6a80a4725.png)
![image](https://cloud.githubusercontent.com/assets/5880785/21339036/890ab2f4-c6b6-11e6-91cf-6f3484d867dd.png)

请问一下cleanPatch可以主动调用吗？ 
1 在补丁已经加载的前提下清除补丁，可能会引起crash。
   crash会发生在cleanPatch方法调用时，还是patch修复的方法调用时呢？
2 如果我做一个tinker的开关，当开关关闭时，可以主动调用cleanPatch吗？这时候有可能用户已经加载过patch了，而且这时重启进程不合适吧，可以做到用户无感知吗？

**Comment by shwenzhang** [comment]
如果补丁已经加载的前提，清理补丁需要先杀掉其他所有进程，然后自杀

**Comment by superLY91** [comment]
在补丁已经加载的前提下清除补丁，可能会引起crash。crash会发生在cleanPatch方法调用时，还是patch修复的方法调用时呢？
