### ISSUE TITLE
Tinker Platform sdk allowBackup 冲突

### ISSUE THREAD

**Issue by yinguanping** [Tencent/tinker#273]
/Users/yinguanping/b2c/mtime_app/mTimeMovie/AndroidManifest.xml:67:9-36 Error:
	Attribute application@allowBackup value=(false) from AndroidManifest.xml:67:9-36
	is also present at [com.tencent.tinker:tinker-server-android:0.3.2] AndroidManifest.xml:11:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:65:5-1013:19 to override.

为什么tinker platform接入的sdk会有allowBackup值为true的设定。patch后台更新patch需要备份应用数据？ 我的应用不改成true 编译都不过

**Comment by shwenzhang** [comment]
需要等1.7.6版本发布

**Comment by w4lle** [comment]
AndroidManifest添加``tools:replace="android:allowBackup``
