### ISSUE TITLE
在loadLibraryFromTinker（）动态加载so库的时, 获取loadResult.libs的结果null？这是什么原因？

### ISSUE THREAD

**Issue by LiuJunb** [Tencent/tinker#276]
final Tinker tinker = Tinker.with(context);
                tinker.cleanPatch();
 
                 String path= Environment.getExternalStorageDirectory().getAbsolutePath() + "/patch_signed_7zip.apk";
                TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(),path );
                Log.d("TAG","path="+path);

                String libname="testShare";
                String relativePath="assets/x86";
                

                libname = libname.startsWith("lib") ? libname : "lib" + libname;
                libname = libname.endsWith(".so") ? libname : libname + ".so";
                String relativeLibPath = relativePath + "/" + libname;
 
                Log.i("TAG", "relativeLibPath=" + relativeLibPath);
                Log.i("TAG", "isEnabledForNativeLib=" + tinker.isEnabledForNativeLib());
                Log.i("TAG", "isTinkerLoaded=" + tinker.isTinkerLoaded()); 

                if (tinker.isEnabledForNativeLib() && tinker.isTinkerLoaded()) {
                   
                    TinkerLoadResult loadResult = tinker.getTinkerLoadResultIfPresent();
                    //这里loadResult.libs的结果为空？？是什么原因呢？
                    if (loadResult.libs != null) {
                        Log.i("TAG", "loadResult=" + loadResult.libs.size());
                        for (String name : loadResult.libs.keySet()) {
                            Log.i("TAG", "name=" + name);
                            if (name.equals(relativeLibPath)) {
                                Log.i("TAG", "name.equals=" + relativeLibPath);
                                String patchLibraryPath = loadResult.libraryDirectory + "/" + name;
                                File library = new File(patchLibraryPath);
                                if (library.exists()) {
                                    //whether we check md5 when load
                                    boolean verifyMd5 = tinker.isTinkerLoadVerify();
                                    if (verifyMd5 && !SharePatchFileUtil.verifyFileMd5(library, loadResult.libs.get(name))) {
                                        tinker.getLoadReporter().onLoadFileMd5Mismatch(library, ShareConstants.TYPE_LIBRARY);
                                    } else {
                                        System.load(patchLibraryPath);
                                        Log.i("TAG", "loadLibraryFromTinker success:" + patchLibraryPath);
                                    }
                                }
                            }
                        }
                    }else{
                        Log.i("TAG", "loadResult.libs=null" );
                    }
                }

**Comment by shwenzhang** [comment]
因为没有补丁so

**Comment by LiuJunb** [comment]
@shwenzhang  补丁so 是存在patch_signed_7zip.apk这里吗？

**Comment by LiuJunb** [comment]
看了wiki ，没看明白生成的补丁so 在哪里。
