### ISSUE TITLE
已经build successful 但onReceiveUpgradePatch不成功

### ISSUE THREAD

**Issue by AnotherSkyBoy** [Tencent/tinker#277]
整个流程走下来了，但还是不成功，请问可能是什么原因
生成差异文件：
E:\ASProjects\TinkerApplication\app>gradle tinkerPatchDebug
Incremental java compilation is an incubating feature.                         
----------------------tinker build warning ------------------------------------
tinker auto operation:      
excluding annotation processor and source template from app packaging. Enable dx
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is bo

tinker will change your build configs:
we will add TINKER_ID=1.0 in your build output manifest file build/intermediates

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermedi
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_in
and you should copy it to your own multiDex keep proguard file yourself.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the ne
-----------------------------------------------------------------
----------------------tinker build warning ------------------------------------
tinker auto operation:
excluding annotation processor and source template from app packaging. Enable dx
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is bo

tinker will change your build configs:
we will add TINKER_ID=1.0 in your build output manifest file build/intermediates

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermedi
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_in
and you should copy it to your own multiDex keep proguard file yourself.

if applyResourceMapping file is exist
we will build tinker apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the ne
-----------------------------------------------------------------
:app:preBuild UP-TO-DATE    
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2421Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72421Library UP-TO-DATE      
:app:prepareComAndroidSupportSupportCompat2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUi2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUtils2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportFragment2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportMediaCompat2421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42421Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2421Library UP-TO-DATE
:app:prepareComTencentTinkerTinkerAndroidLib175Library UP-TO-DATE
:app:prepareComTencentTinkerTinkerAndroidLoader175Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE      
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE      
:app:processDebugManifest                 
:app:tinkerProcessDebugManifest
tinker add tinker_id_1.0 to your AndroidManifest.xml E:\ASProjects\TinkerApplica
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/Andro
:app:tinkerProcessDebugResourceId
apply resource mapping file  is illegal, just ignore
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac                 
Incremental compilation of 1 classes completed in 0.537 secs.
:app:compileDebugNdk UP-TO-DATE                
:app:compileDebugSources
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:transformClassesWithAuxiliaryInjectForDebug                 
[AuxiliaryInject] PreGeneratedPatchDex mode is disabled, skip transforming.
:app:transformClassesWithDexForDebug                 

Running dex as a separate process.

To run dex in process, the Gradle daemon needs a larger heap.
It currently has 247 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at le
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environ

:app:mergeDebugJniLibFolders UP-TO-DATE              
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug                 
:app:assembleDebug
:app:tinkerPatchDebug                 
-----------------------Tinker patch begin-----------------------
configuration:
oldApk:D://app_bug.apk
newApk:E:\ASProjects\TinkerApplication\app\build\outputs\apk\app-debug.apk
outputFolder:E:\ASProjects\TinkerApplication\app\build\outputs/tinkerPatch/debug
isIgnoreWarning:false
isInsertStubMode:false
7-ZipPath:C:\Users\xcl\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZi
useSignAPk:true
package meta fields:
filed name:TINKER_ID, filed value:1.0
dex configs:
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:ook.yzx.tinker.Application
dex loader:com.tencent.tinker.loader.*
lib configs:
libPattern:lib/x86_64/.*\.so
libPattern:lib/x86/.*\.so
libPattern:lib/armeabi-v7a/.*\.so
libPattern:lib/armeabi/.*\.so
libPattern:lib/arm64-v8a/.*\.so
libPattern:lib/mips/.*\.so
libPattern:lib/mips64/.*\.so
resource configs:
resPattern:AndroidManifest\.xml
resPattern:res/.*
resPattern:assets/.*
resPattern:resources\.arsc
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: app_bug.apk, size=1508283, md5=29dce069b8524a21d5f27dd3fc47be98
new apk: app-debug.apk, size=1535343, md5=5d4a71f629d82b78dba9a576770ecd20

                                                                               U
UnZipping apk to E:\ASProjects\TinkerApplication\app\build\outputs\tinkerPatch\d
Check for loader classes in dex: classes.dex

Gen classes.dex patch file:E:\ASProjects\TinkerApplication\app\build\outputs\tin
Verifying if patched new dex is logically the same as original new dex: app-debu

Gen classes.dex for dalvik full dex file:E:\ASProjects\TinkerApplication\app\bui
DexDecoder:write meta file data: classes.dex,,03a148462e22cd098121870bc61e5934,0

Add test install result dex: E:\ASProjects\TinkerApplication\app\build\outputs\t
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much mo
Current 7za path:C:\Users\xcl\.gradle\caches\modules-2\files-2.1\com.tencent.mm\
Result: final signed patch result: E:\ASProjects\TinkerApplication\app\build\out
Result: final signed with 7zip patch result: E:\ASProjects\TinkerApplication\app
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 384 byte, you sho
Tinker patch done, total time cost: 3.416000s
Tinker patch done, you can go to file to find the output E:\ASProjects\TinkerApp
-----------------------Tinker patch end-------------------------

BUILD SUCCESSFUL

Total time: 19.287 secs

onReceiveUpgradePatch()运行时log:
tinkerapplication I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                             PatchResult: 
                                                                                             isUpgradePatch:true
                                                                                             isSuccess:false
                                                                                             rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                                             costTime:74
                                                                                              
12-22 14:40:31.020 9845-10789/com.xcl.tinkerapplication I/Process: Sending signal. PID: 10744 SIG: 9
12-22 14:40:31.130 9845-9859/com.xcl.tinkerapplication I/art: Ignoring second debugger -- accepting and dropping****

**Comment by shwenzhang** [comment]
see wiki
