### ISSUE TITLE
升级Gradle版本之后出现Tinker does not support instant run mode

### ISSUE THREAD

**Issue by TonyChou** [Tencent/tinker#280]
升级Gradle版本为：
dependencies {
        // classpath 'com.android.tools.build:gradle:2.1.2'
         classpath 'com.android.tools.build:gradle:2.2.2'
 }
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

编译的时候报以下错误，哪位大牛能帮忙看看，谢谢了：
Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:assembleDebug]
Error:A problem occurred configuring project ':app'.
> Tinker does not support instant run mode, please trigger build by assembleDebug or disable instant run in 'File->Settings...'.
Information:BUILD FAILED
Information:Total time: 0.513 secs
Error:----------------------tinker build warning ------------------------------------
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=100352025e9138b7edebb709bf4c1c03 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and you should copy it to your own multiDex keep proguard file yourself.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Tinker does not support instant run mode, please trigger build by assembleDebug or disable instant run in 'File->Settings...'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by shwenzhang** [comment]
Tinker does not support instant run mode, please trigger build by assembleDebug or disable instant run in 'File->Settings...'.

**Comment by TonyChou** [comment]
每次都需要执行这个么？无法支持instant run mode，感觉很不方便呢。

**Comment by shwenzhang** [comment]
see wiki
