### ISSUE TITLE
[改进] tinkerPatch 输出路径变为可配置

### ISSUE THREAD

**Issue by walfud** [Tencent/tinker#286]
hi, 我看了 [`TinkerPatchPlugin` 中关于 patch 输出的代码](https://github.com/Tencent/tinker/blob/master/tinker-build/tinker-patch-gradle-plugin/src/main/groovy/com/tencent/tinker/build/gradle/TinkerPatchPlugin.groovy#L140), 希望这里能做成像 oldApk 一样可配置.

**Comment by shwenzhang** [comment]
这样的目的是？

**Comment by walfud** [comment]
1, build 目录经常被 clean 清理.
2, 我们想保留每次发布的 patch 相关信息. 万一有问题可以查看原因.
我们现在的做法是在 patch 结束后加入了一个 copy task, 把 tinkerPatch 改名+拷贝到项目根目录下.

**Comment by shwenzhang** [comment]
一般来说输出目录的改变都是通过自定义task即可。
