### ISSUE TITLE
sample 里面一直patch file is not exist

### ISSUE THREAD

**Issue by 675915408** [Tencent/tinker#29]
已经修改过 tinkeroldapkpath

**Comment by shwenzhang** [comment]
需要将编译好的patch推送到手机中，请先仔细查看文档支持。

**Comment by 675915408** [comment]
推送到手机后 patch fail please check reson

**Comment by parcool** [comment]
@shwenzhang 已经正常走完接入指南“使用” 123步骤，还是出现这个问题。进DDMS也能看到推送上去的patch apk。----小米2s
