### ISSUE TITLE
打包apk报错，有那位好心人帮忙解决下感激不尽！

### ISSUE THREAD

**Issue by yangxp108** [Tencent/tinker#290]
Error:A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Cannot invoke method getAbsolutePath() on null object
   > Task with name 'tinkerPatchFreeRelease' not found in project ':app'.

**Comment by shwenzhang** [comment]
--stracktrace
![image](https://cloud.githubusercontent.com/assets/8335303/21521494/5be688ce-cd38-11e6-9760-b35f39128ffa.png)

**Comment by yangxp108** [comment]
Executing tasks: [:app:assembleFreeRelease]

Parallel execution with configuration on demand is an incubating feature.
WARNING: The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Incremental java compilation is an incubating feature.

----------------------tinker build warning ------------------------------------
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=1.0 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Cannot invoke method getAbsolutePath() on null object
   > Task with name 'tinkerPatchFreeRelease' not found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.258 secs

**Comment by shwenzhang** [comment]
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by yangxp108** [comment]
？？？

**Comment by yangxp108** [comment]
11:00:38: Executing external task 'build'...
Parallel execution is an incubating feature.
WARNING: The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Incremental java compilation is an incubating feature.
----------------------tinker build warning ------------------------------------
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=1.0 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------
:app:preBuild UP-TO-DATE
:app:preFreeDebugBuild UP-TO-DATE
:app:checkFreeDebugManifest
:bugoutSDK:preBuild
:app:preFreeReleaseBuild UP-TO-DATE
:app:preProDebugBuild UP-TO-DATE
:bugoutSDK:preBuild UP-TO-DATE
:app:preProReleaseBuild UP-TO-DATE
:kisoFrame:preBuild UP-TO-DATE
:kisoFrame:preReleaseBuild UP-TO-DATE
:kisoFrame:checkReleaseManifest
:kisoFrame:preDebugAndroidTestBuild UP-TO-DATE
:kisoFrame:preDebugBuild UP-TO-DATE
:kisoFrame:preDebugUnitTestBuild UP-TO-DATE
:kisoFrame:preReleaseUnitTestBuild UP-TO-DATE
:kisoFrame:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:bugoutSDK:preReleaseBuild UP-TO-DATE
:bugoutSDK:checkReleaseManifest
:bugoutSDK:prepareReleaseDependencies
:bugoutSDK:compileReleaseAidl
:third-party:uikit:preBuild UP-TO-DATE
:third-party:uikit:preReleaseBuild UP-TO-DATE
:third-party:uikit:checkReleaseManifest
:third-party:uikit:preDebugAndroidTestBuild UP-TO-DATE
:third-party:uikit:preDebugBuild UP-TO-DATE
:third-party:uikit:preDebugUnitTestBuild UP-TO-DATE
:app:preFreeDebugAndroidTestBuild UP-TO-DATE
:app:preProDebugAndroidTestBuild UP-TO-DATE
:app:generateFreeDebugBuildConfig
:third-party:uikit:preReleaseUnitTestBuild UP-TO-DATE
:third-party:uikit:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:app:generateFreeDebugResValues
:app:incrementalFreeDebugJavaCompilationSafeguard
:third-party:uikit:prepareComAndroidSupportAppcompatV72340Library
:bugoutSDK:compileReleaseNdk UP-TO-DATE
:bugoutSDK:compileLint
:bugoutSDK:copyReleaseLint UP-TO-DATE
:bugoutSDK:mergeReleaseShaders
:app:compileFreeDebugNdk UP-TO-DATE
:app:mergeFreeDebugShaders
:kisoFrame:prepareComAndroidSupportAppcompatV72340Library
:app:compileFreeDebugShaders
:bugoutSDK:compileReleaseShaders
:bugoutSDK:generateReleaseAssets
:bugoutSDK:mergeReleaseAssets
:app:generateFreeDebugAssets
:app:processFreeDebugJavaRes UP-TO-DATE
:app:validateSigningFreeDebug
:app:checkProDebugManifest
:app:generateProDebugBuildConfig
:bugoutSDK:mergeReleaseProguardFiles UP-TO-DATE
:bugoutSDK:packageReleaseRenderscript UP-TO-DATE
:bugoutSDK:compileReleaseRenderscript
:app:generateProDebugResValues
:bugoutSDK:generateReleaseResValues
:app:incrementalProDebugJavaCompilationSafeguard
:bugoutSDK:generateReleaseResources
:bugoutSDK:packageReleaseResources
:app:compileProDebugNdk UP-TO-DATE
:app:mergeProDebugShaders
:app:compileProDebugShaders
:app:generateProDebugAssets
:app:processProDebugJavaRes UP-TO-DATE
:app:validateSigningProDebug
:app:checkFreeReleaseManifest
:app:preFreeDebugUnitTestBuild UP-TO-DATE
:app:preFreeReleaseUnitTestBuild UP-TO-DATE
:app:preProDebugUnitTestBuild UP-TO-DATE
:app:preProReleaseUnitTestBuild UP-TO-DATE
:app:generateFreeReleaseBuildConfig
:app:generateFreeReleaseResValues
:app:incrementalFreeReleaseJavaCompilationSafeguard
:app:compileFreeReleaseNdk UP-TO-DATE
:app:mergeFreeReleaseShaders
:app:compileFreeReleaseShaders
:app:generateFreeReleaseAssets
:app:processFreeReleaseJavaRes UP-TO-DATE
:app:checkProReleaseManifest
:app:generateProReleaseBuildConfig
:app:generateProReleaseResValues
:app:incrementalProReleaseJavaCompilationSafeguard
:app:compileProReleaseNdk UP-TO-DATE
:app:mergeProReleaseShaders
:app:compileProReleaseShaders
:app:generateProReleaseAssets
:app:processProReleaseJavaRes UP-TO-DATE
:app:incrementalFreeDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:processFreeDebugUnitTestJavaRes UP-TO-DATE
:app:mockableAndroidJar UP-TO-DATE
:app:incrementalFreeReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:processFreeReleaseUnitTestJavaRes UP-TO-DATE
:app:incrementalProDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:processProDebugUnitTestJavaRes UP-TO-DATE
:app:incrementalProReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:processProReleaseUnitTestJavaRes UP-TO-DATE
:bugoutSDK:processReleaseManifest
:bugoutSDK:generateReleaseBuildConfig
:bugoutSDK:processReleaseResources
:bugoutSDK:generateReleaseSources
:bugoutSDK:incrementalReleaseJavaCompilationSafeguard
:bugoutSDK:compileReleaseJavaWithJavac
:bugoutSDK:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:bugoutSDK:processReleaseJavaRes UP-TO-DATE
:bugoutSDK:transformResourcesWithMergeJavaResForRelease
:bugoutSDK:transformClassesAndResourcesWithSyncLibJarsForRelease
:bugoutSDK:mergeReleaseJniLibFolders
:bugoutSDK:transformNative_libsWithMergeJniLibsForRelease
:bugoutSDK:transformNative_libsWithSyncJniLibsForRelease
:bugoutSDK:bundleRelease
:bugoutSDK:preDebugBuild UP-TO-DATE
:bugoutSDK:checkDebugManifest
:bugoutSDK:prepareDebugDependencies
:bugoutSDK:compileDebugAidl
:bugoutSDK:compileDebugNdk UP-TO-DATE
:bugoutSDK:copyDebugLint UP-TO-DATE
:bugoutSDK:mergeDebugShaders
:bugoutSDK:compileDebugShaders
:bugoutSDK:generateDebugAssets
:bugoutSDK:mergeDebugAssets
:bugoutSDK:mergeDebugProguardFiles UP-TO-DATE
:bugoutSDK:packageDebugRenderscript UP-TO-DATE
:bugoutSDK:compileDebugRenderscript
:bugoutSDK:generateDebugResValues
:bugoutSDK:generateDebugResources
:bugoutSDK:packageDebugResources
:bugoutSDK:processDebugManifest
:bugoutSDK:generateDebugBuildConfig
:bugoutSDK:processDebugResources
:bugoutSDK:generateDebugSources
:bugoutSDK:incrementalDebugJavaCompilationSafeguard
:bugoutSDK:compileDebugJavaWithJavac
:bugoutSDK:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:bugoutSDK:processDebugJavaRes UP-TO-DATE
:bugoutSDK:transformResourcesWithMergeJavaResForDebug
:bugoutSDK:transformClassesAndResourcesWithSyncLibJarsForDebug
:bugoutSDK:mergeDebugJniLibFolders
:bugoutSDK:transformNative_libsWithMergeJniLibsForDebug
:bugoutSDK:transformNative_libsWithSyncJniLibsForDebug
:bugoutSDK:bundleDebug
:bugoutSDK:compileDebugSources
:bugoutSDK:assembleDebug
:bugoutSDK:compileReleaseSources
:bugoutSDK:assembleRelease
:bugoutSDK:assemble
:bugoutSDK:lint
:kisoFrame:prepareComAndroidSupportSupportV42340Library
:third-party:uikit:prepareComAndroidSupportDesign2340Library
:kisoFrame:prepareComAndroidSupportSupportVectorDrawable2340Library
:kisoFrame:prepareReleaseDependencies
:kisoFrame:compileReleaseAidl
:kisoFrame:compileReleaseNdk UP-TO-DATE
:kisoFrame:compileLint
:kisoFrame:copyReleaseLint UP-TO-DATE
:kisoFrame:compileReleaseRenderscript
:kisoFrame:generateReleaseBuildConfig
:kisoFrame:generateReleaseResValues
:kisoFrame:generateReleaseResources
:kisoFrame:mergeReleaseResources
Ran lint on variant debug: 377 issues found
Ran lint on variant release: 377 issues found
Wrote HTML report to file:///F:/chuizhicaiV3.0/bugoutSDK/build/outputs/lint-results-debug.html
:third-party:uikit:prepareComAndroidSupportRecyclerviewV72340Library
Wrote XML report to file:///F:/chuizhicaiV3.0/bugoutSDK/build/outputs/lint-results-debug.xml
:bugoutSDK:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:bugoutSDK:preDebugUnitTestBuild UP-TO-DATE
:bugoutSDK:prepareDebugUnitTestDependencies
:bugoutSDK:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:bugoutSDK:processDebugUnitTestJavaRes UP-TO-DATE
:bugoutSDK:compileDebugUnitTestSources UP-TO-DATE
:bugoutSDK:mockableAndroidJar UP-TO-DATE
:bugoutSDK:assembleDebugUnitTest UP-TO-DATE
:bugoutSDK:testDebugUnitTest UP-TO-DATE
:bugoutSDK:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:bugoutSDK:preReleaseUnitTestBuild UP-TO-DATE
:bugoutSDK:prepareReleaseUnitTestDependencies
:bugoutSDK:compileReleaseUnitTestJavaWithJavac UP-TO-DATE
:bugoutSDK:processReleaseUnitTestJavaRes UP-TO-DATE
:bugoutSDK:compileReleaseUnitTestSources UP-TO-DATE
:bugoutSDK:assembleReleaseUnitTest UP-TO-DATE
:bugoutSDK:testReleaseUnitTest UP-TO-DATE
:bugoutSDK:test UP-TO-DATE
:bugoutSDK:check
:bugoutSDK:build
:third-party:uikit:prepareComAndroidSupportSupportV42340Library
:third-party:uikit:prepareComAndroidSupportSupportVectorDrawable2340Library
:third-party:uikit:prepareReleaseDependencies
:third-party:uikit:compileReleaseAidl
:third-party:uikit:compileReleaseNdk UP-TO-DATE
:third-party:uikit:compileLint
:third-party:uikit:copyReleaseLint UP-TO-DATE
:third-party:uikit:compileReleaseRenderscript
:third-party:uikit:generateReleaseBuildConfig
:third-party:uikit:generateReleaseResValues
:third-party:uikit:generateReleaseResources
:third-party:uikit:mergeReleaseResources
:kisoFrame:processReleaseManifest
:kisoFrame:processReleaseResources
:kisoFrame:generateReleaseSources
:kisoFrame:incrementalReleaseJavaCompilationSafeguard
:kisoFrame:compileReleaseJavaWithJavac
:kisoFrame:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:kisoFrame:extractReleaseAnnotations
:kisoFrame:mergeReleaseShaders
:kisoFrame:compileReleaseShaders
:kisoFrame:generateReleaseAssets
:kisoFrame:mergeReleaseAssets
:kisoFrame:mergeReleaseProguardFiles UP-TO-DATE
:kisoFrame:packageReleaseRenderscript UP-TO-DATE
:kisoFrame:packageReleaseResources
:kisoFrame:processReleaseJavaRes UP-TO-DATE
:kisoFrame:transformResourcesWithMergeJavaResForRelease
:kisoFrame:transformClassesAndResourcesWithSyncLibJarsForRelease
:kisoFrame:mergeReleaseJniLibFolders
:kisoFrame:transformNative_libsWithMergeJniLibsForRelease
:kisoFrame:transformNative_libsWithSyncJniLibsForRelease
:kisoFrame:bundleRelease
:kisoFrame:checkDebugManifest
:kisoFrame:prepareDebugDependencies
:kisoFrame:compileDebugAidl
:third-party:uikit:processReleaseManifest
:kisoFrame:compileDebugNdk UP-TO-DATE
:kisoFrame:copyDebugLint UP-TO-DATE
:kisoFrame:compileDebugRenderscript
:third-party:uikit:processReleaseResources
:kisoFrame:generateDebugBuildConfig
:kisoFrame:generateDebugResValues
:kisoFrame:generateDebugResources
:kisoFrame:mergeDebugResources
:third-party:uikit:generateReleaseSources
:third-party:uikit:incrementalReleaseJavaCompilationSafeguard
:third-party:uikit:compileReleaseJavaWithJavac
:third-party:uikit:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:kisoFrame:processDebugManifest
:kisoFrame:processDebugResources
:kisoFrame:generateDebugSources
:kisoFrame:incrementalDebugJavaCompilationSafeguard
:kisoFrame:compileDebugJavaWithJavac
:kisoFrame:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:kisoFrame:extractDebugAnnotations
:kisoFrame:mergeDebugShaders
:kisoFrame:compileDebugShaders
:kisoFrame:generateDebugAssets
:kisoFrame:mergeDebugAssets
:kisoFrame:mergeDebugProguardFiles UP-TO-DATE
:kisoFrame:packageDebugRenderscript UP-TO-DATE
:kisoFrame:packageDebugResources
:kisoFrame:processDebugJavaRes UP-TO-DATE
:kisoFrame:transformResourcesWithMergeJavaResForDebug
:kisoFrame:transformClassesAndResourcesWithSyncLibJarsForDebug
:kisoFrame:mergeDebugJniLibFolders
:kisoFrame:transformNative_libsWithMergeJniLibsForDebug
:kisoFrame:transformNative_libsWithSyncJniLibsForDebug
:kisoFrame:bundleDebug
:kisoFrame:compileDebugSources
:kisoFrame:assembleDebug
:kisoFrame:compileReleaseSources
:kisoFrame:assembleRelease
:kisoFrame:assemble
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\a\a\a.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\a\a\c.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\v1\b.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\v1\c.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\a\a\a.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\a\a\c.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\v1\b.class: broken class file?
Error processing F:\chuizhicaiV3.0\kisoFrame\libs\HwPush_SDK_V2705_nomap.jar:com\hianalytics\android\v1\c.class: broken class file?
:kisoFrame:lint
Ran lint on variant release: 4 issues found
Ran lint on variant debug: 4 issues found
Wrote HTML report to file:///F:/chuizhicaiV3.0/kisoFrame/build/outputs/lint-results-debug.html
Wrote XML report to file:///F:/chuizhicaiV3.0/kisoFrame/build/outputs/lint-results-debug.xml
:kisoFrame:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:kisoFrame:prepareDebugUnitTestDependencies
:kisoFrame:compileDebugUnitTestJavaWithJavac
:kisoFrame:processDebugUnitTestJavaRes UP-TO-DATE
:kisoFrame:compileDebugUnitTestSources
:kisoFrame:mockableAndroidJar UP-TO-DATE
:kisoFrame:assembleDebugUnitTest
:kisoFrame:testDebugUnitTest
:kisoFrame:incrementalReleaseUnitTestJavaCompilationSafeguard UP-TO-DATE
:kisoFrame:prepareReleaseUnitTestDependencies
:kisoFrame:compileReleaseUnitTestJavaWithJavac
:kisoFrame:processReleaseUnitTestJavaRes UP-TO-DATE
:kisoFrame:compileReleaseUnitTestSources
:kisoFrame:assembleReleaseUnitTest
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:kisoFrame:testReleaseUnitTest
:kisoFrame:test
:kisoFrame:check
:kisoFrame:build
:third-party:uikit:extractReleaseAnnotations
:third-party:uikit:mergeReleaseShaders
:third-party:uikit:compileReleaseShaders
:third-party:uikit:generateReleaseAssets
:third-party:uikit:mergeReleaseAssets
:third-party:uikit:mergeReleaseProguardFiles UP-TO-DATE
:third-party:uikit:packageReleaseRenderscript UP-TO-DATE
:third-party:uikit:packageReleaseResources
:third-party:uikit:processReleaseJavaRes UP-TO-DATE
:third-party:uikit:transformResourcesWithMergeJavaResForRelease
:third-party:uikit:transformClassesAndResourcesWithSyncLibJarsForRelease
:third-party:uikit:mergeReleaseJniLibFolders
:third-party:uikit:transformNative_libsWithMergeJniLibsForRelease
:third-party:uikit:transformNative_libsWithSyncJniLibsForRelease
:third-party:uikit:bundleRelease
:app:prepareChuizhicaiV30BugoutSDKUnspecifiedLibrary
:third-party:uikit:checkDebugManifest
:third-party:uikit:prepareDebugDependencies
:third-party:uikit:compileDebugAidl
:third-party:uikit:compileDebugNdk UP-TO-DATE
:third-party:uikit:copyDebugLint UP-TO-DATE
:third-party:uikit:compileDebugRenderscript
:third-party:uikit:generateDebugBuildConfig
:third-party:uikit:generateDebugResValues
:third-party:uikit:generateDebugResources
:third-party:uikit:mergeDebugResources
:app:prepareChuizhicaiV30KisoFrameUnspecifiedLibrary
:app:prepareChuizhicaiV30ThirdPartyUikitUnspecifiedLibrary
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:app:prepareComAndroidSupportAppcompatV72340Library
:third-party:uikit:processDebugManifest
:app:prepareComAndroidSupportCardviewV72340Library
:third-party:uikit:processDebugResources
:app:prepareComAndroidSupportDesign2340Library
:app:prepareComAndroidSupportMultidex101Library
:app:prepareComAndroidSupportRecyclerviewV72340Library
:app:prepareComAndroidSupportSupportV42340Library
:app:prepareComAndroidSupportSupportVectorDrawable2340Library
:app:prepareComDaimajiaAndroidanimationsLibrary113Library
:app:prepareComDaimajiaEasingLibrary101Library
:third-party:uikit:generateDebugSources
:third-party:uikit:incrementalDebugJavaCompilationSafeguard
:third-party:uikit:compileDebugJavaWithJavac
:third-party:uikit:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:prepareComGithubChrisbanesPhotoView126Library
:app:prepareComGithubIwgangCountdownview212Library
:app:prepareComSquareupLeakcanaryLeakcanaryAndroid14Beta2Library
:app:prepareComTencentTinkerTinkerAndroidLib176Library
:app:prepareComTencentTinkerTinkerAndroidLoader176Library
:app:prepareComTencentTinkerTinkerpatchSdk034Library
:app:prepareInSrainCubePtrLoadMore106Library
:app:prepareFreeDebugDependencies
:app:compileFreeDebugAidl
:app:compileFreeDebugRenderscript
:app:generateFreeDebugResources
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:app:mergeFreeDebugResources
:third-party:uikit:extractDebugAnnotations
:third-party:uikit:mergeDebugShaders
:third-party:uikit:compileDebugShaders
:third-party:uikit:generateDebugAssets
:third-party:uikit:mergeDebugAssets
:third-party:uikit:mergeDebugProguardFiles UP-TO-DATE
:third-party:uikit:packageDebugRenderscript UP-TO-DATE
:third-party:uikit:packageDebugResources
:third-party:uikit:processDebugJavaRes UP-TO-DATE
:third-party:uikit:transformResourcesWithMergeJavaResForDebug
:third-party:uikit:transformClassesAndResourcesWithSyncLibJarsForDebug
:third-party:uikit:mergeDebugJniLibFolders
:third-party:uikit:transformNative_libsWithMergeJniLibsForDebug
:third-party:uikit:transformNative_libsWithSyncJniLibsForDebug
:third-party:uikit:bundleDebug
:third-party:uikit:compileDebugSources
:third-party:uikit:assembleDebug
:third-party:uikit:compileReleaseSources
:third-party:uikit:assembleRelease
:third-party:uikit:assemble
:third-party:uikit:lint
:app:processFreeDebugManifest
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:23:5-80 Warning:
	Element uses-permission#android.permission.READ_EXTERNAL_STORAGE at AndroidManifest.xml:23:5-80 duplicated with element declared at AndroidManifest.xml:18:5-80
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:25:5-80 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:25:5-80 duplicated with element declared at AndroidManifest.xml:22:5-82
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:26:5-79 Warning:
	Element uses-permission#android.permission.READ_EXTERNAL_STORAGE at AndroidManifest.xml:26:5-79 duplicated with element declared at AndroidManifest.xml:23:5-80
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:30:5-79 Warning:
	Element uses-permission#android.permission.ACCESS_FINE_LOCATION at AndroidManifest.xml:30:5-79 duplicated with element declared at AndroidManifest.xml:24:5-79
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:39:5-81 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:39:5-81 duplicated with element declared at AndroidManifest.xml:25:5-80
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:51:5-75 Warning:
	Element uses-permission#android.permission.READ_PHONE_STATE at AndroidManifest.xml:51:5-75 duplicated with element declared at AndroidManifest.xml:21:5-74
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:73:5-66 Warning:
	Element uses-permission#android.permission.INTERNET at AndroidManifest.xml:73:5-66 duplicated with element declared at AndroidManifest.xml:35:5-67
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:74:5-78 Warning:
	Element uses-permission#android.permission.ACCESS_NETWORK_STATE at AndroidManifest.xml:74:5-78 duplicated with element declared at AndroidManifest.xml:36:5-79
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:75:5-75 Warning:
	Element uses-permission#android.permission.ACCESS_WIFI_STATE at AndroidManifest.xml:75:5-75 duplicated with element declared at AndroidManifest.xml:37:5-76
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:78:5-65 Warning:
	Element uses-permission#android.permission.VIBRATE at AndroidManifest.xml:78:5-65 duplicated with element declared at AndroidManifest.xml:48:5-66
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:80:5-79 Warning:
	Element uses-permission#android.permission.READ_EXTERNAL_STORAGE at AndroidManifest.xml:80:5-79 duplicated with element declared at AndroidManifest.xml:26:5-79
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:81:5-80 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:81:5-80 duplicated with element declared at AndroidManifest.xml:39:5-81
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:84:5-64 Warning:
	Element uses-permission#android.permission.CAMERA at AndroidManifest.xml:84:5-64 duplicated with element declared at AndroidManifest.xml:43:5-65
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:85:5-70 Warning:
	Element uses-permission#android.permission.RECORD_AUDIO at AndroidManifest.xml:85:5-70 duplicated with element declared at AndroidManifest.xml:68:5-71
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:86:5-74 Warning:
	Element uses-permission#android.permission.READ_PHONE_STATE at AndroidManifest.xml:86:5-74 duplicated with element declared at AndroidManifest.xml:51:5-75
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:91:5-79 Warning:
	Element uses-permission#android.permission.MODIFY_AUDIO_SETTINGS at AndroidManifest.xml:91:5-79 duplicated with element declared at AndroidManifest.xml:54:5-80
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:94:5-59 Warning:
	Element uses-feature#android.hardware.camera at AndroidManifest.xml:94:5-59 duplicated with element declared at AndroidManifest.xml:45:5-60
F:\chuizhicaiV3.0\app\src\main\AndroidManifest.xml:95:5-69 Warning:
	Element uses-feature#android.hardware.camera.autofocus at AndroidManifest.xml:95:5-69 duplicated with element declared at AndroidManifest.xml:46:5-70
tinker add tinker_id_1.0 to your AndroidManifest.xml F:\chuizhicaiV3.0\app\build\intermediates\manifests\full\free\debug\AndroidManifest.xml
tinker add com.chuizhicai.TestApplication to dex loader pattern
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml
:app:tinkerProcessFreeDebugManifest
apply resource mapping file F:\chuizhicaiV3.0\app\build\bakApk/app-1229-10-52-53/free/app-free-debug-R.txt is illegal, just ignore
:app:tinkerProcessFreeDebugResourceId
:app:processFreeDebugResources
Ran lint on variant release: 526 issues found
Ran lint on variant debug: 526 issues found
Wrote HTML report to file:///F:/chuizhicaiV3.0/third-party/uikit/build/outputs/lint-results-debug.html
Wrote XML report to file:///F:/chuizhicaiV3.0/third-party/uikit/build/outputs/lint-results-debug.xml
:third-party:uikit:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':third-party:uikit:lint'.
> Lint found errors in the project; aborting build.

Fix the issues identified by lint, or add the following to your build script to proceed with errors:
...
android {
    lintOptions {
        abortOnError false
    }
}
...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 5.451 secs
Lint found errors in the project; aborting build.

Fix the issues identified by lint, or add the following to your build script to proceed with errors:
...
android {
    lintOptions {
        abortOnError false
    }
}
...
11:01:45: External task execution finished 'build'.

**Comment by gzfgeh** [comment]
你解决了吗？ 和你遇到同样的问题了！
