### ISSUE TITLE
微信支付打包不行 tinker 有影响，需要改哪里

### ISSUE THREAD

**Issue by yangxp108** [Tencent/tinker#292]
![qq 20161229144315](https://cloud.githubusercontent.com/assets/6278830/21538183/3477bd2e-cdd5-11e6-8103-3d73bc492341.png)

Error:A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Cannot invoke method getAbsolutePath() on null object
   > Task with name 'tinkerPatchFreeRelease' not found in project ':app'.

**Comment by shwenzhang** [comment]
Task with name 'tinkerPatchFreeRelease' not found in project ':app'.

**Comment by yangxp108** [comment]
好的
