### ISSUE TITLE
tinker是否能够修复360加固的应用？

### ISSUE THREAD

**Issue by Aniderr** [Tencent/tinker#296]
您好，如题我想问问tinker热修复是否能够修复360加固后的包？

**Comment by yatou252303** [comment]
看说明，新版tinker不支持360加固。



279642707@qq.com
 
发件人： Aniderr
发送时间： 2017-01-03 13:58
收件人： Tencent/tinker
抄送： Subscribed
主题： [Tencent/tinker] tinker是否能够修复360加固的应用？ (#296)
您好，如题我想问问tinker热修复是否能够修复360加固后的包？

**Comment by Aniderr** [comment]
好的 谢谢
