### ISSUE TITLE
你好，我加载补丁包的时候返回码是-2，怎么回事啊

### ISSUE THREAD

**Issue by Rainorsad** [Tencent/tinker#299]
01-03 17:23:44.460 9699-9699/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:0
01-03 17:23:44.471 9699-9699/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, **code:-2**

**Comment by KgdFnYpeu** [comment]
-2 就是补丁包不存在，正常现象ShareConstants.ERROR_LOAD_PATCH_DIRECTORY_NOT_EXIST

**Comment by menmaoshan** [comment]
08-15 13:43:03.378 23218-23218/tinker.sample.android W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
08-15 13:43:42.484 23218-23218/tinker.sample.android V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@5cc6312
08-15 13:43:42.659 23218-23218/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:4690
08-15 13:43:42.666 23218-23218/tinker.sample.android I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2

这个又是怎么回事呢，明明是有这个文件的啊？ @shwenzhang

**Comment by menmaoshan** [comment]
看了文档里面说是：找不到"assets/package_meta.txt"文件，但是我打开patch文件看见里面是有的！ @shwenzhang

**Comment by lijianping1989** [comment]
找到是什么问题了吗？同样遇到这个问题，折腾了一下午还是这样

**Comment by D-Rusty** [comment]
09-22 19:06:04.566 10025-10025/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.hhly.community/tinker
09-22 19:06:04.568 10025-10025/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-22 19:06:04.571 10025-10025/? I/Tinker.SamplePatchListener: application maxMemory:192
09-22 19:06:04.573 10025-10025/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.hhly.community/tinker
09-22 19:06:04.573 10025-10025/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.0
09-22 19:06:04.574 10025-10025/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.hhly.community, main process:true, systemOTA:false, fingerPrint:google/angler/angler:7.1.2/N2G48C/4104010:user/release-keys, oatDir:null, useInterpretMode:false
09-22 19:06:04.574 10025-10025/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
09-22 19:06:04.574 10025-10025/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.hhly.community/tinker, code: -2, cost: 3ms
09-22 19:06:04.575 10025-10025/? W/Tinker.Tinker: tinker load fail!
09-22 19:06:04.594 10025-10025/? D/Tinker.DefaultAppLike: onCreate
09-22 19:06:04.922 10025-10025/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:2398
09-22 19:06:04.924 10025-10025/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
09-22 19:06:04.927 10025-10025/? I/Tinker.SamplePatchListener: get platform:null
09-22 19:06:04.928 10025-10025/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -24
09-22 19:06:05.143 10025-10025/com.hhly.community W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
09-22 19:06:04.566 10025-10025/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.hhly.community/tinker
09-22 19:06:04.568 10025-10025/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-22 19:06:04.571 10025-10025/? I/Tinker.SamplePatchListener: application maxMemory:192
09-22 19:06:04.573 10025-10025/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.hhly.community/tinker
09-22 19:06:04.573 10025-10025/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.0
09-22 19:06:04.574 10025-10025/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.hhly.community, main process:true, systemOTA:false, fingerPrint:google/angler/angler:7.1.2/N2G48C/4104010:user/release-keys, oatDir:null, useInterpretMode:false
09-22 19:06:04.574 10025-10025/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
09-22 19:06:04.574 10025-10025/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.hhly.community/tinker, code: -2, cost: 3ms
09-22 19:06:04.575 10025-10025/? W/Tinker.Tinker: tinker load fail!
09-22 19:06:04.594 10025-10025/? D/Tinker.DefaultAppLike: onCreate
09-22 19:06:04.922 10025-10025/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:2398
09-22 19:06:04.924 10025-10025/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
09-22 19:06:04.927 10025-10025/? I/Tinker.SamplePatchListener: get platform:null
09-22 19:06:04.928 10025-10025/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -24
09-22 19:06:05.143 10025-10025/com.hhly.community W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return

**Comment by AlanPanYun** [comment]
补丁包为什么不存在？outputs里面都有啊
