### ISSUE TITLE
一直报ERROR_PATCH_RUNNING错误

### ISSUE THREAD

**Issue by mwping** [Tencent/tinker#30]
09-26 17:28:49.766 9526-9526/com.test.android.app I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:5855
09-26 17:28:49.778 9526-9526/com.test.android.app I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-3, isUpgrade:true
09-26 17:29:23.842 9526-9526/com.test.android.app I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:5855
09-26 17:29:23.846 9526-9526/com.test.android.app I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-3, isUpgrade:true
09-26 17:29:49.781 9526-9526/com.test.android.app I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:5855
09-26 17:29:49.793 9526-9526/com.test.android.app I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-3, isUpgrade:true
09-26 17:30:23.847 9526-9526/com.test.android.app I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:5855
09-26 17:30:23.850 9526-9526/com.test.android.app I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-3, isUpgrade:true
看代码是

`if (TinkerServiceInternals.isTinkerPatchServiceRunning(context)) {
            return ShareConstants.ERROR_PATCH_RUNNING;
        }`

被执行，求解如何解决？是什么地方调出了问题？按照tinker Sample
来的

**Comment by shwenzhang** [comment]
先将:patch关闭
