### ISSUE TITLE
gradle task error

### ISSUE THREAD

**Issue by duzechao** [Tencent/tinker#304]
com.tencent.tinker.build.util.TinkerPatchException: loader classes are found in old secondary dex. Found classes: {Lcom/tencent/tinker/loader/shareutil/ShareResPatchInfo;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V23;,Lcom/tencent/tinker/loader/shareutil/ShareBsDiffPatchInfo;,Lcom/tencent/tinker/loader/BuildConfig;,Lcom/tencent/tinker/loader/shareutil/ShareFileLockHelper;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V14;,Lcom/tencent/tinker/loader/TinkerParallelDexOptimizer$ResultCallback;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V4;,Lcom/tencent/tinker/loader/TinkerParallelDexOptimizer;,Lcom/tencent/tinker/loader/TinkerDexLoader$1;,Lcom/tencent/tinker/loader/TinkerTestDexLoad;,Lcom/tencent/tinker/loader/TinkerSoLoader;,Lcom/tencent/tinker/loader/TinkerDexLoader;,Lcom/tencent/tinker/loader/TinkerResourcePatcher;,Lcom/tencent/tinker/loader/shareutil/ShareConstants;,Lcom/tencent/tinker/loader/AndroidNClassLoader;,Lcom/tencent/tinker/loader/TinkerResourceLoader;,Lcom/tencent/tinker/loader/shareutil/SharePatchInfo;,Lcom/tencent/tinker/loader/shareutil/ShareDexDiffPatchInfo;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder$V19;,Lcom/tencent/tinker/loader/TinkerParallelDexOptimizer$OptimizeWorker;,Lcom/tencent/tinker/loader/SystemClassLoaderAdder;,Lcom/tencent/tinker/loader/shareutil/ShareResPatchInfo$LargeModeInfo;}

**Comment by Android-Star** [comment]
我也有这个问题  都是按照demo里面做的demo可以跑但是自己的项目就有问题

**Comment by duzechao** [comment]
在gradle 中添加multiDexKeepProguard，将tinker的类加到主dex就OK了

**Comment by Android-Star** [comment]
请问怎么将tinker的loader类加到主dex，具体怎么操作的或者说主的dex在gradle的哪里，我也有这个错误而且在官方文档里面也看到了但是不知道具体怎么做，能教我么 谢谢

**Comment by duzechao** [comment]
// dex相关配置项
dex {
    dexMode = "jar" // 可选，默认为jar
    usePreGeneratedPatchDex = false // 可选，默认为false
    pattern = ["classes*.dex",
               "assets/secondary-dex-?.jar"]
    // 必选
    loader = ["com.tencent.tinker.loader.*",
              "!!!这里填你自己的Application",
    ]
}


buildTypes {
    release {
        signingConfig signingConfigs.releaseConfig
        multiDexKeepProguard file("multi.pro")
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        multiDexKeepFile file("multi.pro")//!!!要添加这个 以Proguard的方式手动加入要放到Main.dex中的类
        minifyEnabled true
        shrinkResources true
    }
}

multi.pro的内容
-keep class 你自己的Application.**{*;}
-keep class 你自己的ApplicationLike.**{*;}
-keep class com.tencent.bugly.**{*;}
-keep class com.tencent.tinker.**{*;}

**Comment by Android-Star** [comment]
谢谢  按照你的方法做了之后问题还没有解决，但是如果我把ignoreWarning设置为true，可以正常打出patch包，但是加载时候又会出问题load code-14，我看有的说在dev上已经修复这个问题了。还有一点就是根据文档说使用1.7.6版本的话这部分代码是脚本自动生成的不需要手动添加的吧

**Comment by wanglejun** [comment]
请问楼主解决这个问题了没，我也遇到同样的问题了

**Comment by menmaoshan** [comment]
楼主怎么解决的求分享
