### ISSUE TITLE
在1.7.6版本中，补丁合成成功但是加载失败，code -14

### ISSUE THREAD

**Issue by Zxhua** [Tencent/tinker#308]
W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-05 18:57:20.608 14048-14048/com.xxxx.xxx D/Tinker.TinkerInternals: same fingerprint:Meizu/meizu_m2note/m2note:5.1/LMY47D/1479149007:user/release-keys
01-05 18:57:20.609 14048-14048/com.xxxx.xxx I/PatchInfo: rewritePatchInfoFile file path:/data/data/com.xxxx.xxx/tinker/patch.info , oldVer:b609639b38d93e9c682a6bc9af750d2c, newVer:b609639b38d93e9c682a6bc9af750d2c
01-05 18:57:20.613 14048-14048/com.xxxx.xxx W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.xxxx.xxx count:1
01-05 18:57:20.640 14048-14048/com.xxxx.xxx I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxx.xxx-1/lib/arm, /vendor/lib, /system/lib]]]
01-05 18:57:20.649 14048-14048/com.xxxx.xxx I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.xxxx.xxx/tinker/patch-b609639b/dex/classes.dex.jar", zip file "/data/data/com.xxxx.xxx/tinker/patch-b609639b/dex/test.dex.jar", zip file "/data/app/com.xxxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxx.xxx-1/lib/arm, /vendor/lib, /system/lib]]], dex size:2
01-05 18:57:20.654 14048-14048/com.xxxx.xxx W/Tinker.ClassLoaderAdder: checkDexInstall result:false
01-05 18:57:20.658 14048-14048/com.xxxx.xxx E/Tinker.TinkerDexLoader: install dexes failed
01-05 18:57:20.659 14048-14048/com.xxxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
01-05 18:57:20.660 14048-14048/com.xxxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
01-05 18:57:20.661 14048-14048/com.xxxx.xxx I/MultiDex: VM with version 2.1.0 has multidex support
01-05 18:57:20.661 14048-14048/com.xxxx.xxx I/MultiDex: install
01-05 18:57:20.661 14048-14048/com.xxxx.xxx I/MultiDex: VM has multidex support, MultiDex support library is disabled.
01-05 18:57:20.664 14048-14048/com.xxxx.xxx W/Tinker.Tinker: tinker patch directory: /data/data/com.xxxx.xxx/tinker
01-05 18:57:20.666 14048-14048/com.xxxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14
01-05 18:57:20.666 14048-14048/com.xxxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:b609639b38d93e9c682a6bc9af750d2c, current:b609639b38d93e9c682a6bc9af750d2c
01-05 18:57:20.667 14048-14048/com.xxxx.xxx I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
01-05 18:57:20.667 14048-14048/com.xxxx.xxx E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
01-05 18:57:20.673 14048-14048/com.xxxx.xxx I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
01-05 18:57:20.673 14048-14048/com.xxxx.xxx E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
01-05 18:57:20.676 14048-14048/com.xxxx.xxx E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.h: Tinker Exception:checkDexInstall failed
at com.tencent.tinker.loader.c.a(SystemClassLoaderAdder.java:80)
at com.tencent.tinker.loader.d.a(TinkerDexLoader.java:147)
at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:227)
at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:171)
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:156)
at android.app.Application.attach(Application.java:181)
at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
at android.app.Instrumentation.newApplication(Instrumentation.java:992)
at android.app.LoadedApk.makeApplication(LoadedApk.java:584)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5023)
at android.app.ActivityThread.access$1500(ActivityThread.java:185)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5847)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
01-05 18:57:20.676 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/patch-b609639b.apk
01-05 18:57:20.677 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/dex/classes.dex.jar
01-05 18:57:20.678 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/dex/test.dex.jar
01-05 18:57:20.678 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/dex
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/odex/classes.dex.dex
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/odex/test.dex.dex
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b/odex
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch-b609639b
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/info.lock
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker/patch.info
01-05 18:57:20.679 14048-14048/com.xxxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxxx.xxx/tinker
01-05 18:57:20.680 14048-14048/com.xxxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.xxxx.xxx/tinker, code:-14, cost:79
01-05 18:57:20.680 14048-14048/com.xxxx.xxx W/Tinker.Tinker: tinker load fail!

**Comment by shwenzhang** [comment]
机型是？

**Comment by Zxhua** [comment]
Meizu/meizu_m2note/m2note:5.1

**Comment by Zxhua** [comment]
HUAWEI NXT-DL00 还有一个机型不记得了

**Comment by shwenzhang** [comment]
这个是在线数据，只有极少数部分机器，还是全部都有问题？

**Comment by Zxhua** [comment]
目前尝试了 三款机型 都有这个问题

**Comment by shwenzhang** [comment]
那就是你接入的问题，你看看编译的时候是否正确的传入了dex loader pattern

**Comment by Zxhua** [comment]
请问 怎么查看？谢谢。

**Comment by shwenzhang** [comment]
你在Tinker的交流群吗？你直接把tinkerpatch 下面 tempPatchedDexes发我

**Comment by D-Rusty** [comment]
Tinker的交流群 已经满员了哦，怎办，我这里遇到了，code=24
