### ISSUE TITLE
tinker在加固包上加载失败 问下应用宝需要加固才能上传 请问下微信是如何上传应用宝的

### ISSUE THREAD

**Issue by ccwls3290** [Tencent/tinker#309]
tinker在加固包上加载失败 问下应用宝需要加固才能上传  请问下微信是如何上传应用宝的

**Comment by shwenzhang** [comment]
我记得只有360是必须，应用宝是可选的吧？

**Comment by ccwls3290** [comment]
问下 第一 那如何应对某一平台的加固进行处理 ，有方向或者demo吗？  一般我们只对应用宝进行加固   因为应用宝的量是其他平台的量的总和还要多，我们还是比较看重这个的..

**Comment by zhuzhuohua** [comment]
对了  微信用了tinker  要上360应用市场必须要用360加固的  那你们怎样把微信发布上去的？？

**Comment by shwenzhang** [comment]
1. tinker 1.7.6之后不再支持加固 2. 微信不会去加固dex

**Comment by ethanhua** [comment]
嗯 我觉得这种情况很常见 希望可以提供可以支持加固后的解决方案

**Comment by BeEagle** [comment]
您好，如果那不加固，apk有被反编译的风险，微信是如何应对的？
