### ISSUE TITLE
报Error:Execution failed for task ':app:tinkerProcessDebugManifest'. > tinkerId is not set!!!错误

### ISSUE THREAD

**Issue by XieXiePro** [Tencent/tinker#31]
报Error:Execution failed for task ':app:tinkerProcessDebugManifest'. > tinkerId is not set!!!错误
![image](https://cloud.githubusercontent.com/assets/11964684/18829773/6bd22c6e-8410-11e6-87fe-1b90915adc57.png)

**Comment by shwenzhang** [comment]
#11 , 再次说明一次，以后在issue之前请先查找issue是否已经存在，包括close的

**Comment by sunEvan** [comment]
解决了么？请问怎么解决啊

**Comment by XieXiePro** [comment]
add TINKER_ID=myTINKER_ID to gradle.properties file
参考#7解决了。 @sunEvan

**Comment by shwenzhang** [comment]
@XieXiePro @sunEvan ，不能这么改，这个只是表面原因。不能直接把gitSha()的函数返回打印出来看看，这里明显就是IDE的git路径没有配置对
