### ISSUE TITLE
TinkerServiceInternals.killTinkerPatchServiceProcess空指针

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#310]
原因是am.getRunningAppProcesses()得到的结果为null
这是线上崩溃，机型Xiaomi Redmi Note 3，安卓5.0.2
这个getRunningAppProcesses()方法一般都做了兼容，不会为null，不知道什么情况会得到null

**Comment by shwenzhang** [comment]
偶现？是am == null 还是 getRunningAppProcesses 返回nukk

**Comment by balizhuang2012** [comment]
不知道是否偶现，因为是线上报的崩溃，只发现一例（一台设备，一次上报）。getRunningAppProcesses 返回null

**Comment by shwenzhang** [comment]
fixed by dev
