### ISSUE TITLE
加载补丁失败  checkDexInstall failed

### ISSUE THREAD

**Issue by hoangjian123** [Tencent/tinker#313]
**Gradle 配置**:

ext {
    // for some reason, you may want to ignore tinkerBuild, such as instant run debug build?
    tinkerEnabled = true

    // for normal build
    // old apk file to build patch apk
    tinkerOldApkPath = "${bakPath}/app-debug-0108-07-17-31.apk"
    // proguard mapping file to build patch apk
    tinkerApplyMappingPath = "${bakPath}/app-debug-1214-20-50-05-mapping.txt"
    // resource R.txt to build patch apk, must input if there is resource changed
    tinkerApplyResourcePath = "${bakPath}/app-debug-0108-07-17-31-R.txt"

    // only use for build all flavor, if not, just ignore this field
    tinkerBuildFlavorDirectory = "${bakPath}/app-0108-06-37-44"
}

def getOldApkPath() {
    return hasProperty("OLD_APK") ? OLD_APK : ext.tinkerOldApkPath
}

def getApplyMappingPath() {
    return hasProperty("APPLY_MAPPING") ? APPLY_MAPPING : ext.tinkerApplyMappingPath
}

def getApplyResourceMappingPath() {
    return hasProperty("APPLY_RESOURCE") ? APPLY_RESOURCE : ext.tinkerApplyResourcePath
}

def getTinkerIdValue() {
    return hasProperty("TINKER_ID") ? TINKER_ID : gitSha()
}

def buildWithTinker() {
    return hasProperty("TINKER_ENABLE") ? TINKER_ENABLE : ext.tinkerEnabled
}

def getTinkerBuildFlavorDirectory() {
    return ext.tinkerBuildFlavorDirectory
}

/**
 * 更多Tinker插件详细的配置，参考：https://github.com/Tencent/tinker/wiki
 */
if (buildWithTinker()) {
    apply plugin: 'com.tencent.bugly.tinker-support'
    // 依赖tinker插件
    apply plugin: 'com.tencent.tinker.patch'

    tinkerSupport {
    }

    // 全局信息相关配置项
    tinkerPatch {
        oldApk = getOldApkPath() //必选， 基准包路径

        ignoreWarning = false // 可选，默认false

        useSign = true // 可选，默认true， 验证基准apk和patch签名是否一致

        // 编译相关配置项
        buildConfig {
            applyMapping = getApplyMappingPath() //  可选，设置mapping文件，建议保持旧apk的proguard混淆方式
            applyResourceMapping = getApplyResourceMappingPath() // 可选，设置R.txt文件，通过旧apk文件保持ResId的分配
            tinkerId = "zzzzzzzzzzzzzzzzzzz" // 必选，默认为null
//            tinkerId = getTinkerIdValue()
//            tinkerId = "qqqqqqqqqqqqqqqqqqq"
        }

        // dex相关配置项
        dex {
            dexMode = "jar" // 可选，默认为jar
            usePreGeneratedPatchDex = false // 可选，默认为false
            pattern = ["classes*.dex",
                       "assets/secondary-dex-?.jar"]
//            pattern = []
            // 必选
            loader = ["com.tencent.tinker.loader.*",
                      "com.snailvr.manager.VRApplication",
            ]
        }

        // lib相关的配置项
        lib {
//            pattern=[]
            pattern = ["lib/armeabi/*.so", "lib/armeabi-v7a/*.so", "lib/x86/*.so","lib/x86_64/*.so","lib/mips/*.so","lib/mips64/*.so"]
        }

        // res相关的配置项
        res {
            pattern = ["res/*", "assets/*", "resources.arsc", "AndroidManifest.xml"]
//            ignoreChange = ["assets/sample_meta.txt"]
            largeModSize = 100
        }

        // 用于生成补丁包中的'package_meta.txt'文件
        packageConfig {
            configField("patchMessage", "tinker is sample to use")

            configField("platform", "all")

            configField("patchVersion", "1.0")
        }

        // 7zip路径配置项，执行前提是useSign为true
        sevenZip {
            zipArtifact = "com.tencent.mm:SevenZip:1.1.10" // optional
            //  path = "/usr/local/bin/7za" // optional
        }

        // 如果只用我们提供的插件，可以进行以下配置
        /* apply plugin: 'com.tencent.bugly.tinker-support'

    tinkerSupport {

        // 开启tinker-support插件，默认值true
        enable = true

        // 是否编译完成后，归档apk到指定目录，默认值false
        autoBackupApk = false
        // 指定归档目录，默认值当前module的子目录tinker
        // backupApkDir = 'tinker'

        // 是否启用覆盖tinkerPatch配置功能，默认值false
        // 开启后tinkerPatch配置不生效，即无需添加tinkerPatch
        overrideTinkerPatchConfiguration = true

        // 编译补丁包时，必需指定基线版本的apk，默认值为空
        // 如果为空，则表示不是进行补丁包的编译
        // @{link tinkerPatch.oldApk }
        baseApk = getOldApkPath()

        // 对应tinker插件applyMapping
        baseApkProguardMapping = getApplyMappingPath()

        // 对应tinker插件applyResourceMapping
        baseApkResourceMapping = getApplyResourceMappingPath()

        tinkerId = "aaaaafasdfasdfasdfasdf"
    }*/

    }
}

List<String> flavors = new ArrayList<>();
project.android.productFlavors.each { flavor ->
    flavors.add(flavor.name)
}
boolean hasFlavors = flavors.size() > 0
/**
 * bak apk and mapping
 */
android.applicationVariants.all { variant ->
    /**
     * task type, you want to bak
     */
    def taskName = variant.name
    def date = new Date().format("MMdd-HH-mm-ss")

    tasks.all {
        if ("assemble${taskName.capitalize()}".equalsIgnoreCase(it.name)) {

            it.doLast {
                copy {
                    def fileNamePrefix = "${project.name}-${variant.baseName}"
                    def newFileNamePrefix = hasFlavors ? "${fileNamePrefix}" : "${fileNamePrefix}-${date}"

                    def destPath = hasFlavors ? file("${bakPath}/${project.name}-${date}/${variant.flavorName}") : bakPath
                    from variant.outputs.outputFile
                    into destPath
                    rename { String fileName ->
                        fileName.replace("${fileNamePrefix}.apk", "${newFileNamePrefix}.apk")
                    }

                    from "${buildDir}/outputs/mapping/${variant.dirName}/mapping.txt"
                    into destPath
                    rename { String fileName ->
                        fileName.replace("mapping.txt", "${newFileNamePrefix}-mapping.txt")
                    }

                    from "${buildDir}/intermediates/symbols/${variant.dirName}/R.txt"
                    into destPath
                    rename { String fileName ->
                        fileName.replace("R.txt", "${newFileNamePrefix}-R.txt")
                    }
                }
            }
        }
    }
}
project.afterEvaluate {
    //sample use for build all flavor for one time
    if (hasFlavors) {
        task(tinkerPatchAllFlavorRelease) {
            group = 'tinker'
            def originOldPath = getTinkerBuildFlavorDirectory()
            for (String flavor : flavors) {
                def tinkerTask = tasks.getByName("tinkerPatch${flavor.capitalize()}Release")
                dependsOn tinkerTask
                def preAssembleTask = tasks.getByName("process${flavor.capitalize()}ReleaseManifest")
                preAssembleTask.doFirst {
                    String flavorName = preAssembleTask.name.substring(7, 8).toLowerCase() + preAssembleTask.name.substring(8, preAssembleTask.name.length() - 15)
                    project.tinkerPatch.oldApk = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-release.apk"
                    project.tinkerPatch.buildConfig.applyMapping = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-release-mapping.txt"
                    project.tinkerPatch.buildConfig.applyResourceMapping = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-release-R.txt"

                }

            }
        }

        task(tinkerPatchAllFlavorDebug) {
            group = 'tinker'
            def originOldPath = getTinkerBuildFlavorDirectory()
            for (String flavor : flavors) {
                def tinkerTask = tasks.getByName("tinkerPatch${flavor.capitalize()}Debug")
                dependsOn tinkerTask
                def preAssembleTask = tasks.getByName("process${flavor.capitalize()}DebugManifest")
                preAssembleTask.doFirst {
                    String flavorName = preAssembleTask.name.substring(7, 8).toLowerCase() + preAssembleTask.name.substring(8, preAssembleTask.name.length() - 13)
                    project.tinkerPatch.oldApk = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-debug.apk"
                    project.tinkerPatch.buildConfig.applyMapping = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-debug-mapping.txt"
                    project.tinkerPatch.buildConfig.applyResourceMapping = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-debug-R.txt"
                }

            }
        }
    }
}

**加载Log:**

01-08 07:42:44.741 6129-6129/com.snailvr.manager W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-08 07:42:44.741 6129-6129/com.snailvr.manager D/Tinker.TinkerInternals: same fingerprint:samsung/hero2qltezc/hero2qltechn:6.0.1/MMB29M/G9350ZCU2APK2:user/release-keys
01-08 07:42:44.751 6129-6129/com.snailvr.manager W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.snailvr.manager count:0
01-08 07:42:44.761 6129-6129/com.snailvr.manager W/Tinker.TinkerLoader: after tinker safe mode count:1
01-08 07:42:44.761 6129-6129/com.snailvr.manager I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.snailvr.manager-1/base.apk"],nativeLibraryDirectories=[/data/app/com.snailvr.manager-1/lib/arm, /data/app/com.snailvr.manager-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
01-08 07:42:44.781 6129-6129/com.snailvr.manager W/Tinker.ClassLoaderAdder: checkDexInstall result:false
01-08 07:42:44.781 6129-6129/com.snailvr.manager E/Tinker.TinkerDexLoader: install dexes failed
01-08 07:42:44.781 6129-6129/com.snailvr.manager W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
01-08 07:42:44.781 6129-6129/com.snailvr.manager D/Tinker.DefaultAppLike: onBaseContextAttached:
01-08 07:42:44.791 6129-6129/com.snailvr.manager W/Tinker.Tinker: tinker patch directory: /data/user/0/com.snailvr.manager/tinker
01-08 07:42:44.791 6129-6129/com.snailvr.manager E/Tinker.DefaultLoadReporter: tinker dex check fail:Tinker Exception:checkDexInstall failed
01-08 07:42:44.811 6129-6129/com.snailvr.manager E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
01-08 07:42:44.811 6129-6129/com.snailvr.manager E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                                   at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(BUGLY:79)
                                                                                   at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(BUGLY:137)
                                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(BUGLY:222)
                                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoad(BUGLY:56)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(BUGLY:169)
                                                                                   at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:134)
                                                                                   at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:154)
                                                                                   at android.app.Application.attach(Application.java:211)
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:1020)
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6298)
                                                                                   at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:158)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:7233)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/patch-9533b656.apk
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/dex/classes.dex.jar
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/dex/classes2.dex.jar
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/dex/test.dex.jar
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/dex
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/odex/classes.dex.dex
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/odex/test.dex.dex
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/odex/classes2.dex.dex
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/odex
01-08 07:42:44.811 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/res/resources.apk
01-08 07:42:44.841 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656/res
01-08 07:42:44.841 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch-9533b656
01-08 07:42:44.841 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/info.lock
01-08 07:42:44.841 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker/patch.info
01-08 07:42:44.841 6129-6129/com.snailvr.manager I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.snailvr.manager/tinker
01-08 07:42:44.841 6129-6129/com.snailvr.manager W/Tinker.Tinker: tinker load fail!
01-08 07:42:45.521 6129-6129/com.snailvr.manager D/Tinker.DefaultAppLike: onCreate
01-08 07:42:45.541 6129-6129/com.snailvr.manager I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@101380
01-08 07:42:47.441 6129-6129/com.snailvr.manager W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return

**Comment by shwenzhang** [comment]
如果使用了第三方的tinker扩展，先尝试使用原本的tinker再尝试
