### ISSUE TITLE
官方示例使用flavor多渠道打包生成多个补丁的问题

### ISSUE THREAD

**Issue by heweimxcz** [Tencent/tinker#315]
如果使用flavor生成多渠道，按照官方的示例
![image](https://cloud.githubusercontent.com/assets/9306631/21805349/aaf92bf2-d76e-11e6-840e-a635b917fc20.png)
这样的话所有flavor的doFirst的闭包会先执行，这样所有flavor的oldApk的值都是最后一个渠道的oldApk的路径，从而比对错误

**Comment by heweimxcz** [comment]
本来已经关联好AndResGuard和Tinker，由于不想破坏apk新的签名方式，所以仍然想按照flavor的方式来打多渠道包，结果发现这个问题

**Comment by chengfangpeng** [comment]
@heweimxcz 我也遇到了同样的问题，生成的补丁包只有最后一个渠道的能生效。

**Comment by heweimxcz** [comment]
@chengfangpeng 你使用了AndResGuard这个项目没有，我是使用这个项目然后结合tinker，在使用上面那段多个flavor的脚本在会出现各个flavor中tinker配置赋值失败，，但是如果仅仅使用tinker，上面的那段代码还是生效的，我现在的解决方案是换了打渠道的方式

**Comment by chengfangpeng** [comment]
@heweimxcz 
` task(tinkerPatchAllFlavorRelease) {
                group = 'tinker'
                def originOldPath = getTinkerBuildFlavorDirectory()
                for (String flavor : flavors) {
                    def tinkerTask = tasks.getByName("tinkerPatch${flavor.capitalize()}Release")
                    dependsOn tinkerTask
                    def preAssembleTask = tasks.getByName("process${flavor.capitalize()}ReleaseManifest")
                    preAssembleTask.doFirst {
                        String flavorName = preAssembleTask.name.substring(7, 8).toLowerCase() + preAssembleTask.name.substring(8, preAssembleTask.name.length() - 15)
                        project.tinkerPatch.oldApk = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-release.apk"
                        project.tinkerPatch.buildConfig.applyMapping = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-release-mapping.txt"
                        project.tinkerPatch.buildConfig.applyResourceMapping = "${originOldPath}/${flavorName}/${project.name}-${flavorName}-release-R.txt"

                    }

                }
            }`

上面这部分代码没大看明白，task tinkerPatchAllFlavorRelease的执行其实是把每个flavor执行了一次，任务是tinkerTask，既然tinkerTask就可以单独打出每个flavor的补丁包，为什么还要执行preAssembleTask，没看明白preAssembleTask是干什么的

**Comment by chengfangpeng** [comment]
@heweimxcz 比如我想打tencent渠道的补丁包我只需要执行tinkerPatchTencentRelease就可以了,这个任务是在tinker的插件中创建的吗？

**Comment by chengfangpeng** [comment]
@heweimxcz  我这边的问题是使用tinkerPatchAllFlavorRelease，打出的补丁包，只有最后一个补丁包生效，其余渠道的都提示基础包发生变化了，但是用命令一个渠道一个渠道的打，就没问题了。

**Comment by chengfangpeng** [comment]
@heweimxcz 跑了一下sample,是没问题的

**Comment by liangxianshen** [comment]
`oldApk:/Users/liangchi/Desktop/project/Duia_Kjb/app/build/bakApk/app-1220-19-41-41/a2/app-a2-release.apk
newApk:/Users/liangchi/Desktop/project/Duia_Kjb/app/build/outputs/apk/app-a1-release.apk`

**Comment by victorfan336** [comment]
> @heweimxcz 我这边的问题是使用tinkerPatchAllFlavorRelease，打出的补丁包，只有最后一个补丁包生效，其余渠道的都提示基础包发生变化了，但是用命令一个渠道一个渠道的打，就没问题了。

你好，我想请问下，我用的1.9.11版本的tinker，为什么没有这个tinkerPatchAllFlavorRelease命令，谢谢了
