### ISSUE TITLE
使用tinkerPatch生成补丁包，log显示都是成功的，加载也是成功，但关屏后再也打不开了

### ISSUE THREAD

**Issue by Rock610** [Tencent/tinker#317]
手机是一加1代 android 7.1

以下是加载log:

01-12 15:56:29.719 21533-21533/com.wdwd.wfx W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-12 15:56:29.719 21533-21533/com.wdwd.wfx D/Tinker.TinkerInternals: same fingerprint:oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys
01-12 15:56:29.725 21533-21533/com.wdwd.wfx W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.wdwd.wfx count:1
01-12 15:56:29.736 21533-21533/com.wdwd.wfx I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wdwd.wfx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wdwd.wfx-1/lib/arm, /system/fake-libs, /data/app/com.wdwd.wfx-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]]
01-12 15:56:29.766 21533-21533/com.wdwd.wfx I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.wdwd.wfx/tinker/patch-7f9f191f/dex/classes.dex.jar", zip file "/data/user/0/com.wdwd.wfx/tinker/patch-7f9f191f/dex/classes2.dex.jar", zip file "/data/user/0/com.wdwd.wfx/tinker/patch-7f9f191f/dex/test.dex.jar", zip file "/data/app/com.wdwd.wfx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wdwd.wfx-1/lib/arm, /system/fake-libs, /data/app/com.wdwd.wfx-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]], dex size:3
01-12 15:56:29.767 21533-21533/com.wdwd.wfx W/Tinker.ClassLoaderAdder: checkDexInstall result:true
01-12 15:56:29.767 21533-21533/com.wdwd.wfx I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
01-12 15:56:29.773 21533-21533/com.wdwd.wfx D/Tinker.DefaultAppLike: onBaseContextAttached:
01-12 15:56:29.779 21533-21533/com.wdwd.wfx I/Tinker.ReflectApp: with app application from manifest applicationName:com.wdwd.wfx.application.ShopexApplication
01-12 15:56:29.792 21533-21533/com.wdwd.wfx I/Tinker.ServerUtils: with app key from manifest appKey:e2779049e87cf4af
01-12 15:56:29.794 21533-21533/com.wdwd.wfx I/Tinker.ServerUtils: with app version from manifest appVersion:2.7.3
01-12 15:56:29.796 21533-21533/com.wdwd.wfx I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.wdwd.wfx/tinker_server/version.info, appVersion: 2.7.3, uuid:dbe2b0fa-1d12-4fb8-8210-eb3b44e0fce3, abi:armeabi-v7a, patchVersion:0, patchMd5:, grayValue:3, crashTimes:0, retryTimes:0
01-12 15:56:29.802 21533-21533/com.wdwd.wfx E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
01-12 15:56:29.802 21533-21533/com.wdwd.wfx W/Tinker.Debugger: debugger not attached cu == null
01-12 15:56:29.803 21533-21533/com.wdwd.wfx W/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 2.7.3, appKey: e2779049e87cf4af
01-12 15:56:29.812 21533-21533/com.wdwd.wfx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.wdwd.wfx/tinker
01-12 15:56:29.820 21533-21533/com.wdwd.wfx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
01-12 15:56:29.820 21533-21533/com.wdwd.wfx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:7f9f191f196853e3520245490d693a30, newVersion:7f9f191f196853e3520245490d693a30, current:7f9f191f196853e3520245490d693a30
01-12 15:56:29.821 21533-21533/com.wdwd.wfx I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
01-12 15:56:29.821 21533-21533/com.wdwd.wfx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.wdwd.wfx/tinker, code:0, cost:114
01-12 15:56:29.824 21533-21533/com.wdwd.wfx D/Tinker.DefaultAppLike: onCreate

到这就崩了,然后无限跳这些Log,app在无限自启

**Comment by shwenzhang** [comment]
这个是tinkerpatch一键接入引入的bug,将在明天修复
