### ISSUE TITLE
can't find AppVersion

### ISSUE THREAD

**Issue by 1019272778** [Tencent/tinker#323]
各位大神求助，引入tinker后工程编译时
Error:Execution failed for task ':app:processDefaultConfigDebugManifest'.
> Can't find AppVersion in your config, is there match variantName in tinkerpatchSupport config??

tinker version 1.1.0

tinkerpatchSupport {
    /** 可以在debug的时候关闭 tinkerPatch **/
    tinkerEnable = true
    reflectApplication = true
    appKey = "1782400ad784c933"
    autoBackupApkPath = "${bakPath}"

    baseApkInfos {
        item {
            variantName = "debug"
            appVersion = "1.0.0"

            def pathPrefix = "${bakPath}/${baseInfo}/${variantName}/"
            def name = "${project.name}-${variantName}"
            baseApkFile = "${pathPrefix}/${name}.apk"
            baseProguardMappingFile = "${pathPrefix}/${name}-mapping.txt"
            baseResourceRFile = "${pathPrefix}/${name}-R.txt"
        }
        item {
            variantName = "release"
            appVersion = "1.0.0"

            def pathPrefix = "${bakPath}/${baseInfo}/${variantName}/"
            def name = "${project.name}-${variantName}"
            baseApkFile = "${pathPrefix}/${name}.apk"
            baseProguardMappingFile = "${pathPrefix}/${name}-mapping.txt"
            baseResourceRFile = "${pathPrefix}/${name}-R.txt"
        }
    }
}

**Comment by weinierfei** [comment]
这个是TinkerPatch的用法问题,你应该到https://github.com/TinkerPatch/tinkerpatch-sdk反馈或寻找答案

**Comment by weinierfei** [comment]
这个是TinkerPatch的用法问题,你应该到https://github.com/TinkerPatch/tinkerpatch-sdk 反馈或寻找答案

**Comment by 1019272778** [comment]
页面找不到

**Comment by 1019272778** [comment]
谢谢，不过目前有什么解决办法吗？

**Comment by weinierfei** [comment]
没用过,不知道

**Comment by shwenzhang** [comment]
@1019272778 更新到1.1.1版本，查看最新的版本
