### ISSUE TITLE
Android 5.0/5.1机型上OAT文件损坏

### ISSUE THREAD

**Issue by guoguo338** [Tencent/tinker#328]
5.0/5.1上会有千分之二的用户发生OAT文件损坏的问题。

崩溃栈如下，
#1286 unknown
SIGSEGV(SEGV_ACCERR)

1 #00 pc 00000000 /data/data/com.mogujie/tinker/patch-c303cfcd/odex/classes2.dex.dex [armeabi]
2 #01 pc 00024f8f /data/data/com.mogujie/tinker/patch-c303cfcd/odex/classes3.dex.dex (oatdata+147343) [armeabi]

从oatdump看起来，是OAT文件损坏了。如下，从oatdump看起来，code_offset不为0，但是却没有native code。
    QuickMethodFrameInfo
      frame_size_in_bytes: 32
      core_spill_mask: 0x00008060 (r5, r6, r15)
      fp_spill_mask: 0x00000000
    CODE: (code_offset=0x00a87019 size_offset=0x00a87014 size=64)...

**Comment by jackniuTencent** [comment]
腾讯浏览服务这里也碰到了这个问题，目前是采用侦测删除的办法解决的。根本原因由于无法复现损坏场景且看起来是系统底层bug没能追查清楚。QQ浏览器：jackniu

**Comment by shwenzhang** [comment]
下个版本将增加elf文件格式检测

**Comment by shwenzhang** [comment]
try with tinker 1.7.8
