### ISSUE TITLE
三星S4 SHV-E330K Android:5.01 测试失败

### ISSUE THREAD

**Issue by Qiu800820** [Tencent/tinker#33]
Load patch日志:
09-26 17:51:16.399 19944-19951/tinker.sample.android I/art: Debugger is no longer active
09-26 17:51:20.609 19944-19951/tinker.sample.android I/art: Debugger is no longer active
09-26 17:50:25.409 19944-19951/tinker.sample.android I/art: Debugger is no longer active
09-26 17:50:43.929 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onCreate classloader:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm, /vendor/lib, /system/lib]]]
09-26 17:50:43.929 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onCreate string:I am in the base apk
09-26 17:50:43.929 19944-19944/tinker.sample.android D/Activity: performCreate Call secproduct feature valuefalse
09-26 17:50:43.929 19944-19944/tinker.sample.android D/Activity: performCreate Call debug elastic valuetrue
09-26 17:50:43.929 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onResume
09-26 17:50:44.019 19944-19944/tinker.sample.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@63c9da2 time:704055
09-26 17:50:49.879 19944-19944/tinker.sample.android V/ActivityThread: updateVisibility : ActivityRecord{29de7d1c token=android.os.BinderProxy@63c9da2 {tinker.sample.android/tinker.sample.android.app.MainActivity}} show : false
09-26 17:50:49.899 19944-19944/tinker.sample.android D/Tinker.DefaultAppLike: onTrimMemory level:20
09-26 17:51:16.399 19944-19951/tinker.sample.android I/art: Debugger is no longer active
09-26 17:51:20.609 19944-19951/tinker.sample.android I/art: Debugger is no longer active
09-26 17:51:28.579 19944-19951/tinker.sample.android I/art: Debugger is no longer active
09-26 17:52:03.709 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onResume
09-26 17:52:03.779 19944-19944/tinker.sample.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@63c9da2 time:783815
09-26 17:52:06.109 19944-19944/tinker.sample.android D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
09-26 17:52:06.129 19944-19944/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:133685
09-26 17:52:06.159 19944-19944/tinker.sample.android I/Tinker.SamplePatchListener: get platform:all
09-26 17:52:08.679 19944-23960/tinker.sample.android I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                                   PatchResult: 
                                                                                   isUpgradePatch:true
                                                                                   isSuccess:true
                                                                                   rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                                   costTime:2280
                                                                                   patchVersion:fa92bf3c68b862fb10c1782efb0de761
                                                                                   patchTinkerID:a22a4da
                                                                                   baseTinkerID:a22a4da
                                                                                   Throwable: null
09-26 17:52:08.689 19944-23960/tinker.sample.android I/Process: Sending signal. PID: 23885 SIG: 9
09-26 17:52:08.689 19944-23960/tinker.sample.android I/Tinker.SampleResultService: save delete raw patch file
09-26 17:52:08.689 19944-23960/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/patch_signed_7zip.apk
09-26 17:52:08.689 19944-23960/tinker.sample.android I/Tinker.SampleResultService: tinker wait screen to restart process
09-26 17:52:43.679 19944-19944/tinker.sample.android D/Tinker.DefaultAppLike: onTrimMemory level:20
09-26 17:52:46.889 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onCreate classloader:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm, /vendor/lib, /system/lib]]]
09-26 17:52:46.889 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onCreate string:I am in the base apk
09-26 17:52:46.889 19944-19944/tinker.sample.android D/Activity: performCreate Call secproduct feature valuefalse
09-26 17:52:46.889 19944-19944/tinker.sample.android D/Activity: performCreate Call debug elastic valuetrue
09-26 17:52:46.889 19944-19944/tinker.sample.android E/Tinker.MainActivity: i am on onResume
09-26 17:52:46.949 19944-19944/tinker.sample.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1fae0212 time:826986
09-26 17:52:50.099 19944-19944/tinker.sample.android D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
09-26 17:52:50.149 19944-19944/tinker.sample.android I/Process: Sending signal. PID: 19944 SIG: 9

---------------------------------------------分割线------------------------------------
kill 重新启动后日志:
09-26 17:52:51.289 25202-25202/? E/Zygote: MountEmulatedStorage()
09-26 17:52:51.289 25202-25202/? E/Zygote: v2
09-26 17:52:51.289 25202-25202/? I/libpersona: KNOX_SDCARD checking this for 10856
09-26 17:52:51.289 25202-25202/? I/libpersona: KNOX_SDCARD not a persona
09-26 17:52:51.289 25202-25202/? I/SELinux: Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SHV-E330K_5.0.1_0017
09-26 17:52:51.289 25202-25202/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
09-26 17:52:51.289 25202-25202/? I/art: Late-enabling -Xcheck:jni
09-26 17:52:51.359 25202-25202/tinker.sample.android D/ResourcesManager: creating new AssetManager and set to /data/app/tinker.sample.android-1/base.apk
09-26 17:52:51.509 25202-25202/tinker.sample.android W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
09-26 17:52:51.509 25202-25202/tinker.sample.android I/PatchInfo: rewritePatchInfoFile file path:/data/data/tinker.sample.android/tinker/patch.info , oldVer:fa92bf3c68b862fb10c1782efb0de761, newVer:fa92bf3c68b862fb10c1782efb0de761
09-26 17:52:51.519 25202-25202/tinker.sample.android W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_tinker.sample.android count:0
09-26 17:52:51.559 25202-25202/tinker.sample.android W/Tinker.TinkerLoader: after tinker safe mode count:1
09-26 17:52:51.559 25202-25202/tinker.sample.android I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm, /vendor/lib, /system/lib]]]
09-26 17:52:51.569 25202-25202/tinker.sample.android W/Tinker.ClassLoaderAdder: checkDexInstall result:false
09-26 17:52:51.569 25202-25202/tinker.sample.android E/Tinker.TinkerDexLoader: install dexes failed
09-26 17:52:51.569 25202-25202/tinker.sample.android W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
09-26 17:52:51.569 25202-25202/tinker.sample.android D/Tinker.DefaultAppLike: onBaseContextAttached:
09-26 17:52:51.569 25202-25202/tinker.sample.android I/MultiDex: VM with version 2.1.0 has multidex support
09-26 17:52:51.569 25202-25202/tinker.sample.android I/MultiDex: install
09-26 17:52:51.569 25202-25202/tinker.sample.android I/MultiDex: VM has multidex support, MultiDex support library is disabled.
09-26 17:52:51.569 25202-25202/tinker.sample.android I/Tinker.SamplePatchListener: application maxMemory:128
09-26 17:52:51.569 25202-25202/tinker.sample.android W/Tinker.Tinker: tinker patch directory: /data/data/tinker.sample.android/tinker
09-26 17:52:51.569 25202-25202/tinker.sample.android I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-15
09-26 17:52:51.569 25202-25202/tinker.sample.android I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:fa92bf3c68b862fb10c1782efb0de761, current:fa92bf3c68b862fb10c1782efb0de761
09-26 17:52:51.569 25202-25202/tinker.sample.android I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-15
09-26 17:52:51.569 25202-25202/tinker.sample.android E/Tinker.DefaultLoadReporter: tinker dex check fail:Tinker Exception:checkDexInstall failed
09-26 17:52:51.599 25202-25202/tinker.sample.android I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
09-26 17:52:51.629 25202-25202/tinker.sample.android E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                                       at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:74)
                                                                                       at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:107)
                                                                                       at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:218)
                                                                                       at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:169)
                                                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134)
                                                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
                                                                                       at android.app.Application.attach(Application.java:205)
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                                                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:620)
                                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5086)
                                                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:177)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/patch-fa92bf3c.apk
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/dex/classes.dex.jar
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/dex/test.dex.jar
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/dex
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/odex/classes.dex.dex
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/odex/test.dex.dex
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/odex
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/res/resources.apk
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c/res
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch-fa92bf3c
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/info.lock
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker/patch.info
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/tinker.sample.android/tinker
09-26 17:52:51.629 25202-25202/tinker.sample.android I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/tinker.sample.android/tinker, code:-15, cost:154
09-26 17:52:51.629 25202-25202/tinker.sample.android W/Tinker.Tinker: tinker load fail!
09-26 17:52:51.689 25202-25202/tinker.sample.android D/Tinker.DefaultAppLike: onCreate
09-26 17:52:51.799 25202-25202/tinker.sample.android E/Tinker.MainActivity: i am on onCreate classloader:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/tinker.sample.android/tinker/patch-fa92bf3c/dex/classes.dex.jar", zip file "/data/data/tinker.sample.android/tinker/patch-fa92bf3c/dex/test.dex.jar", zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm, /vendor/lib, /system/lib]]]
09-26 17:52:51.799 25202-25202/tinker.sample.android E/Tinker.MainActivity: i am on onCreate string:I am in the base apk
09-26 17:52:51.799 25202-25202/tinker.sample.android D/Activity: performCreate Call secproduct feature valuefalse
09-26 17:52:51.799 25202-25202/tinker.sample.android D/Activity: performCreate Call debug elastic valuetrue
09-26 17:52:51.799 25202-25202/tinker.sample.android E/Tinker.MainActivity: i am on onResume
09-26 17:52:51.819 25202-25235/tinker.sample.android D/OpenGLRenderer: Render dirty regions requested: true
09-26 17:52:51.889 25202-25235/tinker.sample.android I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
                                                                   OpenGL ES Shader Compiler Version: E031.25.01.03
                                                                   Build Date: 01/08/15 Thu
                                                                   Local Branch: LA.BF.1.1_RB1_20150108_025_1077123
                                                                   Remote Branch: 
                                                                   Local Patches: 
                                                                   Reconstruct Branch: 
09-26 17:52:51.899 25202-25235/tinker.sample.android I/OpenGLRenderer: Initialized EGL, version 1.4
09-26 17:52:51.929 25202-25235/tinker.sample.android D/OpenGLRenderer: Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
09-26 17:52:51.929 25202-25235/tinker.sample.android D/OpenGLRenderer: Enabling debug mode 0
09-26 17:52:52.039 25202-25202/tinker.sample.android W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
09-26 17:52:52.039 25202-25202/tinker.sample.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@390df7de time:832072

**Comment by shwenzhang** [comment]
这个是已经问题，对于部分三星android-19机器是不支持的。

**Comment by adhere534** [comment]
我发现我的patch.info没有生成
tryLoadPatchFiles:patch info not exist:/data/data/tinker.sample.android/tinker/patch.info

patchVersion:null
patchTinkerID:null
baseTinkerID:null
Throwable: null
这几个空的 是什么情况？

**Comment by shwenzhang** [comment]
不是没有生成，只是还没到读的时候，已经返回失败了。还是先仔细看文档
