### ISSUE TITLE
三星S7热更新失败，请帮忙查一下原因，谢谢

### ISSUE THREAD

**Issue by starchen84** [Tencent/tinker#331]
01-18 14:37:53.474 24205-24205/com.videogo W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.videogo/tinker
01-18 14:37:53.474 24205-24205/com.videogo D/Tinker.DefaultAppLike: onBaseContextAttached:
01-18 14:37:53.494 24205-24205/com.videogo I/Tinker.SamplePatchListener: application maxMemory:256
01-18 14:37:53.494 24205-24205/com.videogo W/Tinker.Tinker: tinker patch directory: /data/user/0/com.videogo/tinker
01-18 14:37:53.494 24205-24205/com.videogo I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
01-18 14:37:53.494 24205-24205/com.videogo I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
01-18 14:37:53.494 24205-24205/com.videogo W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
01-18 14:37:53.494 24205-24205/com.videogo I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.videogo/tinker, code:-2, cost:2
01-18 14:37:53.494 24205-24205/com.videogo W/Tinker.Tinker: tinker load fail!
01-18 14:37:53.494 24205-24205/com.videogo D/Tinker.DefaultAppLike: onCreate
01-18 14:37:53.644 24205-24205/com.videogo I/Tinker.LoadLibrary: tinker is not loaded, just return
01-18 14:37:55.134 24205-24205/com.videogo I/PatchWorker: siteUrl:https://test5.ys7.com/assets/deps/patches/3.5.2.0118/patch.txt
01-18 14:37:55.184 24205-24388/com.videogo I/PatchWorker: PatchSpec:{"appVersion":"3.5.2.0118","hc":"","kill":0,"model":"","os":"","patchContent":"","patchMd5":"8bcff757ff99b425e66c76eb4c731c3f","patchName":"VideoGo-debug-logging-v3.5.2_133109_patch","patchSize":0,"patchTime":"","patchUrl":"http://test5.ys7.com/assets/deps/patches/3.5.2.0118/VideoGo-debug-logging-v3.5.2_133109_patch.apk","patchVersion":"1.0","phone":"","updateType":0}
01-18 14:37:55.184 24205-24388/com.videogo D/PatchWorker: checkOldPatchSpec:null
01-18 14:37:55.244 24205-24205/com.videogo I/InjectionManager: dispatchOnViewCreated > Target : com.videogo.main.MainTabActivity isFragment :false
01-18 14:37:55.314 24205-24205/com.videogo I/InjectionManager: dispatchOnViewCreated > Target : com.videogo.login.freelogin.FreeLoginActivity isFragment :false
01-18 14:37:55.694 24205-24205/com.videogo W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
01-18 14:37:57.154 24205-24388/com.videogo D/PatchWorker: checkUserSpec start
01-18 14:37:57.154 24205-24388/com.videogo D/PatchWorker: checkUserSpec success
01-18 14:38:06.354 24205-24388/com.videogo I/PatchWorker: start download VideoGo-debug-logging-v3.5.2_133109_patch from http://test5.ys7.com/assets/deps/patches/3.5.2.0118/VideoGo-debug-logging-v3.5.2_133109_patch.apk
01-18 14:38:06.864 24205-24388/com.videogo I/PatchWorker: VideoGo-debug-logging-v3.5.2_133109_patch (48429 bytes) finished in 508ms
01-18 14:38:19.594 24205-24388/com.videogo I/Tinker.SamplePatchListener: receive a patch file: /data/user/0/com.videogo/files/patches/VideoGo-debug-logging-v3.5.2_133109_patch/8bcff757ff99b425e66c76eb4c731c3f.apk, file size:48429
01-18 14:38:19.624 24205-24388/com.videogo W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
01-18 14:38:19.634 24205-24388/com.videogo I/Tinker.SamplePatchListener: get platform:all
01-18 14:38:19.674 24205-24388/com.videogo I/PatchWorker: patch.xml updated to 1.0
01-18 14:38:19.724 25220-25220/com.videogo:patch D/TimaKeyStoreProvider: TimaSignature is unavailable
01-18 14:38:19.724 25220-25220/com.videogo:patch D/ActivityThread: Added TimaKeyStore provider
01-18 14:38:19.754 25220-25220/com.videogo:patch D/ContextRelationManager: ContextRelationManager() : FEATURE_ENABLED=true
01-18 14:38:19.754 25220-25220/com.videogo:patch D/RelationGraph: garbageCollect()
01-18 14:38:19.754 25220-25220/com.videogo:patch W/ResourcesManager: getTopLevelResources: /data/app/com.videogo-1/base.apk / 1.0 running in com.videogo rsrc of package com.videogo
01-18 14:38:19.754 25220-25220/com.videogo:patch I/InjectionManager: Inside getClassLibPath + mLibMap{0=, 1=}
01-18 14:38:19.764 25220-25220/com.videogo:patch D/ResourcesManager: For user 0 new overlays fetched Null
01-18 14:38:19.764 25220-25220/com.videogo:patch I/InjectionManager: Inside getClassLibPath caller 
01-18 14:38:19.784 25220-25220/com.videogo:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.videogo/tinker
01-18 14:38:19.784 25220-25220/com.videogo:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
01-18 14:38:19.794 25220-25220/com.videogo:patch I/MultiDex: VM with version 2.1.0 has multidex support
01-18 14:38:19.794 25220-25220/com.videogo:patch I/MultiDex: install
01-18 14:38:19.794 25220-25220/com.videogo:patch I/MultiDex: VM has multidex support, MultiDex support library is disabled.
01-18 14:38:19.794 25220-25220/com.videogo:patch I/Tinker.SamplePatchListener: application maxMemory:256
01-18 14:38:19.804 25220-25220/com.videogo:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.videogo/tinker
01-18 14:38:19.804 25220-25220/com.videogo:patch I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
01-18 14:38:19.804 25220-25220/com.videogo:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
01-18 14:38:19.804 25220-25220/com.videogo:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
01-18 14:38:19.804 25220-25220/com.videogo:patch I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.videogo/tinker, code:-2, cost:3
01-18 14:38:19.804 25220-25220/com.videogo:patch W/Tinker.Tinker: tinker load fail!
01-18 14:38:19.804 25220-25220/com.videogo:patch D/Tinker.DefaultAppLike: onCreate
01-18 14:38:19.824 25220-25220/com.videogo:patch D/Utils: isMainProcess packageName:com.videogo, processName:com.videogo:patch
01-18 14:38:19.824 25220-25220/com.videogo:patch D/InjectionManager: InjectionManager
01-18 14:38:19.824 25220-25220/com.videogo:patch D/InjectionManager: fillFeatureStoreMap com.videogo
01-18 14:38:19.834 25220-25220/com.videogo:patch I/InjectionManager: Constructor com.videogo, Feature store :{}
01-18 14:38:19.834 25220-25220/com.videogo:patch I/InjectionManager: featureStore :{}
01-18 14:38:19.834 25220-25220/com.videogo:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
01-18 14:38:19.834 25220-25235/com.videogo:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
01-18 14:38:19.834 25220-25235/com.videogo:patch W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.videogo/files/patches/VideoGo-debug-logging-v3.5.2_133109_patch/8bcff757ff99b425e66c76eb4c731c3f.apk to /data/user/0/com.videogo/tinker_temp/temp.apk
01-18 14:38:19.844 25220-25235/com.videogo:patch I/Tinker.TinkerPatchService: try to increase patch process priority
01-18 14:38:19.914 25220-25235/com.videogo:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:8bcff757ff99b425e66c76eb4c731c3f
01-18 14:38:19.914 25220-25235/com.videogo:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.videogo/tinker/patch-8bcff757
01-18 14:38:19.924 25220-25235/com.videogo:patch W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.videogo/files/patches/VideoGo-debug-logging-v3.5.2_133109_patch/8bcff757ff99b425e66c76eb4c731c3f.apk size: 48429, dest file: /data/user/0/com.videogo/tinker/patch-8bcff757/patch-8bcff757.apk size:48429
01-18 14:38:19.944 25220-25235/com.videogo:patch E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 3842511583, got crc: 4116891567
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchTypeExtractFail: file extract fail type:dex, path:/data/user/0/com.videogo/tinker/patch-8bcff757/patch-8bcff757.apk, extractTo:/data/user/0/com.videogo/tinker/patch-8bcff757/dex/classes.dex.jar, filename:classes.dex
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.videogo/tinker/patch-8bcff757/patch-8bcff757.apk
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.videogo/tinker/patch-8bcff757/dex
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.videogo/tinker/patch-8bcff757
01-18 14:38:19.944 25220-25235/com.videogo:patch W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:20
01-18 14:38:19.944 25220-25235/com.videogo:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/data/user/0/com.videogo/files/patches/VideoGo-debug-logging-v3.5.2_133109_patch/8bcff757ff99b425e66c76eb4c731c3f.apk, success:false, cost:102
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.SampleTinkerReport: hp_report report apply cost = 102
01-18 14:38:19.944 25220-25235/com.videogo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.videogo/tinker_temp/temp.apk
01-18 14:38:19.964 24205-25241/com.videogo I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                         PatchResult: 
                                                                         isSuccess:false
                                                                         rawPatchFilePath:/data/user/0/com.videogo/files/patches/VideoGo-debug-logging-v3.5.2_133109_patch/8bcff757ff99b425e66c76eb4c731c3f.apk
                                                                         costTime:102
                                                                         patchVersion:8bcff757ff99b425e66c76eb4c731c3f
01-18 14:38:19.984 24205-25246/com.videogo D/OkHttp: sessionId=&clientType=3&osVersion=6.0.1&clientVersion=3.5.2.0118&netType=WIFI&clientNo=web_site&systemName=app_android_load_patch&v=3.5.2.0118&did=00744534b22560b2bbd0ce7955369bbc&uid=&pr=false&ct=102&pv=8bcff757ff99b425e66c76eb4c731c3f&key=3&msg=

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/22093450/b61f75f8-de40-11e6-95db-fc01ff63b9c5.png)
请查看文档，基准包不一致
