### ISSUE TITLE
集成tinker的新版和旧版app问题

### ISSUE THREAD

**Issue by JocherCH** [Tencent/tinker#335]
旧版app：v1
集成tinker app：v2
问题描述：旧版app的打包逻辑和tinker的打包逻辑有差异，导致旧版生成的缓存内容影响到v2版本改动内容无效。
如修改layout.xml中TextView的内容，由于旧版缓存存在，当我更新到v2版本后，显示的内容还是v1版本内容，求解

**Comment by shwenzhang** [comment]
see wiki, tinker id
