### ISSUE TITLE
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed

### ISSUE THREAD

**Issue by springtom** [Tencent/tinker#337]
HUAWEI HW-01E（4.1.2） 集成tinker后，启动报此错误。其他机型没问题

**Comment by shwenzhang** [comment]
详细的日志，请参考常见问题的提问须知

**Comment by gdky005** [comment]
我也遇到了这个问题，让我百思不得其解，连续三天了，没一点眉目，试过各种方法，就是不行。最后同事那边有突破了，原来这个问题并不是 tinker 的问题，而是在分包的时候，这个类依赖的类，没有被打到主 dex 里面，所以要排查 这个类 继承的类，还有实现的类，是否都在主 dex 里面。

具体问题错误原因是： 找不到依赖的类，所以无法初始化该类，抛出了找不到类异常。

其实你的错误根本原因是找不到 对应的 自定义 Application。 而你自定义的 Application 又继承 和依赖了 其他的类，这些类没有被你放到主 dex 里面，所以提示这个错误。

总结就是：遇到找不到类的错误，不一定是 真的找不到这个类（大多数是这个），也可能是这个类依赖的类找不到。 

我的问题就是，CallBack 没有在主 Dex 里面。
![image](https://user-images.githubusercontent.com/3477872/37751449-90ed7c16-2dcd-11e8-8378-8878f0428923.png)
