### ISSUE TITLE
sync 报错

### ISSUE THREAD

**Issue by littleQia** [Tencent/tinker#34]
由于代码命名不规范 导致color以及dimen命名里面有black_0.4_bg 之类的命名，貌似tinker有对这方面的检测，导致一直报错。

E:\...\app\build\intermediates\res\merged\_360\debug\values\public.xml
Error:(929) Public symbol dimen/common_font_sw320dp_of_10_5 declared here is not defined.
Error:(1023) Public symbol dimen/common_sw320dp_of_0_5 declared here is not defined.
Error:(1007) Public symbol dimen/common_sw320dp_of_12_5 declared here is not defined.
Error:(978) Public symbol dimen/common_sw320dp_of_1_5 declared here is not defined.
Error:(1080) Public symbol dimen/common_sw320dp_of_2_5 declared here is not defined.
Error:(950) Public symbol dimen/common_sw320dp_of_63_5 declared here is not defined.
Error:Execution failed for task ':app:process_360DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\AndroidStudio\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by shwenzhang** [comment]
#18, ps issue需要描述详细的原因。

**Comment by shwenzhang** [comment]
try with 1.6.1
