### ISSUE TITLE
Tinker 1.7.8功能规划

### ISSUE THREAD

**Issue by shwenzhang** [Tencent/tinker#340]
大约3月17日发布1.7.8版本，主要修改点如下：
1. fix 已知问题 (issue #374 #328 #348 )
2. 支持加固标准方案
3. OTA之后增加等待提示界面
4. 判断 art 7.0之前的JIT过滤
5. 多线程dexoat 线程数限定

delay的原因主要是跟各大加固厂商联系/调试，争取tinker可以支持市面所有的主流加固厂商

**Comment by DengAnbang** [comment]
请问1.7.8版本还要好久发布？想看看加固方面的..

**Comment by chenenyu** [comment]
mark

**Comment by jimdear** [comment]
希望加固方支持爱加密

**Comment by jp1017** [comment]
可以,很强势, 可以先来个,没必要所有加固都一次搞掂, Here we go. :smile:

**Comment by czy1121** [comment]
求支持360加固

**Comment by alexhuahua** [comment]
1.7.8什么时候能出来啊？已经等了很久了

**Comment by zhangdunliang** [comment]
这个新版本有具体的上线时间吗？等了很久

**Comment by kongnanlive** [comment]
long long ago

**Comment by shwenzhang** [comment]
已发布
