### ISSUE TITLE
Tinker Exception:ShareSecurityCheck verifyPatchMetaSignature fail

### ISSUE THREAD

**Issue by biyeshengplay** [Tencent/tinker#341]
将生成的补丁文件patch_signed_7zip.apk原样上传，补丁成功。将补丁文件patch_signed_7zip.apk去掉后缀.apk上传，打补丁报错

02-07 18:37:35.545 D/Tinker.DefaultAppLike( 6390): onCreate
02-07 18:37:35.588 I/Tinker.DefaultPatchReporter( 6390): patchReporter: patch service start
02-07 18:37:35.591 D/Tinker.DefaultAppLike( 6390): onTrimMemory level:80
02-07 18:37:35.602 I/Tinker.TinkerPatchService( 6390): try to increase patch process priority
02-07 18:37:35.603 V/ActivityManager( 3502): Attempted to start a foreground service (ComponentInfo{com.wm.dmall/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
02-07 18:37:35.611 V/ActivityManager( 3502): Attempted to start a foreground service (ComponentInfo{com.wm.dmall/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
02-07 18:37:35.616 I/Tinker.DefaultPatchReporter( 6390): patchReporter: patch exception path:/storage/emulated/0/com.wm.dmall/tinkerpatch/1486463855210.apatch, throwable:Tinker Exception:ShareSecurityCheck file /storage/emulated/0/com.wm.dmall/tinkerpatch/1486463855210.apatch, size 33195 verifyPatchMetaSignature fail, isUpgrade:true
02-07 18:37:35.616 E/Tinker.DefaultPatchReporter( 6390): tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file /storage/emulated/0/com.wm.dmall/tinkerpatch/1486463855210.apatch, size 33195 verifyPatchMetaSignature fail
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:139)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:104)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:89)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at android.os.Looper.loop(Looper.java:150)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): Caused by: java.util.zip.ZipException: Central Directory Entry signature not found; was 9FA89658
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.zip.ZipFile.throwZipException(ZipFile.java:498)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.zip.ZipEntry.<init>(ZipEntry.java:390)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.zip.ZipFile.readCentralDir(ZipFile.java:445)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.zip.ZipFile.<init>(ZipFile.java:175)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.jar.JarFile.<init>(JarFile.java:199)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.jar.JarFile.<init>(JarFile.java:182)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at java.util.jar.JarFile.<init>(JarFile.java:168)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:110)
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): 	... 8 more
02-07 18:37:35.618 I/Tinker.DefaultPatchReporter( 6390): patchReporter: patch all result path:/storage/emulated/0/com.wm.dmall/tinkerpatch/1486463855210.apatch, success:false, cost:16, isUpgrade:true
02-07 18:37:35.618 I/Tinker.PatchFileUtil( 6390): safeDeleteFile, try to delete path: /data/user/0/com.wm.dmall/tinker/patch.retry
02-07 18:37:35.619 I/Tinker.PatchFileUtil( 6390): safeDeleteFile, try to delete path: /data/user/0/com.wm.dmall/tinker/temp.apk

**Comment by shwenzhang** [comment]
02-07 18:37:35.617 E/Tinker.DefaultPatchReporter( 6390): Caused by: java.util.zip.ZipException: Central Directory Entry signature not found; was 9FA89658

不是完整的zip包？
