### ISSUE TITLE
 java.security.SignatureException: Signature was not verified

### ISSUE THREAD

**Issue by MRwangqi** [Tencent/tinker#342]
TinkerInstaller.onReceiveUpgradePatch报错

**Comment by shwenzhang** [comment]
https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#issue%E6%8F%90%E9%97%AE%E9%A1%BB%E7%9F%A5
请查看issue提问须知
