### ISSUE TITLE
自定义application问题

### ISSUE THREAD

**Issue by addappcn** [Tencent/tinker#343]
.app.SampleApplication 这个在哪 sample 目录下 根本没有这个文件，到底要不要自定义application

bugly  文档 写的 自定义application默认构造函数里调用 
super(ShareConstants.TINKER_ENABLE_ALL, "com.uto.driver.application.DriverApplicationLike",
                "com.tencent.tinker.loader.TinkerLoader", false);

**Comment by shwenzhang** [comment]
重复问题，好好看文档
