### ISSUE TITLE
code:-3,一直找不到原因

### ISSUE THREAD

**Issue by BeEagle** [Tencent/tinker#353]
TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/data/com.troy.tinkerfixdemo/tinker/patch.info
02-15 18:04:48.564 11454-11454/com.troy.tinkerfixdemo:patch W/Tinker.Tinker: tinker patch directory: /data/data/com.troy.tinkerfixdemo/tinker
02-15 18:04:48.564 11454-11454/com.troy.tinkerfixdemo:patch I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
02-15 18:04:48.574 11454-11454/com.troy.tinkerfixdemo:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3, systemOTA:false
02-15 18:04:48.574 11454-11454/com.troy.tinkerfixdemo:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
02-15 18:04:48.574 11454-11454/com.troy.tinkerfixdemo:patch I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.troy.tinkerfixdemo/tinker, code:-3, cost:3
02-15 18:04:48.574 11454-11454/com.troy.tinkerfixdemo:patch W/Tinker.Tinker: tinker load fail!
02-15 18:04:48.574 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
02-15 18:04:48.574 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.TinkerPatchService: try to increase patch process priority
02-15 18:04:48.644 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:b3e4505b851c675906b7389841e18dad
02-15 18:04:48.644 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b
02-15 18:04:48.654 11454-11477/com.troy.tinkerfixdemo:patch W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/patch.apk size: 3757, dest file: /data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b/patch-b3e4505b.apk size:3757
02-15 18:04:48.654 11454-11477/com.troy.tinkerfixdemo:patch E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 2609014704, got crc: 3693072101
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchTypeExtractFail: file extract fail type:dex, path:/data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b/patch-b3e4505b.apk, extractTo:/data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b/dex/classes.dex.jar, filename:classes.dex
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b/patch-b3e4505b.apk
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b/dex
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.troy.tinkerfixdemo/tinker/patch-b3e4505b
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:11
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
02-15 18:04:48.664 11454-11477/com.troy.tinkerfixdemo:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/storage/emulated/0/patch.apk, success:false, cost:87
02-15 18:04:48.674 11121-11487/com.troy.tinkerfixdemo I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                           PatchResult: 
                                                                                           isSuccess:false
                                                                                           rawPatchFilePath:/storage/emulated/0/patch.apk
                                                                                           costTime:87
                                                                                           patchVersion:b3e4505b851c675906b7389841e18dad

**Comment by shwenzhang** [comment]
02-15 18:04:48.654 11454-11477/com.troy.tinkerfixdemo:patch E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 2609014704, got crc: 3693072101
