### ISSUE TITLE
Tinker 命令接入遇到的问题

### ISSUE THREAD

**Issue by millerJK** [Tencent/tinker#355]
Tinker 热修复的命令接入有这样一句话： 我们需要自己保证proguard文件以及main dex类是正确的。同时您还提供了tinker_multidexkeep.pro示例，我想问您一下怎么保证main dex类是正确的？同时tinker_multidexkeep.pro 应该怎么使用？ 希望能给一个命令接入的demo ??

**Comment by shwenzhang** [comment]
gradle可以直接传入， eclipse需要自己写task将这些类放在主dex

**Comment by 1pbSolidDrives** [comment]
您说的意思是eclipse下不能用tinker吗
