### ISSUE TITLE
bugly的补丁能生成成功，但是加载失败

### ISSUE THREAD

**Issue by 450287475** [Tencent/tinker#356]
02-17 16:02:31.387 13877-13877/? E/dex2oat: Failed to open dex file from oat file. File: /data/user/0/com.inmotion.ble/tinker/patch-d28cd116/dex/classes.dex.jar Error: Failure to verify dex file '/data/user/0/com.inmotion.ble/tinker/patch-d28cd116/dex/classes.dex.jar': Found virtual method with same index as direct method: 56239
02-17 16:02:31.419 13790-13812/com.inmotion.ble:patch W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.inmotion.ble/tinker/patch-d28cd116/dex/classes.dex.jar --oat-fd=53 --oat-location=/data/user/0/com.inmotion.ble/tinker/patch-d28cd116/odex/classes.dex.dex --compiler-filter=speed) because non-0 exit status
02-17 16:02:31.611 13790-13812/com.inmotion.ble:patch W/art: Failure to verify dex file '/data/user/0/com.inmotion.ble/tinker/patch-d28cd116/dex/classes.dex.jar': Found virtual method with same index as direct method: 56239

手头的机子是7.0。加载失败，但是另一个5.0系统的手机却是加载成功了

**Comment by ccclll1990** [comment]
tinkerSupport {
    enableProxyApplication = false
.....
}

用这种模式试一下,我昨天enableProxyApplication = true 也是 7.0的失败, 4.4.4的成功,  enableProxyApplication = false 成功了.

**Comment by tomystang** [comment]
你好，能把失败的那台手机上的tinker目录打包发到我的邮箱：yinshengtang92@gmail.com吗？我看下是不是合成算法出bug了。

**Comment by shwenzhang** [comment]
建议先使用官方的Tinker尝试是否有问题

**Comment by xxoolltt** [comment]
问题解决了么？？ 现在发现7.0的手机热修复后会报错，java.lang.VerifyError
使用的是最新版本tinker1.7.7

**Comment by 450287475** [comment]
后来我重建了一个基础包，然后再加载修复补丁就可以了。使用的也是tinker 1.7.7

**Comment by xxoolltt** [comment]
那是基础包的问题么？
