### ISSUE TITLE
请问，这个错误是如何解决的，看得不太明白，求问！

### ISSUE THREAD

**Issue by wozhizhizhi** [Tencent/tinker#357]
02-17 16:47:09.162 19950-19972/com.uroad.carclub:patch E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 3913525048, got crc: 2635159770
02-17 16:47:09.162 19950-19972/com.uroad.carclub:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchTypeExtractFail: file extract fail type:dex, path:/data/data/com.uroad.carclub/tinker/patch-2cb27656/patch-2cb27656.apk, extractTo:/data/data/com.uroad.carclub/tinker/patch-2cb27656/dex/classes.dex.jar, filename:classes.dex
02-17 16:47:09.172 19950-19972/com.uroad.carclub:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.uroad.carclub/tinker/patch-2cb27656/patch-2cb27656.apk
02-17 16:47:09.172 19950-19972/com.uroad.carclub:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.uroad.carclub/tinker/patch-2cb27656/dex
02-17 16:47:09.182 19950-19972/com.uroad.carclub:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.uroad.carclub/tinker/patch-2cb27656
02-17 16:47:09.182 19950-19972/com.uroad.carclub:patch W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
02-17 16:47:09.182 19950-19972/com.uroad.carclub:patch I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:66
02-17 16:47:09.182 19950-19972/com.uroad.carclub:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
02-17 16:47:09.182 19950-19972/com.uroad.carclub:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/storage/emulated/0/Android/data/com.uroad.carclub/cache/hotPatch/new.apk, success:false, cost:166
02-17 16:47:09.412 18637-19987/com.uroad.carclub I/Tinker.MbResultService: MbResultService receive result: 
                                                                           PatchResult: 
                                                                           isSuccess:false
                                                                           rawPatchFilePath:/storage/emulated/0/Android/data/com.uroad.carclub/cache/hotPatch/new.apk
                                                                           costTime:166
                                                                           patchVersion:2cb276565ce7cd3893ff4462805921eb

**Comment by shwenzhang** [comment]
02-17 16:47:09.162 19950-19972/com.uroad.carclub:patch E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 3913525048, got crc: 2635159770

基础包改变了，请先查看已有的issue，然后再体issue
