### ISSUE TITLE
1.7.7版本遇到的多渠道打补丁包

### ISSUE THREAD

**Issue by xiaoyaodedao** [Tencent/tinker#360]
刚开始用的是1.7.5的版本,打补丁时任意一个补丁都能用在所有的渠道上,升级到1.7.7后多渠道补丁只能用在该渠道下的apk.可是,上传补丁时说补丁最多只能上传5个.请问:如何打一个补丁能用在所有的渠道上呢?
在1.7.5的多渠道的补丁中YAPATCH.MF的文件中是from tinkerId to tinkerId 而在1.7.7的多渠道补丁中YAPATCH.MF的文件中是from 渠道名tinkerId to 渠道名tinkerId.请问:是不是这个原因能?

**Comment by shwenzhang** [comment]
see wiki
