### ISSUE TITLE
接入Patch 平台出错，一直找不到原因？

### ISSUE THREAD

**Issue by BeEagle** [Tencent/tinker#361]
02-20 20:38:15.216 25714-25714/? I/Tinker.VersionInfo: updateVersionInfo file path:/data/data/com.troy.tinkerpatchtrydemo/tinker_server/version.info, appVersion: 1, uuid:9f156090-f7ee-4905-91e4-1327d771618e, abi:arm64-v8a, patchVersion:3, patchMd5:5ce608825adbe033bf36be310559f49d, grayValue:1, crashTimes:0, retryTimes:2
02-20 20:38:15.216 25714-25714/? I/Tinker.TinkerServerPatchListener: receive a patch file: /data/data/com.troy.tinkerpatchtrydemo/tinker_server/1_3.apk, file size:4815
02-20 20:38:15.336 26178-26178/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/data/com.troy.tinkerpatchtrydemo/tinker/patch.info
02-20 20:38:15.346 26178-26178/? I/Tinker.ServerUtils: with app key from manifest appKey:2f2ff6c4f5d7f0ca
02-20 20:38:15.346 26178-26178/? I/Tinker.ServerUtils: with app version from manifest appVersion:1
02-20 20:38:15.356 26178-26178/? I/Tinker.VersionInfo: readVersionInfo file path:/data/data/com.troy.tinkerpatchtrydemo/tinker_server/version.info, appVersion: 1, uuid:9f156090-f7ee-4905-91e4-1327d771618e, abi:arm64-v8a, patchVersion:3, patchMd5:5ce608825adbe033bf36be310559f49d, grayValue:1, crashTimes:0, retryTimes:2
02-20 20:38:15.366 26178-26178/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 1, appKey: 2f2ff6c4f5d7f0ca
02-20 20:38:15.376 26178-26178/? W/Tinker.Tinker: tinker patch directory: /data/data/com.troy.tinkerpatchtrydemo/tinker
02-20 20:38:15.376 26178-26178/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
02-20 20:38:15.376 26178-26178/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3, systemOTA:false
02-20 20:38:15.376 26178-26178/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
02-20 20:38:15.376 26178-26178/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.troy.tinkerpatchtrydemo/tinker, code:-3, cost:2
02-20 20:38:15.376 26178-26178/? W/Tinker.Tinker: tinker load fail!
02-20 20:38:15.376 26178-26201/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
02-20 20:38:15.396 26178-26201/? I/Tinker.TinkerPatchService: try to increase patch process priority
02-20 20:38:15.446 26178-26201/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:5ce608825adbe033bf36be310559f49d
02-20 20:38:15.446 26178-26201/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882
02-20 20:38:15.446 26178-26201/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/data/com.troy.tinkerpatchtrydemo/tinker_server/1_3.apk size: 4815, dest file: /data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882/patch-5ce60882.apk size:4815
02-20 20:38:15.456 26178-26201/? E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 2219923626, got crc: 3455045159
02-20 20:38:15.456 26178-26201/? I/Tinker.DefaultPatchReporter: patchReporter onPatchTypeExtractFail: file extract fail type:dex, path:/data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882/patch-5ce60882.apk, extractTo:/data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882/dex/classes.dex.jar, filename:classes.dex
02-20 20:38:15.456 26178-26201/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882/patch-5ce60882.apk
02-20 20:38:15.456 26178-26201/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882/dex
02-20 20:38:15.456 26178-26201/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.troy.tinkerpatchtrydemo/tinker/patch-5ce60882
02-20 20:38:15.456 26178-26201/? W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
02-20 20:38:15.456 26178-26201/? I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:11
02-20 20:38:15.456 26178-26201/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
02-20 20:38:15.456 26178-26201/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/data/data/com.troy.tinkerpatchtrydemo/tinker_server/1_3.apk, success:false, cost:66
02-20 20:38:15.476 25714-26204/? I/Tinker.TinkerServerResultService: receive result: 
                                                                     PatchResult: 
                                                                     **isSuccess:false**
                                                                     rawPatchFilePath:/data/data/com.troy.tinkerpatchtrydemo/tinker_server/1_3.apk
                                                                     costTime:66
                                                                     patchVersion:5ce608825adbe033bf36be310559f49d
02-20 20:38:15.476 25714-26204/? I/Tinker.ServerClient: tinker server report patch fail, patchVersion:3, errorCode:-2
02-20 20:38:15.476 25714-26204/? I/Tinker.UrlConnectionFetcher: loadData from url: http://stat.tinkerpatch.com/err.php, method:POST, body:t=1&code=-2&pv=3&av=1&k=2f2ff6c4f5d7f0ca
02-20 20:38:15.476 25714-26204/? I/Tinker.TinkerServerResultService: patch fail, please check reason
02-20 20:38:18.156 25714-25804/? I/Tinker.UrlConnectionFetcher: response code 200 msg: OK

**Comment by shwenzhang** [comment]
请到tinkerpatch主页提问
