### ISSUE TITLE
添加类库项目时，出现Unable to save plugin settings: The plugin org.jetbrains.android failed to save settings and has been disabled. Please restart Android Studio

### ISSUE THREAD

**Issue by ripplewizard** [Tencent/tinker#368]
异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：1.7.7

gradle版本：2.10

系统：Windows10

堆栈/日志：* Where:
Build file 'D:\dev\gitlab.com\tinkerdemo\app\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Android Studio 的版本是 2.2.3

**Comment by shwenzhang** [comment]
这个跟tinker无关吧，看起来就是java8的编译的plugin代码，你现在用的是java7

**Comment by ripplewizard** [comment]
android studio 2,3.3  会强制使用java8，tinker 里边使用的 java7

**Comment by shwenzhang** [comment]
java 8 可以兼容java7的，下面的plugin明显不是tinker的
![image](https://cloud.githubusercontent.com/assets/8335303/23256307/d6e46efe-f9f9-11e6-8ca1-8a77ef229761.png)
