### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by Thewhitelight** [Tencent/tinker#369]
异常类型：app运行时异

手机型号：Nexus 6P

手机系统版本：Android 7.1.1

tinker版本：1.7.7

gradle版本：2.14.1

系统：win8.1

堆栈：
1 java.lang.RuntimeException:Unable to create service com.igexin.sdk.PushService: java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
2 android.app.ActivityThread.handleCreateService(ActivityThread.java:3201)
3 ......
4 Caused by:
5 java.lang.IllegalAccessError:Method 'void com.tencent.bugly.beta.tinker.TinkerApplicationLike.setTinkerPatchApplicationLike(com.tencent.tinker.loader.app.ApplicationLike)' is inaccessible to class 'com.tencent.bugly.beta.tinker.TinkerApplicationLike' (declaration of 'com.tencent.bugly.beta.tinker.TinkerApplicationLike' appears in /data/user/0/cn.***.dms/tinker/patch-2d50e539/dex/classes.dex.jar)
6 com.tencent.bugly.beta.tinker.TinkerApplicationLike.<init>(Unknown Source)
7 java.lang.reflect.Constructor.newInstance0(Native Method)
8 java.lang.reflect.Constructor.newInstance(Constructor.java:430)
9 com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source)
10 com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source)
11 com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source)
12 com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source)
13 com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(Unknown Source)
14 android.app.Application.attach(Application.java:189)
15 android.app.Instrumentation.newApplication(Instrumentation.java:1008)
16 android.app.Instrumentation.newApplication(Instrumentation.java:992)
17 android.app.LoadedApk.makeApplication(LoadedApk.java:796)
18 android.app.ActivityThread.handleCreateService(ActivityThread.java:3188)
19 android.app.ActivityThread.-wrap5(ActivityThread.java)
20 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
21 android.os.Handler.dispatchMessage(Handler.java:102)
22 android.os.Looper.loop(Looper.java:154)
23 android.app.ActivityThread.main(ActivityThread.java:6119)
24 java.lang.reflect.Method.invoke(Native Method)
25 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
26 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by shwenzhang** [comment]
这个是bugly的问题
