### ISSUE TITLE
app加载问题，每次点击luncher里面的app图标，app总是重新启动 

### ISSUE THREAD

**Issue by shanyaodan** [Tencent/tinker#371]
测试手机 模拟器 android5.0 

下面这是安装后首次启动 没有 打补丁
02-24 06:46:08.381 1486-23787/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.qz.app/.SplashActivity (has extras)} from uid 10008 on display 0
02-24 06:46:08.381 1486-1546/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
02-24 06:46:08.434 1486-23788/system_process I/ActivityManager: Start proc com.qz.app for activity com.qz.app/.SplashActivity: pid=14553 uid=10443 gids={50443, 9997, 1028, 1015, 3003} abi=x86_64
02-24 06:46:08.434 14553-14553/? I/art: Not late-enabling -Xcheck:jni (already on)
02-24 06:46:08.453 14553-14561/? I/art: Debugger is no longer active
02-24 06:46:08.457 14553-14553/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.qz.app/tinker
02-24 06:46:08.458 14553-14553/? D/Tinker.DefaultAppLike: onBaseContextAttached:
02-24 06:46:08.458 14553-14553/? I/MultiDex: VM with version 2.1.0 has multidex support
02-24 06:46:08.458 14553-14553/? I/MultiDex: install
02-24 06:46:08.458 14553-14553/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
02-24 06:46:08.461 14553-14553/? W/Tinker.Tinker: tinker patch directory: /data/data/com.qz.app/tinker
02-24 06:46:08.462 14553-14553/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
02-24 06:46:08.462 14553-14553/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
02-24 06:46:08.462 14553-14553/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
02-24 06:46:08.462 14553-14553/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.qz.app/tinker, code:-2, cost:1
02-24 06:46:08.462 14553-14553/? W/Tinker.Tinker: tinker load fail!
02-24 06:46:08.462 14553-14553/? D/Tinker.DefaultAppLike: onCreate
02-24 06:46:08.472 14553-14553/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-24 06:46:08.497 14553-14569/? D/OpenGLRenderer: Render dirty regions requested: true  [ 02-24 06:46:08.498 14553:14553 D/      ]  HostConnection::get() New Host Connection established 0x7f43edb9d640, tid 14553
02-24 06:46:08.499 14553-14553/? D/Atlas: Validating map... [ 02-24 06:46:08.528 14553:14569 D/         ]HostConnection::get() New Host Connection established 0x7f43ed267180, tid 14569
02-24 06:46:08.531 14553-14569/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-24 06:46:08.566 14553-14569/? D/OpenGLRenderer: Enabling debug mode 0
02-24 06:46:08.631 1486-1510/system_process I/ActivityManager: Displayed com.qz.app/.SplashActivity: +216ms
02-24 06:46:11.595 1486-1682/system_process I/ActivityManager: START u0 {flg=0x10000000 cmp=com.qz.app/.activity.LoginActivity} from uid 10443 on display 0
02-24 06:46:11.758 1486-1510/system_process I/ActivityManager: Displayed com.qz.app/.activity.LoginActivity: +146ms

下面这是后台后的代码

02-24 06:47:50.226 1486-1531/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher/com.android.launcher2.Launcher} from uid 1000 on display 0
02-24 06:47:50.233 1123-1123/? E/EGL_emulation: tid 1123: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE)
02-24 06:47:50.281 15774-15774/com.qz.app D/Tinker.DefaultAppLike: onTrimMemory level:20
02-24 06:47:50.329 15774-15774/com.qz.app W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
02-24 06:47:50.894 1763-1964/com.android.launcher W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
02-24 06:47:50.894 1763-1964/com.android.launcher W/OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

下面这是在手机界面点击app图标 app就又从com.qz.app/.SplashActivity界面进入
02-24 06:49:39.484 1486-1546/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
02-24 06:49:44.044 1486-1953/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.qz.app/.SplashActivity (has extras)} from uid 10008 on display 0
02-24 06:49:44.045 1486-1546/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
02-24 06:49:44.193 1486-1510/system_process I/ActivityManager: Displayed com.qz.app/.SplashActivity: +110ms
02-24 06:49:47.144 1486-1748/system_process I/ActivityManager: START u0 {flg=0x10000000 cmp=com.qz.app/.activity.LoginActivity} from uid 10443 on display 0
02-24 06:49:47.200 1660-17106/com.android.inputmethod.latin I/LatinIME:LogUtils: Dictionary info: dictionary = spellcheck_userunigram.en_US ; version = 1487918987 ; date = ?
02-24 06:49:47.203 1660-17107/com.android.inputmethod.latin I/LatinIME:LogUtils: Dictionary info: dictionary = spellcheck_contacts.en_US ; version = 1487918987 ; date = ?
02-24 06:49:47.209 1660-1943/com.android.inputmethod.latin I/LatinIME:LogUtils: Dictionary info: dictionary = main:en ; version = 47 ; date = 1402373178
02-24 06:49:47.246 1486-1510/system_process I/ActivityManager: Displayed com.qz.app/.activity.LoginActivity: +84ms
02-24 06:49:48.570 1486-1564/system_process D/TaskPersister: removeObsoleteFile: deleting file=429_task.xml
02-24 06:49:48.570 1486-1564/system_process D/TaskPersister: removeObsoleteFile: deleting file=429_task_thumbnail.png

**Comment by shanyaodan** [comment]
public class App extends DefaultApplicationLike {

    private static final String TAG = "App";
    public static App instance;
    public static Context mContext;

    public App(Application application, int tinkerFlags, boolean tinkerLoadVerifyFlag,
               long applicationStartElapsedTime, long applicationStartMillisTime, Intent tinkerResultIntent) {
        super(application, tinkerFlags, tinkerLoadVerifyFlag, applicationStartElapsedTime, applicationStartMillisTime, tinkerResultIntent);
    }



    //以前application写在oncreate的东西搬到这里来初始化
    @Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);
        mContext = getApplication();
        MultiDex.install(base);
        TinkerInstaller.install(this, new DefaultLoadReporter(mContext), new DefaultPatchReporter(mContext), new DefaultPatchListener(mContext), SampleResultService.class, new UpgradePatch());
        instance = this;
        this.mContext = base;

    }
}
这是app的代码

**Comment by shwenzhang** [comment]
crash日志？

**Comment by shanyaodan** [comment]
关了吧，是我的问题
