### ISSUE TITLE
如何把更新的so库也加入到补丁中去？

### ISSUE THREAD

**Issue by bigbigbigbigbig** [Tencent/tinker#38]
如果so库出了问题，替换了so库后，如何把更新的so库也加入到补丁中去？而且做到加载patch时会自动加载新的so库，我的试了新，答案是no,patch包只有k,没有加入so库。请问正确的步骤是如何

**Comment by shwenzhang** [comment]
请阅读使用文档，这类问题一律不作问答

**Comment by dodola** [comment]
@bigbigbigbigbig [Tinker-常见问题](https://github.com/Tencent/tinker/wiki/Tinker-API%E6%A6%82%E8%A7%88)

**Comment by bigbigbigbigbig** [comment]
按wiki,so库也加入到补丁中去了，TinkerInstaller.loadArmLibrary也没报错，可在patch里面新加的第三方jar库里有System.loadLibrary，一运行就报错了，请问是什么情况及怎么处理。

**Comment by dodola** [comment]
@bigbigbigbigbig 额。。确实是这样的，虽然不建议在补丁里做像增加第三方库这样大的改动，但这确实是个问题，tinker并没有直接处理loadLibrary加载过程中的nativeLib替换过程

**Comment by shwenzhang** [comment]
第三方库也运行了那个library？如果这样，你可以在他之前提前把so加载了就可以了，这个问题之前是有考虑到的。

**Comment by bigbigbigbigbig** [comment]
@shwenzhang 真实情况是，提前把so加载了一样无效，不知道什么原因
![7f8f34ac](https://cloud.githubusercontent.com/assets/17684980/18858308/b5590078-849d-11e6-998e-110536fa4b3a.png)

**Comment by shwenzhang** [comment]
当然不行，你用的函数错了。你应该用另外一个loadlibrary的函数，还是详细看文档吧。

**Comment by bigbigbigbigbig** [comment]
@shwenzhang 我是用TinkerInstaller.loadArmV7Library(getApplicationContext(), "ksyplayer");
上面切图是jar包里的代码

**Comment by liyuwhy** [comment]
我也出现这个问题，同问怎么避免？？

**Comment by liyuwhy** [comment]
@shwenzhang
