### ISSUE TITLE
can't get git rev, you should add git to system path or just input test value, such as 'testTinkerId'

### ISSUE THREAD

**Issue by liuhe-android** [Tencent/tinker#381]
Error:(34, 0) Cause: can't get git rev, you should add git to system path or just input test value, such as 'testTinkerId'
<a href="openFile:D:\tinker-master\tinker-sample-android\app\build.gradle">Open File</a>
我运行的是simple demo 这个需要做什么配置吗？

**Comment by shwenzhang** [comment]
see wiki
