### ISSUE TITLE
调用assembleDebug编译成功后，没有生成/build/bakApk/xxx.apk

### ISSUE THREAD

**Issue by 1029589860** [Tencent/tinker#382]
build.gradle配置如下：
apply plugin: 'com.tencent.tinker.patch'

def bakPath = file("${buildDir}/bakApk/")
tinkerPatch {
    //有问题的apk的地址
    tinkerEnable true
    oldApk = "${bakPath}/app-debug-2017-0307-1357.apk"
    ignoreWarning = false
    useSign = true
    buildConfig{
        tinkerId = "1.0"
    }
    packageConfig{
        configField("TINKER_ID", "1.0")
        configField("platform", "all")
    }
    dex{
        dexMode = "jar"
        pattern = ["classes*.dex", "assets/secondary-dex-?.jar"]
        loader = ["com.tencent.tinker.loader.*", "ook.yzx.tinker.Application"]
    }
    lib{
        pattern = ["lib/armeabi/*.so","lib/arm64-v8a/*.so","lib/armeabi-v7a/*.so",
                   "lib/mips/*.so","lib/mips64/*.so","lib/x86/*.so","lib/x86_64/*.so"]
    }
    res{
        pattern = ["res/*", "assets/*", "resources.arsc", "AndroidManifest.xml"]
        largeModSize = 100
    }
    sevenZip{
        zipArtifact = "com.tencent.mm:SevenZip:1.1.10"
    }
}

**Comment by 1029589860** [comment]
???

**Comment by shwenzhang** [comment]
bakapk不是tinker的一部分，自己看看build.gradle
