### ISSUE TITLE
华为mate8集成Tinker无法安装补丁

### ISSUE THREAD

**Issue by GoombaCN** [Tencent/tinker#383]
android版本7.0 
先是使用Bugly的热更新 无法安装补丁 
遂安装之前写好的Tinker的Demo在华为mate8上
还是无法安装补丁
在其他机器上就可以正常安装
log里没有相关的错误日志

**Comment by shwenzhang** [comment]
请查看提问须知，而且这个不是tinker的问题。应该是bugly一键接入的问题
