### ISSUE TITLE
Error:Execution failed for task ':tinkerdemo:tinkerProcessDebugManifest'. > tinkerId is not set!!!

### ISSUE THREAD

**Issue by sunEvan** [Tencent/tinker#39]
![t6 h3y7t 7h 5 _m4 7 5](https://cloud.githubusercontent.com/assets/19648325/18833445/34f32f64-8423-11e6-8ad9-46b1e9627fb9.png)

虽然你一直说看close了的，但是真的懵逼啊，运行完，还是一样报错，找那报错的文件夹，却没发现文件，只有一个debug文件夹下的manifest，而且控制台的提示好像错了提示TINDER_ID=null

**Comment by shwenzhang** [comment]
你get出来的tinkerId依然是空，是否正确加入到对的property文件。用单独的IDE窗口打开sample

**Comment by sunEvan** [comment]
自己按照README.md不行，但是导入tinker-sample-android，在gradle.properties加入TINKER_ID=your_ID是可以的，但是这样无解啊，按照README.md不能成功，难道自己写的项目要要把sample的配置全部拷过去？

**Comment by shwenzhang** [comment]
你看一下gitSha()那个函数返回什么不就可以了？很大可能是你没有配ide的git路径

**Comment by sunEvan** [comment]
不知道为什么，就算把配置拷过去，他会提示说找不到这个函数，就好像simple里面加了个判断函数再去apply那个tinker模块，那个函数都找不到，我也试过直接仿照simple里面的配置，把 getTinkerIdValue()函数和定义拷过去，最后说tinkerId这个属性没有，配置gradle我是小白，也没什么搞过，但是错误意思就是找不到这个tinkerId属性

**Comment by shwenzhang** [comment]
@sunEvan ，这个是gradle基本的语法知识，建议先了解gradle配置相关知识。

**Comment by 15189611** [comment]
请问如何看gitSha()这个函数返回值·，能打印？在Gradle 中，谢谢

**Comment by agoodcoolman** [comment]
我导入不了 你们的项目，直接clone ，打开不了。一直在读入项目。

**Comment by shwenzhang** [comment]
@15189611 ，println就可以

**Comment by agoodcoolman** [comment]
@shwenzhang 导入不了你们的项目，你们使用as 2.2 开发的么。项目打不开。我看上面clone你们的项目可以打开。

**Comment by shwenzhang** [comment]
@agoodcoolman , as版本不影响的。就是简单的导入项目，sample工程在单独的IDE 窗口即可

**Comment by agoodcoolman** [comment]
@shwenzhang 谢谢。我知道怎么做了。
