### ISSUE TITLE
ViewTarget  appears in tinker/patch-6a269f69/dex/classes.dex.jar是tinker出什么问题了吗？

### ISSUE THREAD

**Issue by my-sunshine** [Tencent/tinker#390]
java.lang.NoSuchMethodError
No static method setTagId(I)V in class Lcom/bumptech/glide/request/target/ViewTarget; or its super classes (declaration of 'com.bumptech.glide.request.target.ViewTarget' appears in /data/data/XXX/tinker/patch-6a269f69/dex/classes.dex.jar)

**Comment by shwenzhang** [comment]
see wiki,提问规范
