### ISSUE TITLE
编译补丁包时报基础包不存在，但是填写了文件名了。

### ISSUE THREAD

**Issue by beecool7** [Tencent/tinker#394]
1.编译时报错
2.gradle版本2.14.1
3.系统mac

报错的提示：
Error:Execution failed for task ':app:tinkerPatchTestDebug'.
> old apk /Users/apple/AndroidStudioProjects/toso2o/app/build/bakApk/app-0313-22-41-14/test/app-test-debug.apk is not exist, you must set the correct old apk value!

但是我是填写的是：
![66abba95-a125-4504-bb9c-b0950ccc990a](https://cloud.githubusercontent.com/assets/22571898/23883673/a5e0bf98-08a3-11e7-8ac7-2422ea3f9a7a.png)
build生成的文件是这样的
![da184467-59af-4891-8fed-acade111da1d](https://cloud.githubusercontent.com/assets/22571898/23883709/d68afd48-08a3-11e7-969d-407b8685f75a.png)

**Comment by shwenzhang** [comment]
这个用的不是1.7.7 把？更新到最新版本

**Comment by beecool7** [comment]
用的是1.7.7的。

**Comment by beecool7** [comment]
用的是1.7.7版本的。

**Comment by shwenzhang** [comment]
是否使用了第三方平台，按照wiki 的提问须知详细写清楚阿狸

**Comment by beecool7** [comment]
1.编译时出错
2.gradle版本2.14.1
3.tinker的版本是1.7.7
4.项目中集成了百度地图，pushSDK,ShareSDK(友盟推送，友盟分享)，mediapicker
5.项目中只有一个渠道包，就是友盟的。
遇到这个问题后，我尝试着修改了tinkerOldApkPath的中的名称，发现不管我写什么都是报这个错误，
![dca12b9c-9e24-4a8e-8403-31c9863c5933](https://cloud.githubusercontent.com/assets/22571898/23907360/d2a9b652-090b-11e7-8812-58062e93d540.png)
而且都是app-test-debug.apk is not exsit
后来用tinkerPatchAllFlavorDebug,还是报同样的错误。

我编译debug和release是编译期生成的application有区别，release下的application不是对的，如图
![9cbe0388-7a74-41a1-89d7-316872928226](https://cloud.githubusercontent.com/assets/22571898/23907714/f3c5dbee-090c-11e7-845b-39e23235f75b.png)
gradle配置是这样写的
![1c3e2ae8-9e6a-4da0-a93d-2004da0d6b1e](https://cloud.githubusercontent.com/assets/22571898/23907830/3ad43562-090d-11e7-8508-566c8b13194f.png)
生成的bakApk是这样的
![cb0c85b5-4765-4ca1-9a56-ee2d57fe48d0](https://cloud.githubusercontent.com/assets/22571898/23907950/8a7ac9e6-090d-11e7-8c22-efbf60f669ad.png)

**Comment by TracyEminem** [comment]
最后怎么解决的？我也出现了这个问题

**Comment by walkthehorizon** [comment]
我也是类似，错误提示如下
`Error:Execution failed for task ':app:tinkerPatchOfficalDebug'.
> old apk null/offical/app-offical-debug.apk is not exist, you must set the correct old apk value!`

目前还没找到原因

**Comment by walkthehorizon** [comment]
找到原因了，在app的gradle下配置了
`    productFlavors {
        offical {}
        productFlavors.all { flavor ->
            flavor.manifestPlaceholders = [UMENG_CHANNEL_VALUE: name]
        }
    }`，如果你配置了productFlavors那么Tinker将默认使用多渠道打包的方式，此时应开启下面的配置
`
    // 打多渠道补丁时指定目录
     buildAllFlavorsDir = "${bakPath}/${baseApkDir}"`
此外，前面配置的baseApk地址，mapping地址等都不在生效。

**Comment by justenjoy963** [comment]
解决了，新版的修改为tinkerBuildFlavorDirectory = "${bakPath}/app-0914-16-58-54"

**Comment by SrDino** [comment]
如果是多渠道的话，该怎么实现呢？

**Comment by DunkKing123** [comment]
问题解决了吗，我也遇到了这个问题，多渠道打包，难道就不能配置修改APK命名了吗
