### ISSUE TITLE
Google play渠道上不允许使用动态更新吗？

### ISSUE THREAD

**Issue by kris520** [Tencent/tinker#399]
Due to Google Play Developer Distribution Agreement, we can't dynamic update our apk.
~~
这句话的意思是在google play渠道上的版本不能使用动态更新吗？

**Comment by pzhangleo** [comment]
Google默认不允许

**Comment by kris520** [comment]
不允许的话，我只需要在google play渠道上不让热更新的代码生效就可以了吧，代码不需要删除吧？

**Comment by pzhangleo** [comment]
一般没问题，点背被google查到可能下架或者封号

**Comment by shwenzhang** [comment]
请查看已有的issue
