### ISSUE TITLE
Tinker1.7.7版本安装补丁后和ActiveAndroid冲突的问题

### ISSUE THREAD

**Issue by h3r3x3** [Tencent/tinker#400]
异常类型：app运行时异常

手机型号：小米MI 5 荣耀 FRD AL00 华为 MHAAL00 等7.0系统的手机

手机系统版本：Android 7.0

tinker版本：1.7.7

gradle版本：3.3

是否使用第三方SDK： 没有

如果ActiveAndroid采用 ActiveAndroid.initialize(this) 方式来初始化数据库，tinker修复后会导致无法找到table的错误，修复前没有问题。
现在workaround的方法是，手动添加所需要的类，不做让其自行扫描需找。

[https://github.com/pardom/ActiveAndroid/blob/08c6335cd7324c6e72da536b0c6fffa5a798f6a2/src/com/activeandroid/Configuration.java#L232]()
看了下两种差别执行到此处会有有分支，7.0用classloader找不到所需要的类，7.0以下的可以

`
# Thread-3(544)
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
解析原始
1 com.activeandroid.Cache.java.lang.String getTableName(java.lang.Class)(SourceFile:156)
2 com.activeandroid.query.From.void addFrom(java.lang.StringBuilder)(SourceFile:169)
3 com.activeandroid.query.From.java.lang.String toSql()(SourceFile:250)
4 com.activeandroid.query.From.com.activeandroid.Model executeSingle()(SourceFile:311)
`

**Comment by tomystang** [comment]
试着按官网的步骤接入了ActiveAndroid，没有复现成功哦。尝试步骤如下：

1. 在Tinker的Demo里加入描述db的meta：
    <meta-data android:name="AA_DB_NAME" android:value="Test" />
    <meta-data android:name="AA_DB_VERSION" android:value="1" />
2. 在SampleApplicationLike的onCreate方法里初始化ActiveAndroid：
    ActiveAndroid.initialize(this.getApplication());
3. 按官网文档建立Category和Item两个Model类；
4. 在MainActivity的onResume里向db里写入记录：
    Category testCategory = new Category();
    testCategory.name = "testCat";
    testCategory.save();

    Item testItem = new Item();
    testItem.name = "testItem";
    testItem.category = testCategory;
    testItem.save();
    
应用补丁后未发生crash，也确认了记录是成功写入的。

我的复现步骤里是不是漏了啥呢？

**Comment by tomystang** [comment]
我明白了，你是通过补丁新增了Model类，我先看看哈。

**Comment by tomystang** [comment]
![image](https://cloud.githubusercontent.com/assets/20535341/24071378/44c057bc-0c0b-11e7-8dba-6b5bd923ad2d.png)

知道原因了，因为这个库扫描Model类的时候只读了base.apk，就是基准包，所以patch里新引入的Model类肯定无法被找到了。

**解决办法：看来只能像你说的那样手动指定Model类了**

**Comment by shwenzhang** [comment]
这个库为什么要这么做？

**Comment by tomystang** [comment]
@shwenzhang 
这个库是想方便用户使用，所以搞了自动查找Model类的逻辑

**Comment by h3r3x3** [comment]
不是新增的，并没有新增任何类，也没有改动到Model相关的
在7.0以下是不会报错的，以上报错

**Comment by shwenzhang** [comment]
这个是因为库是直接读base.apk加载的，所以没办法

**Comment by BeEagle** [comment]
要是指定model 类应该怎么指定？

**Comment by BeEagle** [comment]
@shwenzhang 请教您，ActiveAndroid 为什么只扫描base.apk呢，不应该是扫描合成补丁之后的新的dex文件么？
