### ISSUE TITLE
添加依赖后找不到相关类

### ISSUE THREAD

**Issue by nicaine** [Tencent/tinker#404]
我按照要求的加入依赖后，找不到相关类啊。com.tencent.tinker.loader.app.DefaultApplicationLike

![oy2 jy3vecc n8r c5 bg](https://cloud.githubusercontent.com/assets/11565328/24130096/9ec2c21e-0e21-11e7-9046-19819ac155c0.png)
![0 j3 f0735u981 ytkw6 7](https://cloud.githubusercontent.com/assets/11565328/24130097/9edb6260-0e21-11e7-816d-c65e8436aa27.png)
![4r ardou3 1t 157c 4dgkc](https://cloud.githubusercontent.com/assets/11565328/24130098/9fe5d9d8-0e21-11e7-8838-7fb9f3f7d449.png)
![4sod7m x67sg j61 nr 3c](https://cloud.githubusercontent.com/assets/11565328/24130101/a49fbbe2-0e21-11e7-8279-3d899144b502.png)

**Comment by shwenzhang** [comment]
clean and sync，这些是gradle的相关问题
