### ISSUE TITLE
Tinker 修复包不起作用

### ISSUE THREAD

**Issue by xiejinsorry** [Tencent/tinker#405]
只是在debug 环境下， 基准包和修复包打包 terminal打包都没问题,但是在onReceiveUpgradePatch的时候，console 的结果是这样的Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                             PatchResult: 
                                                                                             isSuccess:false
                                                                                             rawPatchFilePath:/storage/emulated/0/tinkersample/patch_signed_7zip.apk
                                                                                             costTime:26 
也没有任何异常，不明白是哪里出的问题

**Comment by shwenzhang** [comment]
不用问这种问题，请仔细阅读文档跟相关代码
