### ISSUE TITLE
签名验证失败

### ISSUE THREAD

**Issue by vincecarterhu** [Tencent/tinker#406]
异常类型：签名验证失败

手机型号:奇酷青春版

手机系统版本：:Android 5.1 

tinker版本：如:1.7.7

gradle版本：2.2.3

是否使用第三方SDK： 否

系统：windows

个别的签名文件签名后，会出现签名验证不通过，换个签名后此问题不出现
![image](https://cloud.githubusercontent.com/assets/10098068/24133988/33b66a00-0e3c-11e7-87bd-db37a3a55801.png)

**Comment by shwenzhang** [comment]
个别签名还是个别的手机？出现问题的签名是怎么样签署的

**Comment by vincecarterhu** [comment]
个别的签名，签名是eclipse签署的

**Comment by vincecarterhu** [comment]
个别的签名，签名是eclipse签署的 @shwenzhang

**Comment by shwenzhang** [comment]
你把补丁包跟基础包发我邮箱一下，shaowenzhang1986@gmail.com。或者直接QQ发我
