### ISSUE TITLE
有几个问题如下:

### ISSUE THREAD

**Issue by xiejinsorry** [Tencent/tinker#408]
1. 公司项目是给国外用户的,渠道是发布在Google play ，按你们文档的意思是不能用？
2. 因为application 是Tinker生成的,如果按照以前的方式要搞一些全局变量以及getset如何写？
3. 因为 试过发现 一经使用，即使吧补丁删除，仍旧有效，那假如说 有多个补丁包 ，需要把原来的补丁包卸载吗？

**Comment by shwenzhang** [comment]
see wiki
