### ISSUE TITLE
patch fail please check reason

### ISSUE THREAD

**Issue by shoyu666** [Tencent/tinker#41]
arm-v7a  android 7.0 模拟器

09-26 14:00:56.515 6711-6718/tinker.sample.android W/art: Suspending all threads took: 7.684ms
09-26 14:02:25.296 6711-6711/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:4161
09-26 14:02:25.384 6711-6718/tinker.sample.android W/art: Suspending all threads took: 31.644ms
09-26 14:02:25.611 6711-6711/tinker.sample.android I/Tinker.SamplePatchListener: get platform:all
09-26 14:02:25.851 6711-6718/tinker.sample.android W/art: Suspending all threads took: 102.461ms
09-26 14:02:25.870 6711-6711/tinker.sample.android I/Choreographer: Skipped 46 frames!  The application may be doing too much work on its main thread.
09-26 14:02:25.937 6711-6722/tinker.sample.android I/art: Background sticky concurrent mark sweep GC freed 20348(1446KB) AllocSpace objects, 9(936KB) LOS objects, 44% free, 4MB/8MB, paused 35.089ms total 392.529ms
09-26 14:02:25.952 6711-6722/tinker.sample.android W/art: Suspending all threads took: 14.166ms
09-26 14:02:29.293 6711-6711/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:4161
09-26 14:02:29.345 6711-6711/tinker.sample.android I/Tinker.DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-3, isUpgrade:true
09-26 14:02:31.430 6711-6718/tinker.sample.android W/art: Suspending all threads took: 158.246ms
09-26 14:02:31.516 6711-10816/tinker.sample.android I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                                  PatchResult: 
                                                                                  isUpgradePatch:true
                                                                                  isSuccess:false
                                                                                  rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                                  costTime:2465
                                                                                  patchVersion:6cafef544571321a5b8322f1342a2c0c
                                                                                  patchTinkerID:07af56e
                                                                                  baseTinkerID:07af56e
                                                                                  Throwable: null
09-26 14:02:31.550 6711-10816/tinker.sample.android I/Process: Sending signal. PID: 10778 SIG: 9

![qq 20160926220241](https://cloud.githubusercontent.com/assets/20290812/18837054/f6bff256-8434-11e6-997b-c3ae4903932d.png)

**Comment by shoyu666** [comment]
patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-3, isUpgrade:true
-3是ERROR_PATCH_RUNNING的意思么 isTinkerPatchServiceRunning false?

**Comment by shwenzhang** [comment]
合成过程失败，需要将patch进程的日志附上

**Comment by shoyu666** [comment]
09-26 14:49:39.684 1724-1724/tinker.sample.android:patch I/art: Not late-enabling -Xcheck:jni (already on)
09-26 14:49:39.692 1724-1724/tinker.sample.android:patch W/art: Unknown instruction set features for ARM CPU variant (generic) using conservative defaults
09-26 14:49:41.417 1724-1724/tinker.sample.android:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
09-26 14:49:41.446 1724-1724/tinker.sample.android:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
09-26 14:49:41.471 1724-1724/tinker.sample.android:patch I/MultiDex: VM with version 2.1.0 has multidex support
09-26 14:49:41.471 1724-1724/tinker.sample.android:patch I/MultiDex: install
09-26 14:49:41.471 1724-1724/tinker.sample.android:patch I/MultiDex: VM has multidex support, MultiDex support library is disabled.
09-26 14:49:41.485 1724-1724/tinker.sample.android:patch I/Tinker.SamplePatchListener: application maxMemory:384
09-26 14:49:41.540 1724-1724/tinker.sample.android:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/tinker.sample.android/tinker
09-26 14:49:41.543 1724-1724/tinker.sample.android:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5
09-26 14:49:41.544 1724-1724/tinker.sample.android:patch I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:6cafef544571321a5b8322f1342a2c0c, current:
09-26 14:49:41.544 1724-1724/tinker.sample.android:patch E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
09-26 14:49:41.545 1724-1724/tinker.sample.android:patch I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/tinker.sample.android/tinker, code:-5, cost:142
09-26 14:49:41.551 1724-1724/tinker.sample.android:patch W/Tinker.Tinker: tinker load fail!
09-26 14:49:41.556 1724-1724/tinker.sample.android:patch D/Tinker.DefaultAppLike: onCreate
09-26 14:49:41.616 1724-1724/tinker.sample.android:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
09-26 14:49:41.622 1724-1753/tinker.sample.android:patch I/Tinker.DefaultPatchReporter: patchReporter: patch service start
09-26 14:49:41.655 1724-1753/tinker.sample.android:patch W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch_signed_7zip.apk to /data/user/0/tinker.sample.android/tinker/temp.apk
09-26 14:49:42.175 1724-1753/tinker.sample.android:patch I/Tinker.TinkerPatchService: try to increase patch process priority
09-26 14:49:43.162 1724-1733/tinker.sample.android:patch W/art: Suspending all threads took: 40.243ms
09-26 14:49:43.630 1724-1733/tinker.sample.android:patch W/art: Suspending all threads took: 11.788ms
09-26 14:49:44.179 1724-1733/tinker.sample.android:patch W/art: Suspending all threads took: 29.561ms
09-26 14:49:44.502 1724-1753/tinker.sample.android:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:onPatchVersionCheckFail
09-26 14:49:44.503 1724-1753/tinker.sample.android:patch I/Tinker.DefaultPatchReporter: patchReporter: patch version exist. path:/storage/emulated/0/patch_signed_7zip.apk, version:6cafef544571321a5b8322f1342a2c0c, isUpgrade:true
09-26 14:49:44.504 1724-1753/tinker.sample.android:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:false, cost:2328, isUpgrade:true
09-26 14:49:44.504 1724-1753/tinker.sample.android:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/tinker.sample.android/tinker/patch.retry
09-26 14:49:44.507 1724-1753/tinker.sample.android:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/tinker.sample.android/tinker/temp.apk
09-26 14:49:44.639 1724-1733/tinker.sample.android:patch W/art: Suspending all threads took: 17.070ms

**Comment by shwenzhang** [comment]
版本检查错误，有可能是已经安装了相同的版本。
```
09-26 14:49:44.502 1724-1753/tinker.sample.android:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:onPatchVersionCheckFail
09-26 14:49:44.503 1724-1753/tinker.sample.android:patch I/Tinker.DefaultPatchReporter: patchReporter: patch version exist. path:/storage/emulated/0/patch_signed_7zip.apk, version:6cafef544571321a5b8322f1342a2c0c, isUpgrade:true
```

**Comment by shoyu666** [comment]
@shwenzhang 
同样的包  htc android 5.0 成功 ,确定的是包没问题
模拟器还是错误，删除apk，重新安装好了
谢谢
