### ISSUE TITLE
找不到相关资源

### ISSUE THREAD

**Issue by nicaine** [Tencent/tinker#412]
assembleDebug 做了基础包
修改好 tinker 配置文件, 执行 tinkerPatchDebug.
编译出错，找不到@*android:anim/accelerate_interpolator
![c pcsstuct62ogc8 b3ssu](https://cloud.githubusercontent.com/assets/11565328/24178682/80666522-0ee5-11e7-848a-c5d8587ecd40.png)
![3csm qcl i xx2a 9f4p](https://cloud.githubusercontent.com/assets/11565328/24178683/8074b0e6-0ee5-11e7-9290-b57debddde47.png)
![6ea 5z wtuwtw9i980px d](https://cloud.githubusercontent.com/assets/11565328/24178684/80a53432-0ee5-11e7-9b01-849d17e7ab9c.png)
![d0b9r7fr 5ij3p i 17 z6](https://cloud.githubusercontent.com/assets/11565328/24178685/80dd978c-0ee5-11e7-85c2-f3405c3b28dc.png)

不过我看了bottom_to_center这个里面是对的，没有多余的星号

**Comment by shwenzhang** [comment]
这个是你自身环境的配置问题
