### ISSUE TITLE
Error:Cannot invoke method doFirst() on null object

### ISSUE THREAD

**Issue by MQHuan** [Tencent/tinker#413]
项目中配置了：
    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', "armeabi"
        }
    }
并且配置了productFlavors的情况下会
Gradle project sync failed. Error:Cannot invoke method doFirst() on null object

**Comment by shwenzhang** [comment]
配置splits需要自己修改编译脚本，sample只是一个使用范例
