### ISSUE TITLE
#411 问题

### ISSUE THREAD

**Issue by likaiyuan559** [Tencent/tinker#414]
您好：
我们现在集成了Tinker后，目前发现一个华为机器会出现无法运行的问题：
（无论是debug还是release都不能运行，直接崩溃，机器信息请看下图）
（目前项目内没有做混淆处理，**# dex2jar反编译出来主dex包也包含了BaseApplication且没有被混淆**）
请问该如何解决这个问题呢？

今早又发现一个oppo的4.3版本的机子出现这个问题，希望可以劳烦一下告知我们解决方式，感激不尽。

#411

**Comment by likaiyuan559** [comment]
这是早上出现问题的机型信息
![Uploading a.png…]()

**Comment by likaiyuan559** [comment]
这是早上出现问题的机型信息

![a](https://cloud.githubusercontent.com/assets/18045170/24187331/78f6becc-0f17-11e7-99ee-fa9f27be668b.png)

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/24231456/beb46254-0fbf-11e7-8c29-1dccc2a7d184.png)

自行看日志跟wiki
