### ISSUE TITLE
android N上的tinker修复，导致加载类时间变慢

### ISSUE THREAD

**Issue by NoneNameBoy** [Tencent/tinker#416]
wiki: 『在Android N上，补丁对应用启动时间有轻微的影响；』

实际中，我们在目前项目使用tinker 1.7.7版本植入应用，并且使用nexus 6和小米6(rom 7.0)测试进行普通启动（非首次启动，非补丁首次生效启动）的测试，修复功能都正常的（包括代码，资源），结果是启动速度均延迟了50%。
请问下，有什么办法可以解决或者尽量调优吗？导致启动速度增加的主要原因是什么？

**Comment by alighters** [comment]
前排关注！！个人理解是Android N 上采取了混合编译，但Tinker 为了修复的准确性，就将 JIT 部分做了无用功。所以，在我看来是目前没法调优。

**Comment by shwenzhang** [comment]
请检查一下自己的接入把，这边我们是有测试，基本影响不大的。而且tinker本身就有日志输出

**Comment by NoneNameBoy** [comment]
每次都会看tinker的日志输出，基本上patch load的时间，不会超过100ms。 但是实际上启动影响的是几百ms。 
是否因为AndroidNClassLoader的介入，虽然解决了内联问题，但是像上面同学说的，JIT部分基本废弃了？

**Comment by shwenzhang** [comment]
应该不会，因为Tinker强制全量编译了odex,按理其实上比刚安装时纯解释执行更快

**Comment by shwenzhang** [comment]
这个的大致原因是因为pathlist多了几个element，由于class not found导致的fillinstacktrace造成的。下个版本考虑如何修改这个问题

**Comment by shwenzhang** [comment]
尝试在1.8.0 版本改进

**Comment by NoneNameBoy** [comment]
最近一直在查这个启动问题，发现确实如你所说，loadClass这块儿的时间特别多，而且不止是N平台。
如果没有成功加载的补丁，那么启动速度都是正常的。
期待1.8版本能够解决这个问题，因为我们项目还是蛮想使用tinker这个方案的。
谢谢了。

**Comment by shwenzhang** [comment]
try with 1.8.0

**Comment by balizhuang2012** [comment]
我们项目也遇上这个问题，一旦对外发布补丁，线上平均启动速度大跌，首页启动平均速度大约从2.2秒变慢到2.8秒的样子

**Comment by stephen8341** [comment]
> 最新版本还是慢啊，我们项目一旦对外发布补丁，线上平均启动速度大跌，首页启动平均速度大约从2.2秒变慢到2.8秒的样子

老哥，这块有解决吗？我们这边也是打补丁就变慢，数据也差不多。

**Comment by stephen8341** [comment]
> 最近一直在查这个启动问题，发现确实如你所说，loadClass这块儿的时间特别多，而且不止是N平台。
> 如果没有成功加载的补丁，那么启动速度都是正常的。
> 期待1.8版本能够解决这个问题，因为我们项目还是蛮想使用tinker这个方案的。
> 谢谢了。

hi，兄弟。这块有解决吗？
