### ISSUE TITLE
编译报错 tinkerId is not set!!!

### ISSUE THREAD

**Issue by Aplombs** [Tencent/tinker#418]
Error:Execution failed for task ':app:tinkerProcessDebugManifest'.
> tinkerId is not set!!!

**Comment by Aplombs** [comment]
我的项目已经配置git了
![image](https://cloud.githubusercontent.com/assets/14965464/24346101/8f6d8112-1305-11e7-866b-a1c23083204a.png)

**Comment by shwenzhang** [comment]
先查看已有issue！
