### ISSUE TITLE
如何调用build.gradle 文件中tinkerPatchDebug任务?

### ISSUE THREAD

**Issue by llmsparkbbbboy** [Tencent/tinker#42]
官方提供的simple app 的接入流程中第三步骤 调用tinkerPatchDebug ,如何调用这个任务呢?

**Comment by 7heaven** [comment]
Android Studio的右边gradle点开 里面能找到这个task， 或者你在终端里面输入./gradlew tinkerPatchDebug

**Comment by llmsparkbbbboy** [comment]
谢谢, 原来是这样.

**Comment by shwenzhang** [comment]
@llmsparkbbbboy ，建议先了解gradle编译相关基础知识。
