### ISSUE TITLE
DefaultApplicationLike.onCreate重复调用问题

### ISSUE THREAD

**Issue by easionchang** [Tencent/tinker#422]
异常类型：app运行时异常
手机型号：魅蓝Note3
手机系统版本：Android 5.1
tinker版本：1.7.7
gradle版本：2.10
是否使用第三方SDK： 使用 Bugly SDK和JpushSDK
描述：单独集成Tinker（基于BuglySDK）没问题，单独集成JpushSDK也没有问题；当集成这两个SDK后发现
TinkerApplication和DefaultApplicationLike会被初始化两次。
虽然被初始化两次但是启动和热修复都可以成功。
想咨询两个问题：
1.被初始化两次对应用有没有影响（现在验证没什么影响，不知道以后会有没有）？
2.被初始化两次是不是Tinker的问题（还是极光推送的问题）？

![image](https://cloud.githubusercontent.com/assets/3087267/24434673/a18a802a-1463-11e7-851d-832eb54c1693.png)

![image](http://img.blog.csdn.net/20170329100308676?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvZWFzaW9uX3ptcw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

![image](http://img.blog.csdn.net/20170329100323157?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvZWFzaW9uX3ptcw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

日志如下：

cn.flyrise.feparks E/MyTinkerApplication: onCreate   pid===28253
cn.flyrise.feparks W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/cn.flyrise.feparks/tinker
cn.flyrise.feparks W/Tinker.Tinker: tinker patch directory: /data/data/cn.flyrise.feparks/tinker
cn.flyrise.feparks W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
cn.flyrise.feparks W/Tinker.Tinker: tinker load fail!
cn.flyrise.feparks E/MyTinkerApplicationLike: onCreate   pid===28253
cn.flyrise.feparks I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@dedb759
cn.flyrise.feparks E/MyTinkerApplicationLike: isDebugMode==false
cn.flyrise.feparks:pushcore E/MyTinkerApplication: onCreate   pid===28314
cn.flyrise.feparks:pushcore W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/cn.flyrise.feparks/tinker
cn.flyrise.feparks:pushcore W/Tinker.Tinker: tinker patch directory: /data/data/cn.flyrise.feparks/tinker
cn.flyrise.feparks:pushcore W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
cn.flyrise.feparks:pushcore W/Tinker.Tinker: tinker load fail!
cn.flyrise.feparks:pushcore E/MyTinkerApplicationLike: onCreate   pid===28314
cn.flyrise.feparks:pushcore I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@12ae93ed
cn.flyrise.feparks:pushcore E/MyTinkerApplicationLike: isDebugMode==false
cn.flyrise.feparks:pushcore W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
cn.flyrise.feparks W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return

**Comment by shwenzhang** [comment]
这个明显是因为有两个进程。。。。

**Comment by easionchang** [comment]
这个为什么会有两个进程？是不是tinker的问题？
如果有两个进程对tinker和应用有影响吗？

**Comment by shwenzhang** [comment]
当然跟tinker没有关系，你自己看一下进程号跟进程名

**Comment by easionchang** [comment]
多谢
确定了
是由于采用jcenter方式集成极光推送的原因

**Comment by easionchang** [comment]
还发现有个cn.flyrise.feparks:patch是tinker的进程吧

**Comment by easionchang** [comment]
cn.flyrise.feparks E/MyTinkerApplicationLike: isDebugMode==false
cn.flyrise.feparks:patch E/MyTinkerApplicationLike: isDebugMode==false

DefaultApplicationLike.onCreate还是会调用两次

**Comment by shwenzhang** [comment]
什么叫重复调用，每个进程都需要初始化application实例，这个根本就不是重复调用，是Android的机制本身
