### ISSUE TITLE
关于反射Application的方式

### ISSUE THREAD

**Issue by chenenyu** [Tencent/tinker#426]
异常类型：app运行时异常

手机型号：mi4

手机系统版本：Android 7.0

tinker版本：如:1.7.7

gradle版本：3.3

是否使用第三方SDK： Bugly SDK

补丁的生成及合成过程走完了，但是重启应用之后就崩溃了，看log是自己的Application中调用了其他类的方法，但是被调用的那个类合成的过程中出现了异常(未修改)。请问不使用ApplicationLike的方式接入，需要注意哪些地方？ 自己的Application中引用的类可以修改吗？  需要放到`loader`中吗？

**Comment by shwenzhang** [comment]
这个具体请咨询第三方SDK
