### ISSUE TITLE
Tinker.SamplePatchListener: get platform:all之后一直没有回调结果

### ISSUE THREAD

**Issue by mwping** [Tencent/tinker#43]
下面是:patch进程的Log，（应该是找到了补丁文件），之后一直是onTrimMemory level:60这样的Log。

09-26 23:13:09.964 24843-24856/com.example.testtinker:patch I/Tinker.DefaultPatchReporter: patchReporter: patch service start
09-26 23:13:09.968 24843-24856/com.example.testtinker:patch W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/QQBrowser/跨屏穿越/patch_signed_7zip.apk to /data/user/0/com.example.testtinker/tinker/temp.apk
09-26 23:13:09.971 24843-24856/com.example.testtinker:patch I/Tinker.TinkerPatchService: try to increase patch process priority
09-26 23:13:09.999 24843-24856/com.example.testtinker:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:dexDiffMd5:6452e78ed10bcd0cd2a8dcd5f21d61ac
09-26 23:13:09.999 24843-24856/com.example.testtinker:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.example.testtinker/tinker/patch-6452e78e
09-26 23:13:10.000 24843-24856/com.example.testtinker:patch W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/QQBrowser/跨屏穿越/patch_signed_7zip.apk size:4001, /data/user/0/com.example.testtinker/tinker/patch-6452e78e/patch-6452e78e.apk size:4001
09-26 23:13:10.283 24843-24856/com.example.testtinker:patch I/art: Starting a blocking GC Explicit
09-26 23:13:10.292 24843-24856/com.example.testtinker:patch I/art: Explicit concurrent mark sweep GC freed 67518(2MB) AllocSpace objects, 1(16KB) LOS objects, 40% free, 20MB/33MB, paused 77us total 8.915ms
09-26 23:13:10.353 24843-24856/com.example.testtinker:patch I/art: Starting a blocking GC Explicit
09-26 23:13:10.361 24843-24856/com.example.testtinker:patch I/art: Explicit concurrent mark sweep GC freed 62098(1710KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 20MB/34MB, paused 86us total 8.024ms
09-26 23:13:11.180 24843-24856/com.example.testtinker:patch I/art: Starting a blocking GC Explicit
09-26 23:13:11.189 24843-24856/com.example.testtinker:patch I/art: Explicit concurrent mark sweep GC freed 68042(2MB) AllocSpace objects, 0(0B) LOS objects, 40% free, 20MB/34MB, paused 95us total 8.699ms
09-26 23:13:11.263 24843-24856/com.example.testtinker:patch I/art: Starting a blocking GC Explicit
09-26 23:13:11.272 24843-24856/com.example.testtinker:patch I/art: Explicit concurrent mark sweep GC freed 70475(2020KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 20MB/34MB, paused 92us total 8.292ms
09-26 23:13:11.274 24843-24856/com.example.testtinker:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.example.testtinker/tinker/patch-6452e78e/dex/classes.dex.jar, use time: 1270
09-26 23:13:11.275 24843-24856/com.example.testtinker:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.example.testtinker/tinker/patch-6452e78e/dex/test.dex.jar
09-26 23:13:11.276 24843-24856/com.example.testtinker:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-26 23:13:11.342 24843-24856/com.example.testtinker:patch I/Tinker.DexDiffPatchInternal: success dex optimize file, path: /data/user/0/com.example.testtinker/tinker/patch-6452e78e/dex/classes.dex.jar, use time: 66
09-26 23:13:11.393 24843-24856/com.example.testtinker:patch I/Tinker.DexDiffPatchInternal: success dex optimize file, path: /data/user/0/com.example.testtinker/tinker/patch-6452e78e/dex/test.dex.jar, use time: 51
09-26 23:13:11.393 24843-24856/com.example.testtinker:patch I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:1393, isUpgradePatch:true
09-26 23:13:11.393 24843-24856/com.example.testtinker:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
09-26 23:13:11.394 24843-24856/com.example.testtinker:patch W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
09-26 23:13:11.394 24843-24856/com.example.testtinker:patch I/PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.example.testtinker/tinker/patch.info , oldVer:, newVer:6452e78ed10bcd0cd2a8dcd5f21d61ac
09-26 23:13:11.395 24843-24856/com.example.testtinker:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
09-26 23:13:11.396 24843-24856/com.example.testtinker:patch I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/QQBrowser/跨屏穿越/patch_signed_7zip.apk, success:true, cost:1425, isUpgrade:true
09-26 23:13:11.396 24843-24856/com.example.testtinker:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.example.testtinker/tinker/patch.retry
09-26 23:13:11.396 24843-24856/com.example.testtinker:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.example.testtinker/tinker/temp.apk
09-26 23:13:11.405 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:80
09-26 23:13:54.945 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:80
09-26 23:13:54.959 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:80
09-26 23:13:55.254 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:80
09-26 23:14:29.629 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:60
09-26 23:14:29.662 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:60
09-26 23:14:29.679 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:60
09-26 23:14:38.529 24843-24843/com.example.testtinker:patch D/Tinker.DefaultAppLike: onTrimMemory level:60

app进程的Log：

09-26 23:13:09.870 24690-24690/com.example.testtinker I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/QQBrowser/跨屏穿越/patch_signed_7zip.apk, isUpgrade:true, file size:4001
09-26 23:13:09.883 24690-24690/com.example.testtinker I/Tinker.SamplePatchListener: get platform:all

就一直不往下走了。正常应该出现重启App的Toast提示，求教

**Comment by shwenzhang** [comment]
@mwping , main进程一直还存在吗？patch进程的已经合成成功，下一步应该会回调主进程，是否已经将你的service添加到manifest中?
```java
patchReporter: patch all result path:/storage/emulated/0/QQBrowser/跨屏穿越/patch_signed_7zip.apk, success:true, cost:1425, isUpgrade:true
```

**Comment by mwping** [comment]
@shwenzhang 确实是service没有添加的问题。基本都跑通了，多谢！
