### ISSUE TITLE
华为android O启动应用闪退

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#431]
异常类型：app运行时异常

手机型号：华为6P O版本

手机系统版本：Android 8.0

tinker版本：1.7.7

gradle版本：2.10

是否使用第三方SDK： 否

系统：android

堆栈/日志：
03-22 20:28:01.904 E/AndroidRuntime(13252): FATAL EXCEPTION: main
03-22 20:28:01.904 E/AndroidRuntime(13252): Process: com.duowan.kiwi, PID: 13252
03-22 20:28:01.904 E/AndroidRuntime(13252): java.lang.RuntimeException: Unable to instantiate application com.duowan.kiwi.TinkerApp: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.LoadedApk.makeApplication(LoadedApk.java:1004)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5624)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.ActivityThread.-wrap2(Unknown Source:0)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.os.Looper.loop(Looper.java:154)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.ActivityThread.main(ActivityThread.java:6408)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at java.lang.reflect.Method.invoke(Native Method)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:232)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
03-22 20:28:01.904 E/AndroidRuntime(13252): Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:116)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:122)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.Application.attach(Application.java:189)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.Instrumentation.newApplication(Instrumentation.java:1085)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.Instrumentation.newApplication(Instrumentation.java:1069)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at android.app.LoadedApk.makeApplication(LoadedApk.java:998)
03-22 20:28:01.904 E/AndroidRuntime(13252):  ... 9 more
03-22 20:28:01.904 E/AndroidRuntime(13252): Caused by: java.lang.ClassNotFoundException: com.duowan.kiwi.KiwiApplication
03-22 20:28:01.904 E/AndroidRuntime(13252):  at java.lang.Class.classForName(Native Method)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at java.lang.Class.forName(Class.java:454)
03-22 20:28:01.904 E/AndroidRuntime(13252):  at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109)
03-22 20:28:01.904 E/AndroidRuntime(13252):  ... 16 more
03-22 20:28:01.904 E/AndroidRuntime(13252): Caused by: java.lang.InternalError: Attempt to register dex file /data/app/com.duowan.kiwi-MzFYeRF-ostnfEE1wW_WGg==/base.apk with multiple class loaders

描述：
启动应用闪退

**Comment by typ0520** [comment]
我也出现一个同样的错误，反编译后看到有这个like类并且也是在第一个dex里

**Comment by tomystang** [comment]
检查一下loader pattern里是否误加了com.duowan.kiwi.KiwiApplication？
@balizhuang2012

**Comment by balizhuang2012** [comment]
@tomystang 没有误加。我都没注意到有loader pattern这么个概念，所以没动过，值和demo一样。我试试把生成的application类(com.duowan.kiwi.TinkerApp)加进去吧
        dex {
           dexMode = "jar"
            pattern = ["classes*.dex",
                       "assets/secondary-dex-?.jar"]
            loader = ["com.tencent.tinker.loader.*",
                      "tinker.sample.android.SampleApplication",
                      "tinker.sample.android.app.BaseBuildInfo"
            ]
        }

**Comment by balizhuang2012** [comment]
换成tinker 1.7.8就OK了

**Comment by cryforyou** [comment]
这个问题啥原因?1.7.8哪个patch修复了?

**Comment by shwenzhang** [comment]
try with tinker 1.7.8

**Comment by jian156j** [comment]
这个问题根本原因都没有讲清楚,只是换了个更高的版本???好随意的解法

**Comment by coolegos** [comment]
@jian156j 
> Android 8.0 不支持多个类加载器同时尝试使用相同的 DexFile 对象来定义类。尝试进行此操作，会导致 Android 运行时引发 InternalError 错误，同时显示消息“Attempt to register dex file <filename> with multiple class loaders”。

**Comment by lizhimj** [comment]
有哪位大佬能详解以下这个问题的解法嘛
