### ISSUE TITLE
svn集成tinker

### ISSUE THREAD

**Issue by fishsoft** [Tencent/tinker#432]
使用svn，怎么集成tinker获取tinkerId？

**Comment by itMicmouse** [comment]
import org.tmatesoft.svn.core.wc.*

def getSvnRevision() {
    ISVNOptions options = SVNWCUtil.createDefaultOptions(true);
    SVNClientManager clientManager = SVNClientManager.newInstance(options);
    SVNStatusClient statusClient = clientManager.getStatusClient();
    SVNStatus status = statusClient.doStatus(projectDir, false);
    SVNRevision revision = status.getCommittedRevision();
    return revision.getNumber();
}
