### ISSUE TITLE
TINKER_ID 不对

### ISSUE THREAD

**Issue by xw8852** [Tencent/tinker#434]
异常类型：app运行时异常

手机型号：Letv X608

手机系统版本：Android 5.0 。2

tinker版本：1.7.7

gradle版本：2.14

tinkerPatch {
    oldApk =
//                'null'
            "${projectDir}/tinker/" + project.TINKER_APK
    ignoreWarning = false
    useSign = true
    buildConfig {
        tinkerId = "177"
        applyResourceMapping = oldApk + '-R.txt'
    }
    packageConfig {
        configField("TINKER_ID", "177")
    }
    dex {
        dexMode = "jar"
        pattern = ["classes*.dex",
                   "assets/secondary-dex-?.jar"]
        loader = ["com.tencent.tinker.loader.*",
                  "com.lovehome.android.aijiazhusou.AijiaTinkerApplication"
        ]
    }
    lib {
        pattern = ["lib/armeabi/*.so",
                   "lib/arm64-v8a/*.so",
                   "lib/armeabi-v7a/*.so",
                   "lib/x86/*.so",
                   "lib/x86_64/*.so"]
    }

    res {
        pattern = ["res/*", "assets/*", "resources.arsc", "AndroidManifest.xml"]
//        ignoreChange = ["res/*","resources.arsc"]
        largeModSize = 100
    }
    sevenZip {
        zipArtifact = "com.tencent.mm:SevenZip:1.1.10"
    }

}
最后生成的tinker_id不对
NEW_TINKER_ID=tinker_id_177
TINKER_ID=177
日志提示：
 E/Tinker.TinkerInternals: tinkerId is not equal, base is tinker_id_177, but patch is 177
E/Tinker.UpgradePatch: UpgradePatch tryPatch:onPatchPackageCheckFail

合成日志：

04-04 15:41:21.830 15514-19305/? I/Tinker.AijiaPatchListener: receive a patch file: /data/data/com.lovehome.aijiazhushou.internal/files/update/2.64_update.jar, file size:804529
04-04 15:41:21.837 954-2369/? W/ActivityManager: yuanguohong: cpmInfo = ServiceInfo{3fb7aa85 com.tencent.tinker.lib.service.TinkerPatchService}, cpmUid = 10205, cpmPkg = com.lovehome.aijiazhushou.internal, cpmPcs = com.lovehome.aijiazhushou.internal, userId = 0, callingUid = 10205, callingPid = 15514, hasExOpFlag = false, hasSystemFlag = false
04-04 15:41:21.837 954-2369/? W/ActivityManager: yuanguohong: cpmInfo = ServiceInfo{3fb7aa85 com.tencent.tinker.lib.service.TinkerPatchService}, cpmUid = 10205, cpmPkg = com.lovehome.aijiazhushou.internal, cpmPcs = com.lovehome.aijiazhushou.internal, userId = 0, callingUid = 10205, callingPid = 15514, hasExOpFlag = false, hasSystemFlag = false
04-04 15:41:21.857 954-2369/? I/ActivityManager: Start proc com.lovehome.aijiazhushou.internal:patch for service com.lovehome.aijiazhushou.internal/com.tencent.tinker.lib.service.TinkerPatchService: pid=19450 uid=10205 gids={50205, 9997, 3003, 1028, 1015} abi=armeabi-v7a
04-04 15:41:21.892 19450-19450/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.lovehome.aijiazhushou.internal/tinker
04-04 15:41:21.894 19450-19450/? D/Tinker.DefaultAppLike: onBaseContextAttached:
04-04 15:41:21.899 19450-19450/? I/Tinker.AijiaPatchListener: application maxMemory:256
04-04 15:41:21.902 19450-19450/? E/Tinker.Tinker: tinker patch directory: /data/data/com.lovehome.aijiazhushou.internal/tinker
04-04 15:41:21.903 19450-19450/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
04-04 15:41:21.903 19450-19450/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
04-04 15:41:21.904 19450-19450/? E/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
04-04 15:41:21.904 19450-19450/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.lovehome.aijiazhushou.internal/tinker, code:-2, cost:2
04-04 15:41:21.905 19450-19450/? E/Tinker.Tinker: tinker load fail!
04-04 15:41:21.905 19450-19450/? D/Tinker.DefaultAppLike: onCreate
04-04 15:41:22.077 19450-19450/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@3d2fd4db className=com.tencent.tinker.lib.service.TinkerPatchService packageName=com.lovehome.aijiazhushou.internal intent=null}
04-04 15:41:22.078 19450-19450/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@3d2fd4db className=com.tencent.tinker.lib.service.TinkerPatchService packageName=com.lovehome.aijiazhushou.internal intent=null}
04-04 15:41:22.078 19450-19450/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService@1c9a8b78, flags=0, startId=1
04-04 15:41:22.079 19450-19481/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
04-04 15:41:22.079 19450-19450/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@3d2fd4db startId=1 args=Intent { cmp=com.lovehome.aijiazhushou.internal/com.tencent.tinker.lib.service.TinkerPatchService (has extras) }}
04-04 15:41:22.093 19450-19481/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.lovehome.aijiazhushou.internal/tinker_temp/temp.apk
04-04 15:41:22.094 19450-19481/? E/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
04-04 15:41:22.094 19450-19481/? I/Tinker.TinkerPatchService: try to increase patch process priority
04-04 15:41:22.101 19450-19450/? E/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
04-04 15:41:22.107 954-1119/? W/ActivityManager: yuanguohong: cpmInfo = ServiceInfo{3f8e2132 com.tencent.tinker.lib.service.TinkerPatchService$InnerService}, cpmUid = 10205, cpmPkg = com.lovehome.aijiazhushou.internal, cpmPcs = com.lovehome.aijiazhushou.internal, userId = 0, callingUid = 10205, callingPid = 19450, hasExOpFlag = false, hasSystemFlag = false
04-04 15:41:22.107 954-1119/? W/ActivityManager: yuanguohong: cpmInfo = ServiceInfo{3f8e2132 com.tencent.tinker.lib.service.TinkerPatchService$InnerService}, cpmUid = 10205, cpmPkg = com.lovehome.aijiazhushou.internal, cpmPcs = com.lovehome.aijiazhushou.internal, userId = 0, callingUid = 10205, callingPid = 19450, hasExOpFlag = false, hasSystemFlag = false
04-04 15:41:22.111 19450-19450/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@1b1c2251 className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=com.lovehome.aijiazhushou.internal intent=null}
04-04 15:41:22.115 19450-19450/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@1b1c2251 className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=com.lovehome.aijiazhushou.internal intent=null}
04-04 15:41:22.115 19450-19450/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@39157ab6, flags=0, startId=1
04-04 15:41:22.115 19450-19450/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@1b1c2251 startId=1 args=Intent { cmp=com.lovehome.aijiazhushou.internal/com.tencent.tinker.lib.service.TinkerPatchService$InnerService }}
04-04 15:41:22.115 19450-19450/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@39157ab6
04-04 15:41:22.133 19450-19481/? E/Tinker.TinkerInternals: tinkerId is not equal, base is tinker_id_177, but patch is 177
04-04 15:41:22.134 19450-19481/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:onPatchPackageCheckFail
04-04 15:41:22.134 19450-19481/? I/Tinker.DefaultPatchReporter: patchReporter onPatchPackageCheckFail: package check failed. path:/data/data/com.lovehome.aijiazhushou.internal/files/update/2.64_update.jar, code:-7
04-04 15:41:22.134 19450-19481/? I/Tinker.AijiaTinkerReport: hp_report package check failed, error = -7
04-04 15:41:22.135 19450-19481/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/data/data/com.lovehome.aijiazhushou.internal/files/update/2.64_update.jar, success:false, cost:41
04-04 15:41:22.138 19450-19481/? I/Tinker.AijiaTinkerReport: hp_report report apply cost = 41
04-04 15:41:22.149 954-2369/? W/ActivityManager: yuanguohong: cpmInfo = ServiceInfo{ac3c800 com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService}, cpmUid = 10205, cpmPkg = com.lovehome.aijiazhushou.internal, cpmPcs = com.lovehome.aijiazhushou.internal, userId = 0, callingUid = 10205, callingPid = 19450, hasExOpFlag = false, hasSystemFlag = false
04-04 15:41:22.150 954-2369/? W/ActivityManager: yuanguohong: cpmInfo = ServiceInfo{ac3c800 com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService}, cpmUid = 10205, cpmPkg = com.lovehome.aijiazhushou.internal, cpmPcs = com.lovehome.aijiazhushou.internal, userId = 0, callingUid = 10205, callingPid = 19450, hasExOpFlag = false, hasSystemFlag = false
04-04 15:41:22.151 15514-15514/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@22ab23f5 className=com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService packageName=com.lovehome.aijiazhushou.internal intent=null}
04-04 15:41:22.153 19450-19450/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService@1c9a8b78
04-04 15:41:22.153 15514-15514/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@22ab23f5 className=com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService packageName=com.lovehome.aijiazhushou.internal intent=null}
04-04 15:41:22.153 15514-15514/? D/ActivityThread: SVC-Calling onStartCommand: com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService@2c51258a, flags=0, startId=1
04-04 15:41:22.153 15514-15514/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@22ab23f5 startId=1 args=Intent { cmp=com.lovehome.aijiazhushou.internal/com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService (has extras) }}
04-04 15:41:22.155 15514-19489/? I/Tinker.SampleResultService: SampleResultService receive result: 
                                                               PatchResult: 
                                                               isSuccess:false
                                                               rawPatchFilePath:/data/data/com.lovehome.aijiazhushou.internal/files/update/2.64_update.jar
                                                               costTime:41
04-04 15:41:22.159 15514-15514/? D/ActivityThread: SVC-Destroying service: com.lovehome.android.aijiazhusou.common.tinker.AijiaResultService@2c51258a

**Comment by shwenzhang** [comment]
04-04 15:41:22.134 19450-19481/? I/Tinker.DefaultPatchReporter: patchReporter onPatchPackageCheckFail: package check failed. path:/data/data/com.lovehome.aijiazhushou.internal/files/update/2.64_update.jar, code:-7
