### ISSUE TITLE
自定义Application中复写startActivity是否会有问题

### ISSUE THREAD

**Issue by HolenZhou** [Tencent/tinker#437]
本来考虑Application是用自动生成的方式，但发现改造我们项目的Application时，Application中有类似下面的方法：
```
    @Override
    public void startActivity(Intent intent) {
        AutoSyncManager.checkAutoSync(intent);
        super.startActivity(intent);
    }
```
getResoure()之类的方法TinkerApplication还贴心的回调了代理ApplicationLike类的类似方法，但是startActivity方法是没有类似的回调的，那么我目前只有使用自定义Application的方式在其中复写上面的方法，不知这样是否会有什么问题，还是仅仅会使这部分代码不能进行热修复？

**Comment by shwenzhang** [comment]
如果自定义Application，需要将Application里面使用的类也放到loader类中。建议把这段逻辑移到外面
