### ISSUE TITLE
Tinker 代码混淆后进行签名，然后补丁包是否也支持混淆呢？现在遇到一个问题，就是补丁包混淆后不能识别。

### ISSUE THREAD

**Issue by RichesJson** [Tencent/tinker#438]
异常类型：app运行时异常

手机型号：Nexus6

手机系统版本：Android 7.0

tinker版本：1.7.7

gradle版本: 3.3.0

是否使用第三方SDK：无

系统:Mac

问题：代码混淆后，补丁包认不到。主apk代码混淆后，补丁包是否也支持代码混淆？

堆栈/日志：
04-10 11:58:22.183 2043-4889/? I/ActivityManager: Killing 12513:com.nd.tinker:patch/u0a115 (adj 900): remove task
04-10 11:58:22.185 2043-2833/? I/WindowManager: Destroying surface Surface(name=com.nd.tinker/com.nd.tinker.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
04-10 11:58:22.522 11594-12604/? W/ProcStatsManager: No process com.nd.tinker:patch/10115 for service com.tencent.tinker.lib.service.TinkerPatchService
04-10 11:58:22.522 11594-12604/? W/ProcStatsManager: No process com.nd.tinker:patch/10115 for service com.tencent.tinker.lib.service.TinkerPatchService$InnerService
04-10 11:58:23.669 2043-2043/? I/ActivityManager: Killing 12496:com.nd.tinker/u0a115 (adj 900): remove task
04-10 11:58:26.266 2043-6821/? I/ActivityManager: Force stopping com.nd.tinker appid=10115 user=0: from pid 11594
04-10 11:58:28.600 2043-4889/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nd.tinker/.MainActivity (has extras)} from uid 10039 on display 0
04-10 11:58:28.660 2043-6821/? I/ActivityManager: Start proc 12619:com.nd.tinker/u0a115 for activity com.nd.tinker/.MainActivity
04-10 11:58:28.716 12619-12619/? W/System: ClassLoader referenced unknown path: /data/app/com.nd.tinker-1/lib/arm
04-10 11:58:28.731 12619-12619/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.nd.tinker/tinker/patch.info
04-10 11:58:28.732 12619-12619/? D/Tinker.DefaultAppLike: onBaseContextAttached:
04-10 11:58:28.743 12619-12619/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.nd.tinker/tinker
04-10 11:58:28.744 12619-12619/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3
04-10 11:58:28.744 12619-12619/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
04-10 11:58:28.744 12619-12619/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/com.nd.tinker/tinker, code:-3, cost:2
04-10 11:58:28.744 12619-12619/? W/Tinker.Tinker: tinker load fail!
04-10 11:58:28.745 12619-12619/? D/Tinker.DefaultAppLike: onCreate
04-10 11:58:28.824 2043-4890/? I/ActivityManager: Start proc 12636:com.nd.tinker:patch/u0a115 for service com.nd.tinker/com.tencent.tinker.lib.service.TinkerPatchService
04-10 11:58:28.829 12619-12619/? W/System.err:     at com.nd.tinker.MainActivity.i(MainActivity.java:84)
04-10 11:58:28.829 12619-12619/? W/System.err:     at com.nd.tinker.MainActivity.onCreate(MainActivity.java:41)
04-10 11:58:28.865 12636-12636/? W/System: ClassLoader referenced unknown path: /data/app/com.nd.tinker-1/lib/arm
04-10 11:58:28.881 12636-12636/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.nd.tinker/tinker/patch.info
04-10 11:58:28.882 12636-12636/? D/Tinker.DefaultAppLike: onBaseContextAttached:
04-10 11:58:28.888 12636-12636/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.nd.tinker/tinker
04-10 11:58:28.889 12636-12636/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3
04-10 11:58:28.889 12636-12636/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
04-10 11:58:28.890 12636-12636/? I/Tinker.DefaultLoadReporter: patch load result, path:/data/user/0/com.nd.tinker/tinker, code:-3, cost:2
04-10 11:58:28.890 12636-12636/? W/Tinker.Tinker: tinker load fail!
04-10 11:58:28.890 12636-12636/? D/Tinker.DefaultAppLike: onCreate
04-10 11:58:28.897 12636-12651/? I/Tinker.DefaultPatchReporter: patchReporter: patch service start
04-10 11:58:28.898 12636-12651/? I/Tinker.TinkerPatchService: try to increase patch process priority
04-10 11:58:28.899 2043-2062/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.nd.tinker/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
04-10 11:58:28.907 2043-2043/? V/NotificationService: pkg=com.nd.tinker canInterrupt=false intercept=true
04-10 11:58:28.908 2043-2062/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.nd.tinker/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
04-10 11:58:28.934 2043-2043/? V/NotificationService: pkg=com.nd.tinker canInterrupt=false intercept=true
04-10 11:58:28.954 2043-2084/? I/ActivityManager: Displayed com.nd.tinker/.MainActivity: +308ms
04-10 11:58:28.964 12636-12651/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:dexDiffMd5:4607ba2a782c4e4e7389775e0a062b62
04-10 11:58:28.965 12636-12651/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.nd.tinker/tinker/patch-4607ba2a
04-10 11:58:28.969 12636-12651/? W/Tinker.UpgradePatch: UpgradePatch after /storage/emulated/0/patch_signed_7zip.apk size:4009, /data/user/0/com.nd.tinker/tinker/patch-4607ba2a/patch-4607ba2a.apk size:4009
04-10 11:58:28.970 12636-12651/? W/Tinker.DexDiffPatchInternal: small patch info is not exists, it's ok now.
04-10 11:58:28.971 12636-12651/? E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 160047910, got crc: 4280117666
04-10 11:58:28.971 12636-12651/? I/Tinker.DefaultPatchReporter: patchReporter: file extract fail type:dex_art, path:/data/user/0/com.nd.tinker/tinker/patch-4607ba2a/patch-4607ba2a.apk, extractTo:/data/user/0/com.nd.tinker/tinker/patch-4607ba2a/dex/classes.dex.jar, filename:classes.dex, isUpgrade:true
04-10 11:58:28.972 12636-12651/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.nd.tinker/tinker/patch-4607ba2a/patch-4607ba2a.apk
04-10 11:58:28.972 12636-12651/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.nd.tinker/tinker/patch-4607ba2a/dex
04-10 11:58:28.974 12636-12651/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.nd.tinker/tinker/patch-4607ba2a
04-10 11:58:28.974 12636-12651/? W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
04-10 11:58:28.974 12636-12651/? I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:5, isUpgradePatch:true
04-10 11:58:28.975 12636-12651/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
04-10 11:58:28.975 12636-12651/? I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:false, cost:77, isUpgrade:true
04-10 11:58:28.981 2043-2056/? W/ActivityManager: Unable to start service Intent { cmp=com.nd.tinker/.service.TinkDService (has extras) } U=0: not found
04-10 11:58:29.140 2043-2084/? I/WindowManager: Destroying surface Surface(name=Starting com.nd.tinker) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704 
04-10 11:59:11.262 12619-12619/? D/Tinker.DefaultAppLike: onTrimMemory level:20
04-10 11:59:17.902 11594-11611/? W/ProcStatsManager: No process com.nd.tinker:patch/10115 for service com.tencent.tinker.lib.service.TinkerPatchService
04-10 11:59:17.903 11594-11611/? W/ProcStatsManager: No process com.nd.tinker:patch/10115 for service com.tencent.tinker.lib.service.TinkerPatchService$InnerService
04-10 12:01:17.576 13282-13282/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.qiyi.video/tinker
04-10 12:01:17.576 13282-13282/? W/Tinker.TinkerLoader: sdk info not exists
04-10 12:01:17.580 13282-13282/? D/Tinker.DefaultAppLike: onBaseContextAttached:
04-10 12:01:17.602 13282-13282/? D/Tinker.DefaultAppLike: onCreate

**Comment by RichesJson** [comment]
我不混淆的话是正常的

**Comment by shwenzhang** [comment]
04-10 11:58:28.971 12636-12651/? E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 160047910, got crc: 4280117666

基准包的crc改变了

**Comment by shwenzhang** [comment]
而且你这个明显是1.7.5版本。。

**Comment by RichesJson** [comment]
classpath 'com.android.tools.build:gradle:2.3.0'
        classpath ('com.tencent.tinker:tinker-patch-gradle-plugin:1.7.7')

**Comment by RichesJson** [comment]
对了，crc是什么意思？
