### ISSUE TITLE
Unsupported major.minor version 52.0 issue

### ISSUE THREAD

**Issue by com360** [Tencent/tinker#439]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user1/tinker/tinker-android/tinker-android-lib/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':tinker-android:tinker-android-lib'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/LibraryPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by shwenzhang** [comment]
java 版本，请按照格式提问。

**Comment by com360** [comment]
运行时jdk版本和android 插件编译时jdk版本不一致导致的。
改成jdk8就可以了。
