### ISSUE TITLE
关于文档

### ISSUE THREAD

**Issue by it90msart** [Tencent/tinker#44]
能出一个中文版的详细文档，包括做升级包的和整个流程。一直在关注，就是声音大雨点下，希望可以照顾下国内的开发者。英文版也行，关键就是要详细点

**Comment by CSnowStack** [comment]
Wiki里有啊,很详细的啊

**Comment by it90msart** [comment]
我上去找查询失败，腾讯在bugly网上会给出跟wiki一样的文档嘛

**Comment by Drizzlezhang** [comment]
Wiki已经很详细了

**Comment by shwenzhang** [comment]
https://github.com/Tencent/tinker/wiki，不太清楚你这样提问的意思是什么？文档在wiki上面已经很详细了

**Comment by dotcink** [comment]
觉得文档没有必要用英文，因为热修复几乎只在中国有市场，看看 issues 就知道了。
