### ISSUE TITLE
vivo热补丁，出现java.lang.IllegalArgumentException: No view found for id 0x7f0f0f77 

### ISSUE THREAD

**Issue by iceAnson** [Tencent/tinker#442]
异常类型：app运行时异常

手机型号：vivo系列机型

手机系统版本：Android 4.4.4，Android5.0

tinker版本：1.7.7

gradle版本：2.14.1

系统：如:Mac

发布热补丁后线上bugly统计出现如下日志：实际上rl_setting_ringtone_layout这个id从代码上看并不会在NewsHomeFragment里出现。

具体调用栈如下。
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.lingan.seeyou/com.lingan.seeyou.ui.activity.main.SeeyouActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f0f0f77 (com.lingan.seeyou:id/rl_setting_ringtone_layout) for fragment NewsHomeFragment{28aa0db8 #0 id=0x7f0f0f77 /newshome}
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
3 ......
4 java.lang.IllegalArgumentException:No view found for id 0x7f0f0f77 (com.lingan.seeyou:id/rl_setting_ringtone_layout) for fragment NewsHomeFragment{28aa0db8 #0 id=0x7f0f0f77 /newshome}
5 android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1102)
6 android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1290)
7 android.support.v4.app.BackStackRecord.run(TbsSdkJava:801)
8 android.support.v4.app.FragmentManagerImpl.execPendingActions(TbsSdkJava:1677)
9 android.support.v4.app.FragmentController.execPendingActions(TbsSdkJava:388)
10 android.support.v4.app.FragmentActivity.onStart(TbsSdkJava:604)
11 com.meiyou.sdk.ui.base.BaseActivity.void onStart()(TbsSdkJava:39)
12 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1230)
13 android.app.Activity.performStart(Activity.java:5991)
14 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2431)
15 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2530)
16 android.app.ActivityThread.access$800(ActivityThread.java:171)
17 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425)
18 android.os.Handler.dispatchMessage(Handler.java:111)
19 android.os.Looper.loop(Looper.java:194)
20 android.app.ActivityThread.main(ActivityThread.java:5560)
21 java.lang.reflect.Method.invoke(Native Method)
22 java.lang.reflect.Method.invoke(Method.java:372)
23 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:965)
24 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)

**Comment by shwenzhang** [comment]
是否使用了applyresourceID编译

**Comment by iceAnson** [comment]
并没有，肯定是有使用applyResourceMapping，但是applyresourceID是什么我不清楚，没有集成，但是生成补丁包的时候，并没有出现资源的差异。

**Comment by iceAnson** [comment]
@shwenzhang

**Comment by shwenzhang** [comment]
1. 是否使用了bugly一键接入 2. 是否必现，是否只出现在某些品牌的手机

**Comment by iceAnson** [comment]
1、不是使用bugly一键接入，是手动接入的；
2、只出现在vivo手机上边，其余手机没有必现；无法必现，上线后bugly crash report的

**Comment by shwenzhang** [comment]
请尝试在sample 上复现
