### ISSUE TITLE
大神这个兼容Java1.8吗  

### ISSUE THREAD

**Issue by Darksiderlyd** [Tencent/tinker#443]
使用这个 
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

然后开启
jackOptions{
            enabled = true
        }
就会报错，Application类不能在运行时生成，所以找不到这个类
![image](https://cloud.githubusercontent.com/assets/20541921/25111651/d4ce8808-241e-11e7-9799-e06628b58de1.png)
![image](https://cloud.githubusercontent.com/assets/20541921/25111667/e78446fe-241e-11e7-8aaf-a0a6eb5f02cf.png)

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/25112793/1fc2a3ce-2426-11e7-9f05-f3a7f0520957.png)
支持
