### ISSUE TITLE
一加3T，补丁还原概率性load失败

### ISSUE THREAD

**Issue by icespring** [Tencent/tinker#445]
由于是线上正式版本，关闭了tinker的log，因此无法提供详细log，补丁还原成功，使用锁屏后生效的策略。重新打开app出现黑屏，此问题在还原的时候有一定概率性，有时候可以生效，但是有时候就会出现失败，失败都是在补丁load时。系统版本7.1.1，手机是一加3T，tinker版本是1.7.3

**另外问一下，在系统ANR无法主动crash的情况下，如何保证有问题的机型不再load patch？**

04-18 20:48:42.010 20717-20717/? A/DEBUG: Build fingerprint: 'OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/02072026:user/release-keys'
04-18 20:48:42.010 20717-20717/? A/DEBUG: Revision: '0'
04-18 20:48:42.010 20717-20717/? A/DEBUG: ABI: 'arm'
04-18 20:48:42.010 20717-20717/? A/DEBUG: pid: 20651, tid: 20651, name: 
04-18 20:48:42.010 20717-20717/? A/DEBUG: signal 6 (SIGABRT), code 0 (SI_USER), fault addr --------
04-18 20:48:42.012 20717-20717/? A/DEBUG: Abort message: 'art/runtime/thread.cc:1657] No pending exception expected: java.lang.ArrayIndexOutOfBoundsException: length=1159; index=6327'
04-18 20:48:42.012 20717-20717/? A/DEBUG:     r0 00000000  r1 000050ab  r2 00000006  r3 00000008
04-18 20:48:42.012 20717-20717/? A/DEBUG:     r4 e9a2f58c  r5 00000006  r6 e9a2f534  r7 0000010c
04-18 20:48:42.012 20717-20717/? A/DEBUG:     r8 00000000  r9 0000000a  sl 000004b0  fp e6e05400
04-18 20:48:42.012 20717-20717/? A/DEBUG:     ip 0000000b  sp ffe27b20  lr e9115517  pc e9117d98  cpsr 200d0010
04-18 20:48:42.019 20717-20717/? A/DEBUG: backtrace:
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #00 pc 00049d98  /system/lib/libc.so (tgkill+12)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #01 pc 00047513  /system/lib/libc.so (pthread_kill+34)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #02 pc 0001d765  /system/lib/libc.so (raise+10)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #03 pc 000192a1  /system/lib/libc.so (__libc_android_abort+34)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #04 pc 00017308  /system/lib/libc.so (abort+4)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #05 pc 0031a719  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+328)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #06 pc 000b5285  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+1132)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #07 pc 00333d77  /system/lib/libart.so (_ZNK3art6Thread24AssertNoPendingExceptionEv+602)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #08 pc 000e519d  /system/lib/libart.so (_ZN3art11ClassLinker9FindClassEPNS_6ThreadEPKcNS_6HandleINS_6mirror11ClassLoaderEEE+28)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #09 pc 000d292d  /system/lib/libart.so (_ZN3art11ClassLinker11ResolveTypeERKNS_7DexFileEtNS_6HandleINS_6mirror8DexCacheEEENS4_INS5_11ClassLoaderEEE+132)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #10 pc 000b1253  /system/lib/libart.so (_ZN3art11ClassLinker11ResolveTypeEtPNS_9ArtMethodE+198)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #11 pc 0039b92d  /system/lib/libart.so (artAllocObjectFromCodeRosAlloc+84)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #12 pc 000adfd9  /system/lib/libart.so (art_quick_alloc_object_rosalloc+136)
04-18 20:48:42.021 20717-20717/? A/DEBUG:     #13 pc 00b2f411  /data/app/com.baidu.input-1/oat/arm/base.odex (offset 0x9c6000)
04-18 20:48:44.146 20788-20788/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

**Comment by shwenzhang** [comment]
1.7.3 依然使用分平台合成，在N以上出现问题的概率比较大。

**Comment by icespring** [comment]
那1.7.7版本是否会有该问题呢？如果出现了黑屏现象，如何保证用户能正常重启？
