### ISSUE TITLE
End Of Central Directory signature not found

### ISSUE THREAD

**Issue by andrewhunter0** [Tencent/tinker#448]
机型：Lenovo A7600-m_5.0.2_21_LENOVO 720x1280
Gradle版本：2.2.3
Tinker版本：1.7.7
错误类型：UpgradePatch.tryPatch，补丁合成异常
日志：
java.util.zip.ZipException: End Of Central Directory signature not found java.util.zip.ZipFile.readCentralDir(ZipFile.java:401)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:163)\n\tat java.util.zip.ZipFile.<init>(ZipFile.java:130) com.tencent.tinker.lib.b.c.a(BsDiffPatchInternal.java:97) com.tencent.tinker.lib.b.c.a(BsDiffPatchInternal.java:67)
com.tencent.tinker.lib.b.c.a(BsDiffPatchInternal.java:58) com.tencent.tinker.lib.b.g.a(UpgradePatch.java:137) com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) android.os.Handler.dispatchMessage(Handler.java:111)
 android.os.Looper.loop(Looper.java:194)
 android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shwenzhang** [comment]
这个应该是文件大小出问题了
