### ISSUE TITLE
小米7.0 百度加固 合成补丁成功  但重启不了app

### ISSUE THREAD

**Issue by gd-se7en** [Tencent/tinker#455]
异常类型：app运行时异常

手机型号：小米5

手机系统版本：Android 7.0

tinker版本：1.7.8

gradle版本：2.2.3

是否使用热更新SDK： 否

系统：Windows

堆栈/日志：

合成补丁：
I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                                 PatchResult: 
                                                                                 isSuccess:true
                                                                                 rawPatchFilePath:/storage/emulated/0/xxx/log/patch_signed_7zip.apk
                                                                                 costTime:4269
I/Process: Sending signal. PID: 31880 SIG: 9
I/Tinker.SampleResultService: save delete raw patch file
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/xxx/log/patch_signed_7zip.apk
I/Tinker.SampleResultService: tinker wait screen to restart process

重启app：
W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true

D/Tinker.TinkerInternals: same fingerprint:Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAACNEB:user/release-keys

I/PatchInfo: rewritePatchInfoFile file path:/data/user/0/xxx/tinker/patch.info , oldVer:dda83e6b336f3e86e73d8ccb8aed84f1, newVer:dda83e6b336f3e86e73d8ccb8aed84f1, fingerprint:Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAACNEB:user/release-keys, oatDir:odex

W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_xxx count:1

I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx-1/base.apk", zip file "/data/data/xxx/.1/classes.jar", zip file "/data/data/xxx/.2/classes.jar", zip file "/data/data/xxx/.3/classes.jar"],nativeLibraryDirectories=[/data/app/xxx-1/lib/arm, /system/fake-libs, /data/app/xxx-1/base.apk!/lib/armeabi, /data/data/xxx/lib, /data/data/xxx/lib, /data/data/xxx/lib, /system/lib, /vendor/lib]]]

I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/xxx/tinker/patch-dda83e6b/odex, dex size:2

W/System: ClassLoader referenced unknown path: 

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 3571 (xxx)
                                                         
                                                         [ 04-25 17:05:37.713   462:  462 W/         ]
                                                         debuggerd: handling request: pid=3571 uid=10248 gid=10248 tid=3571

**Comment by shwenzhang** [comment]
try with 1.7.10
