### ISSUE TITLE
ignoreWarning is false

### ISSUE THREAD

**Issue by fengchuiyeluo** [Tencent/tinker#456]
异常类型：Warning:ignoreWarning is false, but resources.arsc is changed, you should use applyResourceMapping mode to build the new apk, otherwise, it may be crash at some times

tinker版本：如:1.7.8

![1](https://cloud.githubusercontent.com/assets/13350298/25380979/be96cc0a-29e4-11e7-940a-f1e778547765.png)
![2](https://cloud.githubusercontent.com/assets/13350298/25380981/bfa7126c-29e4-11e7-9e2b-acab0061e1e0.png)
设置了R.txt以及ignoreWarning=false，但还是会一直提示

**Comment by shwenzhang** [comment]
编译相关要详细的编译日志

**Comment by fengchuiyeluo** [comment]
场景：一个测试project下有多个module，其中有两个都是添加了tinker自己写的测试实例，写第二个module时多次测试会有很大概率发生该错误，不是配置的问题，解决：新起了一个project，将之前写的代码完全照搬，不会有该提示，原因未知，不知道是不是读取错乱的问题
