### ISSUE TITLE
Android7.1 出现ClassCastException异常，需要热修复类的内部类A，与该内部类A实现的接口使用了不同的classloader加载。

### ISSUE THREAD

**Issue by TmacZhang** [Tencent/tinker#457]
异常类型：app运行时异常

手机型号：某品牌 P1

手机系统版本：如:Android 7.1.1

tinker版本：如:1.7.7

gradle版本：无

是否使用热更新SDK：TinkerPatch SDK

系统：如:Windows

堆栈/日志：
04-26 17:39:15.912 D/AndroidRuntime( 5903): Shutting down VM
04-26 17:39:15.912 W/System.err( 5903): java.lang.ClassCastException: com.android.contacts.activities.PeopleActivity$3 cannot be cast to com.android.dialer.dialpad.util.B
04-26 17:39:15.912 W/System.err( 5903): 	at com.android.contacts.ContactsApplication$2.onServiceConnected(ContactsApplication.java:270)
04-26 17:39:15.912 W/System.err( 5903): 	at com.android.dialer.dialpad.util.X.onServiceConnected(X.java:252)
04-26 17:39:15.912 W/System.err( 5903): 	at com.cootek.smartdialer_oem_module.sdk.AIDLUtil$1.onServiceConnected(Unknown)
04-26 17:39:15.912 W/System.err( 5903): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
04-26 17:39:15.912 W/System.err( 5903): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
04-26 17:39:15.912 W/System.err( 5903): 	at android.os.Handler.handleCallback(Handler.java:751)
04-26 17:39:15.912 W/System.err( 5903): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-26 17:39:15.912 W/System.err( 5903): 	at android.os.Looper.loop(Looper.java:154)
04-26 17:39:15.912 W/System.err( 5903): 	at android.app.ActivityThread.main(ActivityThread.java:6144)
04-26 17:39:15.912 W/System.err( 5903): 	at java.lang.reflect.Method.invoke(Native Method)
04-26 17:39:15.912 W/System.err( 5903): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-26 17:39:15.912 W/System.err( 5903): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
这里是对com.android.contacts.activities.PeopleActivity进行热修复，补丁加载成功。
其中com.android.contacts.activities.PeopleActivity$3实现了com.android.dialer.dialpad.util.B这个接口，应该是同样类型。
后来打印出classloader信息
com.android.contacts.activities.PeopleActivity$3||com.tencent.tinker.loader.AndroidNClassLoader
com.android.dialer.dialpad.util.B||dalvik.system.PathClassLoader
发现他们两个加载时候，使用了不同的classloader。
备注：在AndroidM上没有此问题。

**Comment by shwenzhang** [comment]
com.android.dialer.dialpad.util.B 为什么会用patchclassloader加载，是否使用了 tinkerPatch 的一键接入

**Comment by 1032689332** [comment]
@shwenzhang  
引入tinker方式不是 tinkerPatch 的一键接入。
因为是Android系统apk，采取编译方式生成的，采取方式是直接将tinker1.7.7的jar包导入到工程进行编译，同时，按照sample中例子修改的代码。
com.android.dialer.dialpad.util.B 为什么会用patchclassloader加载：这个我也没有弄明白，AndroidN热修复成功后，都应该是通过AndroidNClassLoader吧。

**Comment by shwenzhang** [comment]
com.android.dialer.dialpad.util.B 是系统的类吗？你们自定义的Application是否符合规范，这个应该是你们接入的问题

**Comment by TmacZhang** [comment]
@shwenzhang 
com.android.dialer.dialpad.util.B ：是我们应用里的类。
你们自定义的Application是否符合规范：我是按照sample中Application来修改的，应该是没有问题吧。然后在AndroidM上是没有问题的。

**Comment by shwenzhang** [comment]
1. application怎么写的
2. dex loader pattern 怎么写的
3. applicationLike的自定义类怎么写的

**Comment by shwenzhang** [comment]
? 找到原因了？

**Comment by TmacZhang** [comment]
@shwenzhang 
tinker_config.xml中的dex loader pattern中的loader的application还写的是sample中的类名，改为我自己应用的类名就可以了。多谢。
不过还是要请教一个问题：Android N以后ART采用了混合编译方式，Tinker的解决方案是，完全废弃掉PathClassloader，而采用AndroidNClassLoader来加载后续的所有类。我现在修改后，热修复成功了，但是发现com.android.dialer.dialpad.util.B这个aidl接口的ClassLoader仍然是dalvik.system.PathClassLoader。

**Comment by shwenzhang** [comment]
如果还是PathClassloader肯定cast会异常，某品牌 P1 是一加的手机吗？

**Comment by TmacZhang** [comment]
@shwenzhang 
不是一加手机，一个小品牌，就不说名字了。
本身我们应用的Application会通过PathClassloader加载，然后Application中一个静态方法使用到了com.android.dialer.dialpad.util.B类，这个B类也应该是在PathClassloader加载吧。

**Comment by shwenzhang** [comment]
那就是你们是自定义了Application，这种情况在文档已经说得很清楚，需要把引用的类也加入loader类！！！

**Comment by TmacZhang** [comment]
这种情况在文档已经说得很清楚，需要把引用的类也加入loader类：
这些类是不能修复的，还在原来的dex中，不在补丁中。但是这并没有改变加载这些类的ClassLoader啊。
