### ISSUE TITLE
tinker支持加固，是360加固还是聚安全还是指什么加固，机型有要求吗，支持部分机型还是所有？

### ISSUE THREAD

**Issue by CJEEP** [Tencent/tinker#459]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：tinker支持加固，是360加固还是聚安全还是指什么加固，机型有要求吗，支持部分机型还是所有？
手机型号：

手机系统版本：

tinker版本：

gradle版本：

**Comment by shwenzhang** [comment]
see wiki
