### ISSUE TITLE
华为7.0补丁生效后启动崩溃,抛出VerifyError

### ISSUE THREAD

**Issue by yinte12** [Tencent/tinker#462]
异常类型：app运行时异常，只有华为7.0手机有这个现象，其他手机和系统均正常

手机型号：华为7.0手机，
![image](https://cloud.githubusercontent.com/assets/7117487/25693786/d2851118-30dd-11e7-8f37-16f48ea91ce5.png)

手机系统版本：7.0

tinker版本：如:1.7.7

gradle版本：如:2.2.3

是否使用热更新SDK： 否

堆栈/日志：
![image](https://cloud.githubusercontent.com/assets/7117487/25693830/164a9a3a-30de-11e7-9d0c-943ee8e6ba25.png)

涉及的代码：
```java
   public void setupGraph() {
        mAppComponent = DaggerApplicationComponent.builder()
                .coreApplicationComponent(mCoreComponent)
                .applicationModule(new ApplicationModule(this))
                .build();
        mAppComponent.inject(this);
    }
```
1. 以上代码中this 参数类型是XKApplicationLike。
2. dh.d&a 对应的mapping类是DaggerApplicationComponent$Builder

**Comment by shwenzhang** [comment]
clean patch的时候没有去kill掉所有的process
