### ISSUE TITLE
签名验证失败

### ISSUE THREAD

**Issue by OneHomeKey** [Tencent/tinker#463]
异常类型：签名验证失败

手机型号：努比亚Z7MAX(NX505J)

手机系统版本：Android 7.1.1

tinker版本：1.7.9

gradle版本：2.14.1

是否使用热更新SDK： 否

系统：windows

问题描述：使用公司签名文件签名，会出现签名验证不通过，换个签名此问题不复现
                   签名文件来源沃通
签名工具：android studio 2.3.1
![image](https://cloud.githubusercontent.com/assets/28393217/25705748/f121c610-3110-11e7-8b54-dcaed4a09961.png)

**Comment by shwenzhang** [comment]
这个需要自己debug,因为我们这边不能复现。请确认签名是否一致
