### ISSUE TITLE
提供一份Tinker打补丁的流程图解

### ISSUE THREAD

**Issue by shishuo365** [Tencent/tinker#464]
鉴于每个Tinker的入门者，都希望了解Tinker打补丁的流程；
所以个人制作了一份Tinker打补丁的流程图解；
主要包括以下几种情况：
1.相同版本的APP打一次补丁的过程
2.相同版本的APP打多次补丁的过程
3.不同版本的APP升级的过程

评论里没办法添加图片，只好粘贴上链接地址 [Tinker打补丁流程图解](https://blog.ibaoger.com/2017/05/06/tinker-patch-flow/index.html)

**Comment by shwenzhang** [comment]
thanks
