### ISSUE TITLE
360加固后 android 7.1.1版本安装成功补丁但无法重新启动APP

### ISSUE THREAD

**Issue by skygzs** [Tencent/tinker#467]
异常类型：app运行时异常

手机型号：一加3

手机系统版本：Android 7.1.1

tinker版本：如:1.7.9

gradle版本：如:2.13

是否使用热更新SDK：无

系统：Windows

堆栈/日志：  

I/Tinker.ParallelDex: All dexes are optimized successfully, cost: 194 ms.
I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:208
W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
I/Tinker.DexDiffPatchInternal: dex count: 2, final wait time: 12
I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: changed_classes.dex.dex, size 29312
I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: test.dex.dex, size 17024
I/Tinker.DexDiffPatchInternal: check dex optimizer file format: changed_classes.dex.dex, size 29312
I/Tinker.DexDiffPatchInternal: check dex optimizer file format: test.dex.dex, size 17024
I/PatchInfo: rewritePatchInfoFile file path:/data/user/0/cn.dreamtowns.jints/tinker/patch.info , oldVer:, newVer:589a9e1e584be3e7a59604557fbb50a1, fingerprint:OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/04101830:user/release-keys, oatDir:odex
W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/cn.dreamtowns.jints/cache/patch/patchapk.zip, success: true, cost: 261
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/cn.dreamtowns.jints/tinker_temp/temp.apk
I/Tinker.SampleResultService: SampleResultService receive result: 
        PatchResult: 
        isSuccess:true
        rawPatchFilePath:/data/user/0/cn.dreamtowns.jints/cache/patch/patchapk.zip
        costTime:261
W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/cn.dreamtowns.jints/cache/patch/patchapk.zip
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/cn.dreamtowns.jints/cache/patch/patchapk.zip
I/Tinker.SampleResultService: tinker wait screen to restart process
W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
D/Tinker.TinkerInternals: same fingerprint:OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/04101830:user/release-keys
I/PatchInfo: rewritePatchInfoFile file path:/data/user/0/cn.dreamtowns.jints/tinker/patch.info , oldVer:589a9e1e584be3e7a59604557fbb50a1, newVer:589a9e1e584be3e7a59604557fbb50a1, fingerprint:OnePlus/OnePlus3/OnePlus3:7.1.1/NMF26F/04101830:user/release-keys, oatDir:odex
W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_cn.dreamtowns.jints count:1
I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[dex file "/data/app/cn.dreamtowns.jints-1/base.apk", zip file "/data/app/cn.dreamtowns.jints-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.dreamtowns.jints-1/lib/arm64, /data/app/cn.dreamtowns.jints-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]]
I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/cn.dreamtowns.jints/tinker/patch-589a9e1e/odex, dex size:2
E/Tinker.NClassLoader: load TinkerTestAndroidNClassLoader fail, try to fixDexElementsForProtectedApp
I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/cn.dreamtowns.jints/tinker/patch-589a9e1e/dex/changed_classes.dex.jar", zip file "/data/user/0/cn.dreamtowns.jints/tinker/patch-589a9e1e/dex/test.dex.jar", zip file "/data/app/cn.dreamtowns.jints-1/base.apk", zip file "/data/app/cn.dreamtowns.jints-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.dreamtowns.jints-1/lib/arm64, /data/app/cn.dreamtowns.jints-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]], dex size:2
W/Tinker.ClassLoaderAdder: checkDexInstall result:true
I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
I/Tinker.SamplePatchListener: application maxMemory:256
W/Tinker.Tinker: tinker patch directory: /data/user/0/cn.dreamtowns.jints/tinker
W/System.err:     at com.tencent.tinker.lib.service.TinkerPatchService.<clinit>(TbsSdkJava)
W/System.err:     at com.tencent.tinker.lib.service.TinkerPatchService.setPatchProcessor(TbsSdkJava:69)
W/System.err:     at com.tencent.tinker.lib.d.a.install(TbsSdkJava:142)
W/System.err:     at com.tencent.tinker.lib.d.c.install(TbsSdkJava:71)
W/System.err:     at cn.dreamtowns.jints.tinker.d.b.installTinker(TbsSdkJava:99)
W/System.err:     at cn.dreamtowns.jints.tinker.SampleApplicationLike.onBaseContextAttached(TbsSdkJava:76)
W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TbsSdkJava:132)
W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TbsSdkJava:146)
E/Tinker.SampleUncaughtExHandler: uncaughtException:No implementation found for void com.qihoo.util.StubApp4032527229.interface11(int) (tried Java_com_qihoo_util_StubApp4032527229_interface11 and Java_com_qihoo_util_StubApp4032527229_interface11__I)
E/Tinker.SampleUncaughtExHandler: tinker has fast crash 1 times
E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.UnsatisfiedLinkError: No implementation found for void com.qihoo.util.StubApp4032527229.interface11(int) (tried Java_com_qihoo_util_StubApp4032527229_interface11 and Java_com_qihoo_util_StubApp4032527229_interface11__I)
        at com.qihoo.util.StubApp4032527229.interface11(Native Method)
        at cn.jpush.android.service.PushService.<clinit>(Unknown Source)
        at java.lang.Class.newInstance(Native Method)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3312)
        at android.app.ActivityThread.-wrap5(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6322)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by tomystang** [comment]
试试升级一下360加固工具？最新版的360加固工具是能正常支持的。

**Comment by skygzs** [comment]
从360官网刚下载的加固工具，只有7.0以上不支持，其他的都正常。

**Comment by tomystang** [comment]
http://jiagu.360.cn/protection?s=1
试试用这个链接在线加固？我昨天又用demo试了一次，应该是没问题的。

**Comment by skygzs** [comment]
试了，一样的，还是 锁屏之后 kill掉线程，然后直接报错，然后再启动 APP就 启动不了了

**Comment by shwenzhang** [comment]
@skygzs  用dev分支尝试一下是否已经解决

**Comment by shwenzhang** [comment]
try with 1.7.10
