### ISSUE TITLE
Android 7.0系统上360加固补丁异常

### ISSUE THREAD

**Issue by awen2007** [Tencent/tinker#468]
异常类型：app运行时异常

手机型号：华为Mate9、华为Mate8、华为P9 plus、三星 S7 Edge(韩版)、诺基亚 6、摩托罗拉 MOTO Z

手机系统版本：Android 7.0

tinker版本：1.7.9(tinkerpatch 1.1.6)

gradle版本：2.3.1

是否使用热更新SDK：TinkerPatch SDK

系统：win10

java.lang.UnsatisfiedLinkError: No implementation found for void com.qihoo.util.StubApp2718358134.interface11(int) (tried Java_com_qihoo_util_StubApp2718358134_interface11 and Java_com_qihoo_util_StubApp2718358134_interface11__I)
	at com.qihoo.util.StubApp2718358134.interface11(Native Method)
	at com.tencent.tinker.lib.service.TinkerPatchService.<clinit>(TinkerPatchService.java)
	at com.tencent.tinker.lib.service.TinkerPatchService.setPatchProcessor(TinkerPatchService.java:69)
	at com.tencent.tinker.lib.tinker.Tinker.install(Tinker.java:142)
	at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:71)
	at com.tinkerpatch.sdk.TinkerPatch.<init>(SourceFile:102)
	at com.tinkerpatch.sdk.TinkerPatch$Builder.build(SourceFile:577)
	at com.tinkerpatch.sdk.TinkerPatch.init(SourceFile:126)
	at cn.mastercom.portal.MyApplication.initTinkerPatch(MyApplication.java:45)
	at cn.mastercom.portal.MyApplication.onCreate(MyApplication.java:31)
	at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113)
	at com.qihoo.util.StubApp2718358134.onCreate(StubApp2718358134.java:84)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

WARN18:11:20.68113910System.err at com.tinkerpatch.sdk.tinker.a.a.uncaughtException(SourceFile:58)
WARN18:11:17.66913910System.err at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113)
WARN18:11:17.66913910System.err at cn.mastercom.portal.MyApplication.initTinkerPatch(MyApplication.java:45)
WARN18:11:17.66913910System.err at com.tinkerpatch.sdk.TinkerPatch.init(SourceFile:126)
WARN18:11:17.66913910System.err at com.tinkerpatch.sdk.TinkerPatch$Builder.build(SourceFile:577)
WARN18:11:17.66913910System.err at com.tinkerpatch.sdk.TinkerPatch.(SourceFile:102)
WARN18:11:17.66913910System.err at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:71)
WARN18:11:17.66913910System.err at com.tencent.tinker.lib.tinker.Tinker.install(Tinker.java:142)
WARN18:11:17.66913910System.err at com.tencent.tinker.lib.service.TinkerPatchService.setPatchProcessor(TinkerPatchService.java:69)
WARN18:11:17.66913910System.err at com.tencent.tinker.lib.service.TinkerPatchService.(TinkerPatchService.java)
ERROR18:11:17.66913910Tinker.SampleUncaughtExHandlertinker has fast crash more than 3, we just clean patch!
INFO18:11:17.66913910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch.info
INFO18:11:17.66913910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5
INFO18:11:17.66913910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/odex
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/odex/changed_classes.dex.dex
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/odex/test.dex.dex
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/test.dex.jar
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/changed_classes.dex.jar
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/patch-ac620bd5.apk
INFO18:11:17.66813910Tinker.PatchFileUtilsafeDeleteFile, try to delete path: /data/user/0/cn.mastercom.portal.gd/tinker/info.lock
ERROR18:11:17.66813910Tinker.TinkerApplicationHelperit is not safety to clean patch when tinker is loaded, you should kill all your process after clean!
WARN18:11:17.66413910Tinker.Tinkertinker patch directory: /data/user/0/cn.mastercom.portal.gd/tinker
INFO18:11:17.65813910Tinker.ServerClientinstallTinkerServer, debug value: false, appVersion: 1.6.7, appKey: 654b934c5bd886e8
ERROR18:11:17.65813910ActivityThreadFailed to find provider info for com.tinker.debug.debugprovider
INFO18:11:17.65513910Tinker.VersionInforeadVersionInfo file path:/data/user/0/cn.mastercom.portal.gd/tinker_server/654b934c5bd886e8_version.info, appVersion: 1.6.7, uuid:a29aae2b-6ea2-495d-985e-6fd2259ed2dc, abi:armeabi, patchVersion:1, patchMd5:ac620bd5ec4979a6416662016584e776, grayValue:7, crashTimes:2, retryTimes:0, applySuccess:0
INFO18:11:17.35713910Tinker.ReflectAppreplaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
INFO18:11:17.34213910Tinker.ClassLoaderAdderafter loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/changed_classes.dex.jar", zip file "/data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/test.dex.jar", zip file "/data/app/cn.mastercom.portal.gd-1/base.apk", zip file "/data/app/cn.mastercom.portal.gd-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.mastercom.portal.gd-1/lib/arm, /system/fake-libs, /data/app/cn.mastercom.portal.gd-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]], dex size:2
ERROR18:11:17.33113910Tinker.NClassLoaderload TinkerTestAndroidNClassLoader fail, try to fixDexElementsForProtectedApp
INFO18:11:17.32713910Tinker.ClassLoaderAdderinstallDexes dexOptDir: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/odex, dex size:2
WARN18:11:17.31213910Tinker.TinkerLoadertinker safe mode preferName:tinker_own_config_cn.mastercom.portal.gd count:1
WARN18:11:16.56913849System.err at com.tinkerpatch.sdk.tinker.a.a.uncaughtException(SourceFile:58)
WARN18:11:13.55013849System.err at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113)
WARN18:11:13.55013849System.err at cn.mastercom.portal.MyApplication.initTinkerPatch(MyApplication.java:45)
WARN18:11:13.55013849System.err at com.tinkerpatch.sdk.TinkerPatch.init(SourceFile:126)
WARN18:11:13.55013849System.err at com.tinkerpatch.sdk.TinkerPatch$Builder.build(SourceFile:577)
WARN18:11:13.55013849System.err at com.tinkerpatch.sdk.TinkerPatch.(SourceFile:102)
WARN18:11:13.55013849System.err at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:71)
WARN18:11:13.55013849System.err at com.tencent.tinker.lib.tinker.Tinker.install(Tinker.java:142)
WARN18:11:13.55013849System.err at com.tencent.tinker.lib.service.TinkerPatchService.setPatchProcessor(TinkerPatchService.java:69)
WARN18:11:13.55013849System.err at com.tencent.tinker.lib.service.TinkerPatchService.(TinkerPatchService.java)
ERROR18:11:13.55013849Tinker.SampleUncaughtExHandlertinker has fast crash 2 times
INFO18:11:13.54913849Tinker.VersionInfoupdateVersionInfo file path:/data/user/0/cn.mastercom.portal.gd/tinker_server/654b934c5bd886e8_version.info, appVersion: 1.6.7, uuid:a29aae2b-6ea2-495d-985e-6fd2259ed2dc, abi:armeabi, patchVersion:1, patchMd5:ac620bd5ec4979a6416662016584e776, grayValue:7, crashTimes:2, retryTimes:0, applySuccess:0
WARN18:11:13.54613849Tinker.Tinkertinker patch directory: /data/user/0/cn.mastercom.portal.gd/tinker
INFO18:11:13.54013849Tinker.ServerClientinstallTinkerServer, debug value: false, appVersion: 1.6.7, appKey: 654b934c5bd886e8
ERROR18:11:13.53913849ActivityThreadFailed to find provider info for com.tinker.debug.debugprovider
INFO18:11:13.53613849Tinker.VersionInforeadVersionInfo file path:/data/user/0/cn.mastercom.portal.gd/tinker_server/654b934c5bd886e8_version.info, appVersion: 1.6.7, uuid:a29aae2b-6ea2-495d-985e-6fd2259ed2dc, abi:armeabi, patchVersion:1, patchMd5:ac620bd5ec4979a6416662016584e776, grayValue:7, crashTimes:1, retryTimes:0, applySuccess:0
INFO18:11:13.22413849Tinker.ReflectAppreplaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
INFO18:11:13.20913849Tinker.ClassLoaderAdderafter loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/changed_classes.dex.jar", zip file "/data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/test.dex.jar", zip file "/data/app/cn.mastercom.portal.gd-1/base.apk", zip file "/data/app/cn.mastercom.portal.gd-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.mastercom.portal.gd-1/lib/arm, /system/fake-libs, /data/app/cn.mastercom.portal.gd-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]], dex size:2
ERROR18:11:13.19513849Tinker.NClassLoaderload TinkerTestAndroidNClassLoader fail, try to fixDexElementsForProtectedApp
INFO18:11:13.19013849Tinker.ClassLoaderAdderinstallDexes dexOptDir: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/odex, dex size:2
WARN18:11:13.17713849Tinker.TinkerLoadertinker safe mode preferName:tinker_own_config_cn.mastercom.portal.gd count:1
WARN18:11:12.39113795System.err at com.tinkerpatch.sdk.tinker.a.a.uncaughtException(SourceFile:58)
WARN18:11:09.37913795System.err at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113)
WARN18:11:09.37913795System.err at cn.mastercom.portal.MyApplication.initTinkerPatch(MyApplication.java:45)
WARN18:11:09.37913795System.err at com.tinkerpatch.sdk.TinkerPatch.init(SourceFile:126)
WARN18:11:09.37913795System.err at com.tinkerpatch.sdk.TinkerPatch$Builder.build(SourceFile:577)
WARN18:11:09.37913795System.err at com.tinkerpatch.sdk.TinkerPatch.(SourceFile:102)
WARN18:11:09.37913795System.err at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:71)
WARN18:11:09.37913795System.err at com.tencent.tinker.lib.tinker.Tinker.install(Tinker.java:142)
WARN18:11:09.37913795System.err at com.tencent.tinker.lib.service.TinkerPatchService.setPatchProcessor(TinkerPatchService.java:69)
WARN18:11:09.37913795System.err at com.tencent.tinker.lib.service.TinkerPatchService.(TinkerPatchService.java)
ERROR18:11:09.37813795Tinker.SampleUncaughtExHandlertinker has fast crash 1 times
INFO18:11:09.37813795Tinker.VersionInfoupdateVersionInfo file path:/data/user/0/cn.mastercom.portal.gd/tinker_server/654b934c5bd886e8_version.info, appVersion: 1.6.7, uuid:a29aae2b-6ea2-495d-985e-6fd2259ed2dc, abi:armeabi, patchVersion:1, patchMd5:ac620bd5ec4979a6416662016584e776, grayValue:7, crashTimes:1, retryTimes:0, applySuccess:0
WARN18:11:09.37513795Tinker.Tinkertinker patch directory: /data/user/0/cn.mastercom.portal.gd/tinker
INFO18:11:09.36913795Tinker.ServerClientinstallTinkerServer, debug value: false, appVersion: 1.6.7, appKey: 654b934c5bd886e8
ERROR18:11:09.36913795ActivityThreadFailed to find provider info for com.tinker.debug.debugprovider
INFO18:11:09.36613795Tinker.VersionInforeadVersionInfo file path:/data/user/0/cn.mastercom.portal.gd/tinker_server/654b934c5bd886e8_version.info, appVersion: 1.6.7, uuid:a29aae2b-6ea2-495d-985e-6fd2259ed2dc, abi:armeabi, patchVersion:1, patchMd5:ac620bd5ec4979a6416662016584e776, grayValue:7, crashTimes:0, retryTimes:0, applySuccess:0
INFO18:11:09.07013795Tinker.ReflectAppreplaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
INFO18:11:09.05613795Tinker.ClassLoaderAdderafter loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/changed_classes.dex.jar", zip file "/data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/dex/test.dex.jar", zip file "/data/app/cn.mastercom.portal.gd-1/base.apk", zip file "/data/app/cn.mastercom.portal.gd-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.mastercom.portal.gd-1/lib/arm, /system/fake-libs, /data/app/cn.mastercom.portal.gd-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]], dex size:2
ERROR18:11:09.04513795Tinker.NClassLoaderload TinkerTestAndroidNClassLoader fail, try to fixDexElementsForProtectedApp
INFO18:11:09.04013795Tinker.ClassLoaderAdderinstallDexes dexOptDir: /data/user/0/cn.mastercom.portal.gd/tinker/patch-ac620bd5/odex, dex size:2
WARN18:11:09.02613795Tinker.TinkerLoadertinker safe mode preferName:tinker_own_config_cn.mastercom.portal.gd count:1
INFO18:11:09.02413795PatchInforewritePatchInfoFile file path:/data/user/0/cn.mastercom.portal.gd/tinker/patch.info , oldVer:ac620bd5ec4979a6416662016584e776, newVer:ac620bd5ec4979a6416662016584e776, fingerprint:HUAWEI/NXT-DL00/HWNXT:7.0/HUAWEINXT-DL00/C17B577:user/release-keys, oatDir:odex

**Comment by tomystang** [comment]
试试升级一下360加固工具？最新版360加固应该是没问题的。

**Comment by awen2007** [comment]
已經是最新版本（1.5.1.5）的加固工具了

**Comment by tomystang** [comment]
http://jiagu.360.cn/protection?s=1
试试用这个链接在线加固？我昨天又用demo试了一次，应该是没问题的。

**Comment by shwenzhang** [comment]
@awen2007 用dev分支尝试一下是否已经解决

**Comment by shwenzhang** [comment]
try with 1.7.10

**Comment by ganmingzhu** [comment]
@shwenzhang 刚试了1.7.11  360加固补丁合成失败，不加固的情况下正常

**Comment by ganmingzhu** [comment]
@awen2007 请问一下，你解决了这个加固异常的问题了吗
