### ISSUE TITLE
merge_mapping.py的效果不正确

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#469]
异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：1.7.9

gradle版本：无关

是否使用热更新SDK：否

系统：windows

bug描述：
old-mapping中的映射com.baidu.location.b.a -> ryxq.nm:
current-mapping中的映射com.baidu.location.b -> ryxq.jf:
按理说new-mapping中的结果应该是 -> ryxq.nm:
但实际上却是 -> ryxq.jf:
if current_data.raw_line.split("->")[0] == current_data.raw_line.split("->")[1][:-1]:
我分析了一下脚本,==似乎应该改成!=
有没有其他逻辑错误，麻烦也review一下：）

**Comment by FengJianjian** [comment]
确实有这样的问题 修复已经提交
[pull_request](https://github.com/Tencent/tinker/pull/474)

**Comment by shwenzhang** [comment]
merged
