### ISSUE TITLE
tinkerPatchDebug生成不了补丁包

### ISSUE THREAD

**Issue by yql86** [Tencent/tinker#47]
Sample工程，调用tinkerPatchDebug， 执行app: tinkerPatchDebug 20分钟都没有结束，无法生成补丁包。请问是什么原因，需要做什么修改。

**Comment by yql86** [comment]
环境： androidStudio 2.2
            gradle plugin version 2.2.0
            gradle version 2.14.1

刚开始运行工程，报tinkerId not set , 后面我设置为：            
            tinkerId = '560'
            tinkerOldApkPath = "${bakPath}/app-debug-0927-11-44-48.apk"
执行：tinkerPatchDebug  其他文件，文件夹都有app-debug,thinker_result,log.txt等， 但是就是没生成：patch_signed_7zip.apk。。 任务一直卡在app:tinkerPatchDebug。

**Comment by shwenzhang** [comment]
tinkerPatchDebug包括编译assembleDebug以及tinkerPatch两部分，你首先要确认当前是卡在哪一步？可以将Tinker编译的日志贴出来

**Comment by yql86** [comment]
嗯，下面是log.txt的日志：
Gen classes.dex patch file:/Users/yangqinlin/Downloads/tinker-master-2/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tinker_result/classes.dex, size:749, md5:0614c9a9df8c63aaa58d20965d9b8343
Verifying if patched new dex is logically the same as original new dex: app-debug/classes.dex ...

Gen classes.dex for dalvik full dex file:/Users/yangqinlin/Downloads/tinker-master-2/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tempPatchedDexes/full/classes.dex, size:2076708, md5:a5816619e72f131b4a110f36f3cb52fe
Start generating small patch info file...

Gen classes.dex for art small dex file:/Users/yangqinlin/Downloads/tinker-master-2/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tempPatchedDexes/small/classes.dex, size:5500, md5:090e96bdf5f1897d7efa27f2408e7bae
DexDecoder:write meta file data: classes.dex,,a5816619e72f131b4a110f36f3cb52fe,090e96bdf5f1897d7efa27f2408e7bae,0614c9a9df8c63aaa58d20965d9b8343,280758497,jar

Add test install result dex: /Users/yangqinlin/Downloads/tinker-master-2/tinker-sample-android/app/build/outputs/tinkerPatch/debug/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
Warning:ignoreWarning is false, but resources.arsc is changed, you should use applyResourceMapping mode to build the new apk, otherwise, it may be crash at some times

**Comment by yql86** [comment]
把ignoreWarning设置为true就好了，为什么sample工程false会有问题，告诉我：resources.arsc is changed

**Comment by shwenzhang** [comment]
看日志，因为resources.arsc改变了，如果不使用applyMappingResource，很容易出问题[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by yql86** [comment]
好的，谢谢！

**Comment by icespring** [comment]
但是目前sample工程中，确实没有新增资源，为什么会提示resources.arsc改变了？

**Comment by shwenzhang** [comment]
可以看看resources.arsc究竟改了什么，这里要明确oldapk也需要在我们这边编译

**Comment by mrfluency** [comment]
同问 确实资源增删改

**Comment by shwenzhang** [comment]
代码没有增删改具体编译结果不一定没有改变，用apktool看一下不就可以？这里强调资源要保证两个包都是apply 了tinker的plugin编译出来的

**Comment by shwenzhang** [comment]
这里明确的一点是，tinker每次编译都会生成public.xml，使得所有资源的属性都变成public。所以这里需要确定两个编译都是有使用tinker的gradle plugin

**Comment by doublechina** [comment]
tinker-sample-android 怎么运行不起来，找不到 运行的主项目

**Comment by shwenzhang** [comment]
@yql86 ， please try with 1.7.0
