### ISSUE TITLE
NullPointerException:android.content.res.ResourcesImpl.getDisplayAdjustments()' on a null object reference

### ISSUE THREAD

**Issue by ouyangfeng** [Tencent/tinker#472]
异常类型：app运行时异常

手机型号：坚果pro  100%出现

手机系统版本：Android 7.1.1

tinker版本： compile 'com.tencent.bugly:crashreport_upgrade:latest.release@aar'
                     compile 'com.tencent.bugly:nativecrashreport:latest.release@aar'

gradle版本：如:2.3.0

使用热更新SDK：  Bugly SDK

系统：如:Mac

堆栈/日志：
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.hundun.yanxishe/com.hundun.yanxishe.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.content.res.ResourcesImpl.getDisplayAdjustments()' on a null object reference
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2813)
3 ......
4 Caused by:
5 java.lang.NullPointerException:Attempt to invoke virtual method 'android.view.DisplayAdjustments android.content.res.ResourcesImpl.getDisplayAdjustments()' on a null object reference
6 android.content.res.Resources.getDisplayAdjustments(Resources.java:1896)
7 android.app.ContextImpl.<init>(ContextImpl.java:2091)
8 android.app.ContextImpl.createActivityContext(ContextImpl.java:2005)
9 android.app.ActivityThread.createBaseContextForActivity(ActivityThread.java:2830)
10 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
11 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
12 android.app.ActivityThread.-wrap12(ActivityThread.java)
13 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
14 android.os.Handler.dispatchMessage(Handler.java:102)
15 android.os.Looper.loop(Looper.java:159)
16 android.app.ActivityThread.main(ActivityThread.java:6306)
17 java.lang.reflect.Method.invoke(Native Method)
18 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
19 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

猜测看了7.0源码定位到这里获取到的Resource对象为NULL
请问是不是由于ClassLoader的问题
ActivityThread:
 Resources getTopLevelResources(String resDir, String[] splitResDirs, String[] overlayDirs,
            String[] libDirs, int displayId, LoadedApk pkgInfo) {
        return mResourcesManager.getResources(null, resDir, splitResDirs, overlayDirs, libDirs,
                displayId, null, pkgInfo.getCompatibilityInfo(), pkgInfo.getClassLoader());
    }
ResourcesManager:
 public @Nullable Resources getResources(@Nullable IBinder activityToken,
            @Nullable String resDir,
            @Nullable String[] splitResDirs,
            @Nullable String[] overlayDirs,
            @Nullable String[] libDirs,
            int displayId,
            @Nullable Configuration overrideConfig,
            @NonNull CompatibilityInfo compatInfo,
            @Nullable ClassLoader classLoader) {
        try {
            Trace.traceBegin(Trace.TRACE_TAG_RESOURCES, "ResourcesManager#getResources");
            final ResourcesKey key = new ResourcesKey(
                    resDir,
                    splitResDirs,
                    overlayDirs,
                    libDirs,
                    displayId,
                    overrideConfig != null ? new Configuration(overrideConfig) : null, // Copy
                    compatInfo);
            classLoader = classLoader != null ? classLoader : ClassLoader.getSystemClassLoader();
            return getOrCreateResources(activityToken, key, classLoader);
        } finally {
            Trace.traceEnd(Trace.TRACE_TAG_RESOURCES);
        }
    }

**Comment by tomystang** [comment]
用tinker自带的demo可以复现吗？

**Comment by ouyangfeng** [comment]
没有这款手机，没试过，bugly显示 坚果pro 100%出现

**Comment by ouyangfeng** [comment]
05-15 17:41:16.401 15179 15179 E ResourcesManager: failed to add asset path /data/user/0/com.hundun.yanxishe/tinker/patch-553850ac/res/resources.apk

**Comment by ouyangfeng** [comment]
这是过滤tinker的日志
05-15 17:41:16.239 15179 15179 I art : at java.lang.Class com.tencent.tinker.loader.AndroidNClassLoader.findClass(java.lang.String) (BUGLY:180)
105-15 17:41:16.239 15179 15179 I art : at void com.tencent.tinker.loader.app.TinkerApplication.onCreate() (BUGLY:173)
205-15 17:41:16.239 15179 15179 I art : at java.lang.Class com.tencent.tinker.loader.AndroidNClassLoader.findClass(java.lang.String) (BUGLY:180)
305-15 17:41:16.239 15179 15179 I art : at java.lang.Class com.tencent.tinker.loader.AndroidNClassLoader.findClass(java.lang.String) (BUGLY:180)
405-15 17:41:16.239 15179 15179 I art : at void com.tencent.tinker.loader.app.TinkerApplication.onCreate() (BUGLY:173)
505-15 17:41:16.401 15179 15179 W asset : Asset path /data/user/0/com.hundun.yanxishe/tinker/patch-553850ac/res/resources.apk is neither a directory nor file (type=1).
605-15 17:41:16.401 15179 15179 E ResourcesManager: failed to add asset path /data/user/0/com.hundun.yanxishe/tinker/patch-553850ac/res/resources.apk

**Comment by StevenWT** [comment]
同样的问题。tinker的日志:
4505-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: tinker load exception com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkResInstall failed
4605-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.TinkerResourcePatcher.monkeyPatchExistingResources(TinkerResourcePatcher.java:225)
4705-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.TinkerResourceLoader.loadTinkerResources(TinkerResourceLoader.java:64)
4805-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:237)
4905-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
5005-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at java.lang.reflect.Method.invoke(Native Method)
5105-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:161)
5205-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:130)
5305-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
5405-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.Application.attach(Application.java:196)
5505-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
5605-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.Instrumentation.newApplication(Instrumentation.java:993)
5705-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
5805-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5553)
5905-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.ActivityThread.-wrap2(ActivityThread.java)
6005-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
6105-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.os.Handler.dispatchMessage(Handler.java:102)
6205-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.os.Looper.loop(Looper.java:159)
6305-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at android.app.ActivityThread.main(ActivityThread.java:6306)
6405-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at java.lang.reflect.Method.invoke(Native Method)
6505-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
6605-15 22:17:15.157 12415 12415 E Tinker.DefaultLoadReporter: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by shwenzhang** [comment]
这个问题在Tinker的Sample是否可以重现？

**Comment by StevenWT** [comment]
没有这个测试机所以无法复现。捂脸。

**Comment by ouyangfeng** [comment]
已经买测试机了估计明天到 😂

**Comment by shwenzhang** [comment]
what's new here?

**Comment by Trumeet** [comment]
我也遇到了这个问题，但是自己测试没有出现，看错误统计发现的。设备是锤子，ROM 7.1.1

**Comment by shwenzhang** [comment]
坚果Pro rom的问题，已经找到方法fix

**Comment by shwenzhang** [comment]
try with 1.7.10

**Comment by ZhuangCuicui** [comment]
怎么解决的？

**Comment by jcygittub** [comment]
有什么好的方法解决吗

**Comment by shwenzhang** [comment]
自己看commit啊
