### ISSUE TITLE
Execution failed for task ':app:tinkerPatchRelease'. > Could not get unknown property 'taskName' for task ':app:tinkerPatchRelease' of type com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.

### ISSUE THREAD

**Issue by lcs353732057** [Tencent/tinker#473]
Execution failed for task ':app:tinkerPatchRelease'.
> Could not get unknown property 'taskName' for task ':app:tinkerPatchRelease' of type com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.

**Comment by shwenzhang** [comment]
use new version
