### ISSUE TITLE
TinkerRuntimeException: Tinker Exception:patch dex extract failed (Size mismatch on inflated file: 9467954 vs 9466036)

### ISSUE THREAD

**Issue by cheweili** [Tencent/tinker#476]
异常类型：app运行时异常

手机型号：3007OPPO

手机系统版本：Android 4.4.4

tinker版本：1.7.9

gradle版本：2.1.2

是否使用热更新SDK： 没有使用

系统：windows

堆栈/日志：
这个错误是线上的, 只有加载补丁失败的错误日志 :
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch dex extract failed (Size mismatch on inflated file: 9467954 vs 9466036).
由于公司这边没有这个机型, 无法复现这个失败现象, 暂时无法提供更详细的失败日志
还有两个小建议 :
  1.  是否可以简化对捕捉错误日志的方式描述 , 我尝试了有一些回调函数补丁加载完成后(结果是失败)并不会触发(例如PatchReporter中的onPatchResult) 
  2 .  后来我只在TinkerResultService捕捉加载补丁的结果信息,但经过多次测试和线上的失败日志收集发现 :错误信息有较大概率为null(PatchResult.e) , 这样无法分析失败原因,是否可以优化一下

**Comment by cheweili** [comment]
异常类型：app运行时异常

手机型号：3007OPPO

手机系统版本：Android 4.4.4

tinker版本：1.7.9

gradle版本：2.1.2

是否使用热更新SDK： 没有使用

系统：windows

堆栈/日志：
这个错误是线上的, 只有加载补丁失败的错误日志 :
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch dex extract failed (Size mismatch on inflated file: 9467954 vs 9466036).

**Comment by cheweili** [comment]
由于公司这边没有这个机型, 无法复现这个失败现象, 暂时无法提供更详细的失败日志

**Comment by shwenzhang** [comment]
这个就是解压失败，有可能是空间或者读写的问题。tinker会自动的去做重试的，如果没有出现exception，那个字段的确就是空的

**Comment by cheweili** [comment]
解压补丁失败吗?空间或读问题是因为手机存储空间不足?修复失败没出现exception,这种情况要怎样分析错误原因呢?

**Comment by gogeer** [comment]
这个是解压失败；一般都是解压时候ZipFile会对数据做长度的校验；如果不一致就会出现这个问题；这个原因一般有可能是压缩包的问题；如果采用ZipInputStream会穿 crc Mismatch异常。可能在mac和iOS设备上解压没有这个问题；但是在android设备上会出现。一般重新生成一下压缩包可以解决这个问题

**Comment by BrokerXu** [comment]
我也遇到这个问题，你们是怎么解决的
