### ISSUE TITLE
华为CHE-TL00Honor加载补丁失败

### ISSUE THREAD

**Issue by cheweili** [Tencent/tinker#477]
#异常类型：app运行时异常

手机型号：华为CHE-TL00Honor

手机系统版本：Android 5.0.2
 

tinker版本：1.7.9

gradle版本：2.1.2

是否使用热更新SDK： 没有使用,公司自己管理补丁

系统：windows

这个错误是线上的, 只有加载补丁失败的错误日志 :
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch resource extract failed (Tinker Exception:patch resource extract failed (/data/data/com.womai/tinker/patch-40a8e5a7/res/resources.arsc: open failed: ENOENT (No such file or  #directory)).).
由于公司这边没有这个机型, 无法复现这个失败现象, 暂时无法提供更详细的失败日志

**Comment by shwenzhang** [comment]
这个应该也是读写的问题
