### ISSUE TITLE
是否支持 多个补丁包 合并为一个补丁包

### ISSUE THREAD

**Issue by milk1990** [Tencent/tinker#479]
两个补丁包分别修复两个不一样的问题，是否有工具能够直接合成两个补丁包？？方便补丁包的管理，下发补丁包时，就可以下发一个补丁包（二合一）。

**Comment by simpleton** [comment]
@milk1990 tinker是线性覆盖的，只需遵循git flow的hotfix流程来做patch即可。不存在分别修复了2个不同的问题。

**Comment by milk1990** [comment]
那基于设备下发的不同补丁包怎么做补丁包的管理呢？假设这是现有设备的补丁情况：
设备1：bug1,bug2,bug3
设备2：bug1
设备3：bug2,bug3
如果现在发现一个版本bug4，所有的设备都存在这个问题，那发布的补丁应该是每个设备是不一样的，
设备1补丁内容：bug1,bug2,bug3，bug4
设备2补丁内容：bug1，bug4
设备3补丁内容：bug2,bug3，bug4
这个管理成本将是巨大的，有没有更好的方式解决这个问题

**Comment by shwenzhang** [comment]
其实不需要按设备把，代码里面兼容所有设备即可
