### ISSUE TITLE
Tinker更新成功后在华为Mate9，三星S7等Android7.0以上系统重新打开app闪退

### ISSUE THREAD

**Issue by LittleRoyal** [Tencent/tinker#481]
异常类型：app运行时异常/编译异常

手机型号：华为Mate9

手机系统版本：Android7.0

tinker版本：1.7.8

gradle版本：3.3

是否使用热更新SDK： 否

系统：windows 10

堆栈/日志：
![image](https://cloud.githubusercontent.com/assets/7865415/26245395/7f7c5e50-3cc6-11e7-99d7-da30487a11f9.png)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe8e665e8 in tid 10255 (.nfdaily.nfplus)
05-21 14:50:08.598 10360-10360/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-21 14:50:08.598 10360-10360/? A/DEBUG: Build fingerprint: 'google/angler/angler:7.1.1/NPF10C/3347772:user/release-keys'
05-21 14:50:08.598 10360-10360/? A/DEBUG: Revision: '0'
05-21 14:50:08.598 10360-10360/? A/DEBUG: ABI: 'arm64'
05-21 14:50:08.598 10360-10360/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe8e665e8
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x0   0000000012de4270  x1   0000000000000004  x2   0000000000000005  x3   000000000000000a
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x4   000000006f638960  x5   00000078d3baf124  x6   00000078d3baf128  x7   0000000000000000
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x8   0000000000000000  x9   0000007fe4c0c998  x10  00000078f0356404  x11  ffffffffffdcb8dc
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x12  00000078d3b437ff  x13  fffffffffffffff8  x14  0011897dc4000000  x15  003b9aca00000000
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x16  000000006f636fd0  x17  00000078f3fe1010  x18  0000000000000000  x19  00000078f0695a00
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x20  00000000e8e665e8  x21  0000000012e1f1c0  x22  0000000000000005  x23  00000000e8e665e8
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x24  0000000000000000  x25  0000000012f322e0  x26  0000000012e60d50  x27  0000000000000007
05-21 14:50:08.598 10360-10360/? A/DEBUG:     x28  0000000012e18900  x29  0000000012cc6920  x30  0000000070ab46f4
05-21 14:50:08.598 10360-10360/? A/DEBUG:     sp   0000007fe4c0bbc0  pc   0000000070ab4728  pstate 0000000080000000
05-21 14:50:08.710 10360-10360/? A/DEBUG:     #00 pc 000000000070a728  /system/framework/arm64/boot.oat (offset 0x54d000) (java.util.ArrayList.add+116)
05-21 14:50:08.710 10360-10360/? A/DEBUG:     #01 pc 00000000008a670c  /data/data/xxx/tinker/patch-6f130a57/odex/classes.dex.dex (offset 0xd8f000)
05-21 14:50:53.209 7557-7559/? E/QC-QMI: qmi_client [7557] 7f: failed to locate client data
05-21 14:50:53.212 3810-3810/? E/QC-QMI: qmuxd: RX on fd=13 returned error=0 errno[11:Try again]
05-21 14:50:53.214 3810-3810/? E/QC-QMI: QMUX qmux_client_id=7f not found in qmux client list, unable to remove
05-21 14:50:53.261 10623-10623/? E/Diag_Lib:  Diag_LSM_Init: Failed to open handle to diag driver, error = 13

**Comment by shwenzhang** [comment]
集成问题，需要将application的所有逻辑都放在applicationLike中

**Comment by nb312** [comment]
我的小米手机也会出现加载成功后奔溃现象 并且所有逻辑都放在application中

**Comment by nb312** [comment]
@shwenzhang

**Comment by diaoling90** [comment]
我的这边也是，所有application的所有逻辑都放在applicationLike中的，但是华为小米的好多机型都崩溃的@shwenzhang
