### ISSUE TITLE
联想S898t+Lenovo加载补丁失败

### ISSUE THREAD

**Issue by cheweili** [Tencent/tinker#483]
异常类型：app运行时异常

手机型号：联想S898t+Lenovo

手机系统版本：Android 4.2.2

tinker版本：1.7.9

gradle版本: 2.1.2

是否使用热更新SDK： 否

系统：windows

堆栈/日志：
这个错误是线上的, 只有加载补丁失败的错误日志 :
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch dex extract failed (write failed: ENOSPC (No space left on device)).
由于公司这边没有这个机型, 无法复现这个失败现象, 暂时无法提供更详细的失败日志, 这个是运存不足还是内存不足?

**Comment by shwenzhang** [comment]
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch dex extract failed (write failed: ENOSPC (No space left on device)).
