### ISSUE TITLE
关于library aar包的问题

### ISSUE THREAD

**Issue by yangwuan55** [Tencent/tinker#488]
问一个问题，如果app中依赖了一个library项目的aar包，那么aar包的代码支持热更新么？

**Comment by shwenzhang** [comment]
支持，具体看文档

**Comment by ruijun** [comment]
@yangwuan55  aar要怎样做patch文件呢？

**Comment by yangwuan55** [comment]
@ruijun 没有什么特殊的 反正是对比apk之间的差别 操作一样

**Comment by ruijun** [comment]
@yangwuan55  aar project属于'com.android.library'，需要怎样构建出apk来进行对比呢？要改成'com.android.application'？
