### ISSUE TITLE
你好　编译的时候总是提示“tinkerId is not set!!!”　请问是什么原因？

### ISSUE THREAD

**Issue by Leiluojun** [Tencent/tinker#49]

**Comment by shwenzhang** [comment]
#11 , 请先查询是否已有相关的issue

**Comment by Leiluojun** [comment]
我是直接导入的sample示例module

**Comment by shwenzhang** [comment]
[Tinker 常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by yanhaogoogle** [comment]
我一开始也是这样的，后来我查看了我的git环境变量都配置成功了发现还是出现这样的错误，我后来就把app/build.gradle里面的gitRev()方法里面gitRev的值改成了我git的版本号，虽然可以编译成功，但不知道有什么影响没有。

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/18860204/d0019844-84ad-11e6-9421-cd12fccee432.png)

**Comment by shwenzhang** [comment]
#11

**Comment by xueleitt** [comment]
这几个方法都试过了 手动提交一次 环境配置正确，还是一直有这个错误

**Comment by huigll** [comment]
获取tinkerId  是通过gitSha 方法,这个方法是根据git的命令git rev-parse --short HEAD 来获取. 如果项目没有git库是有问题.你可以直接把返回值改成"testTinkerId" 来简单测试.

**Comment by zhanggao** [comment]
mac  tinkerId is not set 解决办法：
1、更新Xcode后可能提示tinkerId is not set，把Xcode打开 点下同意就好了。
2、1不行试下2，重装git。
