### ISSUE TITLE
Tinker 补丁撤回是否无法保证回滚到上一个补丁版本

### ISSUE THREAD

**Issue by milk1990** [Tencent/tinker#492]
查看源码中，发现清除某个版本的补丁文件代码：  
  /**
     * clean the patch version files, such as tinker/patch-641e634c
     *
     * @param versionName
     */
    public void cleanPatchByVersion(String versionName) {
        if (patchDirectory == null || versionName == null) {
            return;
        }
        String path = patchDirectory.getAbsolutePath() + "/" + versionName;
        SharePatchFileUtil.deleteDir(path);
    }
对应的配置文件并没有修改，是否会造成下次启动的时候补丁加载不上，无法回滚到上一个补丁版本？

**Comment by shwenzhang** [comment]
你可以通过自定义接口保留上一个版本补丁，清除是为了节省空间
