### ISSUE TITLE
非issue，art上内联问题

### ISSUE THREAD

**Issue by cryforyou** [Tencent/tinker#494]
你好，最新代码针对o有个改动，在NClassloader拷贝构造了一份新的dexpathlist，这边意外发现这个改动似乎解决了n以后的内联问题，这边用原来分平台版本在小米7.0上加载补丁后强行全量odex编译会出现崩溃，但是加了这个改动后发现无法复现了，是不是这个改动和内联有关，间接解决了内联问题，因为我对系统源码还不熟悉，所以反馈下给这边，看看是不是有联系，如果这样能解决内联，那么small dex方案还可以用了吧？

**Comment by shwenzhang** [comment]
这个是1.7.10的一个bug, duplicate class,导致自动回退到解释模式。通过这种方式强制回退到解释模式，small dex是没问题的。但是7.0之前也一样有内联的问题
