### ISSUE TITLE
PatchResult.patchVersion没有赋值却用来判断是否退出程序

### ISSUE THREAD

**Issue by daemon369** [Tencent/tinker#496]
在`DefaultTinkerResultService`中使用`checkIfNeedKill`函数来判断是否退出程序，其中用到`PatchResult.patchVersion`来判断，但是并没有找到赋值的地方：

    public boolean checkIfNeedKill(PatchResult result) {
        Tinker tinker = Tinker.with(getApplicationContext());
        if (tinker.isTinkerLoaded()) {
            TinkerLoadResult tinkerLoadResult = tinker.getTinkerLoadResultIfPresent();
            if (tinkerLoadResult != null) {
                String currentVersion = tinkerLoadResult.currentVersion;
                if (result.patchVersion != null && result.patchVersion.equals(currentVersion)) {
                    return false;
                }
            }
        }
        return true;
    }

tinker版本：1.7.11

**Comment by shwenzhang** [comment]
应该是写在upgradePatch里面了，之前merge的时候似乎不小心删了

**Comment by nEdAy** [comment]
mark

**Comment by shwenzhang** [comment]
dev已经提交了。

**Comment by XinYiWorld** [comment]
这个bug什么时候更新一个版本啊？

**Comment by shwenzhang** [comment]
try with 1.8.0
