### ISSUE TITLE
TinkerPatchPlugin 不支持 ABI分包

### ISSUE THREAD

**Issue by coolmu** [Tencent/tinker#498]
异常类型：app编译异常

描述：现在的问题是gradle脚本只能向universal包中Minifest文件中写入tinkerid的meta data，无法向x86等包写入tinkerId。

手机型号

手机系统版本

tinker版本：1.7.7

gradle版本：2.3.0

是否使用热更新SDK： Bugly SDK

系统：如:Mac

堆栈/日志：

**Comment by shwenzhang** [comment]
abi 分包可以通过gradle脚本自己适配
