### ISSUE TITLE
自定义SampleApplication时，文档的路径描述有误

### ISSUE THREAD

**Issue by anzyhui** [Tencent/tinker#50]
自定义SampleApplication，在构造中需要加：
`public SampleApplication(){
        super(
                //tinkerFlags, which types is supported
                //dex only, library only, all support
                ShareConstants.TINKER_ENABLE_ALL,
                // This is passed as a string so the shell application does not
                // have a binary dependency on your ApplicationLifeCycle class.
                "tinker.sample.android.SampleApplicationLike");
    }`
参数二路径应该为：tinker.sample.android.app.SampleApplicationLike

**Comment by tomystang** [comment]
多谢反馈，已修正。
