### ISSUE TITLE
Tinker版本1.7.11，使用360加固后无法加载补丁

### ISSUE THREAD

**Issue by ganmingzhu** [Tencent/tinker#502]
Hi，我看了两个相同的Issue，于是尝试了最新版的Tinker，但在使用360加固后依然无法加载补丁，未加固的情况加载补丁正常。
测试机型：360 N4 ，Android6.0； moto G，Android4.4；
加固地址：http://jiagu.360.cn/protection?s=1

错误日志如下：
05-28 01:49:32.315 25962-25962/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
05-28 01:49:32.317 25962-25962/? D/Tinker.DefaultAppLike: onBaseContextAttached:
05-28 01:49:32.318 25962-25962/? I/MultiDex: VM with version 2.1.0 has multidex support
05-28 01:49:32.319 25962-25962/? I/MultiDex: install
05-28 01:49:32.319 25962-25962/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
05-28 01:49:32.323 25962-25962/? I/Tinker.SamplePatchListener: application maxMemory:512
05-28 01:49:32.325 25962-25962/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.youhu.zen.demo1/tinker
05-28 01:49:32.327 25962-25962/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
05-28 01:49:32.329 25962-25962/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.youhu.zen.demo1:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
05-28 01:49:32.329 25962-25962/? W/Tinker.TinkerLoadResult: tinker is disable, just return
05-28 01:49:32.329 25962-25962/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.youhu.zen.demo1/tinker, code: -1, cost: 4ms
05-28 01:49:32.329 25962-25962/? W/Tinker.Tinker: tinker load fail!
05-28 01:49:32.330 25962-25962/? D/Tinker.DefaultAppLike: onCreate
05-28 01:49:32.330 25962-25962/? D/ActivityThread: BIND_APPLICATION handled : 0 / AppBindData{appInfo=ApplicationInfo{e5f647 com.youhu.zen.demo1}}
05-28 01:49:32.331 25962-25962/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@4ddae74 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=com.youhu.zen.demo1 intent=null}
05-28 01:49:32.332 25962-25962/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@4ddae74 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=com.youhu.zen.demo1 intent=null}
05-28 01:49:32.332 25962-25962/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService@f42cf9d, flags=0, startId=1
05-28 01:49:32.332 25962-25962/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@4ddae74 startId=1 args=Intent { cmp=com.youhu.zen.demo1/com.tencent.tinker.lib.service.TinkerPatchService (has extras) }}
05-28 01:49:32.332 25962-25979/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
05-28 01:49:32.333 25962-25962/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
05-28 01:49:32.336 25962-25979/? W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.youhu.zen.demo1/files/patch_signed_7zip.apk to /data/user/0/com.youhu.zen.demo1/tinker_temp/temp.apk
05-28 01:49:32.343 25962-25979/? I/Tinker.TinkerPatchService: try to increase patch process priority
05-28 01:49:32.348 1138-1754/? I/BGCONTROL: server pass non-stopped app: Intent { cmp=com.youhu.zen.demo1/com.tencent.tinker.lib.service.TinkerPatchService$InnerService }
05-28 01:49:32.351 25962-25962/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@62ccc6c className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=com.youhu.zen.demo1 intent=null}
05-28 01:49:32.352 25962-25962/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@62ccc6c className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=com.youhu.zen.demo1 intent=null}
05-28 01:49:32.352 1138-1138/? D/AppOps: noteOperation: reject #1 for code 11 (11) uid 10230 package com.youhu.zen.demo1
05-28 01:49:32.352 25962-25962/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@ee42235, flags=0, startId=1
05-28 01:49:32.352 1138-1138/? E/NotificationService: Suppressing notification from package com.youhu.zen.demo1 by user request.
05-28 01:49:32.352 25962-25962/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@62ccc6c startId=1 args=Intent { cmp=com.youhu.zen.demo1/com.tencent.tinker.lib.service.TinkerPatchService$InnerService }}
05-28 01:49:32.352 25962-25962/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@ee42235
05-28 01:49:32.352 25962-25962/? D/ActivityThread: SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@62ccc6c
05-28 01:49:32.357 1138-1138/? D/AppOps: noteOperation: reject #1 for code 11 (11) uid 10230 package com.youhu.zen.demo1
05-28 01:49:32.357 1138-1138/? E/NotificationService: Suppressing notification from package com.youhu.zen.demo1 by user request.
05-28 01:49:32.378 25962-25979/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:fe57ed2b66287d24c690a769d3598081
05-28 01:49:32.379 25962-25979/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.youhu.zen.demo1/tinker/patch.info: open failed: ENOENT (No such file or directory)
05-28 01:49:32.379 25962-25979/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.youhu.zen.demo1/tinker/patch.info: open failed: ENOENT (No such file or directory)
05-28 01:49:32.380 25962-25979/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b
05-28 01:49:32.380 25962-25979/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.youhu.zen.demo1/files/patch_signed_7zip.apk size: 3977, dest file: /data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b/patch-fe57ed2b.apk size:3977
05-28 01:49:32.386 25962-25979/? E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 1974695978, got crc: 1675897560
05-28 01:49:32.386 25962-25979/? I/Tinker.DefaultPatchReporter: patchReporter onPatchTypeExtractFail: file extract fail type: dex, path: /data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b/patch-fe57ed2b.apk, extractTo: /data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b/dex/classes.dex.jar, filename: classes.dex
05-28 01:49:32.387 25962-25979/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b/patch-fe57ed2b.apk
05-28 01:49:32.388 25962-25979/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b/dex
05-28 01:49:32.388 25962-25979/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.youhu.zen.demo1/tinker/patch-fe57ed2b
05-28 01:49:32.389 25962-25979/? W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
05-28 01:49:32.390 25962-25979/? I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:6
05-28 01:49:32.390 25962-25979/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
05-28 01:49:32.390 25962-25979/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/com.youhu.zen.demo1/files/patch_signed_7zip.apk, success: false, cost: 47
05-28 01:49:32.390 25962-25979/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.youhu.zen.demo1/tinker_temp/temp.apk

**Comment by shwenzhang** [comment]
查看文档，你的用法不对。
