### ISSUE TITLE
Tinker 补丁增量下发是否可行

### ISSUE THREAD

**Issue by milk1990** [Tencent/tinker#503]
Tinker 不仅仅可以做bug修复，还可以做功能开关，不同的用户需要不同的功能开关，希望每次下发的补丁只是包含本次需要修改的内容，不包含以往的内容，这样可以保证下发的补丁包不至于累积到很大，而且可以有效解决补丁包的管理问题，所以在寻求解决办法：增量补丁包下发，客户端做补丁包的合并，不知道这个方向是否可行？？

**Comment by shwenzhang** [comment]
技术上没太大问题，但是管理上非常大。假设发布过A B C D E补丁，用户可能安装了任何一个补丁。每次发布都要N个差分
