### ISSUE TITLE
tinker 在compileSdkVersion 25     buildToolsVersion '25.0.2' 下能正常生成补丁包，合并失败

### ISSUE THREAD

**Issue by timesfire** [Tencent/tinker#506]
异常类型：loadPatch 失败 返回 -2

手机型号：:模拟器 Nexus 5

手机系统版本：如:Android 7.0 

tinker版本：1.7.11

gradle版本：2.2.2
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

没有使用热更新SDK

系统：Mac

在以上环境下能正常编译，生成补丁包，但是在loadPatch时一直报：
I06-01 16:25:26.950 11266-11266/com.yt.mall I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:165312
06-01 16:25:26.952 11266-11266/com.yt.mall I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2

若将编译环境改为
compileSdkVersion 23
buildToolsVersion '23.0.1'
可以打补丁成功，tinker对这个编译环境有限制吗？只能用23以下？

**Comment by shwenzhang** [comment]
tinker 不依赖编译的环境，-2的问题可以具体去查看文档。这里应该是找不到补丁包中的package meta文件
