### ISSUE TITLE
添加gradle依赖遇见问题了？please help me！

### ISSUE THREAD

**Issue by FlyInTheSkyToMe** [Tencent/tinker#507]
当我Try Again之后，提示：
Error:Could not GET 'https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.pom'. Received status code 400 from server: Bad Request
Enable Gradle 'offline mode' and sync project
or
Error:No cached version of com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11 available for offline mode.
Disable Gradle 'offline mode' and sync project

下面是我Gradle的接入：
项目中：
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath ‘com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11’

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
app中：
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'

    //可选，用于生成application类
    provided('com.tencent.tinker:tinker-android-anno:1.7.11')
    //tinker的核心库
    compile('com.tencent.tinker:tinker-android-lib:1.7.11')

}

**Comment by iluhcm** [comment]
```
Error:No cached version of com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11 available for offline mode.
Disable Gradle 'offline mode' and sync project
```
这个明显的问题，把offline mode关掉就好了。

**Comment by FlyInTheSkyToMe** [comment]
@iluhcm @memorycj 我之前试过，我刚又试了一次， 还是不行。

**Comment by iluhcm** [comment]
[https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/]

看看你的网络环境是否能访问这个目录，如果可以，就是你配置有问题。如果你认为一切都没问题，就重启AS。

**Comment by FlyInTheSkyToMe** [comment]
@iluhcm 可以访问。感谢您！ 如果实在不行，我就卸载AS再重新装。

**Comment by FlyInTheSkyToMe** [comment]
@iluhcm 大神， 我卸载了AS， 然后重装， 还是不行。还是这个错。 我要抓狂了。Please help me ！

**Comment by iluhcm** [comment]
![](http://7xl6ic.com1.z0.glb.clouddn.com/gradle_offline.png)

把这个钩去掉也不行么？

**Comment by FlyInTheSkyToMe** [comment]
是的， 我刚刚又把我的配置哪些删除了，重新生成， 还是不行。 我该怎么办？

**Comment by iluhcm** [comment]
不可能的，如果还提示offline，那就是AS读取的配置和你删除的配置是两份配置，你可能删错地方了。取消打钩，然后点apply，重启AS，一般就可以了。如果还不行那就是你的电脑有问题。

**Comment by FlyInTheSkyToMe** [comment]
classpath ('com.tencent.tinker:tinker-patch-gradle-plugin:1.6.2')，  这个我就能正常引用

**Comment by iluhcm** [comment]
能正常引用很有可能是你的本地maven库已经把相关的依赖下载下来了。

看一下下面这个目录对应有几个tinker plugins版本？
```
/Users/用户名/.m2/repository/com/tencent/tinker/tinker-patch-gradle-plugin
```

看一下目录下的`maven-metadata-local.xml`文件，有哪些version？

**Comment by FlyInTheSkyToMe** [comment]
要不， 你远程我嘛。 麻烦您了！    QQ:470429998

**Comment by FlyInTheSkyToMe** [comment]
@iluhcm 兄弟， 我成功了。 我把所有、一切与AS相关的文件卸载以及删除掉，然后清理了一下电脑。最后成功了。我发现此时我很淡定。感谢您！

**Comment by shwenzhang** [comment]
检查网络以及代理配置
