### ISSUE TITLE
Sample工程无法生成patch_signed_7zip.apk

### ISSUE THREAD

**Issue by yql86** [Tencent/tinker#51]
环境： androidStudio 2.2
gradle plugin version 2.2.0
gradle version 2.14.1

刚开始运行工程，报tinkerId not set , 后面我设置为：

tinkerId = '560'
tinkerOldApkPath = "${bakPath}/app-debug-0927-11-44-48.apk"
执行：tinkerPatchDebug 其他文件，文件夹都有app-debug,thinker_result,log.txt等， 但是就是没生成：patch_signed_7zip.apk。。 任务一直卡在app:tinkerPatchDebug。

**Comment by chenliuchun** [comment]
请参照#47，已解决
