### ISSUE TITLE
有人遇到过更新后UI变形吗？

### ISSUE THREAD

**Issue by WaterElva** [Tencent/tinker#512]
是偶发性的，原因不明，目前我的APP是设置隐藏Actionbar的，然后用view去做actionbar，但发现有时候更新完后，会出现系统的actionbar,问题我在主题的隐藏了，同时整个应用几乎都是变形的，所谓变形就是指正常运行下是没问题的，但是升级后，某些view自动填满全屏,有些明明没有设置间距，却突然会有了间距.

**Comment by nEdAy** [comment]
玄学

**Comment by shwenzhang** [comment]
升级指的是补丁升级吗？需要applyResourceID，并且不能修改remoteview
