### ISSUE TITLE
执行tinkerPathRelease后找不到patch包

### ISSUE THREAD

**Issue by scsfwgy** [Tencent/tinker#516]
异常类型：编译异常

手机型号：编译异常

手机系统版本：编译异常

tinker版本：com.tencent.bugly:tinker-support:1.0.8

gradle版本：2.3.3

是否使用热更新SDK：  Bugly SDK

系统：Mac

堆栈/日志：
无

提问：执行tinkerPathRelease后会生成tinkerPatch包，但是没有生成patch包。完全按照文档进行了配置，关键点也有注意。请问肯能是哪里的原因？

**Comment by shwenzhang** [comment]
编译的日志会写明，bugly的问题可以先咨询bugly
