### ISSUE TITLE
更新补丁之后，再从应用市场更新最新app，app启动不起来。

### ISSUE THREAD

**Issue by XinYiWorld** [Tencent/tinker#523]
异常类型：app打了一次补丁再从市场上下载最新的app覆盖安装，点击应用图标，应用图标暗了一下，应用run不起来，也没有崩溃的现象。

手机型号：所有手机

手机系统版本：所有手机

tinker版本：1.7.11

gradle版本：2.2.1

是否使用热更新SDK：    //微信热修复
    compile("com.tencent.tinker:tinker-android-lib:${TINKER_VERSION}") { changing = true }
    provided("com.tencent.tinker:tinker-android-anno:${TINKER_VERSION}") { changing = true }

系统：Android系统

**Comment by yuanshenbin** [comment]
肯定会有log，把合成的log，和闪退的log发下，什么也不提供，没办法分析

**Comment by XinYiWorld** [comment]
请问打了正式包之后，怎么打Log啊？

**Comment by nEdAy** [comment]
...打Log跟你打什么包没关系 你自己弄的开关

**Comment by XinYiWorld** [comment]
好的，谢谢！

**Comment by weinierfei** [comment]
tinkerId没改?

**Comment by nEdAy** [comment]
我觉得也是tinkerId没改

**Comment by XinYiWorld** [comment]
tinkerId我一直是写死的

**Comment by XinYiWorld** [comment]
听说这个tinkerid的生成是和git关联的，但是我们的项目是用SVN管理的。我这是tinkerid照着网上写死的，请问应该怎么处理？

**Comment by weinierfei** [comment]
1.参见issues432,获取svn的commitid
2.将appversion给tinkerid
然后还是好好看看文档吧

**Comment by nEdAy** [comment]
def getSvnRevision() {
    try {
        new ByteArrayOutputStream().withStream { os ->
            def result = exec {
                executable = 'svn'
                args = ['info']
                standardOutput = os
            }
            if (result == null) {
                throw new GradleException("can't get svn rev, you should add svn to system path or just input test value, such as 'testTinkerId'")
            }
            def outputAsString = os.toString()
            def matchLastChangedRev = outputAsString =~ /Last Changed Rev: (\d+)/

            ext.svnRev = "${matchLastChangedRev[0][1]}".toInteger()
        }
        return svnRev
    } catch (Exception ignored) {
        throw new GradleException("can't get svn rev, you should add svn to system path or just input test value, such as 'testTinkerId'")
    }
}

**Comment by XinYiWorld** [comment]
好的，多谢大神，您的回复速度简直像IM一样。

**Comment by weinierfei** [comment]
我的回复可能理解有误,二选一就好;然后问题解决了的话,你就把这个issues关里,省的邵文再来看,浪费他时间

**Comment by XinYiWorld** [comment]
稍等一会儿

**Comment by XinYiWorld** [comment]
大神，您好，我的问题还是没有解决。
3.3.7版本出现了问题，我更新了一个修复补丁。
然后到应用市场更新了3.3.9版本。
补丁的tinkerId和3.3.9的tinkerid是不一样的，怎么还是会有这个问题呢？是3.3.7的tinkerid不能与3.3.9的一样吗？

**Comment by XinYiWorld** [comment]
另外我更新了补丁之后 ，通过pakageManager得到的版本号没有变，和之前的一样。但是代码更新了
