### ISSUE TITLE
补丁包下载正常，打补丁失败，code=-3

### ISSUE THREAD

**Issue by shishuo365** [Tencent/tinker#524]
异常类型：app运行时异常

手机型号：如:Nexus 5

手机系统版本：如:Android 6.0

tinker版本：如:1.7.9

gradle版本：如:2.2.3

是否使用热更新SDK： 未使用

系统：Mac

使用 gradle 命令行编译的 debug 版补丁，下载到手机里面的是签名的 patch_signed_7zip.apk 加载补丁包后，没有效果，具体日志如下

堆栈/日志：
06-19 21:12:00.821 30906-30906/com.abc.android W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.abc.android/tinker
06-19 21:12:00.826 30906-30906/com.abc.android D/Tinker.DefaultAppLike: onBaseContextAttached:
06-19 21:12:00.846 30906-30906/com.abc.android I/Tinker.TinkerPatchListener: application maxMemory:256
06-19 21:12:00.865 30906-30906/com.abc.android W/Tinker.Tinker: tinker patch directory: /data/data/com.abc.android/tinker
06-19 21:12:00.868 30906-30906/com.abc.android I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.8
06-19 21:12:00.887 30906-30906/com.abc.android I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.abc.android, main process:true, systemOTA:false, oatDir:null, useInterpretMode:false
06-19 21:12:00.887 30906-30906/com.abc.android W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
06-19 21:12:00.887 30906-30906/com.abc.android I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.abc.android/tinker, code: -2, cost: 9ms
06-19 21:12:00.888 30906-30906/com.abc.android W/Tinker.Tinker: tinker load fail!
06-19 21:12:01.277 30906-30906/com.abc.android D/Tinker.DefaultAppLike: onCreate
06-19 21:12:01.633 30906-30906/com.abc.android W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
06-19 21:12:34.811 30906-32050/com.abc.android I/Tinker.TinkerPatchListener: receive a patch file: /data/data/com.abc.android/files/demo_patch_2.8.8_1.apk, file size:6649
06-19 21:12:34.841 30906-32050/com.abc.android W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
06-19 21:12:43.771 30906-32412/com.abc.android I/Tinker.TinkerPatchListener: receive a patch file: /data/data/com.abc.android/files/demo_patch_2.8.8_1.apk, file size:6649
06-19 21:12:43.776 30906-32412/com.abc.android I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/data/com.abc.android/files/demo_patch_2.8.8_1.apk, code: -3

patch进程的日志
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:/Users/ss/Documents/project/AppDemo/build/bakApk/AppDemo-meizu-2.8.8.apk
newApk:/Users/ss/Documents/project/AppDemo/build/outputs/apk/AppDemo-debug.apk
outputFolder:/Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug
isIgnoreWarning:false
isProtectedApp:false
7-ZipPath:/Users/ss/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:patchVersion, filed value:1
dex configs: 
dexMode: jar
dexPattern:assets/secondary-dex-.\.jar
dexPattern:classes.*\.dex
dex loader:com.abc.android.MyApplicationAgent
dex loader:com.tencent.tinker.loader.*
lib configs: 
libPattern:lib/.*/.*\.so
resource configs: 
resPattern:resources\.arsc
resPattern:res/.*
resPattern:assets/.*
resPattern:AndroidManifest\.xml
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: AppDemo-meizu-2.8.8.apk, size=53520328, md5=1b1c8abfc0aa133fa8be81f9373aa7a1
new apk: AppDemo-debug.apk, size=53520712, md5=6bf36d3a3a8ef4fdf55b8f1d9a02cf62
UnZipping apk to /Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/AppDemo-meizu-2.8.8
UnZipping apk to /Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/AppDemo-debug
Check for loader classes in dex: classes.dex
Check for loader classes in dex: classes2.dex
Found modify resource: res/layout/main_bottom_bar_layout.xml

Gen classes.dex patch file:/Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/tinker_result/classes.dex, size:3123, md5:fe53aecf8958a6de1c0c0ea3ea305411
Verifying if patched new dex is logically the same as original new dex: AppDemo-debug/classes.dex ...

Gen classes.dex for dalvik full dex file:/Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/tempPatchedDexes/classes.dex, size:8333100, md5:a70cf62eb0efa7eff8c926406dc6f930

Gen classes2.dex patch file:/Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/tinker_result/classes2.dex, size:363, md5:e738c4d4ee6831886a78fa50f94e2148
Verifying if patched new dex is logically the same as original new dex: AppDemo-debug/classes2.dex ...

Gen classes2.dex for dalvik full dex file:/Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/tempPatchedDexes/classes2.dex, size:8190620, md5:227b9c1fd968570b9d31ecd27c769585
DexDecoder:write meta file data: classes.dex,,a70cf62eb0efa7eff8c926406dc6f930,a70cf62eb0efa7eff8c926406dc6f930,fe53aecf8958a6de1c0c0ea3ea305411,3255747835,jar
DexDecoder:write meta file data: classes2.dex,,227b9c1fd968570b9d31ecd27c769585,227b9c1fd968570b9d31ecd27c769585,e738c4d4ee6831886a78fa50f94e2148,2035221353,jar

Add test install result dex: /Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
Add Test resource file: assets/only_use_to_test_tinker_resource.txt
Final normal zip resource: resources_out.zip, size=28643119, md5=8a250c582fdc4a4a2d29c9b913238be0
Final 7zip resource: resources_out_7z.zip, size=28643089, md5=402ff67295a485318d060d0d0cffba91
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:/Users/ss/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
Result: final signed patch result: /Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/patch_signed.apk, size=6649
Result: final signed with 7zip patch result: /Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug/patch_signed_7zip.apk, size=7319
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 670 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 28.747000s
Tinker patch done, you can go to file to find the output /Users/ss/Documents/project/AppDemo/build/outputs/tinkerPatch/debug
-----------------------Tinker patch end-------------------------

**Comment by shwenzhang** [comment]
06-19 21:12:43.776 30906-32412/com.abc.android I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/data/com.abc.android/files/demo_patch_2.8.8_1.apk, code: -3

patch进程正在运行仲，请自己查看错误码

**Comment by yearRomance** [comment]
E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
2019-08-14 16:20:53.603 4392-4392/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-08-14 16:20:53.603 4392-4392/? D/Tinker.DefaultAppLike: onCreate
2019-08-14 16:20:54.185 4392-4392/com.easytransfer.studyabroad W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
基准包不能连网上报,这是什么问题?
