### ISSUE TITLE
编译补丁包时报错：can't the get signConfig for this build

### ISSUE THREAD

**Issue by lxc7923** [Tencent/tinker#525]
app module 下build .gradle已经配置     
signingConfigs {
        release {
            storeFile file("../test.jks")
            storePassword "123456"
            keyAlias "test"
            keyPassword "123456"
        }
        debug {
            storeFile file("../test.jks")
            storePassword "123456"
            keyAlias "test"
            keyPassword "123456"
        }
    }
打包时选择release，打出基准包，改动后打补丁包就会报can't the get signConfig for this build，在网上查了很久也没有类似的问题，求大神指点

**Comment by shwenzhang** [comment]
参考tinker sample
