### ISSUE TITLE
使用tinker发包后,ormlite 数据库初始化发生ConcurrentModificationException

### ISSUE THREAD

**Issue by liveei** [Tencent/tinker#527]
app 中集成使用了 ormlite 数据库，最近爆发了ConcurrentModificationException ，刚好是从发布tinker包之后爆发的，之前数据正常。
通过查看patch包发现，里面打入了com\j256\ormlite\core\VERSION.txt 中的txt文件，实际该文件未发生变更，而ormlite 数据库在初始化过程中调用了ClassLoader.getResourceAsStream(resourceName) 来读取 VERSION.txt文件，在读取过程中发生了ConcurrentModificationException，以下为相关信息，请腾讯tinker的伙伴帮忙看下：

异常类型：app运行时异常 ConcurrentModificationException

手机型号：华为 oppo  vivo 魅族 三星...

手机系统版本：4.0-6.0

tinker版本：1.7.11

gradle版本：2.3.1

是否使用热更新SDK： TinkerPatch SDK 

系统：windows

堆栈/日志：

1Caused by: java.util.ConcurrentModificationException
2    at java.util.Hashtable$HashIterator.nextEntry(Hashtable.java:727)
3    at java.util.Hashtable$EntryIterator.next(Hashtable.java:778)
4    at java.util.Hashtable$EntryIterator.next(Hashtable.java:776)
5    at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:960)
6    at org.apache.harmony.security.utils.AlgNameMapper.selectEntries(AlgNameMapper.java:187)
7    at org.apache.harmony.security.utils.AlgNameMapper.checkCacheVersion(AlgNameMapper.java:113)
8    at org.apache.harmony.security.utils.AlgNameMapper.map2AlgName(AlgNameMapper.java:150)
9    at org.apache.harmony.security.x509.AlgorithmIdentifier.getAlgorithmName(AlgorithmIdentifier.java:96)
10    at org.apache.harmony.security.pkcs7.SignerInfo.getDigestAlgorithmName(SignerInfo.java:97)
11    at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:128)
12    at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:306)
13    at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:276)
14    at java.util.jar.JarFile.getInputStream(JarFile.java:399)
15    at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
16    at java.net.URL.openStream(URL.java:470)
17    at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:432)
18    at java.lang.Class.getResourceAsStream(Class.java:1037)
19    at com.j256.ormlite.misc.VersionUtils.getVersionFromFile(VersionUtils.java:86)
20    at com.j256.ormlite.misc.VersionUtils.readCoreVersion(VersionUtils.java:68)
21    at com.j256.ormlite.misc.VersionUtils.checkCoreVersusAndroidVersions(VersionUtils.java:41)
22    at com.j256.ormlite.db.SqliteAndroidDatabaseType.<init>(SqliteAndroidDatabaseType.java:22)
23    at com.j256.ormlite.android.AndroidConnectionSource.<init>(AndroidConnectionSource.java:32)
24 <init>
25    at com.j256.ormlite.android.apptools.OrmLiteSqliteOpenHelper.<init>(OrmLiteSqliteOpenHelper.java:37)

**Comment by shwenzhang** [comment]
tinker 对比的是二进制，请确认是否真的没有修改。若这个文件不需求修改，可以放到ignore patch，具体可以放编译日志跟文档
