### ISSUE TITLE
Gradle Sync Issues

### ISSUE THREAD

**Issue by ghost** [Tencent/tinker#528]
Error:Unable to find method 'org.gradle.api.internal.artifacts.configurations.ConfigurationInternal.getModule()Lorg/gradle/api/internal/artifacts/ModuleInternal;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by shwenzhang** [comment]
it isn't the issue of tinker

**Comment by fdxing** [comment]
The same issues occure on My IDE. My Android Studio version is 2.3.3. When import the `Tinker` project, Android Studio `recommend that you update the Android Gradle plugin to version 2.3.3 and Gradle to version 3.3`. We just not click the `update` and use the project's configurations. The issues is solved.

**Comment by ZhuRg** [comment]
Hey，bro，have you solved this problem? I got the same problem when i import this project to Android Studio. Can you tell me the solution to this problem ,if you have solved and remember the solution. thank you very much.

**Comment by CharlieZheng** [comment]
遇到同样的问题，有解决了的么 @fdxing @ZhuRg Is any body solve this issue?

**Comment by ZhuRg** [comment]
@CharlieZheng  I got this problem is because I imported the tinker-master directory which contains multiple project rather than a project including multiple module to Android Studio.It's a low mistake.If your situation like me,u just need import tinker-sample-android directory under tinker-master rather than tinker-master to AS. good luck!

**Comment by sailor1861** [comment]
非Tinker插件的问题：

应该是这个插件，与你的Gradle版本不兼容导致的； 参考官网说明， 选择对应Gradle版本的插件版本即可
 classpath "com.github.dcendents:android-maven-gradle-plugin:1.5"

参考@https://github.com/dcendents/android-maven-gradle-plugin/issues/49
