### ISSUE TITLE
Sample报错 error=2

### ISSUE THREAD

**Issue by liuyuan1993** [Tencent/tinker#53]
![ta 73 a 5b34w1 4p g3c0](https://cloud.githubusercontent.com/assets/15606753/18863748/90585828-84c5-11e6-8f9b-cc5c9b1a8e78.png)
我的本地git版本：
![hj 4c 9e8i imxw7i rd](https://cloud.githubusercontent.com/assets/15606753/18863788/c3235640-84c5-11e6-97c7-df8cfd7d61cb.png)

**Comment by shwenzhang** [comment]
#11
