### ISSUE TITLE
WebCat crash caused by tinker

### ISSUE THREAD

**Issue by miaotao** [Tencent/tinker#531]
This is Android N Device.  Webcat works well before but freezed just after 1 mins. From the log,  Even after reboot the phone, the issue still here.

From the log, I think it is because the tinker just did some hotfix which caused this crash.

re-install webcat will not fix this.

clean the webcat data from "settings->apps"  will fix this.

===================================
06-27 16:12:44.712  8604  8604 I MMDB    : Initialize JNI module (1/11) CursorWindow...
06-27 16:12:44.713  1450  1702 D InputReader: AP_PROF:AppLaunch_dispatchPtr:Up:119081, ID:0
06-27 16:12:44.713  8604  8604 V JNIHelp : Registering com/tencent/wcdb/CursorWindow natives
06-27 16:12:44.713  8604  8604 I MMDB    : Initialize JNI module (2/11) FileUtils...
06-27 16:12:44.713  8604  8604 V JNIHelp : Registering com/tencent/wcdb/FileUtils natives
06-27 16:12:44.713  8604  8604 I MMDB    : Initialize JNI module (3/11) ChunkedCursorWindow...
06-27 16:12:44.713  8604  8604 V JNIHelp : Registering com/tencent/wcdb/database/ChunkedCursorWindow natives
06-27 16:12:44.714  8604  8604 V JNIHelp : Registering com/tencent/wcdb/database/SQLiteAsyncQuery natives
06-27 16:12:44.715  8604  8604 I MMDB    : Initialize JNI module (4/11) SQLiteConnection...
06-27 16:12:44.715  8604  8604 V JNIHelp : Registering com/tencent/wcdb/database/SQLiteConnection natives
06-27 16:12:44.716  8604  8604 I MMDB    : Initialize JNI module (5/11) SQLiteDebug...
06-27 16:12:44.716  8604  8604 V JNIHelp : Registering com/tencent/wcdb/database/SQLiteDebug natives
06-27 16:12:44.716  2064  2064 D SubscriptionController: [getActiveSubscriptionInfoForSimSlotIndex]+ slotIdx=0 subId={id=3, iccId=898601160XXXXXXXXXXX simSlotIndex=0 displayName=ä¸­å½èé carrierName=UNICOM nameSource=0 iconTint=-16725934 dataRoaming=0 iconBitmap=android.graphics.Bitmap@f58d2f5 mcc 460 mnc 1 SimProvisioningStatus 0}
06-27 16:12:44.716  8604  8604 I MMDB    : Initialize JNI module (6/11) SQLiteDirectCursor...
06-27 16:12:44.716  8604  8604 V JNIHelp : Registering com/tencent/wcdb/database/SQLiteDirectQuery natives
06-27 16:12:44.717  8604  8604 I MMDB    : Initialize JNI module (7/11) SQLiteGlobal...
06-27 16:12:44.717  8604  8604 V JNIHelp : Registering com/tencent/wcdb/database/SQLiteGlobal natives
06-27 16:12:44.717  8604  8604 I MMDB    : Initialize JNI module (8/11) DBBackup...
06-27 16:12:44.717  8604  8604 V JNIHelp : Registering com/tencent/wcdb/repair/BackupKit natives
06-27 16:12:44.717  8604  8604 V JNIHelp : Registering com/tencent/wcdb/repair/RecoverKit natives
06-27 16:12:44.717  8604  8604 I MMDB    : Initialize JNI module (9/11) ShellUtil...
06-27 16:12:44.717  8604  8604 V JNIHelp : Registering com/tencent/wcdb/repair/DBDumpUtil natives
06-27 16:12:44.718  8604  8604 I MMDB    : Initialize JNI module (10/11) DBRepair...
06-27 16:12:44.718  8604  8604 V JNIHelp : Registering com/tencent/wcdb/repair/RepairKit natives
06-27 16:12:44.718  8604  8604 I MMDB    : Initialize JNI module (11/11) Log...
06-27 16:12:44.718  8604  8604 V JNIHelp : Registering com/tencent/wcdb/support/Log natives
06-27 16:12:44.753  8604  8604 V jni crash monitor: SignalHander Entered
06-27 16:12:44.754  8604  8604 V jni crash monitor: On Thread start.
06-27 16:12:44.767  8604  8604 I crash   : before unwind signal thread
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Process:            com.tencent.mm
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Crash Thread:       8604(total:17)
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Date/Time:          2107-06-27 +8.00 16:12:44.754
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Live Time:          0s
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Device:             Lenovo P2a42 android-24
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Exception info:     
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Siginfo:            errno:0, pid:10, uid:0, process:UNKNOWN
06-27 16:12:44.767  8604  8604 I crash   : after unwind signal thread
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: 
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: Build fingerprint: Lenovo/kuntao_row/P2a42:7.0/NRD90N/P2a42_S233_170404_ROW:user/release-keys
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: pid: 8604, tid: 8604(main thread)  >>> com.tencent.mm <<<
06-27 16:12:44.767  8604  8604 F MicroMsg_Crash: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000000a
06-27 16:12:44.797  8604  8604 I crash   : after dump thread backtrace
06-27 16:12:44.797  8604  8604 F MicroMsg_Crash:   #00  pc 0x3737d2  /system/lib/libart.so (art::GetCalleeSaveMethodCaller(art::ArtMethod**, art::Runtime::CalleeSaveType, bool)+261)
06-27 16:12:44.797  8604  8604 F MicroMsg_Crash:   #01  pc 0x3e967f  /system/lib/libart.so (artInvokeStaticTrampolineWithAccessCheck+30)
06-27 16:12:44.797  8604  8604 F MicroMsg_Crash:   #02  pc 0x9dde3  /system/lib/libart.so (???)
06-27 16:12:44.797  8604  8604 F MicroMsg_Crash:   #03  pc 0xc52319  /data/data/com.tencent.mm/tinker/patch-939c4417/odex/classes.dex (oatexec+4271928089)
06-27 16:12:44.797  8604  8604 I crash   : after dump stack
06-27 16:12:44.797  8604  8604 I crash   : after dump jni exception
06-27 16:12:44.800  8604  8604 F art     : art/runtime/oat_quick_method_header.cc:55] Failed to find Dex offset for PC offset 0x36(PC 0xc1c3431b, entry_point=0xc1c342e5 current entry_point=0xc1c342e5) in void com.tencent.mm.boot.svg.a.a.bz.<init>()

===============================================

  Package [com.tencent.mm] (2fc024):

      primaryCpuAbi=armeabi
      secondaryCpuAbi=null
      versionCode=1060 minSdk=16 targetSdk=23
      versionName=6.5.8

**Comment by shwenzhang** [comment]
it seem like sqlite db corrupt， what 's your wechat uin? I  can look forward this problem

**Comment by miaotao** [comment]
what's the meaning of "webchat uin"?

**Comment by shwenzhang** [comment]
login id
