### ISSUE TITLE
applicationLike名字中带下划线，编译错误

### ISSUE THREAD

**Issue by awdvhil9** [Tencent/tinker#532]
异常类型：编译异常

tinker版本：如:1.7.11

gradle版本：如:3.3-all

是否使用热更新SDK：否

系统：如:Windows

当ApplicationLike命名的时候，带下划线比如My_ApplicationLike的时候，编译会报FilerException，然后说recreate这个application了，不知道什么原因，把下划线去掉就可以了

**Comment by shwenzhang** [comment]
这边在mac上试了一下，不会存在问题。
