### ISSUE TITLE
加载dex时没有对odex文件做校验

### ISSUE THREAD

**Issue by wei-Ken** [Tencent/tinker#534]
tinkerLoadVerifyFlag=true的情况下，TinkerDexLoader加载dex时会对合成后的dex做md5校验，但是并没有对之前生成的odex文件做校验。这样如果odex文件被修改，那么对dex做的md5校验就没有意义了。

是否考虑增加对odex文件的校验？

**Comment by shwenzhang** [comment]
odex的md5无法提前知道，如果只写sp也是没有任何意义的

**Comment by wei-Ken** [comment]
明白了，能给些建议吗，还是想尽量降低下这个风险

**Comment by shwenzhang** [comment]
odex因为每个机型都不太一样，不能做到批量替换，这里的风险还好。如果想做，可以自己存一下md5，然后用来校验。
