### ISSUE TITLE
在Android7.1.1系统上面偶发的java.lang.LinkageError: No superclass defined for class java.lang.Object 

### ISSUE THREAD

**Issue by achellies** [Tencent/tinker#536]
异常类型：app运行时异常

手机型号：大部分崩溃发生在Oppo R11和Mi6上面

手机系统版本：都是Android7.1.1系统

tinker版本：无（因我们是使用了com.tencent.tinker.loader.SystemClassLoaderAdder这个类进行添加Dex操作，并进行了修改，改成在尾部添加Dex）

gradle版本：无

系统：如:Mac

堆栈/日志：
java.lang.LinkageError: No superclass defined for class java.lang.Object (declaration of 'java.lang.Object' appears in /system/framework/core-oj.jar)
	at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:400)
	at com.tencent.tinker.loader.SystemClassLoaderAdder.checkDexInstall(SystemClassLoaderAdder.java:2109)

**Comment by shwenzhang** [comment]
在后台查了一下，似乎没有类似的crash出现。这个是用在加载插件？

**Comment by achellies** [comment]
是的，用这个类安装插件的DEX

**Comment by shwenzhang** [comment]
tinker 中并没有发现类似的情况
