### ISSUE TITLE
在一些手机报 when loading tinker:java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by lizixian18** [Tencent/tinker#537]
异常类型：app运行时异常

手机型号：小米 M4

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

tinker版本：latest.release

gradle版本：3.3

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：如:Mac

堆栈/日志：
 

![qq 20170630163858](https://user-images.githubusercontent.com/16240767/27727788-8a075e76-5db2-11e7-92dc-2849425b06e9.png)

app打开之后就出现这个异常，OOM，在一些高端一点的手机不会出现，稍微老一点的手机会出现，暂时的解决办法是加 android:largeHeap="true"

**Comment by shwenzhang** [comment]
这个crash跟tinker 没有关系，这里只是一个普通的crash Cather
