### ISSUE TITLE
oppo 7.1.1  ClassCastException

### ISSUE THREAD

**Issue by liangxianshen** [Tencent/tinker#543]
过去的6个小时，发了个补丁，发现oppo在7.1.1系统上出现60+个crash，

集成方式：继承了tinker的代理application
tinker版本号：1.0.6
crashreport_upgrade:1.2.5
机型:oppo r9\oppo r11
系统版本：7.1.1

日志：
#5509 java.lang.ClassCastException
com.tencent.tinker.lib.service.a cannot be cast to com.tencent.tinker.lib.service.a
com.tencent.tinker.lib.service.AbstractResultService.void onHandleIntent(android.content.Intent)(SourceFile:64)

**Comment by ding33211** [comment]
也有同样问题

**Comment by balizhuang2012** [comment]
我们也遇上同样的崩溃，oppo r11或者r11t,都是7.1.1的机器

**Comment by csdnail** [comment]
tinker版本号：1.0.6 ??
是不是该升级了

**Comment by pzhangleo** [comment]
这个版本号是tinkerpatch平台的吧

**Comment by nEdAy** [comment]
mark

**Comment by fenglintianxia6** [comment]
同样都是Oppo 的 7.1.1的机器

**Comment by qingyizeng** [comment]
碰到同样问题

异常类型：app运行时异常

手机型号：Oppo r9m

手机系统版本：CyanogenMod Android 7.1.1

tinker版本：1.7.11

gradle版本：3.3

是否使用热更新SDK： Bugly SDK

系统: Mac

堆栈/日志：
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.xxx.buy2/com.xxx.buy2.activity.ActivityMainTab}: java.lang.ClassCastException: com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication cannot be cast to com.xxx.helper.DDApplication

**Comment by balizhuang2012** [comment]
我用原生的1.7.11 tinker试了试，在线上还是会报这个异常

**Comment by shwenzhang** [comment]
try with 1.8.0

**Comment by liangxianshen** [comment]
这个crash是每次打开都会发生，还是只发生一次呢？
bugly提供的tinker最新是1.0.8，对应的1.7.11，我能放弃1.0.8，直接用1.8.0或者更高版本的tinker吗？
