### ISSUE TITLE
ignoreWarning = false,编译时中断。设置ignoreWarning = true，编译通过，但是在三星Samsung SM-N7506V机型上ANR

### ISSUE THREAD

**Issue by mhlistener** [Tencent/tinker#545]
异常类型：编译异常

异常说明: 
1.在此之前发了几个补丁包一直没问题。今天做了同样的操作编译时异常

2.ignoreWarning = false,编译时中断。信息提示我增加了组件PicassoProvider，事实上我并没有做任何的组件添加。这个Picasso库一直没更新过。同时我对比了之前的发布版本，也没有新加关于组件的任何内容上去。Analyyze apk 新旧包，发现多出了一个PicassoProvider,但是用AS 自带build直接打包是不存在这个provider的。不知道这个组件是如何在不更新库的前提下加上去的？

3.设置ignoreWarning = true，编译通过后但是在三星Samsung SM-N7506V机型上ANR，测试其它四部手机都是可以热修复成功。 

手机型号：Samsung SM-N7506V

手机系统版本：4.3

tinker版本：1.7.11

gradle版本：2.1.0

是否使用热更新SDK：TinkerPatch SDK 

系统：Windows10

堆栈/日志：
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:C:\Users\JohnsonFan\Desktop\FoowBase\bakApk/app-4.1.1-0620-16-42-06/release//app-release.apk
newApk:E:\Androids\android_workspace\back2\xxx\app\build\outputs\apk\xxxx_V4.1.1_07.05.apk
outputFolder:E:\Androids\android_workspace\back2\xxx\app\build\outputs/tinkerPatch/release
isIgnoreWarning:false
isProtectedApp:true
7-ZipPath:C:\Users\JohnsonFan\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
useSignAPk:true
package meta fields: 
dex configs: 
dexMode: jar
dexPattern:classes.*\.dex
dex loader:com.tencent.tinker.loader.*
dex loader:com.xxx.soft.android.Application.FoowwApp
lib configs: 
libPattern:lib/.*/.*\.so
resource configs: 
resPattern:res/.*
resPattern:AndroidManifest\.xml
resPattern:r/.*
resPattern:assets/.*
resPattern:resources\.arsc
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: app-release.apk, size=29439118, md5=e9a2cf9b5d1e64c60cee26a6dd826f72
new apk: FoowwSoftAndroid_V4.1.1_07.05.apk, size=29439573, md5=653349f1899365a88829321296252265
Warning:ignoreWarning is false, but we found a new AndroidComponent com.squareup.picasso.PicassoProvider, it will crash at some time

**Comment by shwenzhang** [comment]
这个看起来就是picasso版本更新之类的原因把，无可能突然新增一个组件的。请自行检查
