### ISSUE TITLE
与AndResGuard兼容时,单独执行AndResGuard的任务编译几十秒最多1-2分钟,但是执行tinkerPatch则要几十分钟?为什么这么慢

### ISSUE THREAD

**Issue by wll2007** [Tencent/tinker#546]
:baby:transformClassesWithMultidexlistForRelease UP-TO-DATE
:baby:transformClassesWithDexForRelease UP-TO-DATE
:baby:mergeReleaseJniLibFolders UP-TO-DATE
:baby:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:baby:transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
:baby:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:baby:packageRelease
:baby:assembleRelease
:baby:resguardRelease
resourceprpguard begin
unziping apk to E:\wherecom-android\baby\build\outputs\apk\AndResGuard_Watch-U_V1.0.0_2017_07_06\temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename com.wherecom.highinnovation
resources mapping file E:\wherecom-android\baby\build\outputs\apk\AndResGuard_Watch-U_V1.0.0_2017_07_06\resource_mapping_Watch-U_V1.0.0_2017_07_06.txt done
writing new resources.arsc 
resources.arsc Character Encoding: utf-8
general unsigned apk: Watch-U_V1.0.0_2017_07_06_unsigned.apk
DestResDir 1239 rawResDir 1239
signing apk: Watch-U_V1.0.0_2017_07_06_signed.apk
signature Algorithm is: SHA1withRSA
use 7zip to repackage: Watch-U_V1.0.0_2017_07_06_signed_7zip.apk, will cost much more time
[addStoredFileIn7Zip]rewrite the stored file into the 7zip, file count:2
zipaligning apk: Watch-U_V1.0.0_2017_07_06_signed.apk
zipaligning apk: Watch-U_V1.0.0_2017_07_06_signed_7zip.apk
resources proguard done, you can go to file to find the output E:\wherecom-android\baby\build\outputs\apk\AndResGuard_Watch-U_V1.0.0_2017_07_06
:baby:tinkerPatchRelease
到这后就花了好长时间

**Comment by shwenzhang** [comment]
可以gradle trace，打出每个任务的耗使。上面没有有价值的信息，旧版本曾经出现个bug，新版本应该已经fix
