### ISSUE TITLE
patch进程出现本地文件锁争抢异常

### ISSUE THREAD

**Issue by xiaomaguoguo** [Tencent/tinker#547]
异常类型：app运行时异常

手机型号：我这是电视

手机系统版本：Android6.0

tinker版本：1.7.10

gradle版本：3.3

是否使用热更新SDK： 否，接的Tinker

系统：Window7

堆栈/日志：
07-06 13:31:12.985 24346-24346/com.knothing.hotfix.hotdemo W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 com.knothing.hotfix.log.pm.PMLog$1.handleMessage:36 android.os.Handler.dispatchMessage:102 android.os.Looper.loop:148 android.app.ActivityThread.main:5417 
07-06 13:31:13.107 24346-26354/com.knothing.hotfix.hotdemo W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
07-06 13:31:13.109 24346-26354/com.knothing.hotfix.hotdemo W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 android.content.ContextWrapper.startService:581 com.tencent.tinker.lib.service.TinkerPatchService.a:62 com.tencent.tinker.lib.listener.DefaultPatchListener.b:53 com.tencent.tinker.lib.tinker.TinkerInstaller.a:91 
07-06 13:31:13.185 26366-26366/com.knothing.hotfix.hotdemo:patch W/System: ClassLoader referenced unknown path: /system/lib/com.knothing.hotfix.hotdemo
07-06 13:31:13.188 5635-5674/com.iflytek.xiri2.system W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 android.content.ContextWrapper.startService:581 com.iflytek.xiri.control.SystemController$9.run:461 java.lang.Thread.run:818 <bottom of call stack> 
07-06 13:31:13.207 26366-26366/com.knothing.hotfix.hotdemo:patch W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
07-06 13:31:13.219 26366-26366/com.knothing.hotfix.hotdemo:patch W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 com.knothing.hotfix.log.pm.PMLog.c:64 com.knothing.hotfix.log.pm.PMLog.a:54 com.bftv.VoiceApplication.onBaseContextAttached:78 com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached:132 
07-06 13:31:13.263 26366-26366/com.knothing.hotfix.hotdemo:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.knothing.hotfix.hotdemo/tinker
07-06 13:31:13.264 26366-26366/com.knothing.hotfix.hotdemo:patch W/Tinker.TinkerLoadResult: tinker is disable, just return
07-06 13:31:13.265 26366-26366/com.knothing.hotfix.hotdemo:patch W/Tinker.Tinker: tinker load fail!
07-06 13:31:13.270 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: java.io.IOException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.initOutputFiles(FileHandler.java:197)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.init(FileHandler.java:159)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.<init>(FileHandler.java:482)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.AsyncFileHandler.<init>(SourceFile:30)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:185)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.<init>(SourceFile:54)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:63)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.a(SourceFile:135)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.b(SourceFile:67)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.bftv.VoiceApplication.onBaseContextAttached(SourceFile:114)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:146)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Application.attach(Application.java:187)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.Posix.fcntlFlock(Native Method)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
07-06 13:31:13.271 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: 	... 27 more
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: java.io.IOException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.initOutputFiles(FileHandler.java:197)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.init(FileHandler.java:159)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.<init>(FileHandler.java:482)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.AsyncFileHandler.<init>(SourceFile:30)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:185)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.<init>(SourceFile:54)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:63)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.a(SourceFile:135)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.b(SourceFile:67)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.bftv.VoiceApplication.onBaseContextAttached(SourceFile:114)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:146)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Application.attach(Application.java:187)
07-06 13:31:13.273 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.Posix.fcntlFlock(Native Method)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
07-06 13:31:13.274 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: 	... 27 more
07-06 13:31:13.276 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: java.io.IOException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.initOutputFiles(FileHandler.java:197)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.init(FileHandler.java:159)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.<init>(FileHandler.java:482)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.AsyncFileHandler.<init>(SourceFile:30)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:185)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.<init>(SourceFile:54)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:63)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.a(SourceFile:135)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.b(SourceFile:67)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.bftv.VoiceApplication.onBaseContextAttached(SourceFile:114)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:146)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Application.attach(Application.java:187)
07-06 13:31:13.277 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.Posix.fcntlFlock(Native Method)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
07-06 13:31:13.278 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: 	... 27 more
07-06 13:31:13.279 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: java.io.IOException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.initOutputFiles(FileHandler.java:197)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.init(FileHandler.java:159)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.<init>(FileHandler.java:482)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.AsyncFileHandler.<init>(SourceFile:30)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:185)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.<init>(SourceFile:54)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:63)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.a(SourceFile:135)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.b(SourceFile:67)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.bftv.VoiceApplication.onBaseContextAttached(SourceFile:114)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:146)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Application.attach(Application.java:187)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-06 13:31:13.280 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.Posix.fcntlFlock(Native Method)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
07-06 13:31:13.281 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: 	... 27 more
07-06 13:31:13.282 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: java.io.IOException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.282 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
07-06 13:31:13.282 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.tryLock(FileChannelImpl.java:181)
07-06 13:31:13.282 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.channels.FileChannel.tryLock(FileChannel.java:584)
07-06 13:31:13.282 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.initOutputFiles(FileHandler.java:197)
07-06 13:31:13.282 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.init(FileHandler.java:159)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.util.logging.FileHandler.<init>(FileHandler.java:482)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.AsyncFileHandler.<init>(SourceFile:30)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:185)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.<init>(SourceFile:54)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.FileLog.a(SourceFile:63)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.a(SourceFile:135)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.knothing.hotfix.log.LogUtil.b(SourceFile:67)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.bftv.VoiceApplication.onBaseContextAttached(SourceFile:114)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:146)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Application.attach(Application.java:187)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
07-06 13:31:13.283 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: Caused by: android.system.ErrnoException: fcntl failed: EAGAIN (Try again)
07-06 13:31:13.284 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.Posix.fcntlFlock(Native Method)
07-06 13:31:13.284 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
07-06 13:31:13.284 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err:     at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
07-06 13:31:13.284 26366-26366/com.knothing.hotfix.hotdemo:patch W/System.err: 	... 27 more
07-06 13:31:13.286 26366-26366/com.knothing.hotfix.hotdemo:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
07-06 13:31:13.287 26366-26386/com.knothing.hotfix.hotdemo:patch W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/Android/data/com.knothing.hotfix.hotdemo/cache/patch.zip to /data/user/0/com.knothing.hotfix.hotdemo/tinker_temp/temp.apk
07-06 13:31:13.371 26366-26386/com.knothing.hotfix.hotdemo:patch W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 android.content.ContextWrapper.startService:581 com.tencent.tinker.lib.service.TinkerPatchService.b:162 com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent:123 android.app.IntentService$ServiceHandler.handleMessage:66 
07-06 13:31:13.415 26366-26386/com.knothing.hotfix.hotdemo:patch W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.knothing.hotfix.hotdemo/tinker/patch.info: open failed: ENOENT (No such file or directory)
07-06 13:31:13.415 26366-26386/com.knothing.hotfix.hotdemo:patch W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.knothing.hotfix.hotdemo/tinker/patch.info: open failed: ENOENT (No such file or directory)
07-06 13:31:13.416 26366-26386/com.knothing.hotfix.hotdemo:patch W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/Android/data/com.knothing.hotfix.hotdemo/cache/patch.zip size: 5833, dest file: /data/user/0/com.knothing.hotfix.hotdemo/tinker/patch-01b48392/patch-01b48392.apk size:5833
07-06 13:31:13.690 24346-24354/com.knothing.hotfix.hotdemo W/CursorWrapperInner: Cursor finalized without prior close()

**Comment by shwenzhang** [comment]
这里唯一加锁的只有读取配置文件，那个文件应该是比较小的。这个时间应该不会长

**Comment by xiaomaguoguo** [comment]
手机里面是没有问题的，但是明显的发现同样大小 的补丁包，在TV里面修复的过程耗时比手机长多了。而且上面的错，同样的demo，在手机里面没有问题，在tv端就报这个错，是不是因为tv的rom定制过的原因 ？
