### ISSUE TITLE
红米Note上启动报java.lang.NoClassDefFoundError，ApplicationLike及直接引用类都在maindex

### ISSUE THREAD

**Issue by biyeshengplay** [Tencent/tinker#549]
异常类型：app运行时异常

手机型号：红米Note

手机系统版本：如:Android 4.4.2 

tinker版本：1.7.5

gradle版本：3.3

是否使用热更新SDK： 否

系统：如:Mac

备注：分包保持配置正确，反编译apk包ApplicationLike及其直接引用类都在maindex

堆栈/日志：
I/MultiDex(17933): install
I/MultiDex(17933): MultiDexExtractor.load(/data/app/com.example.demo-1.apk, false)
D/dalvikvm(17933): create interp thread : stack size=128KB
D/dalvikvm(17933): create new thread
D/dalvikvm(17933): new thread created
D/dalvikvm(17933): update thread list
D/dalvikvm(17933): threadid=10: interp stack at 0x7711d000
D/dalvikvm(17933): threadid=10: created from interp
D/dalvikvm(17933): start new thread
D/dalvikvm(17933): threadid=10: notify debugger
D/dalvikvm(17933): threadid=10 (SharedPreferencesImpl-load): calling run()
I/MultiDex(17933): loading existing secondary dex files
I/MultiDex(17933): load found 3 secondary dex files
D/dalvikvm(17933): open_cached_dex_file : /data/data/com.example.demo/code_cache/secondary-dexes/com.example.demo-1.apk.classes2.zip /data/data/com.example.demo/code_cache/secondary-dexes/com.example.demo-1.apk.classes2.dex
D/dalvikvm(17933): open_cached_dex_file : /data/data/com.example.demo/code_cache/secondary-dexes/com.example.demo-1.apk.classes3.zip /data/data/com.example.demo/code_cache/secondary-dexes/com.example.demo-1.apk.classes3.dex
D/dalvikvm(17933): threadid=10: exiting
D/dalvikvm(17933): threadid=10: bye!
D/dalvikvm(17933): open_cached_dex_file : /data/data/com.example.demo/code_cache/secondary-dexes/com.example.demo-1.apk.classes4.zip /data/data/com.example.demo/code_cache/secondary-dexes/com.example.demo-1.apk.classes4.dex
I/MultiDex(17933): install done
W/Tinker.Tinker(17933): tinker patch directory: /data/data/com.example.demo/tinker
I/Tinker.TinkerLoadResult(17933): parseTinkerResult loadCode:-2
W/Tinker.TinkerLoadResult(17933): can't find patch file, is ok, just return
I/Tinker.DefaultLoadReporter(17933): patch load result, path:/data/data/com.example.demo/tinker, code:-2, cost:2
W/Tinker.Tinker(17933): tinker load fail!
D/Tinker.DefaultAppLike(17933): onCreate
D/DMLog-->DmallApplication(17933): [ (DmallApplication.java:137)#onCreate ] DmallApplication onCreate
D/AndroidRuntime(17933): Shutting down VM
W/dalvikvm(17933): threadid=1: thread exiting with uncaught exception (group=0x41ab0cf8)
W/dalvikvm(17933): threadid=1: uncaught exception occurred
W/System.err(17933): java.lang.RuntimeException: Unable to create application com.example.demo.AutoApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found
W/System.err(17933): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4599)
W/System.err(17933): 	at android.app.ActivityThread.access$1500(ActivityThread.java:154)
W/System.err(17933): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
W/System.err(17933): 	at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err(17933): 	at android.os.Looper.loop(Looper.java:193)
W/System.err(17933): 	at android.app.ActivityThread.main(ActivityThread.java:5349)
W/System.err(17933): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17933): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(17933): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
W/System.err(17933): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
W/System.err(17933): 	at dalvik.system.NativeStart.main(Native Method)
W/System.err(17933): Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found
W/System.err(17933): 	at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:183)
W/System.err(17933): 	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:192)
W/System.err(17933): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
W/System.err(17933): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4596)
W/System.err(17933): 	... 10 more
W/System.err(17933): Caused by: java.lang.reflect.InvocationTargetException
W/System.err(17933): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(17933): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(17933): 	at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:181)
W/System.err(17933): 	... 13 more
W/System.err(17933): Caused by: java.lang.NoClassDefFoundError: com.bumptech.glide.request.target.ViewTarget
W/System.err(17933): 	at com.example.demo.DmallApplication.onCreate(DmallApplication.java:141)
W/System.err(17933): 	... 16 more
W/dalvikvm(17933): threadid=1: calling UncaughtExceptionHandler

**Comment by wildma** [comment]
我也遇到这个问题, 有人回答吗?

**Comment by simpleton** [comment]
@biyeshengplay @wildma 请直接升级到最新版1.7.11. 新版会自动帮助你keep main dex。

**Comment by shwenzhang** [comment]
com.bumptech.glide.request.target.ViewTarget 在主dex么？旧的keep规则写的不够健壮，换到1.7.11把
