### ISSUE TITLE
无法生成mapping文件

### ISSUE THREAD

**Issue by linchangjian** [Tencent/tinker#552]
问题：无法生成mapping文件，编译完成后，只有*.R 文件与*.apk

异常类型：编译异常

<img width="976" alt="2017-07-12 5 35 56" src="https://user-images.githubusercontent.com/8524419/28111580-9547d200-6728-11e7-8d7e-63c8c2b1f4da.png">

tinker版本：如:1.7.11

gradle版本：如:3.3

系统：Mac

堆栈/日志：
----------------------tinker build warning ------------------------------------
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=10.0.0-patchhh in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------
/Users/aniu/***/app/src/main/AndroidManifest.xml:36:5-237:19 Warning:
	application@android:theme was tagged at AndroidManifest.xml:36 to replace other declarations but no other declaration present
/Users/aniu/****/app/src/main/AndroidManifest.xml:228:9-231:45 Warning:
	meta-data#material_url@android:value was tagged at AndroidManifest.xml:228 to replace other declarations but no other declaration present

......
tinker add tinker_id_10.0.0-patchhh to your AndroidManifest.xml /Users/aniu/****/app/build/intermediates/manifests/full/prod/debug/AndroidManifest.xml
tinker add android.taobao.atlas.startup.AtlasBridgeApplication to dex loader pattern
tinker add com.tencent.tinker.loader.* to dex loader pattern
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml
.....

/Users/*****/app/build/intermediates/res/merged/prod/debug/values/values.xml:1179: warning: Attribute "crbDrawableSize" has already been defined

.....

注: Creating file:/Users/aniu/****/app/build/generated/source/apt/prod/debug/*/*/*/BaseApplication.java

try update tinker multidex keep proguard file with /Users/*****/app/build/intermediates/tinker_intermediates/tinker_multidexkeep.pro

**Comment by simpleton** [comment]
@linchangjian mapping是proguard生成的
