### ISSUE TITLE
tinker获取不到了

### ISSUE THREAD

**Issue by awdvhil9** [Tencent/tinker#556]
异常类型：编译异常

tinker版本：如:1.7.11

gradle版本：如:2.3.3

是否使用热更新SDK： 否

系统：Windows

堆栈/日志：
Error:Failed to resolve: annotationProcessor
Error:Failed to resolve: com.tencent.tinker:tinker-android-lib:1.7.11
Error:Failed to resolve: com.tencent.tinker:tinker-android-anno:1.7.11
获取不到，网络是正常的，用tinker-sample也获取不到，请问是什么问题？

**Comment by awdvhil9** [comment]
今天刚发生的，之前是好的

**Comment by xiangqiuhan** [comment]
我也发生了这个错误,所有接入tinker的项目都找不到

**Comment by shishuo365** [comment]
我查看了 jcenter 官网，发现已经没有了 http://jcenter.bintray.com/com/tencent/tinker/

**Comment by guanyueyun** [comment]
真的坑

**Comment by shwenzhang** [comment]
![image](https://user-images.githubusercontent.com/8335303/28397566-eeacbb14-6d34-11e7-8137-38d8a795cd26.png)

**Comment by typ0520** [comment]
加上  mavenLocal()
```
buildscript {
    repositories {
        mavenLocal()
    }
}

allprojects {
    repositories {
        mavenLocal()

    }
}
```

以1.7.9为例执行以下命令
```
git clone https://github.com/Tencent/tinker.git
cd tinker
git checkout v1.7.9
./gradlew install
```

**Comment by xiaweizi** [comment]
我也是

**Comment by shishuo365** [comment]
项目管理者已经参与进来，估计很快就能解决

**Comment by guanyueyun** [comment]
@shwenzhang 好了说一声呀

**Comment by wlj190785060** [comment]
我也遇到这个问题  @typ0520  这个方法也不行

**Comment by typ0520** [comment]
@wlj190785060 可以的，我们组里就是这样解决的，现在都好了

**Comment by awdvhil9** [comment]
@guanyueyun 我这边用那个方法也可以

**Comment by wlj190785060** [comment]
@typ0520  可以了  谢谢你

**Comment by nbcallum** [comment]
很僵，居然被下线了！

**Comment by zackzjc** [comment]
扎心了，老铁

**Comment by guanyueyun** [comment]
@awdvhil9 最后一个命令要执行多久？

![image](https://user-images.githubusercontent.com/23523919/28399174-06907848-6d3e-11e7-99d9-a51cd1611275.png)

**Comment by sougoucm** [comment]
![image](https://user-images.githubusercontent.com/7127052/28399339-0b62abb0-6d3f-11e7-99fb-8daf6adf5772.png)
![image](https://user-images.githubusercontent.com/7127052/28399351-1acfbafc-6d3f-11e7-988e-90475c711f4d.png)
路径变了就可以了

**Comment by guanyueyun** [comment]
@sougoucm 我的改了也不行

**Comment by simpleton** [comment]
@guanyueyun 可以现在repositories里增加`maven{ url 'https://dl.bintray.com/tinker/maven'}` 来workaround.

**Comment by guanyueyun** [comment]
@simpleton 你们本地是不是有这些包了
![image](https://user-images.githubusercontent.com/23523919/28402640-75d334ec-6d53-11e7-93ee-5bfb39d684ea.png)

**Comment by guanyueyun** [comment]
![image](https://user-images.githubusercontent.com/23523919/28402863-9b68ebec-6d54-11e7-9047-2ad686c9ed31.png)
就是不行。。。我是今天才开始尝试tinker的

**Comment by typ0520** [comment]
@guanyueyun 你也太衰了吧，就今天出问题了^_^；  加https://........../tinker这个地址只能解决tinker jar包的问题，腾讯别的包你还要自己在想办法，现在没出问题的都是本地有缓存

**Comment by xucezzu** [comment]
@guanyueyun https://jcenter.bintray.com/com/tencent/tinker/   这个是官方的   把“tencent”改成“thinkerpatch”是一个第三方封装的，http://tinkerpatch.com/

**Comment by dndxxiangyu** [comment]
求帮忙解决啊，以上几种方案都不行，1.7.6

**Comment by guanyueyun** [comment]
@xucezzu 不是三方吧也是腾讯自己的平台吧，tinkerpatch平台的方式也是不信的也是同样的包找不到

**Comment by awdvhil9** [comment]
@guanyueyun 你竟让在下gradle

**Comment by awdvhil9** [comment]
@guanyueyun 没多久就几兆，一会就下完了

**Comment by awdvhil9** [comment]
@guanyueyun 没多久 一会就执行完了，我直接在as里面执行的上面的命令

**Comment by hfg5961107** [comment]
Error:Could not find com.tencent.tinker:tinker-android-lib:1.7.5.
Required by:
    project :app
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by Whoisurdady** [comment]
@simpleton 感谢大神，方法有效，看了下，应该是tinker团队的大拿

**Comment by hfg5961107** [comment]
@guanyueyun 你解决了么？
Error:Could not find com.tencent.mm:apk-parser-lib:1.2.0.
Searched in the following locations:
    file:/D:/as/gradle/m2repository/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.pom
    file:/D:/as/gradle/m2repository/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.jar
    https://jcenter.bintray.com/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.pom
    https://jcenter.bintray.com/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.jar
    https://repo1.maven.org/maven2/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.pom
    https://repo1.maven.org/maven2/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.jar
    https://dl.bintray.com/tinker/maven/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.pom
    https://dl.bintray.com/tinker/maven/com/tencent/mm/apk-parser-lib/1.2.0/apk-parser-lib-1.2.0.jar
Required by:
    project : > com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11 > com.tencent.tinker:tinker-patch-lib:1.7.11

**Comment by dengjiali0925** [comment]
git clone https://github.com/Tencent/tinker.git
cd tinker
git checkout v1.7.9
./gradlew install
请问这些命令在哪个目录下进行呢

**Comment by guanyueyun** [comment]
@hfg5961107 放弃了，重新用andfix了，等他们解决了再来尝试

**Comment by dengjiali0925** [comment]
@typ0520 请问
git clone https://github.com/Tencent/tinker.git
cd tinker
git checkout v1.7.9
./gradlew install
这些命令在哪个目录下执行呢

**Comment by hfg5961107** [comment]
@xiangqiuhan 我是原项目本来就用的这个，现在这问题解决不了，我总不能去把用到的地方全注释掉吧。

**Comment by typ0520** [comment]
@dengjiali0925 随便那个目录执行都可以

**Comment by simpleton** [comment]
@hfg5961107 @dengjiali0925 @guanyueyun 
缺少tinker的库：增加 `maven{ url 'https://dl.bintray.com/tinker/maven'}`
缺少apkparser或者AndResGuard: `maven{ url 'https://dl.bintray.com/wemobiledev/maven'}`

**Comment by awdvhil9** [comment]
@dengjiali0925 我直接在项目目录下执行的，git clone https://github.com/Tencent/tinker.git这个命令下载的tinker就是我正在用的1.7.11，git checkout v1.7.9这个我没执行，我拷了一份local.properties,./gradlew install是在tinker目录下执行的，执行clean和build命令要退出tinker目录，在项目目录下执行

**Comment by simpleton** [comment]
@awdvhil9 不用做local maven...按照你缺少库的提示，增加想用的maven repo即可。

**Comment by dengjiali0925** [comment]
@simpleton 已解决，谢谢啦

**Comment by hfg5961107** [comment]
@simpleton Tinker插件配置中dex相关配置项报错。
Error:(126, 0) Could not set unknown property 'usePreGeneratedPatchDex' for  dexMode = jar
 pattern = []
 loader = []
 ignoreWarningLoader = []
         of type com.tencent.tinker.build.gradle.extension.TinkerDexExtension.

**Comment by guanyueyun** [comment]
@hfg5961107 老铁加上`maven{ url 'https://dl.bintray.com/wemobiledev/maven'}`

**Comment by hfg5961107** [comment]
@guanyueyun  有加的。能找到包了、

**Comment by hfg5961107** [comment]
@simpleton 解决了，谢谢大佬。

**Comment by xurui1995** [comment]
@simpleton 感谢

**Comment by shishuo365** [comment]
还有一个签名的错误
Could not find com.tencent.mm:SevenZip:1.1.10

**Comment by shishuo365** [comment]
汇总一下
缺少tinker的库：增加 maven{ url 'https://dl.bintray.com/tinker/maven'}
缺少apkparser或者AndResGuard: maven{ url 'https://dl.bintray.com/wemobiledev/maven'}
缺少sevenzip的库：增加 maven { url 'https://dl.bintray.com/simsun/maven' }

**Comment by shwenzhang** [comment]
已全部恢复

**Comment by qinghui** [comment]
我原来1.7.11可以，现在不行了，一直提示找不到
https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar

换成1.7.9就可以，clean也报这个错，重新下代码还是一样，

classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
这句改成
classpath "com.tinkerpatch.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
才可以，
怎么解？

**Comment by dounickAC** [comment]
这个是jCenter上的包，但是jCenter公开访问已经停止了，所以可以考虑通过jCenter镜像获取。我用了阿里云的jCenter镜像
https://maven.aliyun.com/nexus/content/repositories/jcenter
成功了
