### ISSUE TITLE
昨天还好好的, 今天Gradle 不能编译, 报 Failed to resolve: annotationProcessor

### ISSUE THREAD

**Issue by fishSon** [Tencent/tinker#557]
```
异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：1.7.11

gradle版本：3.3
是否使用热更新SDK：  TinkerPatch SDK

系统：Windows 7
```
Gradle 编译报错, 提示 <br>
```
Failed to resolve: annotationProcessor
Failed to resolve: com.tencent.tinker:tinker-android-anno:1.7.11
```
- 尝试更新了 SDK 但是并没有用处
- 尝试 clean/rebuild 同样没有用处
----
另外附上Gradle配置:
```
provided ("com.tencent.tinker:tinker-android-anno:${TINKER_VERSION}") { changing=true }
```

**Comment by awdvhil9** [comment]
我也遇到了这个问题

**Comment by guanyueyun** [comment]
`Error:Could not find com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11.
Searched in the following locations:
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.pom
    file:/D:/Program Files/Android/Android Studio/gradle/m2repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar
    file:/C:/Users/Administrator/.m2/repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.pom
    file:/C:/Users/Administrator/.m2/repository/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.pom
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar
Required by:
    project :`

不知道什么原因

**Comment by wlj190785060** [comment]
我也是

**Comment by shishuo365** [comment]
我查看了 jcenter 官网，发现已经没有了 http://jcenter.bintray.com/com/tencent/tinker/

**Comment by shwenzhang** [comment]
duplicate #556

**Comment by fishSon** [comment]
@wlj190785060 @awdvhil9 @shishuo365 我在本地找到 tinker 的 jar 包，直接导入 jar 包，先凑合用吧，起码编译没啥问题了....

**Comment by stven0king** [comment]
现在项目的gradle需要升级到3.1，tinker报错：

```
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.  - tinker-android-anno-1.9.1.jar (com.tencent.tinker:tinker-android-anno:1.9.1)
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

想问问tinker是不是还没有支持到gradle3.1？
