### ISSUE TITLE
Could not find SevenZip-windows-x86_64.exe (com.tencent.mm:SevenZip:1.1.10) 打补丁出错

### ISSUE THREAD

**Issue by wo153** [Tencent/tinker#559]
```
异常类型：编译异常

tinker版本：如:1.7.10

gradle版本：如:3.3

系统：Windows 10

堆栈/日志：
Error:Execution failed for task ':app:tinkerPatchDebug'.
> Could not resolve all files for configuration ':app:sevenZipToolsLocator'.
   > Could not find SevenZip-windows-x86_64.exe (com.tencent.mm:SevenZip:1.1.10).
     Searched in the following locations:
         https://jcenter.bintray.com/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-windows-x86_64.exe

**Comment by micck2** [comment]
I have same question

**Comment by simpleton** [comment]
@wo153 @micck2 可以现在repositories里增加 `maven{ url 'https://dl.bintray.com/wemobiledev/maven'}`

**Comment by shwenzhang** [comment]
duplicate #556

**Comment by guanyueyun** [comment]
@simpleton 加了这个不能解决上诉问题呀

**Comment by guanyueyun** [comment]
![image](https://user-images.githubusercontent.com/23523919/28410028-00195b8e-6d6f-11e7-9c1b-a9342ef7ea68.png)

**Comment by simpleton** [comment]
麻烦更新sevenzip到1.2.3的版本

**Comment by wo153** [comment]
我配置了本地sevenzip路径解决了

**Comment by zhangxy123666** [comment]
本地好用，方法如下:

直接手动创建:
~/.m2/repository/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-osx-x86_64.exe

然后加入到根目录

  repositories { 
        // 加上这一句  
        mavenLocal() 

    }

**Comment by EasyDots** [comment]
> 本地好用，方法如下:
> 
> 直接手动创建:
> ~/.m2/repository/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-osx-x86_64.exe
> 
> 然后加入到根目录
> 
> repositories {
> // 加上这一句
> mavenLocal()
> 
> ```
> }
> ```
@zhangxy123666 怎么直接创建？

**Comment by jqyp324** [comment]
> 本地好用，方法如下:
> 
> 直接手动创建:
> ~/.m2/repository/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-osx-x86_64.exe
> 
> 然后加入到根目录
> 
> repositories {
> // 加上这一句
> mavenLocal()
> 
> ```
> }
> ```

3q done

**Comment by fxfSean** [comment]
直接手动创建:
~/.m2/repository/com/tencent/mm/SevenZip/1.1.10/SevenZip-1.1.10-osx-x86_64.exe
然后加入到根目录

请问下手动创建意思是，将这个.exe的执行文件下载到对应目录吗？可以给个链接吗？
我是MAC系统，不太清楚如何操作，谢谢！
