### ISSUE TITLE
项目同步gradle后Tinker异常

### ISSUE THREAD

**Issue by zxm8241213zxm** [Tencent/tinker#560]
Gradle版本3.3
Android Studio版本2.3

异常信息：同步完成build.gradle后，控制台输出Tinker同步异常！
![6be1ac94-7f66-4118-bab3-4baaedc87ffc](https://user-images.githubusercontent.com/4557482/28406209-24eaa4ca-6d62-11e7-9512-e58d5eb88451.png)

**Comment by simpleton** [comment]
dup #556

**Comment by zxm8241213zxm** [comment]
感谢大神。已经看了前面的帖子了。救了老命了！
