### ISSUE TITLE
tinker-patch-gradle-plugin  1.7.11问题

### ISSUE THREAD

**Issue by qinghui** [Tencent/tinker#562]
我原来1.7.11可以，现在不行了，一直提示找不到
https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar

clean也报这个错，重新下代码还是一样，换成1.7.9就可以。

classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
这句改成
classpath "com.tinkerpatch.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
才可以，怎么解？

**Comment by simpleton** [comment]
@qinghui 现在你贴的url已经有内容了，昨天包被unlink了一段时间，昨晚18:00已经恢复了

**Comment by qinghui** [comment]
上面的jar包是能下载，可是就是提示
Error:Could not find tinker-patch-gradle-plugin.jar (com.tencent.tinker:tinker-patch-gradle-plugin:1.7.11).
Searched in the following locations:
    https://jcenter.bintray.com/com/tencent/tinker/tinker-patch-gradle-plugin/1.7.11/tinker-patch-gradle-plugin-1.7.11.jar
