### ISSUE TITLE
Android O on Pixel 补丁还原成功后出现找不到dex的报错

### ISSUE THREAD

**Issue by icespring** [Tencent/tinker#563]
异常类型：补丁还原异常

手机型号：Gooble Pixel 

手机系统版本：Android O

tinker版本：如:1.7.11

gradle版本：如:3.4.1

是否使用热更新SDK： 否

系统：Mac

堆栈/日志：
07-25 10:20:58.848 928-1994/? I/ActivityManager: Start proc 10887:com.ice.notecool:patch/u0a156 for service com.ice.notecool/com.tencent.tinker.lib.service.TinkerPatchService
07-25 10:20:58.956 10887-10887/com.ice.notecool:patch W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
07-25 10:20:58.957 10887-10887/com.ice.notecool:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
07-25 10:20:58.966 10887-10887/com.ice.notecool:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.ice.notecool/tinker
07-25 10:20:58.967 10887-10887/com.ice.notecool:patch I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
07-25 10:20:58.968 10887-10887/com.ice.notecool:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.ice.notecool:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
07-25 10:20:58.968 10887-10887/com.ice.notecool:patch W/Tinker.TinkerLoadResult: tinker is disable, just return
07-25 10:20:58.969 10887-10887/com.ice.notecool:patch I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.ice.notecool/tinker, code: -1, cost: 2ms
07-25 10:20:58.969 10887-10887/com.ice.notecool:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
07-25 10:20:58.970 10887-10887/com.ice.notecool:patch W/Tinker.Tinker: tinker load fail!
07-25 10:20:58.970 10887-10887/com.ice.notecool:patch D/Tinker.DefaultAppLike: onCreate
07-25 10:20:59.008 10887-10904/com.ice.notecool:patch W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/notecool/patch.apk to /data/user/0/com.ice.notecool/tinker_temp/temp.apk
07-25 10:20:59.023 10887-10904/com.ice.notecool:patch I/Tinker.TinkerPatchService: try to increase patch process priority
07-25 10:20:59.030 928-953/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.ice.notecool/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
07-25 10:20:59.035 928-953/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.ice.notecool/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
07-25 10:20:59.201 10887-10904/com.ice.notecool:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:8cbdc6427188c50930c3f5d3ad52ba7c
07-25 10:20:59.204 10887-10904/com.ice.notecool:patch W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.ice.notecool/tinker/patch.info (No such file or directory)
07-25 10:20:59.205 10887-10904/com.ice.notecool:patch W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.ice.notecool/tinker/patch.info (No such file or directory)
07-25 10:20:59.206 10887-10904/com.ice.notecool:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.ice.notecool/tinker/patch-8cbdc642
07-25 10:20:59.211 10887-10904/com.ice.notecool:patch W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/notecool/patch.apk size: 10316, dest file: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/patch-8cbdc642.apk size:10316
07-25 10:21:02.894 10887-10904/com.ice.notecool:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes.dex, size: 9791056, use time: 3677
07-25 10:21:02.896 10887-10904/com.ice.notecool:patch I/Tinker.BasePatchInternal: try Extracting /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes2.dex
07-25 10:21:03.032 10887-10904/com.ice.notecool:patch I/Tinker.BasePatchInternal: isExtractionSuccessful: true
07-25 10:21:03.056 10887-10904/com.ice.notecool:patch I/Tinker.BasePatchInternal: try Extracting /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/test.dex
07-25 10:21:03.058 10887-10904/com.ice.notecool:patch I/Tinker.BasePatchInternal: isExtractionSuccessful: true
07-25 10:21:03.060 10887-10904/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:3, optimizeDexDirectory:/data/user/0/com.ice.notecool/tinker/patch-8cbdc642/odex/
07-25 10:21:03.064 10887-10995/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes2.dex, size: 5149168
07-25 10:21:03.079 10887-10994/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes.dex, size: 9791056
07-25 10:21:03.109 10996-10996/? I/dex2oat: /system/bin/dex2oat --debuggable --debuggable --dex-file=/data/data/com.ice.notecool/tinker/patch-8cbdc642/dex/classes2.dex --output-vdex-fd=41 --oat-fd=42 --oat-location=/data/data/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/classes2.odex
07-25 10:21:03.164 10997-10997/? I/dex2oat: /system/bin/dex2oat --debuggable --debuggable --dex-file=/data/data/com.ice.notecool/tinker/patch-8cbdc642/dex/classes.dex --output-vdex-fd=44 --oat-fd=45 --oat-location=/data/data/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/classes.odex
07-25 10:21:11.503 10887-10995/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes2.dex, opt file size: 0, use time 8435
07-25 10:21:11.508 10887-10995/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/test.dex, size: 584
07-25 10:21:11.618 11135-11135/? I/dex2oat: /system/bin/dex2oat --debuggable --debuggable --dex-file=/data/data/com.ice.notecool/tinker/patch-8cbdc642/dex/test.dex --output-vdex-fd=41 --oat-fd=42 --oat-location=/data/data/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/test.odex
07-25 10:21:11.804 10887-10995/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/test.dex, opt file size: 0, use time 299
07-25 10:21:14.722 10887-10994/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes.dex, opt file size: 0, use time 3216
07-25 10:21:14.723 10887-10904/com.ice.notecool:patch I/Tinker.ParallelDex: All dexes are optimized successfully, cost: 11661 ms.
07-25 10:21:14.724 10887-10904/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:15512
07-25 10:21:14.725 10887-10904/com.ice.notecool:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
07-25 10:21:14.725 10887-10904/com.ice.notecool:patch W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
07-25 10:21:14.726 10887-10904/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: dex count: 3, final wait time: 18
07-25 10:21:14.727 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 1 times
07-25 10:21:24.729 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 2 times
07-25 10:21:34.733 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 3 times
07-25 10:21:44.741 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 4 times
07-25 10:21:54.746 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 5 times
07-25 10:22:04.751 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 6 times
07-25 10:22:14.760 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 7 times
07-25 10:22:24.766 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 8 times
07-25 10:22:34.770 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 9 times
07-25 10:22:44.776 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 10 times
07-25 10:22:54.783 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 11 times
07-25 10:23:04.785 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 12 times
07-25 10:23:14.793 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 13 times
07-25 10:23:24.799 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 14 times
07-25 10:23:34.806 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 15 times
07-25 10:23:44.811 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 16 times
07-25 10:23:54.813 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 17 times
07-25 10:24:04.820 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: parallel dex optimizer file classes.dex is not exist, just wait 18 times
07-25 10:24:14.826 10887-10904/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: classes.dex, size 0
07-25 10:24:14.834 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file classes.dex is not exist, return false
07-25 10:24:14.843 10887-10904/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: classes2.dex, size 0
07-25 10:24:14.851 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file classes2.dex is not exist, return false
07-25 10:24:14.860 10887-10904/com.ice.notecool:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: test.dex, size 0
07-25 10:24:14.867 10887-10904/com.ice.notecool:patch E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file test.dex is not exist, return false
07-25 10:24:14.875 10887-10904/com.ice.notecool:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchDexOptFail: dex opt fail path: /storage/emulated/0/notecool/patch.apk, dex size: 3
07-25 10:24:14.887 10887-10904/com.ice.notecool:patch E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexOptExist failed
                                                                                        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.waitAndCheckDexOptFile(DexDiffPatchInternal.java:116)
                                                                                        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:149)
                                                                                        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:65)
07-25 10:24:14.890 10887-10904/com.ice.notecool:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/odex/classes.dex
07-25 10:24:14.894 10887-10904/com.ice.notecool:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/odex/classes2.dex
07-25 10:24:14.899 10887-10904/com.ice.notecool:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/odex/test.dex
07-25 10:24:14.901 10887-10904/com.ice.notecool:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, check dex opt file failed
07-25 10:24:14.908 10887-10904/com.ice.notecool:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/notecool/patch.apk, success: false, cost: 195879
07-25 10:24:14.909 10887-10904/com.ice.notecool:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker_temp/temp.apk
07-25 10:24:14.984 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/info.lock
07-25 10:24:14.984 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/patch-8cbdc642.apk
07-25 10:24:14.985 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes.dex
07-25 10:24:14.992 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/classes2.dex
07-25 10:24:14.997 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/test.dex
07-25 10:24:14.997 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/classes2.vdex
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/classes2.odex
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/classes.vdex
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/classes.odex
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/test.vdex
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm/test.odex
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat/arm
07-25 10:24:14.998 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex/oat
07-25 10:24:14.999 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/dex
07-25 10:24:14.999 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642/odex
07-25 10:24:14.999 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker/patch-8cbdc642
07-25 10:24:14.999 7727-13672/com.ice.notecool I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.ice.notecool/tinker

**Comment by shwenzhang** [comment]
fix by dev， wait for next version to piblish
