### ISSUE TITLE
Tinker:NoSuchMethodError

### ISSUE THREAD

**Issue by SirZhao** [Tencent/tinker#565]
java.lang.NoSuchMethodError: No static method closeKeybord(Landroid/view/View;)V in class Lcom/zdd/utils/APPUtils; or its super classes (declaration of 'com.zdd.utils.APPUtils' appears in /data/app/com.netschool.ui-2/base.apk:classes10.dex)

你好，我在AppUtil里写了静态的关闭软键盘的方法,在类中写了个方法去调用这个apputil.closeKeybord,切换editText焦点的时候就会报出此异常，请问如何去解决

**Comment by SirZhao** [comment]
找到问题的原因了

**Comment by laoxiao79** [comment]
@SirZhao 您好，您这个问题是怎么解决的呢？我也遇到了
