### ISSUE TITLE
app/build.gradle中设置minSdkVersion=15时编译生成patch正常更新正常，但是如果minSdkVersion设置成21了之后生成patch时出现异常

### ISSUE THREAD

**Issue by menmaoshan** [Tencent/tinker#566]
异常类型：app/build.gradle中设置minSdkVersion=15时编译生成patch正常更新正常，但是如果minSdkVersion设置成21了之后就会报下面的异常，gradle编译和命令行编译生成patch都出现异常

手机型号：平板设备

手机系统版本：Android7.0

tinker版本：如:1.7.7

gradle版本：如:2.14.1

是否使用热更新SDK： 如 TinkerPatch SDK

系统：如:Windows

堆栈/日志：

C:\Users\Administrator\Desktop\tinker\tool_output>java -jar tinker-patch-cli-1.7.7.jar -old app-release-0720-22-05-59.apk -new app-release-0721-20-28-21.apk -config tinker_config.xml -out output
special configFile file path:C:\Users\Administrator\Desktop\tinker\tool_output\tinker_config.xml
special output directory path: C:\Users\Administrator\Desktop\tinker\tool_output\output
reading config file, C:\Users\Administrator\Desktop\tinker\tool_output\tinker_config.xml
-----------------------Tinker patch begin-----------------------
configuration:
oldApk:C:\Users\Administrator\Desktop\tinker\tool_output\app-release-0720-22-05-59.apk
newApk:C:\Users\Administrator\Desktop\tinker\tool_output\app-release-0721-20-28-21.apk
outputFolder:C:\Users\Administrator\Desktop\tinker\tool_output\output
isIgnoreWarning:false
7-ZipPath:7za
useSignAPk:true
package meta fields:
filed name:patchMessage, filed value:classes.dex
filed name:platform, filed value:all
dex configs:
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.sample.tinkdemo.tinker.SimpleTinkerInApplication
dex loader:com.tencent.tinker.loader.*
lib configs:
libPattern:lib/armeabi/.*\.so
resource configs:
resPattern:res/.*
resPattern:resources\.arsc
resPattern:AndroidManifest\.xml
resPattern:assets/.*
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: app-release-0720-22-05-59.apk, size=10456627, md5=bf78b1b79e9eceab8929476e4db685a8
new apk: app-release-0721-20-28-21.apk, size=10456771, md5=cf7b9fa901ce24c7edde66bc7216bb62

UnZipping apk to C:\Users\Administrator\Desktop\tinker\tool_output\output\app-release-0720-22-05-59
UnZipping apk to C:\Users\Administrator\Desktop\tinker\tool_output\output\app-release-0721-20-28-21
Check for loader classes in dex: classes.dex
Check for loader classes in dex: classes10.dex
Check for loader classes in dex: classes11.dex
Check for loader classes in dex: classes12.dex
Check for loader classes in dex: classes13.dex
Check for loader classes in dex: classes14.dex
Warning:ignoreWarning is false, but we found loader classes are found in old secondary dex. Found classes: {Lcom/sample/tinkdemo/tinker/SimpleTinkerInApplication;}
java.lang.RuntimeException: com.tencent.tinker.build.util.TinkerPatchException: loader classes are found in old secondary dex. Found classes: {Lcom/sample/tinkdemo/tinker/SimpleTinkerInApplication;}
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:179)
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:138)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:113)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
        at com.tencent.tinker.patch.CliMain.run(CliMain.java:106)
        at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)
Caused by: com.tencent.tinker.build.util.TinkerPatchException: loader classes are found in old secondary dex. Found classes: {Lcom/sample/tinkdemo/tinker/SimpleTinkerInApplication;}
        at com.tencent.tinker.build.util.ExcludedClassModifiedChecker.checkIfExcludedClassWasModifiedInNewDex(ExcludedClassModifiedChecker.java:179)
        at com.tencent.tinker.build.decoder.DexDiffDecoder.patch(DexDiffDecoder.java:122)
        at com.tencent.tinker.build.decoder.UniqueDexDiffDecoder.patch(UniqueDexDiffDecoder.java:39)
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:176)
        ... 7 more

Usage: java -jar tinker.jar -old old.apk -new new.apk -config tinker_config.xml -out output_path
others please contact us

**Comment by simpleton** [comment]
disable掉predex

**Comment by shwenzhang** [comment]
如果大于21，系统就不跑keep main dex的那个task了。需要手动指定tinker的main dex pattern

**Comment by menmaoshan** [comment]
loader = [
                    //use sample, let BaseBuildInfo unchangeable with tinker
                    "tinker.sample.android.app.BaseBuildInfo",
                    "com.tencent.tinker.loader.*",
                    "com.sample.tinkdemo.tinker.SimpleTinkerInApplication"
            ]
这样配置了还是不行呀？

**Comment by shwenzhang** [comment]
main dex pattern，不是这个。gradle的配置，具体看文档把

**Comment by menmaoshan** [comment]
如果multiDexEnabled为true，将自动生成Tinker需要放在主dex的keep规则。在tinker 1.7.6版本之前，你需要手动将生成规则拷贝到自己的multiDexKeepProguard文件中。例如Sample中的multiDexKeepProguard file("keep_in_main_dex.txt")。在1.7.6版本之后，这里会通过脚本自动处理，无须手动填写。

应该是这条吧，我android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "com.sample.tinkdemo"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        multiDexKeepProguard file("keep_in_main_dex.txt")
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        /**
         * buildConfig can change during patch!
         * we can use the newly value when patch
         */
        buildConfigField "String", "MESSAGE", "\"I am the base apk\""
//        buildConfigField "String", "MESSAGE", "\"I am the patch apk\""
        /**
         * client version would update with patch
         * so we can get the newly git version easily!
         */
        buildConfigField "String", "TINKER_ID", "\"${getTinkerIdValue()}\""
        buildConfigField "String", "PLATFORM",  "\"all\""
    }
}配置过了，并且把build/intermediates/tinker_intermediates/tinker_multidexkeep.pro这个文件内容复制到app/keep_in_main_dex.txt中，但是还是报一样的错误
