### ISSUE TITLE
android 7.0 上；按照集成SDK 文档上的步骤；为什么没有效果，也没有报错

### ISSUE THREAD

**Issue by zhuangzeqin** [Tencent/tinker#567]
android 7.0 上；按照集成SDK 文档上的步骤；为什么没有效果，也没有报错,不知是否兼容7.0 以上的系统

异常类型： 无

手机型号：荣耀8

手机系统版本：如:Android 7.0 

tinker版本：如:1.7.7

gradle版本：如:2.3.3

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：如:win7

**Comment by simpleton** [comment]
兼容，关闭过滤器只过滤tinker,然后再看下。

**Comment by zhuangzeqin** [comment]
我是个新手；貌似还是不可以；另外一个就是集成文档不够详细明了；一般的集成文档；照着来；引领大家怎么用； 越是简单越是好；都是不会出错的；我前前后后；折腾一下午；都是失败的；不知道为啥；可能是我集成的有问题吧，能否再出一份详细的集成文档呢？从新建工程开始

**Comment by simpleton** [comment]
@zhuangzeqin 可以先跑sample，看是否可以跑通。如果接入的简便性，可以使用[tinkerpatch](tinkerpatch.com)或者bugly.

如下是tinkerpatch的各种[sample](https://github.com/TinkerPatch/tinkerpatch-easy-sample)

接入错误还是具体看log，没有log无法帮你debug。

**Comment by shwenzhang** [comment]
不能这么提问，自己先看日志定位
