### ISSUE TITLE
tinker有没有API能获取不需要下载补丁的结果？

### ISSUE THREAD

**Issue by 951AB159BA** [Tencent/tinker#568]
我发现，如果没有创建或下发任何补丁，App似乎没有任何一个回调API能收到这样的信息，即是不需要下载补丁或下载失败类似的信息。我的项目需求是，开启APP检查是否有补丁要升级或下载，如果没有，必须退出应用，必须强制使用补丁版的正式App。所以，请问，有没有一个方法，能回调是否需要下载补丁的结果，我需要判断是否正常使用而不是退出应用不能使用。因为，从日志打印看，没有特别明显的回调，只有load失败，但不能说明就是失败，其实应该还是可以正常使用。

**Comment by simpleton** [comment]
@951AB159BA tinker默认是没有后台的，需要你这边来开发，或者使用tinkerpatch或者bugly。
tinker本身的设计只是patch，这个强制的逻辑需要你这边来根据patchVersion来自己实现。

**Comment by shwenzhang** [comment]
这个需要自己自定义，类似配置文件的方式。
