### ISSUE TITLE
方便告知下微信，QQ或者腾讯的其他产品在GooglePlay是否采用了Tinker吗？

### ISSUE THREAD

**Issue by aesean** [Tencent/tinker#570]
Tinker确实非常好用，我们希望能在GooglePlay也能上架带有Tinker的版本。热更新会有被下架风险这个我明白。
逆向微信在GooglePlay版本的代码，发现了Tinker相关的类，这是否说明微信在GooglePlay的版本集成了跟Github同样版本的Tinker？另外如果微信确实在GooglePlay投放的apk是集成Tinker的，能分享下微信是如何平衡被GooglePlay下架的风险的吗？
以上方便的话，帮忙详细解答下，谢谢。

**Comment by syc8622374github** [comment]
py

**Comment by magicboylinw** [comment]
这个厉害了，估计没人会回答的～

**Comment by kongnanlive** [comment]
没人举报你没事的

**Comment by kirozhao** [comment]
微信在上架 Google Play 的版本是 禁用了 tinker 热补丁部分代码的（编译时开关屏蔽对 patch 拉取逻辑），为了方便没有专门去移除 tinker 的代码

这个问题没什么可隐瞒的

**Comment by aesean** [comment]
@kirozhao OK，明白了，谢谢。
