### ISSUE TITLE
线上大批量用户出现 app 运行黑屏，但是自己这边测试是没问题的，所以问下，能引起这类问题的原因是哪些？

### ISSUE THREAD

**Issue by lihuaib** [Tencent/tinker#573]
异常类型：线上大批量用户出现 app 运行黑屏，但是自己这边测试是没问题的，所以问下，能引起这类问题的原因是哪些？

手机型号：荣耀 3.0.1 系统， Funtouch OS 等

手机系统版本：都是 4.4.2

tinker版本：如:1.7.11

gradle版本：如:2.3.1

是否使用热更新SDK： 用了TinkerPatch SDK 和 Bugly SDK

系统：如:Mac

堆栈/日志： 无

**Comment by simpleton** [comment]
@lihuaib 有相关的log或者操作系统分布的数据么？

**Comment by shwenzhang** [comment]
4.4手机应该不会，这边可能引起的原因是系统ota之后的首次启动

**Comment by krmao** [comment]
就这么关掉了？怎么解决呀，我也遇到了

**Comment by krmao** [comment]
@shwenzhang

**Comment by krmao** [comment]
在 华为 MATE9 7.0 操作系统上， 进行 tinker线上热修复成功提醒用户重启后，再次启动 程序黑屏卡死，有较大的概率性，且第一次启动几乎100%黑屏
```
        classpath "com.tencent.bugly:symtabfileuploader:1.3.9"
        classpath "com.tencent.bugly:tinker-support:1.0.8"
```
@shwenzhang
