### ISSUE TITLE
tinkerEnabled设置为false的时候,默认的tinker_proguard.pro文件不会生成，导致tinker类的依赖类不在主dex，5.0以下手机会crash

### ISSUE THREAD

**Issue by pmathticol** [Tencent/tinker#575]
异常类型：app运行时异常/编译异常

tinker版本：如:1.7.11

gradle版本：如:2.2.3

没有使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

问题描述:
tinkerEnabled设置为false的时候,默认的tinker_proguard.pro文件不会生成，导致tinker类的依赖类不在主dex，5.0以下手机会crash

**Comment by shwenzhang** [comment]
手动将tinker需要的main dex pattern添加即可

**Comment by 08carmelo** [comment]
@shwenzhang 你好，我找到好几个issue都是这个回答， 关键是怎么添加呢？
