### ISSUE TITLE
请问使用基准包打补丁的问题

### ISSUE THREAD

**Issue by yugu91** [Tencent/tinker#576]
我已使用生产基准包大包 path 1;
客户已经使用了path 1包补丁；
然后我再更新一个补丁包 path 2, 这个patch2 应该使用 path 1 的基准包还是使用 生产的基准包？
我是不是应该先用生产基准包打一个补丁，再用 path 1的基准包打一个补丁？因为有可能一些客户还未更新 path 1

**Comment by shwenzhang** [comment]
patch包的基准包是用户手机上面安装的那个，请仔细查看文档
