### ISSUE TITLE
推荐使用的application写法是不是不支持kotlin？？

### ISSUE THREAD

**Issue by yijun135** [Tencent/tinker#579]
我使用kotlin写了一个继承自DefaultApplicationLike的类，然后rebuild一下以后并没有发现在generated/source/apt/下面并没有找到对应生成对应的类，然而使用Java写的可以生成。
现在这个annotation应该不支持kotlin的写法吧？？以后会不会计划支持呢？？

**Comment by shwenzhang** [comment]
这个跟编译有关，自动生成的代码的task可能不一样。自己写一个application就行
