### ISSUE TITLE
tinker patch exception

### ISSUE THREAD

**Issue by littleQia** [Tencent/tinker#58]
09-27 18:43:04.395 1729-1784/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{.../com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
09-27 18:43:04.401 1729-1784/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{.../com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
09-27 18:43:04.455 10644-10670/? I/Tinker.DefaultPatchReporter: patchReporter: patch exception path:/storage/emulated/0/patch_signed_7zip.apk, throwable:Attempt to read from field 'com.tencent.tinker.loader.shareutil.SharePatchInfo com.tencent.tinker.lib.tinker.TinkerLoadResult.patchInfo' on a null object reference, isUpgrade:true
09-27 18:43:04.456 10644-10670/? E/Tinker.DefaultPatchReporter: tinker patch exception  java.lang.NullPointerException: Attempt to read from field 'com.tencent.tinker.loader.shareutil.SharePatchInfo com.tencent.tinker.lib.tinker.TinkerLoadResult.patchInfo' on a null object reference
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:70)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:122)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
09-27 18:43:04.463 10644-10670/? I/Tinker.DefaultPatchReporter: patchReporter: patch all result path:/storage/emulated/0/patch_signed_7zip.apk, success:false, cost:70, isUpgrade:true
09-27 18:43:04.486 10644-10644/? D/Tinker.DefaultAppLike: onTrimMemory level:80
09-27 18:43:04.687 10613-10710/? I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                      PatchResult: 
                                                                      isUpgradePatch:true
                                                                      isSuccess:false
                                                                      rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                      costTime:70
                                                                      patchVersion:null
                                                                      patchTinkerID:106
                                                                      baseTinkerID:106
                                                                      Throwable:Attempt to read from field 'com.tencent.tinker.loader.shareutil.SharePatchInfo com.tencent.tinker.lib.tinker.TinkerLoadResult.patchInfo' on a null object reference

**Comment by littleQia** [comment]
@shwenzhang   这是由于我参数上的设置有问题么？还是流程都是正常的，是修复出了问题？

**Comment by shwenzhang** [comment]
请尝试使用1.6.2还有问题吗？

**Comment by littleQia** [comment]
用1.6.2可以了 谢谢。
