### ISSUE TITLE
补丁成功后重启崩溃，提示java.lang.ClassCastException: .MainActivity cannot be cast to .BaseActivity

### ISSUE THREAD

**Issue by cikichen** [Tencent/tinker#580]
···
08-18 18:45:02.213 3673-23094/? W/ActivityManager: autoboot: allow to start cpm from top activity.
08-18 18:45:02.215 3673-23094/? W/ActivityManager: autoboot: allow to start cpm from top activity.
08-18 18:45:02.392 12615-12615/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-18 18:45:02.444 12615-12615/? W/System.err: java.lang.ClassCastException: com.xxx.MainActivity cannot be cast to com.xxx.BaseActivity
···

**Comment by shwenzhang** [comment]
是否使用了 bugly sdk?

**Comment by littleQia** [comment]
我们也会出现这个问题，项目中确实集成了bugly，请问是有冲突么还是版本需要更新(现版本1.7.9) @shwenzhang

**Comment by shwenzhang** [comment]
这个是Bugly sdk的问题，请切换使用官方的或者联系他们解决
