### ISSUE TITLE
Android O oat dir bug

### ISSUE THREAD

**Issue by GoodnessJesus** [Tencent/tinker#582]
在1.8.1 tag上我发现了Android O oat目录问题。TinkerDexLoader#deleteOutOfDateOATFile函数删除的目录结构是“tinker/patch-641e634c/oat/”，而SharePatchFileUtil#optimizedPathFor函数返回的目录结构是“tinker/patch-641e634c/dex/oat/isa/***.odex”。所以，即使系统OTA，这个过时的oat文件也是删不掉的。本来是要提pr，但是dev分支并没有对应的函数。

**Comment by shwenzhang** [comment]
似乎是这样子的，不过android o之后其实不需要手动做解释模式执行了

**Comment by shwenzhang** [comment]
fixed by dev
