### ISSUE TITLE
PatchResult强制类型转换错误

### ISSUE THREAD

**Issue by 337240552** [Tencent/tinker#584]
java.lang.ClassCastException
com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult

![image](https://user-images.githubusercontent.com/329210/29645416-df57daea-88af-11e7-886e-897fcd91a70e.png)
热更新SDK： Bugly SDK
gradle版本：2.1.0
bugly tinker版本 ：tinker-support:1.0.8
出错机型：Oppo R11

**Comment by shwenzhang** [comment]
这个是bugly sdk的问题

**Comment by 337240552** [comment]
@shwenzhang AbstractResultService里面确实tinker下面的代码，而且跟bugly的人确认过

**Comment by ding33211** [comment]
同楼上OPPOR11，稳定出现

**Comment by sunshinehu** [comment]
同出现，有什么解决方案吗
