### ISSUE TITLE
补丁合成成功但是内容更新失败

### ISSUE THREAD

**Issue by kevinjqy** [Tencent/tinker#587]
异常类型：app运行时异常

手机型号：小米3 ，vivoX6 

手机系统版本：小米3（Android 6.0.1） ，vivoX6（Android 5.1） 

tinker版本：1.8.0

gradle版本：2.2.3

是否使用热更新SDK：  Bugly SDK

系统：win10

堆栈/日志：
08-29 11:46:23.538 6662-6662/com.intsig.BizCardReader W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
08-29 11:46:23.543 6662-6662/com.intsig.BizCardReader W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.intsig.BizCardReader count:1
08-29 11:46:23.548 6662-6662/com.intsig.BizCardReader W/Tinker.TinkerDexLoader: there is no dex to load
08-29 11:46:23.548 6662-6662/com.intsig.BizCardReader I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
08-29 11:46:23.563 6662-6662/com.intsig.BizCardReader D/Tinker.DefaultAppLike: onBaseContextAttached:
08-29 11:46:23.573 6662-6662/com.intsig.BizCardReader W/Tinker.TinkerLogUtil: new log level: 0
08-29 11:46:23.573 6662-6662/com.intsig.BizCardReader I/Tinker.TinkerPatchListener: application maxMemory:64
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader W/Tinker.Tinker: tinker patch directory: /data/data/com.intsig.BizCardReader/tinker
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.intsig.BizCardReader, main process:true, systemOTA:false, fingerPrint:samsung/t03gctc/t03gctc:4.3/JSS15J/N719KEUCML2:user/release-keys, oatDir:odex, useInterpretMode:false
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:641e31f8ea84624683c62e3c8e4db956, newVersion:641e31f8ea84624683c62e3c8e4db956, current:641e31f8ea84624683c62e3c8e4db956
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.intsig.BizCardReader/tinker, code: 0, cost: 55ms
08-29 11:46:23.578 6662-6662/com.intsig.BizCardReader I/Tinker.TinkerLoadReporter: onLoadResult回调 :rstCode==0     cost==55
08-29 11:46:23.603 6662-6662/com.intsig.BizCardReader D/Tinker.DefaultAppLike: onCreate
08-29 11:46:23.893 6662-6662/com.intsig.BizCardReader W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:173)
08-29 11:46:24.123 6662-6736/com.intsig.BizCardReader E/Tinker.TinkerManager: getListPatchJson  api = https://log-sandbox.intsig.net
08-29 11:46:24.123 6662-6736/com.intsig.BizCardReader E/Tinker.TinkerManager: getListPatchJson  url = https://log-sandbox.intsig.net/hotpatch/get_list_patch
08-29 11:46:24.128 6662-6736/com.intsig.BizCardReader E/Tinker.TinkerManager: getListPatchJson  post body = {"device_model":"SCH-N719","os":"Android","market":"Market","bundle_id":"com.intsig.camcard.android","app_version":"7.33.0","env":"Dev","lang":"zh-cn","os_version":"4.3.0"}
08-29 11:46:24.278 6662-6736/com.intsig.BizCardReader E/Tinker.TinkerManager:   请求成功   result={"ret":"0","data":[{"patch_url":"https:\/\/log-sandbox.intsig.net\/hotpatch\/download_patch?patch_id=f01ee66717ee22dbf7cb80d6e1f67428","patch_id":"f01ee66717ee22dbf7cb80d6e1f67428","patch_version":0,"offline_support":"0"}],"err":""}
08-29 11:46:24.278 6662-6736/com.intsig.BizCardReader E/Tinker.TinkerManager:  getpatchinfo path: https://log-sandbox.intsig.net/hotpatch/download_patch?patch_id=f01ee66717ee22dbf7cb80d6e1f67428
08-29 11:46:24.443 6662-6761/com.intsig.BizCardReader I/DownloadFileService: tinker补丁地址:https://log-sandbox.intsig.net/hotpatch/download_patch?patch_id=f01ee66717ee22dbf7cb80d6e1f67428
08-29 11:46:24.488 6662-6662/com.intsig.BizCardReader W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/data/com.intsig.BizCardReader/tinker_temp/temp.apk is not exist, just return

**Comment by shwenzhang** [comment]
bugly sdk请联系他们的团队
