### ISSUE TITLE
 合成成功 loadCode -2

### ISSUE THREAD

**Issue by mgdxy256** [Tencent/tinker#588]
合成成功 load的时候 loadCode 一直返回-2 。

异常类型：app运行时异常

手机型号：Xiaomi 5s plus

手机系统版本：Android 6.01

tinker版本：如:1.8.0

gradle版本：如:3.5

是否使用热更新SDK：否

系统：Windows

堆栈/日志：
错误日志
08-29 17:32:38.768 32309-32309/com.yfcreate.learn W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yfcreate.learn/tinker
08-29 17:32:38.769 32309-32309/com.yfcreate.learn I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.0
08-29 17:32:38.769 32309-32309/com.yfcreate.learn I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.yfcreate.learn, main process:true, systemOTA:false, fingerPrint:Xiaomi/natrium/natrium:6.0.1/MXB48T/V8.5.4.0.MBGCNED:user/release-keys, oatDir:null, useInterpretMode:false
08-29 17:32:38.769 32309-32309/com.yfcreate.learn W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
08-29 17:32:38.769 32309-32309/com.yfcreate.learn I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.yfcreate.learn/tinker, code: -2, cost: 4ms
08-29 17:32:38.770 32309-32309/com.yfcreate.learn W/Tinker.Tinker: tinker load fail!
08-29 17:32:38.770 32309-32309/com.yfcreate.learn D/Tinker.DefaultAppLike: onCreate
08-29 17:32:38.915 32309-32309/com.yfcreate.learn W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
08-29 17:32:39.653 1310-2089/? I/ActivityManager: START u0 {cmp=com.yfcreate.learn/.ui.tinker.TinkerActivity} from uid 10298 on display 0
08-29 17:32:39.747 1310-1441/? I/ActivityManager: Displayed com.yfcreate.learn/.ui.tinker.TinkerActivity: +83ms
08-29 17:32:40.008 1310-1441/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{5d6fdbb u0 com.yfcreate.learn/.ui.tinker.TinkerActivity t4102} time:161776765
08-29 17:32:55.452 32309-32309/com.yfcreate.learn I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:3452
08-29 17:32:55.455 32309-32309/com.yfcreate.learn I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2

合成日志
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:E:\Library\Learn\app\build\bakApk/app-debug-0829-17-19-50.apk
newApk:E:\Library\Learn\app\build\outputs\apk\app-debug.apk
outputFolder:E:\Library\Learn\app\build\outputs/tinkerPatch/debug
isIgnoreWarning:false
isProtectedApp:false
7-ZipPath:C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:tinker is sample to use
filed name:platform, filed value:all
filed name:patchVersion, filed value:1.0
dex configs: 
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.yfcreate.learn.comm.BaseBuildInfo
dex loader:com.tencent.tinker.loader.*
dex loader:com.yfcreate.learn.BaseApplication
lib configs: 
libPattern:lib/.*/.*\.so
resource configs: 
resPattern:AndroidManifest\.xml
resPattern:assets/.*
resPattern:res/.*
resPattern:resources\.arsc
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: app-debug-0829-17-19-50.apk, size=12394451, md5=c6232b0250a895d379887e046a1cde04
new apk: app-debug.apk, size=12394407, md5=e73a01237d7be4d759f74a1b2ed00ad0
UnZipping apk to E:\Library\Learn\app\build\outputs\tinkerPatch\debug\app-debug-0829-17-19-50
UnZipping apk to E:\Library\Learn\app\build\outputs\tinkerPatch\debug\app-debug
Check for loader classes in dex: classes.dex
found modify resource: resources.arsc, but it is logically the same as original new resources.arsc, just ignore!

Gen classes.dex patch file:E:\Library\Learn\app\build\outputs\tinkerPatch\debug\tinker_result\classes.dex, size:486, md5:7acd1c0112a9bcf0fbf9b2964cc094ad
Verifying if patched new dex is logically the same as original new dex: app-debug/classes.dex ...

Gen classes.dex for dalvik full dex file:E:\Library\Learn\app\build\outputs\tinkerPatch\debug\tempPatchedDexes\classes.dex, size:6113840, md5:6fcb0d2106070637772075bea40f3614
DexDecoder:write meta file data: classes.dex,,6fcb0d2106070637772075bea40f3614,6fcb0d2106070637772075bea40f3614,7acd1c0112a9bcf0fbf9b2964cc094ad,2179007922,3786175652,jar

Add test install result dex: E:\Library\Learn\app\build\outputs\tinkerPatch\debug\tinker_result\test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,0,jar
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
Result: final signed patch result: E:\Library\Learn\app\build\outputs\tinkerPatch\debug\patch_signed.apk, size=3452
Result: final signed with 7zip patch result: E:\Library\Learn\app\build\outputs\tinkerPatch\debug\patch_signed_7zip.apk, size=3833
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 381 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 4.548000s
Tinker patch done, you can go to file to find the output E:\Library\Learn\app\build\outputs/tinkerPatch/debug
-----------------------Tinker patch end-------------------------

**Comment by zijing07** [comment]
大哥为啥关闭了，我也是一样的问题，请问是调整了哪里？
