### ISSUE TITLE
我们App在Android7.1.1的一些机型上面Bugly上报了Tinker里面发生的类型转换错误导致的崩溃，这是什么问题呢

### ISSUE THREAD

**Issue by sunshinehu** [Tencent/tinker#589]
bugly堆栈：

1 com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(SourceFile:64)
--
2 android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
3 android.os.Handler.dispatchMessage(Handler.java:102)
4 android.os.Looper.loop(Looper.java:185)
5 android.os.HandlerThread.run(HandlerThread.java:61)

Bugly Log：

0ete path: /data/user/0/com.**/tinker/patch-02e4f57b/dex/classes.dex.jar
108-29 21:28:21.078 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/dex/classes2.dex.jar
208-29 21:28:21.078 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/dex/classes3.dex.jar
308-29 21:28:21.078 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/dex/test.dex.jar
408-29 21:28:21.078 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/dex
508-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/odex/classes.dex.dex
608-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/odex/classes2.dex.dex
708-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/odex/classes3.dex.dex
808-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/odex/test.dex.dex
908-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b/odex
1008-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch-02e4f57b
1108-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker/patch.info
1208-29 21:28:21.079 27381 27559 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker
1308-29 21:28:21.187 27617 27617 I art : Starting a blocking GC AddRemoveAppImageSpace
1408-29 21:28:21.203 27617 27617 W Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
1508-29 21:28:21.203 27617 27617 D Tinker.DefaultAppLike: onBaseContextAttached:
1608-29 21:28:21.210 27617 27617 I MultiDex: VM with version 2.1.0 has multidex support
1708-29 21:28:21.210 27617 27617 I MultiDex: install
1808-29 21:28:21.210 27617 27617 I MultiDex: VM has multidex support, MultiDex support library is disabled.
1908-29 21:28:21.214 27617 27617 D Tinker.DefaultAppLike: onCreate
2008-29 21:28:21.215 27617 27617 D Tinker.DefaultAppLike: onTrimMemory level:5
2108-29 21:28:21.252 27617 27632 W Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.**/tinker/patch.info (No such file or directory)
2208-29 21:28:21.252 27617 27632 W Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.**/tinker/patch.info (No such file or directory)
2308-29 21:28:21.385 27381 27635 D Event : No subscribers registered for event class aae
2408-29 21:28:21.385 27381 27635 D Event : No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
2508-29 21:28:21.547 27381 27415 D libc-netbsd: [getaddrinfo]: hostname=m.data.mob.com; servname=(null); app_pid=27381; app_uid=10124; ai_flags=1024; ai_family=0; ai_socktype=1 from prox result 0
2608-29 21:28:22.411 27381 27489 D libc-netbsd: [getaddrinfo]: hostname=ip.taobao.com; servname=(null); app_pid=27381; app_uid=10124; ai_flags=1024; ai_family=0; ai_socktype=1 from prox result 0
2708-29 21:28:22.495 27617 27622 I art : Do partial code cache collection, code=31KB, data=29KB
2808-29 21:28:22.495 27617 27622 I art : After code cache collection, code=16KB, data=15KB
2908-29 21:28:22.495 27617 27622 I art : Increasing code cache capacity to 128KB
3008-29 21:28:22.618 27381 27489 D libc-netbsd: [getaddrinfo]: hostname=ip.cn; servname=(null); app_pid=27381; app_uid=10124; ai_flags=1024; ai_family=0; ai_socktype=1 from prox result 0
3108-29 21:28:23.357 27641 27641 W cat : type=1400 audit(0.0:133940): avc: denied { read } for name="address" dev="sysfs" ino=30096 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
3208-29 21:28:23.391 27381 27642 E CheckPermission: _bluetooth code = 1
3308-29 21:28:23.394 27381 27642 E CheckPermission: _bluetooth code = 14
3408-29 21:28:23.744 27381 27489 E System : ********** PLEASE READ ************
3508-29 21:28:23.744 27381 27489 E System : *
3608-29 21:28:23.744 27381 27489 E System : * New versions of the Android SDK no longer support the Crypto provider.
3708-29 21:28:23.744 27381 27489 E System : * If your app was relying on setSeed() to derive keys from strings, you
3808-29 21:28:23.744 27381 27489 E System : * should switch to using SecretKeySpec to load raw key bytes directly OR
3908-29 21:28:23.744 27381 27489 E System : * use a real key derivation function (KDF). See advice here :
4008-29 21:28:23.744 27381 27489 E System : * http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html
4108-29 21:28:23.744 27381 27489 E System : ***********************************
4208-29 21:28:23.744 27381 27489 E System : Returning an instance of SecureRandom from the Crypto provider
4308-29 21:28:23.744 27381 27489 E System : as a temporary measure so that the apps targeting earlier SDKs
4408-29 21:28:23.744 27381 27489 E System : keep working. Please do not rely on the presence of the Crypto
4508-29 21:28:23.744 27381 27489 E System : provider in the codebase, as our plan is to delete it
4608-29 21:28:23.744 27381 27489 E System : completely in the future.
4708-29 21:28:23.827 27617 27622 I art : Do partial code cache collection, code=55KB, data=55KB
4808-29 21:28:23.828 27617 27622 I art : After code cache collection, code=45KB, data=46KB
4908-29 21:28:23.828 27617 27622 I art : Increasing code cache capacity to 256KB
5008-29 21:28:24.436 27381 27652 E System : ********** PLEASE READ ************
5108-29 21:28:24.436 27381 27652 E System : *
5208-29 21:28:24.436 27381 27652 E System : * New versions of the Android SDK no longer support the Crypto provider.
5308-29 21:28:24.436 27381 27652 E System : * If your app was relying on setSeed() to derive keys from strings, you
5408-29 21:28:24.436 27381 27652 E System : * should switch to using SecretKeySpec to load raw key bytes directly OR
5508-29 21:28:24.436 27381 27652 E System : * use a real key derivation function (KDF). See advice here :
5608-29 21:28:24.436 27381 27652 E System : * http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html
5708-29 21:28:24.436 27381 27652 E System : ***********************************
5808-29 21:28:24.436 27381 27652 E System : Returning an instance of SecureRandom from the Crypto provider
5908-29 21:28:24.436 27381 27652 E System : as a temporary measure so that the apps targeting earlier SDKs
6008-29 21:28:24.436 27381 27652 E System : keep working. Please do not rely on the presence of the Crypto
6108-29 21:28:24.436 27381 27652 E System : provider in the codebase, as our plan is to delete it
6208-29 21:28:24.436 27381 27652 E System : completely in the future.
6308-29 21:28:25.021 27381 27489 D Event : No subscribers registered for event class com.**.eventbus.LastedMessageEvent
6408-29 21:28:25.021 27381 27489 D Event : No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
6508-29 21:28:25.707 27489 27489 W DEFAULT_SINGLE_: type=1400 audit(0.0:133941): avc: denied { getattr } for path="/proc/iomem" dev="proc" ino=4026532126 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_iomem:s0 tclass=file permissive=0
6608-29 21:28:25.707 27489 27489 W DEFAULT_SINGLE_: type=1400 audit(0.0:133942): avc: denied { getattr } for path="/proc/sysrq-trigger" dev="proc" ino=4026532195 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_sysrq:s0 tclass=file permissive=0
6708-29 21:28:25.733 27381 27489 I DpmTcmClient: RegisterTcmMonitor from: org.apache.http.impl.conn.TcmIdleTimerMonitor
6808-29 21:28:29.564 27381 27667 E System : ********** PLEASE READ ************
6908-29 21:28:29.564 27381 27667 E System : *
7008-29 21:28:29.564 27381 27667 E System : * New versions of the Android SDK no longer support the Crypto provider.
7108-29 21:28:29.564 27381 27667 E System : * If your app was relying on setSeed() to derive keys from strings, you
7208-29 21:28:29.564 27381 27667 E System : * should switch to using SecretKeySpec to load raw key bytes directly OR
7308-29 21:28:29.564 27381 27667 E System : * use a real key derivation function (KDF). See advice here :
7408-29 21:28:29.564 27381 27667 E System : * http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html
7508-29 21:28:29.564 27381 27667 E System : ***********************************
7608-29 21:28:29.564 27381 27667 E System : Returning an instance of SecureRandom from the Crypto provider
7708-29 21:28:29.564 27381 27667 E System : as a temporary measure so that the apps targeting earlier SDKs
7808-29 21:28:29.564 27381 27667 E System : keep working. Please do not rely on the presence of the Crypto
7908-29 21:28:29.564 27381 27667 E System : provider in the codebase, as our plan is to delete it
8008-29 21:28:29.564 27381 27667 E System : completely in the future.
8108-29 21:28:29.611 27617 27622 I art : Do full code cache collection, code=126KB, data=107KB
8208-29 21:28:29.613 27617 27622 I art : Starting a blocking GC JitCodeCache
8308-29 21:28:29.613 27617 27622 I art : After code cache collection, code=78KB, data=60KB
8408-29 21:28:29.657 27381 27664 D libc-netbsd: [getaddrinfo]: hostname=uphzv6.ys7.com; servname=(null); app_pid=27381; app_uid=10124; ai_flags=0; ai_family=2; ai_socktype=1 from prox result 0
8508-29 21:28:29.821 27381 27664 I PlayerSDK: EGL Version = EGL 1.4
8608-29 21:28:31.581 27617 27617 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w640dp h342dp 480dpi nrml long land finger -keyb/v/h -nav/h s.147mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
8708-29 21:28:31.600 27526 27526 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w640dp h342dp 480dpi nrml long land finger -keyb/v/h -nav/h s.147mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
8808-29 21:28:31.605 27573 27573 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w640dp h342dp 480dpi nrml long land finger -keyb/v/h -nav/h s.147mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
8908-29 21:28:31.630 27381 27381 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w640dp h342dp 480dpi nrml long land finger -keyb/v/h -nav/h s.147mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
9008-29 21:28:32.492 27617 27617 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w360dp h622dp 480dpi nrml long port finger -keyb/v/h -nav/h s.148mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
9108-29 21:28:32.492 27573 27573 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w360dp h622dp 480dpi nrml long port finger -keyb/v/h -nav/h s.148mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
9208-29 21:28:32.510 27526 27526 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w360dp h622dp 480dpi nrml long port finger -keyb/v/h -nav/h s.148mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
9308-29 21:28:32.608 27381 27381 D Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc65535mnc [zh_CN] ldltr sw360dp w360dp h622dp 480dpi nrml long port finger -keyb/v/h -nav/h s.148mThemeChanged = 0mThemeChangedFlags = 0mFlipFont = 0}
9408-29 21:28:33.517 27698 27698 W cat : type=1400 audit(0.0:133943): avc: denied { read } for name="address" dev="sysfs" ino=30096 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
9508-29 21:28:33.610 27381 27645 D libc-netbsd: [getaddrinfo]: hostname=c.data.mob.com; servname=(null); app_pid=27381; app_uid=10124; ai_flags=1024; ai_family=0; ai_socktype=1 from prox result 0
9608-29 21:28:34.492 27381 27553 D SMACK : 09:28:34 下午 SENT (68023251): <iq id="QbDer-4" type="set"><ping xmlns='urn:xmpp:ping'/></iq>
9708-29 21:28:34.633 27381 27554 D SMACK : 09:28:34 下午 RCV (68023251): <iq id="QbDer-4" type="result"/>
9808-29 21:28:34.633 27381 27554 D PacketReader: starttag...parser...iq
9908-29 21:28:35.178 27381 27702 E VideoRender: SurfaceDestroyed wait context
10008-29 21:28:35.186 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
10108-29 21:28:35.190 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
10208-29 21:28:35.192 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
10308-29 21:28:35.193 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
10408-29 21:28:35.435 27617 27622 I art : Do partial code cache collection, code=123KB, data=103KB
10508-29 21:28:35.436 27617 27622 I art : After code cache collection, code=92KB, data=74KB
10608-29 21:28:35.436 27617 27622 I art : Increasing code cache capacity to 512KB
10708-29 21:28:36.881 27617 27704 W art : oat_file_name = /data/user/0/com.**/tinker/patch-ad27e9e3/odex/classes.dex.dex, b = 1
10808-29 21:28:36.881 27617 27703 W art : oat_file_name = /data/user/0/com.**/tinker/patch-ad27e9e3/odex/classes2.dex.dex, b = 1
10908-29 21:28:36.944 27706 27706 I dex2oat : Adjusted thread count : 4
11008-29 21:28:36.945 27705 27705 I dex2oat : Adjusted thread count : 4
11108-29 21:28:36.945 27706 27706 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.**/tinker/patch-ad27e9e3/dex/classes2.dex.jar --oat-fd=46 --oat-location=/data/user/0/com.**/tinker/patch-ad27e9e3/odex/classes2.dex.dex --compiler-filter=speed
11208-29 21:28:36.945 27705 27705 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.**/tinker/patch-ad27e9e3/dex/classes.dex.jar --oat-fd=45 --oat-location=/data/user/0/com.**/tinker/patch-ad27e9e3/odex/classes.dex.dex --compiler-filter=speed
11308-29 21:28:37.736 27705 27711 W dex2oat : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
11408-29 21:28:39.697 27381 27716 E System : ********** PLEASE READ ************
11508-29 21:28:39.697 27381 27716 E System : *
11608-29 21:28:39.697 27381 27716 E System : * New versions of the Android SDK no longer support the Crypto provider.
11708-29 21:28:39.697 27381 27716 E System : * If your app was relying on setSeed() to derive keys from strings, you
11808-29 21:28:39.697 27381 27716 E System : * should switch to using SecretKeySpec to load raw key bytes directly OR
11908-29 21:28:39.697 27381 27716 E System : * use a real key derivation function (KDF). See advice here :
12008-29 21:28:39.697 27381 27716 E System : * http://android-developers.blogspot.com/2016/06/security-crypto-provider-deprecated-in.html
12108-29 21:28:39.697 27381 27716 E System : ***********************************
12208-29 21:28:39.697 27381 27716 E System : Returning an instance of SecureRandom from the Crypto provider
12308-29 21:28:39.697 27381 27716 E System : as a temporary measure so that the apps targeting earlier SDKs
12408-29 21:28:39.697 27381 27716 E System : keep working. Please do not rely on the presence of the Crypto
12508-29 21:28:39.697 27381 27716 E System : provider in the codebase, as our plan is to delete it
12608-29 21:28:39.697 27381 27716 E System : completely in the future.
12708-29 21:28:40.458 27381 27719 D libc-netbsd: [getaddrinfo]: hostname=uphzv3.ys7.com; servname=(null); app_pid=27381; app_uid=10124; ai_flags=0; ai_family=2; ai_socktype=1 from prox result 0
12808-29 21:28:40.582 27705 27712 W dex2oat : Compilation of boolean android.support.constraint.solver.widgets.ConstraintWidgetContainer.a(android.support.constraint.solver.LinearSystem) took 260.790ms
12908-29 21:28:40.590 27381 27719 I PlayerSDK: EGL Version = EGL 1.4
13008-29 21:28:44.896 27381 27728 D libc-netbsd: [getaddrinfo]: hostname=uphzv3.ys7.com; servname=(null); app_pid=27381; app_uid=10124; ai_flags=0; ai_family=2; ai_socktype=1 from prox result 0
13108-29 21:28:45.071 27381 27728 I PlayerSDK: EGL Version = EGL 1.4
13208-29 21:28:46.129 27706 27714 W dex2oat : Compilation of void com.**.realplay.MultiRealPlayActivity.c() took 145.695ms
13308-29 21:28:47.588 27705 27711 W dex2oat : Compilation of java.lang.String com.ezviz.ezdatasource.compiler.RepositoryClass.brewJava() took 225.337ms
13408-29 21:28:47.648 27705 27710 W dex2oat : Compilation of void com.ezviz.ezdatasource.db.RealmDao.setCondition(aqo, com.ezviz.ezdatasource.db.Condition) took 252.239ms
13508-29 21:28:48.274 27705 27712 W dex2oat : Compilation of void com.facebook.csslayout.LayoutEngine.layoutNodeImpl(com.facebook.csslayout.CSSLayoutContext, com.facebook.csslayout.CSSNode, float, float, com.facebook.csslayout.CSSDirection, com.facebook.csslayout.CSSMeasureMode, com.facebook.csslayout.CSSMeasureMode, boolean) took 338.023ms
13608-29 21:28:48.668 27706 27715 W dex2oat : Compilation of void oi.a(oj) took 106.453ms
13708-29 21:28:48.946 27381 27702 E VideoRender: SurfaceDestroyed wait context
13808-29 21:28:48.952 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
13908-29 21:28:48.953 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
14008-29 21:28:48.953 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
14108-29 21:28:48.954 27381 27702 I Adreno : DequeueBuffer: dequeueBuffer failed
14208-29 21:28:48.980 27381 27718 E PlayerSDK: eglDisplay or eglSurface NULL
14308-29 21:28:50.365 27706 27706 I dex2oat : dex2oat took 13.420s (threads: 4) arena alloc=5MB (5723136B) java alloc=6MB (6326992B) native alloc=30MB (32424680B) free=9MB (9911576B)
14408-29 21:28:50.393 27617 27703 W art : oat_file_name = /data/user/0/com.**/tinker/patch-ad27e9e3/odex/classes3.dex.dex, b = 1
14508-29 21:28:50.446 27734 27734 I dex2oat : Adjusted thread count : 4
14608-29 21:28:50.446 27734 27734 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.**/tinker/patch-ad27e9e3/dex/classes3.dex.jar --oat-fd=46 --oat-location=/data/user/0/com.**/tinker/patch-ad27e9e3/odex/classes3.dex.dex --compiler-filter=speed
14708-29 21:28:50.670 27705 27705 I dex2oat : dex2oat took 13.725s (threads: 4) arena alloc=12MB (12639304B) java alloc=5MB (6243256B) native alloc=31MB (33515016B) free=15MB (16554488B)
14808-29 21:28:50.699 27617 27704 W art : oat_file_name = /data/user/0/com.**/tinker/patch-ad27e9e3/odex/test.dex.dex, b = 1
14908-29 21:28:50.751 27736 27736 I dex2oat : Adjusted thread count : 4
15008-29 21:28:50.752 27736 27736 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/com.**/tinker/patch-ad27e9e3/dex/test.dex.jar --oat-fd=45 --oat-location=/data/user/0/com.**/tinker/patch-ad27e9e3/odex/test.dex.dex --compiler-filter=speed
15108-29 21:28:50.858 27736 27736 I dex2oat : dex2oat took 107.388ms (threads: 4) arena alloc=11KB (11736B) java alloc=32KB (32840B) native alloc=758KB (777136B) free=1289KB (1320016B)
15208-29 21:28:52.315 27734 27734 I dex2oat : dex2oat took 1.869s (threads: 4) arena alloc=4MB (4734448B) java alloc=1676KB (1716528B) native alloc=7MB (7488680B) free=6MB (7191384B)
15308-29 21:28:52.334 27617 27632 I Tinker.ParallelDex: All dexes are optimized successfully, cost: 15458 ms.
15408-29 21:28:53.493 27617 27632 I Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.**/tinker/patch.info , oldVer:, newVer:ad27e9e35e203d69e104fb09a0d314d2, fingerprint:OPPO/R11Plus/R11Plus:7.1.1/NMF26X/1495339184:user/release-keys, oatDir:odex
15508-29 21:28:53.495 27617 27632 I Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.**/tinker_temp/temp.apk
15608-29 21:28:53.518 27617 27617 D Tinker.DefaultAppLike: onTrimMemory level:80

**Comment by shwenzhang** [comment]
bugly相关问题，请先联系bugly. 或者尝试使用官方的tinker，因为有很多问题是因为第三方的实现导致的

**Comment by sunshinehu** [comment]
@shwenzhang 感谢回复，但是我们只集成了Bugly的崩溃捕获，Tinker是自己集成的，不是使用Bugly提供的

**Comment by shwenzhang** [comment]
具体的异常信息贴的再详细一点，类型转换错误的提示
