### ISSUE TITLE
vivo x9s Plus加载patch容和失败

### ISSUE THREAD

**Issue by HUAIHU234** [Tencent/tinker#595]
异常类型：app运行加载patch容和失败

手机型号：vivo x9s Plus

手机系统版本：Android 7.1.1 

tinker版本：1.8.1

gradle版本：2.14.1

是否使用热更新SDK：TinkerPatch SDK

系统：Mac os

堆栈/日志：
09-06 16:33:58.586 27648-27648/? D/Tinker.DefaultAppLike: onCreate
09-06 16:33:58.616 27675-27675/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.paic.zhifu.wallet.activity/tinker
09-06 16:33:58.617 27675-27675/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-06 16:33:58.621 27675-27675/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.paic.zhifu.wallet.activity/tinker
09-06 16:33:58.622 27675-27675/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
09-06 16:33:58.622 27675-27675/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.paic.zhifu.wallet.activity:update, main process:false, systemOTA:false, fingerPrint:vivo/PD1635/PD1635:7.1.1/NMF26F/compil08151019:user/release-keys, oatDir:null, useInterpretMode:false
09-06 16:33:58.622 27675-27675/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
09-06 16:33:58.622 27675-27675/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.paic.zhifu.wallet.activity/tinker, code: -2, cost: 3ms
09-06 16:33:58.629 27675-27675/? W/Tinker.Tinker: tinker load fail!
09-06 16:33:58.629 27675-27675/? D/Tinker.DefaultAppLike: onCreate
09-06 16:34:30.599 27586-27586/? D/Tinker.DefaultAppLike: onTrimMemory level:20
09-06 16:40:11.027 3408-4769/? I/ActivityManager: START u0 {cmp=com.paic.zhifu.wallet.activity/.test.YQBTinkerTest} from uid 10330 on display 0
09-06 16:40:11.028 4577-4615/? D/YJ_DBG: safeCenterAPP  com.paic.zhifu.wallet.activity com.paic.zhifu.wallet.activity.test.YQBTinkerTest
09-06 16:40:11.072 4577-5307/? V/pem: noteActivity uid = 10330, cool = 1, name = com.paic.zhifu.wallet.activity.test.YQBTinkerTest
09-06 16:40:11.072 3408-3812/? I/UsageStatsService: reportEvent delete:com.paic.zhifu.wallet.activity.test.YQBTinkerTest
09-06 16:40:11.089 27586-27634/? D/DataCollector: av5.5.0ntWIFIaid00Ic1156k5t3lt1504687211089sid6c7eb51e-4a67-4476-8d16-7d8e6805f58durlYQBTinkerTestdid97c1a5fe-d5e2-4cf3-b93a-7bf722378821sv1.0_lgst0et1504687211089ac88888ip172.20.34.71refYQBTestMainActivitymidda02dba7-1539-40f9-8c43-ff54a7bc1214lid10
09-06 16:40:11.093 27586-27708/? I/TDLog: onResume being called! pageName: test.YQBTinkerTest, FromAPI: false
09-06 16:40:11.096 27586-27708/? I/SkyEyeLog: onResume being called! pageName: test.YQBTinkerTest, FromAPI: false
09-06 16:40:11.108 27586-27586/? D/c: YQBTinkerTest Hook Click View Count: 1
09-06 16:40:11.165 3408-3841/? I/ActivityManager: Displayed com.paic.zhifu.wallet.activity/.test.YQBTinkerTest: +97ms
09-06 16:40:33.848 27586-27634/? D/DataCollector: uidntWIFI_AutoIdStringtv_tinker_testex1504687233847sv1.0lt1504687233847aid00Ic1156k5lid11av5.5.0did97c1a5fe-d5e2-4cf3-b93a-7bf722378821et1504687233847sid6c7eb51e-4a67-4476-8d16-7d8e6805f58d_lgst0ip172.20.34.71enAutoClick_AutoTextTinker 测试_mcIdac88888midda02dba7-1539-40f9-8c43-ff54a7bc1214gpt5
09-06 16:40:33.851 27586-27586/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
09-06 16:40:33.864 3408-29110/? I/ActivityManager: Start proc 29226:com.paic.zhifu.wallet.activity:patch/u0a330 for service com.paic.zhifu.wallet.activity/com.tencent.tinker.lib.service.TinkerPatchService
09-06 16:40:33.912 29226-29226/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
09-06 16:40:33.913 29226-29226/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-06 16:40:33.917 29226-29226/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.paic.zhifu.wallet.activity/tinker
09-06 16:40:33.918 29226-29226/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
09-06 16:40:33.918 29226-29226/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.paic.zhifu.wallet.activity:patch, main process:false, systemOTA:false, fingerPrint:vivo/PD1635/PD1635:7.1.1/NMF26F/compil08151019:user/release-keys, oatDir:null, useInterpretMode:false
09-06 16:40:33.918 29226-29226/? W/Tinker.TinkerLoadResult: tinker is disable, just return
09-06 16:40:33.919 29226-29226/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.paic.zhifu.wallet.activity/tinker, code: -1, cost: 3ms
09-06 16:40:33.926 29226-29226/? W/Tinker.Tinker: tinker load fail!
09-06 16:40:33.926 29226-29226/? D/Tinker.DefaultAppLike: onCreate
09-06 16:40:34.004 29226-29226/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/PAMobileWallet/download/yqb_patch_temp.jar, code: -4
09-06 16:40:34.059 29226-29255/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
09-06 16:40:34.062 29226-29255/? W/Tinker.UpgradePatchRetry: try copy file: /storage/sdcard0/Download/release/yqb_patch.jar to /data/user/0/com.paic.zhifu.wallet.activity/tinker_temp/temp.apk
09-06 16:40:34.064 29226-29255/? I/Tinker.TinkerPatchService: try to increase patch process priority
09-06 16:40:34.071 3408-3813/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.paic.zhifu.wallet.activity/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
09-06 16:40:34.086 3408-3813/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.paic.zhifu.wallet.activity/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
09-06 16:40:34.109 29226-29255/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:ad31957a3e30f6f80f55347631cee70f
09-06 16:40:34.110 29226-29255/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch.info (No such file or directory)
09-06 16:40:34.110 29226-29255/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch.info (No such file or directory)
09-06 16:40:34.110 29226-29255/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a
09-06 16:40:34.111 29226-29255/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/sdcard0/Download/release/yqb_patch.jar size: 14907, dest file: /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/patch-ad31957a.apk size:14907
09-06 16:40:34.117 29226-29255/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/changed_classes.dex.jar
09-06 16:40:34.130 29226-29255/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-06 16:40:34.130 29226-29255/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/test.dex.jar
09-06 16:40:34.132 29226-29255/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-06 16:40:34.139 29226-29255/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/test.dex.jar
09-06 16:40:34.139 29226-29255/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/tinker_classN.apk, result: true, size: 470, use: 7ms
09-06 16:40:34.140 29226-29255/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:2, optimizeDexDirectory:/data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/odex/
09-06 16:40:34.140 29226-29255/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/changed_classes.dex.jar, size: 12874
09-06 16:40:34.159 29226-29255/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/changed_classes.dex.jar, opt file:/data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/odex/changed_classes.dex.dex, opt file size: 0, use time 19
09-06 16:40:34.159 29226-29255/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/tinker_classN.apk, size: 470
09-06 16:40:34.163 29226-29255/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/dex/tinker_classN.apk, opt file:/data/user/0/com.paic.zhifu.wallet.activity/tinker/patch-ad31957a/odex/tinker_classN.dex, opt file size: 0, use time 4
09-06 16:40:34.163 29226-29255/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:51
09-06 16:40:34.163 29226-29255/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
09-06 16:40:34.163 29226-29255/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
09-06 16:40:34.163 29226-29255/? I/Tinker.DexDiffPatchInternal: raw dex count: 2, dex opt dex count: 2, final wait times: 16
09-06 16:40:34.164 29226-29255/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file changed_classes.dex.dex is not exist, just wait 1 times
09-06 16:40:49.165 29226-29255/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file changed_classes.dex.dex is not exist, just wait 2 times

**Comment by shwenzhang** [comment]
这个是异步dex2oat,需要等待
