### ISSUE TITLE
tryLoadPatchFiles:patch dir not exist

### ISSUE THREAD

**Issue by littleQia** [Tencent/tinker#60]
![vxd8r 5qdx lqz2o k rw_](https://cloud.githubusercontent.com/assets/22090724/18898123/300bd6aa-8562-11e6-9d73-f0c27ca98869.png)

我在ApplicationLike的onBaseContextAttached方法里面调用了TinkerInstaller.install(this)，在oncreate里面调用了TinkerInstaller.onReceiveUpgradePatch方法。图片是报错

**Comment by 7heaven** [comment]
-2是文件不存在 看一下补丁文件地址是不是正确

**Comment by littleQia** [comment]
我看了一下，-2是好像是补丁的父文件夹不存在，但是这个是tinker自己创建的应该 @7heaven

**Comment by shwenzhang** [comment]
第一次加载都没有合成当然找不到。然后在合成的时候，报的时候找不到补丁文件，请确认已经推到手机正确的位置

**Comment by littleQia** [comment]
DefaultLoadReporter: patch load Reporter: patch receive fail:/storage/emulated/0/patch_signed_7zip.apk, code:-2, isUpgrade:true    这应该是表明补丁包已经推到正确位置了吧，只是找不到patch dir

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/18899986/e19ccf5c-856f-11e6-8753-11b1e5d70c94.png)

**Comment by littleQia** [comment]
啊 不好意思，之前看代码里面的命名 还以为-2是目录文件夹没有。  后面再试了一下 确实不会报这个了，但是还是报这个
![q qf n 7i 4_a0t6n hv5i](https://cloud.githubusercontent.com/assets/22090724/18903238/7d33f7f0-858a-11e6-95aa-e8277f155863.png)

**Comment by shwenzhang** [comment]
需要将合成过程的日志打出来，才能知道具体的错误原因

**Comment by littleQia** [comment]
合成过程的日志，是指gradlew tinker开始打印出来的日志么，那个很长啊，需要全部打出来么？？

**Comment by shwenzhang** [comment]
不是，也是手机上面的。:process的日志，先看一下文档吧

**Comment by littleQia** [comment]
不好所以问一下，：process日志是在哪里看的。。文档哪里有提到，我去看一下

**Comment by Drizzlezhang** [comment]
@littleQia 我遇到了同样的问题，请问下你是怎么解决的

**Comment by littleQia** [comment]
@Drizzlezhang 我用了1.6.2版本之后就好了
