### ISSUE TITLE
如何给patch包设置version，如何在获取当前应用里安装的补丁的version？

### ISSUE THREAD

**Issue by mr-xia** [Tencent/tinker#602]
如题啊，谢谢！

**Comment by O-Childe** [comment]
ShareConstants.OLD_VERSION 和 ShareConstants.NEW_VERSION

**Comment by mr-xia** [comment]
@O-Childe  对不起，我没动这是什么意思，能详细一点吗？谢谢

**Comment by O-Childe** [comment]
不好意思，我搞错了   我也在研究怎么设置补丁包的versionName。项目中默认是的补丁版本号是pathch-[补丁包md5值的前8位]

**Comment by mr-xia** [comment]
@O-Childe 项目中默认是的补丁版本号应该怎么获取呢？

**Comment by O-Childe** [comment]
去看看UpgradePatch类把
