### ISSUE TITLE
打补丁后无法正确的获取到对应语言的字符资源

### ISSUE THREAD

**Issue by gplcn** [Tencent/tinker#607]
tinker版本：1.7.11
gradle版本：2.14.1
是否使用热更新SDK：  TinkerPatch SDK 
系统：Mac
堆栈/日志：无
问题：通过以下方式来实现中英文切换，发现如果修改了布局文件的布局，打Release环境下的补丁后再切换中英文时，在代码中通过context.getResources().getString(strRes);方法获取到的字符始终是中文资源。
`  Locale locale = new Locale(languageToLoad);
        Locale.setDefault(locale);
        Configuration config = new Configuration();
        config.locale = locale;
        getBaseContext().getResources().updateConfiguration(config, 
        getBaseContext().getResources().getDisplayMetrics());`

**Comment by shwenzhang** [comment]
duplicate #302
暂时可以通过使用方式规避
