### ISSUE TITLE
关于修复启动新activity的求助

### ISSUE THREAD

**Issue by yanhaogoogle** [Tencent/tinker#61]
如果修复代码里面需要使用到新的activity页面，那么有没有比较的好的方法去实现修复呢？
个人设想：在app里面一开始就设置一些不用的activity先把地方站着，如果以后需要修复代码里面业务需要使用新的activity就去在这些以前站着没用的activity里面去添加代码，这种设想不知道可行不？

**Comment by 7heaven** [comment]
之前有相同的issue#19

可以选择预先添加一个activity占位，或者选择一个Activity 多个Fragment的方案，

**Comment by yanhaogoogle** [comment]
@7heaven 好的，我测试试试看，3Q
