### ISSUE TITLE
关于自定义Aplication是否一定要继承DefaultApplicationLike问题

### ISSUE THREAD

**Issue by D-Rusty** [Tencent/tinker#612]
您好，我的项目中不会涉及到自定义Application热修复，请问在这情况下，我一定要集成DefaultApplicationLike吗，如果不需要继承的话，那我应该在代码中做哪些配置，我现在已经完成了build.gradle文件的配置，谢谢

**Comment by shwenzhang** [comment]
查看文档，不建议特殊方式的接入。若想减少接入工作量，可使用tinkerpatch一键接入方式
