### ISSUE TITLE
7.0的设备上报错：找不到resources.apk

### ISSUE THREAD

**Issue by ICECHN** [Tencent/tinker#614]
使用最新的tinker版本，补丁包发布后有发现很多异常信息：
android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/MY_PACKAGE_NAME_XXX/tinker/patch-bdcf021a/res/resources.apk

主要是7.0的设备

**Comment by grace88888884** [comment]
请问这个问题是怎么解决的？

**Comment by 1860Sonic** [comment]
同文 7.0手机大量报错
java.lang.RuntimeException: Unable to create service com.google.android.gms.measurement.AppMeasurementService: java.lang.RuntimeException: Unable to create application com.stub.StubApp: android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/com.xxx/tinker/patch-7abe9053/res/resources.apk
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3345)
