### ISSUE TITLE
应用运行，so库报异常，应用强制退出

### ISSUE THREAD

**Issue by liyuzero** [Tencent/tinker#616]
## Issue/提问须知

异常类型：app运行时异常

手机型号：努比亚Z17

手机系统版本：如:Android 7.0 

tinker版本：如:1.8.1

gradle版本：如:2.3.1

编译SDK：26

是否使用热更新SDK： 否

系统：Win

堆栈/日志：
56:00.385 27859-27913/? W/art: 0xd3a57a98
09-22 16:56:00.385 27859-27913/? W/System.err: Application uncaught exception in thread "Thread-8" java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.sss-1/lib/arm/libstlport_shared.so" already opened by ClassLoader 0x100223; can't open in ClassLoader 0xd3a57af4
09-22 16:56:00.386 27859-27913/? W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:989)
09-22 16:56:00.386 27859-27913/? W/System.err:     at java.lang.System.loadLibrary(System.java:1530)

工程中引用到了libstlport_shared.so库
基准包和补丁包生成成功，所有手机安装基准包都能正常运行。安装补丁时，部分手机会报上述错误，而部分手机打补丁成功。

**Comment by shwenzhang** [comment]
so不能使用两个不同的classloader去加载，可以直接使用TinkerLoadLibrary反射的方式去加载so

**Comment by ethanhua** [comment]
@shwenzhang 我也出现了这个问题，系统版本7.0以上，加载so的代码包含在第三方sdk中不好修改，tinker中什么情况下会出现两个不同的classloader?

**Comment by pmathticol** [comment]
同样遇到了，所以是怎么解决的

**Comment by whikko** [comment]
请教一下这个问题是怎么解决的？我也出现了
