### ISSUE TITLE
当热更新进程执行到这里的时候，如果强制把进程杀掉，之后就再也打不上这个补丁了

### ISSUE THREAD

**Issue by frankqianghe** [Tencent/tinker#617]
异常类型：app执行异常

tinker版本：1.8.1

gradle版本：3.3

是否使用热更新SDK： 是

当热更新进程执行到这里的时候，如果强制把进程杀掉，之后就再也打不上这个补丁了，执行cleanPatch清除之后再打也不行

09-24 01:02:53.083 31308-31308/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:5255
09-24 01:02:53.090 31308-31308/? I/Tinker.SamplePatchListener: get platform:all
09-24 01:02:53.109 3180-3222/? I/ActivityManager: Start proc 31717:com.tinkertest.xiaop_android:patch/u0a294 for service com.tinkertest.xiaop_android/com.tencent.tinker.lib.service.TinkerPatchService
09-24 01:02:53.194 31717-31717/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
09-24 01:02:53.195 31717-31717/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-24 01:02:53.196 31717-31717/? I/Tinker.SamplePatchListener: application maxMemory:256
09-24 01:02:53.198 31717-31717/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.tinkertest.xiaop_android/tinker
09-24 01:02:53.198 31717-31717/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.0
09-24 01:02:53.198 31717-31717/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.tinkertest.xiaop_android:patch, main process:false, systemOTA:false, fingerPrint:samsung/dream2qltezc/dream2qltechn:7.0/NRD90M/G9550ZCU1AQH6:user/release-keys, oatDir:null, useInterpretMode:false
09-24 01:02:53.198 31717-31717/? W/Tinker.TinkerLoadResult: tinker is disable, just return
09-24 01:02:53.198 31717-31717/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.tinkertest.xiaop_android/tinker, code: -1, cost: 4ms
09-24 01:02:53.198 31717-31717/? W/Tinker.Tinker: tinker load fail!
09-24 01:02:53.200 31717-31717/? D/Tinker.DefaultAppLike: onCreate
09-24 01:02:53.239 31717-31717/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
09-24 01:02:53.239 31717-31733/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
09-24 01:02:53.241 31717-31733/? I/Tinker.TinkerPatchService: try to increase patch process priority
09-24 01:02:53.244 3180-3226/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.tinkertest.xiaop_android/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0))
09-24 01:02:53.264 3180-3226/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.tinkertest.xiaop_android/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0))
09-24 01:02:53.315 31717-31733/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:acf9b589ee327f0038bfe9f962527aa2
09-24 01:02:53.316 31717-31733/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.tinkertest.xiaop_android/tinker/patch.info (No such file or directory)
09-24 01:02:53.316 31717-31733/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.tinkertest.xiaop_android/tinker/patch.info (No such file or directory)
09-24 01:02:53.317 31717-31733/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589
09-24 01:02:53.318 31717-31733/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/patch_signed_7zip.apk size: 5255, dest file: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/patch-acf9b589.apk size:5255
09-24 01:02:59.418 31717-31733/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/classes.dex.jar, size: 3419181, use time: 6090
09-24 01:03:01.931 31717-31733/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/classes2.dex.jar, size: 3761630, use time: 2513
09-24 01:03:01.932 31717-31733/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/classes3.dex.jar
09-24 01:03:02.677 31717-31733/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-24 01:03:02.750 31717-31733/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/test.dex.jar
09-24 01:03:02.752 31717-31733/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-24 01:03:03.041 31717-31733/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/test.dex.jar
09-24 01:03:03.041 31717-31733/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/classes2.dex.jar
09-24 01:03:03.041 31717-31733/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/classes.dex.jar
09-24 01:03:03.041 31717-31733/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/classes3.dex.jar
09-24 01:03:03.041 31717-31733/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/tinker_classN.apk, result: true, size: 9899552, use: 289ms
09-24 01:03:03.042 31717-31733/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/odex/
09-24 01:03:03.043 31717-31733/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.tinkertest.xiaop_android/tinker/patch-acf9b589/dex/tinker_classN.apk, size: 9899552

如果再执行热更新就报以下错误:

09-24 01:15:05.692 1749-1749/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:5255
09-24 01:15:05.696 1749-1749/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -3

**Comment by shwenzhang** [comment]
patch进程依然存在，杀掉patch进程即可
