### ISSUE TITLE
系统层app热更新要重启手机才能生效,结束进程无效

### ISSUE THREAD

**Issue by zuoyuan333** [Tencent/tinker#618]
手机型号：三星 sm-9350

手机系统版本  Android 7.0 Android 4.4

tinker版本：1.7.11

gradle版本：2.2.3

是否使用热更新SDK：  Bugly SDK  1.0.8

系统层app热更新要重启手机才能生效 , 结束进程无效 . 有没有什么方案可以跳过重启?

**Comment by shwenzhang** [comment]
系统app的dex与apk是分离的，这块我们没有相关的实践经验。按照原理，只要强制app重新加载dex即可
