### ISSUE TITLE
补丁包版本号怎么获取

### ISSUE THREAD

**Issue by gydhy8** [Tencent/tinker#621]
有两种情况：
1.初次发的安装包有紧急bug修复，怎么判断有新的补丁要下载？
2.打过补丁的app，再有新的补丁发布，app里怎么判断要不要更新补丁？

关键是怎么比对补丁的版本号问题，总不能每次启动只要请求到补丁包，都下载补丁包，然后尝试打补丁吧？

**Comment by shwenzhang** [comment]
可以在补丁的meta data中记录，也可以在其他方式。具体要看你跟后台如何配合
