### ISSUE TITLE
清缓存，版本回退了

### ISSUE THREAD

**Issue by msrlin** [Tencent/tinker#623]
异常类型：app运行时异常

手机型号：如:三星S6 EDG   G9520
手机系统版本：6.1

tinker版本：如:1.8.1

gradle版本：如:2.3.3

是否使用热更新SDK： 无
系统：如:win10

 手机清缓存，版本回退到打插件之前的状态

**Comment by weinierfei** [comment]
你那不叫清缓存,你那叫做清除应用数据

**Comment by msrlin** [comment]
为什么会这样，当时2个一起清除的 @weinierfei
