### ISSUE TITLE
加载手机本地补丁失败

### ISSUE THREAD

**Issue by seldomxiaodong** [Tencent/tinker#624]
异常类型：app运行时异常

手机型号：xiaomi6

手机系统版本：Android 7.1.1 

tinker版本：1.8.1

gradle版本：4.0

是否使用热更新SDK： TinkerPatch SDK

系统：windows

堆栈/日志：
09-29 17:22:08.225 28718-28718/com.pekall.tinkerdemo I/Tinker.TinkerServerPatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:3586
09-29 17:22:08.230 28718-28718/com.pekall.tinkerdemo I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2

调用代码：
File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath()+"/patch_signed_7zip.apk");
                Log.e("xiaodong","file exist:" + file.exists() + file.isFile());
                TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(),
                        Environment.getExternalStorageDirectory().getAbsolutePath()
                                +"/patch_signed_7zip.apk");
补丁文件是存在的，但不生效

**Comment by shwenzhang** [comment]
tinkerpatch需要配合tinekrpatch后台做测试的
