### ISSUE TITLE
patch 合成失败

### ISSUE THREAD

**Issue by joyerf** [Tencent/tinker#625]
异常类型：合成失败

手机型号：全智 T3

手机系统版本：Android 6.0.1

tinker版本：1.7.11

gradle版本：4.2

是否使用热更新SDK： Bugly SDK

系统：Mac

堆栈/日志：
09-29 20:11:54.161 6900-6900/xxxxxxxx I/CrashReport: patch download success !!!
09-29 20:11:54.164 6900-6900/xxxxxxxx D/CrashReport: copy /data/user/0/xxxxxxxx/app_tmpPatch/a378e623-24bf-4396-a4f2-3190630a9024.zip to /data/user/0/xxxxxxxx/app_tmpPatch/tmpPatch.apk success!
09-29 20:11:54.164 6900-6900/xxxxxxxx D/CrashReport: delete temp file
09-29 20:11:54.212 6900-6900/xxxxxxxx D/Tinker.TinkerManager: onDownloadSuccess.
09-29 20:11:54.212 6900-6900/xxxxxxxx D/Tinker.TinkerManager: check if has new patch.
09-29 20:11:54.256 6900-6900/xxxxxxxx D/Tinker.TinkerManager: has new patch.
09-29 20:11:54.257 6900-6900/xxxxxxxx D/Tinker.TinkerManager: starting patch.
09-29 20:11:54.258 6900-6900/xxxxxxxx I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/xxxxxxxx/app_tmpPatch/tmpPatch.apk, file size:4909
09-29 20:11:54.265 6900-6900/xxxxxxxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/user/0/xxxxxxxx/app_tmpPatch/tmpPatch.apk, code: -5

ERROR_PATCH_JIT

**Comment by joyerf** [comment]
怀疑是gradle 版本比较高导致。
 java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by vanroving** [comment]
dexOptions{
        jumboMode =true
    }
 app的gradle里是不是加了这段代码？去掉就好了

**Comment by shwenzhang** [comment]
这个是因为这个手机在6.0的时候编译选项打开了JIT，可能会对patch产生影响，会对这部分手机关闭patch功能

**Comment by franksight** [comment]
怎么解决的？我也碰上这个问题了，也是android6.0的，搞死人了。。。别的安卓 系统版本都没问题

**Comment by Jesen-H** [comment]
解决了吗？
