### ISSUE TITLE
提示补丁加载成功但是没有生效

### ISSUE THREAD

**Issue by oceanbin** [Tencent/tinker#626]
异常类型：提示补丁加载成功但是没有生效

手机型号：Nexus 5

手机系统版本：Android6.0

tinker版本：1.8.1

gradle版本：2.3.2

是否使用热更新SDK： 集成的Tinker1.8.1源码

系统：windows7

09-30 17:04:26.928 10073-10073/com.xxx.xxx I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:7760
09-30 17:04:26.932 10073-10073/com.xxx.xxx W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
09-30 17:04:26.939 10073-10073/com.xxx.xxx I/Tinker.SamplePatchListener: get platform:all
09-30 17:04:27.001 19653-19653/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
09-30 17:04:27.003 19653-19653/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-30 17:04:27.006 19653-19653/? I/Tinker.SamplePatchListener: application maxMemory:192
09-30 17:04:27.009 19653-19653/? W/Tinker.Tinker: tinker patch directory: /data/data/com.xxx.xxx/tinker
09-30 17:04:27.009 19653-19653/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
09-30 17:04:27.013 19653-19653/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.xxx.xxx:patch, main process:false, systemOTA:false, fingerPrint:google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys, oatDir:null, useInterpretMode:false
09-30 17:04:27.013 19653-19653/? W/Tinker.TinkerLoadResult: tinker is disable, just return
09-30 17:04:27.013 19653-19653/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.xxx.xxx/tinker, code: -1, cost: 3ms
09-30 17:04:27.013 19653-19653/? W/Tinker.Tinker: tinker load fail!
09-30 17:04:27.013 19653-19653/? D/Tinker.DefaultAppLike: onCreate
09-30 17:04:27.078 19653-19653/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
09-30 17:04:27.079 19653-19693/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
09-30 17:04:27.081 19653-19693/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch_signed_7zip.apk to /data/data/com.xxx.xxx/tinker_temp/temp.apk
09-30 17:04:27.088 19653-19693/? I/Tinker.TinkerPatchService: try to increase patch process priority
09-30 17:04:27.125 19653-19693/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:80858a8a3808e94f0a3dfba803af3e62
09-30 17:04:27.134 19653-19693/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/com.xxx.xxx/tinker/patch.info: open failed: ENOENT (No such file or directory)
09-30 17:04:27.134 19653-19693/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/com.xxx.xxx/tinker/patch.info: open failed: ENOENT (No such file or directory)
09-30 17:04:27.135 19653-19693/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.xxx.xxx/tinker/patch-80858a8a
09-30 17:04:27.137 19653-19693/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/patch_signed_7zip.apk size: 7760, dest file: /data/data/com.xxx.xxx/tinker/patch-80858a8a/patch-80858a8a.apk size:7760
09-30 17:04:34.566 19653-19693/com.xxx.xxx:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/classes.dex.jar, size: 3325151, use time: 7404
09-30 17:04:38.295 19653-19693/com.xxx.xxx:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/classes2.dex.jar, size: 1768361, use time: 3728
09-30 17:04:38.295 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/test.dex.jar
09-30 17:04:38.296 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-30 17:04:38.535 19653-19693/com.xxx.xxx:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/test.dex.jar
09-30 17:04:38.535 19653-19693/com.xxx.xxx:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/classes2.dex.jar
09-30 17:04:38.537 19653-19693/com.xxx.xxx:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/classes.dex.jar
09-30 17:04:38.540 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: merge classN dex file /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/tinker_classN.apk, result: true, size: 5093942, use: 244ms
09-30 17:04:38.540 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/data/com.xxx.xxx/tinker/patch-80858a8a/odex/
09-30 17:04:38.541 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/tinker_classN.apk, size: 5093942
09-30 17:04:47.217 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/tinker_classN.apk, opt file:/data/data/com.xxx.xxx/tinker/patch-80858a8a/odex/tinker_classN.dex, opt file size: 29045168, use time 8676
09-30 17:04:47.217 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:20079
09-30 17:04:47.217 19653-19693/com.xxx.xxx:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
09-30 17:04:47.218 19653-19693/com.xxx.xxx:patch I/Tinker.ResDiffPatchInternal: res dir: /data/data/com.xxx.xxx/tinker/patch-80858a8a/res/, meta: resArscMd5:87ea2356bda5e9b3d85d5e6abe9afc9e
                                                                                 arscBaseCrc:3005526629
                                                                                 pattern:res/.*
                                                                                 pattern:resources\.arsc
                                                                                 pattern:assets/.*
                                                                                 addedSet:assets/only_use_to_test_tinker_resource.txt
                                                                                 modifiedSet:res/layout/atom_ui_fragmet_main_setting.xml
                                                                                 modifiedSet:res/layout-v17/atom_ui_fragmet_main_setting.xml
09-30 17:04:47.235 19653-19693/com.xxx.xxx:patch I/Tinker.ResDiffPatchInternal: no large modify resources, just return
09-30 17:04:48.096 19653-19693/com.xxx.xxx:patch I/Tinker.ResDiffPatchInternal: final new resource file:/data/data/com.xxx.xxx/tinker/patch-80858a8a/res/resources.apk, entry count:1933, size:8404166
09-30 17:04:48.096 19653-19693/com.xxx.xxx:patch I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:878
09-30 17:04:48.096 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: raw dex count: 3, dex opt dex count: 1, final wait times: 24
09-30 17:04:48.098 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/data/com.xxx.xxx/tinker/patch-80858a8a/odex/tinker_classN.dex, size 29045168
09-30 17:04:48.098 19653-19693/com.xxx.xxx:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file format: tinker_classN.dex, size 29045168
09-30 17:04:48.100 19653-19693/com.xxx.xxx:patch I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/data/com.xxx.xxx/tinker/patch.info , oldVer:, newVer:80858a8a3808e94f0a3dfba803af3e62, fingerprint:google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys, oatDir:odex
09-30 17:04:48.101 19653-19693/com.xxx.xxx:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
09-30 17:04:48.101 19653-19693/com.xxx.xxx:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/patch_signed_7zip.apk, success: true, cost: 21013
09-30 17:04:48.101 19653-19693/com.xxx.xxx:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker_temp/temp.apk
09-30 17:04:48.111 10073-20403/com.xxx.xxx I/Tinker.SampleResultService: SampleResultService receive result: 
                                                                          PatchResult: 
                                                                          isSuccess:true
                                                                          rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                                          costTime:21013
                                                                          patchVersion:80858a8a3808e94f0a3dfba803af3e62
09-30 17:04:48.143 10073-20403/com.xxx.xxx W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /storage/emulated/0/patch_signed_7zip.apk
09-30 17:04:48.143 10073-20403/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/patch_signed_7zip.apk
09-30 17:04:48.144 10073-20403/com.xxx.xxx I/Tinker.SampleResultService: tinker wait screen to restart process
09-30 17:04:59.478 10073-10073/com.xxx.xxx D/Tinker.DefaultAppLike: onTrimMemory level:20
09-30 17:05:01.679 20968-20968/com.xxx.xxx:amd W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
09-30 17:05:01.681 20968-20968/com.xxx.xxx:amd D/Tinker.DefaultAppLike: onBaseContextAttached:
09-30 17:05:01.685 20968-20968/com.xxx.xxx:amd I/Tinker.SamplePatchListener: application maxMemory:192
09-30 17:05:01.687 20968-20968/com.xxx.xxx:amd W/Tinker.Tinker: tinker patch directory: /data/data/com.xxx.xxx/tinker
09-30 17:05:01.688 20968-20968/com.xxx.xxx:amd I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
09-30 17:05:01.688 20968-20968/com.xxx.xxx:amd I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xxx.xxx:amd, main process:false, systemOTA:false, fingerPrint:google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys, oatDir:odex, useInterpretMode:false
09-30 17:05:01.688 20968-20968/com.xxx.xxx:amd I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:80858a8a3808e94f0a3dfba803af3e62, current:
09-30 17:05:01.688 20968-20968/com.xxx.xxx:amd E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
09-30 17:05:01.688 20968-20968/com.xxx.xxx:amd I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.xxx.xxx/tinker, code: -5, cost: 6ms
09-30 17:05:01.688 20968-20968/com.xxx.xxx:amd W/Tinker.Tinker: tinker load fail!
09-30 17:05:01.689 20968-20968/com.xxx.xxx:amd D/Tinker.DefaultAppLike: onCreate
09-30 17:05:01.792 20968-20968/com.xxx.xxx:amd W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
09-30 17:05:03.892 21022-21022/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
09-30 17:05:03.896 21022-21022/com.xxx.xxx D/Tinker.TinkerInternals: same fingerprint:google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys
09-30 17:05:03.896 21022-21022/com.xxx.xxx I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/data/com.xxx.xxx/tinker/patch.info , oldVer:80858a8a3808e94f0a3dfba803af3e62, newVer:80858a8a3808e94f0a3dfba803af3e62, fingerprint:google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys, oatDir:odex
09-30 17:05:03.901 21022-21022/com.xxx.xxx W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.xxx.xxx count:1
09-30 17:05:03.913 21022-21022/com.xxx.xxx I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-1/lib/arm, /vendor/lib, /system/lib]]]
09-30 17:05:03.913 21022-21022/com.xxx.xxx I/Tinker.TinkerDexLoader: verify dex file:/data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/tinker_classN.apk md5, use time: 0
09-30 17:05:03.913 21022-21022/com.xxx.xxx I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/data/com.xxx.xxx/tinker/patch-80858a8a/odex, dex size:1
09-30 17:05:03.917 21022-21022/com.xxx.xxx I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/tinker_classN.apk", zip file "/data/app/com.xxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-1/lib/arm, /vendor/lib, /system/lib]]], dex size:1
09-30 17:05:03.919 21022-21022/com.xxx.xxx W/Tinker.ClassLoaderAdder: checkDexInstall result:false
09-30 17:05:03.920 21022-21022/com.xxx.xxx E/Tinker.TinkerDexLoader: install dexes failed
09-30 17:05:03.921 21022-21022/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
09-30 17:05:03.924 21022-21022/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
09-30 17:05:03.928 21022-21022/com.xxx.xxx I/Tinker.SamplePatchListener: application maxMemory:192
09-30 17:05:03.930 21022-21022/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/data/com.xxx.xxx/tinker
09-30 17:05:03.931 21022-21022/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
09-30 17:05:03.931 21022-21022/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.xxx.xxx, main process:true, systemOTA:false, fingerPrint:google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys, oatDir:odex, useInterpretMode:false
09-30 17:05:03.931 21022-21022/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:80858a8a3808e94f0a3dfba803af3e62, current:80858a8a3808e94f0a3dfba803af3e62
09-30 17:05:03.932 21022-21022/com.xxx.xxx I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
09-30 17:05:03.932 21022-21022/com.xxx.xxx E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
09-30 17:05:03.938 21022-21022/com.xxx.xxx I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
09-30 17:05:03.938 21022-21022/com.xxx.xxx E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
09-30 17:05:03.939 21022-21022/com.xxx.xxx E/Tinker.DefaultLoadReporter: tinker load exception  com.qunar.fix.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                              at com.qunar.fix.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:84)
                                                                              at com.qunar.fix.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
                                                                              at com.qunar.fix.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:255)
                                                                              at com.qunar.fix.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.qunar.fix.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:161)
                                                                              at com.qunar.fix.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:130)
                                                                              at com.qunar.fix.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                                              at android.app.Application.attach(Application.java:181)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:996)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:980)
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
09-30 17:05:03.939 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/info.lock
09-30 17:05:03.940 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/patch-80858a8a.apk
09-30 17:05:03.940 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex/tinker_classN.apk
09-30 17:05:03.944 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/dex
09-30 17:05:03.945 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/odex/tinker_classN.dex
09-30 17:05:03.945 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/odex
09-30 17:05:03.945 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/res/resources.apk
09-30 17:05:03.955 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a/res
09-30 17:05:03.955 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch-80858a8a
09-30 17:05:03.955 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker/patch.info
09-30 17:05:03.955 21022-21022/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.xxx.xxx/tinker
09-30 17:05:03.956 21022-21022/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.xxx.xxx/tinker, code: -14, cost: 79ms
09-30 17:05:03.956 21022-21022/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
09-30 17:05:03.969 21022-21022/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate
09-30 17:05:04.222 21022-21022/com.xxx.xxx W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/data/com.xxx.xxx/tinker_temp/temp.apk is not exist, just return
09-30 17:09:31.466 21022-21022/com.xxx.xxx D/Tinker.DefaultAppLike: onTrimMemory level:20

**Comment by oceanbin** [comment]
把public static final String CHECK_DEX_CLASS = "com.**.**.loader.TinkerTestDexLoad"还原成public static final String CHECK_DEX_CLASS = "com.tencent.tinker.loader.TinkerTestDexLoad"这个就好了 不知道为什么？因为我是集成的源码 而且包名有改动，改成我自己的包名的话，checkDexInstall方法会返回false然后抛异常，改回com.tencent.tinker.loader.TinkerTestDexLoad这个就ok了，费解。。。。有人知道原因的话，求告知！

**Comment by shwenzhang** [comment]
这个是用来校验的类啊

**Comment by oceanbin** [comment]
意思是必须是这个类名？
