### ISSUE TITLE
patch_unsigned.apk无法自动签名

### ISSUE THREAD

**Issue by xdhuangsidi** [Tencent/tinker#627]
异常类型：编译异常

tinker版本：1.8.1

gradle版本：2.2.0

是否使用热更新SDK： Bugly SDK

系统：linux

问题描述     把useSign参数设置为false可以生产未签名的补丁包，但是直接导入tinker-sample-android项目进去AS，发现当useSign设置为true 无法生产签名包

log信息：
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA

java.io.IOException: Can't Generate signed APK. Please check if your sign info is correct.
	at com.tencent.tinker.build.builder.PatchBuilder.signApk(PatchBuilder.java:144)

**Comment by yuanxiaofan** [comment]
请问楼主问题解决解决了吗？

**Comment by a8stefan** [comment]
楼主解决了没

**Comment by xdhuangsidi** [comment]
> 楼主解决了没

我的在linux系统下，java环境没配全，导致签名失败，我装了jdk8完整版，然后跑签名成功了。检查下环境变量是否正确。

**Comment by qiaojiuyuan** [comment]
我是windows系统，我也报了这个错，一开始我编译补丁包的时候，使用的是git Bash的窗口执行的命令编译，后来在cmd的dos窗口编译就好了....
