### ISSUE TITLE
Could not get unknown property : apkVariantData for object com.android.build.gradle.internal.api.ApplicationVariantImpl

### ISSUE THREAD

**Issue by blackberry2016** [Tencent/tinker#628]
集成编译出错
version 1.8.1
Android Studio 3 beta7
build tool vetsion 26.0.2
complileTarget 26

Could not get unknown property : apkVariantData for object com.android.build.gradle.internal.api.ApplicationVariantImpl

**Comment by blackberry2016** [comment]
Link Pull Request :  https://github.com/Tencent/tinker/pull/620

**Comment by shwenzhang** [comment]
duplicate #495 dev已经fix，今日会发布新版本
