### ISSUE TITLE
版本规划1.7.0版本功能－资源自动校验，渠道包支持

### ISSUE THREAD

**Issue by shwenzhang** [Tencent/tinker#63]
1. 资源反射校验；当前在微信中的资源校验是并没有放到Tinker中，对于Tinker资源在编译时自动修改字符串值，反射之后校验是否真正生效；

2. 渠道包flavor更加好的支持；

3. apk-parser引用库的bugfix

预计国庆后可以实现，当前版本资源的校验需要自己手动加上。

**Comment by dodola** [comment]
Mark

**Comment by h3r3x3** [comment]
有时间表吗，预计什么时候发1.7？

**Comment by liuxang** [comment]
加入了AndResGuard后，要怎么处理？

**Comment by shwenzhang** [comment]
@h3r3x3 ，国庆后应该可以

**Comment by shwenzhang** [comment]
@liuxang , 需要apply 资源混淆的mapping

**Comment by bigbigbigbigbig** [comment]
patch与tinker的版本相关吗？如1.7.0patch包能打上1.6.1的old_apk上不？

**Comment by shwenzhang** [comment]
补丁合成与加载的时候肯定用的是1.6.1的版本，如果版本不一样，在编译的时候会出warning

**Comment by shwenzhang** [comment]
可以的，只要把ignoreWarning改为true就可以编译了。只要底层核心的diff算法没有改变即可做到向下兼容

**Comment by liuxang** [comment]
是不是就是把AndResGuard的resource_mapping_app-release.txt的内容全部copy到mapping中？

**Comment by shwenzhang** [comment]
不是，两次编译AndResGuard采用前一次的mapping，跟tinker无关

**Comment by kongnanlive** [comment]
@shwenzhang DefaultTinkerResultService里面能不能可配置下，为了不在成功应用补丁后"自杀"，我还得自己写个Service，这样直接用TinkerInstaller.install(appLike)就好了。

**Comment by shwenzhang** [comment]
Sample只是一个事例，让大家了解tinker这个框架，任何定制的功能都可以通过复写来达到。

**Comment by kongnanlive** [comment]
@shwenzhang 答非说问，只能麻烦点了。tinker这种高定制化真的很棒！

**Comment by jorry** [comment]
加固什么时候支持

**Comment by zhoujunqz** [comment]
@liuxang 如何添加AndResGuard的resource_mapping_app-release.txt？解决了吗
