### ISSUE TITLE
我编译的时候用的Raw模式，并且loadVerifyFlag也没打开，是false,是不是这样就会造成运行的时候类不完整，导致崩溃

### ISSUE THREAD

**Issue by frankqianghe** [Tencent/tinker#639]
异常类型：app运行时异常

手机型号：如:Galasy S8+

手机系统版本：Android 7.0

tinker版本：如:1.8.1

gradle版本：2.3

是否使用热更新SDK： 否

系统：Mac

以下是我打上补丁之后，运行的时候的报错

堆栈/日志：
10-22 15:09:13.633 22038-22038/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
10-22 15:09:13.633 22038-22038/? D/Tinker.TinkerInternals: same fingerprint:samsung/dream2qltezc/dream2qltechn:7.0/NRD90M/G9550ZCU1AQH6:user/release-keys
10-22 15:09:13.636 22038-22038/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.temp.xiaop_android count:1
10-22 15:09:13.639 22038-22038/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.temp.xiaop_android/.cache/secData.jar", zip file "/data/app/com.temp.xiaop_android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.temp.xiaop_android-1/lib/arm, /system/fake-libs, /data/app/com.temp.xiaop_android-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]]
10-22 15:09:13.639 22038-22038/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.temp.xiaop_android/tinker/patch-95f8b63c/dex/tinker_classN.apk md5, use time: 0
10-22 15:09:13.639 22038-22038/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.temp.xiaop_android/tinker/patch-95f8b63c/odex, dex size:2
10-22 15:09:13.647 22038-22038/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[dex file "/data/user/0/com.temp.xiaop_android/tinker/patch-95f8b63c/dex/changed_classes.dex", zip file "/data/user/0/com.temp.xiaop_android/tinker/patch-95f8b63c/dex/tinker_classN.apk", zip file "/data/user/0/com.temp.xiaop_android/.cache/secData.jar", zip file "/data/app/com.temp.xiaop_android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.temp.xiaop_android-1/lib/arm, /system/fake-libs, /data/app/com.temp.xiaop_android-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]], dex size:2
10-22 15:09:13.647 22038-22038/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
10-22 15:09:13.647 22038-22038/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
10-22 15:09:13.656 22038-22038/? D/Tinker.DefaultAppLike: onBaseContextAttached:
10-22 15:09:13.657 22038-22038/? I/Tinker.SamplePatchListener: application maxMemory:256
10-22 15:09:13.659 22038-22038/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.temp.xiaop_android/tinker
10-22 15:09:13.659 22038-22038/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
10-22 15:09:13.660 22038-22038/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.temp.xiaop_android, main process:true, systemOTA:false, fingerPrint:samsung/dream2qltezc/dream2qltechn:7.0/NRD90M/G9550ZCU1AQH6:user/release-keys, oatDir:odex, useInterpretMode:false
10-22 15:09:13.660 22038-22038/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:95f8b63cfc5356377f38e07399a23135, newVersion:95f8b63cfc5356377f38e07399a23135, current:95f8b63cfc5356377f38e07399a23135
10-22 15:09:13.660 22038-22038/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
10-22 15:09:13.660 22038-22038/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.temp.xiaop_android/tinker, code: 0, cost: 38ms
10-22 15:09:13.675 22038-22038/? D/Tinker.DefaultAppLike: onCreate
10-22 15:09:13.838 22038-22083/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.temp.passportsdk.util.PreferenceUtil" on path: DexPathList[[dex file "/data/user/0/com.temp.xiaop_android/tinker/patch-95f8b63c/dex/changed_classes.dex", zip file "/data/user/0/com.temp.xiaop_android/tinker/patch-95f8b63c/dex/tinker_classN.apk", zip file "/data/user/0/com.temp.xiaop_android/.cache/secData.jar", zip file "/data/app/com.temp.xiaop_android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.temp.xiaop_android-1/lib/arm, /system/fake-libs, /data/app/com.temp.xiaop_android-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
10-22 15:09:14.014 22038-22038/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.temp.xiaop_android/tinker_temp/temp.apk is not exist, just return

我编译的时候用的Raw模式，并且loadVerifyFlag也没打开，是false,是不是这样就会造成运行的时候类不完整，导致崩溃

这个问题并不是每次热更新后都会出现，同一个基准包，同一个热更新包，有些时候更新完就能正常运行，有些时候就会报这个错误然后直接崩溃。而且还遇到过热更新打完之后能正常运行几天，但是某一天就突然出现这个问题导致崩溃。

**Comment by shwenzhang** [comment]
上面没有错误日志，而且你用的是加固模式，检查一下是否是确认支持的加固方案吧

**Comment by frankqianghe** [comment]
我用的是梆梆加密，我在WIKI上看已经测试过了，梆梆加密没啥问题

**Comment by shwenzhang** [comment]
看classloader的加载顺序是没有问题的，需要跟梆梆加固确认是否支持tinker。

**Comment by frankqianghe** [comment]
您好，我也不太清楚梆梆目前是否支持tinker，所以我换成腾讯乐固试试，并且我也使用jar模式试试。有最新的结果，我再请教您，谢谢您的回复
