### ISSUE TITLE
Duplicate class found

### ISSUE THREAD

**Issue by andrewhunter0** [Tencent/tinker#64]
我自己的MyApplication继承了TinkerApplication，结果一直报错，说已经存在重复的MyApplication类，说在
/Users/xxxx/Documents/workspace/MyTinkerTest/app/build/generated/source/apt/debug/com/bruce/tinker下已经存在MyApplication.java文件了，所以实际上我们工程不能再创建自己的Application类。

应该是：
1、所有Application相关的代码全部移到继承自DefaultApplicationLike的类MyApplicationLike中

2、同时删除旧的MyApplication.java文件（如果删除，会引起原工程里大量引用找到，修改太大，折中处理方式是，删除MyApplication.java的所有继承，在MyApplicationLike中给其中的全局变量赋值，等对tinker完全集成成功后，再做重新的合理性调整）

3、然后给MyApplicationLike加上注解
基于第2点中，你是否选择删除旧的MyApplication.java文件，下面的做法也稍有不同
3.1、如果选择删除MyApplication.java文件，注解为：
@DefaultLifeCycle(
		application = "com.bruce.tinker.MyApplication",
		flags = ShareConstants.TINKER_ENABLE_ALL)
3.2、如果选择不删除MyApplication.java文件，注解为：
@DefaultLifeCycle(
		application = "com.bruce.tinker.MyApplicationNew",
		flags = ShareConstants.TINKER_ENABLE_ALL)
**同时需要将Manifest.xml中的application引用修改为MyApplicationNew**

4、同时app/build.gradle中给值**(也有跟第3.1、3.2同样的做法，使用MyApplication或者MyApplicationNew)**
loader = ["com.tencent.tinker.loader.*",
                      "com.bruce.tinker.MyApplicationNew",
            ]
这样会自动生成新的MyApplication/MyApplicationNew.java。

是不是应该这样，这样不报错了。文档的指导是不是有点误导，求解，求指教。

**Comment by shwenzhang** [comment]
文档就是这个意思，把将原来的Application隐藏，然后所有引用它的类转换到引用ApplicationLike。这样的是为了实现Application的逻辑可修改

**Comment by andrewhunter0** [comment]
好的，了解。
