### ISSUE TITLE
greendao数据库升级后打补丁，致命问题，请求支援

### ISSUE THREAD

**Issue by luyang7415445** [Tencent/tinker#645]
android.database.sqlite.SQLiteException: Can't downgrade database from version 4 to 3....greenDAO 数据库升级后打补丁，补丁生效后数据库版本升上去了，但是补丁合并失败后数据库版本就会降回原来的，这时候运行程序就会崩溃，因为合并失败后就return了，但是不知道为什么这么容易就合并失败了，请重视下这个问题，很严重的，致命的

**Comment by shwenzhang** [comment]
需要提供补丁合并失败的日志，而且因为补丁是不稳定的，需要谨慎用在升级数据库版本／数据库表这些场景
