### ISSUE TITLE
找不到gif资源

### ISSUE THREAD

**Issue by qingyizeng** [Tencent/tinker#646]
使用tinker热修生效后，刚开始会出现找不到gif图资源，导致app崩溃，偶现，后面再进不会出问题；
未热修的版本没发现同样异常；原包解压后目录里此文件存在，文件没有压缩；怀疑是tinker对资源做了压缩等操作引起？

异常类型：app运行时异常

手机型号：oppo r9m

手机系统版本：android6.0

tinker版本：1.7.11

gradle版本：3.3

使用热更新SDK： Bugly SDK

系统：Mac

堆栈/日志：

1 java.lang.RuntimeException:Unable to resume activity {com.xxxx.buy2/com.xxxx.buy2.activity.ActivityMainTab}: java.lang.RuntimeException: Unable to resume activity {com.xxxx.buy2/com.xxxx.buy2.activities.MyDDActivity}: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/my_dd_sign.gif from drawable resource ID #0x7f02059b
2 android.app.ActivityThread.performResumeActivity(ActivityThread.java:3453)
3 ......
4 Caused by:
5 java.io.FileNotFoundException:This file can not be opened as a file descriptor; it is probably compressed
6 android.content.res.AssetManager.openNonAssetFdNative(Native Method)
7 android.content.res.AssetManager.openNonAssetFd(AssetManager.java:472)
8 android.content.res.Resources.openRawResourceFd(Resources.java:1564)
9 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:87)
10 com.xxxx.buy2.widget.gw.a(MyDDTopView.java:166)
11 com.xxxx.buy2.mydang.MyDDNewFragment.c(MyDDNewFragment.java:371)
12 com.xxxx.buy2.mydang.MyDDNewFragment.onResume(MyDDNewFragment.java:319)
13 android.support.v4.app.Fragment.performResume(Fragment.java:2238)
14 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
15 android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
16 android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
17 android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2914)
18 android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
19 android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
20 android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
21 com.xxxx.buy2.activities.MyDDActivity.onPostResume(MyDDActivity.java)
22 android.app.Activity.performResume(Activity.java:6565)
23 android.app.ActivityThread.performResumeActivity(ActivityThread.java:3438)
24 android.app.LocalActivityManager.moveToState(LocalActivityManager.java:170)
25 android.app.LocalActivityManager.dispatchResume(LocalActivityManager.java:529)
26 android.app.ActivityGroup.onResume(ActivityGroup.java:61)
27 com.xxxx.buy2.activity.ActivityMainTab.onResume(ActivityMainTab.java:338)
28 android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1268)
29 android.app.Activity.performResume(Activity.java:6541)
30 android.app.ActivityThread.performResumeActivity(ActivityThread.java:3438)
31 android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3484)
32 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653)
33 android.os.Handler.dispatchMessage(Handler.java:111)

**Comment by shwenzhang** [comment]
tinker对资源是会保留之前的压缩方式的，这个可以查看编译输出文件夹中resources_out.zip文件
--

**Comment by shwenzhang** [comment]
fixed by 1.9.1
