### ISSUE TITLE
Could not find com.tencent.tinker:tinker-ziputils:1.9.0

### ISSUE THREAD

**Issue by lichen228** [Tencent/tinker#648]
配置了Tinker 1.9.0版本，Gradle报如下问题：
Error:Could not find com.tencent.tinker:tinker-ziputils:1.9.0.

这几个都返了404，是不是没传成功？
https://jcenter.bintray.com/com/tencent/tinker/tinker-ziputils/1.9.0/tinker-ziputils-1.9.0.pom
https://jcenter.bintray.com/com/tencent/tinker/tinker-ziputils/1.9.0/tinker-ziputils-1.9.0.jar
https://repo1.maven.org/maven2/com/tencent/tinker/tinker-ziputils/1.9.0/tinker-ziputils-1.9.0.pom
https://repo1.maven.org/maven2/com/tencent/tinker/tinker-ziputils/1.9.0/tinker-ziputils-1.9.0.jar

**Comment by shwenzhang** [comment]
![image](https://user-images.githubusercontent.com/8335303/32306024-0fa9f28c-bf47-11e7-9790-3e9a479ccc5a.png)

**Comment by lichen228** [comment]
恩，看到了，https://jcenter.bintray.com/com/tencent/tinker下面 tinker-ziputils 这级目录还没建起来，等等吧， 审核过了直接close就行
不过bintray页面上倒是可用了，急用的朋友可以这里拿：
