### ISSUE TITLE
我想询问一下引起verifyPatchMetaSignature fail的原因

### ISSUE THREAD

**Issue by hellosad** [Tencent/tinker#65]
看了下源码，没有分析出原因

**Comment by shwenzhang** [comment]
[Tinker 自定义扩展](https://github.com/Tencent/tinker/wiki/Tinker-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95), 查看具体的错误码

**Comment by hellosad** [comment]
哔了🐶了，没有加读写权限，从IOException重定向到了verifyPatchMetaSignature

**Comment by zabio** [comment]
同样遇到过 android 6.0 记得一定要申请权限

**Comment by xiaoqiang1369** [comment]
热修复成功后app闪退，有人遇到过这个问题么？还是说应该在app退出的时候启动热修复？
