### ISSUE TITLE
tinkerEnabled = false 报 tinkerId is not set!!!

### ISSUE THREAD

**Issue by ftgqzhengkai** [Tencent/tinker#659]
```
异常类型：编译异常

AS版本：AS3.0

tinker版本：如:1.9.0

gradle版本：如:4.1

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：如:Windows 7

```
```
ext {
    //for some reason, you may want to ignore tinkerBuild, such as instant run debug build?
    tinkerEnabled = false
}
当tinkerEnabled = false  提示
 Error:Execution failed for task ':app:tinkerProcessDevelopmentDebugManifest'.
> tinkerId is not set!!!
tinkerEnabled = true 是正常，这是怎么回事？想平时开发关闭。。。
```

**Comment by dede1314** [comment]
出现同样的问题。

**Comment by dede1314** [comment]
` String tinkerValue = project.extensions.tinkerPatch.buildConfig.tinkerId
        if (tinkerValue == null || tinkerValue.isEmpty()) {
            throw new GradleException('tinkerId is not set!!!')
        }`
报问题的是上面的代码，然后查看tinker.gradle中发现tinkerPatch中的buildConfig对应的闭包中
tinkerId = "1.0.1-base"这行被注释了，将注释放开即可。

**Comment by dede1314** [comment]
https://www.jianshu.com/p/6ee2c1f581eb
现在instant run 能正常运行，但时间和正常编译无区别。
