### ISSUE TITLE
如果已经自定义过Application怎么办

### ISSUE THREAD

**Issue by SolveBugs** [Tencent/tinker#66]
你好，如果应用中已经继承了别的第三方的Application，该怎么处理？

**Comment by shwenzhang** [comment]
把第三方Application的实现移动到ApplicationLike中

**Comment by dodola** [comment]
@SolveBugs Application和ApplicationLike在内部是互相持有的，全都迁移过去就可以了，用Like的声明周期 在Like里可以通过getApplication 拿到引用，可以保持原有的方法声明，实现写在Like里，我是这样的，还没出现问题

**Comment by SolveBugs** [comment]
@shwenzhang  我先不管原来的第三方Application，直接继承TinkerApplication（public class AppContext extends TinkerApplication ），但是原来onCreate方法中的实现怎么处理，提示说是不能重写TinkerApplication中的onCreate方法，因为是final的

**Comment by SolveBugs** [comment]
@dodola   你好，你的意思是在ApplicationLike相对应Application的方法中迁移吗？

**Comment by dodola** [comment]
@SolveBugs 对的，不要在继承TinkerApplication的Application里做操作，特意final的

**Comment by SolveBugs** [comment]
@dodola   那原来自定义的Application中定义的方法怎么办，程序中好多地方用的原来自定义的Application对象来调用那些方法的

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/18902871/55f0b0ae-8588-11e6-842f-6fdc4aa0f9f7.png)
参考自定义扩展文档

**Comment by shizhy1986** [comment]
程序他处会调用Application里的方法，现在这些方法全部挪到ApplicationLike？ 挪过去后后期程序又拿不到ApplicationLike这个代理，推荐怎么改？

**Comment by SolveBugs** [comment]
@shizhy1986   @shwenzhang   我也是这种情况

**Comment by shwenzhang** [comment]
如果可以拿到这些方法，代表他们是静态方法或者静态变量。这些方法移动到例如SampleApplicationLike不会有问题吧？然后他处调用的，就转化为调用SampleApplicationLike的方法

**Comment by SolveBugs** [comment]
@shwenzhang   不全是，有的是实例方法，需要对象来调用

**Comment by dodola** [comment]
@SolveBugs 实例方法可以拿到like的实例调用

**Comment by shizhy1986** [comment]
建议TinkerApplication加个接口拿到delegate吧，有接口拿到like？

**Comment by shwenzhang** [comment]
建议参考TinkerManger跟SampleApplicationContext的实现。SampleApplicationLike你程序可以随意拿到啊，不太明白你们的疑惑在哪里

**Comment by shizhy1986** [comment]
@shwenzhang 看到了，也就是自己额外得记录下ApplicationLike，我刚的意思是直接TinkerApplication加个接口getDelegate返回delegate。

**Comment by shwenzhang** [comment]
不行，TinkerApplication已经不可见了。这个是为了实现完全的隔离才能实现application类可修改

**Comment by l114624915** [comment]
在xxxLike中加接口回调可以
        ApplicationBack test = new ApplicationIm();
        String ss = test.getDataCacheManager();

**Comment by SolveBugs** [comment]
@l114624915   求具体思路，不是太理解

**Comment by Anysan** [comment]
@shwenzhang ,按文档写自定义的MyApplication ,一运行就出错，java.lang.RuntimeException: Unable to instantiate application tinker.sample.android.app.MyApplication: java.lang.IllegalAccessException: protected tinker.sample.android.app.MyApplication() is not accessible from class android.app.Instrumentation  ，还要配置哪里参数？

**Comment by shwenzhang** [comment]
protected？

**Comment by SolveBugs** [comment]
@dodola  你好，可以加下我微信（zq978823884）吗，还是有问题想请教下

**Comment by Anysan** [comment]
@shwenzhang ， protected ?  什么意思，不明白

**Comment by addappcn** [comment]
.app.SampleApplication 这个在哪 sample 目录下 根本没有这个文件，到底要不要自定义application


bugly  文档 写的 自定义application默认构造函数里调用 
super(ShareConstants.TINKER_ENABLE_ALL, "com.uto.driver.application.DriverApplicationLike",
                "com.tencent.tinker.loader.TinkerLoader", false);

搞不明白 请详细说明

**Comment by leonzhuhi** [comment]
@shwenzhang 我的项目中有两个Application，分别在一个子模块 和一个在主模块，其中主模块的extends子模块的，现在我是这样配置的：
子模块的 public class BaseApplication extends DefaultApplicationLike{ ...}

主模块的 
@DefaultLifeCycle(application = "com.XXX.app.ApplicationApp",
        flags = ShareConstants.TINKER_ENABLE_ALL,
        loadVerifyFlag = false)
public class XiuApplication extends BaseXiuApplication{ ...}


但是打出的包中直接报空指针，
Unable to instantiate application com.XXX.app.ApplicationApp: java.lang.ClassNotFoundException: Didn't find class "com.XXX.app.ApplicationApp" on path: DexPathList[[zip file "/data/app/com.XXX.context-2/base.apk"],nativeLibraryDirectories=[/data/app/com.XXX.context-2/lib/arm, /data/app/com.XXX.context-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]


这问题怎么去解决？

**Comment by hexianqiao3755** [comment]
@leonzhuhi  我也遇见了这个问题 你解决了吗

**Comment by Faith-Zhaixiaoliang** [comment]
@shwenzhang 我的项目中有两个Application，分别在一个子模块 和一个在主模块，其中主模块的extends子模块的，现在我是这样配置的：
子模块的 public class BaseApplication extends DefaultApplicationLike{ ...}

主模块的
@defaultlifecycle(application = "com.XXX.app.ApplicationApp",
flags = ShareConstants.TINKER_ENABLE_ALL,
loadVerifyFlag = false)
public class XiuApplication extends BaseApplication{ ...}

但是打出的包中直接报空指针，
Unable to instantiate application com.XXX.app.ApplicationApp: java.lang.ClassNotFoundException: Didn't find class "com.XXX.app.ApplicationApp" on path: DexPathList[[zip file "/data/app/com.XXX.context-2/base.apk"],nativeLibraryDirectories=[/data/app/com.XXX.context-2/lib/arm, /data/app/com.XXX.context-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

这问题怎么去解决？

**Comment by Faith-Zhaixiaoliang** [comment]
@hexianqiao3755 你解决了吗

**Comment by kakinIA** [comment]
@shwenzhang
![Uploading image.png…]()
你好，请问这个是什么意思，自定义扩展那里只有这个，没有具体实现的例子。另外继承application，那主入口到底是什么
