### ISSUE TITLE
Warning:ignoreWarning is false, manifest was changed, while hot plug component support mode is disabled. Such changes will not take effect.

### ISSUE THREAD

**Issue by adewu** [Tencent/tinker#660]
com.android.tools.build:gradle:3.0.0

com.tencent.bugly:crashreport_upgrade:1.3.3

com.tencent.bugly:tinker-support:1.1.0

基线包没有问题 相应的生成patch会包改错

ignoreWarning true 也不行

请问 这是什么引起的

-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:/Users/wuxm/work/android_projects/huasheng/app/build/bakApk/app-1110-15-45-12/app-release.apk
newApk:/Users/wuxm/work/android_projects/huasheng/app/build/outputs/apk/release/app-release.apk
outputFolder:/Users/wuxm/work/android_projects/huasheng/app/build/outputs/apk/tinkerPatch/release
isIgnoreWarning:false
isProtectedApp:false
7-ZipPath:/Users/wuxm/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
useSignAPk:true
package meta fields: 
dex configs: 
dexMode: jar
dexPattern:assets/secondary-dex-.\.jar
dexPattern:classes.*\.dex
dex loader:com.tencent.tinker.loader.*
dex loader:com.baselibrary.APP
lib configs: 
libPattern:lib/.*/.*\.so
resource configs: 
resPattern:r/.*
resPattern:resources\.arsc
resPattern:assets/.*
resPattern:AndroidManifest\.xml
resPattern:res/.*
resIgnore change:assets/.*_meta\.txt
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: app-release.apk, size=7551286, md5=ea3ca13e4f98d3ffaf35d03b75d44cc9
new apk: app-release.apk, size=7551334, md5=2fbf175e89062699906a523520128a7d
**# Warning:ignoreWarning is false, manifest was changed, while hot plug component support mode is disabled. Such changes will not take effect.**

**Comment by qingyizeng** [comment]
碰到同样问题！！！

**Comment by adewu** [comment]
if (!config.mSupportHotplugComponent && isManifestChanged) {
                announceWarningOrException("manifest was changed, while hot plug component support mode is disabled. "
                        + "Such changes will not take effect.");
            }

请问 config.mSupportHotplugComponent 是指的什么

**Comment by zhangshaobo87** [comment]
去看看 文档吧  热修复不支持manifest 的更改

**Comment by gougouyaqifei** [comment]
文档和源码都看了 问题是我没修改过manifest

**Comment by adewu** [comment]
@zhangshaobo87  文档和源码都看了 我确定没有修改过manifest

**Comment by adewu** [comment]
我这是集成的bugly 出现的这种情况 更新版本之后 在执行Build过程中 读取tinker-support.gradle 配置时不会读取tinkerPatch下的 ignoreWarning 所以需要把ignoreWarning = true 放到 tinkerSupport下 之后可以成功打出patch 但是之前的问题还会报 但并不影响补丁下发可以热修复

**Comment by zhang625480** [comment]
同样的问题 直接运行的官方demo  请问谁能说下具体是什么原因吗？mainefest确实没有动啊 编译完就在mainActivity里面加了个toast，然后大patch的时候就报这个错

**Comment by tomystang** [comment]
@zhang625480 
如果你用的是1.9.0或1.9.1版本，你遇到的情况应该是已知问题，下周会发fix版本。

**Comment by hqzxzwb** [comment]
@tomystang 我在1.9.1上遇到了，所以现在哪里可以获得fix版本？

**Comment by hyxi** [comment]
我在tinkerSupport下面加ignoreWarning = true也没有生成patch

**Comment by 424385117** [comment]
> 我这是集成的bugly 出现的这种情况 更新版本之后 在执行Build过程中 读取tinker-support.gradle 配置时不会读取tinkerPatch下的 ignoreWarning 所以需要把ignoreWarning = true 放到 tinkerSupport下 之后可以成功打出patch 但是之前的问题还会报 但并不影响补丁下发可以热修复

我用了你的方法可以打补丁,但是不能热修复,派发下去,无法合成
