### ISSUE TITLE
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed

### ISSUE THREAD

**Issue by 872506013** [Tencent/tinker#665]
异常类型：app运行时异常/编译异常

手机型号：如:Nexus 5(如是编译异常，则可以不填)

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

tinker版本：1.9.1

gradle版本：2.3.3

系统：android 7.0 HUAWEI MLA-AL10

java.lang.RuntimeException: Unable to instantiate application 包名.tinker.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed

**Comment by adewu** [comment]
Class var1 = Class.forName(this.delegateClassName, false, this.getClassLoader()); 抛的 锤子T1 4.4.2

**Comment by haoge1214** [comment]
java.lang.RuntimeException: Unable to instantiate application com.memezhibo.android.MemeTinkerApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed

我也是 加载就报错了  有大神 解答一下吗？

**Comment by shwenzhang** [comment]
详细日志

**Comment by gdky005** [comment]
我也遇到了这个问题，让我百思不得其解，连续三天了，没一点眉目，试过各种方法，就是不行。最后同事那边有突破了，原来这个问题并不是 tinker 的问题，而是在分包的时候，这个类依赖的类，没有被打到主 dex 里面，所以要排查 这个类 继承的类，还有实现的类，是否都在主 dex 里面。

具体问题错误原因是： 找不到依赖的类，所以无法初始化该类，抛出了找不到类异常。

其实你的错误根本原因是找不到 对应的 自定义 Application。 而你自定义的 Application 又继承 和依赖了 其他的类，这些类没有被你放到主 dex 里面，所以提示这个错误。

总结就是：遇到找不到类的错误，不一定是 真的找不到这个类（大多数是这个），也可能是这个类依赖的类找不到。 

我的问题就是，CallBack 没有在主 Dex 里面。
![image](https://user-images.githubusercontent.com/3477872/37751449-90ed7c16-2dcd-11e8-8378-8878f0428923.png)

留给后人。
