### ISSUE TITLE
编译问题：supportLibVersion = '23.0.1'

### ISSUE THREAD

**Issue by nEdAy** [Tencent/tinker#666]
tinker版本：:1.8.0或1.81

gradle版本：如:2.3.3

是否使用热更新SDK： 无

系统：win

之前使用1.7.1，更新1.8.1发现 ：

build\intermediates\res\merged\release\values-v23\values-v23.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(18) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(18) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

经查1.8.0 supportLibVersion 改为 23.0.1   使用了appcompat-v7-23.0.1
compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
而我的项目CompileSdkVersion 为  21 所以缺失资源 但由于某种原因我无法升级compile
我可否：
   compile("com.tencent.tinker:tinker-android-lib:${TINKER_VERSION}") {
        exclude group: 'com.android.support'
    }

测试 编译还是通过的 而且我也没要找到使用v7的地方 

项目中也不涉及AppCompat相关主题  也不会热更新 增加Activity

是否可以这样去掉这个依赖

还是我去掉之后 自己引一个 适合我CompileSdkVersion 为  21 的V7 ？

谢谢

**Comment by tomystang** [comment]
@nEdAy 
暂时可以先这样搞，exclude之后根据你的需要引入一个适合你的v7就可以了，后面我会fix这个问题的。

**Comment by tomystang** [comment]
已解决，1.9.2版本将不会再引入support lib里的多余资源了。
