### ISSUE TITLE
tinkerId 插入 manifest 的问题

### ISSUE THREAD

**Issue by freesith** [Tencent/tinker#671]
异常类型：编译异常
tinker版本：如:1.9.1
gradle版本：如:2.2.2
是否使用热更新SDK： 否
系统:Mac

你好,遇到一个问题:

我把tinker加到自己项目里,在本地测试的时候是正常的.

后来我写了个脚本,用jenkins就一直报:
Warning:ignoreWarning is false, manifest was changed, while hot plug component support mode is disabled. Such changes will not take effect.

我确实没有修改过manifest,然后我在本地按照服务器打包流程,把bugfix提交到代码仓库,打tag,运行脚本,发现也报了同样的问题

想到tinker会把tinkerId插入到manifest里,之前的tinkerId用的是git rev,
我把tinkerId改成了版本号,就没再出现了.

所以我想问:
我的gradle配置直接用的sample的配置,
我之前遇到的问题,是因为我提交了代码,导致tinkerId改变发生的吗?
还是说有什么特殊的参数没有配置?

**Comment by awdvhil9** [comment]
我也遇到了这个问题。用的1.9.0的版本，gradle是版本是4.1-all,classpath里用的是2.3.3.修改tinkerid就不能修复，不修改没试过

**Comment by awdvhil9** [comment]
修改ignorewarning为true可以，但是不知道会不会报错

**Comment by shwenzhang** [comment]
这个的确是新版本引发的问题，稍后会fix.暂时可打开ignorewarning，或者把supportComponent打开

**Comment by freesith** [comment]
好的,感谢~
