### ISSUE TITLE
在多module下热修复失败问题

### ISSUE THREAD

**Issue by dahutiger** [Tencent/tinker#673]
我们采用的多module的开发模式，现在修改一个module下的代码，然后发布热修复版本，热修复不成功。在LogCat下看到以下输出日志。
11-17 19:16:40.446 4243-4243 D/Tinker.TinkerManager: onDownloadSuccess.
11-17 19:16:40.446 4243-4243 D/Tinker.TinkerManager: check if has new patch.
11-17 19:16:40.459 4243-4243 D/Tinker.TinkerManager: has new patch.
11-17 19:16:40.464 4243-4243 D/Tinker.TinkerManager: starting patch.
11-17 19:16:40.464 4243-4243 I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk, file size:304189
11-17 19:16:40.483 4243-4243 I/Tinker.TinkerPatchListener: get platform:null
11-17 19:16:40.496 1925-2796 I/ActivityManager: Start proc 4966:com.yunniaohuoyun.driver:patch/u0a374 for service com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService
11-17 19:16:40.497 3053-3443 E/PowerKeeper.Event: tag:30014 msg: 0,4966,10374,com.yunniaohuoyun.driver:patch,service,com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService
11-17 19:16:40.497 3053-3443 E/PowerKeeper.Event: tag:30070 msg: 10374,com.yunniaohuoyun.driver,10374,com.yunniaohuoyun.driver:patch,com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService,{cmp=com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService}
11-17 19:16:40.665 4966-4966 W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
11-17 19:16:40.666 4966-4966 D/Tinker.DefaultAppLike: onBaseContextAttached:
11-17 19:16:40.679 4966-4966 I/Tinker.TinkerPatchListener: application maxMemory:128
11-17 19:16:40.692 4966-4966 W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yunniaohuoyun.driver/tinker
11-17 19:16:40.702 4966-4966 I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
11-17 19:16:40.702 4966-4966 I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.yunniaohuoyun.driver:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
11-17 19:16:40.702 4966-4966 W/Tinker.TinkerLoadResult: tinker is disable, just return
11-17 19:16:40.702 4966-4966 I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.yunniaohuoyun.driver/tinker, code: -1, cost: 8ms
11-17 19:16:40.702 4966-4966 W/Tinker.Tinker: tinker load fail!
11-17 19:16:40.703 4966-4966 D/Tinker.DefaultAppLike: onCreate
11-17 19:16:41.326 4966-4966 W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-17 19:16:41.326 4966-4996 I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
11-17 19:16:41.449 4966-4996 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker_temp/temp.apk
11-17 19:16:41.450 4966-4996 W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
11-17 19:16:41.458 4966-4996 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker_temp/temp.apk
11-17 19:16:41.458 4966-4996 W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
11-17 19:16:41.458 4966-4996 I/Tinker.TinkerPatchService: try to increase patch process priority
11-17 19:16:41.460 1925-1984 V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
11-17 19:16:41.476 3053-3443 E/PowerKeeper.Event: tag:30070 msg: 10374,com.yunniaohuoyun.driver:patch,10374,com.yunniaohuoyun.driver:patch,com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService$InnerService,{cmp=com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}
11-17 19:16:41.482 1925-1984 V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
11-17 19:16:41.634 4966-4996 I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:b71c7ba220acf78872b87270feba07aa
11-17 19:16:41.635 4966-4996 W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.yunniaohuoyun.driver/tinker/patch.info: open failed: ENOENT (No such file or directory)
11-17 19:16:41.635 4966-4996 W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.yunniaohuoyun.driver/tinker/patch.info: open failed: ENOENT (No such file or directory)
11-17 19:16:41.635 4966-4996 I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2
11-17 19:16:41.639 4966-4996 W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk size: 304189, dest file: /data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2/patch-b71c7ba2.apk size:304189
11-17 19:16:41.640 4966-4996 I/Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk, throwable: Tinker Exception:can't recognize dex mode:2948083215,jar
11-17 19:16:41.640 4966-4996 E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
11-17 19:16:41.647 4966-4996 E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:2948083215,jar
                                                                at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(SourceFile:65)
                                                                at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.a(SourceFile:92)
                                                                at bn.d.a(SourceFile:273)
                                                                at bn.d.a(SourceFile:166)
                                                                at bn.d.a(SourceFile:79)
                                                                at bn.g.a(SourceFile:133)
                                                                at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:129)
                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:157)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
11-17 19:16:41.664 4966-4996 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2/patch-b71c7ba2.apk
11-17 19:16:41.665 4966-4996 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2
11-17 19:16:41.666 4966-4996 I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk, success: false, cost: 207
11-17 19:16:41.689 3053-3443 E/PowerKeeper.Event: tag:30070 msg: 10374,com.yunniaohuoyun.driver:patch,10374,com.yunniaohuoyun.driver,com.yunniaohuoyun.driver/com.tencent.bugly.beta.tinker.TinkerResultService,{cmp=com.yunniaohuoyun.driver/com.tencent.bugly.beta.tinker.TinkerResultService}
11-17 19:16:41.722 4243-5019 I/Tinker.TinkerResultService: TinkerResultService receive result: 
                                                           PatchResult: 
                                                           isSuccess:false
                                                           rawPatchFilePath:/data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk
                                                           costTime:207
                                                           Throwable:Tinker Exception:can't recognize dex mode:2948083215,jar
11-17 19:16:47.697 4243-4243 D/Tinker.TinkerManager: onDownloadSuccess.
11-17 19:16:47.697 4243-4243 D/Tinker.TinkerManager: check if has new patch.
11-17 19:16:47.707 4243-4243 D/Tinker.TinkerManager: has new patch.
11-17 19:16:47.714 4243-4243 D/Tinker.TinkerManager: starting patch.
11-17 19:16:47.715 4243-4243 I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk, file size:304189
11-17 19:16:47.726 4243-4243 I/Tinker.TinkerPatchListener: get platform:null
11-17 19:16:47.742 1925-3507 I/ActivityManager: Start proc 5035:com.yunniaohuoyun.driver:patch/u0a374 for service com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService
11-17 19:16:47.744 3053-3443 E/PowerKeeper.Event: tag:30014 msg: 0,5035,10374,com.yunniaohuoyun.driver:patch,service,com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService
11-17 19:16:47.744 3053-3443 E/PowerKeeper.Event: tag:30070 msg: 10374,com.yunniaohuoyun.driver,10374,com.yunniaohuoyun.driver:patch,com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService,{cmp=com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService}
11-17 19:16:47.889 5035-5035 W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
11-17 19:16:47.892 5035-5035 D/Tinker.DefaultAppLike: onBaseContextAttached:
11-17 19:16:47.897 5035-5035 I/Tinker.TinkerPatchListener: application maxMemory:128
11-17 19:16:47.899 5035-5035 W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yunniaohuoyun.driver/tinker
11-17 19:16:47.900 5035-5035 I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
11-17 19:16:47.900 5035-5035 I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.yunniaohuoyun.driver:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
11-17 19:16:47.900 5035-5035 W/Tinker.TinkerLoadResult: tinker is disable, just return
11-17 19:16:47.900 5035-5035 I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.yunniaohuoyun.driver/tinker, code: -1, cost: 7ms
11-17 19:16:47.900 5035-5035 W/Tinker.Tinker: tinker load fail!
11-17 19:16:47.901 5035-5035 D/Tinker.DefaultAppLike: onCreate
11-17 19:16:47.970 5035-5035 W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
11-17 19:16:47.971 5035-5063 I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
11-17 19:16:47.975 5035-5063 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker_temp/temp.apk
11-17 19:16:47.980 5035-5063 W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
11-17 19:16:47.985 5035-5063 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker_temp/temp.apk
11-17 19:16:47.985 5035-5063 W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
11-17 19:16:47.985 5035-5063 I/Tinker.TinkerPatchService: try to increase patch process priority
11-17 19:16:47.986 1925-1984 V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
11-17 19:16:47.998 3053-3443 E/PowerKeeper.Event: tag:30070 msg: 10374,com.yunniaohuoyun.driver:patch,10374,com.yunniaohuoyun.driver:patch,com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService$InnerService,{cmp=com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}
11-17 19:16:48.012 1925-1984 V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.yunniaohuoyun.driver/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
11-17 19:16:48.069 5035-5063 I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:b71c7ba220acf78872b87270feba07aa
11-17 19:16:48.070 5035-5063 W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.yunniaohuoyun.driver/tinker/patch.info: open failed: ENOENT (No such file or directory)
11-17 19:16:48.071 5035-5063 W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.yunniaohuoyun.driver/tinker/patch.info: open failed: ENOENT (No such file or directory)
11-17 19:16:48.071 5035-5063 I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2
11-17 19:16:48.075 5035-5063 W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk size: 304189, dest file: /data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2/patch-b71c7ba2.apk size:304189
11-17 19:16:48.076 5035-5063 I/Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk, throwable: Tinker Exception:can't recognize dex mode:2948083215,jar
11-17 19:16:48.076 5035-5063 E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
11-17 19:16:48.076 5035-5063 E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:2948083215,jar
                                                                at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(SourceFile:65)
                                                                at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.a(SourceFile:92)
                                                                at bn.d.a(SourceFile:273)
                                                                at bn.d.a(SourceFile:166)
                                                                at bn.d.a(SourceFile:79)
                                                                at bn.g.a(SourceFile:133)
                                                                at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:129)
                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:157)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
11-17 19:16:48.079 5035-5063 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2/patch-b71c7ba2.apk
11-17 19:16:48.080 5035-5063 I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunniaohuoyun.driver/tinker/patch-b71c7ba2
11-17 19:16:48.080 5035-5063 I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk, success: false, cost: 95
11-17 19:16:48.091 3053-3443 E/PowerKeeper.Event: tag:30070 msg: 10374,com.yunniaohuoyun.driver:patch,10374,com.yunniaohuoyun.driver,com.yunniaohuoyun.driver/com.tencent.bugly.beta.tinker.TinkerResultService,{cmp=com.yunniaohuoyun.driver/com.tencent.bugly.beta.tinker.TinkerResultService}
11-17 19:16:48.103 4243-5069 I/Tinker.TinkerResultService: TinkerResultService receive result: 
                                                           PatchResult: 
                                                           isSuccess:false
                                                           rawPatchFilePath:/data/user/0/com.yunniaohuoyun.driver/app_tmpPatch/tmpPatch.apk
                                                           costTime:95
                                                           Throwable:Tinker Exception:can't recognize dex mode:2948083215,jar

**Comment by dahutiger** [comment]
@shwenzhang

**Comment by shwenzhang** [comment]
版本不一致，编译的tinker版本跟app使用的版本
