### ISSUE TITLE
tinker手动生成sdk无法替换资源文件

### ISSUE THREAD

**Issue by Owenli0202** [Tencent/tinker#675]
异常类型：编译异常

tinker版本：如:1.8.1

gradle版本：如:2.3.1

是否使用热更新SDK：TinkerPatch SDK

系统：Mac

tinker通过buildSdk生成的库依赖，替换无法替换资源文件（资源文件未在patch包中），删除buid下的缓存文件才能生成包含资源文件的patch包

**Comment by tomystang** [comment]
发一下操作步骤吧，如果你使用buildSdk得到的命令行工具打patch的话应该不会涉及到build目录的。

**Comment by Owenli0202** [comment]
我项目中还有依赖classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
还是通过task方式打patch的。
