### ISSUE TITLE
新增activity合成成功startActivity时空指针

### ISSUE THREAD

**Issue by afunnyrainman** [Tencent/tinker#677]
异常类型：app运行时异常
手机型号：魅族 pro 6s
手机系统版本：7.1.1
tinker版本： compile 'com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.2.1'
   provided 'com.tencent.tinker:tinker-android-anno:1.9.1'
gradle版本：4.1
是否使用热更新SDK： TinkerPatch SDK 
系统：Mac

android studiao 3.0.1 新增activity 下载成功、合成成功、应用成功,但是跳转到热更新的activity时空指针.
 this.startActivity(intent);这一行。

**Comment by tomystang** [comment]
发下crash时的堆栈？

**Comment by afunnyrainman** [comment]
as 2.3.2也不行。
但是打补丁的时候生成签名的apk安装运行到热更新跳转页面哪里也没有报错。

android.os.Parcel.readException(Parcel.java:1690)
2 android.os.Parcel.readException(Parcel.java:1637)
3 android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3419)
4 android.app.Instrumentation.execStartActivity(Instrumentation.java:1526)
5 android.app.Activity.startActivityForResult(Activity.java:4262)
6 android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
7 android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
8 android.app.Activity.startActivityForResult(Activity.java:4220)
9 android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
10 android.app.Activity.startActivity(Activity.java:4594)
11 android.app.Activity.startActivity(Activity.java:4527)
12 com.example.administrator.fanglei.UserInfo.Activity.LoginActivity.LoginStatu(LoginActivity.java:299)
13 com.example.administrator.fanglei.UserInfo.Activity.LoginActivity.access$600(LoginActivity.java:54)
14 com.example.administrator.fanglei.UserInfo.Activity.LoginActivity$4.handleMessage(LoginActivity.java:270)
15 android.os.Handler.dispatchMessage(Handler.java:110)
16 android.os.Looper.loop(Looper.java:203)
17 android.app.ActivityThread.main(ActivityThread.java:6475)
18 java.lang.reflect.Method.invoke(Native Method)
19 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
20 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by tomystang** [comment]
这个堆栈第一行有描述信息或者继续往下看有cause by吗？

**Comment by afunnyrainman** [comment]
没有,这个是腾讯Bugly的，我已经截全了。

**Comment by afunnyrainman** [comment]
我刚试了debug的居然可以，签名的就报错。

**Comment by afunnyrainman** [comment]
但是签名的我要是热更新个toask也是可以

**Comment by tomystang** [comment]
诡异了，你试试把release包的混淆关掉看看有没有问题？

**Comment by afunnyrainman** [comment]
已经是关掉了的。

**Comment by tomystang** [comment]
方便的话把app/build/outputs/tinkerPatch目录打包发到我的邮箱吧：yinshengtang@foxmail.com
log还是太少，我看下是不是其他问题。

**Comment by afunnyrainman** [comment]
可以了，我也不知我做了啥，改了下app的build
 minifyEnabled false
                shrinkResources false
                // Zipalign优化
                zipAlignEnabled true,
卸载了一下APP。
麻烦您了，
close issue了
