### ISSUE TITLE
remoteView是啥,ImageView是吗

### ISSUE THREAD

**Issue by iamzj** [Tencent/tinker#678]
tinker的文档里说的remoteView是啥，我基础包没有ImageView，补丁包加个ImageView设置图片，然后图片放到drawable目录就没起作用
请问可以新加图片？

**Comment by tomystang** [comment]
remoteView一般是用在Notification上的那个View，或者其他需要跨进程传递的View。你新增的图片是用在本进程的Activity上了吗？如果是的话不该不生效的，可能是补丁加载的时候就已经失败了。

发下运行时的log和机型、系统版本吧。

**Comment by iamzj** [comment]
我是tinkerPatch sdk接入的，基准包appVersion1.0，补丁包appVersion1.1，这个是不对的吧，基准包和补丁包appVersion应该一致，对吗

**Comment by tomystang** [comment]
额，appVersion应该是可以变的，具体在群里问下 simsun吧。

**Comment by iamzj** [comment]
群早就满了，后续还有好多人要进群，是否可以新建个2群之类的，我也单独问了他，可能忙没回复

**Comment by simpleton** [comment]
@tomystang 多谢tom帮忙回复，可以close了。
@iamzj 已解答问题，appVersion要保持一致。
