### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method g_()J in class Ljava/nio/channels/FileChannel

### ISSUE THREAD

**Issue by jeneyloo** [Tencent/tinker#679]
异常类型：app运行时异常

手机型号：Nexus 5X(必现crash和手机平台无关)

手机系统版本：Android 7.0

tinker版本：1.7.9

gradle版本：2.3.3

是否使用热更新SDK： 否

系统：Mac

堆栈/日志：
![image](https://user-images.githubusercontent.com/9362651/33108793-fed61d7c-cf78-11e7-9676-f22c350fad54.png)

基准包运行ok，修改代码只是加了一句log输出，打补丁，补丁包应用上发生crash。
代码中有一处调用到java.nio.channels.FileChannel类的size()方法。反编译打补丁过程中生成的新apk看到方法名变成了g_()。
![image](https://user-images.githubusercontent.com/9362651/33108984-001bd23e-cf7a-11e7-956f-7ef6331518af.png)

混淆开了optimize
![image](https://user-images.githubusercontent.com/9362651/33109192-2f44e518-cf7b-11e7-9e35-f29f0422245f.png)

做了以下尝试：
1.修改了下混淆无optimize，也不会出现上述问题
![image](https://user-images.githubusercontent.com/9362651/33109747-578d94ea-cf7e-11e7-9d4b-fd81f1a114ae.png)
2.不配置applyMapping，，也不会出现上述问题

**Comment by tomystang** [comment]
把app/build/outputs/tinkerPatch目录打包发到我的邮箱：yinshengtang@foxmail.com吧，我看下是不是proguard的问题哈

**Comment by jeneyloo** [comment]
@tomystang tinkerPatch文件已发送

**Comment by tomystang** [comment]
嗯嗯，看了一下，应该是proguard的bug，你在proguard的mapping里加上规则keep住java.nio这个包下面的类就可以了。
