### ISSUE TITLE
修复成功后，小米推送会崩溃

### ISSUE THREAD

**Issue by qingyizeng** [Tencent/tinker#680]
修复成功后，小米推送会崩溃；

异常类型：app运行时异常

手机型号：三星 galaxy s5

手机系统版本：如:Android 4.4.2

tinker版本：1.9.0

gradle版本：3.3

是否使用热更新SDK： Bugly SDK 

系统：Mac

堆栈/日志：
11-22 12:43:33.248: E/Tinker.TinkerUncaughtExceptionHandler(32179): uncaughtException:com/google/b/a/c
11-22 12:43:33.258: E/Tinker.TinkerUncaughtExceptionHandler(32179): tinker has fast crash 2 times
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): TinkerUncaughtHandler catch exception:java.lang.VerifyError: com/google/b/a/c
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.protobuf.b$a.b(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.slim.b.l(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.slim.d.a(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.slim.d.b(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.slim.f.a(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.smack.h.b(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.service.XMPushService.p(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.service.XMPushService.o(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.service.XMPushService.g(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.service.XMPushService$d.a(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.service.XMPushService$h.run(Unknown Source)
11-22 12:43:33.258: E/Tinker.UncaughtHandler(32179): 	at com.xiaomi.push.service.l$c.run(Unknown Source)

**Comment by simpleton** [comment]
@qingyizeng 建议升级到1.9.1， bugly的对应版本可以咨询小巫同学
