### ISSUE TITLE
mate9修复不成功

### ISSUE THREAD

**Issue by qingyizeng** [Tencent/tinker#681]
修复不成功

异常类型：app运行时异常

手机型号：huawei mate9

手机系统版本：Android 7.0 

tinker版本：1.9.0

gradle版本：3.3

是否使用热更新SDK：  Bugly SDK

系统：Mac

堆栈/日志：
11-22 12:55:38.618: I/Tinker.TinkerPatchListener(26038): receive a patch file: /data/user/0/com.xxx.buy2/app_tmpPatch/tmpPatch.apk, file size:100815
11-22 12:55:38.622: W/Tinker.UpgradePatchRetry(26038): onPatchListenerCheck, retry count 5 must exceed than max retry count
11-22 12:55:38.623: I/Tinker.DefaultLoadReporter(26038): patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/user/0/com.xxx.buy2/app_tmpPatch/tmpPatch.apk, code: -7

**Comment by tomystang** [comment]
这个错误码是反复尝试次数超过上限了，留意一下运行时log看看有没有其他内容吧。（确认下是不是tinker id对不上，patch包签名有问题之类的？）

**Comment by SbyXlmm** [comment]
# 啊哈

**Comment by qingyizeng** [comment]
同一个包，只在mate9出现这问题，其他手机没出这问题

**Comment by tomystang** [comment]
试试先卸载掉你的app，然后重新安装，再触发补丁加载，然后发下logcat里tag含有tinker的log

**Comment by qingyizeng** [comment]
卸载重装，重新加载补丁还是出同样的log

**Comment by tomystang** [comment]
升级到1.9.2之后重新打基准包和patch包再试试？

**Comment by shwenzhang** [comment]
需要查看真正出现问题的原因，而不是看重试这里。bugly sdk还是咨询bugly的人员吧
