### ISSUE TITLE
parseTinkerResult loadCode:-2

### ISSUE THREAD

**Issue by iamzj** [Tencent/tinker#682]
异常类型：app运行时异常

手机型号：HUAWEI/TIT-AL00，EMUI 3.1 Lite

手机系统版本：Android 5.1

tinker版本：1.9.1

gradle版本：2.3.3

是否使用热更新SDK：否，tinker gradle方式接入

系统：Windows7

堆栈/日志：
W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.zj.zjtinker2gradleaccess/tinker
 D/Tinker.DefaultAppLike: onBaseContextAttached:
 W/Tinker.Tinker: tinker patch directory: /data/data/com.zj.zjtinker2gradleaccess/tinker
 I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
 I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zj.zjtinker2gradleaccess, main process:true, systemOTA:false, fingerPrint:HUAWEI/TIT-AL00/HWTIT-AL00:5.1/HUAWEITIT-AL00/C00B159:user/release-keys, oatDir:null, useInterpretMode:false
 W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
 I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.zj.zjtinker2gradleaccess/tinker, code: -2, cost: 49ms
 W/Tinker.Tinker: tinker load fail!
 I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
 D/Tinker.DefaultAppLike: onCreate
 I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2

补充：
根目录补丁文件是存在的，确定没错，我换成小米手机就没问题，补丁第一次就生效修复了bug，不知道华为手机什么情况

module的gradle是copy示例中的，其中有部分改了：
dex {
            //...
            loader = [
                    //use sample, let BaseBuildInfo unchangeable with tinker
//                    "tinker.sample.android.app.BaseBuildInfo" //官方示例的这行我注释了

                    "com.tencent.tinker.loader.*", "com.zj.zjtinker2gradleaccess.MyApplication"
            ]
｝

MyApplicationLike类：

![tim 20171122132933](https://user-images.githubusercontent.com/21978982/33111894-4d5c2754-cf8b-11e7-8852-3addcebfaa6e.png)

**Comment by simpleton** [comment]
权限问题？

**Comment by bangmi** [comment]
你使用1.7.7的版本试试呢

**Comment by shwenzhang** [comment]
I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -2

确认一下sdk权限，是不是6.0以上手机，需要动态申请
