### ISSUE TITLE
使用系统签名的如何build生成APK

### ISSUE THREAD

**Issue by lishisheng** [Tencent/tinker#683]
异常类型：补丁运行无法合成

手机型号：所有机型

手机系统版本：所有版本

tinker版本：最新版本

gradle版本：2.14.1

是否使用热更新SDK： Bugly SDK

系统：如:windows 7

堆栈/日志：

这边需要使用系统的签名文件platform.pk8和certificate.pem对APK进行签名，由于gradle无法配置自动系统签名，也无法对platform.pk8和certificate.pem转换成jks或者keystore,这样子造成bakApk里面生成的APK跟我原来的APK的签名不一致，即使我用我自己手动签名完的APK替换bakApk里面的APK,执行完buildTinkerPathRelease后生成的补丁上传到后台后，可以正常下载，但是合成的时候会造成失败，请问除了用gradle执行assembleRelease的方法生成基准包之外，有其他手动编译的方法吗，或者可以跳过对APK签名的校验吗？

**Comment by tomystang** [comment]
试试编完基准包之后手动给基准包签名，然后再触发buildTinkerPathRelease，得到patch包之后，手动给生成的patch包用相同的证书签名，这样应该就ok了。
