### ISSUE TITLE
Tinker Exception:can't recognize dex mode:0,jar

### ISSUE THREAD

**Issue by LazyDemo** [Tencent/tinker#687]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：如:nubia z11 

手机系统版本：如:Android 6.0.1 (如是编译异常，则可以不填)

tinker版本：如:1.7.11

gradle版本：如:3.0.1

是否使用热更新SDK： Bugly SDK

系统:Mac

堆栈/日志：
![image](https://user-images.githubusercontent.com/13451082/33254782-6ab655ec-d385-11e7-9777-ac2d68cce251.png)

**Comment by tomystang** [comment]
确认一下基准包的tinker版本和编译时用的tinker版本是否一致？就是tinker-android-xx的版本号和tinker-build-lib的版本号

**Comment by LazyDemo** [comment]
感谢，版本替换到1.9.0就可行了
