### ISSUE TITLE
TInker修复后重启进程，华为机器发生大范围crash

### ISSUE THREAD

**Issue by ibabyting** [Tencent/tinker#693]
TInker修复后重启进程，然后bugly上捕获到了近百次crash上报，且数字一直在增加，全是华为的机器。
以前是没有问题的，自从加入了Process.kill重启进程以生效补丁后出现该问题。bugly上报就只有华为机器，我用华为同样的机型和系统以及其他机型测试过没有发生崩溃异常，补丁也能成功的修复

异常类型：app运行时异常

手机型号：全是华为机器（荣耀，p系列，mate系列等）

手机系统版本：Android7.0 以上系统

tinker版本：1.8.1

gradle版本：3.3

是否使用热更新SDK：只集成了Bugly上报SDK

系统：如:Windows
堆栈/日志：
总共有3个crash上报
**第一个**
android.content.res.Resources$NotFoundException:failed to add asset path /data/user/0/com.xxx/tinker/patch-80ffabd1/res/resources.apk
--
5 android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
6 android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
7 android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
8 android.app.ResourcesManager.getResources(ResourcesManager.java:690)
9 android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1989)
10 android.app.ActivityThreadUtils.getTopLevelResources(ActivityThreadUtils.java:24)
11 huawei.android.hwtheme.HwThemeManagerImpl.updateHwtResource(HwThemeManagerImpl.java:681)
12 android.hwtheme.HwThemeManager.updateHwtResource(HwThemeManager.java:311)
13 android.app.LoadedApk.getResources(LoadedApk.java:803)

**第二个**
android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
--
2 android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
3 android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
4 android.app.ResourcesManager.getResources(ResourcesManager.java:690)
5 android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1989)
6 android.app.ActivityThreadUtils.getTopLevelResources(ActivityThreadUtils.java:24)
7 huawei.android.hwtheme.HwThemeManagerImpl.updateHwtResource(HwThemeManagerImpl.java:491)
8 android.hwtheme.HwThemeManager.updateHwtResource(HwThemeManager.java:311)
9 android.app.LoadedApk.getResources(LoadedApk.java:803)

**第三个**
#9365 java.lang.ClassCastException
com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult
com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(AbstractResultService.java:64)
2 android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
3 android.os.Handler.dispatchMessage(Handler.java:102)
4 android.os.Looper.loop(Looper.java:154)
5 android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ibabyting** [comment]
看着那一大群crash，有点懵逼。。。

**Comment by grace88888884** [comment]
请问这个问题你是怎么解决的？谢谢

**Comment by ibabyting** [comment]
@grace88888884 应用过程中手动清除了旧补丁，也就是tinkerutil的clean方法，导致删除了tinker目录，所以找不到resource，至于只在7.0和7.1崩是因为在createassert时throw exception了，其他版本resource找不到只会log.w
