### ISSUE TITLE
Tinker修复后，出现大面积崩溃。只修复了assets下的资源 

### ISSUE THREAD

**Issue by gigisx** [Tencent/tinker#694]
异常类型：app运行时异常

手机型号：小米REDMINOTE 4X 小米 MI5 5S 部分三星

手机系统版本：如:Android 7.0 7.1.1 7.1.2

tinker版本：如:1.7.9

gradle版本：如:2.33

是否使用热更新SDK： 如 TinkerPatch SDK 

系统：如:liunx

堆栈/日志：

主要异常是 Tinker Exception:createDelegate failed

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.jxedt/com.jxedt.ui.activitys.GuideActivity}: java.lang.RuntimeException: Unable to instantiate application com.jxedt.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
3 ......
4 Caused by:
5 java.lang.VerifyError:Verifier rejected class com.jxedt.AppLike: void com.jxedt.AppLike.initBugly() failed to verify: void com.jxedt.AppLike.initBugly(): [0xE] register v1 has type Precise Reference: com.jxedt.AppLike$3 but expected Reference: com.tencent.bugly.crashreport.CrashReport$CrashHandleCallback
6 void com.jxedt.AppLike.initFresco() failed to verify: void com.jxedt.AppLike.initFresco(): [0x9] 'this' argument 'Reference: com.facebook.imagepipeline.core.ImagePipelineConfig$Builder' not instance of 'Reference: com.facebook.imagepipeline.core.ImagePipelineConfig$Builder'
7 void com.jxedt.AppLike.initLeakcanary() failed to verify: void com.jxedt.AppLike.initLeakcanary(): [0x8] register v0 has type Precise Reference: com.g.a.b but expected Precise Reference: com.g.a.b
8 void com.jxedt.AppLike.initLog() failed to verify: void com.jxedt.AppLike.initLog(): [0x7] 'this' argument 'Reference: com.e.a.h$a' not instance of 'Reference: com.e.a.h$a'
9 void com.jxedt.AppLike.registerRxErrorHandler() failed to verify: v
10 [Message over limit size:1000, has been cutted!]
11 java.lang.reflect.Constructor.newInstance0(Native Method)
12 java.lang.reflect.Constructor.newInstance(Constructor.java:430)
13 com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109)
14 com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:118)
15 com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:131)
16 com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
17 android.app.Application.attach(Application.java:193)
18 android.app.Instrumentation.newApplication(Instrumentation.java:1009)
19 android.app.Instrumentation.newApplication(Instrumentation.java:993)
20 android.app.LoadedApk.makeApplication(LoadedApk.java:800)
21 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2605)
22 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
23 android.app.ActivityThread.-wrap12(ActivityThread.java)
24 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
25 android.os.Handler.dispatchMessage(Handler.java:102)
26 android.os.Looper.loop(Looper.java:163)
27 android.app.ActivityThread.main(ActivityThread.java:6237)
28 java.lang.reflect.Method.invoke(Native Method)
29 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
30 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

11-30 14:15:37.405 22970 22970 E AndroidRuntime: FATAL EXCEPTION: main
--
5411-30 14:15:37.405 22970 22970 E AndroidRuntime: Process: com.jxedt, PID: 22970
5511-30 14:15:37.405 22970 22970 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jxedt/com.jxedt.ui.activitys.GuideActivity}: java.lang.RuntimeException: Unable to instantiate application com.jxedt.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
5611-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
5711-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
5811-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.ActivityThread.-wrap12(ActivityThread.java)
5911-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
6011-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
6111-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.os.Looper.loop(Looper.java:163)
6211-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6237)
6311-30 14:15:37.405 22970 22970 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
6411-30 14:15:37.405 22970 22970 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
6511-30 14:15:37.405 22970 22970 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
6611-30 14:15:37.405 22970 22970 E AndroidRuntime: Caused by: java.lang.RuntimeException: Unable to instantiate application com.jxedt.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
6711-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:806)
6811-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2605)
6911-30 14:15:37.405 22970 22970 E AndroidRuntime: ... 9 more
7011-30 14:15:37.405 22970 22970 E AndroidRuntime: Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
7111-30 14:15:37.405 22970 22970 E AndroidRuntime: at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:112)
7211-30 14:15:37.405 22970 22970 E AndroidRuntime: at # com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:118)
7311-30 14:15:37.405 22970 22970 E AndroidRuntime: at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:131)
7411-30 14:15:37.405 22970 22970 E AndroidRuntime: at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
7511-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.Application.attach(Application.java:193)
7611-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
7711-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.Instrumentation.newApplication(Instrumentation.java:993)
7811-30 14:15:37.405 22970 22970 E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:800)
7911-30 14:15:37.405 22970 22970 E AndroidRuntime: ... 10 more
8011-30 14:15:37.405 22970 22970 E AndroidRuntime: Caused by: java.lang.VerifyError: Verifier rejected class com.jxedt.AppLike: void com.jxedt.AppLike.initBugly() failed to verify: void com.jxedt.AppLike.initBugly(): [0xE] register v1 has type Precise Reference: com.jxedt.AppLike$3 but expected Reference: com.tencent.bugly.crashreport.CrashReport$CrashHandleCallback
8111-30 14:15:37.405 22970 22970 E AndroidRuntime: void com.jxedt.AppLike.initFresco() failed to verify: void com.jxedt.AppLike.initFresco(): [0x9] 'this' argument 'Reference: com.facebook.imagepipeline.core.ImagePipelineConfig$Builder' not instance of 'Reference: com.facebook.imagepipeline.core.ImagePipelineConfig$Builder'
8211-30 14:15:37.405 22970 22970 E AndroidRuntime: void com.jxedt.AppLike.initLeakcanary() failed to verify: void com.jxedt.AppLike.initLeakcanary(): [0x8] register v0 has type Precise Reference: com.g.a.b but expected Precise Reference: com.g.a.b
8311-30 14:15:37.405 22970 22970 E AndroidRuntime: void com.jxedt.AppLike.initLog() failed to verify: void com.jxedt.AppLike.initLog(): [0x7] 'this' argument 'Reference: com.e.a.h$a' not instance of 'Reference: com.e.a.h$a'
8411-30 14:15:37.405 22970 22970 E AndroidRuntime: void com.jxedt.AppLike.registerRxErrorHandler() failed to verify: void com.jxedt.AppLike.registerRxErrorHandler(): [0x9] register v1 has type Precise Reference: com.jxedt.AppLike$1 but expected Reference: rx.g.a (declaration of 'com.jxedt.AppLike' appears in /data/user/0/com.jxedt/tinker/patch-3064dad4/dex/classes.dex.jar)
8511-30 14:15:37.405 22970 22970 E AndroidRuntime: at java.lang.reflect.Constructor.newInstance0(Native Method)
8611-30 14:15:37.405 22970 22970 E AndroidRuntime: at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
8711-30 14:15:37.405 22970 22970 E AndroidRuntime: at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109)
8811-30 14:15:37.405 22970 22970 E AndroidRuntime: ... 17 more
8911-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jxedt/com.jxedt.ui.activitys.GuideActivity}: java.lang.RuntimeException: Unable to instantiate application com.jxedt.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
9011-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
9111-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
9211-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.ActivityThread.-wrap12(ActivityThread.java)
9311-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
9411-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.os.Handler.dispatchMessage(Handler.java:102)
9511-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.os.Looper.loop(Looper.java:163)
9611-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.ActivityThread.main(ActivityThread.java:6237)
9711-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at java.lang.reflect.Method.invoke(Native Method)
9811-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
9911-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10011-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: Caused by: java.lang.RuntimeException: Unable to instantiate application com.jxedt.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
10111-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.LoadedApk.makeApplication(LoadedApk.java:806)
10211-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2605)
10311-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: ... 9 more
10411-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
10511-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:112)
10611-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:118)
10711-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:131)
10811-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
10911-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.Application.attach(Application.java:193)
11011-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
11111-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.Instrumentation.newApplication(Instrumentation.java:993)
11211-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at android.app.LoadedApk.makeApplication(LoadedApk.java:800)
11311-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: ... 10 more
11411-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: Caused by: java.lang.VerifyError: Verifier rejected class com.jxedt.AppLike: void com.jxedt.AppLike.initBugly() failed to verify: void com.jxedt.AppLike.initBugly(): [0xE] register v1 has type Precise Reference: com.jxedt.AppLike$3 but expected Reference: com.tencent.bugly.crashreport.CrashReport$CrashHandleCallback
11511-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: void com.jxedt.AppLike.initFresco() failed to verify: void com.jxedt.AppLike.initFresco(): [0x9] 'this' argument 'Reference: com.facebook.imagepipeline.core.ImagePipelineConfig$Builder' not instance of 'Reference: com.facebook.imagepipeline.core.ImagePipelineConfig$Builder'
11611-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: void com.jxedt.AppLike.initLeakcanary() failed to verify: void com.jxedt.AppLike.initLeakcanary(): [0x8] register v0 has type Precise Reference: com.g.a.b but expected Precise Reference: com.g.a.b
11711-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: void com.jxedt.AppLike.initLog() failed to verify: void com.jxedt.AppLike.initLog(): [0x7] 'this' argument 'Reference: com.e.a.h$a' not instance of 'Reference: com.e.a.h$a'
11811-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: void com.jxedt.AppLike.registerRxErrorHandler() failed to verify: void com.jxedt.AppLike.registerRxErrorHandler(): [0x9] register v1 has type Precise Reference: com.jxedt.AppLike$1 but expected Reference: rx.g.a (declaration of 'com.jxedt.AppLike' appears in /data/user/0/com.jxedt/tinker/patch-3064dad4/dex/classes.dex.jar)
11911-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at java.lang.reflect.Constructor.newInstance0(Native Method)
12011-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
12111-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109)
12211-30 14:15:37.420 22970 22970 E Tinker.UncaughtHandler: ... 17 more

**Comment by tomystang** [comment]
升级到最新的tinkerpatch或tinker还是一样吗？
