### ISSUE TITLE
原有工程的application有interface要实现怎么办

### ISSUE THREAD

**Issue by HeinzLip** [Tencent/tinker#695]

**Comment by tomystang** [comment]
可以考虑改到对应的ApplicationLike里，其他用到Application的地方统一换成ApplicationLike就好了。不过如果你的第三方库一定要你传个Application进去的话，那就只能搞个包装类包一层，真正的Application外面套一层符合你的接口要求的类做代理。就像这样：

DefaultLifeCycle(application = "package.name.RealApplication",
                  flags = ShareConstants.TINKER_ENABLE_ALL,
                  loadVerifyFlag = false)
public class MyApplicationLike {
    void onAttachBaseContext(Context base) {
        //  在这个proxyapplication里实现你不得不实现的所有接口，有库要用到的话就传这个wrappedApp
        ProxyApplication wrappedApp = new ProxyApplication(getApplication());
        ……
    }
}
