### ISSUE TITLE
如果打release包需要怎么做？？

### ISSUE THREAD

**Issue by zzm123456** [Tencent/tinker#70]
尝试打release包，但是bakApk文件夹没有生产对应的文件

**Comment by liuguoquan727** [comment]
Release的使用方法

Tinker的使用方式如下，以gradle接入的release包为例：

每次编译或发包将安装包与mapping文件备份；
若有补丁包的需要，按自身需要修改你的代码、库文件等；
将备份的基准安装包与mapping文件输入到tinkerPatch的配置中；
运行tinkerPatchRelease，即可自动编译最新的安装包，并与输入基准包作差异，得到最终的补丁包。

参考wiki里的接入指南文档

**Comment by shwenzhang** [comment]
[build.gradle](https://github.com/Tencent/tinker/blob/dev/tinker-sample-android/app/build.gradle)

大家还是不能一律的去接受，还是要看一下代码，类似其实保存结果的逻辑

![image](https://cloud.githubusercontent.com/assets/8335303/18908108/efdc1380-85a0-11e6-99d3-da9d9ab34e13.png)

**Comment by zzm123456** [comment]
不好意思~之前有改过这个地方 但是不知道什么原因 没有出现文件，现在重新再改回来 就可以了

**Comment by zzm123456** [comment]
输入之后 只有后缀为mapping.txt文件和R.txt文件 ，没有apk。。。。

**Comment by zzm123456** [comment]
本人比较菜，望解答~~

**Comment by Drizzlezhang** [comment]
@zzm123456 sample里task已经给你写好了，改名字而已

**Comment by chaoyangsun** [comment]
没有mapping文件，别的都有，为什么？
