### ISSUE TITLE
对于Tinker的几点疑问

### ISSUE THREAD

**Issue by jackyperf** [Tencent/tinker#700]
## Tinker 并行dex2oat问题
> 从源码以及实践中，我们知道Tinker安装dex文件触发dex2oat是并行的多个dex2oat进程同时编译，系统负载太高，可能会引发ANR等问题。

- Tinker是否有计划改善这样方式，比如并行->串行。
## Tinker 安装dex文件的时机
- 对于不紧急的patch，是否可以使用`JobScheduler`当系统空闲时来优化dex文件，而不是每次都立即安装。

**Comment by tomystang** [comment]
第一点已经改成串行了，但对于一些较大的dex，在dex2oat阶段偶尔还是会引起ANR；
第二点可以有，不过一般发patch其实都比较紧急了，而且要考虑兼容5.0以前的系统，当时为了处理方便，就没有特别处理了。

**Comment by jackyperf** [comment]
另外，请问Tinker有没有想跟厂商进一步合作优化的打算呢？

**Comment by tomystang** [comment]
厂商能做的事情基本上都做了，而且每个用户集成tinker可能都会有点小改动，厂商也没法逐个去做特殊处理的。现在ANR主要是dex2oat这个阶段，我在评估facebook的oatmeal能优化多少时间，如果速度提升明显，而且没有兼容性问题的话就考虑用这个工具来代替dex2oat了。

**Comment by jackyperf** [comment]
Facebook oatmeal 项目的地址可否告知一下

**Comment by tomystang** [comment]
https://github.com/facebook/redex/tree/master/tools/oatmeal
这里
