### ISSUE TITLE
是否支持D8Dex

### ISSUE THREAD

**Issue by yizeliang** [Tencent/tinker#701]

**Comment by tomystang** [comment]
如果代码里没用到java8引入的新语法特性就没问题。

**Comment by yizeliang** [comment]
@tomystang 那么如果用了java8 新语法特性,不启用D8dex,有问题么

**Comment by tomystang** [comment]
额，那要看下生成出来的dex文件头是不是dex.035了，如果数字部分大于035，tinker暂时是不支持的。
