### ISSUE TITLE
No dexes were changed, nothing needs to be done next.

### ISSUE THREAD

**Issue by zmylls** [Tencent/tinker#702]
异常类型：app运行时异常

手机型号：荣耀9 ；乐视Lex 620；

手机系统版本：Android 7.0+ ；Android6.0

tinker版本：1.8.1

gradle版本：3.3

系统：如:Mac

描述：java文件做了修改，然后打补丁包，但提示No dexes were changed, nothing needs to be done next.并没有比较出差异的部分

堆栈/日志：
Unable to strip library '/Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/intermediates/transforms/mergeJniLibs/release/folders/2000/1f/main/lib/armeabi/libweibosdkcore.so', packaging it as is.
:app:transformResourcesWithMergeJavaResForRelease
:app:packageRelease
:app:assembleRelease
:app:tinkerPatchRelease
-----------------------Tinker patch begin-----------------------
configuration: 
oldApk:/Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/bakapk/app-release-3.2.42-1204-13-38-34.apk
newApk:/Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/apk/app-release.apk
outputFolder:/Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/tinkerPatch/release
isIgnoreWarning:false
isProtectedApp:false
7-ZipPath:/Users/zhangmingyao/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
useSignAPk:true
package meta fields: 
filed name:patchMessage, filed value:tinker is sample to use
filed name:platform, filed value:all
filed name:patchVersion, filed value:1
dex configs: 
dexMode: jar
dex loader:com.jianbao.doctor.MainApp
dex loader:com.tencent.tinker.loader.*
lib configs: 
libPattern:lib/.*/.*\.so
libPattern:/libs/.*\.jar
resource configs: 
resPattern:AndroidManifest\.xml
resPattern:res/.*
resPattern:resources\.arsc
resPattern:assets/.*
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: app-release-3.2.42-1204-13-38-34.apk, size=33688619, md5=ef44bab1b6a97b28865851ebdf2ad560
new apk: app-release.apk, size=33688271, md5=98dbbc32ffa2f2eaf38a9310b0953fea

UnZipping apk to /Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/tinkerPatch/release/app-release-3.2.42-1204-13-38-34
UnZipping apk to /Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/tinkerPatch/release/app-release
found modify resource: resources.arsc, but it is logically the same as original new resources.arsc, just ignore!
No dexes were changed, nothing needs to be done next.
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:/Users/zhangmingyao/.gradle/caches/modules-2/files-2.1/com.tencent.mm/SevenZip/1.1.10/cc390e6c704b74496d9ba0e9b46d2cf8a2a96b84/SevenZip-1.1.10-osx-x86_64.exe
Result: final signed patch result: /Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/tinkerPatch/release/patch_signed.apk, size=2082
Result: final signed with 7zip patch result: /Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/tinkerPatch/release/patch_signed_7zip.apk, size=2406
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 324 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 3.313000s
Tinker patch done, you can go to file to find the output /Users/zhangmingyao/work_space/yibao/AS-Jambo/app/build/outputs/tinkerPatch/release
-----------------------Tinker patch end-------------------------

BUILD SUCCESSFUL

**Comment by tomystang** [comment]
dex pattern配错了？确认一下app/build.gradle里的这个配置吧：
![image](https://user-images.githubusercontent.com/20535341/33586718-ad8c7056-d9a5-11e7-93e3-c580f5a1e1d8.png)

**Comment by zmylls** [comment]
好的谢谢。另外我想问下，默认这个配置就可以吗，哪些情况下可能需要修改？

**Comment by tomystang** [comment]
一般是不用改的，除非你要patch的dex另外放到了别的文件夹里。比方说你有dex放到了assets/xxx.dex，那这个pattern里面就要加上assets/xxx.dex，或者用通配符：assets/*.dex
