### ISSUE TITLE
求一个集成了 纯原生tinker + andresguard 的一个demo啊

### ISSUE THREAD

**Issue by wuhaiyang** [Tencent/tinker#714]
FQ 文档给出的demo 是集成的[tinkerpatch](https://github.com/TinkerPatch/tinkerpatch-andresguard-sample)，并不是纯原生tinker

@shwenzhang  感谢！！！

**Comment by weinierfei** [comment]
tinker-sample-android 给出的不就是纯tinker嘛

**Comment by weinierfei** [comment]
哦,你是想要andresguard的,瞅瞅这个**https://github.com/weinierfei/TinkerDemo**  如果能跑起来的话

**Comment by wuhaiyang** [comment]
谢谢。官方似乎已经支持了
