### ISSUE TITLE
补丁合成时间在1.7.11版本之后变长了

### ISSUE THREAD

**Issue by partoftom** [Tencent/tinker#715]
异常类型：同样的补丁修改, 合成时间在1.7.11上是20秒,1.9.1上是26秒.

手机型号：Vivo X7

手机系统版本：Android 5.1.1

tinker版本：1.9.1

gradle版本：2.3.3

是否使用热更新SDK： 无

对其他手机和其他系统版本也做过合成时间的测试,发现1.9.1普遍会比1.7.11的版本合成时间慢四五秒,想请问下是什么原因.谢谢.

**Comment by shwenzhang** [comment]
应该是将多个dex合成到同一个apk吧

**Comment by tjoven** [comment]
同问，apk70m，加载patch，做dex diff运算用了27s，这时间也太长了。有什么解决办法啊？
SampleResultService receive result:
PatchResult:
isSuccess:true
rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
costTime:27595
patchVersion:1b613385e0fa75b01fbb00fe45a08d50
