### ISSUE TITLE
使用Sample里面的SampleUncaughtExceptionHandler做crash启动保护能同时上传崩溃日志吗？

### ISSUE THREAD

**Issue by c1024** [Tencent/tinker#72]
Wiki里面提到防止补丁后程序无法启动，使用SampleUncaughtExceptionHandler.java做crash启动保护。这里更推荐的是进入安全模式，使用配置的方式强制清理或者升级补丁；
如果用Fabric上传崩溃日志，使用Sample里面的SampleUncaughtExceptionHandler做crash启动保护能同时上传崩溃日志吗？

**Comment by shwenzhang** [comment]
你把具体的逻辑，放到系统已有的UncaughtExceptionHandle即可

**Comment by c1024** [comment]
@shwenzhang 如果像Fabric这种UncaughtExceptionHandler在sdk内部，外部无法获取怎么办

**Comment by shwenzhang** [comment]
这里就比较难办，它们没有类似回调的接口吗？

**Comment by c1024** [comment]
像Fabric是没有

**Comment by zzwwws** [comment]
这里不影响Fabric的crash上传的，请看下图的堆栈：
![image](https://cloud.githubusercontent.com/assets/2063712/18980914/c8cdd9f6-870b-11e6-83e8-b11a46a4bea4.png)
这里先后设置了三次Thread.setDefaultUncaughtExceptionHandler()，也就是说defaultUncaughtExceptionHandler的值改变了三次。但是注意到一般我们重写uncaughtException方法时，处理自己的exception逻辑，最后再调用defaultExceptionHandler.uncaughtException(thread, ex)，也就是抛给上一个defaultUncaughtExceptionHandler对象处理了，看下Fabric的例子
![image](https://cloud.githubusercontent.com/assets/2063712/18980935/0782f014-870c-11e6-835d-fc95f43c4e22.png)
所以，可以同时上传崩溃日志，不用担心。
