### ISSUE TITLE
寄生兽漏洞（ZipEntry.getName()方法未过滤"../"，可导致目录遍历）

### ISSUE THREAD

**Issue by RainMtime** [Tencent/tinker#722]
# 其实是公司的扫描工具金刚，报的一个漏洞（～.~）。
文件类：com.tencent.tinker.lib.patch.DexDiffPatchInternal

存在ZipEntry.getName()的方法调用，但是未过滤"../"符号，所以安全工具会扫出来，进行安全上报。
**目前代码逻辑，其实还ok，不过安全工具，老扫出来**，规范起见，可以对ZipEntry.getName()，过滤一些"../"，省的工具老扫出来。

## 寄生兽漏洞详情概述：
http://ele7enxxh.com/Exaggerated-Android-Vulnerability-Parasyte.html

**Comment by tomystang** [comment]
多谢反馈，下个版本修复。
