### ISSUE TITLE
只有华为H60-LO3（Android 4.4.2）的手机打补丁失败，其他手机正常

### ISSUE THREAD

**Issue by wildma** [Tencent/tinker#724]
异常类型：app运行时异常

手机型号：华为H60-LO3

手机系统版本：Android 4.4.2

tinker版本：1.7.11

gradle版本：2.14.1

是否使用热更新SDK： 否，用的原生的Tinker

系统：Windows

堆栈/日志：
`加载完补丁后第一次进来，黑屏
主要信息：
12-20 13:47:41.930 7071-7071/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
12-20 13:47:41.935 7071-7071/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: tinker has fast crash 1 times

次要信息：
12-20 13:47:41.880 7071-7071/com.bibi.bibi W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-20 13:47:41.880 7071-7071/com.bibi.bibi I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/data/com.bibi.bibi/tinker/patch.info , oldVer:7895dece2d3d9b328aa88b6d73541cf7, newVer:7895dece2d3d9b328aa88b6d73541cf7, fingerprint:Huawei/H60-L03/hwH60:4.4.2/HDH60-L03/C01B318:user/ota-rel-keys,release-keys, oatDir:odex
12-20 13:47:41.885 7071-7071/com.bibi.bibi W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.bibi.bibi count:1
12-20 13:47:41.895 7071-7071/com.bibi.bibi I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.bibi.bibi-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.bibi.bibi-2, /vendor/lib, /system/lib, /data/datalib]]]
12-20 13:47:41.895 7071-7071/com.bibi.bibi I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/data/com.bibi.bibi/tinker/patch-7895dece/odex, dex size:2
12-20 13:47:41.900 7071-7071/com.bibi.bibi I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.bibi.bibi/tinker/patch-7895dece/dex/changed_classes.dex.jar", zip file "/data/data/com.bibi.bibi/tinker/patch-7895dece/dex/test.dex.jar", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.bibi.bibi-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.bibi.bibi-2, /vendor/lib, /system/lib, /data/datalib]]], dex size:2
12-20 13:47:41.900 7071-7071/com.bibi.bibi W/Tinker.ClassLoaderAdder: checkDexInstall result:true
12-20 13:47:41.900 7071-7071/com.bibi.bibi I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-20 13:47:41.915 7071-7071/com.bibi.bibi I/MultiDex: VM with version 1.6.0 does not have multidex support
12-20 13:47:41.915 7071-7071/com.bibi.bibi I/MultiDex: install
12-20 13:47:41.915 7071-7071/com.bibi.bibi I/MultiDex: MultiDexExtractor.load(/data/app/com.bibi.bibi-2.apk, false)
12-20 13:47:41.920 7071-7071/com.bibi.bibi I/MultiDex: loading existing secondary dex files
12-20 13:47:41.920 7071-7071/com.bibi.bibi I/MultiDex: load found 2 secondary dex files
12-20 13:47:41.920 7071-7071/com.bibi.bibi I/MultiDex: install done
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.SamplePatchListener: application maxMemory:192
12-20 13:47:41.925 7071-7071/com.bibi.bibi W/Tinker.Tinker: tinker patch directory: /data/data/com.bibi.bibi/tinker
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.bibi.bibi, main process:true, systemOTA:false, oatDir:odex, useInterpretMode:false
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:7895dece2d3d9b328aa88b6d73541cf7, current:7895dece2d3d9b328aa88b6d73541cf7
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchVersionChanged: patch version change from  to 7895dece2d3d9b328aa88b6d73541cf7
12-20 13:47:41.925 7071-7071/com.bibi.bibi I/Tinker.DefaultLoadReporter: onLoadPatchVersionChanged, try kill all other process
12-20 13:47:41.930 7071-7071/com.bibi.bibi I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.bibi.bibi/tinker, code: 0, cost: 97ms
12-20 13:47:41.930 7071-7071/com.bibi.bibi W/dalvikvm: Class resolved by unexpected DEX: Lcom/bibi/bibi/tinker/SampleLoadReporter;(0x43294728):0x76e59000 ref [Lcom/bibi/bibi/tinker/SampleTinkerReport;] Lcom/bibi/bibi/tinker/SampleTinkerReport;(0x43294728):0x7701e000
12-20 13:47:41.930 7071-7071/com.bibi.bibi W/dalvikvm: (Lcom/bibi/bibi/tinker/SampleLoadReporter; had used a different Lcom/bibi/bibi/tinker/SampleTinkerReport; during pre-verification)
12-20 13:47:41.930 7071-7071/com.bibi.bibi W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4165fc50)
12-20 13:47:41.930 7071-7071/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
12-20 13:47:41.935 7071-7071/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: tinker has fast crash 1 times
12-20 13:47:41.940 7071-7071/com.bibi.bibi W/dalvikvm: Class resolved by unexpected DEX: Lcom/bibi/bibi/tinker/SampleUncaughtExceptionHandler;(0x43294728):0x76e59000 ref [Lcom/bibi/bibi/tinker/Utils;] Lcom/bibi/bibi/tinker/Utils;(0x43294728):0x7701e000
12-20 13:47:41.940 7071-7071/com.bibi.bibi W/dalvikvm: (Lcom/bibi/bibi/tinker/SampleUncaughtExceptionHandler; had used a different Lcom/bibi/bibi/tinker/Utils; during pre-verification)

第二次进来，黑屏
主要信息：
12-20 13:52:00.005 10867-10867/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
12-20 13:52:00.020 10867-10867/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: tinker has fast crash 2 times

次要信息：
12-20 13:51:59.970 10867-10867/com.bibi.bibi W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-20 13:51:59.970 10867-10867/com.bibi.bibi W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.bibi.bibi count:2
12-20 13:51:59.975 10867-10867/com.bibi.bibi I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.bibi.bibi-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.bibi.bibi-2, /vendor/lib, /system/lib, /data/datalib]]]
12-20 13:51:59.980 10867-10867/com.bibi.bibi I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/data/com.bibi.bibi/tinker/patch-7895dece/odex, dex size:2
12-20 13:51:59.980 10867-10867/com.bibi.bibi I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.bibi.bibi/tinker/patch-7895dece/dex/changed_classes.dex.jar", zip file "/data/data/com.bibi.bibi/tinker/patch-7895dece/dex/test.dex.jar", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.bibi.bibi-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.bibi.bibi-2, /vendor/lib, /system/lib, /data/datalib]]], dex size:2
12-20 13:51:59.980 10867-10867/com.bibi.bibi W/Tinker.ClassLoaderAdder: checkDexInstall result:true
12-20 13:51:59.980 10867-10867/com.bibi.bibi I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
12-20 13:51:59.995 10867-10867/com.bibi.bibi I/MultiDex: VM with version 1.6.0 does not have multidex support
12-20 13:51:59.995 10867-10867/com.bibi.bibi I/MultiDex: install
12-20 13:51:59.995 10867-10867/com.bibi.bibi I/MultiDex: MultiDexExtractor.load(/data/app/com.bibi.bibi-2.apk, false)
12-20 13:52:00.000 10867-10867/com.bibi.bibi I/MultiDex: loading existing secondary dex files
12-20 13:52:00.000 10867-10867/com.bibi.bibi I/MultiDex: load found 2 secondary dex files
12-20 13:52:00.000 10867-10867/com.bibi.bibi I/MultiDex: install done
12-20 13:52:00.005 10867-10867/com.bibi.bibi I/Tinker.SamplePatchListener: application maxMemory:192
12-20 13:52:00.005 10867-10867/com.bibi.bibi W/Tinker.Tinker: tinker patch directory: /data/data/com.bibi.bibi/tinker
12-20 13:52:00.005 10867-10867/com.bibi.bibi I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
12-20 13:52:00.005 10867-10867/com.bibi.bibi I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.bibi.bibi, main process:true, systemOTA:false, oatDir:odex, useInterpretMode:false
12-20 13:52:00.005 10867-10867/com.bibi.bibi I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:7895dece2d3d9b328aa88b6d73541cf7, newVersion:7895dece2d3d9b328aa88b6d73541cf7, current:7895dece2d3d9b328aa88b6d73541cf7
12-20 13:52:00.005 10867-10867/com.bibi.bibi I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
12-20 13:52:00.005 10867-10867/com.bibi.bibi I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.bibi.bibi/tinker, code: 0, cost: 76ms
12-20 13:52:00.005 10867-10867/com.bibi.bibi W/dalvikvm: Class resolved by unexpected DEX: Lcom/bibi/bibi/tinker/SampleLoadReporter;(0x432956e0):0x76e59000 ref [Lcom/bibi/bibi/tinker/SampleTinkerReport;] Lcom/bibi/bibi/tinker/SampleTinkerReport;(0x432956e0):0x7701e000
12-20 13:52:00.005 10867-10867/com.bibi.bibi W/dalvikvm: (Lcom/bibi/bibi/tinker/SampleLoadReporter; had used a different Lcom/bibi/bibi/tinker/SampleTinkerReport; during pre-verification)
12-20 13:52:00.005 10867-10867/com.bibi.bibi W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4165fc50)
12-20 13:52:00.005 10867-10867/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
12-20 13:52:00.020 10867-10867/com.bibi.bibi E/Tinker.SampleUncaughtExHandler: tinker has fast crash 2 times
12-20 13:52:00.020 10867-10867/com.bibi.bibi W/dalvikvm: Class resolved by unexpected DEX: Lcom/bibi/bibi/tinker/SampleUncaughtExceptionHandler;(0x432956e0):0x76e59000 ref [Lcom/bibi/bibi/tinker/Utils;] Lcom/bibi/bibi/tinker/Utils;(0x432956e0):0x7701e000
12-20 13:52:00.020 10867-10867/com.bibi.bibi W/dalvikvm: (Lcom/bibi/bibi/tinker/SampleUncaughtExceptionHandler; had used a different Lcom/bibi/bibi/tinker/Utils; during pre-verification)

第三次进来，就可以正常进入了。tinker应该做了清理机制，即把合成的补丁移除掉，等第三次运行的时候就不会再加载补丁了，所以这个时候就正常运行了，但是补丁是没有合成进去的。

12-20 13:53:01.370 11746-11746/com.bibi.bibi W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
12-20 13:53:01.375 11746-11746/com.bibi.bibi W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.bibi.bibi count:3
12-20 13:53:01.380 11746-11746/com.bibi.bibi W/Tinker.TinkerLoader: tryLoadPatchFiles:checkSafeModeCount fail
12-20 13:53:01.380 11746-11746/com.bibi.bibi I/MultiDex: VM with version 1.6.0 does not have multidex support
12-20 13:53:01.380 11746-11746/com.bibi.bibi I/MultiDex: install
12-20 13:53:01.385 11746-11746/com.bibi.bibi I/MultiDex: MultiDexExtractor.load(/data/app/com.bibi.bibi-2.apk, false)
12-20 13:53:01.390 11746-11746/com.bibi.bibi I/MultiDex: loading existing secondary dex files
12-20 13:53:01.390 11746-11746/com.bibi.bibi I/MultiDex: load found 2 secondary dex files
12-20 13:53:01.390 11746-11746/com.bibi.bibi I/MultiDex: install done
12-20 13:53:01.395 11746-11746/com.bibi.bibi I/Tinker.SamplePatchListener: application maxMemory:192
12-20 13:53:01.395 11746-11746/com.bibi.bibi W/Tinker.Tinker: tinker patch directory: /data/data/com.bibi.bibi/tinker
12-20 13:53:01.395 11746-11746/com.bibi.bibi I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
12-20 13:53:01.395 11746-11746/com.bibi.bibi I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-25, process name:com.bibi.bibi, main process:true, systemOTA:false, oatDir:odex, useInterpretMode:false
12-20 13:53:01.395 11746-11746/com.bibi.bibi I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:7895dece2d3d9b328aa88b6d73541cf7, newVersion:7895dece2d3d9b328aa88b6d73541cf7, current:7895dece2d3d9b328aa88b6d73541cf7
12-20 13:53:01.395 11746-11746/com.bibi.bibi I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-25
12-20 13:53:01.395 11746-11746/com.bibi.bibi I/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load unCatch exception: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
12-20 13:53:01.405 11746-11746/com.bibi.bibi I/Tinker.DefaultLoadReporter: unCaught exception disable tinker forever with sp
12-20 13:53:01.405 11746-11746/com.bibi.bibi E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
12-20 13:53:01.410 11746-11746/com.bibi.bibi E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
                                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:247)
                                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:161)
                                                                                   at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:130)
                                                                                   at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                                                   at android.app.Application.attach(Application.java:200)
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586)
                                                                                   at android.app.ActivityThread.access$1800(ActivityThread.java:139)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
12-20 13:53:01.410 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/info.lock
12-20 13:53:01.410 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/patch-7895dece.apk
12-20 13:53:01.410 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/dex/changed_classes.dex.jar
12-20 13:53:01.410 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/dex/test.dex.jar
12-20 13:53:01.410 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/dex
12-20 13:53:01.410 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/odex/changed_classes.dex.dex
12-20 13:53:01.415 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/odex/test.dex.dex
12-20 13:53:01.415 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece/odex
12-20 13:53:01.415 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch-7895dece
12-20 13:53:01.415 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker/patch.info
12-20 13:53:01.415 11746-11746/com.bibi.bibi I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.bibi.bibi/tinker
12-20 13:53:01.415 11746-11746/com.bibi.bibi I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.bibi.bibi/tinker, code: -25, cost: 77ms
12-20 13:53:01.415 11746-11746/com.bibi.bibi W/Tinker.Tinker: tinker load fail!`

**Comment by tomystang** [comment]
com.bibi.bibi.tinker.Utils
这个类应该是被你的Application直接引用了，要加到dex { } 的 loader 配置里才行的。
建议只在ApplicationLike里引用这些工具类。

**Comment by wildma** [comment]
这个是tinker源码里面的utils，没有在Application里直接引用

**Comment by 490965536** [comment]
你有解决么... 我也是遇见这个问题...

**Comment by wildma** [comment]
@tomystang 这个是tinker源码里面的utils，没有在Application里直接引用

**Comment by wildma** [comment]
@490965536 没有，暂时没去弄它了。

**Comment by shwenzhang** [comment]
1. 使用了加固模式？是什么加固方案
2. Class ref in pre-verified class resolved to unexpected implementation 关键原因在这里，出现了preverify,即有类被提前加载了

**Comment by wildma** [comment]
@shwenzhang 用的是360加固。
