### ISSUE TITLE
Tinker.DefaultPatchReporter: Caused by: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by xingchen1106** [Tencent/tinker#725]
异常类型：修复失败

手机型号：Vivo X3V

手机系统版本：Android 4.4

tinker版本：1.9.2

是否使用热更新SDK： 否

系统：wetest

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。
Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
12-22 15:54:20.725	12164	12164	D	
Tinker.DefaultAppLike: onCreate
12-22 15:54:20.725	12164	12177	I	
Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
12-22 15:54:20.775	12164	12177	W	
Tinker.UpgradePatchRetry: try copy file: /data/data/cn.xx.sanxiao/files/patch/1.0/1.0.0.1_1003.apk to /data/data/cn.xx.sanxiao/tinker_temp/temp.apk
12-22 15:54:20.775	12164	12177	I	
Tinker.TinkerPatchService: try to increase patch process priority
12-22 15:54:20.785	1211	1552	I	
am_create_service: [0,1101414712,.TinkerPatchService$InnerService,11607,12164]
12-22 15:54:20.865	12164	12177	I	
Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:b9d0c462267f5e5117e53327add680d4
12-22 15:54:20.875	12164	12177	W	
Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/cn.xx.sanxiao/tinker/patch.info: open failed: ENOENT (No such file or directory)
12-22 15:54:20.875	12164	12177	W	
Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/cn.xx.sanxiao/tinker/patch.info: open failed: ENOENT (No such file or directory)
12-22 15:54:20.875	12164	12177	I	
Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/cn.xx.sanxiao/tinker/patch-b9d0c462
12-22 15:54:20.875	12164	12177	W	
Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/data/cn.xx.sanxiao/files/patch/1.0/1.0.0.1_1003.apk size: 3521, dest file: /data/data/cn.xx.sanxiao/tinker/patch-b9d0c462/patch-b9d0c462.apk size:3521
12-22 15:54:20.875	12164	12177	W	
Tinker.DexDiffPatchInternal: patch recover, dex is not contained
12-22 15:54:21.765	12164	12177	I	
dalvikvm: "IntentService[TinkerPatchService]" prio=5 tid=10 RUNNABLE
12-22 15:54:21.765	12164	12177	I	
dalvikvm: at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
12-22 15:54:21.775	12164	12177	I	
Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path: /data/data/cn.xx.sanxiao/files/patch/1.0/1.0.0.1_1003.apk, throwable: Tinker Exception:patch lib extract failed (null).
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: tinker patch exception com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch lib extract failed (null).
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.lib.patch.BsDiffPatchInternal.extractBsDiffInternals(BsDiffPatchInternal.java:204)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.lib.patch.BsDiffPatchInternal.patchLibraryExtractViaBsDiff(BsDiffPatchInternal.java:68)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.lib.patch.BsDiffPatchInternal.tryRecoverLibraryFiles(BsDiffPatchInternal.java:59)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:141)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at android.os.Handler.dispatchMessage(Handler.java:102)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at android.os.Looper.loop(Looper.java:136)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at android.os.HandlerThread.run(HandlerThread.java:61)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: Caused by: java.lang.OutOfMemoryError
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.bsdiff.BSUtil.inputStreamToByte(BSUtil.java:77)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.bsdiff.BSPatch.patchFast(BSPatch.java:265)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: at com.tencent.tinker.lib.patch.BsDiffPatchInternal.extractBsDiffInternals(BsDiffPatchInternal.java:184)
12-22 15:54:21.775	12164	12177	E	
Tinker.DefaultPatchReporter: ... 8 more
12-22 15:54:21.775	12164	12177	I	
Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.xx.sanxiao/tinker/patch-b9d0c462/patch-b9d0c462.apk
12-22 15:54:21.775	12164	12177	I	
Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.xx.sanxiao/tinker/patch-b9d0c462/lib/lib/armeabi-v7a
12-22 15:54:21.775	12164	12177	I	
Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.xx.sanxiao/tinker/patch-b9d0c462/lib/lib
12-22 15:54:21.775	12164	12177	I	
Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.xx.sanxiao/tinker/patch-b9d0c462/lib
12-22 15:54:21.785	12164	12177	I	
Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.xx.sanxiao/tinker/patch-b9d0c462
12-22 15:54:21.785	12164	12177	D	
jj.Tinker.PatchPatchReporter: PatchPatchReporter onPatchException
12-22 15:54:21.785	12164	12177	I	
Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/data/cn.xx.sanxiao/files/patch/1.0/1.0.0.1_1003.apk, success: false, cost: 1006
12-22 15:54:21.785	12164	12177	I	
Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/cn.xx.sanxiao/tinker_temp/temp.apk
12-22 15:54:21.785	12164	12177	D	
jj.Tinker.PatchPatchReporter: PatchPatchReporter onPatchResult
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: PatchResult:
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: isSuccess:false
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: rawPatchFilePath:/data/data/cn.xx.sanxiao/files/patch/1.0/1.0.0.1_1003.apk
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: costTime:1006
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: patchVersion:b9d0c462267f5e5117e53327add680d4
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService: Throwable:Tinker Exception:patch lib extract failed (null).
12-22 15:54:21.815	12123	12185	I	
Tinker.DefaultTinkerResultService:

**Comment by shwenzhang** [comment]
内存不足，可以过滤部分内存特别低的手机。是否修复了一个比较大的文件

**Comment by 9527se** [comment]
> 内存不足，可以过滤部分内存特别低的手机。是否修复了一个比较大的文件

请问怎么过滤的。有api 吗

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
