### ISSUE TITLE
tinkerSupport打包命名问题

### ISSUE THREAD

**Issue by gzsword** [Tencent/tinker#730]
项目中Flavor比较多，每个flavor都对应特定产品，有各自定制的类型。
目前情况是这样的：
使用**tinkerSupport**插件，配置了**enableProxyApplication = true**（项目中module多，application改起来非常麻烦），bakPath输出路径可以更改，但是我们希望按照flavor去重新命名文件夹

tinker默认：
**build/bakApk/app-1227-17-05-07/xiaomi/app-xiaomi-release.apk**

但是我们希望如下：
**build/bakApk/xiaomi/app-1227-17-05-07/app-xiaomi-release.apk**
请问如何更改？官方api文档好像没有相关配置。

注：
我们也是用了tinkerPatch去配置，参考是下面这个gradle，通过脚本去更改输出：
https://github.com/Tencent/tinker/blob/master/tinker-sample-android/app/build.gradle
但是如果使用**tinkerPatch**，如何配置**enableProxyApplication** 这个属性？

或者tinker插件禁止创建，我们自己gradle脚本进行copy相关apk、mapping、R文件

谢谢。

**Comment by shwenzhang** [comment]
tinker默认没有提供enableProxyApplication的属性，具体可以咨询tinkerPatch的人员
