### ISSUE TITLE
Vivo x9 补丁合成失败

### ISSUE THREAD

**Issue by oybo** [Tencent/tinker#732]
异常类型：app运行时异常

手机型号：Vivo x9

手机系统版本：Android 7.1.1

tinker版本：1.9.1

gradle版本：2.14.1

是否使用热更新SDK： TinkerPatch SDK

系统：android

堆栈/日志：
2-28 17:09:07.410 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 1 times
12-28 17:09:22.412 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 2 times
12-28 17:09:37.414 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 3 times
12-28 17:09:52.416 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 4 times
12-28 17:10:07.418 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 5 times
12-28 17:10:22.421 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 6 times
12-28 17:10:37.423 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 7 times
12-28 17:10:52.426 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 8 times
12-28 17:11:07.428 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 9 times
12-28 17:11:22.429 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 10 times
12-28 17:11:37.432 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 11 times
12-28 17:11:52.437 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 12 times
12-28 17:12:07.439 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 13 times
12-28 17:12:22.441 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 14 times
12-28 17:12:37.444 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 15 times
12-28 17:12:52.447 17691-17722/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 16 times
12-28 17:13:07.449 17691-17722/? I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/com.kanshushenqi.ebook.app/tinker/patch-721ec110/odex/tinker_classN.dex, size 0
12-28 17:13:07.451 17691-17722/? E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file tinker_classN.dex is not exist, return false
12-28 17:13:07.453 17691-17722/? I/Tinker.DefaultPatchReporter: patchReporter onPatchDexOptFail: dex opt fail path: /storage/emulated/0/Download/aaaa.abc, dex size: 1
12-28 17:13:07.456 17691-17722/? E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexOptExist failed
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.waitAndCheckDexOptFile(DexDiffPatchInternal.java:121)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:152)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:181)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
12-28 17:13:07.457 17691-17722/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, check dex opt file failed

**Comment by shwenzhang** [comment]
Vivo部分手机异步dex2oat导致，后续版本会增大等待时间
