### ISSUE TITLE
 java.lang.IllegalArgumentException:com.tencent.tinker.loader.hotplug.interceptor.Interceptor$ITinkerHotplugProxy appears more than once

### ISSUE THREAD

**Issue by van416** [Tencent/tinker#735]
异常类型：app运行时异常

手机型号：荣耀H60-L01 、华为PE

手机系统版本：Android 4.4.2 、4.4.4 、4.2.2

tinker版本：1.9.1

gradle版本：3.0.0

是否使用热更新SDK： 否

系统：android

堆栈/日志：
通过bugly里面看错误日志

java.lang.RuntimeException:cl: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.xx.xx/tinker/patch-b90ee6d9/dex/classes.dex.jar", zip file "/data/data/com.xx.xx/tinker/patch-b90ee6d9/dex/classes2.dex.jar", zip file "/data/data/com.xx.xx/tinker/patch-b90ee6d9/dex/classes3.dex.jar", zip file "/data/data/com.xx.xx/tinker/patch-b90ee6d9/dex/test.dex.jar", zip file "/data/app/com.xx.xx-1.apk", zip file "/data/data/com.xx.xx/code_cache/secondary-dexes/com.xx.xx-1.apk.classes2.zip", zip file "/data/data/com.xx.xx/code_cache/secondary-dexes/com.xx.xx-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/com.xx.xx-1, /vendor/lib, /system/lib, /data/datalib]]]
--
com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor.createProxy(ServiceBinderInterceptor.java:162)
 ......
Caused by:
 java.lang.IllegalArgumentException:com.tencent.tinker.loader.hotplug.interceptor.Interceptor$ITinkerHotplugProxy appears more than once
java.lang.reflect.Proxy.getProxyClass(Proxy.java:116)
 java.lang.reflect.Proxy.newProxyInstance(Proxy.java:212)
com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor.createProxy(ServiceBinderInterceptor.java:153)
com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor.access$100(ServiceBinderInterceptor.java:28)
 com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor$FakeClientBinderHandler.invoke(ServiceBinderInterceptor.java:212)
com.tencent.tinker.loader.hotplug.interceptor.$Proxy0.queryLocalInterface(Native Method)
com.qihoo360.mobilesafe.loaded.client.m.queryLocalInterface(SourceFile:531)
android.app.ActivityManagerNative.asInterface(ActivityManagerNative.java:63)
android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2063)
android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2057)
android.util.Singleton.get(Singleton.java:34)
android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:76)
android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:770)
android.os.Handler.handleCallback(Handler.java:733)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:136)
android.app.ActivityThread.main(ActivityThread.java:5314)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
dalvik.system.NativeStart.main(Native Method)

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。
注意：由于Android Q对Activity的启动流程做了非常大的改动，并且反复限制了相关api的反射调用，因此Tinker未来的版本计划移除对补丁新增Activity的支持，详情请参考置顶issue。
