### ISSUE TITLE
isSuccess false

### ISSUE THREAD

**Issue by zhiqiangli520210** [Tencent/tinker#739]
tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:201281365,jar

**Comment by zhiqiangli520210** [comment]
01-08 11:34:32.686 32493-32493/? I/CrashReport-Native: Opened system log record file: /data/data/com.example.lzq.buglyhotfix/app_bugly/sys_log_1515382472698810.txt
01-08 11:34:32.686 32493-32493/? I/CrashReport-Native: NativeBuglyVersion:3.3.1
01-08 11:34:32.686 32493-32493/? I/CrashReport: [Native] Native Crash Report enable.
01-08 11:34:32.686 32493-32493/? D/CrashReport: [Native] Check extra jni for Bugly NDK v3.3.1
01-08 11:34:32.686 32493-32493/? I/CrashReport: [Native] Info setting jni can be accessed.
01-08 11:34:32.686 32493-32493/? I/CrashReport: [Native] Extra jni can be accessed.
01-08 11:34:32.686 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.jni.NativeCrashHandler$1
01-08 11:34:32.686 32493-32493/? I/CrashReport: anr changed to true
01-08 11:34:32.686 32493-32493/? I/CrashReport: start anr monitor!
01-08 11:34:32.686 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.anr.b$2
01-08 11:34:32.686 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.d$1
01-08 11:34:32.686 32493-32493/? D/CrashReport: add action android.net.conn.CONNECTIVITY_CHANGE
01-08 11:34:32.686 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.BuglyBroadcastRecevier$1
01-08 11:34:32.686 32493-32517/? D/CrashReport: [Util] try to lock file:native_record_lock (pid=32493 | tid=32517)
01-08 11:34:32.686 32493-32517/? D/CrashReport: [Util] successfully locked file:native_record_lock (pid=32493 | tid=32517)
01-08 11:34:32.686 32493-32517/? I/CrashReport-Native: Set native info: app version(1.0.2)
01-08 11:34:32.686 32493-32517/? I/CrashReport-Native: Set native info: app package(com.example.lzq.buglyhotfix)
01-08 11:34:32.686 32493-32517/? I/CrashReport-Native: Set native info: user ID(unknown)
01-08 11:34:32.686 32493-32517/? I/CrashReport-Native: Set native info: isAppForeground(false)
01-08 11:34:32.686 32493-32517/? I/CrashReport-Native: Set native info: launchTime(1515382472670)
01-08 11:34:32.686 32493-32517/? D/CrashReport: [Native] Clean tombs 0
01-08 11:34:32.686 32493-32517/? D/CrashReport: [Util] try to unlock file:native_record_lock (pid=32493 | tid=32517)
01-08 11:34:32.686 32493-32517/? D/CrashReport: [Util] successfully unlocked file:native_record_lock (pid=32493 | tid=32517)
01-08 11:34:32.686 32493-32517/? D/CrashReport: clean tombs 0
01-08 11:34:32.686 32493-32517/? D/CrashReport: [ExtraCrashManager] Trying to notify Bugly agents.
01-08 11:34:32.686 32493-32517/? D/CrashReport: [ExtraCrashManager] Bugly game agent has been notified.
01-08 11:34:32.686 32493-32517/? I/CrashReport: [BuglyBroadcastRecevier] Register broadcast receiver of Bugly.
01-08 11:34:32.696 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
01-08 11:34:32.696 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$2
01-08 11:34:32.696 32493-32493/? I/CrashReport: Beta init start....
01-08 11:34:32.696 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
01-08 11:34:32.696 32493-32493/? I/CrashReport: Beta will init at: com.example.lzq.buglyhotfix
01-08 11:34:32.696 32493-32493/? I/CrashReport: current process: com.example.lzq.buglyhotfix:patch
01-08 11:34:32.696 32493-32493/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.common.strategy.a$1
01-08 11:34:32.696 32493-32493/? I/CrashReportInfo: [init] Bugly initialization finished.
01-08 11:34:32.706 32493-32516/? D/CrashReport: [Database] insert t_ui success.
01-08 11:34:32.706 32493-32516/? D/CrashReport: [Database] insert t_ui success with ID: 9
01-08 11:34:32.706 32493-32518/? D/CrashReport: [Strategy] Notify com.tencent.bugly.crashreport.biz.b
01-08 11:34:32.706 32493-32518/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.biz.a$2
01-08 11:34:32.706 32493-32518/? D/CrashReport: [Strategy] Notify com.tencent.bugly.CrashModule
01-08 11:34:32.706 32493-32517/? D/CrashReport: Uploading frequency will not be checked if SDK is in debug mode.
01-08 11:34:32.706 32493-32518/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.crash.c$2
01-08 11:34:32.706 32493-32516/? D/CrashReport: [Util] try to lock file:local_crash_lock (pid=32493 | tid=32516)
01-08 11:34:32.706 32493-32516/? D/CrashReport: [Util] successfully locked file:local_crash_lock (pid=32493 | tid=32516)
01-08 11:34:32.706 32493-32518/? D/CrashReport: [Strategy] Notify com.tencent.bugly.beta.Beta
01-08 11:34:32.706 32493-32517/? D/CrashReport: [UserInfo] Upload user info(size: 1)
01-08 11:34:32.706 32493-32516/? D/CrashReport: [Util] try to unlock file:local_crash_lock (pid=32493 | tid=32516)
01-08 11:34:32.706 32493-32516/? D/CrashReport: [Util] successfully unlocked file:local_crash_lock (pid=32493 | tid=32516)
01-08 11:34:32.716 32493-32517/? D/CrashReport: summary type 1 vm:7
01-08 11:34:32.746 32493-32517/? D/CrashReport: [ap] Successfully get 'getprop' list.
01-08 11:34:32.756 32493-32517/? D/CrashReport: [ap] System properties number: 568ffffdsfsdfff.
01-08 11:34:32.776 32429-32429/? I/CrashReport: Tinker patch failure, result: 
                                                PatchResult: 
                                                isSuccess:false
                                                rawPatchFilePath:/data/data/com.example.lzq.buglyhotfix/app_tmpPatch/tmpPatch.apk
                                                costTime:37
                                                Throwable:Tinker Exception:can't recognize dex mode:3911889818,jar
这项目 是没人管了吗

**Comment by tomystang** [comment]
额，你是除了bugly之外还引了tinker的包吗？如果是的话，两者的版本要一致才行的。
如果之前可以，现在突然编不过了，那很大概率是这个版本的bugly那边的编译时和运行时tinker lib版本不一致，可以同时反馈给bugly那边看下。

**Comment by zhiqiangli520210** [comment]
最外层build.gradle中 classpath "com.tencent.bugly:tinker-support:1.1.1"
app工程目录下： compile "com.android.support:multidex:1.0.1" // 多dex配置
    //注释掉原有bugly的仓库
    //compile 'com.tencent.bugly:crashreport:latest.release'//其中latest.release指代最新版本号，也可以指定明确的版本号，例如2.3.2
    compile 'com.tencent.bugly:crashreport_upgrade:1.3.1'
    compile 'com.tencent.bugly:nativecrashreport:latest.release' //其中latest.release指代最新版本号，也可以指定明确的版本号，例如2.2.0
麻烦帮忙看一下

**Comment by zhiqiangli520210** [comment]
已经解决了 是bugly的版本问题

**Comment by xumingyi** [comment]
那个版本是对的呢？

**Comment by xumingyi** [comment]
> 已经解决了 是bugly的版本问题

那个版本是对的呢？
