### ISSUE TITLE
Error:(32, 0) Cause: can't get git rev, you should add git to system path or just input test value

### ISSUE THREAD

**Issue by winston1991** [Tencent/tinker#74]
我已经把git在系统环境路径里面设置了，但是还是这个错误，我把gitSha（）注释掉就报另外的错误:can't find TINKER_ID from the new apk manifest file, it must be set!

**Comment by dodola** [comment]
@winston1991 看一下这个issues， #11

**Comment by winston1991** [comment]
谢谢啦

**Comment by winston1991** [comment]
今天一大早来到公司第一件事就是看有没有大神回复我，果然有大神帮我解答@dodola。我迫不及待的打开As,昨天打入的tinker-sample-android,还不到10秒钟就构建成功啦，原来昨天报的错误：can't get git rev, you should add git to system path ，确实是没有把git设置到电脑的系统环境变量，昨天为什么设置了还不行呢？原来设置好git的系统环境变量在cmd命令行窗口测试设置成功之后还不行，你的AndroidStudio必须得重新启动一下，所以今天一早起来就成功了！！！

**Comment by WeissWill** [comment]
win10 用户请注意了！！升级了win10的用户会发现，win10下的cmd比以前平台下的cmd改进了不少，但这些改进也导致了Android studio在调用cmd上出现了问题。
解决办法：
打开cmd控制台窗口，在选项中进行如下操作，然后重启系统，如图：
![qq 20161019115725](https://cloud.githubusercontent.com/assets/13305202/19505212/59c24c44-95f3-11e6-9998-e7de908c4fe5.png)
