### ISSUE TITLE
使用bugly sdk，patch已经下载下来，但是合patch失败

### ISSUE THREAD

**Issue by poikl369** [Tencent/tinker#744]
异常类型：app运行时异常

手机型号：Nexus 6p

手机系统版本：Android 8.0

tinker版本：1.9.1

gradle版本：2.3.3

是否使用热更新SDK：Bugly SDK

系统：Mac

01-09 15:52:02.990 31819-31819/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
01-09 15:52:41.284 32096-32096/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.thel/tinker
01-09 15:52:41.285 32096-32096/? D/Tinker.DefaultAppLike: onBaseContextAttached:
01-09 15:52:41.286 32096-32096/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.thel.app.TheLApp
01-09 15:52:41.292 32096-32096/? I/Tinker.TinkerPatchListener: application maxMemory:192
01-09 15:52:41.294 32096-32096/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.thel/tinker
01-09 15:52:41.295 32096-32096/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
01-09 15:52:41.297 32096-32096/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.thel, main process:true, systemOTA:false, fingerPrint:google/angler/angler:8.0.0/OPR6.170623.019/4299446:user/release-keys, oatDir:null, useInterpretMode:false
01-09 15:52:41.297 32096-32096/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
01-09 15:52:41.298 32096-32096/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.thel/tinker, code: -2, cost: 3ms
01-09 15:52:41.298 32096-32096/? W/Tinker.Tinker: tinker load fail!
01-09 15:52:41.313 32096-32096/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
01-09 15:52:41.314 32096-32096/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
01-09 15:52:41.314 32096-32096/? D/Tinker.DefaultAppLike: onCreate
01-09 15:52:41.522 32115-32115/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.thel/tinker
01-09 15:52:41.522 32115-32115/? D/Tinker.DefaultAppLike: onBaseContextAttached:
01-09 15:52:41.524 32115-32115/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.thel.app.TheLApp
01-09 15:52:41.530 32115-32115/? I/Tinker.TinkerPatchListener: application maxMemory:192
01-09 15:52:41.532 32115-32115/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.thel/tinker
01-09 15:52:41.533 32115-32115/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
01-09 15:52:41.534 32115-32115/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.thel:pushservice, main process:false, systemOTA:false, fingerPrint:google/angler/angler:8.0.0/OPR6.170623.019/4299446:user/release-keys, oatDir:null, useInterpretMode:false
01-09 15:52:41.535 32115-32115/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
01-09 15:52:41.535 32115-32115/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.thel/tinker, code: -2, cost: 3ms
01-09 15:52:41.536 32115-32115/? W/Tinker.Tinker: tinker load fail!
01-09 15:52:41.541 32115-32115/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
01-09 15:52:41.542 32115-32115/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
01-09 15:52:41.542 32115-32115/? D/Tinker.DefaultAppLike: onCreate
01-09 15:52:42.452 32096-32096/com.thel W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
01-09 15:52:45.979 32096-32096/com.thel D/Tinker.TinkerManager: onDownloadSuccess.
01-09 15:52:45.987 32096-32096/com.thel D/Tinker.TinkerManager: check if has new patch.
01-09 15:52:46.026 32096-32096/com.thel D/Tinker.TinkerManager: has new patch.
01-09 15:52:46.028 32096-32096/com.thel D/Tinker.TinkerManager: starting patch.
01-09 15:52:46.030 32096-32096/com.thel I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.thel/app_tmpPatch/tmpPatch.apk, file size:4288
01-09 15:52:46.035 32096-32096/com.thel W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
01-09 15:52:46.037 32096-32096/com.thel I/Tinker.TinkerPatchListener: get platform:null
01-09 15:52:46.038 791-4454/? W/ActivityManager: Unable to start service Intent { cmp=com.thel/com.tencent.tinker.lib.service.TinkerPatchService (has extras) } U=0: not found
01-09 15:52:46.436 32096-32107/com.thel E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                      java.lang.Throwable: Explicit termination method 'close' not called
                                                          at dalvik.system.CloseGuard.open(CloseGuard.java:223)
                                                          at java.util.zip.ZipFile.<init>(ZipFile.java:250)
                                                          at java.util.zip.ZipFile.<init>(ZipFile.java:149)
                                                          at java.util.jar.JarFile.<init>(JarFile.java:160)
                                                          at java.util.jar.JarFile.<init>(JarFile.java:124)
                                                          at com.tencent.bugly.beta.tinker.TinkerUtils.readJarEntry(BUGLY:302)
                                                          at com.tencent.bugly.beta.tinker.TinkerManager.checkNewPatch(BUGLY:469)
                                                          at com.tencent.bugly.beta.tinker.TinkerManager.applyPatch(BUGLY:423)
                                                          at com.tencent.bugly.beta.tinker.TinkerManager.onDownloadSuccess(BUGLY:401)
                                                          at com.tencent.bugly.beta.download.a.onCompleted(BUGLY:193)
                                                          at com.tencent.bugly.beta.global.d.run(BUGLY:263)
                                                          at android.os.Handler.handleCallback(Handler.java:789)
                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                          at android.os.Looper.loop(Looper.java:164)
                                                          at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

以下是bugly的信息：
01-09 15:52:45.715 32096-32159/com.thel I/CrashReport: onUpgradeReceived: title: 
                                                       newFeature: 
                                                       publishTime: 0
                                                       publishType: 0
                                                       appBasicInfo: {
                                                       	appId: 49ea8a7c03
                                                       	platformId: 1
                                                       	versionCode: 0
                                                       	versionName: null
                                                       	buildNo: 0
                                                       	iconUrl: null
                                                       	apkId: 0
                                                       	channelId: null
                                                       	md5: 83b25030ab2863855c15dc2d34845aa836e376ae
                                                       	sdkVer: 
                                                       	bundleId: null
                                                       }
                                                       apkBaseInfo: {
                                                       	apkMd5: 83b25030ab2863855c15dc2d34845aa836e376ae
                                                       	apkUrl: https://s.beta.gtimg.com/rdmimg/hot_patch/49ea8a7c03/eb48b896-c2af-45be-a5d1-d93010004de7.zip
                                                       	manifestMd5: 
                                                       	fileSize: 4288
                                                       	signatureMd5: 
                                                       }
                                                       updateStrategy: 0
                                                       popTimes: 0
                                                       popInterval: 0
                                                       diffApkInfo: {
                                                       	null}
                                                       netType: null
                                                       reserved: 1, {
                                                       	(
                                                       		H2
                                                       		1
                                                       	)
                                                       }
                                                       strategyId: b8477ba2-aece-4f08-ada7-dadc50a8c1b4
                                                       status: 1
                                                       updateTime: 1515484287000
                                                       updateType: 3
                                                        [type: 3]

01-09 15:52:45.499 32096-32158/com.thel D/CrashReport: app version is: [4.5.0.40500], [deviceId:867981020688225|null|5417199962e061fb], channel: [null], base tinkerId:[4.5.0.40500_0109-15-43-12], patch tinkerId:[], patch version:[]

**Comment by shwenzhang** [comment]
bugly sdk请联系bugly相关人员

01-09 15:52:46.038 791-4454/? W/ActivityManager: Unable to start service Intent { cmp=com.thel/com.tencent.tinker.lib.service.TinkerPatchService (has extras) } U=0: not found

**Comment by poikl369** [comment]
已经找到原因，AndroidManifest  application 一个属性导致无法合成

**Comment by 1pbSolidDrives** [comment]
请问是哪个属性导致的？ 我的log跟您的一样
