### ISSUE TITLE
插件修复so库，hack方式生效，非hack方式，三种方法都未生效

### ISSUE THREAD

**Issue by wangjkjuststart** [Tencent/tinker#745]
## 异常类型：so使用插件修复，hack方式生效，不使用hack方式，加载so成功但是未生效
未生效方法：TinkerLoadLibrary.loadLibraryFromTinker，TinkerLoadLibrary.loadArmLibrary，TinkerLoadLibrary.loadArmV7Library

手机型号：Nexus 6

手机系统版本：Android 7.1.1

tinker版本：1.9.1

gradle版本：2.3.0

是否使用热更新SDK： 未使用

系统：win7

日志：
01-10 15:45:42.486 2905-2905/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
01-10 15:45:42.489 2905-2905/? D/Tinker.TinkerInternals: same fingerprint:google/shamu/shamu:7.1.1/N6F27M/4299435:user/release-keys
01-10 15:45:42.489 2905-2905/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.lenovo.tinkerdemo/tinker/patch.info , oldVer:9ec049d0780c62ebe84805619da0a627, newVer:9ec049d0780c62ebe84805619da0a627, fingerprint:google/shamu/shamu:7.1.1/N6F27M/4299435:user/release-keys, oatDir:odex
01-10 15:45:42.493 2905-2905/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.lenovo.tinkerdemo count:1
01-10 15:45:42.501 2905-2905/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lenovo.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lenovo.tinkerdemo-1/lib/arm, /system/fake-libs, /data/app/com.lenovo.tinkerdemo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]]
01-10 15:45:42.501 2905-2905/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.lenovo.tinkerdemo/tinker/patch-9ec049d0/dex/tinker_classN.apk md5, use time: 0
01-10 15:45:42.501 2905-2905/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.lenovo.tinkerdemo/tinker/patch-9ec049d0/odex, dex size:1
01-10 15:45:42.512 2905-2905/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.lenovo.tinkerdemo/tinker/patch-9ec049d0/dex/tinker_classN.apk", zip file "/data/app/com.lenovo.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lenovo.tinkerdemo-1/lib/arm, /system/fake-libs, /data/app/com.lenovo.tinkerdemo-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]], dex size:1
01-10 15:45:42.512 2905-2905/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
01-10 15:45:42.515 2905-2905/? W/Tinker.ResourcePatcher: try to clear typedArray cache!
01-10 15:45:42.516 2905-2905/? I/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
01-10 15:45:42.516 2905-2905/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/user/0/com.lenovo.tinkerdemo/tinker/patch-9ec049d0/res/resources.apk, use time: 4
01-10 15:45:42.516 2905-2905/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
01-10 15:45:42.516 2905-2905/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
01-10 15:45:42.520 2905-2905/? D/Tinker.DefaultAppLike: onBaseContextAttached:
01-10 15:45:42.529 2905-2905/? I/Tinker.SamplePatchListener: application maxMemory:256
01-10 15:45:42.534 2905-2905/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.lenovo.tinkerdemo/tinker
01-10 15:45:42.543 2905-2905/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
01-10 15:45:42.546 2905-2905/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.lenovo.tinkerdemo, main process:true, systemOTA:false, fingerPrint:google/shamu/shamu:7.1.1/N6F27M/4299435:user/release-keys, oatDir:odex, useInterpretMode:false
01-10 15:45:42.546 2905-2905/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:9ec049d0780c62ebe84805619da0a627, current:9ec049d0780c62ebe84805619da0a627
01-10 15:45:42.546 2905-2905/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
01-10 15:45:42.546 2905-2905/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchVersionChanged: patch version change from  to 9ec049d0780c62ebe84805619da0a627
01-10 15:45:42.546 2905-2905/? I/Tinker.DefaultLoadReporter: onLoadPatchVersionChanged, try kill all other process
01-10 15:45:42.548 2905-2905/? I/Tinker.UpgradePatchRetry: onPatchResetMaxCheck, reset max check to 1
01-10 15:45:42.549 2905-2905/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.lenovo.tinkerdemo/tinker, code: 0, cost: 71ms
01-10 15:45:42.554 2905-2905/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
01-10 15:45:42.554 2905-2905/? D/Tinker.DefaultAppLike: onCreate
01-10 15:45:42.869 2905-2905/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.lenovo.tinkerdemo/tinker_temp/temp.apk is not exist, just return
01-10 15:45:59.783 2905-2905/? I/Tinker.LoadLibrary: loadLibraryFromTinker success:/data/user/0/com.lenovo.tinkerdemo/tinker/patch-9ec049d0/lib/lib/armeabi-v7a/libnative-lib.so

**Comment by shwenzhang** [comment]
非hack方式的几个只是实例，需要根据你们自己的abi做处理
