### ISSUE TITLE
找不到自定义属性

### ISSUE THREAD

**Issue by Dpuntu** [Tencent/tinker#747]
异常类型：assembleDebug编译失败

手机型号：未运行

手机系统版本：未运行

tinker版本：1.9.1

gradle版本：3.0.0

是否使用热更新SDK：Bugly SDK

系统：Mac

日志：
Information:Gradle tasks [assembleDebug]
Error:In <declare-styleable> KVItemView, unable to find attribute key_text_color
Error:In <declare-styleable> KVItemView, unable to find attribute value_text_color
Error:java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing process /Users/dpuntu/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/dpuntu/Library/Android/sdk/platforms/android-25/android.jar -M /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/res/merged/debug -m -J /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/generated/source/r/debug -F /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/res/debug/resources-debug.ap_ --custom-package com.fmx.todo.tinker -0 apk --output-text-symbols /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/symbols/debug --no-version-vectors}
Error:com.android.ide.common.process.ProcessException: Error while executing process /Users/dpuntu/Library/Android/sdk/build-tools/26.0.2/aapt with arguments {package -f --no-crunch -I /Users/dpuntu/Library/Android/sdk/platforms/android-25/android.jar -M /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/manifests/full/debug/AndroidManifest.xml -S /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/res/merged/debug -m -J /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/generated/source/r/debug -F /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/res/debug/resources-debug.ap_ --custom-package com.fmx.todo.tinker -0 apk --output-text-symbols /Users/dpuntu/AndroidStudioProjects/tinker/tinker/app/build/intermediates/symbols/debug --no-version-vectors}
Error:org.gradle.process.internal.ExecException: Process 'command '/Users/dpuntu/Library/Android/sdk/build-tools/26.0.2/aapt'' finished with non-zero exit value 1
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt

**Comment by Dpuntu** [comment]
已发现问题，原因是在attrs.xml中，部分属性未设置format，不过有疑问，为什么tinker强制要求每个属性都定义好format呢？

**Comment by shwenzhang** [comment]
从错误日志上面看，并没有看出是tinker有这个强制的要求
