### ISSUE TITLE
合成成功后重启的必要性

### ISSUE THREAD

**Issue by dotcink** [Tencent/tinker#748]
请问合成成功后是否一定要重启 app？（重启可能对保活有影响 v_v）
重启 app 是为了防止多个进程间代码不同步吗？

**Comment by icemanstudy** [comment]
重启是为了重新load dex.不然你合并的dex是没有用上的.

**Comment by dotcink** [comment]
@icemanstudy 重启才能生效，这个明白。
我的疑问是，如果一直不重启，是不是会出问题？
比如，主进程不重启（使用老的 dex），后来启动了个其他进程（使用新的 dex），两者如果有通信，可能就会出问题。应该是吧？
另外，不知道还会不会造成其他问题？

ps. 主要是为了万恶的保活 😢

**Comment by tomystang** [comment]
一直不重启的话，确实会出现一部分进程重启了，另一部分进程可能还没重启，然后两边一有通信的话就有可能crash。

**Comment by icemanstudy** [comment]
我觉得这种情况主要取决于,类加载器在不同进程之间是否是共享的?
若共享,那你即使新开进程,加载的还是旧的类.
否则就会出现两边不一致.
我没有研究过这个问题,希望有了解的可以说一下.

**Comment by dotcink** [comment]
@tomystang Thanks.

@icemanstudy 进程间内存不共享，ClassLoader 也不会共享，在 24 以上打补丁还会创建新的 ClassLoader。
