### ISSUE TITLE
Tinker loader必须放在主dex的原因？

### ISSUE THREAD

**Issue by shizhy1986** [Tencent/tinker#75]
仅仅是因为dalvik上如果multidex的话调用不到Tinker loader？  如果仅仅是这个原因，在调用loader之前就做Multidex.install() 是否ok

**Comment by shwenzhang** [comment]
mutidex install的调用肯定是在loader类之后的

**Comment by shizhy1986** [comment]
@shwenzhang  如果我自己拷贝你TinkerApplication里的实现，在loader之前multidex install , 有问题么，我想知道这个放在主dex是不是就是dalvik上multidex会导致找不到loader类。 art上如果不在主dex有问题么

**Comment by shwenzhang** [comment]
当然有问题啊，这样不行，任何在之前加载的类都不能修改。还是先了解一下类加载相关的知识

**Comment by shizhy1986** [comment]
@shwenzhang 不是很理解，就是Multidex install和 loader顺序换了下，无非Multidex的类不能修改了吧？其他哪些类也会不能修改？Multidex install的classes2.dex里面的类难道也不能修改了？

**Comment by shwenzhang** [comment]
的确如此，但是为了保证方案的隔离性，这样的设计不好。我们的设计应该是除了loader类，其他都可以修改

**Comment by shwenzhang** [comment]
事实上，如果你非常了解tinker的架构，是可以这样改造的。但是这样带来的好处其实没多少
