### ISSUE TITLE
新版本不提供tinker-patch-cli.jar工具了？

### ISSUE THREAD

**Issue by zhaoshuiruoli** [Tencent/tinker#751]
1.9.1中没有找到这个工具，之前都是在tinker-build下tinker-patch-cli的tool_output路径下

**Comment by tomystang** [comment]
运行一下buildTinkerSDK这个gradle task就可以了

**Comment by BiteFoo** [comment]
记得在之前的版本是直接在源码目录下执行gradle makeJar就能输出jar了，现在的版本不一样了。请问，在tinker的源码目录下运行 gradle buildTinkerSDK 吗？

**Comment by BiteFoo** [comment]
在源码目录下执行了gradle builTinkerSDK命令，出现异常，如下：

D:\Android\tinker>gradle  buildTinkerSDK

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Android\tinker\tinker-android\tinker-android-lib\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':tinker-android:tinker-android-lib'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 4.1. Current version is 3.4.1. If using the gradle wrapper, try editing the distributionUrl in D:\Android\tinker\gradle\wrapper\gradle-wrapper.properties to gradle-4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.429 secs
-------------------------------------------------------------
我的tinker-patch-cli下的gradle.properties :
#Mon Jan 22 11:39:15 CST 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

请问，这里应该怎么打这个tinker-patch-cli.jar？谢谢

**Comment by tomystang** [comment]
额，你改错地方了……
应该把这个位置：D:\Android\tinker\gradle\wrapper\gradle-wrapper.properties 里面的distributionUrl改成：
https://services.gradle.org/distributions/gradle-4.1-all.zip
然后再执行那个task，应该就ok了。

**Comment by shwenzhang** [comment]
自己编译即可

**Comment by zhaoshuiruoli** [comment]
thanks
