### ISSUE TITLE
补丁如何安全下架

### ISSUE THREAD

**Issue by pmathticol** [Tencent/tinker#754]
补丁如何安全下架呢。看到TinkerInstaller里面有个cleanPatch方法，但是这个方法有个注释是说
`it is not safety to clean patch when tinker is loaded, you should kill all your process after clean!`
下架补丁的时候，杀进程这不是一个很好的体验，
我本来想在load之前去下架补丁，但是看到tinkerInstaller里必须需要sInstanlled为true才可以。所以只能在install步骤之后才能下架，但是这个时候调用cleanPatch会应该会有classNoNotFound Error吧。
请问有更好更加安全的方式来下架补丁么？

**Comment by icemanstudy** [comment]
理论上是可以在install之前根据条件来判断是否要install.但是你根据什么条件来决定下架呢?
只能先加载了再说.

**Comment by shwenzhang** [comment]
先置一个flag，下一次重新启动的时候再去清除补丁即可
