### ISSUE TITLE
请问eclipse的项目可以用tinker吗？

### ISSUE THREAD

**Issue by 1pbSolidDrives** [Tencent/tinker#755]
我们是一个老项目，无法一直到androidStudio上，请问tinker可以用在eclipse项目中吗？

**Comment by icemanstudy** [comment]
要支持gradle就行.
话说我真的想不出来还有只能用eclipse不能用AS的项目

**Comment by 1pbSolidDrives** [comment]
哦哦 这样啊 了解了

**Comment by shwenzhang** [comment]
或者使用命令行版本，但是需要自己做一些工作，具体查看wiki
