### ISSUE TITLE
tinker打包混淆的时候会把org.apache.http混淆掉，完全keep不住

### ISSUE THREAD

**Issue by xingkonghdc** [Tencent/tinker#759]
proguard-rules.pro文件中已经加入
-keep class org.apache.http.**{*;}
但是使用开启tinkerEnabled = true，打包时候org.apache.http依然会被混淆，导致运行报错
完全keep不住，关闭tinkerEnabled打包正常

**Comment by shwenzhang** [comment]
tinker keep的规则都是额外添加进去的，可以查看编译输出的文件，看看最后keep的规则是怎么样的

**Comment by xingkonghdc** [comment]
问题已经解决了，就是混淆规则会使用基准包里面的mapping文件
