### ISSUE TITLE
添加自定义字体资源文件，打补丁包失败

### ISSUE THREAD

**Issue by LazyDemo** [Tencent/tinker#762]
Error:Execution failed for task ':app:tinkerProcessReleaseResourceId'.
> com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: /Users/apple/AndroidStudioProjects/Jian/app/build/intermediates/res/merged/release/font is not a valid resource sub-directory.

打补丁包的时候提示这个信息，工程里包含了自定义字体的资源文件夹
![image](https://user-images.githubusercontent.com/13451082/35558659-9e1541f6-05e3-11e8-8840-6fbd9422776b.png)

Tinker版本
1.9.1

gradle版本
3.0.1

系统
Mac

**Comment by sher-loki** [comment]
同问

**Comment by shwenzhang** [comment]
麻烦--stacktrace，把详细的错误日志打出来

**Comment by xfhy** [comment]
我也遇到同样的问题...

**Comment by tokiii** [comment]
这个bug 是  RType枚举 少了一个FONT 类型，官方API里面R也没添加这个类型，但是在Api 27或之后支持res中添加font文件夹并添加自定义字体，所以在打补丁包时检查发现这个不合法导致的这个问题出现。
`// Taken from http://developer.android.com/reference/android/R.html
    // TRANSITION for api level 19
    public enum RType {
        ANIM, ANIMATOR, ARRAY, ATTR, BOOL, COLOR, DIMEN, DRAWABLE, FRACTION, ID, INTEGER, INTERPOLATOR, LAYOUT, MENU, MIPMAP, PLURALS, RAW, STRING, STYLE, STYLEABLE, TRANSITION, XML;

        @Override
        public String toString() {
            return super.toString().toLowerCase();
        }
    }`

**Comment by iykzhang** [comment]
问题是关闭状态，是修复了吗？

**Comment by tokiii** [comment]
@iykzhang 没有修复，你现在看github上代码还是缺少了这个font类型，官方不管了，估计是离职了或者是关闭的issue不影响kpi之类吧。

**Comment by tombcato** [comment]
老哥 我也卡这里了 tinker什么时候更新下版本
