### ISSUE TITLE
一个APP依赖的sdk可以对其做单独的热更吗？

### ISSUE THREAD

**Issue by xxdongs** [Tencent/tinker#768]
公司是做了一个手游SDK，不同游戏可以接入我们的SDK，在我们的渠道上运营。现在想在这个SDK上做热更，SDK有bug的时候，所有接入的游戏都能得到更新，请问用tinker可行吗。

我尝试用demo接入SDK，并得到一个差分包，在接入我们SDK的游戏区做热更，结果热更失败。

异常类型：app运行时异常/编译异常
手机型号：天天模拟器
手机系统版本：4.4
tinker版本：1.9.1
gradle版本：3.0.1
是否使用热更新SDK： 否
系统：Win7

堆栈/日志：
02-07 17:38:24.968 18850-18863/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
02-07 17:38:24.968 18850-18863/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/download/patch_signed_7zip.apk to /data/data/com.joygames.zzqy.alpha/tinker_temp/temp.apk
02-07 17:38:24.968 18850-18863/? I/Tinker.TinkerPatchService: try to increase patch process priority
02-07 17:38:24.976 394-2604/system_process W/ActivityManager: Unable to start service Intent { cmp=com.joygames.zzqy.alpha/com.tencent.tinker.lib.service.TinkerPatchService$InnerService } U=0: not found
02-07 17:38:24.996 18850-18863/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:01e62f853eded104fc5edc9c19c556ef
02-07 17:38:24.996 18850-18863/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/com.joygames.zzqy.alpha/tinker/patch.info: open failed: ENOENT (No such file or directory)
02-07 17:38:24.996 18850-18863/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/com.joygames.zzqy.alpha/tinker/patch.info: open failed: ENOENT (No such file or directory)
02-07 17:38:24.996 18850-18863/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85
02-07 17:38:24.996 18850-18863/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/download/patch_signed_7zip.apk size: 3837, dest file: /data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85/patch-01e62f85.apk size:3837
02-07 17:38:25.112 18850-18863/? E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 938964837, got crc: 2261628295
02-07 17:38:25.112 18850-18863/? I/Tinker.DefaultPatchReporter: patchReporter onPatchTypeExtractFail: file extract fail type: dex, path: /data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85/patch-01e62f85.apk, extractTo: /data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85/dex/classes.dex.jar, filename: classes.dex
02-07 17:38:25.112 18850-18863/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85/patch-01e62f85.apk
02-07 17:38:25.112 18850-18863/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85/dex
02-07 17:38:25.112 18850-18863/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.joygames.zzqy.alpha/tinker/patch-01e62f85
02-07 17:38:25.112 18850-18863/? W/Tinker.DexDiffPatchInternal: patch recover, extractDiffInternals fail
02-07 17:38:25.112 18850-18863/? I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:115
02-07 17:38:25.112 18850-18863/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
02-07 17:38:25.112 18850-18863/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/download/patch_signed_7zip.apk, success: false, cost: 143
02-07 17:38:25.112 18850-18863/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.joygames.zzqy.alpha/tinker_temp/temp.apk
02-07 18:02:01.164 18779-18779/com.joygames.zzqy.alpha D/Tinker.DefaultAppLike: onTrimMemory level:20

**Comment by shwenzhang** [comment]
tinker是针对主app的，所以作为sdk是不可行的。sdk可以自己做热更新，例如类似插件化的机制
