### ISSUE TITLE
同步错误

### ISSUE THREAD

**Issue by maxinlei** [Tencent/tinker#769]
Error:Execution failed for task ':app:tinkerProcessDebugManifest'. tinkerId is not set!!!
项目里添加了
 classpath 'com.android.tools.build:gradle:3.0.1'
classpath ('com.tencent.tinker:tinker-patch-gradle-plugin:1.9.1')
app里添加了
apply plugin: 'com.tencent.tinker.patch'

 //可选，用于生成application类
    provided('com.tencent.tinker:tinker-android-anno:1.9.1')
    //tinker的核心库
    compile('com.tencent.tinker:tinker-android-lib:1.9.1')

**Comment by YummyLau** [comment]
tinkerId 没有设置。项目里面是gitSha()方法提供。检查下是否有git仓库或者是否使用git不就ok了吗
