### ISSUE TITLE
编译patch包出错

### ISSUE THREAD

**Issue by maoxiandemeng** [Tencent/tinker#770]
Error:Execution failed for task ':app:tinkerPatchDebug'.
> Could not resolve all dependencies for configuration ':app:sevenZipToolsLocator'.
   > Could not resolve com.tencent.mm:SevenZip:1.1.10.
     Required by:
         android:app:unspecified
      > No cached version of com.tencent.mm:SevenZip:1.1.10 available for offline mode.
      > No cached version of com.tencent.mm:SevenZip:1.1.10 available for offline mode.
      > No cached version of com.tencent.mm:SevenZip:1.1.10 available for offline mode.
      > No cached version of com.tencent.mm:SevenZip:1.1.10 available for offline mode.

**Comment by shwenzhang** [comment]
No cached version of com.tencent.mm:SevenZip:1.1.10 available for offline mode.

offline mode
