### ISSUE TITLE
华为手机资源找不到，报空指针问题

### ISSUE THREAD

**Issue by pmathticol** [Tencent/tinker#776]
异常类型：app运行时异常

手机型号：华为主流机型

手机系统版本：android 6.0以上

tinker版本：如:1.8.1

gradle版本：如:2.3.2

是否使用热更新SDK： 直接接入tinker sdk

堆栈/日志：
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
java.lang.RuntimeException:Unable to start activity 

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
......
java.lang.NullPointerException:Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
android.view.Window.getDefaultFeatures(Window.java:1343)
android.view.Window.<init>(Window.java:481)
com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:331)
com.android.internal.policy.HwPhoneWindow.<init>(HwPhoneWindow.java:77)
com.android.internal.policy.HwPolicyFactoryImpl.getHwPhoneWindow(HwPolicyFactoryImpl.java:40)
com.android.internal.policy.HwPolicyFactory.getHwPhoneWindow(HwPolicyFactory.java:36)
android.app.Activity.attach(Activity.java:6312)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2410)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
android.app.ActivityThread.access$900(ActivityThread.java:168)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:150)
android.app.ActivityThread.main(ActivityThread.java:5659)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by pmathticol** [comment]
2-28 12:10:22.142 22733 22875 I MutiServerManager: getNext get http server,sIP = wns.kg.qq.com,sPort = 14000,pIP = null,pPort = 0,protocol = http,type = dns
02-28 12:10:22.152 22733 24278 I Session : [Session No:5] connect sIP = wns.kg.qq.com,sPort = 8080,pIP = null,pPort = 0,protocol = http,type = dns
02-28 12:10:22.153 22562 22562 W asset   : Asset path /data/user/0/com.tencent.karaoke/tinker/patch-6246603d/res/resources.apk is neither a directory nor file (type=1).
02-28 12:10:22.154 22733 24252 I Session : [Session No:3] connect sIP = 117.135.169.112,sPort = 80,pIP = null,pPort = 0,protocol = tcp,type = bak
02-28 12:10:22.154 22562 22562 W asset   : Asset path /data/user/0/com.tencent.karaoke/tinker/patch-6246603d/res/resources.apk is neither a directory nor file (type=1).
02-28 12:10:22.157 22733 24202 I Session : [Session No:2] connect sIP = 117.135.169.112,sPort = 443,pIP = null,pPort = 0,protocol = tcp,type = bak
02-28 12:10:22.159 22733 24253 I Session : [Session No:4] connect sIP = wns.kg.qq.com,sPort = 14000,pIP = null,pPort = 0,protocol = http,type = dns
02-28 12:10:22.159 22562 22562 E CrashHandler: In thread: Thread[main,5,main]
02-28 12:10:22.159 22562 22562 E CrashHandler: UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.karaoke/com.tencent.karaoke.module.splash.ui.SplashBaseActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.ActivityThread.access$900(ActivityThread.java:165)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.os.Looper.loop(Looper.java:150)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.ActivityThread.main(ActivityThread.java:5621)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at java.lang.reflect.Method.invoke(Native Method)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
02-28 12:10:22.159 22562 22562 E CrashHandler: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.view.Window.getDefaultFeatures(Window.java:1343)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.view.Window.<init>(Window.java:481)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:323)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at com.android.internal.policy.HwPhoneWindow.<init>(HwPhoneWindow.java:60)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at com.android.internal.policy.HwPolicyFactoryImpl.getHwPhoneWindow(HwPolicyFactoryImpl.java:40)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at com.android.internal.policy.HwPolicyFactory.getHwPhoneWindow(HwPolicyFactory.java:39)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.Activity.attach(Activity.java:6307)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
02-28 12:10:22.159 22562 22562 E CrashHandler: 	... 9 more
02-28 12:10:22.159 22562 22562 I crash_recorder: recordTbsCrash:
02-28 12:10:22.159 22562 22562 I crash_recorder:  {java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.karaoke/com.tencent.karaoke.module.splash.ui.SplashBaseActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.res.Resources.getBoolean(int)' on a null object reference
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2451)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.app.ActivityThread.access$900(ActivityThread.java:165)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.os.Looper.loop(Looper.java:150)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at android.app.ActivityThread.main(ActivityThread.java:5621)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at java.lang.reflect.Method.invoke(Native Method)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
02-28 12:10:22.159 22562 22562 I crash_recorder: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
02-28 12:10:22.159 22562 22562 I crash_recorder: Caused by: java.lang.NullPointerException: Attempt t
02-28 12:10:22.159 22562 22562 I crash_recorder: isInTbsContext, webviewType: unknown, isLoading: 0
02-28 12:10:22.171 22562 22562 I System.out: [logcat, -d, -v, threadtime]
02-28 12:10:22.171 22562 22562 I System.out: null
02-28 12:10:22.171 22562 22562 I System.out: null
02-28 12:10:22.171 22562 22562 I System.out: Calling by::className:com.tencent.bugly.proguard.ag  MethodName:a
02-28 12:10:22.206 22733 24278 W Session : [Session No:5] connect result:sIP = wns.kg.qq.com,sPort = 8080,pIP = null,pPort = 0,protocol = http,type = dns, signalStrength = 4,timecost = 54ms,errorCode = 544
02-28 12:10:22.208 22733 24253 W Session : [Session No:4] connect result:sIP = wns.kg.qq.com,sPort = 14000,pIP = null,pPort = 0,protocol = http,type = dns, signalStrength = 4,timecost = 49ms,errorCode = 544

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。

**Comment by unciv6** [comment]
同问
