### ISSUE TITLE
tinker 可以使用 多module 的方式吗？

### ISSUE THREAD

**Issue by maxinlei** [Tencent/tinker#777]
application 我怎么才能集成呢？

**Comment by maxinlei** [comment]
麻烦问一下 有没有 demo 可以提供呢？

**Comment by YummyLau** [comment]
暂时是线上的项目，不方便给出，下周我可以给个demo，或者你在项目中使用，有错误贴出来看下

**Comment by maxinlei** [comment]
我的问题 在于 多个module application 的用法  平常多module 是有个 lib（module）app（module）的application继承lib的application这样整个项目 都用一个 application 现在tinker 是使用 自动生成的 而且 继承的applicationLike 还是 抽象类 这块的用法不是很清楚 而且是否tinker是否可以修复每一个 module呢？

**Comment by YummyLau** [comment]
App的application是不建议集成lib的application。模块化的每个lib都是独立的模块，可独立调试，实际上可以不需要继承同一个。
1. 针对“现在tinker 是使用 自动生成的 而且 继承的applicationLike 还是 抽象类 这块的用法不是很清楚”，wiki其实已经讲得听清楚的，如果实在不懂，下官方的smaple照搬就好。
模块化的设计你可以参考 https://github.com/YummyLau/AndroidModularArchiteture 和我线上的设计基本一直。

2. 针对“tinker是否可以修复每一个 module呢”。从两个方面理解你这个问题。
第一个，如果lib独立运行成application，而对应的application集成tinker是肯定可以的，类似sample
第二个，如果你的app引用多个module（lib），实际上打包的时候这些都只是引用而已。如果线上包出现问题，基于线上版本的svn或者git版本号上拉一个分支作为临时多module项目工程，直接修改对应module的异常代码，再打包生成补丁包，这也是修复module内的代码，只是他是个lib而已。

**Comment by WangChangQin** [comment]
@YummyLau   我也想看看你的demo,方便给个地址吗？我们的项目也是有很多module,整个项目用一个 application,不懂怎么集成

**Comment by 529523346** [comment]
@maxinlei 你的问题解决了么
