### ISSUE TITLE
关于连续修复代码生成补丁问题

### ISSUE THREAD

**Issue by yanhaogoogle** [Tencent/tinker#78]
有这样一个场景：
第一次修复了代码生成了补丁正常这个时候bakApk产生了一个apk文件(现在bakAPk文件下面有2个apk文件：第一个是正常编译的apk，第二个是修复补丁后产生的apk文件)。但是接下来这份代码又要再次进行代码修复,但是这个tinkerOldApkPath这个路劲是写正常编译的那个apk文件还是写修复补丁产生的那个apk文件呢？

**Comment by l114624915** [comment]
修复只能1对1

**Comment by yanhaogoogle** [comment]
@l114624915 难道没办法做到对一套代码或者一个版本下面的代码连续修复吗。。。。

**Comment by shwenzhang** [comment]
可以连续修复，但是针对的都是已经发布的apk，然后把它定为oldapk

**Comment by yanhaogoogle** [comment]
@shwenzhang 如果可以连续修复，那么我把我第一次编译出来的apk当作是一个发布版本，那么我第一次修复代码成功后有了一个新的apk，那么我在这套代码的基础上进行第二次修复那oldapk要设置为那个apk呢是第一次编译的还是第一次修复的？感觉不是很明白啊

**Comment by shwenzhang** [comment]
oldapk肯定一直都是用户手机上面的那一个！

**Comment by yanhaogoogle** [comment]
@shwenzhang 我已经测试成功可以连续hotfix了，昨天不知道出了什么问题导致连续修复不成功
