### ISSUE TITLE
Android O上Start后台Service权限问题

### ISSUE THREAD

**Issue by guoguo338** [Tencent/tinker#781]
Android O限制了不能在用户没grant权限的条件下启动后台Service，请问，下面的代码是不是需要有所改动？启用JobScheduler？

https://developer.android.com/about/versions/oreo/background.html

TinkerPatchService.java:

    public static void runPatchService(Context context, String path) {
        try {
            Intent intent = new Intent(context, TinkerPatchService.class);
            intent.putExtra(PATCH_PATH_EXTRA, path);
            intent.putExtra(RESULT_CLASS_EXTRA, resultServiceClass.getName());
            context.startService(intent);
        } catch (Throwable throwable) {
            TinkerLog.e(TAG, "start patch service fail, exception:" + throwable);
        }
    }

**Comment by tomystang** [comment]
嗯嗯，是的。已在1.9.5版本上做了修改。
