### ISSUE TITLE
tinker补丁包无法下载

### ISSUE THREAD

**Issue by 1pbSolidDrives** [Tencent/tinker#782]
异常类型：app运行时异常

手机型号：华为mate8

手机系统版本：Android 7.0 

tinker版本：1.9.2

gradle版本：4.1

是否使用热更新SDK： TinkerPatch SDK

系统：Mac

堆栈/日志：

03-06 11:38:45.495 7729-7729/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:38:45.496 7729-7729/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:38:45.496 7729-7729/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:38:45.501 7729-7729/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:38:45.503 7729-7729/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:38:45.504 7729-7729/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:38:45.506 7729-7729/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:38:45.515 7729-7729/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:38:45.518 7729-7729/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:38:45.519 7729-7729/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:38:45.519 7729-7729/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh, main process:true, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:38:45.519 7729-7729/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:38:45.519 7729-7729/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 4ms
03-06 11:38:45.519 7729-7729/? W/Tinker.Tinker: tinker load fail!
03-06 11:38:45.519 7729-7729/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:38:45.695 7729-7729/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:38:45.851 7729-7790/? I/ANDROID_TAG: Q_M tinker 4.7.5-1``````````````
03-06 11:38:45.851 7729-7790/? I/ANDROID_TAG: Q_M tinker  assetsPath = nullptr!!!!!
03-06 11:38:46.145 7885-7885/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:38:46.146 7885-7885/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:38:46.147 7885-7885/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:38:46.153 7885-7885/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:38:46.155 7885-7885/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:38:46.157 7885-7885/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:38:46.158 7885-7885/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:38:46.161 7885-7885/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:38:46.163 7885-7885/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:38:46.164 7885-7885/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:38:46.165 7885-7885/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh:QLocal, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:38:46.165 7885-7885/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:38:46.165 7885-7885/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 2ms
03-06 11:38:46.165 7885-7885/? W/Tinker.Tinker: tinker load fail!
03-06 11:38:46.165 7885-7885/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:38:46.193 7885-7885/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:38:46.200 7885-7885/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-06 11:38:46.271 7934-7934/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:38:46.273 7934-7934/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:38:46.273 7934-7934/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:38:46.276 7934-7934/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:38:46.279 7934-7934/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:38:46.281 7934-7934/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:38:46.282 7934-7934/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:38:46.285 7934-7934/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:38:46.289 7934-7934/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:38:46.290 7934-7934/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:38:46.290 7934-7934/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh:QRemote, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:38:46.290 7934-7934/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:38:46.290 7934-7934/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 7ms
03-06 11:38:46.290 7934-7934/? W/Tinker.Tinker: tinker load fail!
03-06 11:38:46.290 7934-7934/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:38:46.326 7934-7934/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:38:46.375 7934-7934/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-06 11:38:46.746 7729-7729/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
03-06 11:38:46.754 7729-7729/? I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/c/4954d71eb59c298e?d=17af9b25-238f-40be-b1d1-8c22f57bc393&v=1520307526753, method:GET, body:null
03-06 11:38:46.756 7729-7729/? W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
03-06 11:38:46.756 7729-7729/? I/Tinker.ServerClient: tinker sync should wait interval 6375s
03-06 11:38:46.879 7729-8112/? I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
03-06 11:39:10.211 8696-8696/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:39:10.212 8696-8696/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:39:10.213 8696-8696/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:39:10.217 8696-8696/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:39:10.219 8696-8696/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:39:10.220 8696-8696/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:39:10.221 8696-8696/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:39:10.223 8696-8696/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:39:10.226 8696-8696/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:39:10.227 8696-8696/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:39:10.227 8696-8696/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh, main process:true, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:39:10.227 8696-8696/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:39:10.227 8696-8696/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 3ms
03-06 11:39:10.227 8696-8696/? W/Tinker.Tinker: tinker load fail!
03-06 11:39:10.227 8696-8696/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:39:10.362 8696-8696/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:39:10.469 8696-8717/? I/ANDROID_TAG: Q_M tinker 4.7.5-1``````````````
03-06 11:39:10.469 8696-8717/? I/ANDROID_TAG: Q_M tinker  assetsPath = nullptr!!!!!
03-06 11:39:10.673 8757-8757/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:39:10.675 8757-8757/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:39:10.675 8757-8757/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:39:10.678 8757-8757/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:39:10.686 8757-8757/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:39:10.687 8757-8757/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:39:10.688 8757-8757/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:39:10.690 8757-8757/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:39:10.693 8757-8757/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:39:10.693 8757-8757/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:39:10.693 8757-8757/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh:QLocal, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:39:10.693 8757-8757/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:39:10.693 8757-8757/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 2ms
03-06 11:39:10.694 8757-8757/? W/Tinker.Tinker: tinker load fail!
03-06 11:39:10.694 8757-8757/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:39:10.723 8757-8757/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:39:10.725 8757-8757/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-06 11:39:10.775 8789-8789/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:39:10.776 8789-8789/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:39:10.776 8789-8789/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:39:10.779 8789-8789/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:39:10.782 8789-8789/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:39:10.783 8789-8789/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:39:10.783 8789-8789/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:39:10.785 8789-8789/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:39:10.788 8789-8789/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:39:10.788 8789-8789/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:39:10.788 8789-8789/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh:QRemote, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:39:10.788 8789-8789/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:39:10.788 8789-8789/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 3ms
03-06 11:39:10.788 8789-8789/? W/Tinker.Tinker: tinker load fail!
03-06 11:39:10.788 8789-8789/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:39:10.837 8789-8789/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:39:10.889 8789-8789/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-06 11:39:11.224 8696-8696/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
03-06 11:39:11.236 8696-8696/? I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/c/4954d71eb59c298e?d=17af9b25-238f-40be-b1d1-8c22f57bc393&v=1520307551233, method:GET, body:null
03-06 11:39:11.238 8696-8696/? W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
03-06 11:39:11.238 8696-8696/? I/Tinker.ServerClient: tinker sync should wait interval 6350s
03-06 11:39:11.384 8696-8840/? I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
03-06 11:45:24.810 9467-9467/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:45:24.812 9467-9467/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:45:24.812 9467-9467/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:45:24.819 9467-9467/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:45:24.821 9467-9467/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:45:24.822 9467-9467/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:45:24.824 9467-9467/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:45:24.826 9467-9467/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:45:24.829 9467-9467/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:45:24.830 9467-9467/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:45:24.830 9467-9467/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh, main process:true, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:45:24.830 9467-9467/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:45:24.830 9467-9467/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 4ms
03-06 11:45:24.830 9467-9467/? W/Tinker.Tinker: tinker load fail!
03-06 11:45:24.830 9467-9467/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:45:24.992 9467-9467/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:45:25.109 9467-9513/? I/ANDROID_TAG: Q_M tinker 4.7.5-1``````````````
03-06 11:45:25.109 9467-9513/? I/ANDROID_TAG: Q_M tinker  assetsPath = nullptr!!!!!
03-06 11:45:25.365 9580-9580/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:45:25.371 9580-9580/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:45:25.371 9580-9580/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:45:25.375 9580-9580/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:45:25.377 9580-9580/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:45:25.377 9580-9580/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:45:25.378 9580-9580/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:45:25.380 9580-9580/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:45:25.384 9580-9580/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:45:25.385 9580-9580/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:45:25.385 9580-9580/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh:QLocal, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:45:25.385 9580-9580/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:45:25.385 9580-9580/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 3ms
03-06 11:45:25.385 9580-9580/? W/Tinker.Tinker: tinker load fail!
03-06 11:45:25.385 9580-9580/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:45:25.414 9580-9580/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:45:25.455 9580-9580/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
                                                           
                                                           [ 03-06 11:45:25.455   414:  414 W/         ]
                                                           debuggerd: resuming target 9615
03-06 11:45:25.457 9624-9624/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:45:25.458 9624-9624/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.zhancheng.TinkerApplication
03-06 11:45:25.458 9624-9624/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
03-06 11:45:25.463 9624-9624/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
03-06 11:45:25.486 9624-9624/? I/Tinker.ServerUtils: with app key from manifest appKey:4954d71eb59c298e
03-06 11:45:25.488 9624-9624/? I/Tinker.ServerUtils: with app version from manifest appVersion:4.8.1
03-06 11:45:25.489 9624-9624/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.zhancheng.android.xx.qh/tinker_server/4954d71eb59c298e_version.info, appVersion: 4.8.1, uuid:17af9b25-238f-40be-b1d1-8c22f57bc393, abi:armeabi, patchVersion:0, patchMd5:, grayValue:5, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
03-06 11:45:25.492 9624-9624/? I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 4.8.1, appKey: 4954d71eb59c298e
03-06 11:45:25.496 9624-9624/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.zhancheng.android.xx.qh/tinker
03-06 11:45:25.497 9624-9624/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.2
03-06 11:45:25.497 9624-9624/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.zhancheng.android.xx.qh:QRemote, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B592:user/release-keys, oatDir:null, useInterpretMode:false
03-06 11:45:25.497 9624-9624/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-06 11:45:25.497 9624-9624/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.zhancheng.android.xx.qh/tinker, code: -2, cost: 4ms
03-06 11:45:25.497 9624-9624/? W/Tinker.Tinker: tinker load fail!
03-06 11:45:25.497 9624-9624/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.2
03-06 11:45:25.521 9624-9624/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
03-06 11:45:25.601 9624-9624/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-06 11:45:25.933 9467-9467/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
03-06 11:45:25.946 9467-9467/? I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/c/4954d71eb59c298e?d=17af9b25-238f-40be-b1d1-8c22f57bc393&v=1520307925944, method:GET, body:null
03-06 11:45:25.947 9467-9467/? W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
03-06 11:45:25.947 9467-9467/? I/Tinker.ServerClient: tinker sync should wait interval 5975s
03-06 11:45:26.120 9467-9734/? I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found

备注：对比正常下载的情况下的日志，本次日志中缺少Tinker.DefaultAppLike相关日志，请问Tinker.DefaultAppLike是干什么用的？

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。如有需要，请补充日志等细节并重新开启此issue。
