### ISSUE TITLE
Android 9.0 tinker用到了系统私有方法，求适配解决（兼容android P）

### ISSUE THREAD

**Issue by pmathticol** [Tencent/tinker#784]
异常类型：app运行时异常

手机系统版本：如:Android 9.0

tinker版本：如:1.8.1

gradle版本：如:2.3.2

android p预览版下发补丁之后会报
Detected problems with API compatibility(visit go.co/dev/appcompat for more info)

**Comment by wangbolocojoy** [comment]
我的项目在9.0运行也崩溃了

**Comment by wangbolocojoy** [comment]
我用的是模拟器

**Comment by tomystang** [comment]
已在1.9.5版本中做了修改。

**Comment by LiXiongDEV** [comment]
niu!
