### ISSUE TITLE
vivo X9S 热修复合成失败

### ISSUE THREAD

**Issue by hejinxigege** [Tencent/tinker#794]
异常类型：热修复合成失败

手机型号：如vivo X9S 

手机系统版本：如:Android 7.1.1 

tinker版本：如:1.9.1

gradle版本：如:1.2.3

系统：如:Mac

合成时间5分钟。最终结果失败
 Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 1 times
、、、、
E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.dex is not exist, just wait 22 times

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。
```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

**Comment by tomystang** [comment]
尝试一下1.9.5版本看看有没有问题？

**Comment by hejinxigege** [comment]
试一下

**Comment by Snowinginlight** [comment]
求解决啊，vivo Y66也有问题，怀疑vivo系手机Android 7.1.1版本都有问题，1.9.5也没有解决

**Comment by icemanstudy** [comment]
同上.1.9.2遇到这个问题,升级到1.9.6,发现尝试次数从30次每次15s变成120次每次10s,然而最终还是失败了.

**Comment by DoomTeam** [comment]
vivo x9s android7.1.1系统也存在该问题啊~这应该一样的

**Comment by balizhuang2012** [comment]
我们也发现线上7.1.1手机的合成失败率25%，稍后看看是不是vivo机型

**Comment by tomystang** [comment]
原因同 #826 
后面会将进度同步到那个issue，这个issue就先关闭了。
