### ISSUE TITLE
让用户完全使用自己的Application类

### ISSUE THREAD

**Issue by blackberry2016** [Tencent/tinker#795]
2.0版本能不能把TinkerApplication的实现代码出现抽象出来，让用户自己的Application类在方法里面调用抽象出来的接口，比如在onBaseContextAttached()调用什么方法这样的方式。或者提供接口让用户实现，然后提供tinker框架所需要的东西。让因为目前有些项目必须继承其他第三方的Application类，没法集成tinker.#793

**Comment by sunhb** [comment]
是这个问题，不知道楼上有没有办法放弃对Application的修复，在自己application中初始化Tinker？

**Comment by balizhuang2012** [comment]
确实有这样的需求场景。比如我的Application.startService()想封装一层try catch

**Comment by blackberry2016** [comment]
@sunhb https://github.com/blackberry2016/tinker

**Comment by DengHuiJun** [comment]
确实需要。目前我这边是自己fork tinker下来改造并维护，很麻烦

**Comment by tomystang** [comment]
这个可以有哇，不过Application不能直接引用其他类，需要多搞一层XXLike，让Application通过反射的方式调用XXLike里对应的生命周期函数，这里我暂时还没想到怎么做得通用化。

@DengHuiJun 你那边是怎么处理的呢？

**Comment by DengHuiJun** [comment]
目前就是根据需要的场景，多搞一层XXLike。

**Comment by tomystang** [comment]
好吧，我再想想看能怎么重构一下吧

**Comment by blackberry2016** [comment]
直接去掉xxLike模式稍微改造一下？把android-loader-lib模块下app包现有的类全部去掉。
'''loader/src/main/java/com/tencent/tinker/loader/app/ContextInjector.java

package com.tencent.tinker.loader.app;

import android.annotation.TargetApi;
import android.app.Application;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.Configuration;
import android.os.SystemClock;
import android.support.annotation.CallSuper;

import com.tencent.tinker.loader.TinkerLoader;
import com.tencent.tinker.loader.TinkerRuntimeException;
import com.tencent.tinker.loader.TinkerUncaughtHandler;
import com.tencent.tinker.loader.hotplug.ComponentHotplug;
import com.tencent.tinker.loader.hotplug.UnsupportedEnvironmentException;
import com.tencent.tinker.loader.shareutil.ShareConstants;
import com.tencent.tinker.loader.shareutil.ShareIntentUtil;
import com.tencent.tinker.loader.shareutil.ShareTinkerInternals;

import java.lang.reflect.Constructor;
import java.lang.reflect.Method;

public class ContextInjector {
    //oh, we can use ShareConstants, because they are loader class and static final!
    private static final int TINKER_DISABLE = ShareConstants.TINKER_DISABLE;
    private static final String INTENT_PATCH_EXCEPTION = ShareIntentUtil.INTENT_PATCH_EXCEPTION;
    private static final String TINKER_LOADER_METHOD = "tryLoad";
    public final Application app;

    /**
     * tinkerFlags, which types is supported
     * dex only, library only, all support
     * default: TINKER_ENABLE_ALL
     */
    public final int tinkerFlags;

    /**
     * whether verify md5 when we load dex or lib
     * they store at data/data/package, and we had verity them at the :patch process.
     * so we don't have to verity them every time for quicker!
     * default:false
     */
    public final boolean tinkerLoadVerifyFlag;

    private final String tinkerLoaderClassName;
    private Intent tinkerResultIntent;
    private long applicationStartElapsedTime;
    private long applicationStartMillisTime;

    /**
     * if we have load patch, we should use safe mode
     */
    private boolean useSafeMode = false;

    public ContextInjector(Application app,
                           Intent tinkerResultIntent,
                           long applicationStartElapsedTime,
                           long applicationStartMillisTime,
                           int tinkerFlags,
                           boolean tinkerLoadVerifyFlag) {
        this(app, tinkerResultIntent, applicationStartElapsedTime, applicationStartMillisTime,
                tinkerFlags, tinkerLoadVerifyFlag, TinkerLoader.class.getName());
    }

    public ContextInjector(Application app,
                           Intent tinkerResultIntent,
                           long applicationStartElapsedTime,
                           long applicationStartMillisTime,
                           int tinkerFlags,
                           boolean tinkerLoadVerifyFlag,
                           String tinkerLoaderClassName) {
        this.app = app;
        this.tinkerResultIntent = tinkerResultIntent;
        this.applicationStartElapsedTime = applicationStartElapsedTime;
        this.applicationStartMillisTime = applicationStartMillisTime;
        this.tinkerFlags = tinkerFlags;
        this.tinkerLoadVerifyFlag = tinkerLoadVerifyFlag;
        this.tinkerLoaderClassName = tinkerLoaderClassName;
    }

    @CallSuper
    public void onCreate() {
        try {
            ComponentHotplug.ensureComponentHotplugInstalled(app);
        } catch (UnsupportedEnvironmentException e) {
            throw new TinkerRuntimeException("failed to make sure that ComponentHotplug logic is fine.", e);
        }
    }

    public void onLowMemory() {
    }

    @TargetApi(14)
    public void onTrimMemory(int level) {
    }

    public void onTerminate() {
    }

    public void onConfigurationChanged(Configuration newConfig) {
    }

    public void onBaseContextAttached(Context base) {
        Thread.setDefaultUncaughtExceptionHandler(new TinkerUncaughtHandler(app));
        applicationStartElapsedTime = SystemClock.elapsedRealtime();
        applicationStartMillisTime = System.currentTimeMillis();

        loadTinker();

        // reset save mode
        if (useSafeMode) {
            String processName = ShareTinkerInternals.getProcessName(app);
            String preferName = ShareConstants.TINKER_OWN_PREFERENCE_CONFIG + processName;
            SharedPreferences sp = app.getSharedPreferences(preferName, Context.MODE_PRIVATE);
            sp.edit().putInt(ShareConstants.TINKER_SAFE_MODE_COUNT, 0).commit();
        }
    }

    protected void loadTinker() {
        //disable tinker, not need to install
        if (tinkerFlags == TINKER_DISABLE) {
            return;
        }
        tinkerResultIntent = new Intent();
        try {
            //reflect tinker loader, because loaderClass may be define by user!
            Class<?> tinkerLoadClass = Class.forName(
                    tinkerLoaderClassName,
                    false,
                    app.getClassLoader()
            );
            Method loadMethod = tinkerLoadClass.getMethod(TINKER_LOADER_METHOD, ContextInjector.class);
            Constructor<?> constructor = tinkerLoadClass.getConstructor();
            tinkerResultIntent = (Intent) loadMethod.invoke(constructor.newInstance(), this);
        } catch (Throwable e) {
            //has exception, put exception error code
            ShareIntentUtil.setIntentReturnCode(
                    tinkerResultIntent,
                    ShareConstants.ERROR_LOAD_PATCH_UNKNOWN_EXCEPTION
            );
            tinkerResultIntent.putExtra(INTENT_PATCH_EXCEPTION, e);
        }
    }

    public boolean isUseSafeMode() {
        return useSafeMode;
    }

    public void setUseSafeMode(boolean useSafeMode) {
        this.useSafeMode = useSafeMode;
    }

    public Intent tinkerResultIntent() {
        return tinkerResultIntent;
    }

    public long applicationStartElapsedTime() {
        return applicationStartElapsedTime;
    }

    public long applicationStartMillisTime() {
        return applicationStartMillisTime;
    }

    public final ClassLoader applicationClassLoader() {
        return app.getClassLoader();
    }

    public final Context applicationBaseContext() {
        return app.getBaseContext();
    }
}

'''

**Comment by blackberry2016** [comment]
看看能不能完全去掉XXLike模式

**Comment by sailor1861** [comment]
XXLike有点麻烦；  我是在外面封装一个Application， 项目自己的Application保持不变；

public class OuterApplication extends TinkerApplication {

    public OuterApplication() {
        super(7, "项目自己的Application类名", "com.tencent.tinker.loader.TinkerLoader", false);
    }
} 

// 在自己的Application中，再初始化Tinker
public class MyApplication extends AHBaseApplication {
	public MyApplication(Application application, int tinkerFlags, boolean tinkerLoadVerifyFlag,
                           long applicationStartElapsedTime, long applicationStartMillisTime, Intent tinkerResultIntent
                           /*, Resources[] resources, ClassLoader[] classLoader, AssetManager[] assetManager*/) {
        mHotFix = new Hotfix(application, tinkerFlags, tinkerLoadVerifyFlag,
                applicationStartElapsedTime, applicationStartMillisTime, tinkerResultIntent
                /*, resources, classLoader, assetManager*/, this);
    }
}

**Comment by endlessbest** [comment]
我也是准备用tinker的时候，发现Application很难继承TinkerApplication。无奈之下只有修改源码。动到的地方也不多，在tinker-android-loader这个工程里，把TinkerApplication干掉，再换成对应的调用就差不多了。

**Comment by tomystang** [comment]
@endlessbest 
这种改法有点危险哇，干掉TinkerApplication，再把里面原有的代码放到你自己的Application里，这时候你自己的Application对外部任何类的引用，包括引用XX.class，访问XX类的成员和方法都要通过反射进行，不然容易在dvm环境下报verify error或者在art环境下报class has already been loaded。

**Comment by dotcink** [comment]
@tomystang 我是加了第三个 Application 类，然后把它的方法派发到另两个 Application，其中自己的 Application 是在加载完 Tinker 后反射创建的（因为可能使用新的 ClassLoader）。

**Comment by blackberry2016** [comment]
@tomystang 这个功能目前在开发了吗？

**Comment by hzy00** [comment]
application的强制依赖确实有点难搞，正头疼怎么集成进去

**Comment by hzy00** [comment]
日志的控制也没有弄。。。

**Comment by limingyuan** [comment]
能不能直接继承tinker生成的XXaplicaton呢，在里面做一些操作

**Comment by blackberry2016** [comment]
@limingyuan 不能，因为生成的XXaplicaton是每次编译的时候生成的。

**Comment by limingyuan** [comment]
@blackberry2016  编译时生成在使用上有什么问题吗，在运行时都是已经存在的.class文件

**Comment by android-notes** [comment]
我们是这么搞的，可以做到基本不影响原来的业务代码


1.按照tinker要求创建一个like类，并在里面手动new自己原来的application，并手动调用相关方法。
由于已经在like.onBaseContextAttached中调用了MultiDex.install(base);所以原来的App类只需要继承自Application就可以了

public class MyApplicationLike extends DefaultApplicationLike {
    //未接入tinker前我们的application就叫App
    //现在App已经是一个代理application了，真正的application是tinker的application，不要把application强转成App了
    private App app;
    public MyApplicationLike(Application application, int i, boolean b, long l, long l1, Intent intent) {
        super(application, i, b, l, l1, intent);
        app = new App();
    }

    public void onCreate() {
        super.onCreate();
        app.onCreate();
    }

    @Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);
        //在这执行MultiDex
        MultiDex.install(base);
        //代理真正的ContextImpl
        app.attachBaseContext(base);
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        app.onConfigurationChanged(newConfig);
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        app.onLowMemory();
    }

    @Override
    public void onTerminate() {
        super.onTerminate();
        app.onTerminate();
    }

    @Override
    public void onTrimMemory(int level) {
        super.onTrimMemory(level);
        app.onTrimMemory(level);
    }
}


2.重写App中如下方法，交给真正的application处理
public class App extend Application{
  ...原来的逻辑不用动，只新增如下方法
    @Override
    public void registerComponentCallbacks(ComponentCallbacks callback) {
        Application application = (Application) getBaseContext().getApplicationContext();
        application.registerComponentCallbacks(callback);
    }
    @Override
    public void unregisterComponentCallbacks(ComponentCallbacks callback) {
        Application application = (Application) getBaseContext().getApplicationContext();
        application.unregisterComponentCallbacks(callback);
    }
    @Override
    public void registerActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {
        Application application = (Application) getBaseContext().getApplicationContext();
        application.registerActivityLifecycleCallbacks(callback);
    }
    @Override
    public void unregisterActivityLifecycleCallbacks(ActivityLifecycleCallbacks callback) {
        Application application = (Application) getBaseContext().getApplicationContext();
        application.unregisterActivityLifecycleCallbacks(callback);
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    @Override
    public void registerOnProvideAssistDataListener(OnProvideAssistDataListener callback) {
        Application application = (Application) getBaseContext().getApplicationContext();
        application.registerOnProvideAssistDataListener(callback);
    }

    @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN_MR2)
    @Override
    public void unregisterOnProvideAssistDataListener(OnProvideAssistDataListener callback) {
        Application application = (Application) getBaseContext().getApplicationContext();
        application.unregisterOnProvideAssistDataListener(callback);
    }

}

特别注意，现在App已经是一个代理application了，真正的application是tinker的application，不要把application强转成App了。

=========================
查看ActivityThread.handleBindApplication源码可知

app启动时通过ContextImpl.createAppContext为Application创建了一个真正的context，
然后通过mInstrumentation.newApplication反射创建了一个Application对象，并调用了app.attach(context)（Application继承来的绝大多数方法其实都是调用的这个context中的方法）。然后执行instrumentation.callApplicationOnCreate(app)调用了Application的onCreate方法。

由此看来Application只不过是一个代理，代理了contextimpl，只不过新增了上面几个registerActivityLifecycleCallbacks等方法

**Comment by qianshengta** [comment]
@android-notes   你好 我最近遇到在Application中注册registerActivityLifecycleCallbacks失效的问题。找到原因应该是Application被反射了原因。所以现在打算试试你的这个方法。但是现在有两个问题想请教你。
第一：App和MyApplicationLike 哪个是要注册到AndroidManifest里的。
第二：MyApplicationLike 构造参数是什么？我现在是将MyApplicationLike 注册到AndroidManifest，
           但是在打基准包的时候报错，提示MyApplicationLike 必须要有一个默认的构造函数

**Comment by qianshengta** [comment]
@tomystang   你好 我最近遇到在Application中注册registerActivityLifecycleCallbacks失效的问题。找到原因应该是Application被反射了原因。所以现在打算试试你的这个方法。但是现在有两个问题想请教你。
第一：App和MyApplicationLike 哪个是要注册到AndroidManifest里的。
第二：MyApplicationLike 构造参数是什么？我现在是将MyApplicationLike 注册到AndroidManifest，
           但是在打基准包的时候报错，提示MyApplicationLike 必须要有一个默认的构造函数

**Comment by qianshengta** [comment]
Task :app:lintVitalRelease FAILED
D:\Android\Project\SubordinationProject\BuglyDemo\app\src\main\java\com\qian\buglydemo\MyApplicationLike.java:24: Error: This class should provide a default constructor (a public constructor with no arguments) (com.qian.buglydemo.MyApplicationLike) [Instantiatable]
//    public MyApplicationLike(Application application, int i, boolean b, long l, long l1, Intent intent) {
             ~~~~~~~~~~~~~~~~~

   Explanation for issues of type "Instantiatable":
   Activities, services, broadcast receivers etc. registered in the manifest
   file (or for custom views, in a layout file) must be "instantiatable" by
   the system, which means that the class must be public, it must have an
   empty public constructor, and if it's an inner class, it must be a static
   inner class.
@tomystang @
