### ISSUE TITLE
Android 9 的 sdk api限制会不会对tinker造成影响

### ISSUE THREAD

**Issue by yizeliang** [Tencent/tinker#796]
如题

**Comment by tomystang** [comment]
升级到1.9.5版本吧，我在Android P dp1上对照着修改过，现在应该只会用到light greylist里的api，如果Google的政策不继续收紧的话暂时是没问题的。

**Comment by LiXiongDEV** [comment]
估计google的private api 限制使用政策只会越来越严格吧，是不是要学Apple/iOS封杀类似hotfix方案？
