### ISSUE TITLE
使用keepDexApply=true导致ImmutableDexTransform中报except limit错误.

### ISSUE THREAD

**Issue by icemanstudy** [Tencent/tinker#798]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：编译异常

tinker版本：1.9.2

gradle版本：3.3

是否使用热更新SDK： 否

系统：win,linux都有



```

错误描述:
不修改任何代码的情况下打patch包,若keepDexApply=true,在执行transformClassesWithDexForRelease任务时出现except limit错误.
keepDexApply=false则没问题.

gradle log:
except limit!
        find class com/e/a/a/b$g.class method num: 35976,field num: 64525,belong dex: classes2
except limit!
        find class com/e/a/a/b$f.class method num: 35977,field num: 64530,belong dex: classes2
except limit!
        find class com/e/a/a/b$j.class method num: 35977,field num: 64530,belong dex: classes2

合成patch的log:
Warning:Class Moved. Some classes are just moved from one dex to another. This behavior may leads to unnecessary enlargement of patch file. you should try to check them:
{classDesc:Lcom/e/a/a/b$j;,from:/data/jenkinsCustomWorkspace/hotfix_test/build/outputs/tinkerPatch/prod/release/prod-release/classes2.dex,to:/data/jenkinsCustomWorkspace/hotfix_test/build/outputs/tinkerPatch/prod/release/prod-release/classes4.dex}
{classDesc:Lcom/e/a/a/b$g;,from:/data/jenkinsCustomWorkspace/hotfix_test/build/outputs/tinkerPatch/prod/release/prod-release/classes2.dex,to:/data/jenkinsCustomWorkspace/hotfix_test/build/outputs/tinkerPatch/prod/release/prod-release/classes4.dex}
{classDesc:Lcom/e/a/a/b$f;,from:/data/jenkinsCustomWorkspace/hotfix_test/build/outputs/tinkerPatch/prod/release/prod-release/classes2.dex,to:/data/jenkinsCustomWorkspace/hotfix_test/build/outputs/tinkerPatch/prod/release/prod-release/classes4.dex}

经查看源码发现是ImmutableDexTransform的writeClassToZipNoCheck方法中出错了.

boolean writeClassToZipNoCheck(DexRefData mfData, ClassSimDef cf, ZipOutputStream zos, ZipEntry zipEntry, byte[] bytes) {
        if (mfData.methodNum + cf.methodCount >= 65536 || mfData.fieldNum + cf.fieldCount >= 64536) {
            return false
        } else {
            mfData.methodNum += cf.methodCount
            mfData.fieldNum += cf.fieldCount
            zos.putNextEntry(zipEntry)
            zos.write(bytes)
            zos.closeEntry()
            return true
        }
    }

由于开启keepDexApply=true后会使用ImmutableDexTransform来维持baseapk的分包规则,我猜想可能是这里的逻辑有点问题.从代码中看还未确定对最终的patch包是否有影响.
目前只能先关闭keepDexApply,但还是希望这个特性能够正常使用.

**Comment by tomystang** [comment]
这个我先问下ImmutableDexTransform的提交者为何fieldCount要限制成64536吧，这个版本先不fix，如果确实有必要这样限制的话，就只能接入第三方分dex方案来满足你的分包要求了。
