### ISSUE TITLE
通过Bugly集成热更新总是失败，Tinker patch failure, result

### ISSUE THREAD

**Issue by richfuns** [Tencent/tinker#803]
异常类型：基本不提示补丁成功或者失败，偶尔会提示 补丁应用失败

手机型号：Vivo 1718

手机系统版本：Android 7.1

tinker版本：

classpath "com.tencent.bugly:tinker-support:1.1.1"

compile 'com.tencent.bugly:crashreport_upgrade:1.3.4'

gradle版本：4.1 , Android Gradle Plugin 3.0.1

是否使用热更新SDK： 采用Bugly SDK

系统：Win10

错误： 

03-27 20:00:38.213 28720-28742/? D/CrashReport: [Upload] Bugly version from headers is: bugly/1.0
03-27 20:00:38.214 28720-28742/? D/CrashReport: [Upload] Status from server is 0 (pid=28720 | tid=28742).
    [Upload] Received 370 bytes
03-27 20:00:38.224 28720-28742/? D/CrashReport: [Util] Unzip 354 bytes data with type Gzip
03-27 20:00:38.226 28720-28742/? D/CrashReport: [Upload] Response cmd is: 804, length of sBuffer is: 299
03-27 20:00:38.227 28720-28742/? I/CrashReport: [Upload] Success: 804
03-27 20:00:38.230 28720-28742/? D/CrashReport: [UploadManager] Local network consume: 5 KB
03-27 20:00:38.245 28720-28742/? D/CrashReport: [Database] deleted t_lr data 1
03-27 20:00:38.263 28720-28742/? D/CrashReport: [Database] insert t_lr success.
    [UploadManager] Network total consume: 6 KB
03-27 20:00:38.263 28720-28742/? I/CrashReport: upload succ:[804] [sended 810] [recevied 370]
03-27 20:00:38.287 28720-28742/? D/CrashReport: [Database] insert st_1002 success.
03-27 20:00:38.290 28720-28742/? I/CrashReport: onUpgradeReceived: title: 
    newFeature: 1.0.3版本测试
    publishTime: 0
    publishType: 0
    appBasicInfo: {
    	appId: 0bf8c8f3bc
    	platformId: 1
    	versionCode: 0
    	versionName: null
    	buildNo: 0
    	iconUrl: null
    	apkId: 0
    	channelId: null
    	md5: ec86d54d642b48f5d924ec2e65da7040b6e6aec6
    	sdkVer: 
    	bundleId: null
    }
    apkBaseInfo: {
    	apkMd5: ec86d54d642b48f5d924ec2e65da7040b6e6aec6
    	apkUrl: https://s.beta.gtimg.com/rdmimg/hot_patch/0bf8c8f3bc/4cca09ac-9926-4a4a-b871-5e443c292239.zip
    	manifestMd5: 
    	fileSize: 3752
    	signatureMd5: 
    }
    updateStrategy: 0
    popTimes: 0
    popInterval: 0
    diffApkInfo: {
    	null}
    netType: null
    reserved: 1, {
    	(
    		H2
    		1
    	)
    }
    strategyId: c28e1a98-7d59-4ad8-afc4-698c43add3db
    status: 1
    updateTime: 1522151993000
    updateType: 3
     [type: 3]
03-27 20:00:38.296 28720-28742/? W/CrashReport: task start com.tencent.bugly.proguard.t
03-27 20:00:38.729 28720-28776/? D/CrashReport: [Database] insert dl_1002 success.
03-27 20:00:38.746 28720-28776/? D/CrashReport: [Database] insert dl_1002 success.
03-27 20:00:38.771 28720-28776/? D/CrashReport: [Database] insert dl_1002 success.
03-27 20:00:38.779 28720-28720/? I/CrashReport: patch download success !!!
03-27 20:00:38.781 28720-28720/? D/CrashReport: copy /data/user/0/us.godeye.tinkerdemo/app_tmpPatch/4cca09ac-9926-4a4a-b871-5e443c292239.zip to /data/user/0/us.godeye.tinkerdemo/app_tmpPatch/tmpPatch.apk success!
    delete temp file
03-27 20:00:38.922 28791-28791/? W/CrashReport: Bugly debug模式开启，请在发布时把isDebug关闭。 -- Running in debug model for 'isDebug' is enabled. Please disable it when you release.
03-27 20:00:38.923 28791-28791/? E/CrashReport: --------------------------------------------------------------------------------------------
03-27 20:00:38.923 28791-28791/? W/CrashReport: Bugly debug模式将有以下行为特性 -- The following list shows the behaviour of debug model: 
    [1] 输出详细的Bugly SDK的Log -- More detailed log of Bugly SDK will be output to logcat;
    [2] 每一条Crash都会被立即上报 -- Every crash caught by Bugly will be uploaded immediately.
    [3] 自定义日志将会在Logcat中输出 -- Custom log will be output to logcat.
03-27 20:00:38.923 28791-28791/? E/CrashReport: --------------------------------------------------------------------------------------------
03-27 20:00:38.923 28791-28791/? I/CrashReportInfo: [init] Open debug mode of Bugly.
03-27 20:00:38.923 28791-28791/? I/CrashReport: [init] Bugly version: v2.6.5
     crash report start initializing...
03-27 20:00:38.923 28791-28791/? I/CrashReportInfo: [init] Bugly start initializing...
03-27 20:00:38.923 28791-28791/? I/CrashReport: [init] Bugly complete version: v2.6.5(1.3.4)
03-27 20:00:38.927 28791-28791/? I/CrashReport: [param] Set APP ID:0bf8c8f3bc
03-27 20:00:38.928 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.biz.a$a
03-27 20:00:38.929 28791-28791/? I/CrashReport: [session] launch app, new start
03-27 20:00:38.929 28791-28810/? D/CrashReport: [UserInfo] Record user info.
03-27 20:00:38.929 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 14366071ms) task: com.tencent.bugly.crashreport.biz.a$b
03-27 20:00:38.931 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 21600000ms) task: com.tencent.bugly.crashreport.biz.a$c
03-27 20:00:38.933 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$2
03-27 20:00:38.934 28791-28791/? I/CrashReport: Initializing crash module.
03-27 20:00:38.945 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
03-27 20:00:38.947 28791-28791/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@debec7d
    registered java monitor: com.tencent.bugly.crashreport.crash.e@52ff772
    user change native true
    native changed to true
    [Native] Trying to load so: Bugly
03-27 20:00:38.948 28791-28791/? W/CrashReport: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/us.godeye.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/us.godeye.tinkerdemo-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libBugly.so"
    [Native] Failed to load so: Bugly
03-27 20:00:38.948 28791-28791/? I/CrashReport: anr changed to true
03-27 20:00:38.949 28791-28791/? I/CrashReport: start anr monitor!
03-27 20:00:38.950 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.anr.b$2
    [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.d$1
03-27 20:00:38.951 28791-28791/? D/CrashReport: add action android.net.conn.CONNECTIVITY_CHANGE
    [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.crash.BuglyBroadcastRecevier$1
03-27 20:00:38.954 28791-28812/? D/CrashReport: [ExtraCrashManager] Trying to notify Bugly agents.
03-27 20:00:38.955 28791-28812/? D/CrashReport: [ExtraCrashManager] Bugly game agent has been notified.
03-27 20:00:38.955 28791-28812/? I/CrashReport: [BuglyBroadcastRecevier] Register broadcast receiver of Bugly.
03-27 20:00:38.956 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
    [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$2
03-27 20:00:38.957 28791-28791/? I/CrashReport: Beta init start....
03-27 20:00:38.957 28791-28810/? D/CrashReport: [Database] insert t_ui success.
    [Database] insert t_ui success with ID: 5
03-27 20:00:38.959 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
03-27 20:00:38.959 28791-28791/? I/CrashReport: Beta will init at: us.godeye.tinkerdemo
    current process: us.godeye.tinkerdemo:patch
03-27 20:00:38.960 28791-28791/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.common.strategy.a$1
03-27 20:00:38.960 28791-28791/? I/CrashReportInfo: [init] Bugly initialization finished.
03-27 20:00:38.966 28791-28812/? D/CrashReport: [Strategy] Notify com.tencent.bugly.crashreport.biz.b
    [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.biz.a$2
    [Strategy] Notify com.tencent.bugly.CrashModule
03-27 20:00:38.967 28791-28812/? W/CrashReport: server native changed to true
03-27 20:00:38.967 28791-28812/? I/CrashReport: native changed to true
    [Native] Trying to load so: Bugly
03-27 20:00:38.967 28791-28812/? W/CrashReport: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/us.godeye.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/us.godeye.tinkerdemo-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libBugly.so"
    [Native] Failed to load so: Bugly
03-27 20:00:38.967 28791-28812/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.crash.c$2
    [Strategy] Notify com.tencent.bugly.beta.Beta
    Uploading frequency will not be checked if SDK is in debug mode.
03-27 20:00:38.969 28791-28810/? D/CrashReport: [Util] try to lock file:local_crash_lock (pid=28791 | tid=28810)
03-27 20:00:38.969 28791-28812/? D/CrashReport: [UserInfo] Upload user info(size: 1)
03-27 20:00:38.969 28791-28810/? D/CrashReport: [Util] successfully locked file:local_crash_lock (pid=28791 | tid=28810)
03-27 20:00:38.971 28791-28810/? D/CrashReport: [Util] try to unlock file:local_crash_lock (pid=28791 | tid=28810)
    [Util] successfully unlocked file:local_crash_lock (pid=28791 | tid=28810)
03-27 20:00:38.974 28791-28812/? I/CrashReport: Failed to get IMEI.
03-27 20:00:38.982 28791-28812/? I/CrashReport: Failed to get IMSI.
03-27 20:00:38.992 28791-28812/? D/CrashReport: summary type 1 vm:7
03-27 20:00:39.030 28791-28812/? D/CrashReport: [ap] Successfully get 'getprop' list.
03-27 20:00:39.052 28791-28812/? D/CrashReport: [ap] System properties number: 667.
03-27 20:00:39.072 28791-28812/? D/CrashReport: su not found
03-27 20:00:39.080 28791-28812/? I/CrashReport: Failed to get IMEI.
03-27 20:00:39.085 28791-28812/? I/CrashReport: Failed to get IMSI.
03-27 20:00:39.089 28791-28812/? D/CrashReport: MAC interface: wlan0
03-27 20:00:39.091 28791-28812/? D/CrashReport: MAC address: 3C:A6:16:AF:E9:5D
03-27 20:00:39.092 28791-28812/? I/CrashReport: ROM ID: vivo/FUNTOUCH/Funtouch OS_3.2
03-27 20:00:39.096 28791-28812/? I/CrashReport: Failed to get SIM serial number.
    SIM serial number: fail
    Hardware serial number: f1e4cab6
03-27 20:00:39.105 28791-28812/? D/CrashReport: [UploadManager] Add upload task (pid=28791 | tid=28812)
    [UploadManager] Initialize security context now (pid=28791 | tid=28812)
03-27 20:00:39.106 28791-28812/? D/CrashReport: [UploadManager] Add upload task to queue (pid=28791 | tid=28812)
03-27 20:00:39.106 28791-28812/? I/CrashReport: [UploadManager] Create and start a new thread to execute a task of initializing security context: BUGLY_ASYNC_UPLOAD
03-27 20:00:39.106 28791-28820/? D/CrashReport: [Util] try to lock file:security_info (pid=28791 | tid=28820)
03-27 20:00:39.107 28791-28820/? D/CrashReport: [Util] successfully locked file:security_info (pid=28791 | tid=28820)
    [UploadManager] Load security info from database (pid=28791 | tid=28820)
03-27 20:00:39.108 28791-28820/? D/CrashReport: [UploadManager] Sucessfully got session ID, try to execute upload tasks now (pid=28791 | tid=28820)
03-27 20:00:39.109 28791-28820/? D/CrashReport: [UploadManager] Try to poll all upload task need and put them into temp queue (pid=28791 | tid=28820)
    [UploadManager] Execute urgent upload tasks of queue which has 1 tasks (pid=28791 | tid=28820)
03-27 20:00:39.109 28791-28820/? I/CrashReport: [UploadManager] Create and start a new thread to execute a upload task: BUGLY_ASYNC_UPLOAD
03-27 20:00:39.110 28791-28820/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ak$2
03-27 20:00:39.111 28791-28820/? D/CrashReport: [Util] try to unlock file:security_info (pid=28791 | tid=28820)
    [Util] successfully unlocked file:security_info (pid=28791 | tid=28820)
03-27 20:00:39.113 28791-28821/? D/CrashReport: [UploadManager] Local network consume: 6 KB
    [Upload] Run upload task with cmd: 840
    [UploadManager] Integrate security to HTTP headers (pid=28791 | tid=28821)
03-27 20:00:39.114 28791-28821/? D/CrashReport: [Util] Zip 1472 bytes data with type Gzip
03-27 20:00:39.135 28791-28821/? D/CrashReport: [Database] deleted t_lr data 1
03-27 20:00:39.144 28791-28821/? D/CrashReport: [Database] insert t_lr success.
03-27 20:00:39.146 28791-28821/? D/CrashReport: [UploadManager] Uploading(ID:1001) time: 2018-03-27 20:00:39
    [Upload] Send 1006 bytes
    [Upload] Upload to http://android.bugly.qq.com/rqd/async?aid=6175e717-0d0f-486a-b024-ab32eed0add8 with cmd 840 (pid=28791 | tid=28821).
03-27 20:00:39.147 28791-28821/? D/CrashReport: request: http://android.bugly.qq.com/rqd/async?aid=6175e717-0d0f-486a-b024-ab32eed0add8, send: 1006 (pid=28791 | tid=28821)
03-27 20:00:39.332 28791-28821/? D/CrashReport: [Upload] Bugly version from headers is: bugly/1.0
    [Upload] Status from server is 0 (pid=28791 | tid=28821).
    [Upload] Received 148 bytes
03-27 20:00:39.334 28791-28821/? D/CrashReport: [Util] Unzip 132 bytes data with type Gzip
03-27 20:00:39.336 28791-28821/? D/CrashReport: [Upload] Response cmd is: 0, length of sBuffer is: 0
03-27 20:00:39.348 28791-28821/? D/CrashReport: [Database] insert t_pf success.
03-27 20:00:39.348 28791-28821/? I/CrashReport: [Upload] Success: userinfo
03-27 20:00:39.350 28791-28821/? D/CrashReport: [UploadManager] Local network consume: 6 KB
03-27 20:00:39.360 28791-28821/? D/CrashReport: [Database] deleted t_lr data 1
03-27 20:00:39.370 28791-28821/? D/CrashReport: [Database] insert t_lr success.
    [UploadManager] Network total consume: 7 KB
    [UserInfo] Successfully uploaded user info.
03-27 20:00:39.380 28791-28821/? D/CrashReport: [Database] insert t_ui success.
    [Database] insert t_ui success with ID: 5
03-27 20:04:44.954 28720-28720/? I/CrashReport: Tinker patch failure, result: 
    PatchResult: 
    isSuccess:false
    rawPatchFilePath:/data/user/0/us.godeye.tinkerdemo/app_tmpPatch/tmpPatch.apk
    costTime:245955
    patchVersion:0907d64fbe256c2a7ac1a514a4d73953

再次尝试的错误： 

03-27 20:23:54.106 3842-3842/? I/CrashReport: Beta init start....
03-27 20:23:54.109 3842-3842/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
03-27 20:23:54.109 3842-3842/? I/CrashReport: Beta will init at: us.godeye.tinkerdemo
    current process: us.godeye.tinkerdemo
    current upgrade sdk version:1.3.4
    setted upgradeCheckPeriod: 0
    setted initDelay: 3000
    autoCheckUpgrade is opened
    showInterruptedStrategy is opened
    isDIY is closed
03-27 20:23:54.110 3842-3842/? I/CrashReport: enableNotification true
    autoDownloadOnWifi false
    canShowApkInfo true
    canAutoPatch true
    canNotifyUserRestart true
    canAutoDownloadPatch true
    enableHotfix true
03-27 20:23:54.115 3842-3842/? I/CrashReport: apkSaveDir: /storage/emulated/0/Android/data/us.godeye.tinkerdemo/files/apk, resSaveDir: /storage/emulated/0/Android/data/us.godeye.tinkerdemo/files/res
03-27 20:23:54.123 3842-3842/? I/CrashReport: enableHotfix 1
03-27 20:23:54.126 3842-3842/? I/CrashReport: [patch] inject failure
03-27 20:23:54.135 3842-3842/? D/CrashReport: [Database] insert ge_1002 success.
03-27 20:23:54.135 3842-3842/? I/CrashReport: save patch failed event success!
    [patch] delete patch.apk success
    [patch] delete tmpPatch.apk success
03-27 20:23:54.136 3842-3842/? I/CrashReport: TINKER_ID:base-1.0.3
03-27 20:23:54.137 3842-3842/? I/CrashReport: NEW_TINKER_ID:
03-27 20:23:54.138 3842-3842/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 3000ms) task: com.tencent.bugly.beta.global.d
03-27 20:23:54.139 3842-3842/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ac$1
03-27 20:23:54.139 3842-3842/? I/CrashReport: Beta init finished...
03-27 20:23:54.139 3842-3842/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.common.strategy.a$1
03-27 20:23:54.139 3842-3842/? I/CrashReportInfo: [init] Bugly initialization finished.
03-27 20:23:54.142 3842-3872/? D/CrashReport: [Strategy] Notify com.tencent.bugly.crashreport.biz.b
    [AsyncTaskHandler] Post a normal task: com.tencent.bugly.crashreport.biz.a$2
    [Strategy] Notify com.tencent.bugly.CrashModule
03-27 20:23:54.142 3842-3872/? W/CrashReport: server native changed to true
03-27 20:23:54.142 3842-3872/? I/CrashReport: native changed to true
    [Native] Trying to load so: Bugly
03-27 20:23:54.143 3842-3870/? D/CrashReport: Uploading frequency will not be checked if SDK is in debug mode.
03-27 20:23:54.143 3842-3872/? W/CrashReport: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/us.godeye.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/us.godeye.tinkerdemo-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libBugly.so"
    [Native] Failed to load so: Bugly
03-27 20:23:54.143 3842-3872/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.crash.c$2
03-27 20:23:54.144 3842-3872/? D/CrashReport: [Strategy] Notify com.tencent.bugly.beta.Beta
03-27 20:23:54.144 3842-3869/? D/CrashReport: [Util] try to lock file:local_crash_lock (pid=3842 | tid=3869)
03-27 20:23:54.145 3842-3869/? D/CrashReport: [Util] successfully locked file:local_crash_lock (pid=3842 | tid=3869)
03-27 20:23:54.145 3842-3870/? D/CrashReport: [UserInfo] Upload user info(size: 2)
03-27 20:23:54.146 3842-3869/? D/CrashReport: [Util] try to unlock file:local_crash_lock (pid=3842 | tid=3869)
03-27 20:23:54.147 3842-3869/? D/CrashReport: [Util] successfully unlocked file:local_crash_lock (pid=3842 | tid=3869)
03-27 20:23:54.148 3842-3870/? I/CrashReport: Failed to get IMEI.
03-27 20:23:54.152 3842-3870/? I/CrashReport: Failed to get IMSI.
03-27 20:23:54.154 3842-3870/? D/CrashReport: summary type 3 vm:8
03-27 20:23:54.155 3842-3870/? D/CrashReport: summary type 1 vm:7
03-27 20:23:54.162 3842-3842/? D/CrashReport: >>> us.godeye.tinkerdemo.MainActivity onCreated <<<
03-27 20:23:54.183 3842-3870/? D/CrashReport: [ap] Successfully get 'getprop' list.
03-27 20:23:54.203 3842-3870/? D/CrashReport: [ap] System properties number: 667.
03-27 20:23:54.218 3842-3870/? D/CrashReport: su not found
03-27 20:23:54.223 3842-3870/? I/CrashReport: Failed to get IMEI.
03-27 20:23:54.226 3842-3870/? I/CrashReport: Failed to get IMSI.
03-27 20:23:54.229 3842-3870/? D/CrashReport: MAC interface: wlan0
03-27 20:23:54.231 3842-3870/? D/CrashReport: MAC address: 3C:A6:16:AF:E9:5D
03-27 20:23:54.232 3842-3870/? I/CrashReport: ROM ID: vivo/FUNTOUCH/Funtouch OS_3.2
03-27 20:23:54.235 3842-3870/? I/CrashReport: Failed to get SIM serial number.
    SIM serial number: fail
    Hardware serial number: f1e4cab6
03-27 20:23:54.244 3842-3870/? D/CrashReport: [UploadManager] Add upload task (pid=3842 | tid=3870)
    [UploadManager] Initialize security context now (pid=3842 | tid=3870)
    [UploadManager] Add upload task to queue (pid=3842 | tid=3870)
03-27 20:23:54.244 3842-3870/? I/CrashReport: [UploadManager] Create and start a new thread to execute a task of initializing security context: BUGLY_ASYNC_UPLOAD
03-27 20:23:54.245 3842-3883/? D/CrashReport: [Util] try to lock file:security_info (pid=3842 | tid=3883)
03-27 20:23:54.246 3842-3883/? D/CrashReport: [Util] successfully locked file:security_info (pid=3842 | tid=3883)
    [UploadManager] Load security info from database (pid=3842 | tid=3883)
03-27 20:23:54.247 3842-3842/? D/CrashReport: >>> us.godeye.tinkerdemo.MainActivity onResumed <<<
03-27 20:23:54.248 3842-3883/? D/CrashReport: [UploadManager] Sucessfully got session ID, try to execute upload tasks now (pid=3842 | tid=3883)
    [UploadManager] Try to poll all upload task need and put them into temp queue (pid=3842 | tid=3883)
    [UploadManager] Execute urgent upload tasks of queue which has 1 tasks (pid=3842 | tid=3883)
03-27 20:23:54.248 3842-3842/? I/CrashReport: [session] launch app one times (app in background 1522153434 seconds and over 30 seconds)
03-27 20:23:54.248 3842-3883/? I/CrashReport: [UploadManager] Create and start a new thread to execute a upload task: BUGLY_ASYNC_UPLOAD
03-27 20:23:54.248 3842-3842/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 0ms) task: com.tencent.bugly.crashreport.biz.a$a
03-27 20:23:54.248 3842-3842/? I/CrashReport: add a timer to upload hot start user info
03-27 20:23:54.248 3842-3872/? D/CrashReport: [UserInfo] Record user info.
03-27 20:23:54.248 3842-3842/? D/CrashReport: [AsyncTaskHandler] Post a delay(time: 300000ms) task: com.tencent.bugly.crashreport.biz.a$a
03-27 20:23:54.249 3842-3883/? D/CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.ak$2
    [Util] try to unlock file:security_info (pid=3842 | tid=3883)
03-27 20:23:54.250 3842-3883/? D/CrashReport: [Util] successfully unlocked file:security_info (pid=3842 | tid=3883)
03-27 20:23:54.252 3842-3884/? D/CrashReport: [UploadManager] Local network consume: 15 KB
    [Upload] Run upload task with cmd: 840
03-27 20:23:54.253 3842-3884/? D/CrashReport: [UploadManager] Integrate security to HTTP headers (pid=3842 | tid=3884)
    [Util] Zip 1721 bytes data with type Gzip
03-27 20:23:54.260 3842-3872/? D/CrashReport: [Database] insert t_ui success.
    [Database] insert t_ui success with ID: 10
03-27 20:23:54.271 3842-3884/? D/CrashReport: [Database] deleted t_lr data 1
03-27 20:23:54.277 3842-3884/? D/CrashReport: [Database] insert t_lr success.

**Comment by tomystang** [comment]
这个应该跟两个月后有人发的issue是一个问题，1.9.8版本已经修复了，预计6月22号发布。

**Comment by richfuns** [comment]
@tomystang  谢谢您的回复，拭目以待啊
