### ISSUE TITLE
1.9.5版本patch补丁包在小米手机上合成失败问题

### ISSUE THREAD

**Issue by bufferoverflowexception** [Tencent/tinker#804]
异常类型：patch补丁包合成失败

手机型号：红米Note3， 小米6

手机系统版本：Android 6.0， Android 7

tinker版本：1.9.5

gradle版本：3.0.1

是否使用热更新SDK： 是，TinkerPatch SDK 

系统：Mac

使用的是TinkerPatch SDK 版本1.2.5， 内置的tinker版本是1.9.5 ，在小米手机上面负责合成的 job service启动失败，经测试两台小米手机均失败，换了另外一台三星手机成功，所以确定是跟系统有关，跟接入没有关系（起初以为是接入步骤有问题） logcat下面看到负责合成的服务被系统拒绝了

03-29 11:13:22.900 1620-2065/? I/AutoStartManagerService: MIUILOG- Reject service :Intent { cmp=com.xx.xxx.xxx.test/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner } userId : 0 uid : 10214
03-29 11:13:22.901 1620-2065/? D/JobSchedulerService: Error executing 236..:[ComponentInfo{com.xx.xxx.xxxx.test/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner},jId=1,u0,suid=10214,R=(-00:05,none),N=0,C=false,I=false,U=false,F=0,P=false,ANI=true,DND=true(READY)]

**Comment by tomystang** [comment]
MIUI的自启动权限会限制JobScheduler的运行，好坑……
你试试在安全中心-授权管理-自启动权限里把你的app的自启动权限打开，应该就正常了。

**Comment by bufferoverflowexception** [comment]
MIUI真坑 。。暂时选择退回1.9.2版本了

**Comment by hqzxzwb** [comment]
1.9.6仍然复现 @tomystang

**Comment by EnternalRain** [comment]
mi 6 ，os 8.0.0 还是复现。没有在安全中心-授权管理-自启动权限里把app的自启动权限打开的情况下

**Comment by simpleton** [comment]
@hqzxzwb @EnternalRain 各位试试1.9.8?

**Comment by lijie815917** [comment]
小米8 ，1.9.9也不行

**Comment by simpleton** [comment]
1.9.11 还可以复现么？

**Comment by lijie815917** [comment]
1.9.11版本在小米8，MIUI10，android8.1上问题还是复现，必须要给应用自启动授权才能成功

**Comment by lijie815917** [comment]
@simpleton @tomystang
