### ISSUE TITLE
如果对于版本1.0.0有两个基线版本,那么这个时候补丁修复会是什么样的情况呢

### ISSUE THREAD

**Issue by xingstarx** [Tencent/tinker#807]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常/编译异常
app运行时异常

手机型号：如:Nexus 5(如是编译异常，则可以不填)

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

tinker版本：如:1.7.7
1.9.1
gradle版本：如:2.10
2.2.3

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK
都不是，用的tinker-manager
系统：如:Mac
Mac
堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。
```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

假设存在这种需求，
我有一个app版本1.0.0，这个版本对应了一个补丁patch1，然后呢我把官网上的1.0.0的apk替换为修复了补丁patch1的1.0.0Fix的apk，当然了apk的版本还是1.0.0，之后线上又出现了一个新的bug，我就打了一个新的补丁patch2。现在发现，patch2对1.0.0.apk，还有1.0.0Fix.apk都能生效,不懂为啥会这样

问这个问题是考虑到在对tinker源码有一定的熟悉程度下，希望寻求到合适的办法能否满足目前我们的需求

tinker补丁合成过程中，关键逻辑在于
![image](https://user-images.githubusercontent.com/8245264/38245893-8b6d68b0-3772-11e8-841b-00a0b5b32a71.png)

upgradePatch.tryPatch()方法，里面做了很多事情，包括验证，dex、res、libriry的合成等等，目前而言，感觉是dex都可以合成，这就导致了我的两个基线版本，对于这两个任意的补丁都能修复，也是醉醉的

**Comment by tomystang** [comment]
这种情况一般是你的tinker_id没改导致的，你的tinker id用的是版本号吗？

**Comment by xingstarx** [comment]
嗯，是的，tinkerid用的是版本号

**Comment by xingstarx** [comment]
是不是还是得这样，对于替换官网上的1.0.0.fix.apk修改其tinkerId为1.0.0.fix，严格区分，那么patch1只会在1.0.0.apk上面生效了，

如果出现了新的bug，那么只在最初的基线版本上打patch2，也只修复1.0.0.apk了，除非有必要在从1.0.0.fix.apk处打一个新的patch2fix,用来处理1.0.0.fix.apk的bug了

还有一个问题，能解释下，为啥我问题中描述的patch补丁可以通过dex合成呢，这块我看的不是很懂，能指点下么

**Comment by tomystang** [comment]
是的，tinker id要能区分每个不同的apk。这就是tinker为啥要弄一个tinker id的概念出来的原因。不过你说你后面那个补丁能合成成功，这个我也觉得奇怪哇，你试试对比一下旧包和旧包.fix的dex的md5？

**Comment by tomystang** [comment]
> 如果出现了新的bug，那么只在最初的基线版本上打patch2，也只修复1.0.0.apk了，除非有必要在从1.0.0.fix.apk处打一个新的patch2fix,用来处理1.0.0.fix.apk的bug了

对的，确实要这样操作才行

**Comment by xingstarx** [comment]
问了simsun，他说加固的app没有做校验，我在DexDiffDecoder这个类里面看到生成patch针对加固的app是有特殊的处理，没有做校验，或许就是这个原因吧

**Comment by tomystang** [comment]
对的，加固过确实会有这个问题。这个算bug，多谢提醒哇。

**Comment by xingstarx** [comment]
别客气啊，我再多做下实验，关了issue的😂😂
