### ISSUE TITLE
TinkerPatchException:  some classes was unexpectedly changed in patched new dex,  check if there's any bugs in patch algorithm. 

### ISSUE THREAD

**Issue by PeiDongHan** [Tencent/tinker#81]
集成tinker到自己的项目里，调用tinkerPatchDebug时异常退出。

Terminal log：
>:wallet:mergeDebugJniLibFolders UP-TO-DATE              
>:wallet:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE      
>:wallet:processDebugJavaRes UP-TO-DATE
>:wallet:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
>:wallet:validateReleaseSigning
>:wallet:packageDebug                 
>:wallet:zipalignDebug                 
>:wallet:assembleDebug                 
>:wallet:tinkerPatchDebug                 
>**found modify resource: AndroidManifest.xml ,but it is AndroidManifest.xml, just ignore!
>com.tencent.tinker.build.util.TinkerPatchException: some classes was unexpectedly changed in patched new dex, check if there's any bugs in patch algorithm. Rel
>ated classes: {Lcom/facebook/react/views/view/ReactViewManager;,Lcom/facebook/csslayout/CSSConstants;,Lcom/facebook/react/views/drawer/ReactDrawerLayoutManager
>;,Lcom/facebook/react/uimanager/LayoutShadowNode;,Lcom/facebook/react/views/toolbar/ReactToolbarManager;,Lcom/facebook/react/views/text/ReactTextViewManager;}**
> Building 99% > :wallet:tinkerPatchDebug

log.txt ：

>-----------------------Tinker patch begin-----------------------
>configuration: 
>oldApk:D:\UMPworkspace\workspace\WalletTinker\wallet\build\bakApk/wallet-debug-0928-19-44-30.apk
>newApk:D:\UMPworkspace\workspace\WalletTinker\target\upay_wallet_fordeve.apk
>outputFolder:D:\UMPworkspace\workspace\WalletTinker/tinkerPatch/debug
>isIgnoreWarning:false
>7-ZipPath:C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
>useSignAPk:true
>package meta fields: 
>filed name:patchMessage, filed value:tinker is sample to use
>filed name:platform, filed value:all
>dex configs: 
>dexMode: jar
>dexPattern:classes.*\.dex
>dexPattern:assets/secondary-dex-.\.jar
>dex loader:com.tencent.tinker.loader.*
>dex loader:tinker.sample.android.SampleApplication
>dex loader:tinker.sample.android.app.BaseBuildInfo
>lib configs: 
>libPattern:lib/armeabi/.*\.so
>resource configs: 
>resPattern:assets/.*
>resPattern:res/.*
>resPattern:AndroidManifest\.xml
>resPattern:resources\.arsc
>resIgnore change:assets/sample_meta\.txt
>largeModSize:100kb
>useApplyResource:false
>
>Analyze old and new apk files:
>old apk: wallet-debug-0928-19-44-30.apk, size=21342655, md5=4515358642afdf0e768ecf40118c7582
>new apk: upay_wallet_fordeve.apk, size=21344002, md5=b9bedd6651fdc435704b11e7369b48bf
>UnZipping apk to D:\UMPworkspace\workspace\WalletTinker\tinkerPatch\debug\wallet-debug-0928-19-44-30
>UnZipping apk to D:\UMPworkspace\workspace\WalletTinker\tinkerPatch\debug\upay_wallet_fordeve
>found modify resource: AndroidManifest.xml ,but it is AndroidManifest.xml, just ignore!
>Check for loader classes in dex: ../wallet-debug-0928-19-44-30/classes.dex
>Check for loader classes in dex: ../wallet-debug-0928-19-44-30/classes2.dex>
>
>Gen classes.dex patch file:D:\UMPworkspace\workspace\WalletTinker\tinkerPatch\debug\tinker_result\classes.dex, size:3934, md5:b0591b36806134976489e5d8b6088963
>Verifying if patched new dex is logically the same as original new dex: upay_wallet_fordeve/classes.dex ...

dex_log.txt ：

>Start diff between [wallet-debug-0928-19-44-30/classes.dex] as old and [upay_wallet_fordeve/classes.dex] as new:

在我的项目里由于一部分使用了ReactNative，所以引用了
>compile "com.facebook.react:react-native:0.19.+"

但是执行tinkerPatchDebug之前我并没有修改ReactNative相关代码，请问是什么问题。

**Comment by shwenzhang** [comment]
麻烦将新旧两个apk发到我邮箱，我具体分析一下

**Comment by shwenzhang** [comment]
@PeiDongHan ,  麻烦将新旧两个apk发到我的gmail邮箱，谢谢

**Comment by PeiDongHan** [comment]
@shwenzhang 不好意思回复晚了，由于公司规定不能提供未加固的apk，我将项目中的ReactNative依赖库导入到sample工程中，复现了该问题。

执行tinkerPatchDebug任务的Terminal log：
>:app:validateDebugSigning                 
>:app:packageDebug                 
>:app:zipalignDebug                 
>:app:assembleDebug                 
>:app:tinkerPatchDebug                                                                      
>com.tencent.tinker.build.util.TinkerPatchException: some classes was unexpectedly changed in patched new dex, check if there's any bugs in patch algorithm. Rel
ated classes: {Lcom/facebook/react/views/view/ReactViewManager;,Lcom/facebook/csslayout/CSSConstants;,Lcom/facebook/react/views/drawer/ReactDrawerLayoutManager
;,Lcom/facebook/react/uimanager/LayoutShadowNode;,Lcom/facebook/react/views/toolbar/ReactToolbarManager;,Lcom/facebook/react/views/text/ReactTextViewManager;}
>        at com.tencent.tinker.build.decoder.DexDiffDecoder.checkDexChange(DexDiffDecoder.java:512)
>        at com.tencent.tinker.build.decoder.DexDiffDecoder.onAllPatchesEnd(DexDiffDecoder.java:228)
>        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:123)
>        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
>        at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
>        at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
>        at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
>        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>        at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:84)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>        at java.lang.reflect.Method.invoke(Method.java:498)
>        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
>        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
>        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
>        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
>        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
>        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
>        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
>        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
>        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
>        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
>        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
>        at org.gradle.internal.Factories$1.create(Factories.java:22)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
>        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
>        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
>        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
>        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
>        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
>        at org.gradle.util.Swapper.swap(Swapper.java:38)
>        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
>        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
>        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
>        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
>        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
>        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>        at java.lang.Thread.run(Thread.java:745)
>com.tencent.tinker.build.util.TinkerPatchException: Failed to generate temporary patched dex, which makes MD5 generating procedure of new dex failed, either.
>        at com.tencent.tinker.build.decoder.DexDiffDecoder.onAllPatchesEnd(DexDiffDecoder.java:234)
>        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:123)
>        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
>        at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
>        at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
>        at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
>        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
>        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
>        at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:84)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>        at java.lang.reflect.Method.invoke(Method.java:498)
>        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
>        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
>        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
>        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
>        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
>        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
>        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
>        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
>        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
>        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
>        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
>        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
>        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
>        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
>        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
>        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
>        at org.gradle.internal.Factories$1.create(Factories.java:22)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
>        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
>        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
>        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
>        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
>        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
>        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
>        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
>        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
>        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
>        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
>        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
>        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
>        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
>        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
>        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
>        at org.gradle.util.Swapper.swap(Swapper.java:38)
>        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
>        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
>        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
>        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
>        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
>        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
>        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
>        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>        at java.lang.Thread.run(Thread.java:745)
>Caused by: com.tencent.tinker.build.util.TinkerPatchException: some classes was unexpectedly changed in patched new dex, check if there's any bugs in patch alg
orithm. Related classes: {Lcom/facebook/react/views/view/ReactViewManager;,Lcom/facebook/csslayout/CSSConstants;,Lcom/facebook/react/views/drawer/ReactDrawerLa
youtManager;,Lcom/facebook/react/uimanager/LayoutShadowNode;,Lcom/facebook/react/views/toolbar/ReactToolbarManager;,Lcom/facebook/react/views/text/ReactTextVie
wManager;}
>        at com.tencent.tinker.build.decoder.DexDiffDecoder.checkDexChange(DexDiffDecoder.java:512)
>        at com.tencent.tinker.build.decoder.DexDiffDecoder.onAllPatchesEnd(DexDiffDecoder.java:228)
>        ... 92 more                   

稍后我会将新旧两个apk发到你的gmail邮箱，辛苦了。

**Comment by shwenzhang** [comment]
please try wit v1.6.2

**Comment by PeiDongHan** [comment]
@shwenzhang 验证过了，没有问题了，给力！

**Comment by ZhouBey** [comment]
1.9.2 又出现了这个问题
