### ISSUE TITLE
命令行工具怎么获得

### ISSUE THREAD

**Issue by ryffic** [Tencent/tinker#816]
命令行工具怎么获得

**Comment by tomystang** [comment]
通过命令行在tinker工程根目录执行gradlew :tinker-build:tinker-patch-cli:buildTinkerSdk，或通过Android Studio执行tinker-build -> tinker-patch-cli分组下的buildTinkerSdk，执行完成后在tinker工程根目录的buildSdk/build目录下就能找到以tinker-patch-cli-版本号.jar命名的命令行工具了。
