### ISSUE TITLE
apk 无法安装 Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

### ISSUE THREAD

**Issue by mylhyz** [Tencent/tinker#820]
使用 Tinker 1.9.2 版本，发现如下情况：

在构建补丁包的时候，同时打出的安装包在某些设备上（4.x的设备出现的概率较大，可通过mumu模拟器稳定复现）无法安装，安装报错`Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]`

经排查，定位到原因为 Manifest 中某 provider 的 `android:authorities` 属性被定义成如下情况`android:authorities="@string/xxx"` 导致，通过将`@stirng/xxx`改为硬编码字符串类似`com.package.name.provider`解决。

但由于仅在构建补丁情况下出现，原因未知，希望能帮忙看一下。

已浏览过相关ISSUE，但考虑到可能问题原因不一致，因此重开此issue进行反馈。

**Comment by tomystang** [comment]
很奇怪，我直接手动构造一个authorities不是硬编码的apk在mumu模拟器上也能复现，确定这个问题真的只在开启了tinker的情况下才会发生？
