### ISSUE TITLE
Error:Failed to complete Gradle execution. 

### ISSUE THREAD

**Issue by xiaoxiong123** [Tencent/tinker#828]
麻烦问一下tinker配置完成后，使用mac电脑运行tinker->tinkerPatchDebug后报出一下错误（win系统可以运行）
Error:Failed to complete Gradle execution.

Cause:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

**Comment by yezhiren1991** [comment]
@xiaoxiong123 麻烦问一下，问题解决了吗

**Comment by Liar1995** [comment]
@yezhiren1991 麻烦问一下，问题解决了吗

**Comment by wlong800** [comment]
同样遇到
Information:Gradle tasks [tinkerPatchAllFlavorRelease]
Error:Failed to complete Gradle execution.

Cause:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
Warning:okio.DeflaterSink: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
Warning:okio.Okio: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.Binding
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.NamingEnumeration
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.NamingException
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.directory.Attribute
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.directory.Attributes
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.directory.DirContext
Warning:org.bouncycastle.cert.dane.fetcher.JndiDANEFetcherFactory$1: can't find referenced class javax.naming.directory.InitialDirContext
