### ISSUE TITLE
请问有适配兼容DexGuard的计划吗？

### ISSUE THREAD

**Issue by liufsd** [Tencent/tinker#829]
```
异常类型：app运行时异常/编译异常

tinker版本：如:1.9.6

gradle版本：2.14.1

是否使用热更新SDK： tinker

系统：如:Mac

```

类似的问题：
[dexguard](https://github.com/Tencent/tinker/issues/676)
[buildTinkerPatchRelease FAILURE](https://github.com/Tencent/tinker/issues/827)

debug 可以打出来补丁，因为没有混淆，release启用了dexguard混淆，就失败了的。

**Comment by tomystang** [comment]
暂时没有，适配037和038格式的新dex的优先级要高一些。
