### ISSUE TITLE
提示热更新成功，但是手机上热更新没生效

### ISSUE THREAD

**Issue by iamupgirl** [Tencent/tinker#832]
异常类型：app运行时异常

手机型号：Google Pixel 2

手机系统版本：Android 8.1 (如是编译异常，则可以不填)

tinker版本：如:1.9.6

gradle版本：如:4.4-rc-3

是否使用热更新SDK：TinkerPatch SDK

系统：Windows

日志：
05-07 10:26:24.121 2382-2382/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:6053
05-07 10:26:24.126 2382-2382/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
05-07 10:26:24.131 2382-2382/? I/Tinker.SamplePatchListener: get platform:all
05-07 10:26:24.131 2382-2382/? I/Tinker.TinkerPatchService: run patch service by job scheduler.
05-07 10:26:24.149 1116-2677/? I/ActivityManager: Start proc 4172:com.gzshili.forestpatrol:patch/u0a228 for service com.gzshili.forestpatrol/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner
05-07 10:26:24.201 4172-4172/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
05-07 10:26:24.202 4172-4172/? D/Tinker.DefaultAppLike: onBaseContextAttached:
05-07 10:26:24.206 4172-4172/? I/Tinker.SamplePatchListener: application maxMemory:192
05-07 10:26:24.207 4172-4172/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.gzshili.forestpatrol/tinker
05-07 10:26:24.208 4172-4172/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.6
05-07 10:26:24.208 4172-4172/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.gzshili.forestpatrol:patch, main process:false, systemOTA:false, fingerPrint:google/taimen/taimen:8.1.0/OPM2.171019.029/4657601:user/release-keys, oatDir:null, useInterpretMode:false
05-07 10:26:24.208 4172-4172/? W/Tinker.TinkerLoadResult: tinker is disable, just return
05-07 10:26:24.208 4172-4172/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.gzshili.forestpatrol/tinker, code: -1, cost: 2ms
05-07 10:26:24.208 4172-4172/? W/Tinker.Tinker: tinker load fail!
05-07 10:26:24.208 4172-4172/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
05-07 10:26:24.208 4172-4172/? D/Tinker.DefaultAppLike: onCreate
05-07 10:26:24.208 4172-4172/? D/Tinker.DefaultAppLike: onCreate
05-07 10:26:24.279 4172-4172/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
05-07 10:26:24.282 4172-4208/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
05-07 10:26:24.309 4172-4208/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch_signed_7zip.apk to /data/user/0/app.package.name/tinker_temp/temp.apk
05-07 10:26:24.466 4172-4208/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:4425a5a6ab65cfcd7c2088ba3d2cd1a6
05-07 10:26:24.468 4172-4208/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/app.package.name/tinker/patch.info (No such file or directory)
05-07 10:26:24.469 4172-4208/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/app.package.name/tinker/patch.info (No such file or directory)
05-07 10:26:24.469 4172-4208/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/app.package.name/tinker/patch-4425a5a6
05-07 10:26:24.470 4172-4208/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/patch_signed_7zip.apk size: 6053, dest file: /data/user/0/app.package.name/tinker/patch-4425a5a6/patch-4425a5a6.apk size:6053
05-07 10:26:31.907 4172-4208/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/classes.dex.jar, size: 3742296, use time: 7435
05-07 10:26:31.908 4172-4208/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/classes2.dex.jar
05-07 10:26:32.452 4172-4208/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
05-07 10:26:32.490 4172-4208/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/test.dex.jar
05-07 10:26:32.492 4172-4208/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
05-07 10:26:32.729 4172-4208/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/classes2.dex.jar
05-07 10:26:32.730 4172-4208/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/test.dex.jar
05-07 10:26:32.730 4172-4208/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/classes.dex.jar
05-07 10:26:32.735 4172-4208/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/tinker_classN.apk, result: true, size: 4607957, use: 242ms
05-07 10:26:32.736 4172-4208/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
05-07 10:26:32.737 4172-4208/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/app.package.name/tinker/patch-4425a5a6/odex/
05-07 10:26:32.738 4172-4208/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/tinker_classN.apk, size: 4607957
05-07 10:26:38.134 4172-4208/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/tinker_classN.apk, opt file:/data/user/0/app.package.name/tinker/patch-4425a5a6/dex/oat/arm/tinker_classN.odex, opt file size: 192936, use time 5395
05-07 10:26:38.134 4172-4208/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:13663
05-07 10:26:38.134 4172-4208/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
05-07 10:26:38.134 4172-4208/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
05-07 10:26:38.135 4172-4208/? I/Tinker.DexDiffPatchInternal: raw dex count: 3, dex opt dex count: 1, final wait times: 90
05-07 10:26:38.141 4172-4208/? I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/app.package.name/tinker/patch-4425a5a6/dex/oat/arm/tinker_classN.odex, size 192936
05-07 10:26:38.141 4172-4208/? I/Tinker.DexDiffPatchInternal: check dex optimizer file format: tinker_classN.odex, size 192936
05-07 10:26:38.144 4172-4208/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/app.package.name/tinker/patch.info , oldVer:, newVer:4425a5a6ab65cfcd7c2088ba3d2cd1a6, fingerprint:google/taimen/taimen:8.1.0/OPM2.171019.029/4657601:user/release-keys, oatDir:odex
05-07 10:26:38.148 4172-4208/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
05-07 10:26:38.148 4172-4208/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/patch_signed_7zip.apk, success: true, cost: 13759
05-07 10:26:38.149 4172-4208/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/app.package.name/tinker_temp/temp.apk
05-07 10:26:38.161 2382-4381/? I/Tinker.SampleResultService: SampleResultService receive result: 
                                                             PatchResult: 
                                                             isSuccess:true
                                                             rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
                                                             costTime:13759
                                                             patchVersion:4425a5a6ab65cfcd7c2088ba3d2cd1a6
05-07 10:26:38.163 2382-4381/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /storage/emulated/0/patch_signed_7zip.apk
05-07 10:26:38.163 2382-4381/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/patch_signed_7zip.apk
05-07 10:26:38.164 2382-4381/? I/Tinker.SampleResultService: tinker wait screen to restart process

**Comment by wangzheshaoye00** [comment]
这个是怎么解决的？我的vivo手机也是8.1系统，补丁包下发成功了，也不生效

**Comment by wangzheshaoye00** [comment]
哦。升级到1.9.8版本就生效了
