### ISSUE TITLE
OPPO手机上，安装热修复的版本运行一段时间后，再次打开出现必现崩溃

### ISSUE THREAD

**Issue by wstczlt** [Tencent/tinker#835]
异常类型：app运行时异常

手机型号：OPPO R11

手机系统版本：如:Android 7.1

tinker版本：如:1.9.6

是否使用热更新SDK： 无

系统：如:Mac

堆栈/日志：
异常logcat：
05-09 10:15:30.684  1627  2936 D ActivityManager: cleanUpApplicationRecord -- 24780
05-09 10:15:30.688  1627  1627 I OppoPhoneWindowManager: KeyLockModeReceiver KeyLockMode: 0 ProcessName: com.smile.gifmaker:messagesdk
05-09 10:15:30.704 24803 24803 W System  : ClassLoader referenced unknown path:
05-09 10:15:30.740 24803 24803 I art     : Starting a blocking GC AddRemoveAppImageSpace
05-09 10:15:30.742 24803 24803 I art     : Failed to add image file Failed to flatten class loader hierarchy 'Unknown class loader type com.tencent.tinker.loader.AndroidNClassLoader'
05-09 10:15:30.742 24803 24803 I art     : Starting a blocking GC AddRemoveAppImageSpace
05-09 10:15:30.743 24803 24803 W System  : ClassLoader referenced unknown path:
05-09 10:15:30.771 24704 24848 E linker  : library "/system/lib64/libc.so" ("/system/lib64/libc.so") needed or dlopened by "/data/app/com.smile.gifmaker-1/lib/arm/libdu.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.smile.gifmaker-1/lib/arm:/system/fake-libs:/data/app/com.smile.gifmaker-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.smile.gifmaker"]
05-09 10:15:30.777 24803 24803 I art     : Starting a blocking GC AddRemoveAppImageSpace
05-09 10:15:30.785 24803 24803 W System  : ClassLoader referenced unknown path: /data/user/0/com.smile.gifmaker/tinker/patch-11543623/dex/tinker_classN.apk
05-09 10:15:30.790 24803 24803 D AndroidRuntime: Shutting down VM
05-09 10:15:30.793 24803 24803 E AndroidRuntime: FATAL EXCEPTION: main
05-09 10:15:30.793 24803 24803 E AndroidRuntime: Process: com.smile.gifmaker:pushservice, PID: 24803
05-09 10:15:30.793 24803 24803 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.yxcorp.gifshow.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:853)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5710)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:185)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6522)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(SourceFile:114)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(SourceFile:120)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:133)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:148)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.Application.attach(Application.java:198)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:993)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:847)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	... 9 more
05-09 10:15:30.793 24803 24803 E AndroidRuntime: Caused by: java.lang.ClassCastException: com.yxcorp.gifshow.App$AppLike cannot be cast to com.tencent.tinker.loader.app.ApplicationLike
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(SourceFile:111)
05-09 10:15:30.793 24803 24803 E AndroidRuntime: 	... 16 more
05-09 10:15:30.797  1627  1638 W ActivityManager: Process com.smile.gifmaker has crashed too many times: killing!
05-09 10:15:30.797  1627  1638 I ActivityManager: Killing 24803:com.smile.gifmaker:pushservice/u0a417 (adj 0): crash

追踪其中的‘‘Failed to add image file Failed to flatten class loader hierarchy 'Unknown class loader type com.tencent.tinker.loader.AndroidNClassLoader'’’，找到系统源码：https://android.googlesource.com/platform/art/+/master/runtime/class_linker.cc，其中
![image](https://user-images.githubusercontent.com/5256222/39795527-354c1918-5383-11e8-9da7-f851725d925b.png)
这段似乎判断了classloader的类型必须是PathClassLoader，但是如果是这样那么应该是所有场景都crash才对，但是现象是隔了一段时间再启动的时候才出现crash，这个很奇怪。

求助。

**Comment by wstczlt** [comment]
Caused by: java.lang.ClassCastException: com.yxcorp.gifshow.App$AppLike cannot be cast to com.tencent.tinker.loader.app.ApplicationLike

**Comment by wstczlt** [comment]
看各种现象很像是7.0的混合编译的问题，但是tinker的wiki上是解决了混合编译问题的，所以比较疑惑。还在查。

**Comment by wstczlt** [comment]
@tomystang 希望帮忙看一下这个问题，谢谢了，搞了两天了没解决。。

**Comment by wstczlt** [comment]
![image](https://user-images.githubusercontent.com/5256222/39866402-296b775a-5483-11e8-98c3-29e7722103ff.png)
全都是OPPO API25的机型。

**Comment by wstczlt** [comment]
ping。。。

**Comment by icemanstudy** [comment]
我用的还是1.9.2.暂未遇到.关注一下~

**Comment by wstczlt** [comment]
ping。。。。

**Comment by tomystang** [comment]
@wstczlt 
你的AndroidManifest.xml里配置的Application类是这个吗：com.yxcorp.gifshow.App
估计是你的XXLike类作为Application的内部类，导致profiling jit之后XXLike的ClassLoader信息跟XXLike的父类的信息不一致的原因，所以才会一开始没事，过一阵子就挂了。
你试试把XXLike类独立出来，你自己的App类用反射创建出XXLike类，创建的时候ClassLoader指定成App类的classloader，然后模仿tinker里的TinkerApplication把App类的生命周期代理到你的XXLike，看看还会不会有问题？

**Comment by wstczlt** [comment]
但是目前只在OPPO API25以上出现此问题，其它手机暂时没收集到这样的问题，很奇怪。

**Comment by wstczlt** [comment]
目前正在实验不用内部类的方式，看看线上灰度的情况，有结论再来更新。
