### ISSUE TITLE
Tinker.UpgradePatch: UpgradePatch tryPatch:onPatchPackageCheckFail

### ISSUE THREAD

**Issue by zzm123456** [Tencent/tinker#84]
这个错误是什么原因导致的啊

**Comment by shwenzhang** [comment]
请仔细阅读文档

**Comment by dodola** [comment]
@zzm123456 提供一下日志和错误码，或者根据错误码查一下对应的wiki号

**Comment by zzm123456** [comment]
@dodola 09-29 14:51:07.548 793-809/? E/NotificationService: Ignoring notification with icon==0: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null])
09-29 14:51:07.564 30331-30344/? E/Tinker.DexDiffPatchInternal: apk entry classes.dex crc is not equal, expect crc: 978100211, got crc: 143278357
09-29 14:51:07.572 30331-30344/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
