### ISSUE TITLE
 使用tinker加载了补丁包，再安装新版本的apk不能覆盖打开APP后没有新版的功能

### ISSUE THREAD

**Issue by liuglgithub** [Tencent/tinker#846]
异常类型：app运行时异常

手机型号：三星s7

手机系统版本：如:Android 7.0 

tinker版本：如:1.9.5

gradle版本：如:3.3

是否使用热更新SDK： 无

系统：如:Mac

堆栈/日志：
先加载补丁包，之后再安装新版本的apk，打开后发现新版的功能没有，就像新版本没安装一样。

**Comment by liuglgithub** [comment]
补丁包和新版本APP的TINKER_ID的值是一样的。导致不能新版不能覆盖老版本。

**Comment by manitozhang** [comment]
你好你的问题解决了吗,
