### ISSUE TITLE
编译执行gradlew tinkerpatchdebug报错

### ISSUE THREAD

**Issue by xinnian25** [Tencent/tinker#850]
异常类型： 编译异常

手机型号： 编译异常 

手机系统版本： 编译异常 

tinker版本：1.9.1

gradle版本：2.3.3

是否使用热更新SDK：是，TinkerPatch SDK

系统：Windows10

日志

![image](https://user-images.githubusercontent.com/10289114/40636268-cd8ca942-6330-11e8-8da8-370f34fcfbbb.png)

**Comment by sailor1861** [comment]
这个，感觉就是环境问题呀； Demo应该是可以正常编译的；

**Comment by icemanstudy** [comment]
task找不到.这是gradle配置问题.
