### ISSUE TITLE
Error:com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]

### ISSUE THREAD

**Issue by cfgnqk** [Tencent/tinker#851]
Error:com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
Error:com.tencent.tinker.android.dex.DexException: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
Error:com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]

**Comment by tomystang** [comment]
你用了jdk7或者8的新特性？tinker暂时还不支持这种新版本的dex，1.9.9版本会适配的。

**Comment by KomoriWu** [comment]
我现在是1.9.9 还是遇到了

**Comment by itxiaox** [comment]
我现在是1.9.13 还是遇到了

**Comment by qwerwen** [comment]
我现在是1.9.9 还是遇到了

**Comment by qwerwen** [comment]
Caused by: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 56, 0]这个是什么问题51，56， 0 @tomystang

**Comment by afunnyrainman** [comment]
Error:com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]  1.9.14.5 还是遇到了

**Comment by persiona** [comment]
Also met, why did not find the answer, who knows how to deal with

**Comment by persiona** [comment]
@tomystang  Who can help find the answer

**Comment by Jerricc** [comment]
1.9.14.21也遇到了
