### ISSUE TITLE
Tinker补丁加载成功,更新下个版本后该版本新增加功能没有加载.仍旧为版本更新前(加载过补丁后)的内容.必须卸载加载过补丁的app再安装新版才行

### ISSUE THREAD

**Issue by Young-Joe** [Tencent/tinker#853]
tinker版本：1.9.6

gradle版本：如:3.0

系统：如:Mac

问题描述:Tinker补丁加载成功,更新下个版本后该版本新增加功能没有加载.仍旧为版本更新前(加载过补丁后)的内容.必须卸载加载过补丁的app再安装新版才行.望解答.

**Comment by wangxuejiao00** [comment]
我遇得到和你一样的情况，什么原因？
