### ISSUE TITLE
补丁在小米Mix2S手机上无法应用成功，提示JobSchedulerService: Error executing JobStatus

### ISSUE THREAD

**Issue by byhook** [Tencent/tinker#855]
异常类型：app运行时异常

手机型号：小米Mix 2S

手机系统版本：Android 8.0.0

tinker版本：1.9.6

gradle版本：3.5

是否使用热更新SDK： bugly和tinker都有集成

系统：ubuntu16.0.4

堆栈/日志：
06-07 15:21:17.600 1349-1438/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{fd32882 u0 com.onzhou.tinker/.MainActivity t1297} time:25891586
06-07 15:21:23.747 22921-22921/? D/Tinker.TinkerManager: onDownloadSuccess.
06-07 15:21:23.748 22921-22921/? D/Tinker.TinkerManager: check if has new patch.
06-07 15:21:23.764 22921-22921/? D/Tinker.TinkerManager: has new patch.
06-07 15:21:23.765 22921-22921/? D/Tinker.TinkerManager: starting patch.
06-07 15:21:23.766 22921-22921/? I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.onzhou.tinker/app_tmpPatch/tmpPatch.apk, file size:4613
06-07 15:21:23.769 22921-22921/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
06-07 15:21:23.770 22921-22921/? I/Tinker.TinkerPatchListener: get platform:null
06-07 15:21:23.770 22921-22921/? I/Tinker.TinkerPatchService: run patch service by job scheduler.
06-07 15:21:23.773 1349-8388/? I/AutoStartManagerService: MIUILOG- Reject service :Intent { cmp=com.onzhou.tinker/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner } userId : 0 uid : 10238
06-07 15:21:23.773 1349-8388/? D/JobSchedulerService: Error executing JobStatus{c3c482e #u0a238/1 com.onzhou.tinker/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner u=0 s=10238 TIME=none:+3ms READY}
06-07 15:21:32.480 22982-22982/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/data/com.onzhou.tinker/.jiagu/classes.dex --oat-file=/data/data/com.onzhou.tinker/.jiagu/oat/arm64/classes.odex --inline-max-code-units=0 --compiler-filter=speed
06-07 15:22:17.382 1349-1427/? I/WindowManager: Failed to capture screenshot of Token{2e7f7cd ActivityRecord{fd32882 u0 com.onzhou.tinker/.MainActivity t1297}} appWin=Window{606dbfb u0 com.onzhou.tinker/com.onzhou.tinker.MainActivity} drawState=4
06-07 15:22:17.549 3403-3682/? D/PowerCheckerService: foreground, uid = 10238, app = com.onzhou.tinker
06-07 15:26:17.260 1349-1440/? D/ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{9cc0b93 com.onzhou.tinker} is now in focus and seems to be in full-screen mode
06-07 15:26:17.260 1349-1440/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.onzhou.tinker/com.onzhou.tinker.MainActivity/12
06-07 15:26:17.267 3063-3181/? I/WtProcessController: MOVE TO FOREGROUND: com.onzhou.tinker 10238
06-07 15:26:17.267 3063-3181/? I/WtProcessController: FOREGROUND INFO: name=com.onzhou.tinker uid=10238 pid=22921 TaskId:1297
06-07 15:26:17.330 1349-1429/? I/WindowManager: Waiting for drawn Window{606dbfb u0 com.onzhou.tinker/com.onzhou.tinker.MainActivity}: removed=false visible=true mHasSurface=true drawState=1
06-07 15:26:17.331 1349-1821/? I/WindowManager: Waiting for drawn Window{606dbfb u0 com.onzhou.tinker/com.onzhou.tinker.MainActivity}: removed=false visible=true mHasSurface=true drawState=1
06-07 15:26:17.334 1349-1821/? I/WindowManager: Waiting for drawn Window{606dbfb u0 com.onzhou.tinker/com.onzhou.tinker.MainActivity}: removed=false visible=true mHasSurface=true drawState=3
06-07 15:26:17.334 1349-1821/? I/WindowManager: Waiting for drawn Window{606dbfb u0 com.onzhou.tinker/com.onzhou.tinker.MainActivity}: removed=false visible=true mHasSurface=true drawState=4
06-07 15:26:17.334 1349-1821/? D/WindowManager: Window drawn win=Window{606dbfb u0 com.onzhou.tinker/com.onzhou.tinker.MainActivity}
06-07 15:26:17.347 1349-1438/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{fd32882 u0 com.onzhou.tinker/.MainActivity t1297} time:26191333
06-07 15:26:17.364 3403-3682/? D/PowerCheckerService: foreground, uid = 10238, app = com.onzhou.tinker
06-07 15:26:19.424 3063-3181/? I/StatusController: Last foreground:com.onzhou.tinker uid:10238 Current foreground:com.miui.home uid:10029
06-07 15:26:19.432 22921-22921/? D/Tinker.DefaultAppLike: onTrimMemory level:20

**Comment by icemanstudy** [comment]
好像和自启动权限有关吧.你看看,已经有人提出过issue了.
https://github.com/Tencent/tinker/issues/844

**Comment by RuanXiaoHui** [comment]
回归到1.9.2的版本试试，我目前使用的是降级这种方案

**Comment by tomystang** [comment]
对的，这是miui把JobScheduler统一禁用掉了的问题，这周有个尝试解决这个问题的新版本在灰度了，预计6月22号发。
