### ISSUE TITLE
需要等待1分钟才会自动关闭进程，补丁生效，是否公司项目太大导致？

### ISSUE THREAD

**Issue by Klay-11** [Tencent/tinker#856]
异常类型：补丁生效等待时间过长
手机型号：OPPOR9plus
手机系统版本：Android 6.0
tinker版本：1.9.5
gradle版本：3.1.2
是否使用热更新SDK： 否
系统：window7

问题详情：
点击加载补丁后执行TinkerInstaller.onReceiveUpgradePatch(getApplicationContext(), path);
app并没有自动关闭，而是差不多过了1分钟以后，才会自动关闭（我理解为以上代码加载补丁生效）
是否因为我司项目比较大的原因？有42M

**Comment by icemanstudy** [comment]
以oppo r9 plus的配置来说,1分钟很正常.
因为你调用onReceiveUpgradePatch方法以后,经历了dex合成和dex2oat两个步骤.这是很耗时的.哪有补丁一加载立马生效的~~~

**Comment by Klay-11** [comment]
好的，谢谢你的回复. 解决了我的疑惑. 
我还以为是自己集成的时候哪里配置出了问题，看来是正常情况. 
因为官方Demo几乎是直接关了进程就可以更新，所以对比下来我以为没有执行热修复.
