### ISSUE TITLE
Logo Proposal: Tinker

### ISSUE THREAD

**Issue by baranpirincal** [Tencent/tinker#862]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by tomystang** [comment]
Thank you for your kindness. In fact we had a logo designed by our team and used for long in the internal repo. Due to our carelessness, the logo was not placed on the github repo. We will fix it soon.

**Comment by baranpirincal** [comment]
You're welcome,

Have a nice day!
