### ISSUE TITLE
apply plugin所处位置的疑惑

### ISSUE THREAD

**Issue by qiangxi** [Tencent/tinker#864]
在分析源码时，看到aosp-dexutils的build.gradle中，`apply plugin`放在文件底部，所以希望能解答一下 `apply plugin`放在文件的顶部或底部的区别是什么？有什么作用？万分感谢！！！
```
apply plugin: 'java'

[compileJava, compileTestJava, javadoc]*.options*.encoding = 'UTF-8'

version rootProject.ext.VERSION_NAME
group rootProject.ext.GROUP

task buildTinkerSdk(type: Copy, dependsOn: [build]) {
    group = "tinker"
    from('build/libs') {
        include '*.jar'
        exclude '*javadoc.jar'
        exclude '*-sources.jar'
    }
    into(rootProject.file("buildSdk/android"))
}

apply from: rootProject.file('gradle/java-artifacts.gradle')
apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
```

**Comment by tomystang** [comment]
这里apply from你理解成include就好了，相当于把被apply的那个gradle文件复制到这句话所在的地方。所以apply from的位置有没有影响就看被apply的文件有没有依赖一些必须先apply或者config的插件了。

**Comment by qiangxi** [comment]
明白了，不过还有一点疑问就是`apply plugin`的放置位置是否与`apply from`类似？

**Comment by tomystang** [comment]
只是类似哇，apply plugin是先load plugin的入口类，然后去调用入口类的apply方法，其实还是有点区别的。可以参考这个链接下的回答：
https://stackoverflow.com/questions/29378249/difference-apply-from-vs-apply-plugin

**Comment by qiangxi** [comment]
哈，这个链接早前看过，从中明白了`apply plugin`与`apply from`的区别，但是没有介绍`apply plugin`不同位置的效果，结合你上面说的，除了`apply plugin`比`apply from`多了个“load plugin的入口类”这一步，二者应该差不多，都是加载相关extension和tasks到当前的build.gradle中，放置位置应该还是和是否依赖其他配置有关，我理解的对吗？

**Comment by tomystang** [comment]
嗯嗯，对的。

**Comment by qiangxi** [comment]
都搞清楚了，非常感谢，赞~
