### ISSUE TITLE
android 8.0 加载失败parseTinkerResult loadCode:-1

### ISSUE THREAD

**Issue by lanqi-x** [Tencent/tinker#865]
异常类型：app运行时异常

手机型号：Nexus 4

手机系统版本：Android 8.0 

tinker版本：如:1.9.6

gradle版本：如:2.10

是否使用热更新SDK： 否

系统：如:Mac

堆栈/日志：
 I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/remind/zaihu/patch.rmfix, file size:4379
 W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
 I/Tinker.TinkerPatchService: run patch service by job scheduler.
:patch W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
:patch I/Tinker.SamplePatchListener: application maxMemory:256
:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.remind.zaihu/tinker
:patch I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.6
:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.remind.zaihu:patch, main process:false, systemOTA:false, fingerPrint:google/sdk_gphone_x86/generic_x86:8.0.0/OSR1.180418.003/4741120:userdebug/dev-keys, oatDir:null, useInterpretMode:false
:patch W/Tinker.TinkerLoadResult: tinker is disable, just return
:patch I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.remind.zaihu/tinker, code: -1, cost: 2ms
:patch W/Tinker.Tinker: tinker load fail!
:patch I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return

**Comment by tomystang** [comment]
额，这个log还不够全，正常情况下如果没加载补丁，启动的时候也会打-1的错误码的，看看patch进程在你调了onPatchReceived方法之后有没有启动，启动之后打了哪些log吧。

**Comment by lanqi-x** [comment]
额，这个就是调用了onPatchReceived方法之后的报错呢！即调用了TinkerInstaller.onReceiveUpgradePatch方法，日志的第一句就是补丁文件的路径及文件大小，在输出这个日志后就没反应了，如果此时再调用TinkerInstaller.onReceiveUpgradePatch方法就会报code为-3的错误，所以我也看不出是什么错误，在8.0以下是正常的

**Comment by Srain-z** [comment]
@lanqi-x  请问你解决了么？

**Comment by lanqi-x** [comment]
木有

**Comment by Srain-z** [comment]
@lanqi-x 更新tinker 1.9.8 就好了

**Comment by lanqi-x** [comment]
@Srain-z 好的，我试下，谢谢你

**Comment by lwmukx1208** [comment]
我更新了1.9.8还是报这个错误，8.1系统
