### ISSUE TITLE
热更新后部分手机出现SavedState的类型转换异常

### ISSUE THREAD

**Issue by lsp9876** [Tencent/tinker#866]
## Issue/提问须知

异常类型：app运行时异常

手机型号：各机型均有复现

手机系统版本：各版本均有
tinker版本：1.9.1

gradle版本:3.0.1

是否使用热更新SDK： Bugly SDK

系统：:Mac

堆栈/日志：
日志1：
java.lang.RuntimeException:Unable to start activity ComponentInfo{****login.LoginActivity}: java.lang.ClassCastException: android.view.View$BaseSavedState cannot be cast to android.widget.CompoundButton$SavedState

日志2：
ava.lang.RuntimeException:Unable to start activity ComponentInfo{*****h.activity.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.support.v4.view.ViewPager$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/ll_mine_order. Make sure other views do not use the same id.

出现问的的页面一般含有多个fragment，不同fragment中有id相同的控件，热更新之前一直没有出现这个问题，热更新后下发了888个用户，其中68人出现此问题，就立即终止了，本地使用7部真机测试未能复现

**Comment by tomystang** [comment]
上周调试了一下，怀疑issue里提的class cast exception都跟主进程和其他进程之间加载补丁的状态不一致有关，这周我做了点修改，预计6月22号会发个新版本，到时请尝试一下看看问题会不会消失吧。

**Comment by lsp9876** [comment]
好的，之前用公式邮箱向jspatch@qq.com发过相同的问题，如果重复，还请忽略

**Comment by VinaChiong** [comment]
你好，请问这个问题已经修复了吗？
