### ISSUE TITLE
开启AAPT2后编译报错

### ISSUE THREAD

**Issue by ToryCrox** [Tencent/tinker#869]
异常类型：编译异常
tinker版本：1.9.6
gradle版本：3.0.1
是否使用热更新SDK： Bugly SDK
系统：Mac
堆栈/日志：
/build/intermediates/res/merged/debug/values/ids.xml: error: uncompiled XML file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

经分析发现生成的build/intermediates/tinker_intermediates/public.xml和idx.xml没有内容，而且aapt2不支持public.xml形式的资源固定方式。要问一下tinker做aapt2方面的适配吗？是不是一定要关掉aapt2？

**Comment by tomystang** [comment]
tinker确实还不支持aapt2，所以要关掉aapt2才行。这个在下个版本里会考虑适配的。
