### ISSUE TITLE
app使用1.9.6升级使用1.9.8后安装启动崩溃

### ISSUE THREAD

**Issue by afunnyrainman** [Tencent/tinker#875]
异常类型： TinkerPatch.init  初始化崩溃
手机型号：如:OPPO R9S

手机系统版本 Android 6.0.1,level 23

tinker版本：如:1.9.6  app升级成1.9.8 

gradle版本：3.0.1

是否使用热更新SDK：  TinkerPatch SDK

系统：如:android

堆栈/日志：

app先使用的1.9.6，然后有过上传补丁,今天把tinker升级成了1.9.8启动直接崩溃。然后错误手机是 TinkerPatch.init这一行崩溃。
No static method k(Landroid/content/Context;)Ljava/lang/String; in class Lcom/damai/bixin/interfaces/nm; or its super classes (declaration of 'com.damai.bixin.interfaces.nm' appears in /data/user/0/com.example.dng.Li/tinker/patch-5e525049/dex/tinker_classN.apk)
com.damai.bixin.interfaces.nm.d(TinkerServiceInternals.java:116)

**Comment by afunnyrainman** [comment]
app版本升级之后

**Comment by tomystang** [comment]
不能对1.9.6的base包打1.9.8的包产生的patch的，base包和patch包使用的tinker版本必须严格一致才行。
