### ISSUE TITLE
编译失败：First type is not attr!  （launcher:processSbox3DebugResources FAILED）

### ISSUE THREAD

**Issue by nelon1990** [Tencent/tinker#878]
异常类型：编译异常

tinker版本：1.9.1

android build tools：com.android.tools.build:gradle:3.1.3

gradle版本：4.4

是否使用热更新SDK： TinkerPatch SDK

系统：Window 10

命令行执行：gradlew --stacktrace --debug assemble

发生错误：
>![image](https://user-images.githubusercontent.com/16273800/42409477-7477a4f0-820d-11e8-9ca3-9423a1554087.png)

stacktrace:
>![image](https://user-images.githubusercontent.com/16273800/42409472-6a7c228c-820d-11e8-9bce-2b89ef82840a.png)

gradle:
由于基准包及文件是从网络中下载，所以修改了bakapp/mapping/resource-mapping文件的获取方式，目前能够确定文件是正确下载并被引用，其中，mapping文件为空文件，没有混淆
assemble是在tinker打开的情况下进行的，工程在没有集成tinker或继承了tinker但没有多flavor时，是可以正常编译的。

![image](https://user-images.githubusercontent.com/16273800/42409564-9a4ba86a-820e-11e8-99c0-210aea0f42e9.png)
![image](https://user-images.githubusercontent.com/16273800/42409561-94489158-820e-11e8-8fdd-58ba34f7ce55.png)
![image](https://user-images.githubusercontent.com/16273800/42409553-76a68862-820e-11e8-98c5-5779ff6f3121.png)
![image](https://user-images.githubusercontent.com/16273800/42409547-52eb3bd4-820e-11e8-9370-de4542c399db.png)
![image](https://user-images.githubusercontent.com/16273800/42409549-589ff09c-820e-11e8-8f68-4d944739022b.png)

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
