### ISSUE TITLE
使用tools:text="@tools:sample/full_names"打补丁失败

### ISSUE THREAD

**Issue by DarkSherlock** [Tencent/tinker#879]
我的一个recyclerview的item布局中的一个textview 使用了tools:text="@tools:sample/full_names"导致打基准包能正常通过编译，补丁包却不行。
 <TextView
            android:id="@+id/tv_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/global_text1_color"
            android:textSize="13sp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/iv_header"
            **tools:text="@tools:sample/full_names"**/>
```
异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：com.tencent.bugly:tinker-support:1.1.2

gradle版本：3.1.3

是否使用热更新SDK： Bugly SDK

系统：win7

堆栈/日志：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:tinkerProcessReleaseResourceId'.
> com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: Invalid reference '@tools:sample/full_names' in 'E:\aikaola\answerquestions\app\build\intermediates\res\merged\release\layout\item_super_class_student_rv.xml'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by mrrobot97** [comment]
同上，不识别Android Studio提供的预览资源@tools:sample/avatars

异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：1.9.1

gradle版本：3.1.3

是否使用热更新SDK： 否

系统：macOs

堆栈/日志：
Execution failed for task ':applive:tinkerProcessDebugResourceId'.
17:59:05.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: Invalid reference '@tools:sample/avatars' in '/Users/hikigaya/walilive/applive/build/intermediates/res/merged/debug/layout/michannel_video_collection_layout.xml'

**Comment by tuzhao** [comment]
同上，不识别Android Studio提供的预览资源@tools:sample/avatars
异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：1.9.6

gradle版本：3.1.4

是否使用热更新SDK： 是 用的bugly

系统：macOs

堆栈/日志：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:tinkerProcessGoogleReleaseResourceId'.
> com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: Invalid reference '@tools:sample/avatars' in '/Users/******/app/build/intermediates/res/merged/google/release/layout-land/instabug_lyt_notification.xml'

**Comment by tomystang** [comment]
已知问题，下个版本修复。
