### ISSUE TITLE
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by duoduo2012** [Tencent/tinker#881]
我在三星，oppo手机上出现了类似的pre-verify的问题，系统是4.4和4.3。但是在华为手机上没有问题，系统是6.0,8.0。
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

.MyApplication.onCreate(MyApplication.java:60)
--
2 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
3 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4346)
4 android.app.ActivityThread.access$1500(ActivityThread.java:135)
5 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
6 android.os.Handler.dispatchMessage(Handler.java:102)
7 android.os.Looper.loop(Looper.java:136)
8 android.app.ActivityThread.main(ActivityThread.java:5019)
9 java.lang.reflect.Method.invokeNative(Native Method)
10 java.lang.reflect.Method.invoke(Method.java:515)
11 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
13 dalvik.system.NativeStart.main(Native Method)

**Comment by RuanXiaoHui** [comment]
我这边也遇到了，用的Tinker版本是1.9.8，compileSdkVersion，buildToolsVersion都是26+，然后在5.0+没有问题，在4.3、4.4补丁都提示应用成功，但是引用启动就崩溃，报错问题是：Class ref in pre-verified class resolved to unexpected implementation，并且下面日志提示一大堆类以及资源找不到。

**Comment by heiheiwanne** [comment]
我也有遇到这个问题，1.9.8 , 4.4小米手机，
一直报Class ref in pre-verified class resolved to unexpected implementation，我的是说自定义view的自定义属性找不到

**Comment by heiheiwanne** [comment]
@RuanXiaoHui 你那边问题解决了吗

**Comment by RuanXiaoHui** [comment]
@heiheiwanne   我这边5.0以下做了限制，目前就是直接将5.0以下的手机拉入黑名单  不让去走下载加载的逻辑

**Comment by heiheiwanne** [comment]
有没有大佬来解决下这个问题啊，我看最近好几个人都出现这种问题了

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
