### ISSUE TITLE
Application多层继承运行时crash

### ISSUE THREAD

**Issue by hzy00** [Tencent/tinker#882]
异常类型：app运行时异常

手机型号：华为Mate8

手机系统版本：7.0

tinker版本：1.9.8

gradle版本：2.1.3

是否使用热更新SDK： 否

系统：Mac

堆栈/日志：     Caused by: java.lang.ClassCastException: me.andpay.apos.app.DebugAposApp cannot be cast to me.andpay.timobileframework.mvc.support.TiApplication

application采用了多层继承的方式，DebugAposApp为manifest中声明的application，TiApplication为其父类，Activity中调用了（TiApplication）getApplication(),类型转换时crash， 该patch包在htc、vivo、乐视等手机上都修复成功了，唯独在这台华为手机上crash
gradle配置loader中也有把相关的application类都放在里面

tinker相关日志
`
07-20 11:44:46.504 20273-20273/? W/Tinker.Tinker: tinker patch directory: /data/user/0/me.andpay.apos/tinker
07-20 11:44:46.505 20273-20273/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
07-20 11:44:46.505 20273-20273/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.8
07-20 11:44:46.506 20273-20273/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:me.andpay.apos:patch, main process:false, systemOTA:false, fingerPrint:HUAWEI/NXT-TL00/HWNXT:7.0/HUAWEINXT-TL00/C01B589:user/release-keys, oatDir:null, useInterpretMode:false
07-20 11:44:46.506 20273-20273/? W/Tinker.TinkerLoadResult: tinker is disable, just return
07-20 11:44:46.506 20273-20273/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/me.andpay.apos/tinker, code: -1, cost: 0ms
07-20 11:44:46.506 20273-20273/? W/Tinker.Tinker: tinker load fail!
07-20 11:44:46.509 20273-20273/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch.apk, code: -4
07-20 11:44:46.612 20273-20353/? I/Tinker.TinkerPatchService: try to increase patch process priority
07-20 11:44:46.627 20273-20353/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
07-20 11:44:46.628 20273-20353/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/patch.apk to /data/user/0/me.andpay.apos/tinker_temp/temp.apk
07-20 11:44:46.662 20273-20353/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:acafd9183221e969932cdf2b69e9ab73
07-20 11:44:46.663 20273-20353/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/me.andpay.apos/tinker/patch.info (No such file or directory)
    read property failed, e:java.io.FileNotFoundException: /data/user/0/me.andpay.apos/tinker/patch.info (No such file or directory)
07-20 11:44:46.663 20273-20353/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/me.andpay.apos/tinker/patch-acafd918
07-20 11:44:46.664 20273-20353/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/patch.apk size: 24193, dest file: /data/user/0/me.andpay.apos/tinker/patch-acafd918/patch-acafd918.apk size:24193
07-20 11:45:12.321 20273-20353/me.andpay.apos:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/classes.dex.jar, size: 3462950, use time: 25655
07-20 11:45:12.321 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/classes2.dex.jar
07-20 11:45:13.624 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
07-20 11:45:34.306 20273-20353/me.andpay.apos:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/classes3.dex.jar, size: 2673953, use time: 20577
07-20 11:45:34.306 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/test.dex.jar
07-20 11:45:34.307 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
07-20 11:45:34.599 20273-20353/me.andpay.apos:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/classes.dex.jar
07-20 11:45:34.601 20273-20353/me.andpay.apos:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/classes2.dex.jar
07-20 11:45:34.602 20273-20353/me.andpay.apos:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/classes3.dex.jar
07-20 11:45:34.603 20273-20353/me.andpay.apos:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/test.dex.jar
07-20 11:45:34.603 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/tinker_classN.apk, result: true, size: 10225783, use: 296ms
    legal files to do dexopt: [/data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/tinker_classN.apk]
07-20 11:45:34.604 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/me.andpay.apos/tinker/patch-acafd918/odex/
    start to parallel optimize dex /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/tinker_classN.apk, size: 10225783
07-20 11:45:59.490 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/me.andpay.apos/tinker/patch-acafd918/dex/tinker_classN.apk, opt file:/data/user/0/me.andpay.apos/tinker/patch-acafd918/odex/tinker_classN.dex, opt file size: 65270184, use time 24886
    recover dex result:true, cost:72826
07-20 11:45:59.491 20273-20353/me.andpay.apos:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
07-20 11:45:59.491 20273-20353/me.andpay.apos:patch W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
07-20 11:45:59.491 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: raw dex count: 4, dex opt dex count: 1, final wait times: 120
07-20 11:45:59.499 20273-20353/me.andpay.apos:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/me.andpay.apos/tinker/patch-acafd918/odex/tinker_classN.dex, size 65270184
    check dex optimizer file format: tinker_classN.dex, size 65270184
07-20 11:45:59.502 20273-20353/me.andpay.apos:patch I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/me.andpay.apos/tinker/patch.info , oldVer:, newVer:acafd9183221e969932cdf2b69e9ab73, fingerprint:HUAWEI/NXT-TL00/HWNXT:7.0/HUAWEINXT-TL00/C01B589:user/release-keys, oatDir:odex
07-20 11:45:59.505 20273-20353/me.andpay.apos:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
07-20 11:45:59.505 20273-20353/me.andpay.apos:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/patch.apk, success: true, cost: 72876
07-20 11:45:59.505 20273-20353/me.andpay.apos:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/me.andpay.apos/tinker_temp/temp.apk
`

**Comment by hwldzh** [comment]
请问修复了吗？我也遇到同样的问题

**Comment by tomystang** [comment]
ART内联导致的问题，可以尝试升级到1.9.14版本看看是否解决。
