### ISSUE TITLE
如果修改源码，让TinkerApplication继承自定义Application，怎么做？

### ISSUE THREAD

**Issue by blackberry2016** [Tencent/tinker#883]
如果修改源码，让TinkerApplication继承，自定义Application，是否可行？怎么做？

**Comment by Vegen** [comment]
@Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);
        //在这执行MultiDex
        MultiDex.install(base);
        //代理真正的ContextImpl
        app.attachBaseContext(base);
    }

这里的  app.attachBaseContext(base);  attachBaseContext是 protected 的，你是怎样做到的。

**Comment by android-notes** [comment]
你的 application重写这个方法，改成public   `protect  attachBaseContext`

**Comment by qianshengta** [comment]
@android-notes   你好 我最近遇到在Application中注册registerActivityLifecycleCallbacks失效的问题。找到原因应该是Application被反射了原因。所以现在打算试试你的这个方法。但是现在有两个问题想请教你。
第一：App和MyApplicationLike 哪个是要注册到AndroidManifest里的。
第二：MyApplicationLike 构造参数是什么？我现在是将MyApplicationLike 注册到AndroidManifest，
           但是在打基准包的时候报错，提示MyApplicationLike 必须要有一个默认的构造函数

**Comment by qianshengta** [comment]
Task :app:lintVitalRelease FAILED
D:\Android\Project\SubordinationProject\BuglyDemo\app\src\main\java\com\qian\buglydemo\MyApplicationLike.java:24: Error: This class should provide a default constructor (a public constructor with no arguments) (com.qian.buglydemo.MyApplicationLike) [Instantiatable]
//    public MyApplicationLike(Application application, int i, boolean b, long l, long l1, Intent intent) {
             ~~~~~~~~~~~~~~~~~

   Explanation for issues of type "Instantiatable":
   Activities, services, broadcast receivers etc. registered in the manifest
   file (or for custom views, in a layout file) must be "instantiatable" by
   the system, which means that the class must be public, it must have an
   empty public constructor, and if it's an inner class, it must be a static
   inner class.
@tomystang @android-notes

**Comment by qingmengbanxia** [comment]
在做鸿蒙混合开发，要求必须使用严格继承Application类或继承HarmonyApplication类，用目前这种 @android-notes 给出的方案导致打出的包在鸿蒙端使用时候有问题。
有没有让TinkerApplication继承HarmonyApplication的方案？
