### ISSUE TITLE
Tinker官方QQ技术交流群：377388954

### ISSUE THREAD

**Issue by shwenzhang** [Tencent/tinker#89]
为了方便大家更容易的接入Tinker或讨论相关技术，大家可加入QQ交流群377388954。为了方便大家交流，入群请注明姓名与公司等信息。
1. 在任何提问前，请仔细阅读好文档；
2. 希望可以创造互相帮助，互相分享的氛围。

![group](https://cloud.githubusercontent.com/assets/8335303/18943762/36879328-8654-11e6-96d5-3339d552cbd8.png)

**Comment by mrfluency** [comment]
赞 等待1.6.2

**Comment by hubangmao** [comment]
感谢 贵团队

**Comment by Ivan25640306** [comment]
請問驗證怎麼進去?
