### ISSUE TITLE
补丁包下载下来后，不安装

### ISSUE THREAD

**Issue by Huangzhe** [Tencent/tinker#891]
通过bugly来集成Tinker,下载补丁包后，不去自动安装，日志如下：
07-31 16:37:15.616 14736-14736/xx D/Tinker.TinkerManager: onDownloadSuccess.
    check if has new patch.
07-31 16:37:15.640 14736-14736/xx D/Tinker.TinkerManager: has new patch.
07-31 16:37:15.641 14736-14736/xx D/Tinker.TinkerManager: starting patch.
07-31 16:37:15.653 14736-14736/xx I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/xx/app_tmpPatch/tmpPatch.apk, file size:4427
07-31 16:37:15.660 14736-14736/xx W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
07-31 16:37:15.666 14736-14736/xx I/Tinker.TinkerPatchListener: get platform:null
07-31 16:37:15.667 14736-14736/xx I/Tinker.TinkerPatchService: run patch service by job scheduler.
07-31 16:37:15.669 14736-14736/xx E/Tinker.TinkerPatchService: start patch service fail, exception:java.lang.IllegalArgumentException: No such service ComponentInfo{xx/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner}

**Comment by earnking** [comment]
请问你解决了嘛，我的目前也是这个问题，是路径什么

**Comment by Huangzhe** [comment]
没有解决

**Comment by git930** [comment]
解决了吗？小米Mix2 也是补丁下载了，不安装

**Comment by angelaxiangxiang** [comment]
试试 tinker 1.9.8 版本

**Comment by tomystang** [comment]
exception:java.lang.IllegalArgumentException: No such service ComponentInfo{xx/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner

一般是bugly sdk和tinker sdk版本没对上导致服务缺失引起的，统一升级到bugly支持的最新版本即可。如果还有问题，可重开此issue。
