### ISSUE TITLE
在清单文件设置tinkerID依然tinkerId is not set!!!

### ISSUE THREAD

**Issue by shijia109** [Tencent/tinker#892]
看过文档说tinkerId设置有两种方式，一种gradle方式，也得用gradle打包，实测可以通过，一种在清单文件设置tinkerID，用jar包生成patch，我想用这种非方式，加了<meta-data android:name="TINKER_ID" android:value="tinker_id_b168b32" />，但是一直报tinkerId is not set!!!，注解方式生成的application也无法生成，是这种设置tinkerId的方式作废了，还是我集成步骤有问题？

**Comment by shijia109** [comment]
![qq 20180801183542](https://user-images.githubusercontent.com/11850630/43516981-bb4a57c0-9576-11e8-9a06-7b63b3fdb37c.png)

**Comment by twiceyuan** [comment]
测试在 `tinker-support.gradle` 文件中的 `tinkerSupport { enable = false }` 时也会提示 `Cause: tinkerId is not set!!!` 并同步失败，完整的 `tinker-support.gradle` 文件如下：

```groovy
apply plugin: 'com.tencent.bugly.tinker-support'

def bakPath = file("${buildDir}/bakApk/")

/**
 * 此处填写每次构建生成的基准包目录
 */
def baseApkDir = "app-0807-09-17-58"

/**
 * 对于插件各参数的详细解析请参考
 */
tinkerSupport {
    enable = false
    autoBackupApkDir = "${bakPath}"
    overrideTinkerPatchConfiguration = true
    baseApk = "${bakPath}/${baseApkDir}/app-release.apk"
    baseApkProguardMapping = "${bakPath}/${baseApkDir}/app-release-mapping.txt"
    baseApkResourceMapping = "${bakPath}/${baseApkDir}/app-release-R.txt"
    tinkerId = "base-1.0.1"
    enableProxyApplication = false
    supportHotplugComponent = true
}
```

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。

@shijia109 
cli工具可以在tinker工程里执行buildTinkerSdk这个task编译得到，另外你关闭tinker插件之后手动添加tinker id之后，可以用as查看一下编译出来的apk的AndroidManifest.xml里是否真的有你加进去的tinkerId，如果没有，说明tinker的编译时插件可能有bug，再重新提一个issue吧。

**Comment by hello-ring** [comment]
我也遇到这个问题，不能直接编译运行了
enable = false 插件关闭了 应该不管有没有设置tinkerid 都不能报这个错吧
