### ISSUE TITLE
AndroidNClassLoader怎么进行测试是否正常工作

### ISSUE THREAD

**Issue by NingSo** [Tencent/tinker#894]
```
异常类型：app运行时异常/编译异常

手机型号：一加5和Nexus6P

手机系统版本：8.1.0

tinker版本：1.9.1

gradle版本：3.1.3

是否使用热更新SDK： tinker源码

系统：如:Mac

堆栈/日志：
08-02 14:33:40.282 15482-15482/? I/AdkShell: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.liam.liamhotfix-In8Z7DumynXP3x0_d1lpjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.liam.liamhotfix-In8Z7DumynXP3x0_d1lpjg==/lib/arm64, /system/lib64, /system/vendor/lib64]]]
08-02 14:33:40.283 15482-15482/? W/System: ClassLoader referenced unknown path: 
08-02 14:33:40.284 15482-15482/? W/zygote64: Unsupported class loader
08-02 14:33:40.285 15482-15482/? W/zygote64: Skipping duplicate class check due to unsupported classloader
08-02 14:33:40.287 15482-15482/? W/zygote64: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
08-02 14:33:40.288 15482-15482/? W/zygote64: Skipping duplicate class check due to unsupported classloader
08-02 14:33:40.289 15482-15482/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.ak.dex.dex.AndroidNClassLoader[DexPathList[[dex file "/storage/emulated/0/patch_dex.dex", zip file "/data/app/com.liam.liamhotfix-In8Z7DumynXP3x0_d1lpjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.liam.liamhotfix-In8Z7DumynXP3x0_d1lpjg==/lib/arm64, /system/lib64, /system/vendor/lib64]]], dex size:1
```
在学习你们开源项目的时候，有深入看过《Android N混合编译与对热补丁影响解析》有以下两点疑问：
问题一：你们采取的方案是运行时替换PathClassLoader方案，然后注入了自定义的AndroidNClassLoader，但是我发现运行调试的时候，用8.1.0的手机，并没有走`AndroidNClassLoader`的`findClass`方法，调试热更的dex也没有被加入到`pathList`里面。
看上面的log信息有提醒日志
```
08-02 14:33:40.283 15482-15482/? W/System: ClassLoader referenced unknown path: 
08-02 14:33:40.284 15482-15482/? W/zygote64: Unsupported class loader
08-02 14:33:40.285 15482-15482/? W/zygote64: Skipping duplicate class check due to unsupported classloader
```
是否有影响？

问题二：
在考虑是否是因为AndroidNClassLoader不生效的角度，我在方法**AndroidNClassLoader#createAndroidNClassLoader**中注入了这两行代码之后就OK了，当然上面的日志依然是一样的，结果所有的满足api24之后的系统版本所有的都走了该自定义AndroidNClassLoader中的findClass，想问一下这样work之后是否有什么其他的影响还是你们开源的这个有遗漏这块
```
  final Field parentField = ShareReflectUtil.findField(originalClassLoader, "parent");
  parentField.set(originalClassLoader, androidNClassLoader);
```
🙏感谢大佬有空帮忙解答一下疑惑。

**Comment by tomystang** [comment]
日志是正常的，自定义的ClassLoader替换了默认ClassLoader之后都会打那几行log，除了会跳过duplicate class check之外暂时没发现啥副作用。

调试的时候findClass方法不一定都断得下来，具体原因我也没有仔细研究，求补充哇。你可以试试在AndroidNClassLoader的findClass里打log，只要不是application和loader类应该都会走这个findClass加载的。而且热更新的Dex肯定是注入进去了，你可以在MainActivity里直接打this.getClass().getClassLoader().toString()，应该是看得到的。

**Comment by FaustKwan** [comment]
我也遇到同样的问题，AndroidNClassLoader执行成功dex注入也成功，但MainActivity里this.getClass().getClassLoader().toString()输出的还是本来的PathClassLoader而不是AndroidNClassLoader

**Comment by NingSo** [comment]
参考我的问题二的写法 @FaustKwan 但是作者没有给我解惑。。😂

**Comment by FaustKwan** [comment]
@NingSo 谢谢回答。我的解读是AndroidNClassLoader构造时是作为一个PathClassLoader的儿子存在的，如果按照问题二的写法，则是把AndroidNClassLoader作为PathClassLoader的父亲存在了，好像不是原作者的意图，而且也会导致findClass死循环。（本人一个小白……）

**Comment by NingSo** [comment]
@FaustKwan 嗯，不至于死循环，只不过是替换掉了parent。所有想问作者这个问题啊。因为什么都不做的话按照源码走的话貌似不起作用了。

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭，如仍有疑问可重新开启此issue。
