### ISSUE TITLE
都要杀进程后才能生效吗？

### ISSUE THREAD

**Issue by anzyhui** [Tencent/tinker#90]
返回键退回到桌面，再进入，修复并不会生效，需要把进程杀了，再进入才有效。都是这样的吗？

**Comment by shwenzhang** [comment]
只要看看SampleResultService就知道原因了，Sample只是一个事例，大家还是要去看看代码的

**Comment by anzyhui** [comment]
谢谢，看了一下知道原因了，这边处理的是，在app在后台，以及屏幕熄灭的时候，都会杀掉进程，没有做返回桌面杀掉进程的处理，这个根据自身情况来自由发挥吧。
