### ISSUE TITLE
接入 DaggerAndroid 运行时报 xxxApplication does not implement dagger.android.HasActivityInjector

### ISSUE THREAD

**Issue by guanpj** [Tencent/tinker#900]
异常类型：app运行时异常

手机型号：Smartisan OD103(坚果Pro)

手机系统版本：Android 7.1.1

tinker版本：1.9.6

gradle版本：3.1.0

使用 BuglySdk

系统：windows

使用 DaggerAndroid 时需要在 BaseActivity 进行注入：AndroidInjection.inject(this); 
inject(Activity activity) 方法如下：
    public static void inject(Activity activity) {
    checkNotNull(activity, "activity");
    Application application = activity.getApplication();
    if (!(application instanceof HasActivityInjector)) {
      throw new RuntimeException(
          String.format(
              "%s does not implement %s",
              application.getClass().getCanonicalName(),
              HasActivityInjector.class.getCanonicalName()));
    }

    AndroidInjector<Activity> activityInjector =
        ((HasActivityInjector) application).activityInjector();
    checkNotNull(activityInjector, "%s.activityInjector() returned null", application.getClass());

    activityInjector.inject(activity);
  }
获取到的 TinkerApplication 没有实现 HasActivityInjector，用 TinkerApplication  实现了这个接口后发现 TinkerApplication  里面的逻辑是不会执行的，所以用不了 DaggerAndroid

**Comment by RobMastersToast** [comment]
Is there any update on this? I'm experiencing the same issue.

p.s. Apologies for replying in English! Feel free to continue replying in Chinese.

**Comment by blackberry2016** [comment]
@RobMastersToast You should write your own AndroidInjection instead of using dagger.android.AndroidInjection.

AndroidInjection2 .java
```
//   Dagger.INSTANCE is the key
public final class AndroidInjection2 {
    public static void inject(Activity activity) {
        checkNotNull(activity, "activity");
        AndroidInjector<Activity> activityInjector = Dagger.INSTANCE.activityInjector();
        activityInjector.inject(activity);
    }
}
``` 
 Dagger .java
```
public abstract class Dagger implements HasActivityInjector,
        HasSupportFragmentInjector,
        HasServiceInjector,
        HasBroadcastReceiverInjector,
        HasContentProviderInjector {
    public static Dagger INSTANCE;
}
```

**Comment by guanpj** [comment]
> @guanpj 重写你的注入过程，请参照以上代码片段。
你好，你的代码我看得不是很明白，你能说明一下具体的思路吗？

**Comment by guanpj** [comment]
@blackberry2016 你好，你的代码我看得不是很明白，你能说明一下具体的思路吗？

**Comment by guanpj** [comment]
@RobMastersToast I found a way to avoid this restraint by DaggerAndroid Lib, 
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        //AndroidInjection.inject(this);   old way to inject
        ReadhubApplicationLike.getInstance().activityInjector().inject(this); //this is new way
        super.onCreate(savedInstanceState);
        if (null != mPresenter) {
            mPresenter.onAttach(this);
        }
    }

**Comment by RobMastersToast** [comment]
Thanks @blackberry2016 and @guanpj. Good to know there's a more simple way to fix this, but for now I seem to have got it working using a custom AndroidInjector, as per @blackberry2016's example - although slightly tweaked. I'd say this issue can probably be closed now that there are a couple of viable workarounds?
