### ISSUE TITLE
小米6补丁可能生效后，会造成应用打开直接闪退。其他手机补丁生效后没有问题 TinkerApplicationLike cannot be cast to ApplicationLike

### ISSUE THREAD

**Issue by bjpftz** [Tencent/tinker#904]
异常类型：app运行时异常

手机型号：小米6

手机系统版本：Android7.1.1

tinker版本：1.9.6
gradle版本：3.0.1

是否使用热更新SDK：Bugly SDK

系统：Windows

错误产生原因，补丁可能生效后，会造成应用打开直接闪退。

其报错日志为

com.tencent.bugly.beta.tinker.TinkerApplicationLike cannot be cast to com.tencent.tinker.loader.app.ApplicationLike

TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed

**Comment by bjpftz** [comment]
大佬看到了，请劳驾看下是什么问题，谢谢啦

**Comment by xiaobaDev** [comment]
我遇到了和你一样的问题。情况是这样的
1：比如4.1.0的包有bug，我发了热修复。成功
2：我重新创建了4.1.0的apk包，覆盖安装。
3：打开新安装的包就会出现你这个问题。
结论：
新包更新版本号。线上是不会有这个问题的。

**Comment by tomystang** [comment]
已知问题了，Application和ApplicationLike发生内联导致的，下个版本会修复。

**Comment by tomystang** [comment]
请尝试1.9.14版本，如仍有问题，请补充log等细节后重开此issue。
