### ISSUE TITLE
想问下:补丁加载进入安全模式是什么原因

### ISSUE THREAD

**Issue by fanlelong** [Tencent/tinker#905]
想问下:补丁加载进入安全模式是什么原因

**Comment by tomystang** [comment]
在应用的ApplicationLike.onAttachBaseContext开始执行之前发生了3次或以上的crash就会触发tinker进入安全模式，也就是删除正在尝试加载的补丁，并且永久忽略对当前base包加载补丁的操作。要恢复补丁加载功能的话需要重新下发一个新的base包和对应的补丁。
