### ISSUE TITLE
问题：能不能打加固的补丁？

### ISSUE THREAD

**Issue by TangXiaoLv** [Tencent/tinker#91]

**Comment by tomystang** [comment]
加固的补丁，是指基准包和新包都加固过吗？
加固之后Dex很可能已经不是标准结构了（加了干扰指令、抹去了部分数据项、故意构造非法数据项等等），这样Tinker的DexDiff逻辑很可能会出错，所以暂时不建议对加固的Dex应用这套方案。

**Comment by TangXiaoLv** [comment]
@tomystang 如果线上包是加固的，基准包和新包都未加固，打出来的补丁对线上加固的包能起作用么？或者还是说需要用基准包和新包都加固过后打出的加固补丁才有效？

**Comment by tomystang** [comment]
这样也是不支持的。
线上包和本地基准包的角色是一样的，也就是说只有线上包和本地基础包二进制一致，打出的补丁才有意义。如果线上包是加固过，本地基准包未加固，这两个包的二进制肯定就不一致了。

**Comment by k-lam** [comment]
那微信是怎么兼顾tinker和加固呢？

**Comment by Drizzlezhang** [comment]
@tomystang 那如果说基准包和新包都未加固生成的补丁，可以给加固后的基准包使用么

**Comment by TangXiaoLv** [comment]
@Drizzlezhang 按上面说法看来是不行

**Comment by tomystang** [comment]
@k-lam 微信没有加固dex。

@Drizzlezhang 不行的，因为运行时读取到的基准包肯定是加固后的，这样编译时用未加固的两个包生成的patch就没有意义了。

@TangXiaoLv 嗯嗯，确实是不行的。

**Comment by shwenzhang** [comment]
对于明确需要加固的产品，我们这边计划提供qzone方式的一个回退实现

**Comment by kongnanlive** [comment]
@shwenzhang 刚刚试了下360手机助手的加固，确实无法应用补丁，但问题在于360这个不要脸的非要你加固后才可以发布，何解？

**Comment by kongnanlive** [comment]
@tomystang 微信没有加固是怎么通过360手机助手审核的？

**Comment by k-lam** [comment]
微信不加固dex，那怎么防破解呢？怎么做到安全呢？

**Comment by chenliuchun** [comment]
同问微信的同学

**Comment by ifinver** [comment]
同 @kongnanlive 的问题，我们项目也遇到了这个问题，怎么办啊- -

**Comment by ifinver** [comment]
就是360渠道强制要求加固，tinker就不能用了，怎么破..

**Comment by shwenzhang** [comment]
tinker这边后面会推出一种qzone插桩方案的回退版本，但是会导致性能损耗以及补丁包可能过大问题。若应用自己没有主观的加固需求，360市场可以不上，它会自动捉包更新的

**Comment by ifinver** [comment]
@shwenzhang 好的多谢~

**Comment by ovmarschen** [comment]
360市场可以不上+1

**Comment by 0kai** [comment]
@kongnanlive 我觉得360助手会求着微信上他们平台的吧

**Comment by shwenzhang** [comment]
@Okai. 我们是没有主动360市场的。

**Comment by Qiu800820** [comment]
tinker不是支持so更新么，   那么把基准包和新包都加固再用tinker命令进行BsDiff生成新的补丁包也不行么?  感觉360加固后的classes.dex都是一样的 只是so不同

**Comment by shwenzhang** [comment]
@TangXiaoLv please try with 1.7.0

**Comment by shwenzhang** [comment]
[是否支持加固](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#tinker%E6%98%AF%E5%90%A6%E5%85%BC%E5%AE%B9%E5%8A%A0%E5%9B%BA)， tinker的普通模式需要Dex的合成，它并不支持加固，一定要使用加固的app可以使用usePreGeneratedPatchDex模式。

**Comment by huyn** [comment]
版本1.7.3， usePreGeneratedPatchDex设置为true之后， 360加固亲测，patch成功，但是实际上没有效果

**Comment by shwenzhang** [comment]
@huyn 不修改mainActivity，之前测试过是没问题的

**Comment by huyn** [comment]
@shwenzhang MainActivity指的是LAUNCHER吗？我的更新逻辑是在LAUNCHER中启动的Activity当中

**Comment by shwenzhang** [comment]
对，文档里面就有说。因为360加固会提前加载LAUNCHER

**Comment by huyn** [comment]
@shwenzhang 
这是我的LAUNCHER 的onCreate方法
`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        startActivity(new Intent(this, PluginMainActivity.class));
        finish();
    }`
我要热更新的的部分在PluginMainActivity当中，为类绕过MainActivity，特意让它只做一个跳转
