### ISSUE TITLE
请问tinker可以给xposed插件打补丁吗？

### ISSUE THREAD

**Issue by moncat** [Tencent/tinker#922]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：如:魅蓝u20

手机系统版本：如:Android 6.0

tinker版本：如:1.9.1

gradle版本：如:3.3

是否使用热更新SDK： TinkerPatch

系统：如:window

堆栈/日志：
1. 开发的该app activity页面布局有问题，使用tinker打补丁可以修复
2.该app也是xposed的插件，xposed代码bug使用tinker打补丁修复（新增三行代码），但发现新增代码没有执行。

请问tinker可以给xposed插件打补丁吗？ 和上下文是否有关系。

**Comment by moncat** [comment]
SOS ， somebody help me

**Comment by tomystang** [comment]
不行的，xposed插件有自己的生命周期管理逻辑，入口和直接启动那个apk不同，所以tinker没法直接支持。我印象里记得Xposed也没有提供一个足够早的时机给插件自身做ClassLoader的hack，估计支持起来会有点困难哇。
