### ISSUE TITLE
多渠道有好多包，可以同时生成这些不同渠道包的补丁吗？

### ISSUE THREAD

**Issue by SolveBugs** [Tencent/tinker#94]
多渠道有好多个包，可以同时生成这些不同渠道包的补丁吗？

**Comment by shwenzhang** [comment]
建议不要使用flavor方式生成渠道包，这样补丁包太多了

**Comment by SolveBugs** [comment]
@shwenzhang  现在项目用的是就是gradle生成多渠道的，请问这种该怎么处理？

**Comment by shwenzhang** [comment]
正如文档所说可以采用插入manifest，chanel.ini，或者zip comment等方式。使用flavor会导致不同的渠道代码是不同的

**Comment by kongnanlive** [comment]
@SolveBugs 我推荐给你一个https://github.com/mcxiaoke/packer-ng-plugin

**Comment by shwenzhang** [comment]
look at the newly wiki
