### ISSUE TITLE
Too many classes in --main-dex-list, main dex capacity exceeded打包失败

### ISSUE THREAD

**Issue by android-notes** [Tencent/tinker#942]
tinker是不是把打了运行时注解的类全部打到了main dex里，使用默认打release包命令可以打包成功，开启thinker后一直打包失败，提示Too many classes in --main-dex-list, main dex capacity exceeded。我们用的gson+retrofit，看了下开启tinker打的包，好像只要用了SerializedName、GET、POST等注解的类全部打到了主dex中。maindexlist中一共有8000多个类，不开启tinker时只有800多个类，即使Applicationlike中没有任何代码的话依旧打包失败

**Comment by tomystang** [comment]
额，但是tinker的multidex规则里没写跟注解有关的条目哇。
不过tinker会把loader类都打进主dex里，你看下gradle里tinkerPatch块里配置的loader pattern是不是包含了gson和retrofit的类？

**Comment by android-notes** [comment]
没有包含gson和retrofit。只有这些

```
dex {
            /**
             * optional，default 'jar'
             * only can be 'raw' or 'jar'. for raw, we would keep its original format
             * for jar, we would repack dexes with zip format.
             * if you want to support below 14, you must use jar
             * or you want to save rom or check quicker, you can use raw mode also
             */
            dexMode = "jar"

            /**
             * necessary，default '[]'
             * what dexes in apk are expected to deal with tinkerPatch
             * it support * or ? pattern.
             */
            pattern = ["classes*.dex",
                       "assets/secondary-dex-?.jar"]
            /**
             * necessary，default '[]'
             * Warning, it is very very important, loader classes can't change with patch.
             * thus, they will be removed from patch dexes.
             * you must put the following class into main dex.
             * Simply, you should add your own application {@code tinker.sample.android.SampleApplication}
             * own tinkerLoader, and the classes you use in them
             *
             * 注意：
             * 1) 此处声明的是不能用 tinker 热修复的类
             * 2) 这里要将自定义Application 中的直接使用类填入
             *
             */
            loader = [
                    //use sample, let BaseBuildInfo unchangeable with tinker
                    "com.tencent.tinker.loader.*" // tinker 保留
            ]
        }


```

去掉了stetho，然后DefaultApplicationLike子类中除了调用构造方法外，不添加任何代码，勉强可以打包成功，但maindexlist中列出了7800多个类，反编译了下生成的apk，主dex有9.2MB，看了下里面有好多注解， 好像只要打了SerializedName、GET、POST，Metadata，Deprecated，等运行时注解的类全部打到了主dex中，另外好像所有kotlin的类都打到了主dex中。kotlin类好像都会自动添加@Metadata注解


这是  intermediates中manifest_keep.txt文件内容

```

# view AndroidManifest.xml #generated:81
-keep class com.xx.xxx.App { <init>(...); }//继承自TinkerApplication的Application


#tinker multidex keep patterns:
-keep public class * implements com.tencent.tinker.loader.app.ApplicationLifeCycle {
    <init>(...);
    void onBaseContextAttached(android.content.Context);
}

-keep public class * extends com.tencent.tinker.loader.TinkerLoader {
    <init>(...);
}

-keep public class * extends android.app.Application {
     <init>();
     void attachBaseContext(android.content.Context);
}

-keep class com.tencent.tinker.loader.TinkerTestAndroidNClassLoader {
    <init>(...);
}

#your dex.loader patterns here
-keep class com.tencent.tinker.loader.** {
    <init>(...);
}

-keep class com.xxx.xx.xx {//继承自TinkerApplication的Application
    <init>(...);
}


```

tinker multidex keep 文件
```
#tinker multidex keep patterns:
-keep public class * implements com.tencent.tinker.loader.app.ApplicationLifeCycle {
    <init>(...);
    void onBaseContextAttached(android.content.Context);
}

-keep public class * extends com.tencent.tinker.loader.TinkerLoader {
    <init>(...);
}

-keep public class * extends android.app.Application {
     <init>();
     void attachBaseContext(android.content.Context);
}

-keep class com.tencent.tinker.loader.TinkerTestAndroidNClassLoader {
    <init>(...);
}

#your dex.loader patterns here
-keep class com.tencent.tinker.loader.** {
    <init>(...);
}

-keep class com.xx.xxx.xxxxx {//继承自TinkerApplication的Application

    <init>(...);
}
```
@tomystang

**Comment by DoomTeam** [comment]
朋友，那这个bug解决了吗？我们也有相似的问题，项目使用了kotlin和Arouter，开启tinker后签名打包就会存在主dex太大的bug

**Comment by android-notes** [comment]
没解决，只是把stetho等这种线上包用不到的依赖去掉了，另外，like中通过class.forname(new String("com.xx.xxx.初始化类"))加载类初始化我们的业务代码，勉强打包成功，另外，Application的所有子类也会打到主dex中，Application子类依赖的类也会打到主dex中，只能通过class.forname(new String("com.xx.xxx.xx"))这种方式避免打到主dex中，直接使用class.forname("com.xx.xxx.xx")这种反射方式还是会打到主dex中。  
@DoomTeam

**Comment by paul1992li** [comment]
也遇到同样问题 tinker生成的multidexkeep.pro需要表明需要保留的类并不是很多 但是实际编译过程中multi-dex目录下的maindexlist.txt包括的数量却非常大，直接主dex溢出了
之前会去用第三方分包插件去处理这个问题 但是升级到AGP升级到3.0以后插件作者没有更新，感觉像是multidex的锅

**Comment by paul1992li** [comment]
@android-notes @DoomTeam @tomystang 
这个问题折磨了很久，两个方案： 1）是启动后通过classloader拿到所有启动的类(包括tinker依赖的所有类)生成maindexlist.txt(release通过mapping.txt处理下)然后配置dexoptions的additionalParameters指定用该文件生成主dex ； 2）换一个思路，在gradle编译流程生成maindexlist之后以及通过该文件生成主dex之前剔除启动不需要的类
我实际解决方案是第二个，直接把下面的语句加到:app下的build脚本
注意事项 ：1）我的APG版本3.1.4  multidex版本1.0.3，gradle wrapper 4.4/4.6，下面任务依赖和gradle版本相关，不同版本生成maindexlist.txt的任务名称不一样，有些是transformClassesWithMultidexlistForDebug/ transformClassesWithMultidexlistForRelease，早期版本是createDebugMainDexClassList/createReleaseMainDexClassList
2）如果进一步丰富下边处理流程的话，需要通过mapping文件处理混淆解决release版本的问题
3）:app目录下的qgame-dex-knife.txt内容包括下边这些内容，也可以包括自己app内启动用不到的组件view甚至activity等等
net/sourceforge/pinyin4j/
com/amitshekhar/
net/sqlcipher/
android/arch/persistence/room/
com/tencent/qqlive/
com/alibaba/
okhttp3/
com/github/mikephil/charting/
com/squareup/haha/
com/github/tony19/
org/jetbrains/anko/
kotlin/
com/squareup/
com/airbnb/
android/support/v
com/facebook/fresco/
com/facebook/stetho/
com/google/android/flexbox/
com/sixgod/pluginsdk/

//分包相关gradle task
tasks.whenTaskAdded { task ->
    android.applicationVariants.all { variant ->
        if (task.name == "transformClassesWithMultidexlistFor${variant.name.capitalize()}") {
            task.finalizedBy "generateNew${variant.name.capitalize()}MainDexClassList"
        }
    }
}

android.applicationVariants.all { variant ->
    task("generateNew${variant.name.capitalize()}MainDexClassList").doLast {
        //从主dex移除的类
        def dexKnifeList = []
        File dexKnifeFile = new File("${project.projectDir}/qgame-dex-knife.txt")
        println "${project.projectDir}/qgame-dex-knife.txt exist: ${dexKnifeFile.exists()} , size: ${dexKnifeList.size()}"
        if (dexKnifeFile.exists()) {
            dexKnifeFile.eachLine { line ->
                if (!line.isEmpty()) {
                    dexKnifeList.add(line.trim())
                }
            }
            dexKnifeList.unique()
        }
        dexKnifeList.each {
            println "qgame-dex-knife -->  knife-content[${dexKnifeList.indexOf(it)}]: ${it}"
        }
        //系统编译生成的主dex
        def mainDexList = []
        File mainDexFile = new File("${project.buildDir}/intermediates/multi-dex/${variant.dirName}/maindexlist.txt")
        println "${project.buildDir}/intermediates/multi-dex/${variant.dirName}/maindexlist.txt exist: ${mainDexFile.exists()}"
        if (mainDexFile.exists()) {
            mainDexFile.eachLine { line ->
                if (!line.isEmpty()) {
                    mainDexList.add(line.trim())
                }
            }
            mainDexList.unique()
            println "qgame-dex-knife -->  beforeKnife maindexlist size: ${mainDexList.size()}"
            if (!dexKnifeList.isEmpty()) {
                def newMainDexList = mainDexList.findResults { mainDexItem ->
                    def isKeepMainDexItem = true
                    for (dexKnifeItem in dexKnifeList) {
                        if (mainDexItem.contains(dexKnifeItem)) {
                            isKeepMainDexItem = false
                            break
                        }
                    }
                    if (isKeepMainDexItem) mainDexItem else null
                }
                if (newMainDexList.size() < mainDexList.size()) {
                    mainDexFile.delete()
                    mainDexFile.createNewFile()
                    mainDexFile.withWriterAppend { writer ->
                        newMainDexList.each {
                            writer << it << '\n'
                            writer.flush()
                        }
                    }
                }
                println "qgame-dex-knife -->  afterKnife maindexlist size: ${newMainDexList.size()}"
            }
        }
    }
}

**Comment by paul1992li** [comment]
@tomystang  针对APG3.0以上版本，TinkerMultiDexConfigTask里边有些依赖的任务发生了变更，目前看应该没什么影响

**Comment by android-notes** [comment]
不错，好像没问题。下次再打包失败时试试这个方案 @paul1992li

**Comment by zilicheOwns** [comment]
> 不错，好像没问题。下次再打包失败时试试这个方案 @paul1992li

我上个版本是1.9.8，升级到1.9.9。也出先这个问题。maindexlist中一共有10000多个类，1.9.8只有2000多类，加上了keepRuntimeAnnotatedClasses 也没啥效果，大佬们，知道1.9.9有什么改动导致的问题吗

**Comment by android-notes** [comment]
把这段代码  

  dexOptions {
        keepRuntimeAnnotatedClasses false
    } 

  加到
android{
}

中也不行，是不是加错位置了？  @zilicheOwns

**Comment by zilicheOwns** [comment]
> 把这段代码
> 
> dexOptions {
> keepRuntimeAnnotatedClasses false
> }
> 
> 加到
> android{
> }
> 
> 中也不行，是不是加错位置了？ @zilicheOwns

dexOptions {
        incremental true
        preDexLibraries false
        jumboMode true
        javaMaxHeapSize '4G'
        keepRuntimeAnnotatedClasses false
}
加了只减了300个类，应该还有其他原因导致的？

**Comment by weinierfei** [comment]
@paul1992li @android-notes  两位好,在升级tinker1.9.11的过程中,我也遇到了这个问题,试了一下'keepRuntimeAnnotatedClasses false'不好使;然后用paul1992li的脚本文件,发现在maindexlist.txt生成之前,编辑就挂了,根本执行不到从maindexlist中删除dex-knife的地方啊,请二位指导一下,谢啦

**Comment by forJrking** [comment]
如果适配了 Android P ，降级可以达到兼容，已经踩坑
        COMPILESDK = 27
        MINSDK = 16
        TARGETSDK = 27
        BUILDTOOLS = "27.0.3"
        SUPPORT = "27.1.0"

**Comment by weinierfei** [comment]
@forJrking 这个应该不是适配引起的吧  应该是新版AGP使用D8编译,没法禁用,导致原本的keepRuntimeAnnotatedClasses false失效,使用tinker的时候会爆出主dex爆炸;

**Comment by zysidea** [comment]
keepRuntimeAnnotatedClasses false 不管用  @android-notes

**Comment by yinshudi** [comment]
遇到了同样的问题，请问各位最后是怎么解决的

**Comment by alen252** [comment]
keepRuntimeAnnotatedClasses false 不管用。有终极解决方案吗？

**Comment by ManBali** [comment]
> @android-notes @DoomTeam @tomystang
> 
> ```
> 这个问题折磨了好几天，两个方案：   
>    1）是启动后通过classloader拿到所有启动的类(包括tinker依赖的所有类)生成maindexlist.txt(release通过mapping.txt处理下)然后配置dexoptions的additionalParameters指定用该文件生成主dex ；
>    2）换一个思路，在gradle编译流程生成maindexlist之后以及通过该文件生成主dex之前剔除启动不需要的类
> 我的解决方案是第二个，直接把下面的语句加到:app下的build脚本
> //分包相关gradle task
> tasks.whenTaskAdded { task ->
>     android.applicationVariants.all { variant ->
>         if (task.name == "transformClassesWithMultidexlistFor${variant.name.capitalize()}") {
>             task.finalizedBy "generateNew${variant.name.capitalize()}MainDexClassList"
>         }
>     }
> }
> 
> android.applicationVariants.all { variant ->
>     task("generateNew${variant.name.capitalize()}MainDexClassList").doLast {
>         //从主dex移除的列表
>         def dexKnifeList = []
>         File dexKnifeFile = new File("${project.projectDir}/qgame-dex-knife.txt")
>         println "${project.projectDir}/qgame-dex-knife.txt exist: ${dexKnifeFile.exists()} , size: ${dexKnifeList.size()}"
>         if (dexKnifeFile.exists()) {
>             dexKnifeFile.eachLine { line ->
>                 if (!line.isEmpty()) {
>                     dexKnifeList.add(line.trim())
>                 }
>             }
>             dexKnifeList.unique()
>         }
>         dexKnifeList.each {
>             println "qgame-dex-knife -->  knife-content[${dexKnifeList.indexOf(it)}]: ${it}"
>         }
>         //系统编译生成的maindexlist
>         def mainDexList = []
>         File mainDexFile = new File("${project.buildDir}/intermediates/multi-dex/${variant.dirName}/maindexlist.txt")
>         println "${project.buildDir}/intermediates/multi-dex/${variant.dirName}/maindexlist.txt exist: ${mainDexFile.exists()}"
>         if (mainDexFile.exists()) {
>             mainDexFile.eachLine { line ->
>                 if (!line.isEmpty()) {
>                     mainDexList.add(line.trim())
>                 }
>             }
>             mainDexList.unique()
>             println "qgame-dex-knife -->  beforeKnife maindexlist size: ${mainDexList.size()}"
>             if (!dexKnifeList.isEmpty()) {
>                 //从maindexlist移除掉移除列表可以匹配到的类
>                 def newMainDexList = mainDexList.findResults { mainDexItem ->
>                     def isKeepMainDexItem = true
>                     for (dexKnifeItem in dexKnifeList) {
>                         if (mainDexItem.contains(dexKnifeItem)) {
>                             isKeepMainDexItem = false
>                             break
>                         }
>                     }
>                     if (isKeepMainDexItem) mainDexItem else null
>                 }
>                 if (newMainDexList.size() < mainDexList.size()) {
>                     mainDexFile.delete()
>                     mainDexFile.createNewFile()
>                     mainDexFile.withWriterAppend { writer ->
>                         newMainDexList.each {
>                             writer << it << '\n'
>                             writer.flush()
>                         }
>                     }
>                 }
>                 println "qgame-dex-knife -->  afterKnife maindexlist size: ${newMainDexList.size()}"
>             }
>         }
>     }
> }
> 
> 注意事项 ：
>    1）我的APG版本3.1.4  multidex版本1.0.3，gradle wrapper 4.4/4.6，下面任务依赖和gradle版本相关，
> 不同版本生成maindexlist.txt的任务名称不一样，有些是transformClassesWithMultidexlistForDebug/ transformClassesWithMultidexlistForRelease，
> 早期版本是createDebugMainDexClassList/createReleaseMainDexClassList
>    2）如果进一步丰富下边处理流程的话，需要通过mapping文件处理混淆解决release版本的问题
>    3）:app目录下的qgame-dex-knife.txt内容包括下边这些内容，也可以包括自己app内启动用不到的类，view 、activity等等
> net/sourceforge/pinyin4j/
> com/amitshekhar/
> net/sqlcipher/
> android/arch/persistence/room/
> com/tencent/qqlive/
> com/alibaba/
> okhttp3/
> com/github/mikephil/charting/
> com/squareup/haha/
> com/github/tony19/
> org/jetbrains/anko/
> kotlin/
> com/squareup/
> com/airbnb/
> android/support/v
> com/facebook/fresco/
> com/facebook/stetho/
> com/google/android/flexbox/
> com/sixgod/pluginsdk/
> ```
> 
> 加上自己项目内可以移除的类，效果是类12k->5k, 方法110k ->50k，临时方案，比较简单，可以参考下

我这尝试使用你这方法，但是发现，最终还是将我不需要的类打到了 maindex里面。
我们使用的gradle=3.1.2 
compileSdkVersion=28
buildToolsVersion=27.0.3
AndroidStudio = 3.2.1 
默认开启了d8
