### ISSUE TITLE
tinker在升级gradle：3.2.0时，提示缺少annotationProcessor

### ISSUE THREAD

**Issue by wimvogt** [Tencent/tinker#949]
异常类型：app运行时异常

手机型号：One Plus A2001

手机系统版本：Android 6.1

tinker版本：1.9.1

gradle版本：3.2.0

是否使用热更新SDK：TinkerPatch SDK

系统：Mac

堆栈/日志：
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
  - tinker-android-anno-1.9.1.jar (com.tencent.tinker:tinker-android-anno:1.9.1)
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

根据官网配置，已经在所有模块的build.gradle中添加includeCompileClasspath true，但是还是提示此错误，提示缺少annotationProcessor，(tips：butterKnife有类似问题，添加了一个9.0.0-SNAPSHOT版本)

**Comment by zgmd** [comment]
同样的问题，求解答

**Comment by zgmd** [comment]
defaultConfig {
        //添加如下配置就OK了
        javaCompileOptions { annotationProcessorOptions { includeCompileClasspath = true } }
}
