### ISSUE TITLE
如果能够做成阿里百川hotfix那样的控制台就更好了

### ISSUE THREAD

**Issue by xiaoguxg** [Tencent/tinker#95]

**Comment by shwenzhang** [comment]
会有计划的，但是我要先调研清楚大家的核心需要是什么？想要得到一个怎么样的平台

**Comment by gushoubang** [comment]
控制起来比较方便就行。。。

**Comment by zzzhoukang** [comment]
1. 能够内测、灰度发布，全量发布；
2. 能够停止下发，回滚patch；
3. 能够监控patch load的一些情况；

@shwenzhang 非常期待能够推出Tinker的相关服务

**Comment by YeDaxia** [comment]
支持~

**Comment by kongnanlive** [comment]
@zzzhoukang 做到这个程度要收钱了🙄

**Comment by zzzhoukang** [comment]
@kongnanlive 付费是可接受的，特别是优质服务

**Comment by shwenzhang** [comment]
事实上，个人感觉对于企业服务，免费意味着免责。当然Tinker也还没确定怎么做这件事情，是否收费也言之过早

**Comment by parcool** [comment]
@zzzhoukang 同意。付费是可接受的，特别是优质服务

**Comment by 675915408** [comment]
同意付费企业版 支持！

**Comment by it90msart** [comment]
1.历史版本控制，查看修复基础和成功率
2.对crash的用户可以指定下发或者版本回滚
3.可以提供sdk包，对新包的修复，直接通过后台来下发，加载，统一管理。
4.对加固出现的问题可以提供微信的加固方式出来，统一管理，这样便于问题管理和跟踪

**Comment by voidZhao** [comment]
我觉得大家核心需要的肯定是足够详细的接入上的说明，付不付费倒是其次，足够好的东西，肯定有人买账的

**Comment by gushoubang** [comment]
就是自己找地方控制版本什么的比较麻烦

**Comment by yunair** [comment]
1. 监测
2. 对特定用户发布
3. 灰度和全量

**Comment by yql86** [comment]
今天按照sample把tinker集成到自己的项目中，感觉的确是个好东西。 想向大神了解下，在微信中tinker是如何应用的。与服务端交互下载补丁包的接口是如何定义的？如何避免重复下载，如何同一个版本进行多次补丁下载，希望把服务器pull的部分开放出来。

**Comment by weinierfei** [comment]
请问控制台有木有列入计划?

**Comment by caik13** [comment]
做这样一个平台是好事，但是希望收费的是这个平台自己平台推出的各种服务，而tinker还是tinker

**Comment by shwenzhang** [comment]
@caik13 server这边我个人没有太多的时间，主要是让朋友帮忙做的，代码也会放到单独的repo。我主要是帮忙把控功能与质量

**Comment by typ0520** [comment]
我们团队做了一个管理平台，在官方的出来前可以在自己公司环境部署一个先用着，https://github.com/baidao/tinker-manager

**Comment by gordonpro** [comment]
如果配合腾讯加固整合在一起，支持加固后依然能修复那就好了

**Comment by gordonpro** [comment]
目前腾讯Bugly已经加入控制台 https://bugly.qq.com/docs/user-guide/instruction-manual-android-hotfix/
