### ISSUE TITLE
问题：Didn't find class "com.tencent.tinker.entry.DefaultApplicationLike"

### ISSUE THREAD

**Issue by VeryCure** [Tencent/tinker#953]
## 现在打包出现问题如下：
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/entry/DefaultApplicationLike;
        at com.tencent.bugly.beta.Beta.installTinker(BUGLY:969)
导致APP直接无法启动

异常类型：app运行时异常
手机型号：一加6

手机系统版本：9.0

tinker版本：1.9.6

gradle版本：3.0.1

是否使用热更新SDK： 

系统：Window

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。

**Comment by tomystang** [comment]
> tinker版本：1.9.6

如果bugly用了最新版的话，tinker lib的版本要更新到1.9.9才行

**Comment by luoyou592** [comment]
怎么没有做到兼容呢，要不是在这里看到估计要把项目给整烂了哈

**Comment by luoyou592** [comment]
更新到1.9.9，5.0以下的tinker分包不管用   multiDexKeepProguard file("./tinker_multidexkeep.pro") //keep specific classes using proguard syntax
会报出Didn't find class "xxx" on path: DexPathList

**Comment by VeryCure** [comment]
@tomystang 可以了，谢谢！希望在官方文档中也做下更新，避免他人也遇到这种情况。

**Comment by luoyou592** [comment]
@VeryCure 你5.0以下手机运行有没有报这个错呢？Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed

**Comment by tomystang** [comment]
@luoyou592 
正在看了，我这边没构造出来，还在查原因。

**Comment by luoyou592** [comment]
我用之前版本重新构造然后修改下那个分包文件的路径再换成最新构造。现在不报错了
com.tencent.tinker.entry.ApplicationLifeCycle

**Comment by tomystang** [comment]
诡异了，那估计还是生成的multidex规则有问题

**Comment by dengbing0907** [comment]
我能问下解决了吗？碰到同样的问题了
