### ISSUE TITLE
项目自定义的Application类已经继承了一个第三方的Application类，如何接入到tinker中？

### ISSUE THREAD

**Issue by wonghoman** [Tencent/tinker#98]
项目自定义的Application类已经继承了一个第三方的Application类，接入tinker还要继承DefaultApplicationLike类，但java不可能多继承，请问，这种情况下如何接入到tinker中？

**Comment by shwenzhang** [comment]
#66

**Comment by gaoxuxu** [comment]
使用ApplicationLike代理

**Comment by wonghoman** [comment]
非常感谢作者的快速回复！
