### ISSUE TITLE
关于自定义Application 需要实现接口的问题.

### ISSUE THREAD

**Issue by hlgithub369** [Tencent/tinker#983]
![image](https://user-images.githubusercontent.com/15081751/49366458-5b73d000-f724-11e8-8328-a84d2367f7c5.png)
你好.我自定义我已经把原来继承Application改成了继承DefaultApplicationLike

运行也没有问题.但是.我项目中还集成了.dagger2.调用的时候他说需要application实现自己的方法.
但是那个application是kinker自己生成的..有没有办法进行实现接口的修改.

**Comment by tomystang** [comment]
这个tinker自己暂时还不支持哇，不过bugly的热补丁sdk通过在tinker的基础上反射替换Application类的方式支持了，可以先试试看。
