### ISSUE TITLE
tinker与9instant run 的兼容问题

### ISSUE THREAD

**Issue by dede1314** [Tencent/tinker#988]
通过集成ApplicatinLike的方式接入的tinker， 因为开发阶段想使用instant run.
在tinker.gradle 文件做了如下改动：
`tinkerSupport {
enable = false;

overrideTinkerPatchConfiguration = false
}

tinkerPatch {
tinkerEnable = false
.....
buildConfig{
tinkerId = "1.0.1-base"
}
}`

开启instant run, 但是编译速度并没有改善,和平时一样，请问是tinker关闭的方式不对吗？
通过bugly集成的方式接入的tinker,版本为1.3.4。

**Comment by tomystang** [comment]
你需要把包括apply tinker plugin的部分一起屏蔽掉才行，不然instant run还是不会生效的。
