### ISSUE TITLE
QQ群问题：CRC32(第12个梅森素数)

### ISSUE THREAD

**Issue by SwiftyWang** [Tencent/tinker#989]
答案是什么 输入A359519F或者 0xA359519F都不对。。

**Comment by tomUp** [comment]
ASCII：**0xA359519F**
HEX：**0x8B34C149**

试过了去掉0x都不行，有答案的@一下。

**Comment by docwei2050** [comment]
我也不知道

**Comment by tomUp** [comment]
A359519F
就是这个密码，多试几次吧
