### ISSUE TITLE
TinkerPatchService的静态成员upgradePatchProcessor 和 repairPatchProcessor都是在主进程里赋值的

### ISSUE THREAD

**Issue by suang** [Tencent/tinker#99]
然后在patch进程里使用，这个不太合理吧。 这2个静态成员主进程和patch进程都有自己的备份，属于不同的进程空间，原则上是不能使用的。 没挂是系统使用了copy-on-write的策略？

**Comment by shwenzhang** [comment]
呃呃呃，这个是每个进程都有的

**Comment by suang** [comment]
虽然在主进程里设置了这2个变量，但是主进程里并没有用到他们。

**Comment by shwenzhang** [comment]
没用到不会有问题啊
